"""§11.13.5.Z2AF LF-09 blocker-DAG re-adjudication persist.

Docs/governance invariants only. Persists the already-completed
read-only LF-09 adjudication as COMPLETE with unchanged DAG topology.
Does not start LF-10, does not close LIVE_FLATTEN_PROVABILITY or Face
Value, does not treat the persist as admissible productive evidence,
and does not submit orders, call OKX, fund, open a position, or unlock
Canary.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MASTER_RUNBOOK = REPO_ROOT / "docs" / "runbooks" / "canonical" / "PEAK_TRADE_MASTER_RUNBOOK.md"
MAP_OF_TRUTH = REPO_ROOT / "docs" / "governance" / "PEAK_TRADE_MAP_OF_TRUTH.md"

Z2AF_HEADING = "### 11.13.5.Z2AF LF-09 blocker-DAG re-adjudication persist"
Z2AE_HEADING = "### 11.13.5.Z2AE LF-08 LIVE_FLATTEN_PROVABILITY re-adjudication persist"
Z2AD_HEADING = "### 11.13.5.Z2AD LF-07 productive reachability adjudication persist"
Z2AC_HEADING = "### 11.13.5.Z2AC LF-06 venue semantics evidence persist"
Z2AB_HEADING = "### 11.13.5.Z2AB Productive runtime proof is not pre-submit admissible"
Z2AA_HEADING = "### 11.13.5.Z2AA Earliest Z2Y safety dependency is not statically provable"
NEXT_POINTER = (
    "OWNER_GO_REQUIRED_SEPARATE_FOR_ANY_NEXT_OPERATIONAL_ACTION_NOT_"
    "AUTHORIZED_BY_THIS_PERSIST_LF09_COMPLETE_DAG_UNCHANGED_LIVE_FLATTEN_"
    "UNPROVEN_FACE_VALUE_CONFLICT_PARALLEL_NUMERIC_ROOT_PRODUCTIVE_RUNTIME_"
    "PROOF_NOT_ADMISSIBLE_NO_LF10_NO_FLATTEN_CONTINUATION_NO_ORDER_NO_"
    "ALLOWLIST_CANARY_NOT_AUTHORIZED_SUPPORT_CONTACT_NOT_AUTHORIZED"
)
CONSUMED_Z2AE_POINTER = (
    "OWNER_GO_REQUIRED_SEPARATE_FOR_ANY_LF09_OR_FLATTEN_CONTINUATION_NOT_"
    "AUTHORIZED_BY_THIS_PERSIST_LF08_B_LIVE_FLATTEN_UNPROVEN_IMPLEMENTED_"
    "PLUS_OFFLINE_TESTED_IS_NOT_PRODUCTIVE_PROOF_PRODUCTIVE_REACHABILITY_"
    "NOT_ADMISSIBLE_NO_NEW_ADMISSIBLE_EVIDENCE_OVERSHOOT_FLIP_RACE_UNPROVEN_"
    "FAIL_CLOSED_IS_NON_PROOF_GATE_4_GATE_6_FAIL_GATE_8_UNINSTANTIABLE_NO_"
    "RUNTIME_NO_WIRING_NO_ORDER_NO_ALLOWLIST_CANARY_NOT_AUTHORIZED_SUPPORT_"
    "CONTACT_NOT_AUTHORIZED"
)
OWNER_GO = "LF_09_SSOT_PERSIST_ONLY"
BASELINE_SHA = "d384b5e9c87909bb131033dd6be3e8001e70cbee"


def _read(path: Path) -> str:
    assert path.is_file(), f"missing canonical path: {path}"
    return path.read_text(encoding="utf-8")


def _z2af_section(text: str) -> str:
    start = text.find(Z2AF_HEADING)
    assert start >= 0, "missing §11.13.5.Z2AF heading"
    end = text.find("## 11.14 Live order and economic evidence ladder", start)
    assert end > start, "missing §11.14 boundary after Z2AF"
    return text[start:end]


def test_z2af_heading_is_unique_and_follows_z2ae() -> None:
    text = _read(MASTER_RUNBOOK)
    assert text.count(Z2AF_HEADING) == 1
    z2aa = text.find(Z2AA_HEADING)
    z2ab = text.find(Z2AB_HEADING)
    z2ac = text.find(Z2AC_HEADING)
    z2ad = text.find(Z2AD_HEADING)
    z2ae = text.find(Z2AE_HEADING)
    z2af = text.find(Z2AF_HEADING)
    ladder = text.find("## 11.14 Live order and economic evidence ladder")
    assert 0 <= z2aa < z2ab < z2ac < z2ad < z2ae < z2af < ladder


def test_z2af_docs_bind_lf09_complete_without_runtime_or_lf10() -> None:
    section = _z2af_section(_read(MASTER_RUNBOOK))
    required = (
        "AUTHORIZED_SCOPE=LF_09_SSOT_PERSIST_ONLY",
        f"OWNER_GO={OWNER_GO}",
        "OWNER_GO_STATUS=CONSUMED",
        f"BASELINE_ORIGIN_MAIN_SHA={BASELINE_SHA}",
        "LAST_CANONICALLY_CLOSED_STEP_BEFORE_WRITE=LF_08",
        "LAST_CANONICALLY_CLOSED_STEP=LF_09",
        "LF_08_ADJUDICATION=B",
        "LF_09_READ_ONLY_ADJUDICATION=COMPLETE",
        "LF_09_BLOCKER_DAG_RE_ADJUDICATION=COMPLETE",
        "BLOCKER_DAG_CHANGED=false",
        "LF_08_DID_NOT_CLOSE_LIVE_FLATTEN_PROVABILITY=true",
        "DAG_TOPOLOGY_UNCHANGED=true",
        "EARLIEST_EXECUTION_SAFETY_BLOCKER=LIVE_FLATTEN_PROVABILITY",
        "EARLIEST_NUMERIC_SAFETY_BLOCKER=FACE_VALUE_CONFLICT",
        "PARALLEL_NUMERIC_ROOT=FACE_VALUE_AUTHORITY_CONFLICT",
        "FACE_VALUE_AUTHORITY=CONFLICTED",
        "FACE_VALUE_CONFLICT_STATUS=UNRESOLVED",
        "USD_USDC_OPERATOR=UNPROVEN",
        "COVER_USDC=UNINSTANTIATED",
        "COVER_USDC_STATUS=UNINSTANTIATED",
        "RULE_C=UNPROVEN",
        "RULE_C_STATUS=UNPROVEN",
        "FUNDING=UNSATISFIED_NUMERIC_NONE",
        "FUNDING_PREREQUISITE=UNSATISFIED",
        "NUMERIC_FUNDING_AMOUNT=NONE",
        "ENTRY_WORST_CASE_LOSS=UNINSTANTIABLE",
        "FLATTEN_WORST_CASE_LOSS=UNINSTANTIABLE",
        "PRODUCTIVE_REACHABILITY=NOT_ADMISSIBLE",
        "PRODUCTIVE_REACHABILITY_ADMISSIBLE=false",
        "FILL_DETERMINISM=UNPROVEN",
        "CANARY_ADMISSIBILITY=NOT_ADMISSIBLE",
        "NO_BLOCKER_CLOSED_BY_LF09=true",
        "NEW_ADMISSIBLE_EVIDENCE_SINCE_LF_08=false",
        "NEW_ADMISSIBLE_PRODUCTIVE_EVIDENCE=false",
        "DOCS_PERSIST_IS_NOT_ADMISSIBLE_PRODUCTIVE_EVIDENCE=true",
        "IMPLEMENTED_PLUS_OFFLINE_TESTED_IS_NOT_PRODUCTIVE_PROOF=true",
        "LF_06_OVERALL_ADJUDICATION=NOT_PASS",
        "LF_07_ADJUDICATION=B",
        "MECHANISM_IMPLEMENTED=PARTIAL_OFFLINE_ONLY",
        "VENUE_SEMANTICS_FULLY_PROVEN=false",
        "FLATTEN_RUNTIME_WIRING_PRESENT=false",
        "FLATTEN_RUNTIME_REACHABLE_TODAY=false",
        "EXISTING_EXECUTE_PATH_CAN_REACH_FLATTEN=false",
        "FAIL_CLOSED_NEUTRALIZES_UNPROVEN_VENUE_SEMANTICS=false",
        "FAIL_CLOSED_TODAY_IS_NON_REACHABILITY_NOT_VENUE_SAFETY_PROOF=true",
        "OFFLINE_TEST_IS_NOT_PRODUCTIVE_VENUE_PROOF=true",
        "CLOSE_POSITION_IF_ANY_IS_NOT_FLATTEN_AND_NOT_ACTIVATED=true",
        "MARKET_CLOSE_IS_NOT_AN_ALLOWED_SUBSTITUTE=true",
        "OVERSHOOT_PROTECTION_STATUS=UNPROVEN",
        "ZERO_CROSS_FLIP_PROTECTION_STATUS=UNPROVEN",
        "RACE_SHRINK_BEHAVIOR_STATUS=UNPROVEN",
        "GATE_4_FLATTEN_CAPABILITY_REMAINS=FAIL",
        "GATE_5_PRICE_BOUND_FOR_ENTRY_REMAINS=FAIL",
        "GATE_6_PRICE_BOUND_FOR_FLATTEN_REMAINS=FAIL",
        "GATE_7_FILL_STATE_MACHINE_REMAINS=UNPROVEN",
        "GATE_8_WORST_CASE_LOSS_BOUND=UNINSTANTIABLE",
        "FLATTEN_PRICE_POLICY_OPERATIONALLY_USABLE=false",
        "RUNTIME_REACHABLE=false",
        "LIFECYCLE_FLATTEN_RUNTIME_REACHABLE=false",
        "LIVE_FLATTEN_PROVABILITY=UNPROVEN",
        "LIVE_FLATTEN_PROVABILITY_REMAINS=UNPROVEN_HARD_STOP",
        "FLATTEN_SUBMIT_REACHABLE=false",
        "CLOSE_POSITION_ENDPOINT_ALLOWLISTED=false",
        "LF_10_AUTHORIZED=false",
        "LF_10_STARTED=false",
        "NO_LF10_ANALYSIS=true",
        "NO_LF10_IMPLEMENTATION=true",
        "NO_RUNTIME_CODE_CHANGE=true",
        "NO_FLATTEN_TRANSPORT_BINDING=true",
        "NO_PRICE_POLICY_CHANGE=true",
        "NO_RUNTIME_WIRING=true",
        "NO_ALLOWLIST_EXPANSION=true",
        "NO_CLOSE_POSITION_ENDPOINT=true",
        "NO_MARKET_ORDER_ACTIVATION=true",
        "RUNTIME_ACTIVATION_EXECUTED=false",
        "CANARY_EXECUTE_EXECUTED=false",
        "NETWORK_MUTATION=none",
        "NETWORK_TRADING_MUTATION=none",
        "Z2AB_PRODUCTIVE_RUNTIME_PROOF_ADMISSIBILITY_REMAINS=C",
        "Z2Y_AUTHORIZABILITY_ADJUDICATION_REMAINS=B",
        "PRODUCTIVE_RUNTIME_PROOF_ADMISSIBLE=false",
        "ORDER_SUBMIT_AUTHORIZED=false",
        "FILLED_POSITION_DERIVED_RUNTIME_AUTHORIZED=false",
        "FUTURE_RUNTIME_PROTOCOL_DOCUMENTED=false",
        "NEW_EVIDENCE_CLOSES_Z2Y_SAFETY_DEPENDENCY=false",
        "NEW_EVIDENCE_CHANGES_RUNTIME_AUTHORIZATION=false",
        "NO_POST=true",
        "NO_OKX_API_CALL=true",
        "NO_USD_EQUALS_USDC=true",
        "USD_EQUALS_USDC_ASSUMED=false",
        "LIVE_AUTHORIZED=false",
        "TESTNET_AUTHORIZED=false",
        "CANARY_AUTHORIZED=false",
        "SUPPORT_CONTACT_AUTHORIZED=false",
        "ALLOWLIST_EXPANSION_AUTHORIZED=false",
        "NO_CAPABILITY_ADVANCEMENT=true",
        "NEXT_OWNER_AUTHORIZATION_REQUIRED=SEPARATE_OWNER_GO_REQUIRED_LF10_NOT_AUTHORIZED_BY_THIS_PERSIST",
        "HARD_STOP_AFTER_THIS_TASK=true",
        f"CANONICAL_NEXT_STEP={NEXT_POINTER}",
        "EARLIEST_UNRESOLVED_DEPENDENCY=LIVE_FLATTEN_PROVABILITY",
    )
    for marker in required:
        assert marker in section, f"missing Z2AF marker: {marker}"
    forbidden = (
        "\nLIVE_AUTHORIZED=true\n",
        "\nTESTNET_AUTHORIZED=true\n",
        "\nLF_10_AUTHORIZED=true\n",
        "\nLF_10_STARTED=true\n",
        "\nRUNTIME_REACHABLE=true\n",
        "\nLIFECYCLE_FLATTEN_RUNTIME_REACHABLE=true\n",
        "\nFLATTEN_RUNTIME_REACHABLE_TODAY=true\n",
        "\nEXISTING_EXECUTE_PATH_CAN_REACH_FLATTEN=true\n",
        "\nFAIL_CLOSED_NEUTRALIZES_UNPROVEN_VENUE_SEMANTICS=true\n",
        "\nFLATTEN_PRICE_POLICY_OPERATIONALLY_USABLE=true\n",
        "\nPRODUCTIVE_REACHABILITY_ADMISSIBLE=true\n",
        "\nPRODUCTIVE_RUNTIME_PROOF_AVAILABLE=true\n",
        "\nNEW_ADMISSIBLE_EVIDENCE_SINCE_LF_08=true\n",
        "\nNEW_ADMISSIBLE_PRODUCTIVE_EVIDENCE=true\n",
        "\nBLOCKER_DAG_CHANGED=true\n",
        "\nDOCS_PERSIST_IS_NOT_ADMISSIBLE_PRODUCTIVE_EVIDENCE=false\n",
        "\nIMPLEMENTED_PLUS_OFFLINE_TESTED_IS_NOT_PRODUCTIVE_PROOF=false\n",
        "\nVENUE_SEMANTICS_FULLY_PROVEN=true\n",
        "\nLF_08_ADJUDICATION=A\n",
        "\nLF_08_ADJUDICATION=C\n",
        "\nLF_07_ADJUDICATION=A\n",
        "\nLF_06_OVERALL_ADJUDICATION=PASS\n",
        "\nLF_06_STATUS=PASS\n",
        "\nLIVE_FLATTEN_PROVABILITY=PROVEN\n",
        "\nOVERSHOOT_PROTECTION_STATUS=PROVEN\n",
        "\nZERO_CROSS_FLIP_PROTECTION_STATUS=PROVEN\n",
        "\nRACE_SHRINK_BEHAVIOR_STATUS=PROVEN\n",
        "\nGATE_4_FLATTEN_CAPABILITY_REMAINS=PASS\n",
        "\nGATE_6_PRICE_BOUND_FOR_FLATTEN_REMAINS=PASS\n",
        "\nGATE_8_WORST_CASE_LOSS_BOUND=INSTANTIABLE\n",
        "\nPRODUCTIVE_RUNTIME_PROOF_ADMISSIBLE=true\n",
        "\nCANARY_ADMISSIBILITY=ADMISSIBLE\n",
        "\nFACE_VALUE_AUTHORITY=RESOLVED\n",
        "\nCOVER_USDC_STATUS=INSTANTIATED\n",
        "\nRULE_C_STATUS=PROVEN\n",
        "\nUSD_EQUALS_USDC_ASSUMED=true\n",
        "\nNO_USD_EQUALS_USDC=false\n",
        "\nORDER_SUBMIT_AUTHORIZED=true\n",
        "\nFILLED_POSITION_DERIVED_RUNTIME_AUTHORIZED=true\n",
        "\nFUTURE_RUNTIME_PROTOCOL_DOCUMENTED=true\n",
        "\nNEW_EVIDENCE_CLOSES_Z2Y_SAFETY_DEPENDENCY=true\n",
        "\nNEW_EVIDENCE_CHANGES_RUNTIME_AUTHORIZATION=true\n",
        "\nNO_ALLOWLIST_EXPANSION=false\n",
        "\nOKX_API_CALL_PERFORMED=true\n",
        "\nORDER_SUBMITTED=true\n",
        "\nFUNDING_PERFORMED=true\n",
        "\nCANARY_AUTHORIZED=true\n",
        "\nSUPPORT_CONTACT_AUTHORIZED=true\n",
        "\nALLOWLIST_EXPANSION_AUTHORIZED=true\n",
        "\nCLOSE_POSITION_ENDPOINT_ALLOWLISTED=true\n",
        "\nFLATTEN_SUBMIT_REACHABLE=true\n",
        "\nRUNTIME_ACTIVATION_EXECUTED=true\n",
        "\nCANARY_EXECUTE_EXECUTED=true\n",
    )
    for marker in forbidden:
        assert marker not in section, f"forbidden Z2AF marker present: {marker!r}"


def test_z2af_map_of_truth_navigation_pointer_matches_runbook() -> None:
    mot = _read(MAP_OF_TRUTH)
    assert "THIS_DOCUMENT_DEFINES_NO_SEMANTICS=true" in mot
    assert "THIS_DOCUMENT_IS_NOT_A_SECOND_SSOT=true" in mot
    assert "§11.13.5.Z2AF |" in mot
    assert f"NEXT_CANONICAL_STEP_POINTER={NEXT_POINTER}" in mot
    assert f"NEXT_CANONICAL_STEP_POINTER={CONSUMED_Z2AE_POINTER}\n" not in mot
    assert "historical next pointer superseded by §11.13.5.Z2AF" in mot
    assert "LF_09_READ_ONLY_ADJUDICATION=COMPLETE" in mot
    assert "BLOCKER_DAG_CHANGED=false" in mot
    assert "LF_08_DID_NOT_CLOSE_LIVE_FLATTEN_PROVABILITY=true" in mot
    assert "LIVE_FLATTEN_PROVABILITY=UNPROVEN" in mot
    assert "FACE_VALUE_AUTHORITY=CONFLICTED" in mot
    assert "PARALLEL_NUMERIC_ROOT=FACE_VALUE_AUTHORITY_CONFLICT" in mot
    assert "RULE_C_STATUS=UNPROVEN" in mot
    assert "USD_USDC_OPERATOR=UNPROVEN" in mot
    assert "COVER_USDC_STATUS=UNINSTANTIATED" in mot
    assert "FUNDING=UNSATISFIED_NUMERIC_NONE" in mot
    assert "ENTRY_WORST_CASE_LOSS=UNINSTANTIABLE" in mot
    assert "FLATTEN_WORST_CASE_LOSS=UNINSTANTIABLE" in mot
    assert "PRODUCTIVE_REACHABILITY=NOT_ADMISSIBLE" in mot
    assert "CANARY_ADMISSIBILITY=NOT_ADMISSIBLE" in mot
    assert "PRODUCTIVE_RUNTIME_PROOF_ADMISSIBLE=false" in mot
    assert "NEW_ADMISSIBLE_PRODUCTIVE_EVIDENCE=false" in mot
    assert "LAST_CANONICALLY_CLOSED_STEP=LF_09" in mot
    assert "LF_10_AUTHORIZED=false" in mot
    assert "LF_10_STARTED=false" in mot
    assert "LIVE_AUTHORIZED=false" in mot
    assert (
        "FOR_ANY_LF09_OR_FLATTEN_CONTINUATION"
        not in mot.split("NEXT_CANONICAL_STEP_POINTER=", 1)[1].split("\n", 1)[0]
    )
