"""CLI contract tests for scripts/ops/check_requirements_synced_with_uv.sh."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "ops" / "check_requirements_synced_with_uv.sh"

_REQ_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv export --format requirements.txt --all-extras --all-groups --locked "
    "--no-hashes -o {target}\n"
)


def _write_requirements(fake_repo: Path, content: str) -> None:
    (fake_repo / "requirements.txt").write_text(content, encoding="utf-8")


def _install_uv_stub(fake_repo: Path, exported_content: str, args_log: Path) -> Path:
    uv_bin_dir = fake_repo / "bin"
    uv_bin_dir.mkdir(parents=True, exist_ok=True)
    uv_stub = uv_bin_dir / "uv"
    script = f"""#!/usr/bin/env bash
set -euo pipefail

printf '%s\\n' "$@" > "{args_log}"
out=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -o)
      out="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

if [[ -z "$out" ]]; then
  echo "missing -o" >&2
  exit 9
fi

cat <<'EOF' > "$out"
{exported_content}EOF
"""
    uv_stub.write_text(script, encoding="utf-8")
    uv_stub.chmod(0o755)
    return uv_bin_dir


def _run(fake_repo: Path, *, uv_bin_dir: Path | None) -> subprocess.CompletedProcess[str]:
    env = dict(os.environ)
    if uv_bin_dir is None:
        empty_path = fake_repo / "empty-path"
        empty_path.mkdir(parents=True, exist_ok=True)
        # Keep core shell utilities available, but ensure no real uv is found.
        env["PATH"] = f"{empty_path}{os.pathsep}/usr/bin{os.pathsep}/bin"
    else:
        env["PATH"] = f"{uv_bin_dir}{os.pathsep}{env.get('PATH', '')}"
    return subprocess.run(
        ["bash", str(SCRIPT)],
        cwd=fake_repo,
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )


def test_fails_with_exit_1_when_uv_is_missing(tmp_path: Path) -> None:
    _write_requirements(
        tmp_path,
        _REQ_HEADER.format(target="requirements.txt") + "alpha==1.0.0\n",
    )
    p = _run(tmp_path, uv_bin_dir=None)
    assert p.returncode == 1
    assert p.stdout.strip() == "❌ uv not found. Install uv first."
    assert p.stderr == ""


def test_passes_when_requirements_match_after_line2_normalization(tmp_path: Path) -> None:
    args_log = tmp_path / "uv-args.log"
    exported = _REQ_HEADER.format(target="/tmp/generated-by-stub.txt") + "alpha==1.0.0\n"
    uv_bin_dir = _install_uv_stub(tmp_path, exported, args_log)
    _write_requirements(
        tmp_path,
        _REQ_HEADER.format(target="requirements.txt") + "alpha==1.0.0\n",
    )

    p = _run(tmp_path, uv_bin_dir=uv_bin_dir)

    assert p.returncode == 0
    assert "✅ requirements.txt matches uv.lock export." in p.stdout
    assert p.stderr == ""

    logged_args = args_log.read_text(encoding="utf-8").splitlines()
    assert logged_args == [
        "export",
        "--format",
        "requirements.txt",
        "--all-extras",
        "--all-groups",
        "--locked",
        "--no-hashes",
        "-o",
        logged_args[-1],
    ]


def test_fails_with_diff_stdout_when_requirements_drift(tmp_path: Path) -> None:
    args_log = tmp_path / "uv-args.log"
    exported = _REQ_HEADER.format(target="/tmp/generated-by-stub.txt") + "alpha==1.0.0\n"
    uv_bin_dir = _install_uv_stub(tmp_path, exported, args_log)
    _write_requirements(
        tmp_path,
        _REQ_HEADER.format(target="requirements.txt") + "beta==2.0.0\n",
    )

    p = _run(tmp_path, uv_bin_dir=uv_bin_dir)

    assert p.returncode == 1
    assert "--- " in p.stdout
    assert "+++ " in p.stdout
    assert "-beta==2.0.0" in p.stdout
    assert "+alpha==1.0.0" in p.stdout
    assert "✅ requirements.txt matches uv.lock export." not in p.stdout
    assert p.stderr == ""
