"""§11.13.5.Z2AC LF-06 venue semantics evidence persist.

Docs/governance invariants only. Persists the already-completed
read-only LF-06 adjudication as NOT_PASS. Does not start LF-07, does
not prove overshoot/flip/race, does not make flatten runtime-reachable,
and does not submit orders, call OKX, fund, open a position, or unlock
Canary.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MASTER_RUNBOOK = REPO_ROOT / "docs" / "runbooks" / "canonical" / "PEAK_TRADE_MASTER_RUNBOOK.md"
MAP_OF_TRUTH = REPO_ROOT / "docs" / "governance" / "PEAK_TRADE_MAP_OF_TRUTH.md"

Z2AC_HEADING = "### 11.13.5.Z2AC LF-06 venue semantics evidence persist"
Z2AB_HEADING = "### 11.13.5.Z2AB Productive runtime proof is not pre-submit admissible"
Z2AA_HEADING = "### 11.13.5.Z2AA Earliest Z2Y safety dependency is not statically provable"
NEXT_POINTER = (
    "OWNER_GO_REQUIRED_SEPARATE_TO_ADJUDICATE_ANY_LF07_OR_FLATTEN_CONTINUATION_"
    "NOT_AUTHORIZED_BY_THIS_PERSIST_LF06_NOT_PASS_OVERSHOOT_FLIP_RACE_UNPROVEN_"
    "WIRE_TYPE_PRODUCTIVE_UNPROVEN_NO_RUNTIME_NO_ORDER_NO_ALLOWLIST_LIVE_"
    "FLATTEN_UNPROVEN_CANARY_NOT_AUTHORIZED_SUPPORT_CONTACT_NOT_AUTHORIZED"
)
CONSUMED_Z2AB_POINTER = (
    "OWNER_GO_REQUIRED_SEPARATE_BECAUSE_PRODUCTIVE_RUNTIME_PROOF_NOT_ADMISSIBLE_"
    "PRE_SUBMIT_LOSS_BOUND_UNINSTANTIABLE_LIMIT_REDUCEONLY_FLATTEN_NOT_"
    "DETERMINISTIC_REDUCEONLY_ABSENT_FROM_CANARY_PAYLOAD_CLOSE_POSITION_NOT_"
    "ALLOWLISTED_FACE_VALUE_UNRESOLVED_COVER_USDC_UNINSTANTIATED_FUNDING_"
    "PREREQUISITE_UNSATISFIED_FILL_DETERMINISM_UNPROVEN_RULE_C_UNPROVEN_NO_"
    "ORDER_NO_POSITION_NO_FUNDING_NO_ALLOWLIST_EXPANSION_CANARY_NOT_"
    "AUTHORIZED_SUPPORT_CONTACT_NOT_AUTHORIZED"
)
OWNER_GO = "LF_06_SSOT_PERSIST_ONLY"
BASELINE_SHA = "05d2f2edb430eaa765fbdd12620bd2cb31f83e21"


def _read(path: Path) -> str:
    assert path.is_file(), f"missing canonical path: {path}"
    return path.read_text(encoding="utf-8")


def _z2ac_section(text: str) -> str:
    start = text.find(Z2AC_HEADING)
    assert start >= 0, "missing §11.13.5.Z2AC heading"
    end = text.find("## 11.14 Live order and economic evidence ladder", start)
    assert end > start, "missing §11.14 boundary after Z2AC"
    return text[start:end]


def test_z2ac_heading_is_unique_and_follows_z2ab() -> None:
    text = _read(MASTER_RUNBOOK)
    assert text.count(Z2AC_HEADING) == 1
    z2aa = text.find(Z2AA_HEADING)
    z2ab = text.find(Z2AB_HEADING)
    z2ac = text.find(Z2AC_HEADING)
    ladder = text.find("## 11.14 Live order and economic evidence ladder")
    assert 0 <= z2aa < z2ab < z2ac < ladder


def test_z2ac_docs_bind_lf06_not_pass_without_runtime_or_lf07() -> None:
    section = _z2ac_section(_read(MASTER_RUNBOOK))
    required = (
        "AUTHORIZED_SCOPE=LF_06_SSOT_PERSIST_ONLY",
        f"OWNER_GO={OWNER_GO}",
        "OWNER_GO_STATUS=CONSUMED",
        f"BASELINE_ORIGIN_MAIN_SHA={BASELINE_SHA}",
        "LAST_CANONICALLY_CLOSED_STEP=LF_05",
        "LF_06_READ_ONLY_ADJUDICATION=NOT_PASS",
        "LF_06_OVERALL_ADJUDICATION=NOT_PASS",
        "CLAIM_LF06_01_REDUCE_ONLY_SUPPORTED_ON_EXISTING_ORDER_ENDPOINT=PROVEN",
        "CLAIM_LF06_02_REDUCE_ONLY_EXACT_WIRE_TYPE=PARTIALLY_PROVEN",
        "CLAIM_LF06_03_REDUCE_ONLY_APPLICABLE_TO_RELEVANT_FUTURES_CONTEXT=PROVEN",
        "CLAIM_LF06_04_NET_MODE_POS_SIDE_SEMANTICS=PARTIALLY_PROVEN",
        "CLAIM_LF06_05_SIGNED_POSITION_TO_FLATTEN_SIDE_MAPPING=PARTIALLY_PROVEN",
        "CLAIM_LF06_06_REDUCE_ONLY_PREVENTS_POSITION_INCREASE=PARTIALLY_PROVEN",
        "CLAIM_LF06_07_REDUCE_ONLY_PREVENTS_ZERO_CROSS_AND_FLIP=UNPROVEN",
        "CLAIM_LF06_08_OVERSIZED_REDUCE_ONLY_ORDER_BEHAVIOR=PARTIALLY_PROVEN",
        "CLAIM_LF06_09_ALREADY_FLAT_REDUCE_ONLY_BEHAVIOR=UNPROVEN",
        "CLAIM_LF06_10_RACE_SHRINK_BEFORE_FLATTEN_BEHAVIOR=UNPROVEN",
        "REDUCE_ONLY_ENDPOINT_SUPPORT=DOCUMENTED_PROVEN_ON_POST_&#47;api&#47;v5&#47;trade&#47;order",
        "REDUCE_ONLY_WIRE_TYPE_STATUS=PARTIALLY_PROVEN_REQUEST_BOOLEAN_RESPONSE_STRING_PRODUCTIVE_UNPROVEN",
        "NET_MODE_POS_SIDE_STATUS=PARTIALLY_PROVEN",
        "OVERSHOOT_PROTECTION_STATUS=UNPROVEN",
        "ZERO_CROSS_FLIP_PROTECTION_STATUS=UNPROVEN",
        "RACE_SHRINK_BEHAVIOR_STATUS=UNPROVEN",
        "FLATTEN_PRICE_POLICY_OPERATIONALLY_USABLE=false",
        "RUNTIME_REACHABLE=false",
        "LIFECYCLE_FLATTEN_RUNTIME_REACHABLE=false",
        "LIVE_FLATTEN_PROVABILITY=UNPROVEN_HARD_STOP",
        "GATE_4_FLATTEN_CAPABILITY_REMAINS=FAIL",
        "GATE_4_REDUCEONLY_IN_CANARY_PAYLOAD_REMAINS=false",
        "GATE_6_PRICE_BOUND_FOR_FLATTEN_REMAINS=FAIL",
        "DOCUMENTED_REDUCEONLY_IS_NOT_FULL_FLIP_PROTECTION=true",
        "AMENDSOURCE_4_IS_NOT_GUARANTEED_OVERSHOOT_BEHAVIOR=true",
        "OFFLINE_TEST_IS_NOT_PRODUCTIVE_VENUE_PROOF=true",
        "REQUEST_BOOLEAN_DOCS_ARE_NOT_PRODUCTIVE_WIRE_ACCEPTANCE=true",
        "NET_MODE_DOCS_ARE_NOT_PRODUCTIVE_REDUCEONLY_LIMIT_POSSIDE_PROOF=true",
        "OFFLINE_FLATTEN_MECHANISM_IS_NOT_RUNTIME_REACHABLE=true",
        "EVIDENCE_CLASS_PRODUCTIVELY_PROVEN_BEHAVIOR=ABSENT_FOR_REDUCEONLY_LIMIT_FLATTEN",
        "LF_07_AUTHORIZED=false",
        "LF_07_STARTED=false",
        "NO_LF07_ANALYSIS=true",
        "NO_LF07_IMPLEMENTATION=true",
        "NO_RUNTIME_CODE_CHANGE=true",
        "NO_FLATTEN_TRANSPORT_BINDING=true",
        "NO_PRICE_POLICY_CHANGE=true",
        "NO_ALLOWLIST_EXPANSION=true",
        "NO_CLOSE_POSITION_ENDPOINT=true",
        "NO_MARKET_ORDER_ACTIVATION=true",
        "CLOSE_POSITION_ENDPOINT_ALLOWLISTED=false",
        "FLATTEN_SUBMIT_REACHABLE=false",
        "ENTRY_PAYLOAD_STILL_OMITS_REDUCEONLY=true",
        "EARLIEST_UNRESOLVED_LF06_CLAIM=CLAIM_LF06_02_REDUCE_ONLY_EXACT_WIRE_TYPE",
        "EARLIEST_UNRESOLVED_DEPENDENCY=LIVE_FLATTEN_PROVABILITY",
        "Z2AB_PRODUCTIVE_RUNTIME_PROOF_ADMISSIBILITY_REMAINS=C",
        "Z2Y_AUTHORIZABILITY_ADJUDICATION_REMAINS=B",
        "PRODUCTIVE_RUNTIME_PROOF_ADMISSIBLE=false",
        "ORDER_SUBMIT_AUTHORIZED=false",
        "FILLED_POSITION_DERIVED_RUNTIME_AUTHORIZED=false",
        "FUTURE_RUNTIME_PROTOCOL_DOCUMENTED=false",
        "NEW_EVIDENCE_CLOSES_Z2Y_SAFETY_DEPENDENCY=false",
        "NEW_EVIDENCE_CHANGES_RUNTIME_AUTHORIZATION=false",
        "NO_POST=true",
        "NO_OKX_API_CALL=true",
        "NO_USD_EQUALS_USDC=true",
        "USD_EQUALS_USDC_ASSUMED=false",
        "LIVE_AUTHORIZED=false",
        "CANARY_AUTHORIZED=false",
        "SUPPORT_CONTACT_AUTHORIZED=false",
        "ALLOWLIST_EXPANSION_AUTHORIZED=false",
        "NO_CAPABILITY_ADVANCEMENT=true",
        "NEXT_OWNER_AUTHORIZATION_REQUIRED=SEPARATE_OWNER_GO_REQUIRED_TO_ADJUDICATE_LF07_THIS_PERSIST_DOES_NOT_AUTHORIZE_LF07",
        "HARD_STOP_AFTER_THIS_TASK=true",
        f"CANONICAL_NEXT_STEP={NEXT_POINTER}",
    )
    for marker in required:
        assert marker in section, f"missing Z2AC marker: {marker}"
    forbidden = (
        "\nLIVE_AUTHORIZED=true\n",
        "\nTESTNET_AUTHORIZED=true\n",
        "\nLF_07_AUTHORIZED=true\n",
        "\nLF_07_STARTED=true\n",
        "\nRUNTIME_REACHABLE=true\n",
        "\nLIFECYCLE_FLATTEN_RUNTIME_REACHABLE=true\n",
        "\nFLATTEN_PRICE_POLICY_OPERATIONALLY_USABLE=true\n",
        "\nLF_06_OVERALL_ADJUDICATION=PASS\n",
        "\nLIVE_FLATTEN_PROVABILITY=PROVEN\n",
        "\nOVERSHOOT_PROTECTION_STATUS=PROVEN\n",
        "\nZERO_CROSS_FLIP_PROTECTION_STATUS=PROVEN\n",
        "\nRACE_SHRINK_BEHAVIOR_STATUS=PROVEN\n",
        "\nCLAIM_LF06_07_REDUCE_ONLY_PREVENTS_ZERO_CROSS_AND_FLIP=PROVEN\n",
        "\nCLAIM_LF06_09_ALREADY_FLAT_REDUCE_ONLY_BEHAVIOR=PROVEN\n",
        "\nCLAIM_LF06_10_RACE_SHRINK_BEFORE_FLATTEN_BEHAVIOR=PROVEN\n",
        "\nCLAIM_LF06_02_REDUCE_ONLY_EXACT_WIRE_TYPE=PROVEN\n",
        "\nGATE_4_FLATTEN_CAPABILITY_REMAINS=PASS\n",
        "\nGATE_6_PRICE_BOUND_FOR_FLATTEN_REMAINS=PASS\n",
        "\nPRODUCTIVE_RUNTIME_PROOF_ADMISSIBLE=true\n",
        "\nORDER_SUBMIT_AUTHORIZED=true\n",
        "\nFILLED_POSITION_DERIVED_RUNTIME_AUTHORIZED=true\n",
        "\nFUTURE_RUNTIME_PROTOCOL_DOCUMENTED=true\n",
        "\nNEW_EVIDENCE_CLOSES_Z2Y_SAFETY_DEPENDENCY=true\n",
        "\nNEW_EVIDENCE_CHANGES_RUNTIME_AUTHORIZATION=true\n",
        "\nUSD_EQUALS_USDC_ASSUMED=true\n",
        "\nNO_USD_EQUALS_USDC=false\n",
        "\nNO_ALLOWLIST_EXPANSION=false\n",
        "\nOKX_API_CALL_PERFORMED=true\n",
        "\nORDER_SUBMITTED=true\n",
        "\nFUNDING_PERFORMED=true\n",
        "\nCANARY_AUTHORIZED=true\n",
        "\nSUPPORT_CONTACT_AUTHORIZED=true\n",
        "\nALLOWLIST_EXPANSION_AUTHORIZED=true\n",
        "\nCLOSE_POSITION_ENDPOINT_ALLOWLISTED=true\n",
        "\nFLATTEN_SUBMIT_REACHABLE=true\n",
    )
    for marker in forbidden:
        assert marker not in section, f"forbidden Z2AC marker present: {marker!r}"


def test_z2ac_map_of_truth_navigation_pointer_matches_runbook() -> None:
    mot = _read(MAP_OF_TRUTH)
    assert "§11.13.5.Z2AC |" in mot
    assert f"NEXT_CANONICAL_STEP_POINTER={NEXT_POINTER}" in mot
    assert f"NEXT_CANONICAL_STEP_POINTER={CONSUMED_Z2AB_POINTER}\n" not in mot
    assert "historical next pointer superseded by §11.13.5.Z2AC" in mot
    assert "LF_06_OVERALL_ADJUDICATION=NOT_PASS" in mot
    assert "OVERSHOOT_PROTECTION_STATUS=UNPROVEN" in mot
    assert "ZERO_CROSS_FLIP_PROTECTION_STATUS=UNPROVEN" in mot
    assert "RACE_SHRINK_BEHAVIOR_STATUS=UNPROVEN" in mot
    assert "RUNTIME_REACHABLE=false" in mot
    assert "LF_07_AUTHORIZED=false" in mot
    assert "LIVE_FLATTEN_PROVABILITY=UNPROVEN_HARD_STOP" in mot
    assert "LIVE_AUTHORIZED=false" in mot
