"""Constants for CAPABILITY_PRESENTATION_PROJECTION_OPERATIONAL_MATERIALIZER_INVOCATION_V1.

AUTHORITY_EFFECT=NONE
DASHBOARD_ROLE=PURE_CONSUMER
TRADING_SEMANTIC_CHANGE=false
RUNTIME_HOOK_ADDED=false
AUTOMATIC_CALLER_ADDED=false

Operational invocation reads durable archive siblings only (via existing
materializers). It does not export, recompute domain truth, or invent inputs.
"""

from __future__ import annotations

from src.ops.presentation_projection_octet_orchestrator_v1.constants_v1 import (
    FAMILY_CANONICAL_DECISION,
    FAMILY_DOUBLE_PLAY,
    FAMILY_DYNAMIC_SCOPE,
    FAMILY_REGIME_BULL_BEAR_SWITCH,
)

CAPABILITY_ID = "CAPABILITY_PRESENTATION_PROJECTION_OPERATIONAL_MATERIALIZER_INVOCATION_V1"
PACKAGE_MARKER = "PRESENTATION_PROJECTION_OPERATIONAL_MATERIALIZER_INVOCATION_V1=true"
OWNER = "ops.presentation_projection_operational_materializer_invocation_v1"
AUTHORITY_EFFECT = "NONE"
DASHBOARD_ROLE = "PURE_CONSUMER"

ERROR_OWNER_GO_REQUIRED = "OPERATIONAL_MATERIALIZER_INVOCATION_OWNER_GO_REQUIRED"
ERROR_ARCHIVE_ROOT_REQUIRED = "OPERATIONAL_MATERIALIZER_INVOCATION_ARCHIVE_ROOT_REQUIRED"
ERROR_ARCHIVE_ROOT_NOT_DIRECTORY = "OPERATIONAL_MATERIALIZER_INVOCATION_ARCHIVE_ROOT_NOT_DIRECTORY"
ERROR_GENERATED_AT_REQUIRED = "OPERATIONAL_MATERIALIZER_INVOCATION_GENERATED_AT_REQUIRED"

# Post-commit export families that already call the same materializers in
# family_export_adapter_v1 (sibling → projection, read-only).
OPERATIONAL_SIBLING_MATERIALIZER_FAMILIES: tuple[str, ...] = (
    FAMILY_DYNAMIC_SCOPE,
    FAMILY_REGIME_BULL_BEAR_SWITCH,
    FAMILY_CANONICAL_DECISION,
    FAMILY_DOUBLE_PLAY,
)
