"""Standing constants for the P08 empty-data-not-zero follow-up.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1,
build_okx_live_canary_auth_headers_v1, classify_target_position_state_v1,
classify_position_observation_v1, and build_account_positions_query_v1.
Does not mint a second HTTP client, signer, SecretRef owner, live/testnet/
canary authority, or mutation path. Does not authorize POST, flatten, P09
work, posSide submit-body proof, balance GET, config GET, or treating empty
data as zero.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INST_TYPE,
    DEFAULT_INSTRUMENT_ID,
    ENDPOINT_ACCOUNT_POSITIONS,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)
from src.ops.section_11_13_5_p08_position_observation_v1.constants_v1 import (
    CASE_A_TARGET_NONZERO,
    CASE_B_TARGET_ZERO,
    CASE_C_EMPTY_DATA_NOT_ZERO,
    CASE_D_TARGET_NOT_OBSERVED,
    CASE_E_HTTP_OR_OKX_ERROR,
    CASE_F_AMBIGUOUS,
    EMPTY_DATA_IS_ZERO as PREDECESSOR_EMPTY_DATA_IS_ZERO,
    NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC,
    NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_UNRESOLVED,
    NEXT_AUTHORITY_BOUNDARY_CASE_B,
    NEXT_AUTHORITY_BOUNDARY_CASE_D,
    NEXT_AUTHORITY_BOUNDARY_CASE_E,
    NEXT_AUTHORITY_BOUNDARY_CASE_F,
    P08_CANONICAL_DEFINITION,
    RESULT_CLASS_200_OKX_0,
    RESULT_CLASS_401_50110,
    RESULT_CLASS_OTHER,
    RESULT_CLASS_TRANSPORT,
)

CAPABILITY_ID = "P08_EMPTY_DATA_NOT_ZERO_V1"
PACKAGE_MARKER = "P08_EMPTY_DATA_NOT_ZERO_V1=true"
OWNER = "ops.section_11_13_5_p08_empty_data_not_zero_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p08_empty_data_not_zero.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_P08_EMPTY_DATA_NOT_ZERO_MAXIMUM_SAFE_LEVERAGE_V1"
WORKPACKAGE_ID = "OKX_EEA_P08_EMPTY_DATA_NOT_ZERO_MAX_SAFE_LEVERAGE_V1"
THIS_SLICE = "11.13.5.P08_EMPTY_DATA_NOT_ZERO"
PREDECESSOR_SLICE = "11.13.5.P08_POSITION_OBSERVATION"
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "975fcf72e8cedcecf614bbf1d6a11b0f97dcf374"
AUTHORIZED_HOST = "eea.okx.com"
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
TARGET_INST_TYPE = DEFAULT_INST_TYPE

AUTHORIZED_OPERATION = (
    "MINIMUM_NECESSARY_AUTHENTICATED_NON_MUTATING_PRIVATE_GET_ACCOUNT_POSITIONS_TO_RESOLVE_CASE_C"
)
AUTHORIZED_ENDPOINT = "GET /api/v5/account/positions"
AUTHORIZED_ENDPOINT_PATH = ENDPOINT_ACCOUNT_POSITIONS
MAX_NETWORK_REQUEST_COUNT = 3
MAX_HTTP_EXCHANGE_COUNT = 3
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
RETRY_AUTHORIZED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
SECOND_GET_ALLOWED = True
SECOND_GET_AUTHORIZED = True
THIRD_GET_ALLOWED = True
THIRD_GET_AUTHORIZED = True
ALTERNATE_ENDPOINT_ALLOWED = False
INSTID_FILTER_ALLOWED = True
INSTTYPE_FILTER_ALLOWED = True
PUBLIC_GET_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
P08_OBSERVATION_ALLOWED = True
P08_CLOSE_ALLOWED = True
FUNDING_ALLOWED = False
BALANCE_GET_ALLOWED = False
CONFIG_GET_ALLOWED = False
MAX_SIZE_GET_ALLOWED = False
POSITIONS_HISTORY_GET_ALLOWED = False
KEY_ROTATION_ALLOWED = False
PERMISSION_CHANGE_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
POSITION_CREATION_ALLOWED = False
POSITION_MODIFICATION_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
G_POSMODE_REOPEN_ALLOWED = False
G_POSMODE_CLOSE_ALLOWED = False
P09_WORK_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False

GET_1_ROLE = "UNFILTERED_ACCOUNT_POSITIONS"
GET_2_ROLE = "TARGET_INSTID_ACCOUNT_POSITIONS"
GET_3_ROLE = "INSTTYPE_FUTURES_ACCOUNT_POSITIONS"
GET_1_QUERY_ALLOWED = False
GET_2_REQUIRES_CASE_C_ON_GET_1 = True
GET_3_REQUIRES_NO_TARGET_ROW_AFTER_GET_2 = True

ENDPOINT = ENDPOINT_ACCOUNT_POSITIONS
ENDPOINT_METHOD = "GET"
FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/config",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/account/positions-history",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
)
FORBIDDEN_HTTP_METHODS: tuple[str, ...] = (
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "HEAD",
    "OPTIONS",
    "TRACE",
    "CONNECT",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
REUSED_CLASSIFIER = "classify_target_position_state_v1"
REUSED_POSITION_OBSERVATION_CLASSIFIER = "classify_position_observation_v1"
REUSED_QUERY_BUILDER = "build_account_positions_query_v1"
REUSED_PREDECESSOR_PACKAGE = "src/ops/section_11_13_5_p08_position_observation_v1"
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET_PACKAGE = False

EVIDENCE_DIRNAME = "section_11_13_5_p08_empty_data_not_zero_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)
P08_CANONICAL_DEFINITION_REUSED = P08_CANONICAL_DEFINITION
FRESHNESS_POLICY = (
    "FLATTEN_PRE_SEND_MAX_AGE_MS=5000;"
    "THIS_WINDOW_SAMPLES_AGE_AFTER_LAST_GET_AND_IS_NOT_FLATTEN_SEND_PERMIT"
)
EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False
FILTERED_EMPTY_IS_ZERO = False
TYPED_EMPTY_IS_ZERO = False
PREDECESSOR_EMPTY_DATA_IS_ZERO_REUSED = PREDECESSOR_EMPTY_DATA_IS_ZERO

HISTORICAL_P08_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_p08_position_observation_v1/20260903T190424Z"
)
HISTORICAL_P08_BODY_SHA256 = "fc24d69479edbb84f22c7d5bd4525349734056ad3baf7a5adf7e553f68c06a3a"
HISTORICAL_P08_IS_CURRENT_08_PROOF = False
Z2CN_EMPTY_ENVELOPE_SHA256 = HISTORICAL_P08_BODY_SHA256

RESULT_CLASS_200_OKX_0_REUSED = RESULT_CLASS_200_OKX_0
RESULT_CLASS_401_50110_REUSED = RESULT_CLASS_401_50110
RESULT_CLASS_OTHER_REUSED = RESULT_CLASS_OTHER
RESULT_CLASS_TRANSPORT_REUSED = RESULT_CLASS_TRANSPORT

CASE_A_TARGET_NONZERO_REUSED = CASE_A_TARGET_NONZERO
CASE_B_TARGET_ZERO_REUSED = CASE_B_TARGET_ZERO
CASE_C_EMPTY_DATA_NOT_ZERO_REUSED = CASE_C_EMPTY_DATA_NOT_ZERO
CASE_D_TARGET_NOT_OBSERVED_REUSED = CASE_D_TARGET_NOT_OBSERVED
CASE_E_HTTP_OR_OKX_ERROR_REUSED = CASE_E_HTTP_OR_OKX_ERROR
CASE_F_AMBIGUOUS_REUSED = CASE_F_AMBIGUOUS

NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC
NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_UNRESOLVED_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_UNRESOLVED
NEXT_AUTHORITY_BOUNDARY_CASE_B_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_B
NEXT_AUTHORITY_BOUNDARY_CASE_C_REMAINS = (
    "SEPARATE_OWNER_GO_REQUIRED_P08_STILL_NOT_CLOSED_EMPTY_DATA_REMAINS_NOT_ZERO"
)
NEXT_AUTHORITY_BOUNDARY_CASE_D_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_D
NEXT_AUTHORITY_BOUNDARY_CASE_E_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_E
NEXT_AUTHORITY_BOUNDARY_CASE_F_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_F
NEXT_AUTHORITY_BOUNDARY_CONTRADICTION = (
    "SEPARATE_OWNER_GO_REQUIRED_AFTER_CONTRADICTORY_POSITION_GETS_NO_RETRY_UNDER_THIS_GO"
)
