"""Constants for OKX_NATIVE_INSTRUMENT_AND_MARK_PRICE_RUNTIME_BINDING_FAIL_CLOSED_V1."""

from __future__ import annotations

CAPABILITY_ID = "OKX_NATIVE_INSTRUMENT_AND_MARK_PRICE_RUNTIME_BINDING_FAIL_CLOSED_V1"
PACKAGE_MARKER = "OKX_NATIVE_INSTRUMENT_AND_MARK_PRICE_RUNTIME_BINDING_FAIL_CLOSED_V1=true"
PRODUCER_FAMILY = "ops.okx_native_instrument_and_mark_price_runtime_binding_fail_closed_v1"
SCHEMA_VERSION = "v1"

# Venue-binding authority (reuse-before-new; no second registry).
VENUE_MAPPING_AUTHORITY = (
    "ops.bounded_futures_testnet_venue_binding_v0.default_okx_europe_xperp_production_binding"
)
VENUE_MAPPING_VERSION = "okx_eea_xperp_venue_mapping_v1"
MAPPING_SOURCE = VENUE_MAPPING_AUTHORITY

AUTHORIZED_VENUE = "OKX"
AUTHORIZED_NETWORK_SCOPE = "PUBLIC_MARKET_DATA_ONLY"
CANONICAL_INSTRUMENT_ID = "ETH-USD_UM_XPERP-310404"

MARK_PRICE_ENDPOINT = "/api/v5/public/mark-price"
MARK_PRICE_FIELD = "markPx"
MARK_PRICE_INST_TYPE = "FUTURES"
INSTRUMENTS_ENDPOINT = "/api/v5/public/instruments"
TICKER_ENDPOINT = "/api/v5/market/ticker"

# Declared ticker semantics (never markPx).
TICKER_FIELD_LAST = "last"
TICKER_FIELD_BID = "bidPx"
TICKER_FIELD_ASK = "askPx"

# Price semantics → public contract (explicit; no silent substitution).
FEATURE_PRICE_ENDPOINT = MARK_PRICE_ENDPOINT
FEATURE_PRICE_FIELD = MARK_PRICE_FIELD
STRATEGY_REFERENCE_PRICE_ENDPOINT = MARK_PRICE_ENDPOINT
STRATEGY_REFERENCE_PRICE_FIELD = MARK_PRICE_FIELD
SIMULATED_FILL_REFERENCE_PRICE_ENDPOINT = MARK_PRICE_ENDPOINT
SIMULATED_FILL_REFERENCE_PRICE_FIELD = MARK_PRICE_FIELD
MARK_TO_MARKET_PRICE_ENDPOINT = MARK_PRICE_ENDPOINT
MARK_TO_MARKET_PRICE_FIELD = MARK_PRICE_FIELD
# Existing hardening constant MARK_TO_MARKET_PRICE_SOURCE remains "explicit_mid_price";
# the mid value is obtained from the mark-price contract above.

ACTIVE_INSTRUMENT_STATES = frozenset({"live"})
DEFAULT_MAX_MARK_PRICE_STALE_SECONDS = 5.0

ERROR_CLASSES: tuple[str, ...] = (
    "CANONICAL_INSTRUMENT_MAPPING_MISSING",
    "CANONICAL_INSTRUMENT_MAPPING_AMBIGUOUS",
    "VENUE_INSTRUMENT_INACTIVE",
    "VENUE_INSTRUMENT_RESPONSE_MISMATCH",
    "PUBLIC_MARK_PRICE_RESPONSE_EMPTY",
    "REQUIRED_PRICE_FIELD_MISSING",
    "INVALID_PRICE_VALUE",
    "MARKET_DATA_TIMESTAMP_MISSING",
    "MARKET_DATA_STALE",
    "TRANSPORT_FAILURE",
)

DETERMINISTIC_ERROR_CLASSES: frozenset[str] = frozenset(
    {
        "CANONICAL_INSTRUMENT_MAPPING_MISSING",
        "CANONICAL_INSTRUMENT_MAPPING_AMBIGUOUS",
        "VENUE_INSTRUMENT_INACTIVE",
        "VENUE_INSTRUMENT_RESPONSE_MISMATCH",
        "PUBLIC_MARK_PRICE_RESPONSE_EMPTY",
        "REQUIRED_PRICE_FIELD_MISSING",
        "INVALID_PRICE_VALUE",
        "MARKET_DATA_TIMESTAMP_MISSING",
        "MARKET_DATA_STALE",
    }
)

CONFIG_RELPATH = (
    "config/ops/okx_native_instrument_and_mark_price_runtime_binding_fail_closed_v1.toml"
)
CLI_RELPATH = (
    "scripts/ops/run_okx_native_instrument_and_mark_price_runtime_binding_fail_closed_v1.py"
)

PRIVATE_API_USED = False
ORDER_ROUTING_REACHABLE = False
ORDERS_CREATED = False
EXTERNAL_PAPER_ORDER_EXECUTION_ENABLED = False
TESTNET_EXECUTION_OCCURRED = False
LIVE_EXECUTION_OCCURRED = False
PROMOTION_AUTHORITY = False
FORCED_FIXTURE_WALLCLOCK_REACHABLE = False
