"""Standing constants for productive read-only Treasury venue observation WP.

Network requires explicit Owner-GO. Standing authority pins remain false.
"""

from __future__ import annotations

from src.ops.full_core_live_path_composition_root_v1.productive_read_only_get_transport_v1 import (
    AUTHORIZED_HOST,
)
from src.ops.offline_funding_balance_read_producer_v1.constants_v1 import (
    FUNDING_BALANCE_ENDPOINT,
    FUNDING_BALANCE_ENDPOINT_METHOD,
    REUSED_REST_HOST,
    REUSED_VENUE,
)
from src.ops.pl_tf_002_network_evidence_contract_v1.constants_v1 import (
    NE_TF_001_ENDPOINT_PATH,
)
from src.ops.pl_tf_002_productive_read_only_session_executor_v1.constants_v1 import (
    OWNER_GO as SESSION_EXECUTOR_OWNER_GO,
    TRANSPORT_CLASS,
)
from src.ops.treasury_phase_2_read_only_venue_observation_binding_v1.constants_v1 import (
    EDGE_SEAM_ID as VENUE_OBSERVATION_EDGE_SEAM_ID,
    TREASURY_CAPITAL_CCY,
)

CAPABILITY_ID = "TREASURY_PRODUCTIVE_READ_ONLY_VENUE_OBSERVATION_V1"
PACKAGE_MARKER = "TREASURY_PRODUCTIVE_READ_ONLY_VENUE_OBSERVATION_V1=true"
OWNER = "ops.treasury_productive_read_only_venue_observation_v1"
SCHEMA_VERSION = "treasury_productive_read_only_venue_observation.v1"
CONTRACT_VERSION = "v1"
JOIN_SEAM_ID = "TREASURY_PRODUCTIVE_READ_ONLY_VENUE_OBSERVATION_V1"

WP_ID = "TREASURY_PRODUCTIVE_READ_ONLY_VENUE_OBSERVATION_V1"
OWNER_GO = f"OWNER_GO_{WP_ID}"
ALLOWED_WP_OWNER_GOS = frozenset({OWNER_GO, WP_ID, "OWNER_GO=true"})
SESSION_OWNER_GO = SESSION_EXECUTOR_OWNER_GO

RUNTIME_AUTHORIZATION_EFFECT = "NONE"
NETWORK_READ_ONLY_AUTHORIZED = False
NETWORK_EXECUTION_AUTHORIZED = False
CREDENTIAL_LOAD_AUTHORIZED = False
EXTERNAL_EFFECT_AUTHORIZED = False
TREASURY_MUTATION_AUTHORIZED = False
RISK_ADMISSIBLE_MINT_AUTHORIZED = False
STEP_29P_AUTHORITY_CHANGED = False
K1_AUTHORITY_CHANGED = False

EVIDENCE_DIRNAME = "treasury_productive_read_only_venue_observation_v1"
EVIDENCE_RELROOT = f"evidence/ops/{EVIDENCE_DIRNAME}"

AUTHORIZED_NETWORK_HOST = AUTHORIZED_HOST
VENUE_HOST = REUSED_REST_HOST
VENUE = REUSED_VENUE
PRODUCTIVE_TRANSPORT_CLASS = TRANSPORT_CLASS

FUNDING_GET_ENDPOINT = FUNDING_BALANCE_ENDPOINT
FUNDING_GET_METHOD = FUNDING_BALANCE_ENDPOINT_METHOD
ACCOUNT_CONFIG_ENDPOINT = NE_TF_001_ENDPOINT_PATH
READ_ONLY_ENDPOINT_CLASSES: tuple[str, ...] = (
    "PRIVATE_READ_ONLY_FUNDING_BALANCE",
    "PRIVATE_READ_ONLY_ACCOUNT_CONFIG_IDENTITY",
)

MAX_NETWORK_REQUEST_COUNT = 4
TREASURY_OBSERVATION_INSTRUMENT_ID = "ETH-USDT-SWAP"
CAPITAL_CCY = TREASURY_CAPITAL_CCY
VENUE_OBSERVATION_EDGE = VENUE_OBSERVATION_EDGE_SEAM_ID

EARLIEST_NEW_REAL_BLOCKER_AFTER_WP = (
    "CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_BASE_UNBOUND_AFTER_PRODUCER_DEFINED"
)

CREDENTIAL_SURFACE = "PL_TF_002_PRODUCTIVE_READ_ONLY_SESSION_EXECUTOR_V1"
