"""WP-C authority invariant attestation (closure only; AUTHORITY=NONE)."""

from __future__ import annotations

from typing import Any

from src.ops.market_data_private_state_runtime_convergence_v1.constants_v1 import (
    ACCOUNT_EQUITY_SIZING_AUTHORITY_NOT_ACQUIRED_BY_WP_C,
    CAP_2_3_SELECTION_OWNER_STATUS,
    EXECUTION_AUTHORITY_STATUS,
    K2_STATUS,
    LIVE_EXTERNAL_EFFECT_AUTHORIZED,
    MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED,
    MV2_DP_AUTHORITY_STATUS,
    PRETRADE_AUTHORITY_STATUS,
    PRIVATE_STATE_STRATEGY_AUTHORITY,
    PRIVATE_WS_ORDER_SEND_AUTHORIZED,
    PUBLIC_MARKET_DATA_SELECTION_AUTHORITY,
    REST_POST_PERMIT_CHANGE,
    WIRE_BOUNDARY_STATUS,
)


def wp_c_safety_attestation_v1() -> dict[str, Any]:
    return {
        "PUBLIC_MARKET_DATA_SELECTION_AUTHORITY": PUBLIC_MARKET_DATA_SELECTION_AUTHORITY,
        "PRIVATE_STATE_STRATEGY_AUTHORITY": PRIVATE_STATE_STRATEGY_AUTHORITY,
        "PRIVATE_WS_ORDER_SEND_AUTHORIZED": PRIVATE_WS_ORDER_SEND_AUTHORIZED,
        "CAP_2_3_SELECTION_OWNER_STATUS": CAP_2_3_SELECTION_OWNER_STATUS,
        "MV2_DP_AUTHORITY_STATUS": MV2_DP_AUTHORITY_STATUS,
        "PRETRADE_AUTHORITY_STATUS": PRETRADE_AUTHORITY_STATUS,
        "EXECUTION_AUTHORITY_STATUS": EXECUTION_AUTHORITY_STATUS,
        "WIRE_BOUNDARY_STATUS": WIRE_BOUNDARY_STATUS,
        "ACCOUNT_EQUITY_SIZING_AUTHORITY_NOT_ACQUIRED_BY_WP_C": (
            ACCOUNT_EQUITY_SIZING_AUTHORITY_NOT_ACQUIRED_BY_WP_C
        ),
        "LIVE_EXTERNAL_EFFECT_AUTHORIZED": LIVE_EXTERNAL_EFFECT_AUTHORIZED,
        "MULTI_FUTURE_RUNTIME_AUTHORIZED": MULTI_FUTURE_RUNTIME_AUTHORIZED,
        "MAX_POSITIONS_EFFECTIVE": MAX_POSITIONS_EFFECTIVE,
        "K2_STATUS": K2_STATUS,
        "REST_POST_PERMIT_CHANGE": REST_POST_PERMIT_CHANGE,
        "wp_c_may_select": False,
        "wp_c_may_rerank": False,
        "wp_c_may_promote_optimizer": False,
        "wp_c_may_weaken_wire_gates": False,
    }
