"""Machine-readable failure and reason codes for Capability 2.3."""

from __future__ import annotations

from enum import Enum


class SelectionFailureCodeV1(str, Enum):
    RANKING_SNAPSHOT_MISSING = "RANKING_SNAPSHOT_MISSING"
    RANKING_SNAPSHOT_INVALID = "RANKING_SNAPSHOT_INVALID"
    RANKING_SNAPSHOT_STALE = "RANKING_SNAPSHOT_STALE"
    RANKING_DIGEST_MISMATCH = "RANKING_DIGEST_MISMATCH"
    RANKING_SCHEMA_MISMATCH = "RANKING_SCHEMA_MISMATCH"
    RANKING_CAPABILITY_MISMATCH = "RANKING_CAPABILITY_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    NO_CANDIDATES = "NO_CANDIDATES"
    NO_ELIGIBLE_SELECTION = "NO_ELIGIBLE_SELECTION"
    DATA_QUALITY_FAILURE = "DATA_QUALITY_FAILURE"
    MINIMUM_HISTORY_FAILURE = "MINIMUM_HISTORY_FAILURE"
    MARK_PRICE_MISSING = "MARK_PRICE_MISSING"
    INSTRUMENT_SUSPENDED = "INSTRUMENT_SUSPENDED"
    INSTRUMENT_INVALID = "INSTRUMENT_INVALID"
    DATA_LOSS = "DATA_LOSS"
    WITHIN_MIN_HOLDING_PERIOD = "WITHIN_MIN_HOLDING_PERIOD"
    HYSTERESIS_BLOCKS_CHURN = "HYSTERESIS_BLOCKS_CHURN"
    OPEN_POSITION_BLOCKS_SWITCH = "OPEN_POSITION_BLOCKS_SWITCH"
    REPLACEMENT_PENDING = "REPLACEMENT_PENDING"
    MANUAL_OVERRIDE_FORBIDDEN = "MANUAL_OVERRIDE_FORBIDDEN"
    ALLOWLIST_INPUT_FORBIDDEN = "ALLOWLIST_INPUT_FORBIDDEN"
    DASHBOARD_INPUT_FORBIDDEN = "DASHBOARD_INPUT_FORBIDDEN"
    LEGACY_SELECTION_INPUT_FORBIDDEN = "LEGACY_SELECTION_INPUT_FORBIDDEN"
    PERSISTENCE_WRITE_FAILURE = "PERSISTENCE_WRITE_FAILURE"
    PARTIAL_WRITE = "PARTIAL_WRITE"
    CORRUPT_PERSISTED_SELECTION = "CORRUPT_PERSISTED_SELECTION"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    DUPLICATE_SELECTION_WRITER = "DUPLICATE_SELECTION_WRITER"
    SELECTION_ID_CONTENT_CONFLICT = "SELECTION_ID_CONTENT_CONFLICT"
    INTEGRITY_FAILURE = "INTEGRITY_FAILURE"
    MISSING_RANKING_EVENT_TIME = "MISSING_RANKING_EVENT_TIME"
    MISSING_RANKING_SNAPSHOT_ID = "MISSING_RANKING_SNAPSHOT_ID"
    SELECTION_VALIDITY_EXPIRED = "SELECTION_VALIDITY_EXPIRED"
    ALPHA_BLOCKED = "ALPHA_BLOCKED"
    MAX_POSITIONS_VIOLATION = "MAX_POSITIONS_VIOLATION"
    MULTI_FUTURE_UNAUTHORIZED = "MULTI_FUTURE_UNAUTHORIZED"


ALL_FAILURE_CODES: frozenset[str] = frozenset(code.value for code in SelectionFailureCodeV1)
