"""Forensic census of fee and slippage sources. Classification only. Not authority."""

from __future__ import annotations

from typing import Any

from src.ops.section_11_14_live_handoff_standing_fee_slippage_and_exact_execution_envelope_v1.constants_v1 import (
    COVER_USDC_SLIPPAGE_RESERVE_ALGEBRA,
    FEE_SOURCE_ENDPOINT,
    HISTORICAL_BTC_FAMILY,
    HISTORICAL_BTC_MAKER_USDC,
    HISTORICAL_BTC_TAKER_USDC,
    RESEARCH_BACKTEST_FEE_MODEL,
    ROUND_TRIP_FEE_RESERVE_ALGEBRA,
    RULE_SLIPPAGE_COVER_USDC,
    SLIPPAGE_POLICY_ID,
)


def fee_source_census_v1() -> tuple[dict[str, Any], ...]:
    return (
        {
            "CANDIDATE": "CURRENT_TRADE_FEE_GET",
            "SOURCE": FEE_SOURCE_ENDPOINT,
            "PATH": "src/ops/section_11_14_live_handoff_standing_fee_slippage_and_exact_execution_envelope_v1/fee_policy_v1.py",
            "FIELD_NAME": "taker|takerUSDC and maker|makerUSDC",
            "UNIT": "FRACTION_OF_NOTIONAL",
            "SIGN": "VENUE_NEGATIVE_IS_DEBIT",
            "SCOPE": "EXACT_SINGLE_SUI_USD_UM_XPERP_ENTRY_FILL",
            "FRESHNESS": "REQUIRED_CURRENT_GET_PER_PRETRADE_DECISION",
            "AUTHORITY_CLASS": "KANONISCHE_POLICY_PLUS_CURRENT_OBSERVATION",
            "CONSUMER": "exact_execution_envelope_v1",
            "HISTORICAL_OR_CURRENT": "CURRENT_WHEN_OBSERVED",
            "ADJUDICATED_STATUS": "STANDING_POLICY_BOUND_NUMERIC_REQUIRES_CURRENT_GET",
        },
        {
            "CANDIDATE": "DELIVERY_FIELD",
            "SOURCE": FEE_SOURCE_ENDPOINT,
            "PATH": "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/expiry_fee_economic_uncertainty_bound_v1.py",
            "FIELD_NAME": "delivery",
            "UNIT": "FRACTION_OF_NOTIONAL",
            "SIGN": "VENUE_NEGATIVE_OR_UNSIGNED_RATE",
            "SCOPE": "EXPIRY_SETTLEMENT_NOT_THIS_ENTRY_FILL",
            "FRESHNESS": "MAY_BE_OBSERVED_NOT_CONSUMED",
            "AUTHORITY_CLASS": "FORENSIC_RAW_NOT_THIS_FILL",
            "CONSUMER": "none_for_this_envelope",
            "HISTORICAL_OR_CURRENT": "CURRENT_OBSERVABLE_NOT_THIS_FILL",
            "ADJUDICATED_STATUS": "EXCLUDED_FROM_ENTRY_FILL_EXPECTED_FEE",
        },
        {
            "CANDIDATE": "HISTORICAL_Z2N_BTC_RATES",
            "SOURCE": f"{FEE_SOURCE_ENDPOINT} instFamily={HISTORICAL_BTC_FAMILY}",
            "PATH": "docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md §11.13.5.Z2N",
            "FIELD_NAME": "takerUSDC/makerUSDC",
            "UNIT": "FRACTION_OF_NOTIONAL",
            "SIGN": "VENUE_NEGATIVE_IS_DEBIT",
            "SCOPE": "BTC-USD_UM_XPERP_HISTORICAL",
            "FRESHNESS": "STALE_WRONG_FAMILY",
            "AUTHORITY_CLASS": "HISTORISCHER_ZWISCHENSTAND",
            "CONSUMER": "none_for_current_sui_fill",
            "HISTORICAL_OR_CURRENT": "HISTORICAL",
            "ADJUDICATED_STATUS": "REJECTED_NOT_CURRENT_SUI_AUTHORITY",
            "HISTORICAL_VALUE": f"taker={HISTORICAL_BTC_TAKER_USDC} maker={HISTORICAL_BTC_MAKER_USDC}",
        },
        {
            "CANDIDATE": "ROUND_TRIP_FEE_RESERVE",
            "SOURCE": "§11.13.5.Z2E FEE_RESERVE_ALGEBRA",
            "PATH": "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/exact_formula_body_v1.py",
            "FIELD_NAME": "FEE_RESERVE",
            "UNIT": "PEAK_TRADE_INTERNAL_NOTIONAL_UNIT",
            "SIGN": "UNSIGNED_RESERVE",
            "SCOPE": "COVER_USDC_CAPITAL_RESERVE_NOT_THIS_FILL",
            "FRESHNESS": "POLICY_FORM",
            "AUTHORITY_CLASS": "HISTORISCHE_COVER_USDC_POLICY",
            "CONSUMER": "none_for_this_entry_fill",
            "HISTORICAL_OR_CURRENT": "CURRENT_ALGEBRA_WRONG_SCOPE",
            "ADJUDICATED_STATUS": "REJECTED_ROUND_TRIP_NOT_SINGLE_FILL",
            "ALGEBRA": ROUND_TRIP_FEE_RESERVE_ALGEBRA,
        },
        {
            "CANDIDATE": "RESEARCH_BACKTEST_TAKER",
            "SOURCE": RESEARCH_BACKTEST_FEE_MODEL,
            "PATH": "src/backtest/cost_config_v0.py",
            "FIELD_NAME": "taker_fee_bps",
            "UNIT": "BPS",
            "SIGN": "UNSIGNED_COST",
            "SCOPE": "OFFLINE_RESEARCH",
            "FRESHNESS": "NOT_VENUE_CURRENT",
            "AUTHORITY_CLASS": "INTERPRETATION_NOT_LIVE_AUTHORITY",
            "CONSUMER": "research_only",
            "HISTORICAL_OR_CURRENT": "HISTORICAL_RESEARCH",
            "ADJUDICATED_STATUS": "REJECTED_NOT_CURRENT_LIVE_FEE_POLICY",
        },
        {
            "CANDIDATE": "PIPELINE_HARDCODED_0_0005",
            "SOURCE": "src/execution/pipeline.py fee_rate default",
            "PATH": "src/execution/pipeline.py",
            "FIELD_NAME": "fee_rate",
            "UNIT": "FRACTION",
            "SIGN": "UNSIGNED",
            "SCOPE": "NON_11_14_EXECUTION_PIPELINE",
            "FRESHNESS": "HARDCODED",
            "AUTHORITY_CLASS": "HISTORISCHER_DEFAULT_NOT_CURRENT",
            "CONSUMER": "none_for_this_envelope",
            "HISTORICAL_OR_CURRENT": "HISTORICAL",
            "ADJUDICATED_STATUS": "REJECTED_HARDCODED_NOT_CURRENT",
        },
        {
            "CANDIDATE": "IDENTITY_BOUND_FILL_FEE_OBSERVED",
            "SOURCE": "GET /api/v5/trade/fills fee/feeCcy",
            "PATH": "src/ops/section_11_14_live_order_and_economic_evidence_ladder_v1/fee_observed_predicate_v1.py",
            "FIELD_NAME": "fee",
            "UNIT": "feeCcy amount",
            "SIGN": "VENUE_NATIVE_FILL_FEE",
            "SCOPE": "HISTORICAL_IDENTITY_BOUND_FILL",
            "FRESHNESS": "HISTORICAL_NOT_PRETRADE_POLICY",
            "AUTHORITY_CLASS": "FORENSIC_RAW_POST_FILL",
            "CONSUMER": "restart/accounting",
            "HISTORICAL_OR_CURRENT": "HISTORICAL",
            "ADJUDICATED_STATUS": "REJECTED_AS_STANDING_PRETRADE_POLICY",
        },
    )


def slippage_source_census_v1() -> tuple[dict[str, Any], ...]:
    return (
        {
            "CANDIDATE": "LIMIT_WORST_FILL_EQUALS_LIMIT_PX",
            "SOURCE": SLIPPAGE_POLICY_ID,
            "PATH": "src/ops/section_11_14_live_handoff_standing_fee_slippage_and_exact_execution_envelope_v1/slippage_policy_v1.py",
            "FIELD_NAME": "px",
            "UNIT": "QUOTE_PRICE",
            "SIGN": "BUY_WORST_IS_HIGHEST_ADMISSIBLE_EQUALS_LIMIT",
            "SCOPE": "EXACT_SINGLE_LIMIT_ENTRY",
            "FRESHNESS": "DERIVED_FROM_CURRENT_TICKER_PLUS_TICKSZ",
            "AUTHORITY_CLASS": "KANONISCHE_STANDING_POLICY",
            "CONSUMER": "exact_execution_envelope_v1",
            "HISTORICAL_OR_CURRENT": "CURRENT",
            "ADJUDICATED_STATUS": "BOUND",
        },
        {
            "CANDIDATE": "VENUE_PRICE_LIMIT_BAND",
            "SOURCE": "GET /api/v5/public/price-limit buyLmt/sellLmt",
            "PATH": "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/price_band_observation_v1.py",
            "FIELD_NAME": "buyLmt",
            "UNIT": "QUOTE_PRICE",
            "SIGN": "UPPER_BOUND_FOR_BUY",
            "SCOPE": "VENUE_PRICE_BAND_GATE_NOT_SLIPPAGE",
            "FRESHNESS": "CURRENT_GET",
            "AUTHORITY_CLASS": "KANONISCHE_PRETRADE_GATE_NOT_SLIPPAGE_POLICY",
            "CONSUMER": "PRICE_BAND_VALID",
            "HISTORICAL_OR_CURRENT": "CURRENT",
            "ADJUDICATED_STATUS": "NOT_SLIPPAGE_BOUND",
        },
        {
            "CANDIDATE": "HISTORICAL_0_0008",
            "SOURCE": "unspecified historical constant",
            "PATH": "none_as_current_authority",
            "FIELD_NAME": "0.0008",
            "UNIT": "FRACTION",
            "SIGN": "UNSIGNED",
            "SCOPE": "UNKNOWN_HISTORICAL",
            "FRESHNESS": "STALE",
            "AUTHORITY_CLASS": "HISTORISCHER_ZWISCHENSTAND",
            "CONSUMER": "none",
            "HISTORICAL_OR_CURRENT": "HISTORICAL",
            "ADJUDICATED_STATUS": "REJECTED_NOT_CURRENT",
        },
        {
            "CANDIDATE": "COVER_USDC_SLP_TOB_FLOOR_TICK",
            "SOURCE": RULE_SLIPPAGE_COVER_USDC,
            "PATH": "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/exact_formula_body_v1.py",
            "FIELD_NAME": "SLIPPAGE_RESERVE",
            "UNIT": "PEAK_TRADE_INTERNAL_NOTIONAL_UNIT",
            "SIGN": "UNSIGNED_RESERVE",
            "SCOPE": "COVER_USDC_NOT_LIMIT_FILL_WORST_PRICE",
            "FRESHNESS": "POLICY_FORM_UNINSTANTIATED_NUMERIC",
            "AUTHORITY_CLASS": "COVER_USDC_POLICY_NOT_THIS_FILL",
            "CONSUMER": "none_for_this_entry_fill",
            "HISTORICAL_OR_CURRENT": "CURRENT_ALGEBRA_WRONG_SCOPE",
            "ADJUDICATED_STATUS": "REJECTED_AS_LIMIT_WORST_FILL_POLICY",
            "ALGEBRA": COVER_USDC_SLIPPAGE_RESERVE_ALGEBRA,
        },
        {
            "CANDIDATE": "RESEARCH_BACKTEST_SLIPPAGE",
            "SOURCE": "backtest/research cost models",
            "PATH": "src/backtest/",
            "FIELD_NAME": "slippage_bps",
            "UNIT": "BPS",
            "SIGN": "UNSIGNED",
            "SCOPE": "OFFLINE_RESEARCH",
            "FRESHNESS": "NOT_VENUE_CURRENT",
            "AUTHORITY_CLASS": "INTERPRETATION_NOT_LIVE_AUTHORITY",
            "CONSUMER": "research_only",
            "HISTORICAL_OR_CURRENT": "HISTORICAL_RESEARCH",
            "ADJUDICATED_STATUS": "REJECTED_NOT_CURRENT",
        },
    )
