"""Fail-closed constants for the §11.14 exact-single-fill execution envelope."""

from __future__ import annotations

CAPABILITY_ID = (
    "SECTION_11_14_LIVE_HANDOFF_STANDING_FEE_SLIPPAGE_AND_COMPLETE_NON_EXECUTING_"
    "EXACT_SINGLE_FILL_EXECUTION_ENVELOPE_V1"
)
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "section_11_14_exact_single_fill_execution_envelope.v1"
ENVELOPE_VERSION = "section_11_14_exact_execution_envelope.v1"
OWNER = "ops.section_11_14_live_handoff_standing_fee_slippage_and_exact_execution_envelope_v1"
THIS_SLICE = (
    "11.14.LIVE_HANDOFF_STANDING_FEE_SLIPPAGE_AND_COMPLETE_NON_EXECUTING_"
    "EXACT_SINGLE_FILL_EXECUTION_ENVELOPE"
)
PREDECESSOR_SLICE = (
    "11.14.LIVE_HANDOFF_CURRENT_ORIGIN_MAIN_BOUND_GET_ONLY_"
    "PRETRADE_ACCOUNT_NETWORK_AND_INSTRUMENT_READINESS"
)
LAST_CANONICALLY_CLOSED_PREDECESSOR = (
    "SECTION_11_14_LIVE_HANDOFF_EXACT_SINGLE_LIVE_IDENTITY_BOUND_"
    "VENUE_FILL_THEN_CONTEMPORANEOUS_PRE_RESTART_CAPTURE"
)
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_HANDOFF_STANDING_FEE_SLIPPAGE_AND_"
    "COMPLETE_NON_EXECUTING_EXACT_SINGLE_FILL_EXECUTION_ENVELOPE_V1"
)

PATH_ACCOUNT_TRADE_FEE = "/api/v5/account/trade-fee"
TRADE_FEE_INST_TYPE = "FUTURES"
FEE_SOURCE_ENDPOINT = PATH_ACCOUNT_TRADE_FEE
FEE_FIELD_TAKER_GENERIC = "taker"
FEE_FIELD_MAKER_GENERIC = "maker"
FEE_FIELD_TAKER_USDC = "takerUSDC"
FEE_FIELD_MAKER_USDC = "makerUSDC"
FEE_FIELD_DELIVERY = "delivery"
FEE_SIGN_DEBIT_IS_NEGATIVE = True
FEE_CURRENCY_REQUIRED = "USDC"
FEE_RATE_UNIT = "FRACTION_OF_NOTIONAL"
NOTIONAL_ALGEBRA = "qty * ctVal * worst_fill_px"
NOTIONAL_ALGEBRA_ROLE = "PEAK_TRADE_INTERNAL_NOTIONAL_ENVELOPE_NOT_OEM_OKX_FEE_FORMULA"
EXACT_OKX_FEE_FORMULA_STATUS = "UNPROVEN"
SINGLE_FILL_FEE_RATE_ALGEBRA = "max(debit(taker), debit(maker))"
SINGLE_FILL_FEE_AMOUNT_ALGEBRA = "conservative_rate * internal_notional"
ROUND_TRIP_FEE_RESERVE_ALGEBRA = "2 * max(abs(taker), abs(maker)) * INTERNAL_NOTIONAL_ENVELOPE"
ROUND_TRIP_FEE_RESERVE_IS_NOT_THIS_FILL = True
MAKER_TAKER_ASSUMPTION = "FAIL_CLOSED_UNCERTAINTY_RESOLVED_AS_CONSERVATIVE_MAX_DEBIT"
DELIVERY_FEE_ROLE_FOR_THIS_FILL = "NOT_PART_OF_ENTRY_FILL"
HISTORICAL_BTC_TAKER_USDC = "-0.0005"
HISTORICAL_BTC_MAKER_USDC = "-0.0002"
HISTORICAL_BTC_FAMILY = "BTC-USD_UM_XPERP"
HISTORICAL_FEE_RATES_ARE_NOT_CURRENT = True
RESEARCH_BACKTEST_FEE_MODEL = "backtest_fee_taker_symmetric_v0"
RESEARCH_BACKTEST_IS_NOT_CURRENT = True
CONSERVATIVE_FEE_QUANTIZE_EXPONENT = -12
FEE_QUANTIZE_ROLE = "PEAK_TRADE_CONSERVATIVE_CEILING_NOT_VENUE_ROUNDING_PROOF"

SLIPPAGE_POLICY_ID = "LIMIT_WORST_FILL_EQUALS_LIMIT_PX"
SLIPPAGE_POLICY_UNIT = "QUOTE_PRICE_AND_FRACTION_OF_REFERENCE"
HISTORICAL_SLIPPAGE_0_0008_IS_NOT_CURRENT = True
PRICE_LIMIT_BAND_IS_NOT_SLIPPAGE = True
COVER_USDC_SLIPPAGE_RESERVE_ALGEBRA = "2 * max(askPx - bidPx, tickSz) * ctVal * qty"
COVER_USDC_SLIPPAGE_RESERVE_IS_NOT_THIS_FILL_WORST_PRICE = True
RULE_SLIPPAGE_COVER_USDC = "SLP-TOB-FLOOR-TICK"

CLORDID_STATUS = "UNKNOWN_REQUIRES_FUTURE_EXECUTION_OWNER_GO"
CLORDID_PLAN_SENTINEL = "UNKNOWN_REQUIRES_FUTURE_EXECUTION_OWNER_GO"
POS_SIDE_OMITTED_IN_NET_MODE = True

CAPTURE_OPTIONAL_ENVELOPE_FIELDS: tuple[str, ...] = (
    "execution_envelope_id",
    "execution_envelope_version",
    "fee_provenance",
    "slippage_provenance",
    "expected_fee",
    "expected_fee_ccy",
    "planned_fill_price",
    "worst_case_fill_price",
    "order_qty",
    "order_qty_unit",
    "instrument_id",
)
