"""Constants for research stratification v2 — no production numeric thresholds."""

from __future__ import annotations

RESEARCH_STRATIFICATION_CONTRACT_VERSION = "canonical_volatility_max_age_research_stratification/v2"
EVIDENCE_SCHEMA_VERSION_V2 = "canonical_volatility_max_age_productive_research_evidence_record/v2"
SPEC_REL_PATH = (
    "docs/ops/specs/MASTER_V2_CANONICAL_VOLATILITY_MAX_AGE_RESEARCH_STRATIFICATION_V2.md"
)

TRADING_AUTHORITY = "NONE"
PROMOTION_AUTHORITY = "NONE"

# Fail-closed / non-counting stratum labels
FAIL_CLOSED_STRATUM_VALUES: frozenset[str] = frozenset(
    {
        "INSUFFICIENT_DATA",
        "UNCLASSIFIED",
        "MISSING",
        "UNKNOWN",
    }
)

VOLATILITY_INPUT_AUTHORITY = "CMC_TYPED_VOLATILITY_OBSERVATION"
MARK_PATH_INPUT_AUTHORITY = "RESEARCH_OWNED_OBSERVATION_MARK_PATH"

CROSS_SESSION_STATE_POLICY = "RESEARCH_MARK_PATH_MAY_RESTORE_WITHIN_CAMPAIGN_ONLY"
CROSS_CAMPAIGN_STATE_POLICY = "NO_CARRY"

BLOCKER_MARKET_STATE_PARAMETER_AUTHORITY_UNSET = (
    "MARKET_STATE_STRATIFICATION_PARAMETER_AUTHORITY_UNSET"
)
BLOCKER_VOLATILITY_PARAMETER_AUTHORITY_UNSET = "VOLATILITY_STRATIFICATION_PARAMETER_AUTHORITY_UNSET"
BLOCKER_CMC_PROVENANCE_INCOMPLETE = "CMC_VOLATILITY_PROVENANCE_INCOMPLETE"
BLOCKER_MARK_PATH_PROVENANCE_INCOMPLETE = "RESEARCH_MARK_PATH_PROVENANCE_INCOMPLETE"
BLOCKER_CROSS_CAMPAIGN_CARRY = "CROSS_CAMPAIGN_RESEARCH_STATE_CARRY_FORBIDDEN"

AUTHORITY_STATUS_UNSET = "UNSET"
AUTHORITY_STATUS_RATIFIED = "RATIFIED"

# Production: no numeric values — lookback/threshold slots exist but remain unset.
RESEARCH_MARK_PATH_MAX_LEN = 128
