"""Standing constants for the offline Funding Account balance read producer.

This package reuses the existing §11.13.5 private GET allowlist, RO HTTP
client, and RO signer contract. It does not mint Live, Testnet, Canary,
order, transfer, deposit, or conversion authority. Implementation is not
execution.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    ENDPOINT_ACCOUNT_BALANCE,
    ENDPOINT_ASSET_BALANCES,
    GET_ENDPOINTS_PRIVATE,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    POST_ENDPOINTS_GATED,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)

CAPABILITY_ID = "OFFLINE_FUNDING_BALANCE_READ_PRODUCER_V1"
PACKAGE_MARKER = "OFFLINE_FUNDING_BALANCE_READ_PRODUCER_V1=true"
OWNER = "ops.offline_funding_balance_read_producer_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "offline_funding_balance_read_producer.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_Z2DF_OFFLINE_FUNDING_BALANCE_READ_PRODUCER_V1"
WORKPACKAGE_ID = "OFFLINE_FUNDING_BALANCE_READ_PRODUCER_V1"
THIS_SLICE = "11.13.5.Z2DF"
PREDECESSOR_SLICE = "11.13.5.Z2DB"
CURRENT_CANONICAL_SECTION = "11.13.5.Z2DF"

FUNDING_BALANCE_ENDPOINT = ENDPOINT_ASSET_BALANCES
FUNDING_BALANCE_ENDPOINT_METHOD = "GET"
FUNDING_BALANCE_ENDPOINT_CLASS = "PRIVATE_READ_ONLY"
TRADING_ACCOUNT_BALANCE_ENDPOINT = ENDPOINT_ACCOUNT_BALANCE
FORBIDDEN_TRANSFER_ENDPOINT = "/api/v5/asset/transfer"
FORBIDDEN_WITHDRAWAL_ENDPOINT = "/api/v5/asset/withdrawal"
FORBIDDEN_NON_ALLOWLISTED_ASSET_ENDPOINT = "/api/v5/asset/currencies"

assert FUNDING_BALANCE_ENDPOINT in GET_ENDPOINTS_PRIVATE
assert FUNDING_BALANCE_ENDPOINT != TRADING_ACCOUNT_BALANCE_ENDPOINT
assert FORBIDDEN_TRANSFER_ENDPOINT not in GET_ENDPOINTS_PRIVATE
assert FORBIDDEN_TRANSFER_ENDPOINT not in POST_ENDPOINTS_GATED

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_RO_SIGNER_SYMBOL = "build_okx_live_ro_get_auth_headers_v1"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_RECORDING_TRANSPORT = "RecordingFakeCanaryTransportV1"

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

PRODUCTIVE_NETWORK_REACHABILITY = False
NETWORK_CALL_PERFORMED = False
SECRET_MATERIALIZATION_ALLOWED = False
CAPITAL_MOVEMENT_AUTHORIZED = False
INTERNAL_TRANSFER_AUTHORIZED = False
EXTERNAL_DEPOSIT_AUTHORIZED = False
CURRENCY_CONVERSION_AUTHORIZED = False
PREREQUISITE_08_CLOSED_BY_THIS_PACKAGE = False
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False
ABSENT_CURRENCY_ROW_ZERO_SEMANTICS_CREATED = False
USD_USDC_COLLAPSED = False

FUNDING_BALANCE_GET_IMPLEMENTED = True
FUNDING_BALANCE_GET_EXECUTED = False
FUNDING_ACCOUNT_STATUS = "UNKNOWN"

DEFAULT_MAX_RETRIES = 0
DEFAULT_MAX_REQUEST_COUNT = 1
MAX_RAW_DIGIT_LEN = 64
ROW_CCY_MAX_LEN = 32

SOURCE_ENDPOINT_FIELD = "GET /api/v5/asset/balances"
FUNDING_ACCOUNT_SCOPE = "OKX_FUNDING_ACCOUNT"
TRADING_ACCOUNT_SCOPE = "OKX_TRADING_ACCOUNT"

VENUE_ROW_FIELDS: tuple[str, ...] = ("ccy", "bal", "frozenBal", "availBal")
