"""Assemble the PR #6252 merge-closeout persist pack. Offline. No GET. No POST."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_13_5_pr_6252_merge_closeout_v1.adjudicate_v1 import (
    adjudicate_pr_6252_merge_closeout_v1,
)
from src.ops.section_11_13_5_pr_6252_merge_closeout_v1.constants_v1 import (
    AUTHORIZED_ACCOUNT_UID,
    AUTHORIZED_HOST,
    AUTHORIZED_OPERATION,
    AUTHORIZED_SCOPE,
    CANONICAL_EVIDENCE_RUN_ID,
    CENSUS_RUNTIME_RESIDUAL,
    CLOSEOUT_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
    CLOSEOUT_DOES_NOT_AUTHORIZE_GET_VALUE,
    CLOSEOUT_DOES_NOT_AUTHORIZE_POST_VALUE,
    CLOSEOUT_DOES_NOT_AUTHORIZE_RETRY_VALUE,
    CLOSEOUT_DOES_NOT_AUTHORIZE_SECTION_11_14_VALUE,
    CLOSEOUT_DOES_NOT_SET_CANARY_AUTHORIZED_VALUE,
    CLOSEOUT_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EMPTY_DATA_IS_ZERO_VALUE,
    EXPECTED_ORIGIN_MAIN_SHA,
    FAIL_CLOSED_IF_EMPTY_DATA_PROMOTED_TO_ZERO_VALUE,
    FAIL_CLOSED_IF_G12_MARKED_CLOSED_VALUE,
    FAIL_CLOSED_IF_SECTION_11_14_AUTHORIZED_VALUE,
    G12_STATUS_VALUE,
    LAST_CANONICALLY_CLOSED_STEP,
    LIVE_FLATTEN_PROVABILITY_PROVEN_VALUE,
    MERGE_AUTHORIZED_BY_THIS_PERSIST_VALUE,
    MINIMUM_ADDITIONAL_OWNER_GO_COUNT,
    NEXT_AUTHORITY_BOUNDARY,
    NEXT_OWNER_GO_REQUIRED,
    NEXT_WORKPACKAGE,
    OWNER_GO,
    OWNER_MERGE_GO_FOR_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_PR_STATUS,
    PR_6252_FILE_COUNT,
    PR_6252_HEAD_SHA,
    PR_6252_MERGE_PARENT,
    PR_6252_MERGE_SHA,
    PR_6252_NUMBER,
    PR_6252_STATUS_VALUE,
    PREDECESSOR_EVIDENCE_PACK,
    PREDECESSOR_RECOVERY_PACK,
    PREDECESSOR_SLICE,
    PRIOR_OWNER_GO,
    PRODUCTIVE_FLATTEN_TEXT_REWRITTEN_VALUE,
    RECOVERY_POSITION_SEMANTICS_VALUE,
    RETRY_ALLOWED_VALUE,
    SECTION_11_14_AUTHORIZED_VALUE,
    STALE_NEXT_POINTER_CORRECTED_VALUE,
    STALE_POINTER_WAS_VALUE,
    TARGET_INSTRUMENT_ID,
    TARGET_POSITION_ZERO_PROVEN_VALUE,
    THIS_GO_GET_COUNT,
    THIS_GO_POST_COUNT,
    THIS_SLICE,
    WORKPACKAGE_COUNT,
    WORKPACKAGE_ID,
)
from src.ops.section_11_13_5_pr_6252_merge_closeout_v1.persist_v1 import (
    persist_pr_6252_merge_closeout_evidence_v1,
)


class Pr6252MergeCloseoutAssembleError(RuntimeError):
    """Fail-closed assemble violation."""


def assemble_pr_6252_merge_closeout_v1(
    *,
    origin_main_sha: str,
    evidence_root: Path | None = None,
    run_id: str = CANONICAL_EVIDENCE_RUN_ID,
) -> dict[str, Any]:
    """Build and optionally persist PR #6252 closeout. No GET. No POST."""
    if str(origin_main_sha or "").strip() != EXPECTED_ORIGIN_MAIN_SHA:
        raise Pr6252MergeCloseoutAssembleError("ORIGIN_MAIN_SHA_MISMATCH")
    verdict = adjudicate_pr_6252_merge_closeout_v1(origin_main_sha=origin_main_sha)
    if verdict["G12_STATUS"] != G12_STATUS_VALUE:
        raise Pr6252MergeCloseoutAssembleError("G12_MUST_REMAIN_OPEN")
    if verdict["TARGET_POSITION_ZERO_PROVEN"] is True:
        raise Pr6252MergeCloseoutAssembleError("TARGET_POSITION_ZERO_MUST_REMAIN_UNPROVEN")
    if verdict["SECTION_11_14_AUTHORIZED"] is True:
        raise Pr6252MergeCloseoutAssembleError("SECTION_11_14_MUST_REMAIN_UNAUTHORIZED")
    census = {
        "DOCUMENT_CLASS": "PR_6252_MERGE_CLOSEOUT_CENSUS_V1",
        "DOCUMENT_ROLE": "FORENSIC_CENSUS_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "CENSUS_BASE_SHA": origin_main_sha,
        "SEAM_COUNT": verdict["CENSUS"]["SEAM_COUNT"],
        "EPISTEMIC_CLASS_COUNTS": verdict["CENSUS"]["EPISTEMIC_CLASS_COUNTS"],
        "PROVEN_SEAMS": verdict["CENSUS"]["PROVEN_SEAMS"],
        "NOT_PROMOTED_SEAMS": verdict["CENSUS"]["NOT_PROMOTED_SEAMS"],
        "PR_6252_STATUS": PR_6252_STATUS_VALUE,
        "OWNER_MERGE_GO_FOR_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_PR_STATUS": (
            OWNER_MERGE_GO_FOR_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_PR_STATUS
        ),
        "STALE_NEXT_POINTER_CORRECTED": STALE_NEXT_POINTER_CORRECTED_VALUE,
        "G12_STATUS": G12_STATUS_VALUE,
        "TARGET_POSITION_ZERO_PROVEN": TARGET_POSITION_ZERO_PROVEN_VALUE,
        "LIVE_FLATTEN_PROVABILITY_PROVEN": LIVE_FLATTEN_PROVABILITY_PROVEN_VALUE,
        "RECOVERY_POSITION_SEMANTICS": RECOVERY_POSITION_SEMANTICS_VALUE,
        "EMPTY_DATA_IS_ZERO": EMPTY_DATA_IS_ZERO_VALUE,
        "SECTION_11_14_AUTHORIZED": SECTION_11_14_AUTHORIZED_VALUE,
        "RETRY_ALLOWED": RETRY_ALLOWED_VALUE,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "PRODUCTIVE_FLATTEN_TEXT_REWRITTEN": PRODUCTIVE_FLATTEN_TEXT_REWRITTEN_VALUE,
    }
    lineage = {
        "DOCUMENT_CLASS": "PR_6252_MERGE_CLOSEOUT_LINEAGE_V1",
        "DOCUMENT_ROLE": "FORENSIC_LINEAGE_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "LINEAGE_FIELD_NAMES": verdict["CENSUS"]["LINEAGE_FIELD_NAMES"],
        "SEAMS": verdict["LINEAGE"],
        "G12_STATUS": G12_STATUS_VALUE,
        "TARGET_POSITION_ZERO_PROVEN": TARGET_POSITION_ZERO_PROVEN_VALUE,
        "LIVE_FLATTEN_PROVABILITY_PROVEN": LIVE_FLATTEN_PROVABILITY_PROVEN_VALUE,
        "RECOVERY_POSITION_SEMANTICS": RECOVERY_POSITION_SEMANTICS_VALUE,
        "EMPTY_DATA_IS_ZERO": EMPTY_DATA_IS_ZERO_VALUE,
        "SECTION_11_14_AUTHORIZED": SECTION_11_14_AUTHORIZED_VALUE,
        "RETRY_ALLOWED": RETRY_ALLOWED_VALUE,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "PRODUCTIVE_FLATTEN_TEXT_REWRITTEN": PRODUCTIVE_FLATTEN_TEXT_REWRITTEN_VALUE,
    }
    adjudication = {
        "DOCUMENT_CLASS": "PR_6252_MERGE_CLOSEOUT_ADJUDICATION_V1",
        "DOCUMENT_ROLE": "INTERPRETATION_NOT_RAW_WIRE_NOT_SSOT",
        "AUTHORITY": "NONE",
        **{k: v for k, v in verdict.items() if k not in {"CENSUS", "LINEAGE"}},
        "CENSUS": verdict["CENSUS"],
        "LINEAGE": verdict["LINEAGE"],
    }
    summary = {
        "DOCUMENT_CLASS": "PR_6252_MERGE_CLOSEOUT_PACKAGE_V1",
        "DOCUMENT_ROLE": "DERIVED_NON_SSOT",
        "OWNER_GO": OWNER_GO,
        "OWNER_GO_CONSUMED": True,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "AUTHORIZED_SCOPE": AUTHORIZED_SCOPE,
        "AUTHORIZED_OPERATION": AUTHORIZED_OPERATION,
        "HOST": AUTHORIZED_HOST,
        "AUTHORIZED_ACCOUNT_UID": AUTHORIZED_ACCOUNT_UID,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "PR_6252_NUMBER": PR_6252_NUMBER,
        "PR_6252_STATUS": PR_6252_STATUS_VALUE,
        "PR_6252_MERGE_SHA": PR_6252_MERGE_SHA,
        "PR_6252_MERGE_PARENT": PR_6252_MERGE_PARENT,
        "PR_6252_HEAD_SHA": PR_6252_HEAD_SHA,
        "PR_6252_FILE_COUNT": PR_6252_FILE_COUNT,
        "OWNER_MERGE_GO_FOR_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_PR_STATUS": (
            OWNER_MERGE_GO_FOR_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_PR_STATUS
        ),
        "PRODUCTIVE_FLATTEN_TEXT_REWRITTEN": PRODUCTIVE_FLATTEN_TEXT_REWRITTEN_VALUE,
        "STALE_NEXT_POINTER_CORRECTED": STALE_NEXT_POINTER_CORRECTED_VALUE,
        "STALE_POINTER_WAS": STALE_POINTER_WAS_VALUE,
        "G12_STATUS": G12_STATUS_VALUE,
        "TARGET_POSITION_ZERO_PROVEN": TARGET_POSITION_ZERO_PROVEN_VALUE,
        "LIVE_FLATTEN_PROVABILITY_PROVEN": LIVE_FLATTEN_PROVABILITY_PROVEN_VALUE,
        "RECOVERY_POSITION_SEMANTICS": RECOVERY_POSITION_SEMANTICS_VALUE,
        "EMPTY_DATA_IS_ZERO": EMPTY_DATA_IS_ZERO_VALUE,
        "SECTION_11_14_AUTHORIZED": SECTION_11_14_AUTHORIZED_VALUE,
        "RETRY_ALLOWED": RETRY_ALLOWED_VALUE,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "CENSUS_RUNTIME_RESIDUAL": CENSUS_RUNTIME_RESIDUAL,
        "NEXT_WORKPACKAGE": NEXT_WORKPACKAGE,
        "NEXT_OWNER_GO_REQUIRED": NEXT_OWNER_GO_REQUIRED,
        "WORKPACKAGE_COUNT": WORKPACKAGE_COUNT,
        "MINIMUM_ADDITIONAL_OWNER_GO_COUNT": MINIMUM_ADDITIONAL_OWNER_GO_COUNT,
        "GET_REQUEST_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "HTTP_EXCHANGE_COUNT": 0,
        "POST_COUNT": THIS_GO_POST_COUNT,
        "WRITE_REQUEST_COUNT": 0,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "PRIVATE_AUTH_USED": False,
        "LIVE_AUTHORIZED": False,
        "CANARY_AUTHORIZED": False,
        "SUBMIT_UNLOCKED": False,
        "LIVE_ENABLED": False,
        "LIVE_ARMED": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": MERGE_AUTHORIZED_BY_THIS_PERSIST_VALUE,
        "CLOSEOUT_DOES_NOT_SET_LIVE_AUTHORIZED": CLOSEOUT_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
        "CLOSEOUT_DOES_NOT_SET_CANARY_AUTHORIZED": CLOSEOUT_DOES_NOT_SET_CANARY_AUTHORIZED_VALUE,
        "CLOSEOUT_DOES_NOT_AUTHORIZE_GET": CLOSEOUT_DOES_NOT_AUTHORIZE_GET_VALUE,
        "CLOSEOUT_DOES_NOT_AUTHORIZE_POST": CLOSEOUT_DOES_NOT_AUTHORIZE_POST_VALUE,
        "CLOSEOUT_DOES_NOT_AUTHORIZE_RETRY": CLOSEOUT_DOES_NOT_AUTHORIZE_RETRY_VALUE,
        "CLOSEOUT_DOES_NOT_AUTHORIZE_FLATTEN": CLOSEOUT_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
        "CLOSEOUT_DOES_NOT_AUTHORIZE_SECTION_11_14": (
            CLOSEOUT_DOES_NOT_AUTHORIZE_SECTION_11_14_VALUE
        ),
        "FAIL_CLOSED_IF_G12_MARKED_CLOSED": FAIL_CLOSED_IF_G12_MARKED_CLOSED_VALUE,
        "FAIL_CLOSED_IF_EMPTY_DATA_PROMOTED_TO_ZERO": (
            FAIL_CLOSED_IF_EMPTY_DATA_PROMOTED_TO_ZERO_VALUE
        ),
        "FAIL_CLOSED_IF_SECTION_11_14_AUTHORIZED": FAIL_CLOSED_IF_SECTION_11_14_AUTHORIZED_VALUE,
        "PREDECESSOR_EVIDENCE_PACK": PREDECESSOR_EVIDENCE_PACK,
        "PREDECESSOR_RECOVERY_PACK": PREDECESSOR_RECOVERY_PACK,
        "EXECUTION_READY": False,
        "ATLAS_AUTHORITY": "NONE",
        "LANDSCAPE_AUTHORITY": "NONE",
    }
    result: dict[str, Any] = {
        "verdict": verdict,
        "census": census,
        "lineage": lineage,
        "adjudication": adjudication,
        "summary": summary,
    }
    if evidence_root is not None:
        pack = Path(evidence_root) / run_id
        verified = persist_pr_6252_merge_closeout_evidence_v1(
            pack=pack,
            origin_main_sha=origin_main_sha,
            census=census,
            lineage=lineage,
            adjudication=adjudication,
            summary=summary,
        )
        result["EVIDENCE_PACK"] = str(pack)
        result["MANIFEST_VERIFY_RC"] = int(verified.get("MANIFEST_VERIFY_RC", 1))
    return result
