"""Standing constants for PR #6252 merge-closeout persist.

Offline CASE_B contract persist. No GET. No POST. No flatten. No Live/Canary
unlock. Does not rewrite PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_pr_6252_merge_closeout_v1.contract_v1 import (
    CASE,
    CLOSEOUT_DOES_NOT_AUTHORIZE_FLATTEN,
    CLOSEOUT_DOES_NOT_AUTHORIZE_GET,
    CLOSEOUT_DOES_NOT_AUTHORIZE_POST,
    CLOSEOUT_DOES_NOT_AUTHORIZE_RETRY,
    CLOSEOUT_DOES_NOT_AUTHORIZE_SECTION_11_14,
    CLOSEOUT_DOES_NOT_SET_CANARY_AUTHORIZED,
    CLOSEOUT_DOES_NOT_SET_LIVE_AUTHORIZED,
    EMPTY_DATA_IS_ZERO,
    FAIL_CLOSED_IF_EMPTY_DATA_PROMOTED_TO_ZERO,
    FAIL_CLOSED_IF_G12_MARKED_CLOSED,
    FAIL_CLOSED_IF_SECTION_11_14_AUTHORIZED,
    G12_STATUS,
    GET_PERFORMED_THIS_PERSIST,
    LIVE_FLATTEN_PROVABILITY_PROVEN,
    MERGE_AUTHORIZED_BY_THIS_PERSIST,
    OWNER_MERGE_GO_STATUS,
    POST_PERFORMED,
    PR_6252_STATUS,
    PRIVATE_AUTH_USED,
    PRODUCTIVE_FLATTEN_TEXT_REWRITTEN,
    RECOVERY_POSITION_SEMANTICS,
    RETRY_ALLOWED,
    SECTION_11_14_AUTHORIZED,
    STALE_NEXT_POINTER_CORRECTED,
    STALE_POINTER_WAS,
    TARGET_POSITION_ZERO_PROVEN,
)

CAPABILITY_ID = "PR_6252_MERGE_CLOSEOUT_V1"
PACKAGE_MARKER = "PR_6252_MERGE_CLOSEOUT_V1=true"
OWNER = "ops.section_11_13_5_pr_6252_merge_closeout_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "pr_6252_merge_closeout.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_PR_6252_MERGE_CLOSEOUT_MAXIMUM_SAFE_LEVERAGE_V1"
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_MAXIMUM_SAFE_LEVERAGE_V1"
)
WORKPACKAGE_ID = "OKX_EEA_PR_6252_MERGE_CLOSEOUT_V1"
THIS_SLICE = "11.13.5.PR_6252_MERGE_CLOSEOUT"
PREDECESSOR_SLICE = "11.13.5.PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_PR_6252_MERGE_CLOSEOUT"
EXPECTED_ORIGIN_MAIN_SHA = "3d1ec4eeee5497e4a933e471b89cadfc470c828d"
PR_6252_NUMBER = 6252
PR_6252_MERGE_SHA = EXPECTED_ORIGIN_MAIN_SHA
PR_6252_MERGE_PARENT = "a23cb998d4d9121a7f06816cc54c0c6ce19a5992"
PR_6252_HEAD_SHA = "0db6f269c2414b8283eaaa0579eabcbd0971453a"
PR_6252_FILE_COUNT = 41
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_PR_6252_POST_MERGE_CLOSEOUT_AND_STALE_POINTER_CORRECTION"
AUTHORIZED_SCOPE = "PR_6252_POST_MERGE_CLOSEOUT"
CANONICAL_EVIDENCE_RUN_ID = "20260904T101200Z"
PREDECESSOR_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_productive_flatten_post_and_reconciliation_v1/20260904T061816Z"
)
PREDECESSOR_RECOVERY_PACK = (
    "evidence/ops/section_11_13_5_productive_flatten_post_and_reconciliation_v1/"
    "20260904T061816Z_recovery_read_only"
)

CASE_VALUE = CASE
PR_6252_STATUS_VALUE = PR_6252_STATUS
OWNER_MERGE_GO_FOR_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_PR_STATUS = OWNER_MERGE_GO_STATUS
PRODUCTIVE_FLATTEN_TEXT_REWRITTEN_VALUE = PRODUCTIVE_FLATTEN_TEXT_REWRITTEN
STALE_NEXT_POINTER_CORRECTED_VALUE = STALE_NEXT_POINTER_CORRECTED
STALE_POINTER_WAS_VALUE = STALE_POINTER_WAS
G12_STATUS_VALUE = G12_STATUS
TARGET_POSITION_ZERO_PROVEN_VALUE = TARGET_POSITION_ZERO_PROVEN
LIVE_FLATTEN_PROVABILITY_PROVEN_VALUE = LIVE_FLATTEN_PROVABILITY_PROVEN
RECOVERY_POSITION_SEMANTICS_VALUE = RECOVERY_POSITION_SEMANTICS
EMPTY_DATA_IS_ZERO_VALUE = EMPTY_DATA_IS_ZERO
SECTION_11_14_AUTHORIZED_VALUE = SECTION_11_14_AUTHORIZED
RETRY_ALLOWED_VALUE = RETRY_ALLOWED
GET_PERFORMED_THIS_PERSIST_VALUE = GET_PERFORMED_THIS_PERSIST
POST_PERFORMED_VALUE = POST_PERFORMED
PRIVATE_AUTH_USED_VALUE = PRIVATE_AUTH_USED
MERGE_AUTHORIZED_BY_THIS_PERSIST_VALUE = MERGE_AUTHORIZED_BY_THIS_PERSIST
CLOSEOUT_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = CLOSEOUT_DOES_NOT_SET_LIVE_AUTHORIZED
CLOSEOUT_DOES_NOT_SET_CANARY_AUTHORIZED_VALUE = CLOSEOUT_DOES_NOT_SET_CANARY_AUTHORIZED
CLOSEOUT_DOES_NOT_AUTHORIZE_GET_VALUE = CLOSEOUT_DOES_NOT_AUTHORIZE_GET
CLOSEOUT_DOES_NOT_AUTHORIZE_POST_VALUE = CLOSEOUT_DOES_NOT_AUTHORIZE_POST
CLOSEOUT_DOES_NOT_AUTHORIZE_RETRY_VALUE = CLOSEOUT_DOES_NOT_AUTHORIZE_RETRY
CLOSEOUT_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = CLOSEOUT_DOES_NOT_AUTHORIZE_FLATTEN
CLOSEOUT_DOES_NOT_AUTHORIZE_SECTION_11_14_VALUE = CLOSEOUT_DOES_NOT_AUTHORIZE_SECTION_11_14
FAIL_CLOSED_IF_G12_MARKED_CLOSED_VALUE = FAIL_CLOSED_IF_G12_MARKED_CLOSED
FAIL_CLOSED_IF_EMPTY_DATA_PROMOTED_TO_ZERO_VALUE = FAIL_CLOSED_IF_EMPTY_DATA_PROMOTED_TO_ZERO
FAIL_CLOSED_IF_SECTION_11_14_AUTHORIZED_VALUE = FAIL_CLOSED_IF_SECTION_11_14_AUTHORIZED
EARLIEST_UNRESOLVED_DEPENDENCY = "LIVE_FLATTEN_PROVABILITY_IF_NOT_PROVEN"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_G12_POSITION_ZERO_PROOF"
CENSUS_RUNTIME_RESIDUAL = "G12_LIVE_FLATTEN_PROVABILITY_REMAINS_UNPROVEN"
NEXT_WORKPACKAGE = "G12_LIVE_FLATTEN_PROVABILITY"
NEXT_OWNER_GO_REQUIRED = "SEPARATE_OWNER_GO_FOR_FRESH_POSITION_ROW_ZERO_PROOF"
MINIMUM_ADDITIONAL_OWNER_GO_COUNT = 1
WORKPACKAGE_COUNT = 1
THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
POSITION_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
FUNDING_ALLOWED = False
MERGE_ALLOWED = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P25_CLOSED = True
STP_CLOSED = True
APT_CLOSED = True
STPR_CLOSED = True
CENSUS_CLOSED = True
APRPI_CLOSED = True
PRODUCTIVE_FLATTEN_POST_CLOSED = True
EVIDENCE_DIRNAME = "section_11_13_5_pr_6252_merge_closeout_v1"
