"""Constants for CURRENT MF N=5 Boundary occupied-lane Cap24 N=1 bind join."""

from __future__ import annotations

from src.ops.current_mf_n5_isolated_lane_instance_topology_v1.constants_v1 import (
    CROSS_UNIVERSE_CANDIDATE_BORROWING as TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK as TOPOLOGY_CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN as TOPOLOGY_CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT as TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING as TOPOLOGY_CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION as TOPOLOGY_CROSS_UNIVERSE_SELECTION,
    FIVE_LANE_RUNTIME_CREATED as TOPOLOGY_FIVE_LANE_RUNTIME_CREATED,
    INSTRUMENT_ID_ALONE_SUFFICIENT as TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT,
    LANE_MAPPING_OWNER as TOPOLOGY_LANE_MAPPING_OWNER,
    MAX_POSITIONS_EFFECTIVE as TOPOLOGY_MAX_POSITIONS_EFFECTIVE,
    MF_PRODUCTIVE_JOIN as TOPOLOGY_MF_PRODUCTIVE_JOIN,
    MULTI_UNIVERSE_MERGE as TOPOLOGY_MULTI_UNIVERSE_MERGE,
)
from src.ops.current_mf_n5_occupied_lane_pin_consumer_join_v1.constants_v1 import (
    FIVE_LANE_CONTINUOUS_HOST_JOIN as PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN,
)
from src.ops.current_mf_n5_ranking_domain_occupied_lane_cap23_n1_produce_join_v1.constants_v1 import (
    OWNER as CAP23_PRODUCE_JOIN_OWNER_VALUE,
)
from src.ops.single_selected_future_policy_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP23_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP23_OWNER_VALUE,
)
from src.ops.single_selected_future_runtime_binding_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP24_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP24_OWNER_VALUE,
    RUNTIME_ACTIVATION_ALLOWED as CAP24_RUNTIME_ACTIVATION_ALLOWED,
)

OWNER = "ops.current_mf_n5_boundary_occupied_lane_cap24_n1_bind_join_v1"
CONTRACT_ID = "CURRENT_MF_N5_BOUNDARY_OCCUPIED_LANE_CAP24_N1_BIND_JOIN_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_n5_boundary_occupied_lane_cap24_n1_bind_join.v1"

LANE_MAPPING_OWNER = TOPOLOGY_LANE_MAPPING_OWNER
CAP23_SELECTION_OWNER = CAP23_OWNER_VALUE
CAP23_PRODUCE_JOIN_OWNER = CAP23_PRODUCE_JOIN_OWNER_VALUE
CAP24_BINDING_OWNER = CAP24_OWNER_VALUE

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
JOIN_SELECTION_AUTHORITY = False
JOIN_CAP23_SELECTION_AUTHORITY = False
JOIN_CAP24_BINDING_AUTHORITY = False
JOIN_TRADING_AUTHORITY = False
JOIN_RUNTIME_ACTIVATION_AUTHORITY = False
JOIN_EXECUTION_AUTHORITY = False
JOIN_RANKING_AUTHORITY = False
JOIN_MEMBERSHIP_AUTHORITY = False
JOIN_MAPPING_AUTHORITY = False
JOIN_PERSISTENCE_AUTHORITY = False
PARALLEL_AUTHORITY_CREATED = False

CROSS_UNIVERSE_SELECTION = TOPOLOGY_CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = TOPOLOGY_CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = TOPOLOGY_CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = TOPOLOGY_CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = TOPOLOGY_MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT
UNIVERSE_ISOLATION = "HARD"
UNIVERSE_ISOLATION_ENFORCED = True

MF_PRODUCTIVE_JOIN = TOPOLOGY_MF_PRODUCTIVE_JOIN
FIVE_LANE_RUNTIME_CREATED = TOPOLOGY_FIVE_LANE_RUNTIME_CREATED
FIVE_LANE_CONTINUOUS_HOST_JOIN = PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = False
MF_SINGLE_EGRESS_REWIRED = False
MAX_POSITIONS_EFFECTIVE = int(TOPOLOGY_MAX_POSITIONS_EFFECTIVE)
MULTI_FUTURE_RUNTIME_AUTHORIZED = bool(CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED)
PREPARED_BOUND_CARDINALITY = "0..5"
PRODUCTIVE_RUNTIME_CARDINALITY = "1_UNJOINED"
FAILURE_POLICY_FOR_OCCUPIED_LANE_WITHOUT_SUCCESSFUL_BIND = "A_ABSENT_AND_CONTINUE"
assert MAX_POSITIONS_EFFECTIVE == int(CAP23_MAX_POSITIONS_EFFECTIVE)
assert MAX_POSITIONS_EFFECTIVE == int(CAP24_MAX_POSITIONS_EFFECTIVE) == 1
assert MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_RUNTIME_ACTIVATION_ALLOWED is False
assert MF_PRODUCTIVE_JOIN is False
assert FIVE_LANE_RUNTIME_CREATED is False
assert FIVE_LANE_CONTINUOUS_HOST_JOIN is False
assert PARALLEL_AUTHORITY_CREATED is False
assert JOIN_SELECTION_AUTHORITY is False
assert JOIN_CAP23_SELECTION_AUTHORITY is False
assert JOIN_CAP24_BINDING_AUTHORITY is False
assert JOIN_TRADING_AUTHORITY is False
assert JOIN_RUNTIME_ACTIVATION_AUTHORITY is False
assert CAP23_SELECTION_OWNER == "ops.single_selected_future_policy_v1"
assert CAP24_BINDING_OWNER == "ops.single_selected_future_runtime_binding_v1"

CAP23_CHANGE_REQUIRED = False
CAP24_CHANGE_REQUIRED = False
MASTER_V2_CHANGE_REQUIRED = False
DOUBLE_PLAY_CHANGE_REQUIRED = False

FAILURE_AUTHORITY = "BOUNDARY_CAP24_BIND_JOIN_AUTHORITY_CLAIM_FORBIDDEN"
FAILURE_UNKNOWN_LANE_ID = "BOUNDARY_CAP24_BIND_JOIN_UNKNOWN_LANE_ID"
FAILURE_SELECTION_TYPE = "BOUNDARY_CAP24_BIND_JOIN_SELECTION_TYPE_MISMATCH"

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "produce_occupied_lane_cap23_n1_selections_v1",
        "run_single_selected_future_policy_v1",
        "produce_single_selected_future_v1",
        "produce_from_ranking_state_root_v1",
        "persist_selection_bundle_atomic_v1",
        "_pick_top_eligible",
        "ensure_single_selected_future_runtime_binding_v1",
        "persist_binding_evidence_atomic_v1",
        "run_current_productive_master_v2_runtime_cycle_v1",
        "compose_core_live_execution_intent_v1",
        "mf_canonical_single_egress_authority_handoff_contract_v1",
        "master_v2",
        "double_play",
        "execution",
        "top_n_active_set",
        "LiveExecutionPort",
    }
)
