"""Constants for CURRENT MF N=5 occupied-lane governed-cycle N=1 consumer join.

Consumes S8 roots and invokes the existing governed cycle lane-local with
NON-V5 EG and S7 T2. Cap61 stays unbound. Host and productive MF join remain
false. PRODUCTIVE_RUNTIME_CARDINALITY remains 1_UNJOINED.
"""

from __future__ import annotations

from src.ops.current_mf_n5_boundary_occupied_lane_cap24_n1_bind_join_v1.constants_v1 import (
    HOST_JOIN as BOUNDARY_HOST_JOIN,
    PREPARED_BOUND_CARDINALITY as BOUNDARY_PREPARED_BOUND_CARDINALITY,
    PRODUCTIVE_RUNTIME_CARDINALITY as BOUNDARY_PRODUCTIVE_RUNTIME_CARDINALITY,
)
from src.ops.current_mf_n5_full_autonomy_occupied_lane_mv2_dp_decision_state_addressing_join_v1.constants_v1 import (
    ATOMICITY_SEMANTICS as ADDRESSING_ATOMICITY_SEMANTICS,
    CURSOR_OWNER as ADDRESSING_CURSOR_OWNER,
    FIRST_TRADING_DECISION_CONSUMER as ADDRESSING_FIRST_TRADING_DECISION_CONSUMER,
    HOST_JOIN as ADDRESSING_HOST_JOIN,
    MAY_BIND_CAP61_STATE_ROOT as ADDRESSING_MAY_BIND_CAP61_STATE_ROOT,
    MAY_INVOKE_GOVERNED_CYCLE as ADDRESSING_MAY_INVOKE_GOVERNED_CYCLE,
    N1_GLOBAL_CURSOR_STORE_RELPATH as ADDRESSING_N1_GLOBAL_CURSOR_STORE_RELPATH,
    OWNER as ADDRESSING_OWNER,
    PAIR_MAP_OBJECT as ADDRESSING_PAIR_MAP_OBJECT,
    PAIR_MAP_PRODUCER as ADDRESSING_PAIR_MAP_PRODUCER,
    S7_JOIN_SYMBOL as ADDRESSING_S7_JOIN_SYMBOL,
    S8_JOIN_SYMBOL as ADDRESSING_S8_JOIN_SYMBOL,
    SLOT_STATE_ROOT_RESOLVER as ADDRESSING_SLOT_STATE_ROOT_RESOLVER,
)
from src.ops.current_mf_n5_isolated_lane_instance_topology_v1.constants_v1 import (
    CROSS_UNIVERSE_CANDIDATE_BORROWING as TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK as TOPOLOGY_CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN as TOPOLOGY_CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT as TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING as TOPOLOGY_CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION as TOPOLOGY_CROSS_UNIVERSE_SELECTION,
    FIVE_LANE_RUNTIME_CREATED as TOPOLOGY_FIVE_LANE_RUNTIME_CREATED,
    INSTRUMENT_ID_ALONE_SUFFICIENT as TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT,
    LANE_MAPPING_OWNER as TOPOLOGY_LANE_MAPPING_OWNER,
    MAX_POSITIONS_EFFECTIVE as TOPOLOGY_MAX_POSITIONS_EFFECTIVE,
    MF_PRODUCTIVE_JOIN as TOPOLOGY_MF_PRODUCTIVE_JOIN,
    MULTI_UNIVERSE_MERGE as TOPOLOGY_MULTI_UNIVERSE_MERGE,
)
from src.ops.current_mf_n5_occupied_lane_pin_consumer_join_v1.constants_v1 import (
    FIVE_LANE_CONTINUOUS_HOST_JOIN as PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN,
)
from src.ops.single_selected_future_policy_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP23_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP23_OWNER_VALUE,
)
from src.ops.single_selected_future_runtime_binding_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP24_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP24_OWNER_VALUE,
    RUNTIME_ACTIVATION_ALLOWED as CAP24_RUNTIME_ACTIVATION_ALLOWED,
)

OWNER = "ops.current_mf_n5_full_autonomy_occupied_lane_governed_cycle_n1_consumer_join_v1"
CONTRACT_ID = (
    "CURRENT_MF_N5_FULL_AUTONOMY_OCCUPIED_LANE_GOVERNED_CYCLE_N1_CONSUMER_JOIN_CONTRACT_V1"
)
SCHEMA_VERSION = "current_mf_n5_full_autonomy_occupied_lane_governed_cycle_n1_consumer_join.v1"
SLICE_ID = "GOVERNED_CYCLE_N1_CONSUMER_JOIN_TO_PRE_EXTERNAL_EFFECT"
OWNER_GO_THIS_SLICE = (
    "OWNER_GO_CURRENT_MF_N5_FULL_AUTONOMY_OCCUPIED_LANE_GOVERNED_CYCLE_N1_CONSUMER_JOIN_V1"
)

LANE_MAPPING_OWNER = TOPOLOGY_LANE_MAPPING_OWNER
CAP23_SELECTION_OWNER = CAP23_OWNER_VALUE
CAP24_BINDING_OWNER = CAP24_OWNER_VALUE
S8_PRODUCER_OWNER = ADDRESSING_OWNER
CONSUMER_OWNER = OWNER
CURSOR_OWNER = ADDRESSING_CURSOR_OWNER
CAP61_CONFIRMATION_OWNER = "ops.stateful_confirmation_and_c1_productive_binding_v1"
FULL_AUTONOMY_HOST_OWNER = "stateful_no_order_host_join_v1"
FULL_CORE_LIVE_PATH_AUTHORITY = "full_core_live_path_authority_v1"
GOVERNED_CYCLE_OWNER = (
    "ops.full_core_live_path_composition_root_v1.current_productive_governed_cycle_orchestrator_v1"
)

PAIR_MAP_PRODUCER = ADDRESSING_PAIR_MAP_PRODUCER
PAIR_MAP_OBJECT = ADDRESSING_PAIR_MAP_OBJECT
SLOT_STATE_ROOT_RESOLVER = ADDRESSING_SLOT_STATE_ROOT_RESOLVER
S8_JOIN_SYMBOL = ADDRESSING_S8_JOIN_SYMBOL
S7_JOIN_SYMBOL = ADDRESSING_S7_JOIN_SYMBOL
JOIN_SYMBOL = "invoke_occupied_lane_governed_cycle_n1_consumer_v1"
JOIN_IMPLEMENTED = True
JOIN_INTENDED_EGRESS = "dict[lane_id, OccupiedLaneGovernedCycleN1ConsumerResultV1]"
CONSUMPTION_SEAM = "invoke_run_current_productive_governed_cycle_v1"
S8_CONSUMED = True
GOVERNED_CYCLE_INVOKED = True
EG_DISPATCH_SYMBOL = "non_v5_eg_dispatch_v1"
T2_DISPATCH_SYMBOL = S7_JOIN_SYMBOL
EG_V5_USED = False
T2_S7_USED = True
FIRST_TRADING_DECISION_CONSUMER = ADDRESSING_FIRST_TRADING_DECISION_CONSUMER
NATIVE_ID_SOURCE = "BoundInstrumentV1.venue_native_id"
N1_GLOBAL_CURSOR_STORE_RELPATH = ADDRESSING_N1_GLOBAL_CURSOR_STORE_RELPATH
N1_GLOBAL_CURSOR_LANE_SAFE = False
CURSOR_BUNDLE_TYPE = "CurrentProductiveSideStateConfirmationCursorV1"
CURSOR_FILENAME = "current_productive_sidestate_confirmation_cursor_v1.json"
CURSOR_HAS_LANE_ID_FIELD = False
CURSOR_SCHEMA_CHANGED = False
NEW_CURSOR_LANE_ID_FIELD = False
ATOMICITY_SEMANTICS = ADDRESSING_ATOMICITY_SEMANTICS
ATOMICITY_CLAIMED_SATISFIED = False
PERSIST_SURFACE_OWNER = CURSOR_OWNER
CAP61_CYCLE_STATE_ROOT_BOUND = False
MAY_BIND_CAP61_STATE_ROOT = False
MAY_CAP61_PERSIST = False
MAY_CAP62_PERSIST = False
MAY_G17_CHECKPOINT = False
MAY_EXIT_POLICY_PERSIST = False
MAY_INVOKE_GOVERNED_CYCLE = True
INVOCATION_CONTEXT = "BOUNDED_TEST_HARNESS_LANE_ISOLATED"
OCCUPIED_LANES_ONLY = True
UNIQUE_MUTABLE_ROOTS_ENFORCED = True
GLOBAL_N1_CURSOR_REJECTED = True
LANE_STATE_ROOT_ROLE = "EXTERNAL_ADDRESSING_ONLY"

SAME_TRADING_CONFIGURATION_ACROSS_LANES = True
SHARED_MUTABLE_STATE_ACROSS_LANES = False
NEW_STATE_OWNER_CREATED = False
NEW_COLLECTION_DTO_CREATED = False
NEW_TOP5_HANDOFF_DTO_CREATED = False
NEW_MULTI_BOUND_AUTHORITY_DTO_CREATED = False
NEW_MV2_DP_INGRESS_DTO_CREATED = False
NEW_CURSOR_SCHEMA_CREATED = False

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
JOIN_SELECTION_AUTHORITY = False
JOIN_CAP23_SELECTION_AUTHORITY = False
JOIN_CAP24_BINDING_AUTHORITY = False
JOIN_TRADING_AUTHORITY = False
JOIN_RUNTIME_ACTIVATION_AUTHORITY = False
JOIN_EXECUTION_AUTHORITY = False
JOIN_RANKING_AUTHORITY = False
JOIN_MEMBERSHIP_AUTHORITY = False
JOIN_MAPPING_AUTHORITY = False
JOIN_PERSISTENCE_AUTHORITY = False
JOIN_FULL_AUTONOMY_HOST_AUTHORITY = False
PARALLEL_AUTHORITY_CREATED = False
THIS_SLICE_MAY_REINVOKE_CAP23 = False
THIS_SLICE_MAY_REINVOKE_CAP24 = False
MF_PRODUCTIVE_JOIN = TOPOLOGY_MF_PRODUCTIVE_JOIN
FIVE_LANE_RUNTIME_CREATED = TOPOLOGY_FIVE_LANE_RUNTIME_CREATED
FIVE_LANE_CONTINUOUS_HOST_JOIN = PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = False
MF_SINGLE_EGRESS_REWIRED = False
MAX_POSITIONS_EFFECTIVE = int(TOPOLOGY_MAX_POSITIONS_EFFECTIVE)
MULTI_FUTURE_RUNTIME_AUTHORIZED = bool(CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED)
PREPARED_BOUND_CARDINALITY = BOUNDARY_PREPARED_BOUND_CARDINALITY
PRODUCTIVE_RUNTIME_CARDINALITY = BOUNDARY_PRODUCTIVE_RUNTIME_CARDINALITY

CROSS_UNIVERSE_SELECTION = TOPOLOGY_CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = TOPOLOGY_CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = TOPOLOGY_CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = TOPOLOGY_CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = TOPOLOGY_MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT
UNIVERSE_ISOLATION = "HARD"
UNIVERSE_ISOLATION_ENFORCED = True

CAP23_CHANGE_REQUIRED = False
CAP24_CHANGE_REQUIRED = False
MASTER_V2_CHANGE_REQUIRED = False
DOUBLE_PLAY_CHANGE_REQUIRED = False
FULL_AUTONOMY_HOST_CHANGE_REQUIRED = False
CURSOR_OWNER_CHANGE_REQUIRED = False

assert HOST_JOIN is False
assert BOUNDARY_HOST_JOIN is False
assert ADDRESSING_HOST_JOIN is False
assert ADDRESSING_MAY_INVOKE_GOVERNED_CYCLE is False
assert MAY_INVOKE_GOVERNED_CYCLE is True
assert ADDRESSING_MAY_BIND_CAP61_STATE_ROOT is False
assert MAY_BIND_CAP61_STATE_ROOT is False
assert S8_JOIN_SYMBOL == "bind_occupied_lane_governed_cycle_store_roots_v1"
assert S7_JOIN_SYMBOL == "compose_occupied_lane_mv2_dp_durable_cycle_v1"
assert JOIN_SYMBOL == "invoke_occupied_lane_governed_cycle_n1_consumer_v1"
assert EG_DISPATCH_SYMBOL == "non_v5_eg_dispatch_v1"
assert T2_DISPATCH_SYMBOL == S7_JOIN_SYMBOL
assert EG_V5_USED is False
assert T2_S7_USED is True
assert S8_CONSUMED is True
assert GOVERNED_CYCLE_INVOKED is True
assert NATIVE_ID_SOURCE == "BoundInstrumentV1.venue_native_id"
assert FIRST_TRADING_DECISION_CONSUMER == "run_current_productive_master_v2_runtime_cycle_v1"
assert ATOMICITY_SEMANTICS == "NON_ATOMIC_DIRECT_WRITE_TEXT"
assert ATOMICITY_CLAIMED_SATISFIED is False
assert CAP61_CYCLE_STATE_ROOT_BOUND is False
assert NEW_STATE_OWNER_CREATED is False
assert MAX_POSITIONS_EFFECTIVE == int(CAP23_MAX_POSITIONS_EFFECTIVE)
assert MAX_POSITIONS_EFFECTIVE == int(CAP24_MAX_POSITIONS_EFFECTIVE) == 1
assert MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_RUNTIME_ACTIVATION_ALLOWED is False
assert MF_PRODUCTIVE_JOIN is False
assert FIVE_LANE_RUNTIME_CREATED is False
assert FIVE_LANE_CONTINUOUS_HOST_JOIN is False
assert PARALLEL_AUTHORITY_CREATED is False
assert JOIN_SELECTION_AUTHORITY is False
assert JOIN_CAP23_SELECTION_AUTHORITY is False
assert JOIN_CAP24_BINDING_AUTHORITY is False
assert JOIN_TRADING_AUTHORITY is False
assert JOIN_RUNTIME_ACTIVATION_AUTHORITY is False
assert JOIN_RANKING_AUTHORITY is False
assert JOIN_PERSISTENCE_AUTHORITY is False
assert JOIN_FULL_AUTONOMY_HOST_AUTHORITY is False
assert JOIN_EXECUTION_AUTHORITY is False
assert PREPARED_BOUND_CARDINALITY == "0..5"
assert PRODUCTIVE_RUNTIME_CARDINALITY == "1_UNJOINED"
assert EXECUTION_CONCURRENCY_AUTHORIZED is False
assert PAIR_MAP_OBJECT == "dict[lane_id, (IsolatedLaneSlotV1, BoundInstrumentV1)]"
assert CURSOR_OWNER == (
    "ops.full_core_live_path_composition_root_v1."
    "current_productive_sidestate_confirmation_cursor_v1"
)
assert S8_PRODUCER_OWNER == (
    "ops.current_mf_n5_full_autonomy_occupied_lane_mv2_dp_decision_state_addressing_join_v1"
)

FAILURE_AUTHORITY = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_AUTHORITY_CLAIM_FORBIDDEN"
FAILURE_UNKNOWN_LANE_ID = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_UNKNOWN_LANE_ID"
FAILURE_PAIR_TYPE = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_PAIR_TYPE_MISMATCH"
FAILURE_OCCUPANCY = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_OCCUPANCY_MISMATCH"
FAILURE_IDENTITY_MISMATCH = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_IDENTITY_MISMATCH"
FAILURE_NATIVE_ID_MISSING = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_NATIVE_ID_MISSING"
FAILURE_S8_ROOTS_MISSING = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_S8_ROOTS_MISSING"
FAILURE_INJECTED_C1_REQUIRED = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_INJECTED_C1_REQUIRED"
FAILURE_ORIGIN_MAIN_SHA = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_ORIGIN_MAIN_SHA_MISSING"
FAILURE_V5_DISPATCH = "FULL_AUTONOMY_GOVERNED_CYCLE_N1_CONSUMER_V5_DISPATCH_FORBIDDEN"

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "produce_occupied_lane_cap23_n1_selections_v1",
        "run_single_selected_future_policy_v1",
        "produce_single_selected_future_v1",
        "produce_from_ranking_state_root_v1",
        "persist_selection_bundle_atomic_v1",
        "_pick_top_eligible",
        "run_single_selected_future_runtime_binding_gate_v1",
        "ensure_single_selected_future_runtime_binding_v1",
        "persist_binding_evidence_atomic_v1",
        "compose_occupied_lane_mv2_dp_handoff_v1",
        "_run_cap21_to_cap24_v1",
        "execute_current_productive_one_runtime_cycle_after_new_finalized_1m_c1_observation_v1",
        "current_productive_one_runtime_cycle_after_new_finalized_1m_c1_observation",
        "ensure_host_activation_binding_v1",
        "stateful_no_order_host_join_v1",
        "construct_live_execution_port_v1",
        "persist_dynamic_scope_state_atomic_v1",
        "load_dynamic_scope_state_v1",
        "apply_current_productive_g17_typed_vol_mark_history_checkpoint_v1",
        "persist_exit_policy_state_atomic_v1",
        "commit_host_exit_policy_state_v1",
        "run_current_productive_governed_continuous_cycle_run_v1",
        "mf_canonical_single_egress_authority_handoff_contract_v1",
        "master_v2",
        "double_play",
        "execution",
        "top_n_active_set",
        "LiveExecutionPort",
    }
)
