"""Hard-facts system closure constants — authority boundaries and safety flags."""

from __future__ import annotations

PACKAGE_MARKER = "HARD_FACTS_SYSTEM_CLOSURE_V1=true"
OWNER = "ops.hard_facts_system_closure_v1"
CONTRACT_VERSION = "hard_facts_system_closure.v1"

POST_ALLOWED = False
EXTERNAL_EFFECT_AUTHORIZED = False
REAL_VENUE_POST_ALLOWED = False
MULTI_FUTURE_RUNTIME_AUTHORIZED = False
N_GT_1_ENABLED = False
MAX_POSITIONS_EFFECTIVE = 1

CAP22_RANKING_CONTEXT_ONLY = True
CAP23_SOLE_SELECTION_AUTHORITY = True
CAP24_BIND_ONLY = True
MASTER_V2_ORCHESTRATION_ONLY = True
DOUBLE_PLAY_TRADING_DECISION_SEMANTICS = True
INTELLIGENCE_ZERO_TRADING_DECISION_AUTHORITY = True
SUPERVISOR_ZERO_ECONOMIC_AUTHORITY = True
PRE_EXTERNAL_TERMINAL = True

SYNTHETIC_RANKING_MARKERS = (
    "synthetic",
    "SYNTHETIC",
    "synthesize_ready",
    "TEST_FIXTURE_ONLY",
    "productive_real_fact=false",
)

PRODUCTIVE_RANKING_CAPABILITY_ID = "CAPABILITY_2_2_PRODUCTIVE_FUTURES_RANKING_PRODUCER_V1"
PRODUCTIVE_RANKING_PRODUCER_VERSION = "productive_futures_ranking_producer.v1"

CASE_SWITCH_EQUIVALENTS = (
    "trading_gate",
    "safety_mode",
    "HostExitPolicyBindingV1",
    "durable_kill_switch",
    "typed_vol_presence_gate",
    "s5_governed_cycle_orchestrator",
)

__all__ = [
    "CAP22_RANKING_CONTEXT_ONLY",
    "CAP23_SOLE_SELECTION_AUTHORITY",
    "CAP24_BIND_ONLY",
    "CASE_SWITCH_EQUIVALENTS",
    "CONTRACT_VERSION",
    "DOUBLE_PLAY_TRADING_DECISION_SEMANTICS",
    "EXTERNAL_EFFECT_AUTHORIZED",
    "INTELLIGENCE_ZERO_TRADING_DECISION_AUTHORITY",
    "MASTER_V2_ORCHESTRATION_ONLY",
    "MAX_POSITIONS_EFFECTIVE",
    "MULTI_FUTURE_RUNTIME_AUTHORIZED",
    "N_GT_1_ENABLED",
    "OWNER",
    "PACKAGE_MARKER",
    "POST_ALLOWED",
    "PRE_EXTERNAL_TERMINAL",
    "PRODUCTIVE_RANKING_CAPABILITY_ID",
    "PRODUCTIVE_RANKING_PRODUCER_VERSION",
    "REAL_VENUE_POST_ALLOWED",
    "SUPERVISOR_ZERO_ECONOMIC_AUTHORITY",
    "SYNTHETIC_RANKING_MARKERS",
]
