"""Exit authority matrix derived from productive runtime truth."""

from __future__ import annotations

from typing import Any

from src.ops.exit_policy_producer_binding_v1.constants_v1 import (
    ADVERSE_PRODUCER_OWNER,
    ADVERSE_RESOLVE_OWNER,
    ENTRY_EXIT_POLICY_OWNER,
    OWNER,
    PRODUCTIVE_DECISION_OWNER,
    PRODUCTIVE_HOST,
    SAFETY_PRODUCER_OWNER,
    TIME_FOUNDATION_OWNER,
)


def build_exit_authority_matrix_v1() -> list[dict[str, Any]]:
    return [
        {
            "EXIT_CLASS": "Safety Exit",
            "CANONICAL_PRODUCER": SAFETY_PRODUCER_OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_HOST,
            "CURRENT_PLACEHOLDER_OR_STUB": "PolicySignalV0(triggered=False) before Cap 6.5",
            "STATE_OWNER": "bridge_session + evaluate_bridge_safety_v2 inputs",
            "CONFIG_OWNER": "safety_binding_v2 thresholds (drawdown kill)",
            "EVENT_TIME_OWNER": "observation venue_event_time",
            "PERSISTED_INPUTS": "killstate/drawdown via session; exit pending via Cap 6.5 state",
            "RESTART_INPUTS": "Cap 6.5 exit policy state + session rebuildable safety inputs",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 1,
            "REQUIRED_BINDING_CHANGE": "bind evaluate_bridge_safety_v2 into productive host",
        },
        {
            "EXIT_CLASS": "Hard-Risk Reduce",
            "CANONICAL_PRODUCER": SAFETY_PRODUCER_OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_HOST,
            "CURRENT_PLACEHOLDER_OR_STUB": "PolicySignalV0(triggered=False) before Cap 6.5",
            "STATE_OWNER": "bridge_session portfolio drawdown",
            "CONFIG_OWNER": "safety_binding_v2 drawdown_kill_threshold",
            "EVENT_TIME_OWNER": "observation venue_event_time",
            "PERSISTED_INPUTS": "portfolio/accounting via Cap 3.1 / Cap 6.4",
            "RESTART_INPUTS": "accounting restart + Cap 6.5 pending exit",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 2,
            "REQUIRED_BINDING_CHANGE": "bind hard_risk_reduction_signal from safety producer",
        },
        {
            "EXIT_CLASS": "Reconciliation Action",
            "CANONICAL_PRODUCER": "productive_reconciliation_runtime_binding_v1 + entry_exit_policy",
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_DECISION_OWNER,
            "CURRENT_PLACEHOLDER_OR_STUB": "none (reconciliation_state consumed directly)",
            "STATE_OWNER": "ops.productive_reconciliation_runtime_binding_v1",
            "CONFIG_OWNER": "reconciliation taxonomy",
            "EVENT_TIME_OWNER": "startup gate / restart recovery",
            "PERSISTED_INPUTS": "reconciliation state root",
            "RESTART_INPUTS": "reconciliation-before-alpha gate",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 3,
            "REQUIRED_BINDING_CHANGE": "none (already productive)",
        },
        {
            "EXIT_CLASS": "Adverse Exit",
            "CANONICAL_PRODUCER": f"{ADVERSE_PRODUCER_OWNER} / {ADVERSE_RESOLVE_OWNER}",
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_HOST,
            "CURRENT_PLACEHOLDER_OR_STUB": "host stub False; replay resolve may override",
            "STATE_OWNER": "dynamic_scope + entry_price Cap 6.5 state",
            "CONFIG_OWNER": "canonical adverse_exit_distance (Cap 6.3)",
            "EVENT_TIME_OWNER": "observation venue_event_time",
            "PERSISTED_INPUTS": "entry_price/side + pending exit Cap 6.5",
            "RESTART_INPUTS": "Cap 6.5 exit policy state",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 4,
            "REQUIRED_BINDING_CHANGE": "host productive adverse producer evaluation",
        },
        {
            "EXIT_CLASS": "Profit Exit",
            "CANONICAL_PRODUCER": OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_HOST,
            "CURRENT_PLACEHOLDER_OR_STUB": "PolicySignalV0(triggered=False) unbound stub",
            "STATE_OWNER": "Cap 6.5 exit policy state + accounting entry_price",
            "CONFIG_OWNER": "canonical up_distance reused as profit_protection_distance",
            "EVENT_TIME_OWNER": "observation venue_event_time",
            "PERSISTED_INPUTS": "entry_price/side Cap 6.5",
            "RESTART_INPUTS": "Cap 6.5 exit policy state",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 4,
            "REQUIRED_BINDING_CHANGE": "bind profit_protection producer (up_distance reuse)",
        },
        {
            "EXIT_CLASS": "Time Exit",
            "CANONICAL_PRODUCER": TIME_FOUNDATION_OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_HOST,
            "CURRENT_PLACEHOLDER_OR_STUB": "PolicySignalV0(triggered=False) unbound stub",
            "STATE_OWNER": "Cap 6.5 exit policy state entry_event_time + max_hold",
            "CONFIG_OWNER": "CANONICAL_TIME_EXIT_MAX_HOLD_SECONDS (Cap 6.5 binding constant)",
            "EVENT_TIME_OWNER": "observation venue_event_time",
            "PERSISTED_INPUTS": "entry_event_time, max_hold, pending exit",
            "RESTART_INPUTS": "Cap 6.5 exit policy state",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 4,
            "REQUIRED_BINDING_CHANGE": "bind wallclock_time_exit_due_v1",
        },
        {
            "EXIT_CLASS": "Invalidation Exit",
            "CANONICAL_PRODUCER": OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_HOST,
            "CURRENT_PLACEHOLDER_OR_STUB": "PolicySignalV0(triggered=False) unbound stub",
            "STATE_OWNER": "Cap 6.1 confirmation INVALID + Cap 6.5 pending exit",
            "CONFIG_OWNER": "confirmation assessment state",
            "EVENT_TIME_OWNER": "observation venue_event_time",
            "PERSISTED_INPUTS": "confirmation state Cap 6.1 / Cap 6.4",
            "RESTART_INPUTS": "confirmation restart + Cap 6.5 pending exit",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 4,
            "REQUIRED_BINDING_CHANGE": "bind invalidation from confirmation INVALID",
        },
        {
            "EXIT_CLASS": "Reversal Exit",
            "CANONICAL_PRODUCER": ENTRY_EXIT_POLICY_OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_DECISION_OWNER,
            "CURRENT_PLACEHOLDER_OR_STUB": "none (composition-driven inside policy)",
            "STATE_OWNER": "position_state + composition_result",
            "CONFIG_OWNER": "none",
            "EVENT_TIME_OWNER": "trading_epoch",
            "PERSISTED_INPUTS": "position via accounting; composition rebuildable",
            "RESTART_INPUTS": "accounting + confirmation + scope",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 6,
            "REQUIRED_BINDING_CHANGE": "none (already inside policy)",
        },
        {
            "EXIT_CLASS": "Reduce / Hold",
            "CANONICAL_PRODUCER": ENTRY_EXIT_POLICY_OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_DECISION_OWNER,
            "CURRENT_PLACEHOLDER_OR_STUB": "none",
            "STATE_OWNER": "position_state + composition",
            "CONFIG_OWNER": "none",
            "EVENT_TIME_OWNER": "trading_epoch",
            "PERSISTED_INPUTS": "position via accounting",
            "RESTART_INPUTS": "accounting restart",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 5,
            "REQUIRED_BINDING_CHANGE": "none",
        },
        {
            "EXIT_CLASS": "Alpha Entry",
            "CANONICAL_PRODUCER": ENTRY_EXIT_POLICY_OWNER,
            "CURRENT_PRODUCTIVE_CALLER": PRODUCTIVE_DECISION_OWNER,
            "CURRENT_PLACEHOLDER_OR_STUB": "none",
            "STATE_OWNER": "confirmation + composition + reconciliation",
            "CONFIG_OWNER": "Cap 6.3 decision config",
            "EVENT_TIME_OWNER": "trading_epoch",
            "PERSISTED_INPUTS": "Cap 6.1/6.2/6.3/6.4",
            "RESTART_INPUTS": "Cap 6.4 atomic restart",
            "CANONICAL_AUTHORITY": ENTRY_EXIT_POLICY_OWNER,
            "PRECEDENCE_POSITION": 7,
            "REQUIRED_BINDING_CHANGE": "ensure exits precede entry via producer binding",
        },
    ]


def inventory_exit_policy_authority_v1() -> dict[str, Any]:
    return {
        "parallel_exit_authority_created": False,
        "core_logic_changed": False,
        "no_new_parallel_state_model": True,
        "productive_host": PRODUCTIVE_HOST,
        "decision_owner": PRODUCTIVE_DECISION_OWNER,
        "binding_owner": OWNER,
        "matrix": build_exit_authority_matrix_v1(),
    }
