"""Fail-closed reason codes for Cap 6.5 exit-policy producer binding."""

from __future__ import annotations

from enum import Enum


class ExitPolicyBindingFailureCodeV1(str, Enum):
    EXIT_STATE_MISSING = "EXIT_STATE_MISSING"
    EXIT_STATE_CORRUPT = "EXIT_STATE_CORRUPT"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    WRITER_CONFLICT = "WRITER_CONFLICT"
    INSTRUMENT_MISMATCH = "INSTRUMENT_MISMATCH"
    ALPHA_BLOCKED_EXIT_STATE_UNRECOVERABLE = "ALPHA_BLOCKED_EXIT_STATE_UNRECOVERABLE"
    FORCED_EXIT_SIGNAL_FORBIDDEN = "FORCED_EXIT_SIGNAL_FORBIDDEN"
