"""Monetary normalization authority constants (GHV / productive PRE_EXTERNAL).

RUNTIME_AUTHORIZATION_EFFECT=NONE
TRADING_AUTHORITY=NONE
"""

from __future__ import annotations

PACKAGE_MARKER = "GOVERNED_PRODUCTIVE_MONETARY_NORMALIZATION_V1=true"
OWNER = "ops.governed_productive_monetary_normalization_v1"
SCHEMA_VERSION = "governed_productive_monetary_normalization.v1"

CANONICAL_INTERNAL_RISK_NUMERAIRE = "USDC"
PHYSICAL_USDC_REQUIRED_FOR_NUMERAIRE = False

USDT_USDC_ENDPOINT = "/api/v5/market/index-tickers"
USDT_USDC_SOURCE_IDENTITY = "USDC-USDT"
USDT_USDC_SOURCE_FIELD = "idxPx"
USDT_USDC_VENUE = "OKX_EEA"

RAW_RATE_UNIT_USDT_PER_USDC = "USDT/USDC"
NORMALIZED_RATE_UNIT_USDC_PER_USDT = "USDC/USDT"
IDENTITY_RATE_UNIT = "USDC/USDC"

RATE_AUTHORITY = "OKX_PUBLIC_INDEX_OBSERVATION"
AUTHORITY_SEMANTIC_MONETARY_NORMALIZATION = "MONETARY_NORMALIZATION_ONLY"
AUTHORITY_SEMANTIC_IDENTITY = "IDENTITY"

FRESHNESS_POLICY = "FRESH_GET_PER_PRETRADE_DECISION"
COMPOSITE_CONVERSION_AUTHORIZED = False

USDT_USDC_PAIR_NATIVE_ID = "USDC-USDT-SWAP"
