"""Standing constants for P08 distinct first-party evidence V2.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1,
build_okx_live_canary_auth_headers_v1, classify_target_position_state_v1,
classify_position_observation_v1, and build_account_positions_query_v1
(posId path only). Does not mint a second HTTP client, signer, SecretRef
owner, live/testnet/canary authority, or mutation path. Does not repeat
equivalent /account/positions empty-envelope probes. Does not authorize
POST, flatten, P09 work, posSide submit-body proof, funding, balance GET,
or treating empty/history/risk absence as zero.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INST_TYPE,
    DEFAULT_INSTRUMENT_ID,
    ENDPOINT_ACCOUNT_POSITIONS,
    ENDPOINT_ACCOUNT_POSITIONS_HISTORY,
    ENDPOINT_ACCOUNT_POSITION_RISK,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)
from src.ops.section_11_13_5_p08_position_observation_v1.constants_v1 import (
    CASE_A_TARGET_NONZERO,
    CASE_B_TARGET_ZERO,
    CASE_C_EMPTY_DATA_NOT_ZERO,
    CASE_D_TARGET_NOT_OBSERVED,
    CASE_E_HTTP_OR_OKX_ERROR,
    CASE_F_AMBIGUOUS,
    EMPTY_DATA_IS_ZERO as PREDECESSOR_EMPTY_DATA_IS_ZERO,
    NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC,
    NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_UNRESOLVED,
    NEXT_AUTHORITY_BOUNDARY_CASE_B,
    NEXT_AUTHORITY_BOUNDARY_CASE_D,
    NEXT_AUTHORITY_BOUNDARY_CASE_E,
    NEXT_AUTHORITY_BOUNDARY_CASE_F,
    P08_CANONICAL_DEFINITION,
    RESULT_CLASS_200_OKX_0,
    RESULT_CLASS_401_50110,
    RESULT_CLASS_OTHER,
    RESULT_CLASS_TRANSPORT,
)

CAPABILITY_ID = "P08_DISTINCT_FIRST_PARTY_EVIDENCE_V2"
PACKAGE_MARKER = "P08_DISTINCT_FIRST_PARTY_EVIDENCE_V2=true"
OWNER = "ops.section_11_13_5_p08_distinct_first_party_evidence_v1"
CONTRACT_VERSION = "v2"
SCHEMA_VERSION = "p08_distinct_first_party_evidence.v2"
OWNER_GO = "PEAK_TRADE_OWNER_GO_P08_DISTINCT_FIRST_PARTY_EVIDENCE_MAXIMUM_SAFE_LEVERAGE_V2"
WORKPACKAGE_ID = "OKX_EEA_P08_DISTINCT_FIRST_PARTY_EVIDENCE_MAX_SAFE_LEVERAGE_V2"
THIS_SLICE = "11.13.5.P08_DISTINCT_FIRST_PARTY_EVIDENCE"
PREDECESSOR_SLICE = "11.13.5.P08_EMPTY_DATA_NOT_ZERO"
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "fd22be6386894e3982aa83ebd4e7c0365038bcf0"
AUTHORIZED_HOST = "eea.okx.com"
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
TARGET_INST_TYPE = DEFAULT_INST_TYPE

AUTHORIZED_OPERATION = "DISTINCT_AUTHENTICATED_NON_MUTATING_PRIVATE_GETS_TO_DISCRIMINATE_P08"
AUTHORIZED_ENDPOINTS = (
    "GET /api/v5/account/positions-history",
    "GET /api/v5/account/account-position-risk",
    "GET /api/v5/account/positions?posId=",
)
ENDPOINT_ACCOUNT_POSITIONS_REUSED = ENDPOINT_ACCOUNT_POSITIONS
AUTHORIZED_ENDPOINT_PATHS: tuple[str, ...] = (
    ENDPOINT_ACCOUNT_POSITIONS_HISTORY,
    ENDPOINT_ACCOUNT_POSITION_RISK,
    ENDPOINT_ACCOUNT_POSITIONS_REUSED,
)

MAX_NETWORK_REQUEST_COUNT = 5
MAX_HTTP_EXCHANGE_COUNT = 5
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
HISTORY_PAGE_LIMIT = 100
RETRY_ALLOWED = False
RETRY_AUTHORIZED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
PUBLIC_GET_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
P08_OBSERVATION_ALLOWED = True
P08_CLOSE_ALLOWED = True
FUNDING_ALLOWED = False
BALANCE_GET_ALLOWED = False
CONFIG_GET_ALLOWED = False
MAX_SIZE_GET_ALLOWED = False
POSITIONS_UNFILTERED_GET_ALLOWED = False
POSITIONS_INSTID_GET_ALLOWED = False
POSITIONS_INSTTYPE_GET_ALLOWED = False
POSITIONS_HISTORY_GET_ALLOWED = True
ACCOUNT_POSITION_RISK_GET_ALLOWED = True
POSID_POSITIONS_GET_ALLOWED = True
POSID_GET_REQUIRES_INDEPENDENT_PROOF = True
KEY_ROTATION_ALLOWED = False
PERMISSION_CHANGE_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
POSITION_CREATION_ALLOWED = False
POSITION_MODIFICATION_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
G_POSMODE_REOPEN_ALLOWED = False
G_POSMODE_CLOSE_ALLOWED = False
P09_WORK_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False

GET_ROLE_TARGET_HISTORY = "TARGET_POSITIONS_HISTORY"
GET_ROLE_TYPED_HISTORY = "TYPED_POSITIONS_HISTORY"
GET_ROLE_HISTORY_PAGINATION = "TARGET_HISTORY_PAGINATION"
GET_ROLE_ACCOUNT_POSITION_RISK = "ACCOUNT_POSITION_RISK"
GET_ROLE_POSID_POSITIONS = "POSID_ACCOUNT_POSITIONS"

GET_PURPOSE_TARGET_HISTORY = "POSID_RECOVERY_AND_THREE_MONTH_EVER_HELD_WINDOW"
GET_PURPOSE_TYPED_HISTORY = "DISCRIMINATE_TARGET_FILTER_INCOMPLETENESS_VS_TYPED_EMPTY"
GET_PURPOSE_HISTORY_PAGINATION = "CONTINUE_FIRST_PARTY_AFTER_CURSOR_WHEN_PAGE_FULL"
GET_PURPOSE_ACCOUNT_POSITION_RISK = "INDEPENDENT_POSDATA_CROSS_CHECK_NOT_CANONICAL"
GET_PURPOSE_POSID_POSITIONS = "EXPLICIT_POSID_CLOSED_ELICITATION_CURRENT_STATE"

FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/config",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/account/adjust-leverage-info",
    "/api/v5/account/max-avail-size",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
)
FORBIDDEN_HTTP_METHODS: tuple[str, ...] = (
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "HEAD",
    "OPTIONS",
    "TRACE",
    "CONNECT",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
REUSED_CLASSIFIER = "classify_target_position_state_v1"
REUSED_POSITION_OBSERVATION_CLASSIFIER = "classify_position_observation_v1"
REUSED_POSITIONS_QUERY_BUILDER = "build_account_positions_query_v1"
REUSED_PREDECESSOR_PACKAGE = "src/ops/section_11_13_5_p08_empty_data_not_zero_v1"
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False
SECOND_POSITION_AUTHORITY_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET_PACKAGE = False

EVIDENCE_DIRNAME = "section_11_13_5_p08_distinct_first_party_evidence_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)
P08_CANONICAL_DEFINITION_REUSED = P08_CANONICAL_DEFINITION
FRESHNESS_POLICY = (
    "FLATTEN_PRE_SEND_MAX_AGE_MS=5000;"
    "THIS_WINDOW_SAMPLES_AGE_AFTER_LAST_GET_AND_IS_NOT_FLATTEN_SEND_PERMIT"
)
EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False
FILTERED_EMPTY_IS_ZERO = False
TYPED_EMPTY_IS_ZERO = False
HISTORY_EMPTY_IS_ZERO = False
HISTORY_EMPTY_IS_NEVER_HELD = False
HISTORY_EMPTY_IS_CURRENT_ZERO = False
RISK_POSDATA_EMPTY_IS_ZERO = False
CROSS_CHECK_IS_CANONICAL_AUTHORITY = False
HISTORICAL_STATE_IS_CURRENT_STATE = False
DOCUMENTATION_SEMANTICS_ARE_OBSERVED_ACCOUNT_STATE = False

HISTORICAL_P08_EMPTY_DATA_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_p08_empty_data_not_zero_v1/20260903T193620Z"
)
HISTORICAL_P08_POSITION_OBSERVATION_PACK = (
    "evidence/ops/section_11_13_5_p08_position_observation_v1/20260903T190424Z"
)
HISTORICAL_Z2CH_HISTORY_PACK_NOTE = (
    "§11.13.5.Z2CH positions-history H0 2026-08-28 is historical, not current 08 proof"
)
HISTORICAL_EMPTY_ENVELOPE_SHA256 = (
    "fc24d69479edbb84f22c7d5bd4525349734056ad3baf7a5adf7e553f68c06a3a"
)
HISTORICAL_EMPTY_SHA_IS_CURRENT_08_PROOF = False
Z2CH_HISTORY_QUERY_GRAMMAR = "PROVEN_FIRST_PARTY"
Z2CH_HISTORY_RETENTION = "FIRST_PARTY_LAST_3_MONTHS_NOT_LIFETIME"
Z2V_RISK_QUERY_GRAMMAR = "PROVEN_FIRST_PARTY_INSTTYPE_FUTURES"

RESULT_CLASS_200_OKX_0_REUSED = RESULT_CLASS_200_OKX_0
RESULT_CLASS_401_50110_REUSED = RESULT_CLASS_401_50110
RESULT_CLASS_OTHER_REUSED = RESULT_CLASS_OTHER
RESULT_CLASS_TRANSPORT_REUSED = RESULT_CLASS_TRANSPORT

CASE_A_TARGET_NONZERO_REUSED = CASE_A_TARGET_NONZERO
CASE_B_TARGET_ZERO_REUSED = CASE_B_TARGET_ZERO
CASE_C_EMPTY_DATA_NOT_ZERO_REUSED = CASE_C_EMPTY_DATA_NOT_ZERO
CASE_D_TARGET_NOT_OBSERVED_REUSED = CASE_D_TARGET_NOT_OBSERVED
CASE_E_HTTP_OR_OKX_ERROR_REUSED = CASE_E_HTTP_OR_OKX_ERROR
CASE_F_AMBIGUOUS_REUSED = CASE_F_AMBIGUOUS

HISTORY_CLASS_EMPTY = "HISTORY_EMPTY_NOT_NEVER_HELD_NOT_CURRENT_ZERO"
HISTORY_CLASS_TARGET_POSID_PROVEN = "HISTORY_TARGET_ROW_POSID_PROVEN"
HISTORY_CLASS_TARGET_POSID_ABSENT = "HISTORY_TARGET_ROW_POSID_ABSENT"
HISTORY_CLASS_TARGET_NOT_OBSERVED = "HISTORY_TARGET_NOT_OBSERVED"
HISTORY_CLASS_AMBIGUOUS_POSID = "HISTORY_AMBIGUOUS_MULTIPLE_POSID"
HISTORY_CLASS_HTTP_OR_OKX_ERROR = "HISTORY_HTTP_OR_OKX_ERROR"

RISK_CLASS_POSDATA_EMPTY = "RISK_POSDATA_EMPTY_NOT_ZERO"
RISK_CLASS_TARGET_OBSERVED = "RISK_TARGET_ROW_OBSERVED"
RISK_CLASS_TARGET_NOT_OBSERVED = "RISK_TARGET_NOT_OBSERVED"
RISK_CLASS_AMBIGUOUS = "RISK_AMBIGUOUS_OR_CONTRADICTORY"
RISK_CLASS_HTTP_OR_OKX_ERROR = "RISK_HTTP_OR_OKX_ERROR"

NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC
NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_UNRESOLVED_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_UNRESOLVED
NEXT_AUTHORITY_BOUNDARY_CASE_B_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_B
NEXT_AUTHORITY_BOUNDARY_CASE_D_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_D
NEXT_AUTHORITY_BOUNDARY_CASE_E_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_E
NEXT_AUTHORITY_BOUNDARY_CASE_F_REUSED = NEXT_AUTHORITY_BOUNDARY_CASE_F
NEXT_AUTHORITY_BOUNDARY_CHANNELS_UNRESOLVED = (
    "SEPARATE_OWNER_GO_REQUIRED_P08_STILL_NOT_CLOSED_DISTINCT_CHANNELS_DO_NOT_PROVE_CURRENT_STATE"
)
NEXT_AUTHORITY_BOUNDARY_CONTRADICTION = (
    "SEPARATE_OWNER_GO_REQUIRED_AFTER_CONTRADICTORY_DISTINCT_CHANNELS_NO_RETRY_UNDER_THIS_GO"
)
NEXT_AUTHORITY_BOUNDARY_WRITE_BOUNDARY = (
    "SEPARATE_OWNER_GO_REQUIRED_BEFORE_WRITE_EXECUTION_LIVE_CANARY_CREDENTIAL_OR_FUNDING"
)

PREDECESSOR_EMPTY_DATA_IS_ZERO_REUSED = PREDECESSOR_EMPTY_DATA_IS_ZERO
