"""PRE_EXTERNAL → external-effect boundary bounded WP v1 (census + static proof only)."""

from __future__ import annotations

from src.ops.pre_external_to_external_effect_boundary_bounded_wp_v1.constants_v1 import (
    BASELINE_ORIGIN_MAIN_SHA,
    CANARY_WIRE_SEND_HARNESS_PREFIX,
    CONTRACT_VERSION,
    CONTINUOUS_RUN_ADJUDICATION_CLASS,
    ENVELOPE_BOUND_SEND_SEAM_OWNER,
    EXECUTION_BOUNDARY_OWNER,
    EXTERNAL_EFFECT_GATE_OWNER,
    EXTERNAL_EFFECT_SINK_SURFACES,
    INTENTIONALLY_ISOLATED_OWNER_GO_POST_SLICES,
    INTENTIONALLY_LEGACY_PRE_EXTERNAL_CLAIM_MODULES,
    OWNER,
    PACKAGE_MARKER,
    PERMIT_MINT_ADJUDICATION_CLASS,
    PRE_EXTERNAL_PRODUCTIVE_ENTRY_MODULES,
    PRE_EXTERNAL_TO_EXTERNAL_EFFECT_BOUNDARY_COMPLETE,
    REQUIRED_CLOSURE_COUNT,
    STANDING_LIVE_PREDICATES_ADJUDICATION_CLASS,
    STEP_29Q_ADJUDICATION_CLASS,
    UNKNOWN_BOUNDARY_PATH_COUNT,
)
from src.ops.pre_external_to_external_effect_boundary_bounded_wp_v1.proof_v1 import (
    PreExternalToExternalEffectBoundaryProofResultV1,
    prove_pre_external_to_external_effect_boundary_v1,
)

__all__ = [
    "BASELINE_ORIGIN_MAIN_SHA",
    "CANARY_WIRE_SEND_HARNESS_PREFIX",
    "CONTRACT_VERSION",
    "CONTINUOUS_RUN_ADJUDICATION_CLASS",
    "ENVELOPE_BOUND_SEND_SEAM_OWNER",
    "EXECUTION_BOUNDARY_OWNER",
    "EXTERNAL_EFFECT_GATE_OWNER",
    "EXTERNAL_EFFECT_SINK_SURFACES",
    "INTENTIONALLY_ISOLATED_OWNER_GO_POST_SLICES",
    "INTENTIONALLY_LEGACY_PRE_EXTERNAL_CLAIM_MODULES",
    "OWNER",
    "PACKAGE_MARKER",
    "PERMIT_MINT_ADJUDICATION_CLASS",
    "PRE_EXTERNAL_PRODUCTIVE_ENTRY_MODULES",
    "PRE_EXTERNAL_TO_EXTERNAL_EFFECT_BOUNDARY_COMPLETE",
    "PreExternalToExternalEffectBoundaryProofResultV1",
    "REQUIRED_CLOSURE_COUNT",
    "STANDING_LIVE_PREDICATES_ADJUDICATION_CLASS",
    "STEP_29Q_ADJUDICATION_CLASS",
    "UNKNOWN_BOUNDARY_PATH_COUNT",
    "prove_pre_external_to_external_effect_boundary_v1",
]
