"""Constants for CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1"
PACKAGE_MARKER = "CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1=true"
OWNER = "ops.capability_11_1_execution_domain_and_order_lifecycle_contracts_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "capability_11_1_execution_domain_and_order_lifecycle_contracts.v1"
PRODUCER_VERSION = "capability_11_1_execution_domain_and_order_lifecycle_contracts.v1"
CONTRACT_VERSION = "v1"

# Hard safety bindings (non-authorizing contracts/scaffolding only).
CORE_LOGIC_CHANGE = False
CORE_LOGIC_CHANGE_ALLOWED = False
ACTIVATION_STATE = "not_activated"
ACTIVATION_CHANGED = False
RUNTIME_ACTIVATED = False
LIVE_TRADING_ALLOWED = False
TESTNET_ALLOWED = False
PAPER_EXCHANGE_ORDERS_ALLOWED = False
EXCHANGE_CREDENTIAL_USE_ALLOWED = False
REAL_CAPITAL_MOVEMENT_ALLOWED = False
NETWORK_SESSION_ALLOWED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
RULESET_MUTATION_ALLOWED = False
NOTION_MUTATION_ALLOWED = False

TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False
EXCHANGE_CREDENTIAL_USE_AUTHORIZED = False
REAL_CAPITAL_MOVEMENT_AUTHORIZED = False
OWNER_GO_REQUIRED_FOR_EACH_ACTIVATION = True

LIVE_PATH_CHANGED = False
TESTNET_PATH_CHANGED = False
ORDER_PATH_CHANGED = False
EXCHANGE_CREDENTIAL_PATH_CHANGED = False
NETWORK_SESSION_STARTED = False

VOLATILITY_NUMERIC_MAX_AGE_ENFORCING = False
NUMERIC_MAX_AGE_EFFECT = "DIAGNOSTIC_ONLY"

# Architecture invariants.
ONE_DECISION_AUTHORITY_CHAIN = True
ONE_CANONICAL_INTENT_SCHEMA = True
ONE_CANONICAL_EXECUTION_EVENT_SCHEMA = True
ONE_ACCOUNTING_AUTHORITY = True
ONE_PORTFOLIO_AUTHORITY = True
ONE_RECONCILIATION_AUTHORITY = True
MODE_SPECIFIC_EXECUTION_SIDE_EFFECTS_ONLY = True
NO_LIVE_ONLY_ALPHA_LOGIC = True
NO_TESTNET_ONLY_ALPHA_LOGIC = True
NO_EXECUTION_ADAPTER_DECISION_AUTHORITY = True

# Reachability claims for Cap 11.1.
SIMULATED_EXECUTION_PORT_RETAINED = True
SIMULATED_EXECUTION_PORT_SOLE_REACHABLE = True
TESTNET_EXECUTION_PORT_DECLARED = True
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_PORT_DECLARED = True
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
EXCHANGE_CREDENTIAL_ACCESS_REACHABLE = False
REAL_CAPITAL_MOVEMENT_REACHABLE = False

# Existing owners consumed unchanged.
CANONICAL_INTENT_OWNER = "src.governance.canonical_order_intent_v1"
SIMULATED_EXECUTION_PORT_OWNER = (
    "src.ops.single_future_stateful_no_order_runtime_activation_v1.simulated_execution_port_v1"
)
NO_ORDER_HOST = (
    "src/ops/wallclock_full_canonical_decision_to_simulated_economics_runtime_bridge_v1/"
    "decision_economics_cycle_bridge_v1.py"
)

CLIENT_ORDER_ID_CONTRACT_VERSION = "phase_11_client_order_id_contract_v1"
EXECUTION_EVENT_SCHEMA_VERSION = "canonical_execution_event_schema_v1"
ORDER_LIFECYCLE_CONTRACT_VERSION = "phase_11_order_lifecycle_contract_v1"
EXECUTION_PORT_CONTRACT_VERSION = "phase_11_mode_specific_execution_port_contract_v1"

EVIDENCE_DIRNAME = "capability_11_1_execution_domain_and_order_lifecycle_contracts_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
