"""Max-age parameter research design + evidence accumulation contract v1.

Closes research *prerequisites* only: productive reuse/restart labeling join,
typed research-evidence schema, deterministic non-enforcing counterfactual
evaluation, preregistered dimensions/metrics/controls, and durable
multi-session / multi-regime evidence accumulation.

Does **not** select a numeric threshold, recommend candidate values, execute
parameter research, enable Alpha enforcement, suppress entries by age, alter
Exit/Risk/Safety authority, rematerialize estimates, or authorize live paths.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence, Union

from trading.master_v2.canonical_volatility_numeric_max_age_policy_contract_and_non_enforcing_telemetry_v1 import (
    AGE_FORMULA,
    AGE_REFERENCE_CLOCK,
    ENFORCEMENT_ENABLED as POLICY_ENFORCEMENT_ENABLED,
    NUMERIC_MAX_AGE_DECIDED as POLICY_NUMERIC_MAX_AGE_DECIDED,
    THRESHOLD_STATUS_UNRESOLVED,
    CanonicalVolatilityMaxAgePolicyEvidenceV1,
    evaluate_canonical_volatility_estimate_age_policy_v1,
)

PACKAGE_MARKER = (
    "MASTER_V2_CANONICAL_VOLATILITY_NUMERIC_MAX_AGE_PARAMETER_RESEARCH_"
    "DESIGN_AND_EVIDENCE_ACCUMULATION_CONTRACT_V1=true"
)

CAPABILITY_ID = (
    "MASTER_V2_CANONICAL_VOLATILITY_NUMERIC_MAX_AGE_PARAMETER_RESEARCH_"
    "DESIGN_AND_EVIDENCE_ACCUMULATION_CONTRACT_V1"
)
CAPABILITY_VERSION = (
    "canonical_volatility_numeric_max_age_parameter_research_design_"
    "and_evidence_accumulation_contract/v1"
)
RESEARCH_DESIGN_OWNER = (
    "trading.master_v2."
    "canonical_volatility_numeric_max_age_parameter_research_design_"
    "and_evidence_accumulation_contract_v1"
)
JOIN_CONTRACT_NAME = "canonical_volatility_numeric_max_age_research_evidence_join"
JOIN_CONTRACT_VERSION = "canonical_volatility_numeric_max_age_research_evidence_join/v1"
ACCUMULATION_LEDGER_NAME = "canonical_volatility_numeric_max_age_research_evidence_ledger"
ACCUMULATION_LEDGER_VERSION = "canonical_volatility_numeric_max_age_research_evidence_ledger/v1"
PREREGISTRATION_CONTRACT_VERSION = (
    "canonical_volatility_numeric_max_age_research_preregistration/v1"
)

NUMERIC_MAX_AGE_DECIDED = False
NUMERIC_MAX_AGE_SECONDS = None
THRESHOLD_STATUS = THRESHOLD_STATUS_UNRESOLVED
ENFORCEMENT_ENABLED = False
ENFORCEMENT_APPLIED = False
ALPHA_ENFORCEMENT_ALLOWED = False
PARAMETER_RESEARCH_EXECUTED = False
THRESHOLD_SELECTED = False
THRESHOLD_RECOMMENDATION_PRODUCED = False
COUNTERFACTUAL_ENFORCEMENT_ENABLED = False
PRESENCE_GATE_AUTHORITY_UNCHANGED = True
EXIT_RISK_SAFETY_INDEPENDENCE_MUST_REMAIN = True
EVENT_TIME_IS_AGE_AUTHORITY = True
WALLCLOCK_IS_NOT_AGE_AUTHORITY = True
RECEIVE_TIME_IS_NOT_AGE_AUTHORITY = True
DECISION_TIME_IS_NOT_AGE_AUTHORITY = True
REUSE_MUST_NOT_REFRESH_ESTIMATE_AS_OF = True
RESTART_MUST_NOT_REMATERIALIZE_VOLATILITY = True
LIVE_AUTHORIZATION = False
HARD_STOP = True

NEXT_AFTER_THIS_CAPABILITY = (
    "SEPARATE_OPERATOR_AUTHORIZED_NUMERIC_MAX_AGE_PARAMETER_RESEARCH_AND_SELECTION"
)

DEFAULT_DURABLE_LEDGER_RELATIVE_PATH = (
    "docs/evidence/canonical_volatility_numeric_max_age_research_evidence_ledger_v1/"
    "research_evidence_ledger.jsonl"
)

RESEARCH_QUESTION_V1 = (
    "Which event-time numeric max-age threshold region, if any, can later be "
    "operator-selected for canonical volatility estimates without Alpha "
    "enforcement in this capability, such that stale-estimate acceptance and "
    "fresh-estimate rejection trade off robustly across sessions, regimes, "
    "instruments, cost assumptions, and a sealed final holdout — without "
    "selecting a value here?"
)

CANDIDATE_THRESHOLD_SOURCE_V1 = (
    "EXPLICIT_OPERATOR_OR_CALLER_SUPPLIED_CANDIDATE_ARGUMENTS_ONLY;"
    "NO_IMPLICIT_DEFAULT;"
    "NO_PRODUCTIVE_POLICY_LITERAL;"
    "NO_AUTOGENERATED_GRID_IN_THIS_CAPABILITY"
)

DATASET_SCOPE_V1 = (
    "STRUCTURAL_SCOPE_ONLY:"
    "offline_hardening_bridge_and_operator_authorized_research_ledgers;"
    "no_live_market_stream;"
    "no_holdout_panel_access_in_this_capability"
)

SESSION_SCOPE_V1 = (
    "MULTI_SESSION_REQUIRED:"
    "each_ledger_record_binds_nonempty_session_id;"
    "cross_session_join_forbidden;"
    "minimum_distinct_sessions_defined_in_minimum_evidence_requirements"
)

INSTRUMENT_SCOPE_V1 = (
    "PER_RECORD_INSTRUMENT_BINDING_REQUIRED:"
    "each_ledger_record_binds_nonempty_instrument_id;"
    "cross_instrument_join_forbidden;"
    "no_universe_wide_threshold_collapse_in_this_capability"
)

COST_ASSUMPTIONS_V1 = (
    "RECONSTRUCTION_COST_AND_SLIPPAGE_MUST_BE_EXPLICIT_IN_LATER_RESEARCH;"
    "NET_PNL_AFTER_COSTS_IS_A_PREREGISTERED_METRIC;"
    "NO_ZERO_COST_OPTIMISM;"
    "NO_COST_ASSUMPTION_NUMERIC_DEFAULT_SELECTED_HERE"
)

PURGED_SPLIT_POLICY_V1 = (
    "PURGED_CHRONOLOGICAL_SPLITS_REQUIRED_FOR_LATER_PARAMETER_RESEARCH;"
    "TRAIN_VALIDATION_BOUNDARY_MUST_PURGE_OVERLAPPING_EVENT_TIME_WINDOWS;"
    "NO_RANDOM_IID_SHUFFLE_SPLITS;"
    "SPLIT_EXECUTION_NOT_PERFORMED_IN_THIS_CAPABILITY"
)

EMBARGO_POLICY_V1 = (
    "EVENT_TIME_EMBARGO_BETWEEN_TRAIN_VALIDATION_AND_HOLDOUT_REQUIRED;"
    "EMBARGO_DURATION_MUST_BE_OPERATOR_DECLARED_BEFORE_RESEARCH_EXECUTION;"
    "NO_EMBARGO_BYPASS;"
    "EMBARGO_NOT_EXECUTED_IN_THIS_CAPABILITY"
)

WALK_FORWARD_DESIGN_V1 = (
    "ANCHORED_OR_ROLLING_EVENT_TIME_WALK_FORWARD_REQUIRED_FOR_LATER_RESEARCH;"
    "EACH_FOLD_REUSES_PURGED_SPLITS_AND_EMBARGO;"
    "NO_SINGLE_SHOT_IN_SAMPLE_SELECTION;"
    "WALK_FORWARD_NOT_EXECUTED_IN_THIS_CAPABILITY"
)

FINAL_HOLDOUT_POLICY_V1 = (
    "SEALED_FINAL_HOLDOUT_REQUIRED_BEFORE_ANY_THRESHOLD_SELECTION;"
    "HOLDOUT_ACCESS_FORBIDDEN_UNTIL_SEPARATE_OPERATOR_GO;"
    "HOLDOUT_MAY_ONLY_CONFIRM_OR_REJECT_A_PREDECLARED_ROBUST_REGION;"
    "NO_HOLDOUT_TUNING;"
    "HOLDOUT_NOT_EXECUTED_IN_THIS_CAPABILITY"
)


class MaxAgeResearchDesignContractError(ValueError):
    """Fail-closed invalid research-design / evidence-join construction."""


class MaxAgeResearchDimensionV1(str, Enum):
    CANDIDATE_THRESHOLD_DOMAIN = "CANDIDATE_THRESHOLD_DOMAIN"
    ESTIMATOR_HORIZON_STRATA = "ESTIMATOR_HORIZON_STRATA"
    PRODUCER_CADENCE_STRATA = "PRODUCER_CADENCE_STRATA"
    INSTRUMENT_STRATA = "INSTRUMENT_STRATA"
    VOLATILITY_REGIME_STRATA = "VOLATILITY_REGIME_STRATA"
    MARKET_STATE_STRATA = "MARKET_STATE_STRATA"
    SESSION_DAY_STRATA = "SESSION_DAY_STRATA"
    STRESS_SCENARIO_STRATA = "STRESS_SCENARIO_STRATA"
    COST_SLIPPAGE_RECONSTRUCTION = "COST_SLIPPAGE_RECONSTRUCTION"


class MaxAgeResearchMetricV1(str, Enum):
    STALE_ESTIMATE_ACCEPTANCE_RATE = "STALE_ESTIMATE_ACCEPTANCE_RATE"
    FRESH_ESTIMATE_REJECTION_RATE = "FRESH_ESTIMATE_REJECTION_RATE"
    UNKNOWN_ABSENT_TRANSITION_RATE = "UNKNOWN_ABSENT_TRANSITION_RATE"
    DECISION_ENTRY_SUPPRESSION_RATE = "DECISION_ENTRY_SUPPRESSION_RATE"
    EXIT_INTERFERENCE_RATE = "EXIT_INTERFERENCE_RATE"
    STATE_TRANSITION_STABILITY = "STATE_TRANSITION_STABILITY"
    REPLAY_DETERMINISM = "REPLAY_DETERMINISM"
    POLLING_CADENCE_SENSITIVITY = "POLLING_CADENCE_SENSITIVITY"
    NET_PNL_AFTER_COSTS = "NET_PNL_AFTER_COSTS"
    SHARPE = "SHARPE"
    PROFIT_FACTOR = "PROFIT_FACTOR"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    TRADE_COUNT_STABILITY = "TRADE_COUNT_STABILITY"
    PARAMETER_REGION_STABILITY = "PARAMETER_REGION_STABILITY"


class MaxAgeLeakageControlV1(str, Enum):
    EVENT_TIME_ONLY_AGE_CLOCK = "EVENT_TIME_ONLY_AGE_CLOCK"
    NO_WALLCLOCK_IN_AGE = "NO_WALLCLOCK_IN_AGE"
    NO_RECEIVE_TIME_IN_AGE = "NO_RECEIVE_TIME_IN_AGE"
    NO_DECISION_TIME_IN_AGE = "NO_DECISION_TIME_IN_AGE"
    NO_LOOKAHEAD_LABELS = "NO_LOOKAHEAD_LABELS"
    REUSE_MUST_NOT_REFRESH_AS_OF = "REUSE_MUST_NOT_REFRESH_AS_OF"
    NO_REMATERIALIZATION_AS_FRESHNESS = "NO_REMATERIALIZATION_AS_FRESHNESS"
    NO_IMPLICIT_THRESHOLD_DEFAULT = "NO_IMPLICIT_THRESHOLD_DEFAULT"


class MaxAgeStressControlV1(str, Enum):
    HISTORY_GAP = "HISTORY_GAP"
    OUT_OF_ORDER_REJECT = "OUT_OF_ORDER_REJECT"
    RESTART_WITHOUT_ESTIMATE = "RESTART_WITHOUT_ESTIMATE"
    LONG_NO_SAMPLE_REUSE = "LONG_NO_SAMPLE_REUSE"
    CLOCK_TRUST_UNTRUSTED = "CLOCK_TRUST_UNTRUSTED"
    DATA_INTEGRITY_UNTRUSTED = "DATA_INTEGRITY_UNTRUSTED"
    WARMUP_WITHOUT_ESTIMATE = "WARMUP_WITHOUT_ESTIMATE"
    DUPLICATE_SAMPLE_REUSE = "DUPLICATE_SAMPLE_REUSE"


class MaxAgeRobustnessRequirementV1(str, Enum):
    MULTI_SESSION_COVERAGE = "MULTI_SESSION_COVERAGE"
    MULTI_REGIME_COVERAGE = "MULTI_REGIME_COVERAGE"
    CADENCE_VS_STALENESS_IDENTIFIABILITY = "CADENCE_VS_STALENESS_IDENTIFIABILITY"
    OFFLINE_RUNTIME_EVENT_TIME_EQUIVALENCE = "OFFLINE_RUNTIME_EVENT_TIME_EQUIVALENCE"
    EXIT_INTERFERENCE_NEAR_ZERO = "EXIT_INTERFERENCE_NEAR_ZERO"
    DETERMINISTIC_COUNTERFACTUAL_REPLAY = "DETERMINISTIC_COUNTERFACTUAL_REPLAY"
    NO_ALPHA_ENFORCEMENT_DURING_RESEARCH = "NO_ALPHA_ENFORCEMENT_DURING_RESEARCH"


class MaxAgeRejectionCriterionV1(str, Enum):
    SINGLE_METRIC_SHARPE_MAXIMIZATION = "SINGLE_METRIC_SHARPE_MAXIMIZATION"
    SINGLE_METRIC_PNL_MAXIMIZATION = "SINGLE_METRIC_PNL_MAXIMIZATION"
    SINGLE_METRIC_TRADE_COUNT_MAXIMIZATION = "SINGLE_METRIC_TRADE_COUNT_MAXIMIZATION"
    SINGLE_BEST_CONFIGURATION_WITHOUT_REGION = "SINGLE_BEST_CONFIGURATION_WITHOUT_REGION"
    IN_SAMPLE_ONLY_SELECTION = "IN_SAMPLE_ONLY_SELECTION"
    HOLDOUT_TUNING_OR_HOLDOUT_LEAKAGE = "HOLDOUT_TUNING_OR_HOLDOUT_LEAKAGE"
    COST_IGNORING_SELECTION = "COST_IGNORING_SELECTION"
    DRAWDOWN_IGNORING_SELECTION = "DRAWDOWN_IGNORING_SELECTION"
    INSUFFICIENT_MULTI_SESSION_COVERAGE = "INSUFFICIENT_MULTI_SESSION_COVERAGE"
    INSUFFICIENT_MULTI_REGIME_COVERAGE = "INSUFFICIENT_MULTI_REGIME_COVERAGE"
    PARAMETER_REGION_UNSTABLE = "PARAMETER_REGION_UNSTABLE"
    EXIT_INTERFERENCE_ABOVE_NEAR_ZERO = "EXIT_INTERFERENCE_ABOVE_NEAR_ZERO"
    ENFORCEMENT_OR_ALPHA_MUTATION_ATTEMPT = "ENFORCEMENT_OR_ALPHA_MUTATION_ATTEMPT"


class MaxAgeSelectionCriterionV1(str, Enum):
    ROBUST_THRESHOLD_REGION_NOT_POINT = "ROBUST_THRESHOLD_REGION_NOT_POINT"
    NET_PNL_AFTER_COSTS_NON_DEGRADED = "NET_PNL_AFTER_COSTS_NON_DEGRADED"
    MAX_DRAWDOWN_BOUNDED = "MAX_DRAWDOWN_BOUNDED"
    PARAMETER_REGION_STABILITY_REQUIRED = "PARAMETER_REGION_STABILITY_REQUIRED"
    MULTI_SESSION_AGREEMENT_REQUIRED = "MULTI_SESSION_AGREEMENT_REQUIRED"
    MULTI_REGIME_AGREEMENT_REQUIRED = "MULTI_REGIME_AGREEMENT_REQUIRED"
    FINAL_HOLDOUT_CONFIRMATION_REQUIRED = "FINAL_HOLDOUT_CONFIRMATION_REQUIRED"
    EXIT_INTERFERENCE_NEAR_ZERO_REQUIRED = "EXIT_INTERFERENCE_NEAR_ZERO_REQUIRED"
    NO_BEST_SHARPE_POINT_SELECTION = "NO_BEST_SHARPE_POINT_SELECTION"
    NO_MAX_PNL_POINT_SELECTION = "NO_MAX_PNL_POINT_SELECTION"
    NO_MAX_TRADE_COUNT_POINT_SELECTION = "NO_MAX_TRADE_COUNT_POINT_SELECTION"
    OPERATOR_AUTHORIZED_SELECTION_ONLY_AFTER_RESEARCH = (
        "OPERATOR_AUTHORIZED_SELECTION_ONLY_AFTER_RESEARCH"
    )


class CounterfactualAgeLabelV1(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    WOULD_BE_FRESH_IF_THRESHOLD = "WOULD_BE_FRESH_IF_THRESHOLD"
    WOULD_BE_STALE_IF_THRESHOLD = "WOULD_BE_STALE_IF_THRESHOLD"
    AGE_UNAVAILABLE = "AGE_UNAVAILABLE"
    THRESHOLD_ARGUMENT_INVALID = "THRESHOLD_ARGUMENT_INVALID"


PREREGISTERED_RESEARCH_DIMENSIONS: tuple[str, ...] = tuple(
    d.value for d in MaxAgeResearchDimensionV1
)
PREREGISTERED_REGIME_DIMENSIONS: tuple[str, ...] = (
    MaxAgeResearchDimensionV1.VOLATILITY_REGIME_STRATA.value,
    MaxAgeResearchDimensionV1.MARKET_STATE_STRATA.value,
    MaxAgeResearchDimensionV1.SESSION_DAY_STRATA.value,
    MaxAgeResearchDimensionV1.STRESS_SCENARIO_STRATA.value,
)
PREREGISTERED_RESEARCH_METRICS: tuple[str, ...] = tuple(m.value for m in MaxAgeResearchMetricV1)
PREREGISTERED_LEAKAGE_CONTROLS: tuple[str, ...] = tuple(c.value for c in MaxAgeLeakageControlV1)
PREREGISTERED_STRESS_CONTROLS: tuple[str, ...] = tuple(c.value for c in MaxAgeStressControlV1)
PREREGISTERED_ROBUSTNESS_REQUIREMENTS: tuple[str, ...] = tuple(
    r.value for r in MaxAgeRobustnessRequirementV1
)
PREREGISTERED_REJECTION_CRITERIA: tuple[str, ...] = tuple(
    c.value for c in MaxAgeRejectionCriterionV1
)
PREREGISTERED_SELECTION_CRITERIA: tuple[str, ...] = tuple(
    c.value for c in MaxAgeSelectionCriterionV1
)
MINIMUM_EVIDENCE_REQUIREMENTS_V1: Mapping[str, Any] = {
    "minimum_distinct_sessions": 2,
    "minimum_distinct_regimes": 2,
    "minimum_distinct_instruments": 1,
    "minimum_computed_age_observations": 1,
    "require_reuse_and_restart_label_coverage": True,
    "require_durable_or_in_memory_ledger_records": True,
    "numeric_max_age_seconds_must_remain_null": True,
    "threshold_selection_forbidden_in_this_capability": True,
    "parameter_research_execution_forbidden_in_this_capability": True,
}


def _canonical_json_bytes(payload: Mapping[str, Any]) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")


def _sha256_hex(payload: Mapping[str, Any]) -> str:
    return hashlib.sha256(_canonical_json_bytes(payload)).hexdigest()


def _require_nonempty_identity(value: Any, *, field_name: str) -> str:
    if value is None:
        raise MaxAgeResearchDesignContractError(f"{field_name}_required")
    text = str(value).strip()
    if not text:
        raise MaxAgeResearchDesignContractError(f"{field_name}_must_be_nonempty")
    return text


def _require_nonempty_text(value: Any, *, field_name: str) -> str:
    return _require_nonempty_identity(value, field_name=field_name)


def _require_nonempty_str_tuple(values: Sequence[Any], *, field_name: str) -> tuple[str, ...]:
    if not values:
        raise MaxAgeResearchDesignContractError(f"{field_name}_required")
    out: list[str] = []
    for item in values:
        out.append(_require_nonempty_text(item, field_name=field_name))
    return tuple(out)


def _as_optional_int(value: Any) -> Optional[int]:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _as_optional_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _as_optional_bool(value: Any) -> Optional[bool]:
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    return None


def _optional_identity(value: Any) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _assert_identity_agreement(
    *,
    field_name: str,
    expected: str,
    observed: Any,
) -> None:
    observed_id = _optional_identity(observed)
    if observed_id is None:
        return
    if observed_id != expected:
        raise MaxAgeResearchDesignContractError(f"cross_{field_name}_join_conflict")


@dataclass(frozen=True)
class CanonicalVolatilityMaxAgeResearchDesignContractV1:
    """Immutable preregistered research design; no selected threshold."""

    preregistration_contract_version: str
    capability_id: str
    capability_version: str
    join_contract_name: str
    join_contract_version: str
    research_question: str
    candidate_threshold_source: str
    candidate_dimensions: tuple[str, ...]
    dataset_scope: str
    session_scope: str
    instrument_scope: str
    regime_dimensions: tuple[str, ...]
    metrics: tuple[str, ...]
    cost_assumptions: str
    leakage_controls: tuple[str, ...]
    purged_split_policy: str
    embargo_policy: str
    walk_forward_design: str
    stress_controls: tuple[str, ...]
    robustness_controls: tuple[str, ...]
    rejection_criteria: tuple[str, ...]
    selection_criteria: tuple[str, ...]
    final_holdout_policy: str
    minimum_evidence_requirements: Mapping[str, Any]
    age_reference_clock: str
    age_formula: str
    threshold_status: str
    numeric_max_age_seconds: Optional[float]
    enforcement_enabled: bool
    enforcement_applied: bool
    alpha_enforcement_allowed: bool
    parameter_research_executed: bool
    accumulation_ledger_name: str
    accumulation_ledger_version: str
    preregistration_digest: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "accumulation_ledger_name": self.accumulation_ledger_name,
            "accumulation_ledger_version": self.accumulation_ledger_version,
            "age_formula": self.age_formula,
            "age_reference_clock": self.age_reference_clock,
            "alpha_enforcement_allowed": self.alpha_enforcement_allowed,
            "candidate_dimensions": list(self.candidate_dimensions),
            "candidate_threshold_source": self.candidate_threshold_source,
            "capability_id": self.capability_id,
            "capability_version": self.capability_version,
            "cost_assumptions": self.cost_assumptions,
            "dataset_scope": self.dataset_scope,
            "embargo_policy": self.embargo_policy,
            "enforcement_applied": self.enforcement_applied,
            "enforcement_enabled": self.enforcement_enabled,
            "final_holdout_policy": self.final_holdout_policy,
            "instrument_scope": self.instrument_scope,
            "join_contract_name": self.join_contract_name,
            "join_contract_version": self.join_contract_version,
            "leakage_controls": list(self.leakage_controls),
            "metrics": list(self.metrics),
            "minimum_evidence_requirements": dict(self.minimum_evidence_requirements),
            "numeric_max_age_seconds": self.numeric_max_age_seconds,
            "parameter_research_executed": self.parameter_research_executed,
            "preregistration_contract_version": self.preregistration_contract_version,
            "preregistration_digest": self.preregistration_digest,
            "purged_split_policy": self.purged_split_policy,
            "regime_dimensions": list(self.regime_dimensions),
            "rejection_criteria": list(self.rejection_criteria),
            "research_question": self.research_question,
            "robustness_controls": list(self.robustness_controls),
            "selection_criteria": list(self.selection_criteria),
            "session_scope": self.session_scope,
            "stress_controls": list(self.stress_controls),
            "threshold_status": self.threshold_status,
            "walk_forward_design": self.walk_forward_design,
        }


def _preregistration_digest_v1(payload: Mapping[str, Any]) -> str:
    body = {k: v for k, v in payload.items() if k != "preregistration_digest"}
    return _sha256_hex(body)


def build_ratified_max_age_research_design_contract_v1() -> (
    CanonicalVolatilityMaxAgeResearchDesignContractV1
):
    provisional = {
        "accumulation_ledger_name": ACCUMULATION_LEDGER_NAME,
        "accumulation_ledger_version": ACCUMULATION_LEDGER_VERSION,
        "age_formula": AGE_FORMULA,
        "age_reference_clock": AGE_REFERENCE_CLOCK,
        "alpha_enforcement_allowed": ALPHA_ENFORCEMENT_ALLOWED,
        "candidate_dimensions": list(PREREGISTERED_RESEARCH_DIMENSIONS),
        "candidate_threshold_source": CANDIDATE_THRESHOLD_SOURCE_V1,
        "capability_id": CAPABILITY_ID,
        "capability_version": CAPABILITY_VERSION,
        "cost_assumptions": COST_ASSUMPTIONS_V1,
        "dataset_scope": DATASET_SCOPE_V1,
        "embargo_policy": EMBARGO_POLICY_V1,
        "enforcement_applied": ENFORCEMENT_APPLIED,
        "enforcement_enabled": ENFORCEMENT_ENABLED,
        "final_holdout_policy": FINAL_HOLDOUT_POLICY_V1,
        "instrument_scope": INSTRUMENT_SCOPE_V1,
        "join_contract_name": JOIN_CONTRACT_NAME,
        "join_contract_version": JOIN_CONTRACT_VERSION,
        "leakage_controls": list(PREREGISTERED_LEAKAGE_CONTROLS),
        "metrics": list(PREREGISTERED_RESEARCH_METRICS),
        "minimum_evidence_requirements": dict(MINIMUM_EVIDENCE_REQUIREMENTS_V1),
        "numeric_max_age_seconds": NUMERIC_MAX_AGE_SECONDS,
        "parameter_research_executed": PARAMETER_RESEARCH_EXECUTED,
        "preregistration_contract_version": PREREGISTRATION_CONTRACT_VERSION,
        "purged_split_policy": PURGED_SPLIT_POLICY_V1,
        "regime_dimensions": list(PREREGISTERED_REGIME_DIMENSIONS),
        "rejection_criteria": list(PREREGISTERED_REJECTION_CRITERIA),
        "research_question": RESEARCH_QUESTION_V1,
        "robustness_controls": list(PREREGISTERED_ROBUSTNESS_REQUIREMENTS),
        "selection_criteria": list(PREREGISTERED_SELECTION_CRITERIA),
        "session_scope": SESSION_SCOPE_V1,
        "stress_controls": list(PREREGISTERED_STRESS_CONTROLS),
        "threshold_status": THRESHOLD_STATUS,
        "walk_forward_design": WALK_FORWARD_DESIGN_V1,
    }
    digest = _preregistration_digest_v1(provisional)
    contract = CanonicalVolatilityMaxAgeResearchDesignContractV1(
        preregistration_contract_version=PREREGISTRATION_CONTRACT_VERSION,
        capability_id=CAPABILITY_ID,
        capability_version=CAPABILITY_VERSION,
        join_contract_name=JOIN_CONTRACT_NAME,
        join_contract_version=JOIN_CONTRACT_VERSION,
        research_question=RESEARCH_QUESTION_V1,
        candidate_threshold_source=CANDIDATE_THRESHOLD_SOURCE_V1,
        candidate_dimensions=PREREGISTERED_RESEARCH_DIMENSIONS,
        dataset_scope=DATASET_SCOPE_V1,
        session_scope=SESSION_SCOPE_V1,
        instrument_scope=INSTRUMENT_SCOPE_V1,
        regime_dimensions=PREREGISTERED_REGIME_DIMENSIONS,
        metrics=PREREGISTERED_RESEARCH_METRICS,
        cost_assumptions=COST_ASSUMPTIONS_V1,
        leakage_controls=PREREGISTERED_LEAKAGE_CONTROLS,
        purged_split_policy=PURGED_SPLIT_POLICY_V1,
        embargo_policy=EMBARGO_POLICY_V1,
        walk_forward_design=WALK_FORWARD_DESIGN_V1,
        stress_controls=PREREGISTERED_STRESS_CONTROLS,
        robustness_controls=PREREGISTERED_ROBUSTNESS_REQUIREMENTS,
        rejection_criteria=PREREGISTERED_REJECTION_CRITERIA,
        selection_criteria=PREREGISTERED_SELECTION_CRITERIA,
        final_holdout_policy=FINAL_HOLDOUT_POLICY_V1,
        minimum_evidence_requirements=dict(MINIMUM_EVIDENCE_REQUIREMENTS_V1),
        age_reference_clock=AGE_REFERENCE_CLOCK,
        age_formula=AGE_FORMULA,
        threshold_status=THRESHOLD_STATUS,
        numeric_max_age_seconds=NUMERIC_MAX_AGE_SECONDS,
        enforcement_enabled=ENFORCEMENT_ENABLED,
        enforcement_applied=ENFORCEMENT_APPLIED,
        alpha_enforcement_allowed=ALPHA_ENFORCEMENT_ALLOWED,
        parameter_research_executed=PARAMETER_RESEARCH_EXECUTED,
        accumulation_ledger_name=ACCUMULATION_LEDGER_NAME,
        accumulation_ledger_version=ACCUMULATION_LEDGER_VERSION,
        preregistration_digest=digest,
    )
    return validate_max_age_research_design_contract_v1(contract)


def validate_max_age_research_design_contract_v1(
    contract: CanonicalVolatilityMaxAgeResearchDesignContractV1,
) -> CanonicalVolatilityMaxAgeResearchDesignContractV1:
    if contract.preregistration_contract_version != PREREGISTRATION_CONTRACT_VERSION:
        raise MaxAgeResearchDesignContractError("preregistration_contract_version_mismatch")
    if contract.threshold_status != THRESHOLD_STATUS_UNRESOLVED:
        raise MaxAgeResearchDesignContractError("threshold_must_remain_unresolved")
    if contract.numeric_max_age_seconds is not None:
        raise MaxAgeResearchDesignContractError("numeric_max_age_seconds_must_be_null")
    if (
        contract.enforcement_enabled
        or contract.enforcement_applied
        or contract.alpha_enforcement_allowed
    ):
        raise MaxAgeResearchDesignContractError("enforcement_forbidden")
    if contract.parameter_research_executed:
        raise MaxAgeResearchDesignContractError("parameter_research_execution_forbidden")
    if contract.age_reference_clock != AGE_REFERENCE_CLOCK:
        raise MaxAgeResearchDesignContractError("age_reference_clock_mismatch")

    _require_nonempty_text(contract.research_question, field_name="research_question")
    _require_nonempty_text(
        contract.candidate_threshold_source, field_name="candidate_threshold_source"
    )
    _require_nonempty_text(contract.dataset_scope, field_name="dataset_scope")
    _require_nonempty_text(contract.session_scope, field_name="session_scope")
    _require_nonempty_text(contract.instrument_scope, field_name="instrument_scope")
    _require_nonempty_text(contract.cost_assumptions, field_name="cost_assumptions")
    _require_nonempty_text(contract.purged_split_policy, field_name="purged_split_policy")
    _require_nonempty_text(contract.embargo_policy, field_name="embargo_policy")
    _require_nonempty_text(contract.walk_forward_design, field_name="walk_forward_design")
    _require_nonempty_text(contract.final_holdout_policy, field_name="final_holdout_policy")
    _require_nonempty_str_tuple(contract.candidate_dimensions, field_name="candidate_dimensions")
    _require_nonempty_str_tuple(contract.regime_dimensions, field_name="regime_dimensions")
    _require_nonempty_str_tuple(contract.metrics, field_name="metrics")
    _require_nonempty_str_tuple(contract.leakage_controls, field_name="leakage_controls")
    _require_nonempty_str_tuple(contract.stress_controls, field_name="stress_controls")
    _require_nonempty_str_tuple(contract.robustness_controls, field_name="robustness_controls")
    _require_nonempty_str_tuple(contract.rejection_criteria, field_name="rejection_criteria")
    _require_nonempty_str_tuple(contract.selection_criteria, field_name="selection_criteria")
    if not isinstance(contract.minimum_evidence_requirements, Mapping):
        raise MaxAgeResearchDesignContractError("minimum_evidence_requirements_required")
    if not contract.minimum_evidence_requirements:
        raise MaxAgeResearchDesignContractError("minimum_evidence_requirements_required")

    forbidden_selection_tokens = (
        "best sharpe",
        "maximum pnl",
        "maximum trade count",
        "single best configuration",
    )
    selection_blob = " ".join(contract.selection_criteria).lower()
    for token in forbidden_selection_tokens:
        if token in selection_blob:
            raise MaxAgeResearchDesignContractError("forbidden_point_selection_rule")
    required_selection = {
        MaxAgeSelectionCriterionV1.ROBUST_THRESHOLD_REGION_NOT_POINT.value,
        MaxAgeSelectionCriterionV1.MULTI_SESSION_AGREEMENT_REQUIRED.value,
        MaxAgeSelectionCriterionV1.MULTI_REGIME_AGREEMENT_REQUIRED.value,
        MaxAgeSelectionCriterionV1.FINAL_HOLDOUT_CONFIRMATION_REQUIRED.value,
        MaxAgeSelectionCriterionV1.NO_BEST_SHARPE_POINT_SELECTION.value,
        MaxAgeSelectionCriterionV1.NO_MAX_PNL_POINT_SELECTION.value,
        MaxAgeSelectionCriterionV1.NO_MAX_TRADE_COUNT_POINT_SELECTION.value,
    }
    if not required_selection.issubset(set(contract.selection_criteria)):
        raise MaxAgeResearchDesignContractError("selection_criteria_incomplete")

    expected_digest = _preregistration_digest_v1(contract.to_dict())
    if contract.preregistration_digest != expected_digest:
        raise MaxAgeResearchDesignContractError("preregistration_digest_mismatch")
    return contract


@dataclass(frozen=True)
class CanonicalVolatilityMaxAgeResearchEvidenceJoinV1:
    """Typed join of age evidence + producer/binding + decision/economics strata."""

    join_contract_name: str
    join_contract_version: str
    session_id: str
    cycle_id: str
    cycle_index: Optional[int]
    instrument_id: str
    regime_id: str
    trading_epoch: Optional[int]
    producer_outcome: Optional[str]
    reuse_status: Optional[str]
    restart_status: Optional[str]
    restart_without_estimate: Optional[bool]
    estimate_present: Optional[bool]
    estimate_as_of_event_time: Optional[str]
    observation_count: Optional[int]
    source_digest: Optional[str]
    reference_event_time: Optional[str]
    computed_age_seconds: Optional[float]
    max_age_status: Optional[str]
    threshold_status: str
    presence_status: Optional[str]
    clock_trust_status: Optional[str]
    data_integrity_status: Optional[str]
    age_decision: Optional[str]
    age_reason_code: Optional[str]
    enforcement_applied: bool
    alpha_scope_entry_authority_allowed: Optional[bool]
    decision_outcome: Optional[str]
    selected_side: Optional[str]
    economic_metrics: Optional[Mapping[str, Any]]
    join_digest: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "age_decision": self.age_decision,
            "age_reason_code": self.age_reason_code,
            "alpha_scope_entry_authority_allowed": self.alpha_scope_entry_authority_allowed,
            "clock_trust_status": self.clock_trust_status,
            "computed_age_seconds": self.computed_age_seconds,
            "cycle_id": self.cycle_id,
            "cycle_index": self.cycle_index,
            "data_integrity_status": self.data_integrity_status,
            "decision_outcome": self.decision_outcome,
            "economic_metrics": (
                None if self.economic_metrics is None else dict(self.economic_metrics)
            ),
            "enforcement_applied": self.enforcement_applied,
            "estimate_as_of_event_time": self.estimate_as_of_event_time,
            "estimate_present": self.estimate_present,
            "instrument_id": self.instrument_id,
            "join_contract_name": self.join_contract_name,
            "join_contract_version": self.join_contract_version,
            "join_digest": self.join_digest,
            "max_age_status": self.max_age_status,
            "observation_count": self.observation_count,
            "presence_status": self.presence_status,
            "producer_outcome": self.producer_outcome,
            "reference_event_time": self.reference_event_time,
            "regime_id": self.regime_id,
            "restart_status": self.restart_status,
            "restart_without_estimate": self.restart_without_estimate,
            "reuse_status": self.reuse_status,
            "selected_side": self.selected_side,
            "session_id": self.session_id,
            "source_digest": self.source_digest,
            "threshold_status": self.threshold_status,
            "trading_epoch": self.trading_epoch,
        }

    def business_identity_v1(self) -> tuple[str, str, str, str]:
        return (
            self.join_contract_version,
            self.session_id,
            self.cycle_id,
            self.instrument_id,
        )

    def record_identity_v1(self) -> tuple[str, str, str, str, str]:
        return (*self.business_identity_v1(), self.join_digest)


def _join_digest_v1(payload: Mapping[str, Any]) -> str:
    body = {k: v for k, v in payload.items() if k != "join_digest"}
    return _sha256_hex(body)


def build_max_age_research_evidence_join_v1(
    *,
    session_id: str,
    cycle_id: str,
    instrument_id: str,
    regime_id: str,
    max_age_policy_evidence: Union[CanonicalVolatilityMaxAgePolicyEvidenceV1, Mapping[str, Any]],
    producer_outcome: Optional[str] = None,
    reuse_status: Optional[str] = None,
    restart_status: Optional[str] = None,
    restart_without_estimate: Optional[bool] = None,
    estimate_present: Optional[bool] = None,
    observation_count: Optional[int] = None,
    source_digest: Optional[str] = None,
    trading_epoch: Optional[int] = None,
    cycle_index: Optional[int] = None,
    alpha_scope_entry_authority_allowed: Optional[bool] = None,
    decision_outcome: Optional[str] = None,
    selected_side: Optional[str] = None,
    economic_metrics: Optional[Mapping[str, Any]] = None,
    join_contract_version: str = JOIN_CONTRACT_VERSION,
) -> CanonicalVolatilityMaxAgeResearchEvidenceJoinV1:
    """Build typed research join; never selects threshold or applies enforcement."""
    session_id_n = _require_nonempty_identity(session_id, field_name="session_id")
    cycle_id_n = _require_nonempty_identity(cycle_id, field_name="cycle_id")
    instrument_id_n = _require_nonempty_identity(instrument_id, field_name="instrument_id")
    regime_id_n = _require_nonempty_identity(regime_id, field_name="regime_id")
    contract_version_n = _require_nonempty_identity(
        join_contract_version, field_name="join_contract_version"
    )
    if contract_version_n != JOIN_CONTRACT_VERSION:
        raise MaxAgeResearchDesignContractError("join_contract_version_mismatch")

    if isinstance(max_age_policy_evidence, CanonicalVolatilityMaxAgePolicyEvidenceV1):
        age = max_age_policy_evidence.to_dict()
    else:
        age = dict(max_age_policy_evidence)

    if age.get("enforcement_applied") is True:
        raise MaxAgeResearchDesignContractError("join_forbids_enforcement_applied_true")
    if age.get("numeric_threshold_selected") is True:
        raise MaxAgeResearchDesignContractError("join_forbids_numeric_threshold_selected")

    threshold_status = _require_nonempty_identity(
        age.get("threshold_status") or THRESHOLD_STATUS,
        field_name="threshold_status",
    )
    if threshold_status != THRESHOLD_STATUS_UNRESOLVED:
        raise MaxAgeResearchDesignContractError("join_requires_unresolved_threshold_status")

    _assert_identity_agreement(
        field_name="session",
        expected=session_id_n,
        observed=age.get("session_id"),
    )
    _assert_identity_agreement(
        field_name="cycle",
        expected=cycle_id_n,
        observed=age.get("cycle_id"),
    )
    _assert_identity_agreement(
        field_name="instrument",
        expected=instrument_id_n,
        observed=age.get("instrument_id"),
    )
    _assert_identity_agreement(
        field_name="regime",
        expected=regime_id_n,
        observed=age.get("regime_id"),
    )

    effective_reuse = reuse_status if reuse_status is not None else age.get("reuse_status")
    effective_restart = restart_status if restart_status is not None else age.get("restart_status")
    effective_as_of = age.get("estimate_as_of_event_time")
    effective_source = source_digest if source_digest is not None else age.get("source_digest")

    provisional = {
        "age_decision": age.get("decision"),
        "age_reason_code": age.get("reason_code"),
        "alpha_scope_entry_authority_allowed": alpha_scope_entry_authority_allowed,
        "clock_trust_status": age.get("clock_trust_status"),
        "computed_age_seconds": age.get("computed_age_seconds"),
        "cycle_id": cycle_id_n,
        "cycle_index": cycle_index,
        "data_integrity_status": age.get("data_integrity_status"),
        "decision_outcome": decision_outcome,
        "economic_metrics": None if economic_metrics is None else dict(economic_metrics),
        "enforcement_applied": False,
        "estimate_as_of_event_time": effective_as_of,
        "estimate_present": estimate_present,
        "instrument_id": instrument_id_n,
        "join_contract_name": JOIN_CONTRACT_NAME,
        "join_contract_version": contract_version_n,
        "max_age_status": age.get("max_age_status"),
        "observation_count": observation_count,
        "presence_status": age.get("presence_status"),
        "producer_outcome": producer_outcome,
        "reference_event_time": age.get("reference_event_time"),
        "regime_id": regime_id_n,
        "restart_status": effective_restart,
        "restart_without_estimate": restart_without_estimate,
        "reuse_status": effective_reuse,
        "selected_side": selected_side,
        "session_id": session_id_n,
        "source_digest": effective_source,
        "threshold_status": threshold_status,
        "trading_epoch": trading_epoch,
    }
    digest = _join_digest_v1(provisional)
    return CanonicalVolatilityMaxAgeResearchEvidenceJoinV1(
        join_contract_name=JOIN_CONTRACT_NAME,
        join_contract_version=contract_version_n,
        session_id=session_id_n,
        cycle_id=cycle_id_n,
        cycle_index=cycle_index,
        instrument_id=instrument_id_n,
        regime_id=regime_id_n,
        trading_epoch=trading_epoch,
        producer_outcome=producer_outcome,
        reuse_status=None if effective_reuse is None else str(effective_reuse),
        restart_status=None if effective_restart is None else str(effective_restart),
        restart_without_estimate=restart_without_estimate,
        estimate_present=estimate_present,
        estimate_as_of_event_time=(None if effective_as_of is None else str(effective_as_of)),
        observation_count=observation_count,
        source_digest=None if effective_source is None else str(effective_source),
        reference_event_time=(
            None
            if age.get("reference_event_time") is None
            else str(age.get("reference_event_time"))
        ),
        computed_age_seconds=_as_optional_float(age.get("computed_age_seconds")),
        max_age_status=(
            None if age.get("max_age_status") is None else str(age.get("max_age_status"))
        ),
        threshold_status=threshold_status,
        presence_status=(
            None if age.get("presence_status") is None else str(age.get("presence_status"))
        ),
        clock_trust_status=(
            None if age.get("clock_trust_status") is None else str(age.get("clock_trust_status"))
        ),
        data_integrity_status=(
            None
            if age.get("data_integrity_status") is None
            else str(age.get("data_integrity_status"))
        ),
        age_decision=None if age.get("decision") is None else str(age.get("decision")),
        age_reason_code=None if age.get("reason_code") is None else str(age.get("reason_code")),
        enforcement_applied=False,
        alpha_scope_entry_authority_allowed=alpha_scope_entry_authority_allowed,
        decision_outcome=decision_outcome,
        selected_side=selected_side,
        economic_metrics=None if economic_metrics is None else dict(economic_metrics),
        join_digest=digest,
    )


def build_max_age_research_evidence_join_from_cycle_v1(
    cycle: Mapping[str, Any],
) -> CanonicalVolatilityMaxAgeResearchEvidenceJoinV1:
    """Project a hardening-bridge cycle dict into the typed research join."""
    binding = dict(cycle.get("canonical_volatility_typed_binding") or {})
    gate = dict(cycle.get("double_play_typed_volatility_presence_gate") or {})
    age = dict(gate.get("max_age_policy_evidence") or {})
    feature_regime = dict(cycle.get("feature_regime") or {})
    if not age:
        raise MaxAgeResearchDesignContractError("cycle_missing_max_age_policy_evidence")

    session_id = _require_nonempty_identity(cycle.get("session_id"), field_name="session_id")
    cycle_id = _require_nonempty_identity(cycle.get("cycle_id"), field_name="cycle_id")
    instrument_id = _require_nonempty_identity(
        cycle.get("instrument_id"), field_name="instrument_id"
    )
    regime_id = _require_nonempty_identity(feature_regime.get("regime_id"), field_name="regime_id")

    _assert_identity_agreement(
        field_name="session",
        expected=session_id,
        observed=binding.get("session_id"),
    )
    _assert_identity_agreement(
        field_name="session",
        expected=session_id,
        observed=gate.get("session_id"),
    )
    _assert_identity_agreement(
        field_name="session",
        expected=session_id,
        observed=age.get("session_id"),
    )
    _assert_identity_agreement(
        field_name="cycle",
        expected=cycle_id,
        observed=binding.get("cycle_id"),
    )
    _assert_identity_agreement(
        field_name="cycle",
        expected=cycle_id,
        observed=gate.get("cycle_id"),
    )
    _assert_identity_agreement(
        field_name="cycle",
        expected=cycle_id,
        observed=age.get("cycle_id"),
    )
    _assert_identity_agreement(
        field_name="instrument",
        expected=instrument_id,
        observed=binding.get("instrument_id"),
    )
    _assert_identity_agreement(
        field_name="instrument",
        expected=instrument_id,
        observed=gate.get("instrument_id"),
    )
    _assert_identity_agreement(
        field_name="instrument",
        expected=instrument_id,
        observed=age.get("instrument_id"),
    )
    _assert_identity_agreement(
        field_name="regime",
        expected=regime_id,
        observed=binding.get("regime_id"),
    )
    _assert_identity_agreement(
        field_name="regime",
        expected=regime_id,
        observed=gate.get("regime_id"),
    )
    _assert_identity_agreement(
        field_name="regime",
        expected=regime_id,
        observed=age.get("regime_id"),
    )

    return build_max_age_research_evidence_join_v1(
        session_id=session_id,
        cycle_id=cycle_id,
        instrument_id=instrument_id,
        regime_id=regime_id,
        max_age_policy_evidence=age,
        producer_outcome=(
            None
            if binding.get("producer_outcome") is None
            else str(binding.get("producer_outcome"))
        ),
        reuse_status=(
            None if binding.get("reuse_status") is None else str(binding.get("reuse_status"))
        ),
        restart_status=(
            None if binding.get("restart_status") is None else str(binding.get("restart_status"))
        ),
        restart_without_estimate=_as_optional_bool(binding.get("restart_without_estimate")),
        estimate_present=_as_optional_bool(binding.get("estimate_present")),
        observation_count=_as_optional_int(binding.get("observation_count")),
        source_digest=(
            None if binding.get("source_digest") is None else str(binding.get("source_digest"))
        ),
        trading_epoch=_as_optional_int(cycle.get("trading_epoch")),
        cycle_index=_as_optional_int(cycle.get("cycle_index")),
        alpha_scope_entry_authority_allowed=_as_optional_bool(
            gate.get("alpha_scope_entry_authority_allowed")
        ),
        decision_outcome=(
            None if cycle.get("decision_outcome") is None else str(cycle.get("decision_outcome"))
        ),
        selected_side=(
            None if cycle.get("selected_side") is None else str(cycle.get("selected_side"))
        ),
        economic_metrics=(
            None
            if cycle.get("economic_metrics") is None
            else dict(cycle.get("economic_metrics") or {})
        ),
    )


@dataclass(frozen=True)
class CounterfactualMaxAgeThresholdDiagnosticV1:
    """Non-enforcing diagnostic for a caller-supplied candidate threshold.

    The candidate is an evaluation argument only — never a ratified selection,
    recommendation, or productive policy value.
    """

    computed_age_seconds: Optional[float]
    candidate_max_age_seconds_argument: float
    counterfactual_label: str
    enforcement_applied: bool
    alpha_decision_mutated: bool
    threshold_status_productive: str
    evaluation_mode: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "alpha_decision_mutated": self.alpha_decision_mutated,
            "candidate_max_age_seconds_argument": self.candidate_max_age_seconds_argument,
            "computed_age_seconds": self.computed_age_seconds,
            "counterfactual_label": self.counterfactual_label,
            "enforcement_applied": self.enforcement_applied,
            "evaluation_mode": self.evaluation_mode,
            "threshold_status_productive": self.threshold_status_productive,
        }


def evaluate_counterfactual_max_age_threshold_diagnostic_v1(
    *,
    computed_age_seconds: Optional[float],
    candidate_max_age_seconds_argument: float,
) -> CounterfactualMaxAgeThresholdDiagnosticV1:
    """Deterministic counterfactual age label; never enforces Alpha decisions."""
    if (
        not isinstance(candidate_max_age_seconds_argument, (int, float))
        or isinstance(candidate_max_age_seconds_argument, bool)
        or candidate_max_age_seconds_argument < 0.0
    ):
        return CounterfactualMaxAgeThresholdDiagnosticV1(
            computed_age_seconds=computed_age_seconds,
            candidate_max_age_seconds_argument=float("nan"),
            counterfactual_label=CounterfactualAgeLabelV1.THRESHOLD_ARGUMENT_INVALID.value,
            enforcement_applied=False,
            alpha_decision_mutated=False,
            threshold_status_productive=THRESHOLD_STATUS,
            evaluation_mode="DIAGNOSTIC_COUNTERFACTUAL_NO_ENFORCEMENT",
        )

    candidate = float(candidate_max_age_seconds_argument)
    if computed_age_seconds is None:
        label = CounterfactualAgeLabelV1.AGE_UNAVAILABLE
    elif float(computed_age_seconds) <= candidate:
        label = CounterfactualAgeLabelV1.WOULD_BE_FRESH_IF_THRESHOLD
    else:
        label = CounterfactualAgeLabelV1.WOULD_BE_STALE_IF_THRESHOLD

    return CounterfactualMaxAgeThresholdDiagnosticV1(
        computed_age_seconds=None if computed_age_seconds is None else float(computed_age_seconds),
        candidate_max_age_seconds_argument=candidate,
        counterfactual_label=label.value,
        enforcement_applied=False,
        alpha_decision_mutated=False,
        threshold_status_productive=THRESHOLD_STATUS,
        evaluation_mode="DIAGNOSTIC_COUNTERFACTUAL_NO_ENFORCEMENT",
    )


def evaluate_counterfactual_from_age_evidence_v1(
    *,
    age_evidence: Union[CanonicalVolatilityMaxAgePolicyEvidenceV1, Mapping[str, Any]],
    candidate_max_age_seconds_argument: float,
) -> CounterfactualMaxAgeThresholdDiagnosticV1:
    if isinstance(age_evidence, CanonicalVolatilityMaxAgePolicyEvidenceV1):
        age_seconds = age_evidence.computed_age_seconds
        if age_evidence.enforcement_applied:
            raise MaxAgeResearchDesignContractError("counterfactual_forbids_enforced_evidence")
    else:
        age_seconds = _as_optional_float(age_evidence.get("computed_age_seconds"))
        if age_evidence.get("enforcement_applied") is True:
            raise MaxAgeResearchDesignContractError("counterfactual_forbids_enforced_evidence")
    return evaluate_counterfactual_max_age_threshold_diagnostic_v1(
        computed_age_seconds=age_seconds,
        candidate_max_age_seconds_argument=candidate_max_age_seconds_argument,
    )


def _join_from_mapping_v1(
    record: Mapping[str, Any],
) -> CanonicalVolatilityMaxAgeResearchEvidenceJoinV1:
    return build_max_age_research_evidence_join_v1(
        session_id=str(record.get("session_id") or ""),
        cycle_id=str(record.get("cycle_id") or ""),
        instrument_id=str(record.get("instrument_id") or ""),
        regime_id=str(record.get("regime_id") or ""),
        max_age_policy_evidence={
            "estimate_as_of_event_time": record.get("estimate_as_of_event_time"),
            "reference_event_time": record.get("reference_event_time"),
            "computed_age_seconds": record.get("computed_age_seconds"),
            "max_age_status": record.get("max_age_status"),
            "threshold_status": record.get("threshold_status") or THRESHOLD_STATUS,
            "presence_status": record.get("presence_status"),
            "clock_trust_status": record.get("clock_trust_status"),
            "data_integrity_status": record.get("data_integrity_status"),
            "reuse_status": record.get("reuse_status"),
            "restart_status": record.get("restart_status"),
            "source_digest": record.get("source_digest"),
            "decision": record.get("age_decision"),
            "reason_code": record.get("age_reason_code"),
            "enforcement_applied": record.get("enforcement_applied", False),
            "numeric_threshold_selected": record.get("numeric_threshold_selected", False),
            "session_id": record.get("session_id"),
            "cycle_id": record.get("cycle_id"),
            "instrument_id": record.get("instrument_id"),
            "regime_id": record.get("regime_id"),
        },
        producer_outcome=(
            None if record.get("producer_outcome") is None else str(record.get("producer_outcome"))
        ),
        reuse_status=(
            None if record.get("reuse_status") is None else str(record.get("reuse_status"))
        ),
        restart_status=(
            None if record.get("restart_status") is None else str(record.get("restart_status"))
        ),
        restart_without_estimate=_as_optional_bool(record.get("restart_without_estimate")),
        estimate_present=_as_optional_bool(record.get("estimate_present")),
        observation_count=_as_optional_int(record.get("observation_count")),
        source_digest=(
            None if record.get("source_digest") is None else str(record.get("source_digest"))
        ),
        trading_epoch=_as_optional_int(record.get("trading_epoch")),
        cycle_index=_as_optional_int(record.get("cycle_index")),
        alpha_scope_entry_authority_allowed=_as_optional_bool(
            record.get("alpha_scope_entry_authority_allowed")
        ),
        decision_outcome=(
            None if record.get("decision_outcome") is None else str(record.get("decision_outcome"))
        ),
        selected_side=(
            None if record.get("selected_side") is None else str(record.get("selected_side"))
        ),
        economic_metrics=(
            None
            if record.get("economic_metrics") is None
            else dict(record.get("economic_metrics") or {})
        ),
        join_contract_version=str(record.get("join_contract_version") or JOIN_CONTRACT_VERSION),
    )


def _validate_loaded_join_payload_v1(
    payload: Mapping[str, Any],
) -> CanonicalVolatilityMaxAgeResearchEvidenceJoinV1:
    if not isinstance(payload, Mapping):
        raise MaxAgeResearchDesignContractError("ledger_record_must_be_object")
    if payload.get("enforcement_applied") is True:
        raise MaxAgeResearchDesignContractError("ledger_contains_enforcement")
    if payload.get("numeric_threshold_selected") is True:
        raise MaxAgeResearchDesignContractError("ledger_contains_numeric_threshold_selected")
    threshold_status = _require_nonempty_identity(
        payload.get("threshold_status"),
        field_name="threshold_status",
    )
    if threshold_status != THRESHOLD_STATUS_UNRESOLVED:
        raise MaxAgeResearchDesignContractError("ledger_requires_unresolved_threshold")

    join = _join_from_mapping_v1(payload)
    stored_digest = _require_nonempty_identity(payload.get("join_digest"), field_name="join_digest")
    if stored_digest != join.join_digest:
        raise MaxAgeResearchDesignContractError("ledger_join_digest_mismatch")
    return join


def _apply_duplicate_policy_v1(
    *,
    existing: Sequence[Mapping[str, Any]],
    candidate: CanonicalVolatilityMaxAgeResearchEvidenceJoinV1,
) -> CanonicalVolatilityMaxAgeResearchEvidenceJoinV1 | None:
    """Return None to append; return candidate for identical idempotent no-op."""
    business = candidate.business_identity_v1()
    for raw in existing:
        existing_join = _validate_loaded_join_payload_v1(raw)
        if existing_join.business_identity_v1() != business:
            continue
        if existing_join.join_digest == candidate.join_digest:
            return candidate
        raise MaxAgeResearchDesignContractError("ledger_duplicate_identity_digest_conflict")
    return None


def append_max_age_research_evidence_ledger_record_v1(
    *,
    ledger_path: Path,
    record: Union[CanonicalVolatilityMaxAgeResearchEvidenceJoinV1, Mapping[str, Any]],
) -> CanonicalVolatilityMaxAgeResearchEvidenceJoinV1:
    """Append one join record to a durable JSONL ledger (multi-session corpus)."""
    if isinstance(record, CanonicalVolatilityMaxAgeResearchEvidenceJoinV1):
        join = record
    else:
        join = _join_from_mapping_v1(record)

    if join.enforcement_applied:
        raise MaxAgeResearchDesignContractError("ledger_forbids_enforcement_applied")
    if join.threshold_status != THRESHOLD_STATUS_UNRESOLVED:
        raise MaxAgeResearchDesignContractError("ledger_requires_unresolved_threshold")
    recomputed = _join_digest_v1(join.to_dict())
    if recomputed != join.join_digest:
        raise MaxAgeResearchDesignContractError("ledger_join_digest_mismatch")

    ledger_path = Path(ledger_path)
    existing = load_max_age_research_evidence_ledger_v1(ledger_path)
    duplicate = _apply_duplicate_policy_v1(existing=existing, candidate=join)
    if duplicate is not None:
        return duplicate

    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(join.to_dict(), sort_keys=True, separators=(",", ":"), default=str)
    with ledger_path.open("a", encoding="utf-8") as handle:
        handle.write(line + "\n")
    return join


def load_max_age_research_evidence_ledger_v1(
    ledger_path: Path,
) -> list[dict[str, Any]]:
    path = Path(ledger_path)
    if not path.exists():
        return []
    records: list[dict[str, Any]] = []
    seen_business: dict[tuple[str, str, str, str], str] = {}
    try:
        raw_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise MaxAgeResearchDesignContractError(f"ledger_read_failed:{exc}") from exc

    for line_no, raw in enumerate(raw_text.splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        try:
            payload = json.loads(line)
        except json.JSONDecodeError as exc:
            raise MaxAgeResearchDesignContractError(
                f"ledger_corrupt_json:line={line_no}:{exc.msg}"
            ) from exc
        if not isinstance(payload, dict):
            raise MaxAgeResearchDesignContractError(f"ledger_record_must_be_object:line={line_no}")
        join = _validate_loaded_join_payload_v1(payload)
        business = join.business_identity_v1()
        prior_digest = seen_business.get(business)
        if prior_digest is not None:
            if prior_digest != join.join_digest:
                raise MaxAgeResearchDesignContractError(
                    f"ledger_duplicate_identity_digest_conflict:line={line_no}"
                )
            # Identical duplicate in durable ledger is corruption for load order;
            # fail-closed rather than silently collapsing.
            raise MaxAgeResearchDesignContractError(
                f"ledger_duplicate_identity_repeated:line={line_no}"
            )
        seen_business[business] = join.join_digest
        records.append(join.to_dict())
    return records


def summarize_max_age_research_evidence_accumulation_v1(
    records: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Multi-session / multi-regime coverage summary (no threshold selection)."""
    sessions = sorted({str(r.get("session_id") or "") for r in records if r.get("session_id")})
    regimes = sorted({str(r.get("regime_id") or "") for r in records if r.get("regime_id")})
    instruments = sorted(
        {str(r.get("instrument_id") or "") for r in records if r.get("instrument_id")}
    )
    reuse_labels = sorted(
        {str(r.get("reuse_status") or "") for r in records if r.get("reuse_status")}
    )
    restart_labels = sorted(
        {str(r.get("restart_status") or "") for r in records if r.get("restart_status")}
    )
    ages = [
        float(r["computed_age_seconds"])
        for r in records
        if r.get("computed_age_seconds") is not None
    ]
    return {
        "accumulation_ledger_version": ACCUMULATION_LEDGER_VERSION,
        "record_count": len(records),
        "session_count": len(sessions),
        "regime_count": len(regimes),
        "instrument_count": len(instruments),
        "sessions": sessions,
        "regimes": regimes,
        "instruments": instruments,
        "reuse_status_labels": reuse_labels,
        "restart_status_labels": restart_labels,
        "computed_age_observations": len(ages),
        "threshold_status": THRESHOLD_STATUS,
        "numeric_max_age_decided": NUMERIC_MAX_AGE_DECIDED,
        "enforcement_enabled": ENFORCEMENT_ENABLED,
        "enforcement_applied": ENFORCEMENT_APPLIED,
        "parameter_research_executed": PARAMETER_RESEARCH_EXECUTED,
        "multi_session_coverage": len(sessions) >= 2,
        "multi_regime_coverage": len(regimes) >= 2,
    }


def accumulate_max_age_research_evidence_record_from_cycle_v1(
    cycle: Mapping[str, Any],
    *,
    ledger_path: Path | None = None,
    in_memory_ledger: list[dict[str, Any]] | None = None,
) -> CanonicalVolatilityMaxAgeResearchEvidenceJoinV1:
    """Join a cycle, optionally append to durable + in-memory research ledgers."""
    join = build_max_age_research_evidence_join_from_cycle_v1(cycle)
    payload = join.to_dict()

    if in_memory_ledger is not None:
        duplicate = _apply_duplicate_policy_v1(existing=in_memory_ledger, candidate=join)
        if duplicate is None:
            in_memory_ledger.append(dict(payload))

    if ledger_path is not None:
        append_max_age_research_evidence_ledger_record_v1(
            ledger_path=ledger_path,
            record=join,
        )
    return join


def assert_architecture_guards_v1(*, repo_root: Optional[Path] = None) -> dict[str, Any]:
    root = repo_root or Path(__file__).resolve().parents[3]
    this_src = (
        root
        / "src/trading/master_v2"
        / (
            "canonical_volatility_numeric_max_age_parameter_research_design_"
            "and_evidence_accumulation_contract_v1.py"
        )
    ).read_text(encoding="utf-8")
    policy_src = (
        root
        / "src/trading/master_v2"
        / "canonical_volatility_numeric_max_age_policy_contract_and_non_enforcing_telemetry_v1.py"
    ).read_text(encoding="utf-8")
    bridge_src = (
        root
        / "src/ops/wallclock_full_canonical_decision_to_simulated_economics_runtime_bridge_hardening_v2"
        / "hardening_cycle_bridge_v2.py"
    ).read_text(encoding="utf-8")
    binding_src = (
        root
        / "src/trading/master_v2"
        / "canonical_volatility_productive_runtime_cmc_typed_binding_v1.py"
    ).read_text(encoding="utf-8")

    code_before_guards = this_src.split("def assert_architecture_guards_v1", 1)[0]
    if "enforcement_applied=True" in code_before_guards:
        raise RuntimeError("ENFORCEMENT_APPLIED_TRUE_FORBIDDEN")
    if "ALPHA_ENFORCEMENT_ALLOWED = True" in code_before_guards:
        raise RuntimeError("ALPHA_ENFORCEMENT_FLAG_DRIFT")
    if "PARAMETER_RESEARCH_EXECUTED = True" in code_before_guards:
        raise RuntimeError("PARAMETER_RESEARCH_EXECUTED_FLAG_DRIFT")
    if "THRESHOLD_SELECTED = True" in code_before_guards:
        raise RuntimeError("THRESHOLD_SELECTED_FLAG_DRIFT")
    if NUMERIC_MAX_AGE_DECIDED or ENFORCEMENT_ENABLED or LIVE_AUTHORIZATION:
        raise RuntimeError("THRESHOLD_ENFORCEMENT_OR_LIVE_FLAG_DRIFT")
    if ENFORCEMENT_APPLIED:
        raise RuntimeError("ENFORCEMENT_APPLIED_FLAG_DRIFT")
    if POLICY_NUMERIC_MAX_AGE_DECIDED or POLICY_ENFORCEMENT_ENABLED:
        raise RuntimeError("POLICY_THRESHOLD_OR_ENFORCEMENT_DRIFT")
    if "RESTORED_EXISTING_ESTIMATE" in policy_src.split("def assert_architecture_guards_v1", 1)[0]:
        raise RuntimeError("RESTORED_EXISTING_ESTIMATE_MUST_REMAIN_ABSENT")
    if "derive_reuse_and_restart_status_for_age_policy_v1" not in binding_src:
        raise RuntimeError("BINDING_MUST_DERIVE_REUSE_RESTART_LABELS")
    if "reuse_status=binding_reuse" not in bridge_src:
        raise RuntimeError("BRIDGE_MUST_WIRE_REUSE_STATUS_INTO_PRESENCE_GATE")
    if "accumulate_max_age_research_evidence_record_from_cycle_v1" not in bridge_src:
        raise RuntimeError("BRIDGE_MUST_ACCUMULATE_RESEARCH_EVIDENCE_JOIN")
    if "evaluate_counterfactual_max_age_threshold_diagnostic_v1" not in code_before_guards:
        raise RuntimeError("COUNTERFACTUAL_DIAGNOSTIC_PATH_MISSING")
    if "demote_trading_gate" in code_before_guards:
        raise RuntimeError("COUNTERFACTUAL_MUST_NOT_DEMOTE_TRADING_GATE")
    if "ledger_join_digest_mismatch" not in code_before_guards:
        raise RuntimeError("LEDGER_DIGEST_VERIFICATION_MISSING")
    if "ledger_duplicate_identity_digest_conflict" not in code_before_guards:
        raise RuntimeError("LEDGER_DUPLICATE_CONFLICT_POLICY_MISSING")

    diagnostic = evaluate_counterfactual_max_age_threshold_diagnostic_v1(
        computed_age_seconds=120.0,
        candidate_max_age_seconds_argument=60.0,
    )
    if diagnostic.enforcement_applied or diagnostic.alpha_decision_mutated:
        raise RuntimeError("COUNTERFACTUAL_ENFORCEMENT_LEAK")

    _ = evaluate_canonical_volatility_estimate_age_policy_v1
    design = build_ratified_max_age_research_design_contract_v1()
    return {
        "capability_id": CAPABILITY_ID,
        "capability_version": CAPABILITY_VERSION,
        "research_design_owner": RESEARCH_DESIGN_OWNER,
        "preregistration_contract_version": design.preregistration_contract_version,
        "preregistration_digest": design.preregistration_digest,
        "threshold_status": design.threshold_status,
        "numeric_max_age_seconds": design.numeric_max_age_seconds,
        "enforcement_enabled": design.enforcement_enabled,
        "enforcement_applied": design.enforcement_applied,
        "alpha_enforcement_allowed": design.alpha_enforcement_allowed,
        "parameter_research_executed": design.parameter_research_executed,
        "candidate_dimensions_count": len(design.candidate_dimensions),
        "metrics_count": len(design.metrics),
        "live_authorization": LIVE_AUTHORIZATION,
        "hard_stop": HARD_STOP,
        "guards_pass": True,
    }


def assert_capability_non_goals_v1() -> Mapping[str, Any]:
    return {
        "capability_id": CAPABILITY_ID,
        "capability_version": CAPABILITY_VERSION,
        "numeric_max_age_decided": NUMERIC_MAX_AGE_DECIDED,
        "numeric_max_age_seconds": NUMERIC_MAX_AGE_SECONDS,
        "threshold_status": THRESHOLD_STATUS,
        "threshold_selected": THRESHOLD_SELECTED,
        "threshold_recommendation_produced": THRESHOLD_RECOMMENDATION_PRODUCED,
        "enforcement_enabled": ENFORCEMENT_ENABLED,
        "enforcement_applied": ENFORCEMENT_APPLIED,
        "alpha_enforcement_allowed": ALPHA_ENFORCEMENT_ALLOWED,
        "parameter_research_executed": PARAMETER_RESEARCH_EXECUTED,
        "counterfactual_enforcement_enabled": COUNTERFACTUAL_ENFORCEMENT_ENABLED,
        "presence_gate_authority_unchanged": PRESENCE_GATE_AUTHORITY_UNCHANGED,
        "exit_risk_safety_independence_must_remain": (EXIT_RISK_SAFETY_INDEPENDENCE_MUST_REMAIN),
        "event_time_is_age_authority": EVENT_TIME_IS_AGE_AUTHORITY,
        "wallclock_is_not_age_authority": WALLCLOCK_IS_NOT_AGE_AUTHORITY,
        "receive_time_is_not_age_authority": RECEIVE_TIME_IS_NOT_AGE_AUTHORITY,
        "decision_time_is_not_age_authority": DECISION_TIME_IS_NOT_AGE_AUTHORITY,
        "reuse_must_not_refresh_estimate_as_of": REUSE_MUST_NOT_REFRESH_ESTIMATE_AS_OF,
        "restart_must_not_rematerialize_volatility": (RESTART_MUST_NOT_REMATERIALIZE_VOLATILITY),
        "live_authorization": LIVE_AUTHORIZATION,
        "hard_stop": HARD_STOP,
        "next_after_this_capability": NEXT_AFTER_THIS_CAPABILITY,
        "package_marker": PACKAGE_MARKER,
        "gaps_remaining": (
            "C1_G10_NUMERIC_MAX_AGE_THRESHOLD_VALUE",
            "OPERATOR_AUTHORIZED_PARAMETER_RESEARCH_AND_SELECTION",
        ),
    }


__all__ = [
    "ACCUMULATION_LEDGER_NAME",
    "ACCUMULATION_LEDGER_VERSION",
    "ALPHA_ENFORCEMENT_ALLOWED",
    "CANDIDATE_THRESHOLD_SOURCE_V1",
    "CAPABILITY_ID",
    "CAPABILITY_VERSION",
    "COST_ASSUMPTIONS_V1",
    "COUNTERFACTUAL_ENFORCEMENT_ENABLED",
    "CanonicalVolatilityMaxAgeResearchDesignContractV1",
    "CanonicalVolatilityMaxAgeResearchEvidenceJoinV1",
    "CounterfactualAgeLabelV1",
    "CounterfactualMaxAgeThresholdDiagnosticV1",
    "DATASET_SCOPE_V1",
    "DEFAULT_DURABLE_LEDGER_RELATIVE_PATH",
    "EMBARGO_POLICY_V1",
    "ENFORCEMENT_APPLIED",
    "ENFORCEMENT_ENABLED",
    "FINAL_HOLDOUT_POLICY_V1",
    "HARD_STOP",
    "INSTRUMENT_SCOPE_V1",
    "JOIN_CONTRACT_NAME",
    "JOIN_CONTRACT_VERSION",
    "LIVE_AUTHORIZATION",
    "MINIMUM_EVIDENCE_REQUIREMENTS_V1",
    "MaxAgeLeakageControlV1",
    "MaxAgeRejectionCriterionV1",
    "MaxAgeResearchDesignContractError",
    "MaxAgeResearchDimensionV1",
    "MaxAgeResearchMetricV1",
    "MaxAgeRobustnessRequirementV1",
    "MaxAgeSelectionCriterionV1",
    "MaxAgeStressControlV1",
    "NUMERIC_MAX_AGE_DECIDED",
    "NUMERIC_MAX_AGE_SECONDS",
    "PACKAGE_MARKER",
    "PARAMETER_RESEARCH_EXECUTED",
    "PREREGISTERED_LEAKAGE_CONTROLS",
    "PREREGISTERED_REGIME_DIMENSIONS",
    "PREREGISTERED_REJECTION_CRITERIA",
    "PREREGISTERED_RESEARCH_DIMENSIONS",
    "PREREGISTERED_RESEARCH_METRICS",
    "PREREGISTERED_ROBUSTNESS_REQUIREMENTS",
    "PREREGISTERED_SELECTION_CRITERIA",
    "PREREGISTERED_STRESS_CONTROLS",
    "PREREGISTRATION_CONTRACT_VERSION",
    "PURGED_SPLIT_POLICY_V1",
    "RESEARCH_DESIGN_OWNER",
    "RESEARCH_QUESTION_V1",
    "SESSION_SCOPE_V1",
    "THRESHOLD_SELECTED",
    "THRESHOLD_STATUS",
    "WALK_FORWARD_DESIGN_V1",
    "accumulate_max_age_research_evidence_record_from_cycle_v1",
    "append_max_age_research_evidence_ledger_record_v1",
    "assert_architecture_guards_v1",
    "assert_capability_non_goals_v1",
    "build_max_age_research_evidence_join_from_cycle_v1",
    "build_max_age_research_evidence_join_v1",
    "build_ratified_max_age_research_design_contract_v1",
    "evaluate_counterfactual_from_age_evidence_v1",
    "evaluate_counterfactual_max_age_threshold_diagnostic_v1",
    "load_max_age_research_evidence_ledger_v1",
    "summarize_max_age_research_evidence_accumulation_v1",
    "validate_max_age_research_design_contract_v1",
]
