"""Historical default deauthorization markers for capital/risk/sizing (v1).

Isolated offline replay fixtures may still use these literals when explicitly
bound via ``ISOLATED_OFFLINE_REPLAY_FIXTURE_LINEAGE_REF_V1``. They must not
imply CURRENT or productive authority.
"""

from __future__ import annotations

from decimal import Decimal

ISOLATED_OFFLINE_REPLAY_FIXTURE_LINEAGE_REF_V1 = (
    "capital_risk_sizing_offline_replay_binding_adapter_v0."
    "isolated_offline_replay_fixture_capital_context_v0"
)

ISOLATED_OFFLINE_REPLAY_FIXTURE_ACCOUNT_EQUITY = Decimal("10000")
ISOLATED_OFFLINE_REPLAY_FIXTURE_SCOPE_CAPITAL_LIMIT = Decimal("500")
ISOLATED_OFFLINE_REPLAY_FIXTURE_PER_TRADE_RISK_LIMIT = Decimal("25")
ISOLATED_OFFLINE_REPLAY_FIXTURE_TOTAL_CAPITAL_LIMIT = Decimal("500")
ISOLATED_OFFLINE_REPLAY_FIXTURE_DAILY_LOSS_REMAINING_BUDGET = Decimal("25")
ISOLATED_OFFLINE_REPLAY_FIXTURE_MAXIMUM_QUANTITY = Decimal("100")
ISOLATED_OFFLINE_REPLAY_FIXTURE_REFERENCE_PRICE = Decimal("3500")
ISOLATED_OFFLINE_REPLAY_FIXTURE_PROTECTIVE_STOP = Decimal("3400")

REASON_CAPITAL_RISK_CONTEXT_UNRESOLVED = "CAPITAL_RISK_CONTEXT_UNRESOLVED"
REASON_CAPITAL_RISK_STATIC_LIMITS_UNRESOLVED = "CAPITAL_RISK_STATIC_LIMITS_UNRESOLVED"
REASON_DAILY_LOSS_REMAINING_BUDGET_UNRESOLVED = "DAILY_LOSS_REMAINING_BUDGET_UNRESOLVED"
REASON_PRODUCTIVE_CAPITAL_RISK_LIMITS_UNRESOLVED = "PRODUCTIVE_CAPITAL_RISK_LIMITS_UNRESOLVED"
