"""Standing constants for §11.13.5.Z2DH one-shot Funding Account GET.

Reuses LiveCanaryHttpClientV1, the existing canary GET signer, and the
Z2DF observation parser. Does not mint a second HTTP client, signer,
SecretRef owner, live/testnet/canary authority, or capital-movement path.
Does not reuse the consumed Z2DG Owner-GO.
"""

from __future__ import annotations

from src.ops.offline_funding_balance_read_producer_v1.constants_v1 import (
    FORBIDDEN_TRANSFER_ENDPOINT,
    FORBIDDEN_WITHDRAWAL_ENDPOINT,
    FUNDING_BALANCE_ENDPOINT,
    FUNDING_BALANCE_ENDPOINT_METHOD,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)

CAPABILITY_ID = "Z2DH_SINGLE_ACTUAL_READ_ONLY_FUNDING_BALANCE_GET_V1"
PACKAGE_MARKER = "Z2DH_SINGLE_ACTUAL_READ_ONLY_FUNDING_BALANCE_GET_V1=true"
OWNER = "ops.section_11_13_5_z2dh_single_actual_read_only_funding_balance_get_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "z2dh_single_actual_read_only_funding_balance_get.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_Z2DH_SINGLE_ACTUAL_READ_ONLY_FUNDING_BALANCE_GET_V1"
WORKPACKAGE_ID = "SINGLE_ACTUAL_READ_ONLY_FUNDING_BALANCE_GET_V1"
THIS_SLICE = "11.13.5.Z2DH"
PREDECESSOR_SLICE = "11.13.5.Z2DG"
CURRENT_CANONICAL_SECTION = "11.13.5.Z2DH"
EXPECTED_ORIGIN_MAIN_SHA = "79bb087a8531714b1fdb8d65d4077bc31068b67b"
LAST_MERGED_PR = "6219"
AUTHORIZED_HOST = "eea.okx.com"

AUTHORIZED_OPERATION = "EXACTLY_ONE_ACTUAL_AUTHENTICATED_READ_ONLY_GET"
AUTHORIZED_ENDPOINT = "GET /api/v5/asset/balances"
MAX_NETWORK_REQUEST_COUNT = 1
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False

ENDPOINT = FUNDING_BALANCE_ENDPOINT
ENDPOINT_METHOD = FUNDING_BALANCE_ENDPOINT_METHOD
FORBIDDEN_TRANSFER = FORBIDDEN_TRANSFER_ENDPOINT
FORBIDDEN_WITHDRAWAL = FORBIDDEN_WITHDRAWAL_ENDPOINT

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
REUSED_OBSERVATION_PARSER = "parse_funding_account_balance_observation_v1"
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET = False

EVIDENCE_DIRNAME = "section_11_13_5_z2dh_single_actual_read_only_funding_balance_get_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "NO_AUTHORIZED_REACHABLE_PRODUCER_OF_NONZERO_VENUE_POSITION_REQUIRED_BY_PREREQUISITE_08"
)
