"""Standing constants for the offline execution-boundary workpackage.

This package composes existing gates. It does not mint Live, Testnet,
Canary, or order authority. GRANT never means live send.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    GENERAL_LIVE_SUBMIT_UNLOCKED,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.flatten_submit_transport_v1 import (
    DEDICATED_FLATTEN_TRANSPORT_LIVE_WIRE_ENABLED,
)

CAPABILITY_ID = "OFFLINE_EXECUTION_PERMISSION_AND_POSITION_CREATION_PRODUCER_WIRING_V1"
PACKAGE_MARKER = "OFFLINE_EXECUTION_PERMISSION_AND_POSITION_CREATION_PRODUCER_WIRING_V1=true"
OWNER = "ops.offline_execution_permission_and_position_creation_producer_wiring_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "offline_execution_permission_and_position_creation_producer_wiring.v1"
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_OFFLINE_EXECUTION_PERMISSION_AND_POSITION_CREATION_PRODUCER_WIRING_V1"
)
WORKPACKAGE_ID = "OFFLINE_EXECUTION_PERMISSION_AND_POSITION_CREATION_PRODUCER_WIRING_V1"
THIS_SLICE = "11.13.5.Z2DB"
PREDECESSOR_LIVE_SLICE = "11.13.5.Z2DA"
CURRENT_CANONICAL_SECTION = "11.13.5.Z2DA"
CANONICAL_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
REQUIRED_ENVIRONMENT = "NON_LIVE_BOUNDARY"
ENDPOINT_SUBMIT = "/api/v5/trade/order"
DEFAULT_ORDER_TYPE = "limit"
DEFAULT_TD_MODE = "cross"
CLORDID_ENVIRONMENT = "offline"

# Standing authority — imported, never flipped by this package.
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
STANDING_GENERAL_LIVE_SUBMIT_UNLOCKED = GENERAL_LIVE_SUBMIT_UNLOCKED
STANDING_FLATTEN_LIVE_WIRE_ENABLED = DEDICATED_FLATTEN_TRANSPORT_LIVE_WIRE_ENABLED

PRODUCTIVE_WIRE_ENABLED = False
PRODUCTIVE_WIRE_REACHABLE = False
VENUE_MUTATION_ALLOWED = False
GRANT_IMPLIES_LIVE_SEND = False
PREREQUISITE_08_CLOSED_BY_THIS_PACKAGE = False
EXECUTION_READY = False
EXECUTION_PERMISSION_AUTHORITY_EFFECT = "NONE"
SECOND_PERMISSION_AUTHORITY_CREATED = False
BLIND_RESEND_ALLOWED = False
NETWORK_CALL_PERFORMED = False
SECRET_MATERIALIZATION_ALLOWED = False

CANARY_ENTRY_SUBMIT_PERMIT_OWNS_GENERAL_DECISION = False
CANARY_ENTRY_SUBMIT_PERMIT_ROLE = "SPECIALIZED_ONESHOT_ADAPTER_INPUT_NOT_GENERAL_OWNER"
FLATTEN_PRE_SEND_OWNS_ENTRY_DECISION = False
FLATTEN_PRE_SEND_ROLE = "FLATTEN_ONLY_NOT_POSITION_CREATION"

FORBIDDEN_LIVE_ENVIRONMENTS: tuple[str, ...] = (
    "LIVE",
    "PRODUCTION",
    "PROD",
    "TESTNET",
    "DEMO",
    "CANARY",
)

POSITION_CREATION_INTENT_ACTIONS: frozenset[str] = frozenset({"ENTER_LONG", "ENTER_SHORT"})
POSITION_CREATION_MAPPER_SIDES: frozenset[str] = frozenset({"BUY", "SELL"})
ENTER_LONG_MAPPER_SIDE = "BUY"
ENTER_SHORT_MAPPER_SIDE = "SELL"
