"""Frozen claims for the canonical offline position-creation path persist."""

from __future__ import annotations

from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.constants_v1 import (
    PRODUCTIVE_WIRE_REACHABLE,
    STANDING_CANARY_AUTHORIZED,
    STANDING_LIVE_ARMED,
    STANDING_LIVE_AUTHORIZED,
    STANDING_LIVE_ENABLED,
    STANDING_ORDERS_ALLOWED,
    STANDING_SUBMIT_UNLOCKED,
    STANDING_TESTNET_AUTHORIZED,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.path_wiring_constants_v1 import (
    CANONICAL_OFFLINE_POSITION_CREATION_PATH_IMPLEMENTED,
    HOST_GRAPH_ACTIVATION,
    PATH_WIRING_OWNER_GO,
    PATH_WIRING_PREDECESSOR_SLICE,
    PATH_WIRING_THIS_SLICE,
    PATH_WIRING_WORKPACKAGE_ID,
)

CLAIMS: dict[str, object] = {
    "OWNER_GO": PATH_WIRING_OWNER_GO,
    "WORKPACKAGE_ID": PATH_WIRING_WORKPACKAGE_ID,
    "THIS_SLICE": PATH_WIRING_THIS_SLICE,
    "PREDECESSOR_SLICE": PATH_WIRING_PREDECESSOR_SLICE,
    "CANONICAL_OFFLINE_POSITION_CREATION_PATH_IMPLEMENTED": (
        CANONICAL_OFFLINE_POSITION_CREATION_PATH_IMPLEMENTED
    ),
    "CANONICAL_OFFLINE_POSITION_CREATION_PATH_WIRED": True,
    "HOST_GRAPH_ACTIVATION": HOST_GRAPH_ACTIVATION,
    "SECOND_TRADING_AUTHORITY_CREATED": False,
    "MASTER_V2_DP_IS_SOLE_TRADING_DECISION_CORE": True,
    "PRODUCTIVE_WIRE_REACHABLE": PRODUCTIVE_WIRE_REACHABLE,
    "LIVE_SEND_ALLOWED": False,
    "POSITION_CREATION_CURRENTLY_AUTHORIZED": False,
    "REAL_POSITION_CREATED": False,
    "PREREQUISITE_08_CLOSED": False,
    "LIVE_AUTHORIZED": STANDING_LIVE_AUTHORIZED,
    "TESTNET_AUTHORIZED": STANDING_TESTNET_AUTHORIZED,
    "CANARY_AUTHORIZED": STANDING_CANARY_AUTHORIZED,
    "ORDERS_ALLOWED": STANDING_ORDERS_ALLOWED,
    "LIVE_ENABLED": STANDING_LIVE_ENABLED,
    "LIVE_ARMED": STANDING_LIVE_ARMED,
    "SUBMIT_UNLOCKED": STANDING_SUBMIT_UNLOCKED,
    "OFFLINE_PATH_PROVEN": True,
    "VENUE_PATH_PROVEN": False,
    "LIVE_PATH_AUTHORIZED": False,
}
