"""Frozen claims for the offline execution-boundary workpackage persist."""

from __future__ import annotations

from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.constants_v1 import (
    BLIND_RESEND_ALLOWED,
    EXECUTION_PERMISSION_AUTHORITY_EFFECT,
    EXECUTION_READY,
    OWNER_GO,
    PREREQUISITE_08_CLOSED_BY_THIS_PACKAGE,
    PRODUCTIVE_WIRE_REACHABLE,
    SECOND_PERMISSION_AUTHORITY_CREATED,
    STANDING_CANARY_AUTHORIZED,
    STANDING_LIVE_ARMED,
    STANDING_LIVE_AUTHORIZED,
    STANDING_LIVE_ENABLED,
    STANDING_ORDERS_ALLOWED,
    STANDING_SUBMIT_UNLOCKED,
    STANDING_TESTNET_AUTHORIZED,
    THIS_SLICE,
    VENUE_MUTATION_ALLOWED,
    WORKPACKAGE_ID,
)

CLAIMS: dict[str, object] = {
    "OWNER_GO": OWNER_GO,
    "WORKPACKAGE_ID": WORKPACKAGE_ID,
    "THIS_SLICE": THIS_SLICE,
    "EXECUTION_PERMISSION_CONTROLLER_IMPLEMENTED": True,
    "EXECUTION_PERMISSION_AUTHORIZED": False,
    "EXECUTION_PERMISSION_AUTHORITY_EFFECT": EXECUTION_PERMISSION_AUTHORITY_EFFECT,
    "SECOND_PERMISSION_AUTHORITY_CREATED": SECOND_PERMISSION_AUTHORITY_CREATED,
    "OFFLINE_POSITION_CREATION_REQUEST_PRODUCER_IMPLEMENTED": True,
    "POSITION_CREATION_RUNTIME_WIRE_REACHABLE": False,
    "AUTHORIZED_REACHABLE_VENUE_POSITION_PRODUCER": False,
    "REAL_POSITION_CREATED": False,
    "PRODUCTIVE_WIRE_REACHABLE": PRODUCTIVE_WIRE_REACHABLE,
    "VENUE_MUTATION_ALLOWED": VENUE_MUTATION_ALLOWED,
    "BLIND_RESEND_ALLOWED": BLIND_RESEND_ALLOWED,
    "PREREQUISITE_08_CLOSED": PREREQUISITE_08_CLOSED_BY_THIS_PACKAGE,
    "EXECUTION_READY": EXECUTION_READY,
    "LIVE_AUTHORIZED": STANDING_LIVE_AUTHORIZED,
    "TESTNET_AUTHORIZED": STANDING_TESTNET_AUTHORIZED,
    "CANARY_AUTHORIZED": STANDING_CANARY_AUTHORIZED,
    "ORDERS_ALLOWED": STANDING_ORDERS_ALLOWED,
    "LIVE_ENABLED": STANDING_LIVE_ENABLED,
    "LIVE_ARMED": STANDING_LIVE_ARMED,
    "SUBMIT_UNLOCKED": STANDING_SUBMIT_UNLOCKED,
}
