"""Standing constants for post-Z2DQ Route-C create-path blocker census."""

from __future__ import annotations

OWNER_GO = "PEAK_TRADE_OWNER_GO_POST_Z2DQ_MAXIMUM_SAFE_LEVERAGE_V1"
WORKPACKAGE_ID = "POST_Z2DQ_ROUTE_C_CREATE_PATH_BLOCKER_CENSUS_SSOT_PERSIST_V1"
THIS_SLICE = "11.13.5.Z2DR"
PREDECESSOR_SLICE = "11.13.5.Z2DQ"
EXPECTED_ORIGIN_MAIN_SHA = "046d2954f5ad9f51ecc8b1e2b94f54789ddfa013"

Z2DQ_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_z2dq_route_c_net_mode_posside_first_party_contract_evidence_v1/"
    "20260903T153000Z/"
)
Z2DP_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_z2dp_post_z2do_fresh_create_readiness_evidence_v1/"
    "20260903T114921Z/"
)

EARLIEST_UNRESOLVED_DEPENDENCY = "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
CREATE_READINESS_AFTER_ALL_BOUND_SLICES = "BLOCKED_BY_MULTIPLE_GAPS"

NEXT_AUTHORITY_BOUNDARY = (
    "SEPARATE_OWNER_GO_REQUIRED_BEFORE_ANY_VENUE_WIRE_OR_GET_OR_POST_"
    "OR_POSITION_CREATION_OR_FLATTEN_OR_LIVE_OR_CANARY"
)

G_POSMODE_STATUS = "CLOSED"
G_POSMODE_STATUS_CLOSED_AS = "EVIDENCE_EXHAUSTION_FAIL_CLOSED"
G_POSMODE_RESULT_CLASS = "FIRST_PARTY_CONTRACT_EVIDENCE_INSUFFICIENT_FAIL_CLOSED"

OFFLINE_CLOSABLE_GAP_COUNT = 0
RUNTIME_FACT_REQUIRED_GAP_COUNT = 4
HIGHER_AUTHORITY_GAP_COUNT = 3
