"""Adjudicate post-Z2DQ Route-C create-path blocker census."""

from __future__ import annotations

from typing import Any

from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_create_path_blocker_census_v1 import (
    CREATE_PATH_BLOCKER_RECORDS_V1,
    DEPENDENCY_EDGES_V1,
    census_summary_v1,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_create_path_blocker_constants_v1 import (
    CREATE_READINESS_AFTER_ALL_BOUND_SLICES,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EXPECTED_ORIGIN_MAIN_SHA,
    G_POSMODE_RESULT_CLASS,
    G_POSMODE_STATUS,
    G_POSMODE_STATUS_CLOSED_AS,
    HIGHER_AUTHORITY_GAP_COUNT,
    NEXT_AUTHORITY_BOUNDARY,
    OFFLINE_CLOSABLE_GAP_COUNT,
    OWNER_GO,
    PREDECESSOR_SLICE,
    RUNTIME_FACT_REQUIRED_GAP_COUNT,
    THIS_SLICE,
    WORKPACKAGE_ID,
    Z2DP_EVIDENCE_PACK,
    Z2DQ_EVIDENCE_PACK,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_submit_composition_constants_v1 import (
    CREATE_PATH_ARCHITECTURALLY_COMPLETE,
    CREATE_PATH_CURRENTLY_AUTHORIZED,
    CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
    CURRENT_PRODUCTIVE_WIRE_REACHABLE,
    POSITION_MODE_FAIL_CLOSED,
    POSITION_MODE_SUBMIT_BODY_SEMANTICS,
    PREREQUISITE_08_CLOSED,
)


def adjudicate_route_c_create_path_blocker_census_v1() -> dict[str, Any]:
    summary = census_summary_v1()
    open_gaps = [r.gap_id for r in CREATE_PATH_BLOCKER_RECORDS_V1 if r.status == "OPEN"]
    return {
        "OWNER_GO": OWNER_GO,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "EXPECTED_ORIGIN_MAIN_SHA": EXPECTED_ORIGIN_MAIN_SHA,
        "RESULT_CLASS": "CREATE_PATH_BLOCKER_CENSUS_EXHAUSTIVE_COMPLETE",
        "CENSUS_STATUS": "EXHAUSTIVE_COMPLETE",
        "CENSUS_EXHAUSTION_PROVEN": True,
        "CREATE_READINESS_AFTER_ALL_BOUND_SLICES": CREATE_READINESS_AFTER_ALL_BOUND_SLICES,
        "CREATE_READINESS_GAPS": (
            "POSITION_MODE;PRETRADE_GATES;FUNDING_OR_CAPACITY;PREREQUISITE_08;WIRE;CREATE_AUTH"
        ),
        "G_POSMODE_STATUS": G_POSMODE_STATUS,
        "G_POSMODE_STATUS_CLOSED_AS": G_POSMODE_STATUS_CLOSED_AS,
        "G_POSMODE_RESULT_CLASS": G_POSMODE_RESULT_CLASS,
        "POSITION_MODE_SUBMIT_BODY_SEMANTICS": POSITION_MODE_SUBMIT_BODY_SEMANTICS,
        "POSITION_MODE_FAIL_CLOSED": POSITION_MODE_FAIL_CLOSED,
        "POSITION_MODE_READY": False,
        "CREATE_PATH_ARCHITECTURALLY_COMPLETE": CREATE_PATH_ARCHITECTURALLY_COMPLETE,
        "CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE": CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
        "CURRENT_PRODUCTIVE_WIRE_REACHABLE": CURRENT_PRODUCTIVE_WIRE_REACHABLE,
        "CREATE_PATH_CURRENTLY_AUTHORIZED": CREATE_PATH_CURRENTLY_AUTHORIZED,
        "PREREQUISITE_08_CLOSED": PREREQUISITE_08_CLOSED,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "OFFLINE_CLOSABLE_GAP_COUNT": OFFLINE_CLOSABLE_GAP_COUNT,
        "RUNTIME_FACT_REQUIRED_GAP_COUNT": RUNTIME_FACT_REQUIRED_GAP_COUNT,
        "HIGHER_AUTHORITY_GAP_COUNT": HIGHER_AUTHORITY_GAP_COUNT,
        "MAX_SAFE_OFFLINE_BUNDLE_REMAINING": 0,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "Z2DQ_EVIDENCE_PACK": Z2DQ_EVIDENCE_PACK,
        "Z2DP_EVIDENCE_PACK": Z2DP_EVIDENCE_PACK,
        "OPEN_GAP_IDS": open_gaps,
        **summary,
        "BLOCKER_RECORDS": [r.to_dict() for r in CREATE_PATH_BLOCKER_RECORDS_V1],
        "DEPENDENCY_EDGES": [
            {"from": src, "to": dst, "kind": kind} for src, dst, kind in DEPENDENCY_EDGES_V1
        ],
        "OPEN_CONTRADICTIONS": [],
    }
