"""Frozen claims for Route-C net-mode posSide first-party contract evidence persist."""

from __future__ import annotations

from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.constants_v1 import (
    STANDING_CANARY_AUTHORIZED,
    STANDING_LIVE_ARMED,
    STANDING_LIVE_AUTHORIZED,
    STANDING_LIVE_ENABLED,
    STANDING_ORDERS_ALLOWED,
    STANDING_SUBMIT_UNLOCKED,
    STANDING_TESTNET_AUTHORIZED,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_net_mode_posside_first_party_contract_evidence_constants_v1 import (
    CANARY_SEMANTICS_TRANSFER_USED,
    EVIDENCE_EXHAUSTION_PROVEN,
    EXPECTED_ORIGIN_MAIN_SHA,
    FIRST_PARTY_CONTRACT_EVIDENCE_SUFFICIENT,
    FIRST_PARTY_ROUTE_C_NET_MODE_POSSIDE_CONTRACT_FOUND,
    G_POSMODE_STATUS_CLOSED,
    G_POSMODE_STATUS_CLOSED_AS,
    MISSING_EVIDENCE_EDGE,
    OWNER_GO,
    POSITION_MODE_FAIL_CLOSED,
    POSITION_MODE_SEMANTICS_UNPROVEN,
    PREDECESSOR_SLICE,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_submit_composition_constants_v1 import (
    CREATE_PATH_ARCHITECTURALLY_COMPLETE,
    CREATE_PATH_CURRENTLY_AUTHORIZED,
    CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
    CURRENT_PRODUCTIVE_WIRE_REACHABLE,
    HOST_GRAPH_ACTIVATION,
    PREREQUISITE_08_CLOSED,
)

CLAIMS: dict[str, object] = {
    "OWNER_GO": OWNER_GO,
    "WORKPACKAGE_ID": WORKPACKAGE_ID,
    "THIS_SLICE": THIS_SLICE,
    "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
    "EXPECTED_ORIGIN_MAIN_SHA": EXPECTED_ORIGIN_MAIN_SHA,
    "EVIDENCE_EXHAUSTION_PROVEN": EVIDENCE_EXHAUSTION_PROVEN,
    "FIRST_PARTY_CONTRACT_EVIDENCE_SUFFICIENT": FIRST_PARTY_CONTRACT_EVIDENCE_SUFFICIENT,
    "FIRST_PARTY_ROUTE_C_NET_MODE_POSSIDE_CONTRACT_FOUND": (
        FIRST_PARTY_ROUTE_C_NET_MODE_POSSIDE_CONTRACT_FOUND
    ),
    "POSITION_MODE_SUBMIT_BODY_SEMANTICS": POSITION_MODE_SEMANTICS_UNPROVEN,
    "POSITION_MODE_FAIL_CLOSED": POSITION_MODE_FAIL_CLOSED,
    "CANARY_SEMANTICS_TRANSFER_USED": CANARY_SEMANTICS_TRANSFER_USED,
    "G_POSMODE_STATUS": G_POSMODE_STATUS_CLOSED,
    "G_POSMODE_STATUS_CLOSED_AS": G_POSMODE_STATUS_CLOSED_AS,
    "MISSING_EVIDENCE_EDGE": MISSING_EVIDENCE_EDGE,
    "CREATE_PATH_ARCHITECTURALLY_COMPLETE": CREATE_PATH_ARCHITECTURALLY_COMPLETE,
    "CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE": CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
    "CURRENT_PRODUCTIVE_WIRE_REACHABLE": CURRENT_PRODUCTIVE_WIRE_REACHABLE,
    "CREATE_PATH_CURRENTLY_AUTHORIZED": CREATE_PATH_CURRENTLY_AUTHORIZED,
    "HOST_GRAPH_ACTIVATION": HOST_GRAPH_ACTIVATION,
    "PREREQUISITE_08_CLOSED": PREREQUISITE_08_CLOSED,
    "NETWORK_CALL_PERFORMED": False,
    "GET_EXECUTED_THIS_PERSIST": False,
    "POST_EXECUTED": False,
    "POST_ALLOWED": False,
    "CREDENTIAL_ACCESS_PERFORMED": False,
    "LIVE_AUTHORIZED": STANDING_LIVE_AUTHORIZED,
    "TESTNET_AUTHORIZED": STANDING_TESTNET_AUTHORIZED,
    "CANARY_AUTHORIZED": STANDING_CANARY_AUTHORIZED,
    "ORDERS_ALLOWED": STANDING_ORDERS_ALLOWED,
    "LIVE_ENABLED": STANDING_LIVE_ENABLED,
    "LIVE_ARMED": STANDING_LIVE_ARMED,
    "SUBMIT_UNLOCKED": STANDING_SUBMIT_UNLOCKED,
}
