"""Frozen claims for post-Z2DQ Route-C create-path blocker census persist."""

from __future__ import annotations

from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.constants_v1 import (
    STANDING_CANARY_AUTHORIZED,
    STANDING_LIVE_ARMED,
    STANDING_LIVE_AUTHORIZED,
    STANDING_LIVE_ENABLED,
    STANDING_ORDERS_ALLOWED,
    STANDING_SUBMIT_UNLOCKED,
    STANDING_TESTNET_AUTHORIZED,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_create_path_blocker_constants_v1 import (
    CREATE_READINESS_AFTER_ALL_BOUND_SLICES,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EXPECTED_ORIGIN_MAIN_SHA,
    G_POSMODE_RESULT_CLASS,
    G_POSMODE_STATUS,
    G_POSMODE_STATUS_CLOSED_AS,
    NEXT_AUTHORITY_BOUNDARY,
    OWNER_GO,
    PREDECESSOR_SLICE,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_submit_composition_constants_v1 import (
    CREATE_PATH_ARCHITECTURALLY_COMPLETE,
    CREATE_PATH_CURRENTLY_AUTHORIZED,
    CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
    CURRENT_PRODUCTIVE_WIRE_REACHABLE,
    PREREQUISITE_08_CLOSED,
)

CLAIMS: dict[str, object] = {
    "OWNER_GO": OWNER_GO,
    "WORKPACKAGE_ID": WORKPACKAGE_ID,
    "THIS_SLICE": THIS_SLICE,
    "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
    "EXPECTED_ORIGIN_MAIN_SHA": EXPECTED_ORIGIN_MAIN_SHA,
    "CENSUS_EXHAUSTION_PROVEN": True,
    "CREATE_READINESS_AFTER_ALL_BOUND_SLICES": CREATE_READINESS_AFTER_ALL_BOUND_SLICES,
    "G_POSMODE_STATUS": G_POSMODE_STATUS,
    "G_POSMODE_STATUS_CLOSED_AS": G_POSMODE_STATUS_CLOSED_AS,
    "G_POSMODE_RESULT_CLASS": G_POSMODE_RESULT_CLASS,
    "POSITION_MODE_SUBMIT_BODY_SEMANTICS": "UNPROVEN",
    "POSITION_MODE_FAIL_CLOSED": True,
    "CREATE_PATH_ARCHITECTURALLY_COMPLETE": CREATE_PATH_ARCHITECTURALLY_COMPLETE,
    "CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE": CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
    "CURRENT_PRODUCTIVE_WIRE_REACHABLE": CURRENT_PRODUCTIVE_WIRE_REACHABLE,
    "CREATE_PATH_CURRENTLY_AUTHORIZED": CREATE_PATH_CURRENTLY_AUTHORIZED,
    "PREREQUISITE_08_CLOSED": PREREQUISITE_08_CLOSED,
    "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
    "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
    "NETWORK_CALL_PERFORMED": False,
    "GET_EXECUTED_THIS_PERSIST": False,
    "POST_EXECUTED": False,
    "POST_ALLOWED": False,
    "CREDENTIAL_ACCESS_PERFORMED": False,
    "LIVE_AUTHORIZED": STANDING_LIVE_AUTHORIZED,
    "TESTNET_AUTHORIZED": STANDING_TESTNET_AUTHORIZED,
    "CANARY_AUTHORIZED": STANDING_CANARY_AUTHORIZED,
    "ORDERS_ALLOWED": STANDING_ORDERS_ALLOWED,
    "LIVE_ENABLED": STANDING_LIVE_ENABLED,
    "LIVE_ARMED": STANDING_LIVE_ARMED,
    "SUBMIT_UNLOCKED": STANDING_SUBMIT_UNLOCKED,
}
