"""Verifier for Cap 11 §11.12.8 productive Testnet campaign path."""

from __future__ import annotations

from typing import Any

from src.ops.capability_11_section_11_12_8_productive_testnet_campaign_path_v1.constants_v1 import (
    ACTIVATION_STATE,
    AUTHORIZATION_CONSUMED,
    CAPABILITY_11_13_STARTED,
    CAPABILITY_ID,
    CORE_LOGIC_CHANGE,
    EXCHANGE_ORDER_SUBMIT_REACHABLE,
    FIXTURE_PROOF_PRESERVED,
    LIVE_AUTHORIZED,
    LIVE_EXECUTION_REACHABLE,
    NETWORK_EFFECT,
    NETWORK_SESSION_STARTED,
    NETWORK_WRITE_PERFORMED,
    NETWORK_WRITES_AUTHORIZED,
    NEXT_CONSUMER_CAPABILITY_ID,
    ORDER_EFFECT,
    ORDER_PATH_STARTED,
    ORDER_SEND_DISABLED,
    ORDERS_AUTHORIZED,
    PATH_CLASS,
    PREDECESSOR_CAPABILITY_ID,
    PRODUCTIVE_TESTNET_CAMPAIGN_COMPLETED,
    PRODUCTIVE_TESTNET_CAMPAIGN_PATH_ABSENT,
    PRODUCTIVE_TESTNET_CAMPAIGN_PATH_PRESENT,
    PRODUCTIVE_TESTNET_CAMPAIGN_STARTED,
    PRODUCTIVE_TESTNET_CAPABILITY_IMPLEMENTED,
    PRODUCTIVE_TESTNET_EXECUTION_AUTHORIZED,
    REAL_EXECUTION_ADAPTER_CONSTRUCTED,
    REFERENCE_ONLY,
    SECTION_11_13_STARTED,
    TESTNET_AUTHORIZED,
    TESTNET_EXECUTION_REACHABLE,
    TESTNET_ORDER_SUBMIT_PERFORMED,
)
from src.ops.capability_11_section_11_12_8_productive_testnet_campaign_path_v1.productive_path_v1 import (
    prove_productive_testnet_campaign_path_v1,
)

CALL_GRAPH_BEFORE: dict[str, Any] = {
    "nodes": [
        "CanonicalStatefulTradingCore",
        "Cap11_Section_11_12_8_FixtureCampaignEvidence",
        "SimulatedExecutionPort",
    ],
    "productive_testnet_campaign_path": "absent",
    "productive_testnet_execution": "forbidden",
    "testnet_campaign": "not_started",
    "cap_11_13": "not_started",
}

CALL_GRAPH_AFTER: dict[str, Any] = {
    "nodes": [
        "CanonicalStatefulTradingCore",
        "Cap11_Section_11_12_8_FixtureCampaignEvidence",
        "Cap11_Section_11_12_8_ProductiveTestnetCampaignPath",
        "SimulatedExecutionPort",
    ],
    "path_class": PATH_CLASS,
    "fixture_proof": "preserved",
    "productive_testnet_campaign_path": "present",
    "productive_testnet_execution": "forbidden_until_separate_owner_go",
    "network_effect": NETWORK_EFFECT,
    "order_effect": ORDER_EFFECT,
    "testnet_campaign_started": False,
    "cap_11_13": "not_started",
    "next_consumer": NEXT_CONSUMER_CAPABILITY_ID,
}


def verify_capability_11_section_11_12_8_productive_testnet_campaign_path_v1() -> dict[str, Any]:
    proof = prove_productive_testnet_campaign_path_v1()
    ok = bool(proof.get("ok"))
    claims = {
        "CAPABILITY_ID": CAPABILITY_ID,
        "PREDECESSOR_CAPABILITY_ID": PREDECESSOR_CAPABILITY_ID,
        "NEXT_CONSUMER_CAPABILITY_ID": NEXT_CONSUMER_CAPABILITY_ID,
        "CORE_LOGIC_CHANGE": CORE_LOGIC_CHANGE,
        "ACTIVATION_STATE": ACTIVATION_STATE,
        "REFERENCE_ONLY": REFERENCE_ONLY,
        "PATH_CLASS": PATH_CLASS,
        "PRODUCTIVE_TESTNET_CAPABILITY_IMPLEMENTED": (PRODUCTIVE_TESTNET_CAPABILITY_IMPLEMENTED),
        "FIXTURE_PROOF_PRESERVED": FIXTURE_PROOF_PRESERVED,
        "PRODUCTIVE_TESTNET_CAMPAIGN_PATH_PRESENT": (PRODUCTIVE_TESTNET_CAMPAIGN_PATH_PRESENT),
        "PRODUCTIVE_TESTNET_CAMPAIGN_PATH_ABSENT": (PRODUCTIVE_TESTNET_CAMPAIGN_PATH_ABSENT),
        "PRODUCTIVE_TESTNET_EXECUTION_AUTHORIZED": (PRODUCTIVE_TESTNET_EXECUTION_AUTHORIZED),
        "PRODUCTIVE_TESTNET_CAMPAIGN_STARTED": PRODUCTIVE_TESTNET_CAMPAIGN_STARTED,
        "PRODUCTIVE_TESTNET_CAMPAIGN_COMPLETED": PRODUCTIVE_TESTNET_CAMPAIGN_COMPLETED,
        "NETWORK_EFFECT": NETWORK_EFFECT,
        "ORDER_EFFECT": ORDER_EFFECT,
        "ORDER_SEND_DISABLED": ORDER_SEND_DISABLED,
        "ORDERS_AUTHORIZED": ORDERS_AUTHORIZED,
        "ORDER_PATH_STARTED": ORDER_PATH_STARTED,
        "NETWORK_WRITES_AUTHORIZED": NETWORK_WRITES_AUTHORIZED,
        "NETWORK_WRITE_PERFORMED": NETWORK_WRITE_PERFORMED,
        "NETWORK_SESSION_STARTED": NETWORK_SESSION_STARTED,
        "EXCHANGE_ORDER_SUBMIT_REACHABLE": EXCHANGE_ORDER_SUBMIT_REACHABLE,
        "TESTNET_ORDER_SUBMIT_PERFORMED": TESTNET_ORDER_SUBMIT_PERFORMED,
        "TESTNET_EXECUTION_REACHABLE": TESTNET_EXECUTION_REACHABLE,
        "LIVE_EXECUTION_REACHABLE": LIVE_EXECUTION_REACHABLE,
        "REAL_EXECUTION_ADAPTER_CONSTRUCTED": REAL_EXECUTION_ADAPTER_CONSTRUCTED,
        "LIVE_AUTHORIZED": LIVE_AUTHORIZED,
        "TESTNET_AUTHORIZED": TESTNET_AUTHORIZED,
        "AUTHORIZATION_CONSUMED": AUTHORIZATION_CONSUMED,
        "CAPABILITY_11_13_STARTED": CAPABILITY_11_13_STARTED,
        "SECTION_11_13_STARTED": SECTION_11_13_STARTED,
        "PATH_PROOF_OK": proof.get("ok"),
        "START_GATE_MAY_START": proof.get("start_gate_may_start"),
        "START_GATE_STARTED": proof.get("start_gate_started"),
        "PATH_ONLY_MAY_START": proof.get("path_only_may_start"),
        "LIVE_BLOCKED": proof.get("live_blocked"),
        "CREDENTIAL_SCOPE_BLOCKED": proof.get("credential_scope_blocked"),
        "ENABLED_FALSE_BLOCKED": proof.get("enabled_false_blocked"),
        "ARMED_FALSE_BLOCKED": proof.get("armed_false_blocked"),
        "OWNER_AUTH_BLOCKED": proof.get("owner_auth_blocked"),
        "CONFIRM_INVALID_BLOCKED": proof.get("confirm_invalid_blocked"),
        "CONFIRM_MISMATCH_BLOCKED": proof.get("confirm_mismatch_blocked"),
        "CONFIRM_ARGV_BLOCKED": proof.get("confirm_argv_blocked"),
        "SCOPE_ESCALATION_BLOCKED": proof.get("scope_escalation_blocked"),
        "CAMPAIGN_START_REFUSED": proof.get("campaign_start_refused"),
        "EXECUTION_REFUSED": proof.get("execution_refused"),
        "CAP_11_13_REFUSED": proof.get("cap_11_13_refused"),
        "ORDER_SUBMIT_REFUSED": proof.get("order_submit_refused"),
        "NETWORK_SESSION_REFUSED": proof.get("network_session_refused"),
        "LIVE_PATH_REFUSED": proof.get("live_path_refused"),
        "INSTRUMENT_SCOPE_BLOCKED": proof.get("instrument_scope_blocked"),
        "ORDER_TYPE_BLOCKED": proof.get("order_type_blocked"),
        "POSITION_LIMIT_BLOCKED": proof.get("position_limit_blocked"),
        "KILL_SWITCH_BLOCKED": proof.get("kill_switch_blocked"),
        "EMERGENCY_CONTROL_BLOCKED": proof.get("emergency_control_blocked"),
        "PATH_BINDING_DIGEST": proof.get("path_binding_digest"),
    }
    return {
        "ok": ok,
        "VERIFIER_RESULT": "PASS" if ok else "FAIL",
        "CAPABILITY_ID": CAPABILITY_ID,
        "claims": claims,
        "proofs": {"productive_path": proof},
        "call_graph_before": CALL_GRAPH_BEFORE,
        "call_graph_after": CALL_GRAPH_AFTER,
    }
