"""Constants for the CURRENT MF-member → pinned Cap23 N=1 adapter contract."""

from __future__ import annotations

from src.ops.single_selected_future_policy_v1.governed_pin_v1 import (
    ADAPTER_MAY_RERANK,
    ADAPTER_MAY_RESELECT,
    ADAPTER_MAY_WRITE_CAP23_SELECTION,
    CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION,
    INSTRUMENT_ID_ALONE_SUFFICIENT,
    MULTI_UNIVERSE_MERGE,
    PIN_IS_SELECTION_AUTHORITY,
)

OWNER = "ops.current_mf_member_to_pinned_cap23_n1_adapter_v1"
CONTRACT_ID = "CURRENT_MF_MEMBER_TO_PINNED_CAP23_N1_ADAPTER_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_member_to_pinned_cap23_n1_adapter.v1"
CANONICAL_UNIVERSE_IDENTITY_SOURCE = "ProductiveFuturesRankingSnapshotV1.universe_snapshot_id"

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
PIN_AUTHORITY = "NON_AUTHORITATIVE_CONSTRAINT_ONLY"
CAP23_SELECTION_OWNER = "ops.single_selected_future_policy_v1"
CAP24_BINDING_OWNER = "ops.single_selected_future_runtime_binding_v1"

MF_PRODUCTIVE_JOIN = False
FIVE_LANE_RUNTIME_CREATED = False
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = False
MF_SINGLE_EGRESS_REWIRED = False

PIN_IS_SELECTION_AUTHORITY = PIN_IS_SELECTION_AUTHORITY
ADAPTER_MAY_WRITE_CAP23_SELECTION = ADAPTER_MAY_WRITE_CAP23_SELECTION
ADAPTER_MAY_RERANK = ADAPTER_MAY_RERANK
ADAPTER_MAY_RESELECT = ADAPTER_MAY_RESELECT
CROSS_UNIVERSE_SELECTION = CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = INSTRUMENT_ID_ALONE_SUFFICIENT

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "produce_single_selected_future_v1",
        "run_single_selected_future_policy_v1",
        "persist_selection_bundle_atomic_v1",
        "mf_membership_selector_and_rotation_runtime_contract_v1",
        "mf_canonical_single_egress_authority_handoff_contract_v1",
        "master_v2",
        "double_play",
        "execution",
        "top_n_active_set",
    }
)
