"""Standing constants for the P11 POS_TO_SZ unit-identity independent proof.

Public official-spec retrieval plus offline adjudication. No private GET.
No POST. No flatten execute. No Live/Canary/submit unlock. No alias
promotion of ORDER_PLAN contracts into TARGET_POSITION_QTY.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.venue_contract_count_v1 import (
    ORDER_PLAN_QTY_DOMAIN,
    ORDER_PLAN_QTY_UNIT,
    SUI_OPERATIVE_ORDER_SZ,
    SUI_OPERATIVE_ORDER_SZ_UNIT,
)
from src.ops.section_11_13_5_p11_pos_to_sz_unit_identity_independent_proof_v1.contract_v1 import (
    CASE,
    CONVERSION_FORMULA,
    CURRENT_UNIT_CONTRACT,
    IDENTITY_OR_CONVERSION,
    INSTRUMENT_SCOPE,
    NUMBER_OF_CONTRACTS,
    POS_UNIT,
    SZ_UNIT,
    TARGET_POSITION_QTY_UNIT_STATUS,
    UNIT_CHAIN_VERDICT,
)

CAPABILITY_ID = "P11_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF_V1"
PACKAGE_MARKER = "P11_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF_V1=true"
OWNER = "ops.section_11_13_5_p11_pos_to_sz_unit_identity_independent_proof_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p11_pos_to_sz_unit_identity_independent_proof.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF_NO_ALIAS_PROMOTION_V1"
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT"
    "_FORENSIC_ADJUDICATE_OFFLINE_PERSIST_PR_V1"
)
WORKPACKAGE_ID = "OKX_EEA_P11_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF_V1"
THIS_SLICE = "11.13.5.P11"
PREDECESSOR_SLICE = "11.13.5.P10"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_P11"
EXPECTED_ORIGIN_MAIN_SHA = "4861bd3feaa2949d62ef2c3eab435ea2d917bf05"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "INDEPENDENT_POS_TO_SZ_UNIT_IDENTITY_PROOF_OFFLINE_AND_PUBLIC_SPEC"
AUTHORIZED_SCOPE = "A_P11_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF"
CANONICAL_EVIDENCE_RUN_ID = "20260903T233500Z"

TARGET_POSITION_QTY_UNIT = TARGET_POSITION_QTY_UNIT_STATUS
CURRENT_UNIT_CONTRACT_VALUE = CURRENT_UNIT_CONTRACT
POS_TO_SZ_UNIT_IDENTITY = "PROVEN"
POS_UNIT_VALUE = POS_UNIT
SZ_UNIT_VALUE = SZ_UNIT
IDENTITY_OR_CONVERSION_VALUE = IDENTITY_OR_CONVERSION
CONVERSION_FORMULA_VALUE = CONVERSION_FORMULA
INSTRUMENT_SCOPE_VALUE = INSTRUMENT_SCOPE
CASE_VALUE = CASE
UNIT_CHAIN_VERDICT_VALUE = UNIT_CHAIN_VERDICT
QTY_UNIT_CENSUS_COMPLETE = True
QTY_UNIT_LINEAGE_COMPLETE = True
EARLIEST_MISSING_QTY_UNIT_PROOF = "NONE_POS_TO_SZ_UNIT_IDENTITY_PROVEN"
EARLIEST_UNRESOLVED_DEPENDENCY = "EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE"
EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT = "PASS"
CONFLICT_COUNT = 0
ORDER_PLAN_QTY_UNIT_CURRENT = ORDER_PLAN_QTY_UNIT
ORDER_PLAN_QTY_DOMAIN_CURRENT = ORDER_PLAN_QTY_DOMAIN
SUI_OPERATIVE_ORDER_SZ_CURRENT = SUI_OPERATIVE_ORDER_SZ
SUI_OPERATIVE_ORDER_SZ_UNIT_CURRENT = SUI_OPERATIVE_ORDER_SZ_UNIT
ORDER_PLAN_QTY_IS_NOT_TARGET_POSITION_QTY = True
SUI_OPERATIVE_ORDER_SZ_IS_NOT_TARGET_POSITION_QTY = True
ONE_CONTRACT_EQUALS_ONE_SUI = False
NUMERIC_POS_EQUALS_SZ_IS_NOT_UNIT_PROOF = True
MINSZ_1_IS_NOT_UNIT_PROOF = True
CTVAL_1_IS_NOT_UNIT_PROOF = True
CTVAL_IS_NOT_POS_TO_SZ_FACTOR = True
HISTORICAL_ORDER_PLAN_VENUE_CONTRACT_COUNT_IS_NOT_CURRENT_TARGET_POSITION_QTY_UNIT = True
HISTORICAL_BTC_DENOMINATION_IS_NOT_CURRENT_SUI_XPERP_TARGET_POSITION_QTY_UNIT = True
P08_CLOSED = True
P10_CLOSED = True
P10_DOES_NOT_PROVE_TARGET_POSITION_QTY_UNIT = True
TARGET_POSITION_NONZERO_PROVEN = True
TARGET_POSITION_QTY_NUMERIC = "PASS"
P11_DOES_NOT_GRANT_EXECUTION_READINESS = True
P11_DOES_NOT_AUTHORIZE_FLATTEN = True
IMPLICIT_PASSTHROUGH_PRESENT = True
IMPLICIT_PASSTHROUGH_IS_NOT_UNIT_PROOF = True
IDENTITY_NOW_INDEPENDENTLY_PROVEN = True
PLACE_ORDER_REQUEST_PARAM_NAMES_UNIT = False
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = True
ORIGINAL_WIRE_BODY_BYTES_AVAILABLE = False
POSCCY_PRESENT_IN_AUTHORIZED_P08_CAPTURE = False

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_p11_pos_to_sz_unit_identity_independent_proof_v1"

FORBIDDEN_PROMOTION_ALIASES: tuple[str, ...] = (
    "qty",
    "sz",
    "size",
    "contracts",
    "contract count",
    "base",
    "base amount",
    "quote amount",
    "notional",
    "position size",
    ORDER_PLAN_QTY_UNIT,
    ORDER_PLAN_QTY_DOMAIN,
    SUI_OPERATIVE_ORDER_SZ_UNIT,
    "VENUE_CONTRACT_COUNT",
    "CONTRACTS_SZ",
    "minSz",
    "lotSz",
    "ctVal",
    "ctValCcy",
)

# Proven status token is allowed. Physical unit token is NUMBER_OF_CONTRACTS
# from the official phrase, not ORDER_PLAN "contracts".
ALLOWED_UNIT_TOKENS: frozenset[str] = frozenset(
    {
        "PROVEN",
        NUMBER_OF_CONTRACTS,
        UNIT_CHAIN_VERDICT,
    }
)
