"""
Realistic scenario tests for Live-Overrides integration.

Tests the complete workflow from Promotion Loop writing auto.toml
to PeakConfig loading it in different environments.
"""

from pathlib import Path
from tempfile import TemporaryDirectory

import pytest

from src.core.peak_config import load_config_with_live_overrides


def test_complete_workflow_live_environment():
    """
    Test des kompletten Workflows:
    1. Promotion Loop schreibt auto.toml
    2. Live-Session lädt Config mit Overrides
    3. Parameter werden korrekt angewendet
    """
    with TemporaryDirectory() as tmpdir:
        # Schritt 1: Setup - Basis-Config erstellen (Paper-Defaults)
        config_path = Path(tmpdir) / "config.toml"
        config_path.write_text(
            """
# Basis-Config (Paper-Defaults)
[environment]
mode = "live"
enable_live_trading = true
live_dry_run_mode = true

[portfolio]
leverage = 1.0
max_position_size = 0.1

[strategy]
name = "ma_crossover"
trigger_delay = 10.0
fast_window = 20
slow_window = 50

[risk]
max_position = 0.1
stop_loss = 0.02

[macro]
regime_weight = 0.0
""",
            encoding="utf-8",
        )

        # Schritt 2: Promotion Loop schreibt Auto-Overrides (bounded_auto)
        auto_path = Path(tmpdir) / "auto.toml"
        auto_path.write_text(
            """
# Auto-generated by Promotion Loop v0 (bounded_auto)
[auto_applied]
"portfolio.leverage" = 1.75
"strategy.trigger_delay" = 8.0
"macro.regime_weight" = 0.35
"risk.max_position" = 0.12
""",
            encoding="utf-8",
        )

        # Schritt 3: Live-Session lädt Config
        cfg = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )

        # Schritt 4: Verifikation - Overrides wurden angewendet
        assert cfg.get("portfolio.leverage") == 1.75
        assert cfg.get("strategy.trigger_delay") == 8.0
        assert cfg.get("macro.regime_weight") == 0.35
        assert cfg.get("risk.max_position") == 0.12

        # Unveränderte Werte bleiben erhalten
        assert cfg.get("portfolio.max_position_size") == 0.1
        assert cfg.get("strategy.fast_window") == 20
        assert cfg.get("strategy.slow_window") == 50
        assert cfg.get("risk.stop_loss") == 0.02


def test_workflow_testnet_environment():
    """Test dass Overrides auch in Testnet-Environment angewendet werden."""
    with TemporaryDirectory() as tmpdir:
        config_path = Path(tmpdir) / "config.toml"
        config_path.write_text(
            """
[environment]
mode = "testnet"

[portfolio]
leverage = 1.0
""",
            encoding="utf-8",
        )

        auto_path = Path(tmpdir) / "auto.toml"
        auto_path.write_text(
            """
[auto_applied]
"portfolio.leverage" = 1.5
""",
            encoding="utf-8",
        )

        cfg = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )

        assert cfg.get("portfolio.leverage") == 1.5


def test_workflow_paper_environment_no_apply():
    """
    Test dass in Paper-Environment keine Overrides angewendet werden.
    Dies ist der Standard-Backtest-Workflow.
    """
    with TemporaryDirectory() as tmpdir:
        config_path = Path(tmpdir) / "config.toml"
        config_path.write_text(
            """
[environment]
mode = "paper"

[portfolio]
leverage = 1.0

[strategy]
trigger_delay = 10.0
""",
            encoding="utf-8",
        )

        # auto.toml existiert, wird aber nicht angewendet
        auto_path = Path(tmpdir) / "auto.toml"
        auto_path.write_text(
            """
[auto_applied]
"portfolio.leverage" = 2.0
"strategy.trigger_delay" = 5.0
""",
            encoding="utf-8",
        )

        cfg = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )

        # Original-Werte bleiben in Paper-Environment
        assert cfg.get("portfolio.leverage") == 1.0
        assert cfg.get("strategy.trigger_delay") == 10.0


def test_incremental_override_updates():
    """
    Test dass sukzessive Updates in auto.toml korrekt verarbeitet werden.
    Simuliert mehrere Promotion Loop Cycles.
    """
    with TemporaryDirectory() as tmpdir:
        config_path = Path(tmpdir) / "config.toml"
        config_path.write_text(
            """
[environment]
mode = "live"

[portfolio]
leverage = 1.0

[strategy]
trigger_delay = 10.0

[macro]
regime_weight = 0.0
""",
            encoding="utf-8",
        )

        auto_path = Path(tmpdir) / "auto.toml"

        # Cycle 1: Nur Leverage-Override
        auto_path.write_text(
            """
[auto_applied]
"portfolio.leverage" = 1.25
""",
            encoding="utf-8",
        )

        cfg1 = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )
        assert cfg1.get("portfolio.leverage") == 1.25
        assert cfg1.get("strategy.trigger_delay") == 10.0
        assert cfg1.get("macro.regime_weight") == 0.0

        # Cycle 2: Leverage + Trigger-Delay
        auto_path.write_text(
            """
[auto_applied]
"portfolio.leverage" = 1.5
"strategy.trigger_delay" = 8.0
""",
            encoding="utf-8",
        )

        cfg2 = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )
        assert cfg2.get("portfolio.leverage") == 1.5
        assert cfg2.get("strategy.trigger_delay") == 8.0
        assert cfg2.get("macro.regime_weight") == 0.0

        # Cycle 3: Alle drei Parameter
        auto_path.write_text(
            """
[auto_applied]
"portfolio.leverage" = 1.75
"strategy.trigger_delay" = 7.0
"macro.regime_weight" = 0.3
""",
            encoding="utf-8",
        )

        cfg3 = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )
        assert cfg3.get("portfolio.leverage") == 1.75
        assert cfg3.get("strategy.trigger_delay") == 7.0
        assert cfg3.get("macro.regime_weight") == 0.3


def test_mixed_types_in_overrides():
    """Test dass verschiedene Datentypen korrekt angewendet werden."""
    with TemporaryDirectory() as tmpdir:
        config_path = Path(tmpdir) / "config.toml"
        config_path.write_text(
            """
[environment]
mode = "live"

[portfolio]
leverage = 1.0
max_position_size = 0.1

[strategy]
trigger_delay = 10
fast_window = 20

[flags]
enable_feature = false
""",
            encoding="utf-8",
        )

        auto_path = Path(tmpdir) / "auto.toml"
        auto_path.write_text(
            """
[auto_applied]
"portfolio.leverage" = 1.75          # float
"portfolio.max_position_size" = 0.15 # float
"strategy.trigger_delay" = 8         # int
"strategy.fast_window" = 25          # int
"flags.enable_feature" = true        # bool
""",
            encoding="utf-8",
        )

        cfg = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )

        assert cfg.get("portfolio.leverage") == 1.75
        assert cfg.get("portfolio.max_position_size") == 0.15
        assert cfg.get("strategy.trigger_delay") == 8
        assert cfg.get("strategy.fast_window") == 25
        assert cfg.get("flags.enable_feature") is True


def test_deeply_nested_overrides():
    """Test dass tief verschachtelte Pfade korrekt funktionieren."""
    with TemporaryDirectory() as tmpdir:
        config_path = Path(tmpdir) / "config.toml"
        config_path.write_text(
            """
[environment]
mode = "live"

[portfolio.risk.limits]
max_position = 0.1
max_leverage = 2.0

[strategy.ma_crossover.params]
fast = 10
slow = 30

[live.execution.slippage]
model = "fixed"
value = 0.001
""",
            encoding="utf-8",
        )

        auto_path = Path(tmpdir) / "auto.toml"
        auto_path.write_text(
            """
[auto_applied]
"portfolio.risk.limits.max_position" = 0.12
"portfolio.risk.limits.max_leverage" = 2.5
"strategy.ma_crossover.params.fast" = 12
"live.execution.slippage.value" = 0.0015
""",
            encoding="utf-8",
        )

        cfg = load_config_with_live_overrides(
            config_path, auto_overrides_path=auto_path
        )

        assert cfg.get("portfolio.risk.limits.max_position") == 0.12
        assert cfg.get("portfolio.risk.limits.max_leverage") == 2.5
        assert cfg.get("strategy.ma_crossover.params.fast") == 12
        assert cfg.get("live.execution.slippage.value") == 0.0015
        # Unchanged
        assert cfg.get("strategy.ma_crossover.params.slow") == 30
        assert cfg.get("live.execution.slippage.model") == "fixed"
