"""Authority / evidence matrix for Cap 7.1 lifecycles."""

from __future__ import annotations

from typing import Any

from src.ops.simulated_entry_reduce_exit_actionability_evidence_v1.constants_v1 import (
    ACCOUNTING_CALLER,
    OWNER,
    PERSISTENCE_CALLER,
    PRODUCTIVE_ENTRY_CALLER,
    PRODUCTIVE_EXIT_CALLER,
    PRODUCTIVE_HOST,
    PRODUCTIVE_REDUCE_CALLER,
    RECONCILIATION_CALLER,
    SIMULATED_EXECUTION_CALLER,
)


def inventory_actionability_authority_v1() -> dict[str, Any]:
    matrix = [
        {
            "lifecycle_class": "long_full_cycle",
            "controlled_market_inputs": "rising_mids_after_feature_warmup_seed",
            "expected_canonical_decision": "enter_long → hold → profit/adverse/time exit",
            "expected_intent": "BUY entry then SELL exit/reduce",
            "productive_caller": PRODUCTIVE_ENTRY_CALLER,
            "state_roots": [
                "confirmation",
                "dynamic_scope",
                "decision_config",
                "accounting",
                "decision_path_atomic",
                "exit_policy",
                "reconciliation",
            ],
            "config_owners": "ops.decision_config_ownership_and_consumer_closure_v1",
            "event_time_owner": "host_cycle_event_ts_unix",
            "execution_consumer": SIMULATED_EXECUTION_CALLER,
            "accounting_consumer": ACCOUNTING_CALLER,
            "persistence_commit": PERSISTENCE_CALLER,
            "restart_point": "cap64_atomic_commit_marker",
            "reconciliation_result": "RECONCILED_BEFORE_ALPHA",
            "evidence_record": "long_lifecycle_trace_v1.json",
            "verifier_claim": "ENTRY_END_TO_END_EVIDENCE_PROVEN + EXIT_END_TO_END_EVIDENCE_PROVEN",
            "forbidden_direct_injection": True,
        },
        {
            "lifecycle_class": "short_full_cycle",
            "controlled_market_inputs": "falling_mids_below_default_protective_stop_anchor",
            "expected_canonical_decision": "enter_short → hold → adverse/profit exit",
            "expected_intent": "SELL entry then BUY exit/reduce",
            "productive_caller": PRODUCTIVE_ENTRY_CALLER,
            "state_roots": [
                "confirmation",
                "dynamic_scope",
                "decision_config",
                "accounting",
                "decision_path_atomic",
                "exit_policy",
                "reconciliation",
            ],
            "config_owners": "ops.decision_config_ownership_and_consumer_closure_v1",
            "event_time_owner": "host_cycle_event_ts_unix",
            "execution_consumer": SIMULATED_EXECUTION_CALLER,
            "accounting_consumer": ACCOUNTING_CALLER,
            "persistence_commit": PERSISTENCE_CALLER,
            "restart_point": "cap64_atomic_commit_marker",
            "reconciliation_result": "RECONCILED_BEFORE_ALPHA",
            "evidence_record": "short_lifecycle_trace_v1.json",
            "verifier_claim": "SHORT_LIFECYCLE_PROVEN",
            "forbidden_direct_injection": True,
        },
        {
            "lifecycle_class": "partial_reduce",
            "controlled_market_inputs": "profit_protection_path_with_partial_qty",
            "expected_canonical_decision": "reduce then continue/exit",
            "expected_intent": "partial SELL/BUY reduce",
            "productive_caller": PRODUCTIVE_REDUCE_CALLER,
            "state_roots": ["accounting", "decision_path_atomic", "exit_policy"],
            "config_owners": "ops.decision_config_ownership_and_consumer_closure_v1",
            "event_time_owner": "host_cycle_event_ts_unix",
            "execution_consumer": SIMULATED_EXECUTION_CALLER,
            "accounting_consumer": ACCOUNTING_CALLER,
            "persistence_commit": PERSISTENCE_CALLER,
            "restart_point": "after_partial_reduce_before_final_exit",
            "reconciliation_result": "RECONCILED_BEFORE_ALPHA",
            "evidence_record": "reduce_lifecycle_trace_v1.json",
            "verifier_claim": "PARTIAL_REDUCE_LIFECYCLE_PROVEN",
            "forbidden_direct_injection": True,
        },
        {
            "lifecycle_class": "canonical_exit_ladder",
            "controlled_market_inputs": "adverse_distance / profit_distance / time_hold",
            "expected_canonical_decision": "adverse_scope_exit | profit_protection_exit | time_exit",
            "expected_intent": "exit/reduce intent from Cap 6.5 producers",
            "productive_caller": PRODUCTIVE_EXIT_CALLER,
            "state_roots": ["exit_policy", "accounting", "decision_path_atomic"],
            "config_owners": "ops.exit_policy_producer_binding_v1",
            "event_time_owner": "host_cycle_event_ts_unix",
            "execution_consumer": SIMULATED_EXECUTION_CALLER,
            "accounting_consumer": ACCOUNTING_CALLER,
            "persistence_commit": PERSISTENCE_CALLER,
            "restart_point": "open_position_before_exit",
            "reconciliation_result": "RECONCILED_BEFORE_ALPHA",
            "evidence_record": "failure_injection_results.json + lifecycle traces",
            "verifier_claim": "EXIT_SIMULATED_FILL_OBSERVED",
            "forbidden_direct_injection": True,
        },
        {
            "lifecycle_class": "restart_and_failure",
            "controlled_market_inputs": "duplicate_obs / corrupt_checkpoint / writer_conflict",
            "expected_canonical_decision": "fail-closed or idempotent continuation",
            "expected_intent": "no duplicate intents/fills",
            "productive_caller": PRODUCTIVE_HOST,
            "state_roots": ["decision_path_atomic", "confirmation", "dynamic_scope"],
            "config_owners": "ops.full_decision_path_atomic_restart_closure_v1",
            "event_time_owner": "host_cycle_event_ts_unix",
            "execution_consumer": SIMULATED_EXECUTION_CALLER,
            "accounting_consumer": ACCOUNTING_CALLER,
            "persistence_commit": PERSISTENCE_CALLER,
            "restart_point": "flat | open | confirmation | dynamic_scope",
            "reconciliation_result": RECONCILIATION_CALLER,
            "evidence_record": "restart_recovery_traces_v1.json",
            "verifier_claim": "DETERMINISTIC_REPLAY_PROVEN + EVIDENCE_RECOVERY_IDEMPOTENT",
            "forbidden_direct_injection": True,
        },
    ]
    return {
        "owner": OWNER,
        "productive_host": PRODUCTIVE_HOST,
        "parallel_decision_authority_created": False,
        "core_logic_changed": False,
        "forced_intent_allowed": False,
        "direct_fill_injection_allowed": False,
        "matrix": matrix,
    }
