"""Standing constants for the P08 one-shot unfiltered positions GET.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1,
build_okx_live_canary_auth_headers_v1, classify_target_position_state_v1,
and build_account_positions_query_v1(unfiltered). Does not mint a second
HTTP client, signer, SecretRef owner, live/testnet/canary authority, or
mutation path. Does not authorize POST, flatten, P09 work, or posSide
submit-body proof.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    ENDPOINT_ACCOUNT_POSITIONS,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)

CAPABILITY_ID = "P08_POSITION_OBSERVATION_V1"
PACKAGE_MARKER = "P08_POSITION_OBSERVATION_V1=true"
OWNER = "ops.section_11_13_5_p08_position_observation_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p08_position_observation.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_P08_POSITION_OBSERVATION_V1"
WORKPACKAGE_ID = "OKX_EEA_P08_POSITION_OBSERVATION_SINGLE_GET_V1"
THIS_SLICE = "11.13.5.P08_POSITION_OBSERVATION"
PREDECESSOR_SLICE = "11.13.5.POST_Z2DS_POST_WHITELIST_PRIVATE_AUTH_ATTESTATION"
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "12e2d222e95b78ddc91c642253c6907743495ba9"
AUTHORIZED_HOST = "eea.okx.com"
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID

AUTHORIZED_OPERATION = (
    "EXACTLY_ONE_AUTHENTICATED_NON_MUTATING_UNFILTERED_PRIVATE_GET_ACCOUNT_POSITIONS"
)
AUTHORIZED_ENDPOINT = "GET /api/v5/account/positions"
MAX_NETWORK_REQUEST_COUNT = 1
MAX_HTTP_EXCHANGE_COUNT = 1
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
RETRY_AUTHORIZED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
SECOND_GET_ALLOWED = False
SECOND_GET_AUTHORIZED = False
ALTERNATE_ENDPOINT_ALLOWED = False
INSTID_FILTER_ALLOWED = False
PUBLIC_GET_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
P08_OBSERVATION_ALLOWED = True
P08_CLOSE_ALLOWED = True
FUNDING_ALLOWED = False
BALANCE_GET_ALLOWED = False
CONFIG_GET_ALLOWED = False
MAX_SIZE_GET_ALLOWED = False
KEY_ROTATION_ALLOWED = False
PERMISSION_CHANGE_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
POSITION_CREATION_ALLOWED = False
POSITION_MODIFICATION_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
G_POSMODE_REOPEN_ALLOWED = False
G_POSMODE_CLOSE_ALLOWED = False
P09_WORK_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False

ENDPOINT = ENDPOINT_ACCOUNT_POSITIONS
ENDPOINT_METHOD = "GET"
FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/config",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
REUSED_CLASSIFIER = "classify_target_position_state_v1"
REUSED_QUERY_BUILDER = "build_account_positions_query_v1"
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET = False

EVIDENCE_DIRNAME = "section_11_13_5_p08_position_observation_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)
P08_CANONICAL_DEFINITION = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN:"
    "positive observation-proof gate requiring HTTP 200, OKX 0, unfiltered "
    "GET /api/v5/account/positions, exactly one target-instrument row, and "
    "canonically nonzero pos. Empty data[] is not zero. Absent target row "
    "is not zero. Zero row does not close P08."
)
FRESHNESS_POLICY = (
    "FLATTEN_PRE_SEND_MAX_AGE_MS=5000;"
    "THIS_WINDOW_SAMPLES_AGE_AFTER_GET_AND_IS_NOT_FLATTEN_SEND_PERMIT"
)
EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False

RESULT_CLASS_200_OKX_0 = "HTTP_200_OKX_0"
RESULT_CLASS_401_50110 = "HTTP_401_OKX_50110"
RESULT_CLASS_OTHER = "OTHER_FAIL_CLOSED"
RESULT_CLASS_TRANSPORT = "TRANSPORT_OR_CLIENT_FAIL"

CASE_A_TARGET_NONZERO = "CASE_A_TARGET_NONZERO"
CASE_B_TARGET_ZERO = "CASE_B_TARGET_ZERO"
CASE_C_EMPTY_DATA_NOT_ZERO = "CASE_C_EMPTY_DATA_NOT_ZERO"
CASE_D_TARGET_NOT_OBSERVED = "CASE_D_TARGET_INSTRUMENT_NOT_OBSERVED"
CASE_E_HTTP_OR_OKX_ERROR = "CASE_E_HTTP_AUTH_OR_OKX_ERROR"
CASE_F_AMBIGUOUS = "CASE_F_AMBIGUOUS_OR_CONTRADICTORY"

NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC = (
    "SEPARATE_OWNER_GO_FOR_EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT"
)
NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_UNRESOLVED = (
    "SEPARATE_OWNER_GO_FOR_EXECUTION_PREREQUISITE_09_TARGET_POSITION_QTY_NUMERIC"
)
NEXT_AUTHORITY_BOUNDARY_CASE_B = (
    "SEPARATE_OWNER_GO_REQUIRED_P08_NONZERO_NOT_SATISFIED_ZERO_ROW_THIS_WINDOW"
)
NEXT_AUTHORITY_BOUNDARY_CASE_C = "SEPARATE_OWNER_GO_REQUIRED_P08_EMPTY_DATA_IS_NOT_ZERO"
NEXT_AUTHORITY_BOUNDARY_CASE_D = "SEPARATE_OWNER_GO_REQUIRED_P08_TARGET_INSTRUMENT_NOT_OBSERVED"
NEXT_AUTHORITY_BOUNDARY_CASE_E = (
    "SEPARATE_OWNER_GO_REQUIRED_AFTER_POSITION_GET_ERROR_NO_RETRY_UNDER_THIS_GO"
)
NEXT_AUTHORITY_BOUNDARY_CASE_F = (
    "SEPARATE_OWNER_GO_REQUIRED_AFTER_AMBIGUOUS_POSITION_ROWS_NO_RETRY_UNDER_THIS_GO"
)
