"""WP-B safety boundary and authority attestation."""

from __future__ import annotations

from typing import Any

from src.ops.full_core_live_path_composition_root_v1.constants_v1 import (
    EXTERNAL_EFFECT_AUTHORIZED,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    POST_ALLOWED,
    PRODUCTIVE_WIRE_SEND_REACHABLE,
    REAL_EXTERNAL_EFFECT_AUTHORIZED,
    REAL_VENUE_POST_ALLOWED,
    SUBMISSION_AUTHORIZED,
    WIRE_SEND_PERMITTED,
)
from src.ops.okx_eea_private_account_state_runtime_v1.constants_v1 import (
    EXECUTION_AUTHORITY,
    K2_ABSENT,
    MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED,
    PRIVATE_WS_AMEND_AUTHORIZED,
    PRIVATE_WS_CANCEL_AUTHORIZED,
    PRIVATE_WS_ORDER_SEND_AUTHORIZED,
    RANKING_AUTHORITY,
    REST_POST_PERMIT_CHANGE,
    RUNNING_ACCOUNT_EQUITY_MINT_ALLOWED,
    SELECTION_AUTHORITY,
    STRATEGY_AUTHORITY,
    WP_B_RANKING_AUTHORITY,
    WP_B_SELECTION_AUTHORITY,
    WP_B_STRATEGY_AUTHORITY,
)


def private_runtime_safety_attestation_v1() -> dict[str, Any]:
    return {
        "WP_B_STRATEGY_AUTHORITY": WP_B_STRATEGY_AUTHORITY,
        "WP_B_RANKING_AUTHORITY": WP_B_RANKING_AUTHORITY,
        "WP_B_SELECTION_AUTHORITY": WP_B_SELECTION_AUTHORITY,
        "CAP_2_3_SOLE_SELECTION_OWNER": "UNCHANGED",
        "MV2_DP_AUTHORITY": "UNCHANGED",
        "PRETRADE_AUTHORITY": "UNCHANGED",
        "EXECUTION_AUTHORITY": EXECUTION_AUTHORITY,
        "PRIVATE_WS_ORDER_SEND_AUTHORIZED": PRIVATE_WS_ORDER_SEND_AUTHORIZED,
        "PRIVATE_WS_AMEND_AUTHORIZED": PRIVATE_WS_AMEND_AUTHORIZED,
        "PRIVATE_WS_CANCEL_AUTHORIZED": PRIVATE_WS_CANCEL_AUTHORIZED,
        "REST_POST_PERMIT_CHANGE": REST_POST_PERMIT_CHANGE,
        "WIRE_BOUNDARY_CHANGE": False,
        "EXTERNAL_EFFECT_CHANGE": False,
        "LIVE_ENABLED": LIVE_ENABLED is True,
        "LIVE_ARMED": LIVE_ARMED is True,
        "WIRE_SEND_PERMITTED": WIRE_SEND_PERMITTED is True,
        "SUBMISSION_AUTHORIZED": SUBMISSION_AUTHORIZED is True,
        "LIVE_AUTHORIZED": LIVE_AUTHORIZED is True,
        "PRODUCTIVE_WIRE_SEND_REACHABLE": PRODUCTIVE_WIRE_SEND_REACHABLE is True,
        "EXTERNAL_EFFECT_AUTHORIZED": EXTERNAL_EFFECT_AUTHORIZED,
        "REAL_EXTERNAL_EFFECT_AUTHORIZED": REAL_EXTERNAL_EFFECT_AUTHORIZED,
        "REAL_VENUE_POST_ALLOWED": REAL_VENUE_POST_ALLOWED,
        "POST_ALLOWED": POST_ALLOWED,
        "MULTI_FUTURE_RUNTIME_AUTHORIZED": MULTI_FUTURE_RUNTIME_AUTHORIZED,
        "MAX_POSITIONS_EFFECTIVE": MAX_POSITIONS_EFFECTIVE,
        "K2_ABSENT": K2_ABSENT,
        "RUNNING_ACCOUNT_EQUITY_MINT_ALLOWED": RUNNING_ACCOUNT_EQUITY_MINT_ALLOWED,
        "SELECTION_AUTHORITY": SELECTION_AUTHORITY,
        "STRATEGY_AUTHORITY": STRATEGY_AUTHORITY,
        "RANKING_AUTHORITY": RANKING_AUTHORITY,
        "private_runtime_may_post": False,
        "private_runtime_may_ws_order_send": False,
    }
