"""Fail-closed constants for the §11.14 exact-single live fill execution WP."""

from __future__ import annotations

CAPABILITY_ID = (
    "SECTION_11_14_LIVE_HANDOFF_EXACT_SINGLE_LIVE_FILL_REQUIRES_SEPARATE_OWNER_EXECUTION_GO_V1"
)
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = (
    "section_11_14_live_handoff_exact_single_live_fill_requires_separate_owner_execution_go.v1"
)
OWNER = (
    "ops.section_11_14_live_handoff_exact_single_live_fill_requires_separate_owner_execution_go_v1"
)
THIS_SLICE = "11.14.LIVE_HANDOFF_EXACT_SINGLE_LIVE_FILL_REQUIRES_SEPARATE_OWNER_EXECUTION_GO"
PREDECESSOR_SLICE = (
    "11.14.CURRENT_ORIGIN_MAIN_8605BF_GET_ONLY_TRADE_FEE_AND_STALE_PRETRADE_PREDICATE_REFRESH"
)
LAST_CANONICALLY_CLOSED_STEP = (
    "SECTION_11_14_LIVE_HANDOFF_EXACT_SINGLE_LIVE_FILL_REQUIRES_SEPARATE_OWNER_EXECUTION_GO"
)
OWNER_EXECUTION_GO = (
    "PEAK_TRADE_OWNER_EXECUTION_GO_SECTION_11_14_LIVE_HANDOFF_EXACT_SINGLE_LIVE_FILL_"
    "ORIGIN_MAIN_705A063D0FDDB60BC6D94693E029BB57669108DC_PRE_EXISTING_POSITION_POS_1_V1"
)
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GET_ONLY_GO_SECTION_11_14_CURRENT_ORIGIN_MAIN_8605BF_"
    "GET_ONLY_TRADE_FEE_AND_STALE_PRETRADE_PREDICATE_REFRESH_V1"
)
CANONICAL_EVIDENCE_RUN_ID = "20260907T211230Z"
EXPECTED_ORIGIN_MAIN_SHA = "705a063d0fddb60bc6d94693e029bb57669108dc"
EXPECTED_ORIGIN_MAIN_TREE = "1c83a69d9d6652fcc6691d33110985895b3aedb8"
TOKEN_EXPECTED_PRE_EXISTING_POSITION = "pos=1"

BOUND_INSTRUMENT_ID = "SUI-USD_UM_XPERP-310404"
BOUND_INST_FAMILY = "SUI-USD_UM_XPERP"
BOUND_VENUE = "eea.okx.com"
BOUND_POSITION_MODE = "net_mode"
BOUND_ACCOUNT_MODE = "2"
BOUND_MARGIN_MODE = "cross"
BOUND_LEVERAGE = "3"
PRODUCTIVE_RUNNER = "run_canary_submit_transport_v1"
PRODUCTIVE_SUBMIT_CALLER = "execute_exact_single_live_submit_post_v1"
EXECUTION_PORT = "LiveCanaryHttpClientV1.POST /api/v5/trade/order"
CANARY_TECHNICAL_EXECUTE_TOKEN = "OWNER_GO_LIVE_CANARY_MINIMUM_EXPOSURE"
HISTORICAL_SUBMIT_WRAPPER_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_EXACT_SINGLE_LIVE_SUBMIT_POST_V1"
)
HISTORICAL_SUBMIT_WRAPPER_SHA = "d6d3fa2970aafc9517cff9c0b8c1685dabd9791b"
MAX_SUBMITS_THIS_WP = 1
MAX_POSITIONS_EFFECTIVE = 1
POSITION_COUNT_LIMIT = 1

GET_PACK_RELATIVE_ROOT = (
    "evidence/ops/section_11_14_live_handoff_exact_single_live_fill_"
    "requires_separate_owner_execution_go_v1"
)
EVIDENCE_RELATIVE_ROOT = GET_PACK_RELATIVE_ROOT

EXACT_OKX_FEE_FORMULA_STATUS = "UNPROVEN"
OWNER_EXECUTION_AUTHORIZED_STANDING = False
SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED = False
LIVE_RESTART_RECONSTRUCTED = False
HOST_CRASH_DURABILITY = "UNPROVEN"
CASE_ADJUDICATION = (
    "CASE_OWNER_EXECUTION_GO_CONSUMED_NO_SUBMIT_OPEN_POSITION_PRESENT_"
    "CANARY_ENTRY_WOULD_INCREASE_EXISTING_POSITION"
)
OWNER_EXECUTION_GO_STATUS = "CONSUMED_NO_SUBMIT"
EXECUTION_DECISION = "NO_EXECUTION"
FINAL_ACTION = "HARD_STOP"
EARLIEST_UNRESOLVED_DEPENDENCY = "LIVE_RESTART_RECONSTRUCTED"
EARLIEST_UNRESOLVED_AUTHORITY_PREDICATE = (
    "NEW_OWNER_EXECUTION_GO_REQUIRED_THIS_TOKEN_CONSUMED_NO_SUBMIT"
)
NEXT_OWNER_GO_REQUIRED = "OWNER_MERGE_GO_THEN_SEPARATE_OWNER_EXECUTION_GO_NOT_THIS_TOKEN"
PROPOSED_NEXT_SLICE = (
    "SECTION_11_14_LIVE_HANDOFF_EXACT_SINGLE_LIVE_FILL_AFTER_POSITION_COMPATIBLE_STATE_"
    "REQUIRES_SEPARATE_OWNER_EXECUTION_GO_V1"
)

SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
ADJUDICATION_FILENAME = "EXECUTION_ADJUDICATION.json"
PREDICATE_TABLE_FILENAME = "PREDICATE_TABLE.json"
SAFETY_FILENAME = "SAFETY.json"
BASELINE_FILENAME = "BASELINE.json"
NON_EXECUTION_FILENAME = "NON_EXECUTION.json"
OWNER_GO_FILENAME = "OWNER_EXECUTION_GO.json"
PRODUCTIVE_PATH_FILENAME = "PRODUCTIVE_PATH.json"
STRATEGY_DECISION_FILENAME = "STRATEGY_DECISION.json"
POSITION_SAFETY_FILENAME = "POSITION_SAFETY.json"
FINAL_GATES_FILENAME = "FINAL_GATES.json"
LINEAGE_FILENAME = "LINEAGE.json"
CENSUS_FILENAME = "CENSUS.json"
GET_RESULTS_FILENAME = "GET_RESULTS.sanitized.json"
GET_ADJUDICATION_FILENAME = "ADJUDICATION.json"
MANIFEST_FILENAME = "MANIFEST.sha256"
