"""Standing constants for authenticated private runtime read and permit issuance."""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.bounded_activation_permit_v1 import (
    BOUNDED_ACTIVATION_OWNER_GO_CANONICAL,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    ENDPOINT_ACCOUNT_POSITIONS,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.position_observation_freshness_contract_v1 import (
    POSITION_OBSERVATION_FRESHNESS_MAX_AGE_MS,
)
from src.ops.section_11_13_5_authenticated_private_runtime_read_and_runtime_permit_issuance_v1.contract_v1 import (
    ABSENT_TARGET_ROW_IS_ZERO,
    AUTHENTICATED_PRIVATE_RUNTIME_READ_AUTHORIZED,
    CENSUS_TEXT_REWRITTEN,
    EMPTY_DATA_IS_ZERO,
    FAIL_CLOSED_IF_MARKED_FLATTEN_PROVEN_FROM_PERMIT_ALONE,
    FLATTEN_EXECUTE_AUTHORIZED,
    NETWORK_SESSION_AUTHORIZED,
    PRODUCTIVE_FLATTEN_POST_AUTHORIZED,
    PRODUCTIVE_RECONCILIATION_AUTHORIZED,
    RUNTIME_PERMIT_ISSUANCE_AUTHORIZED,
    THIS_GO_DOES_NOT_AUTHORIZE_FLATTEN,
    THIS_GO_DOES_NOT_AUTHORIZE_FLATTEN_NETWORK_SESSION,
    THIS_GO_DOES_NOT_AUTHORIZE_POST,
    THIS_GO_DOES_NOT_SET_LIVE_AUTHORIZED,
)

CAPABILITY_ID = "AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE_V1"
PACKAGE_MARKER = "AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE_V1=true"
OWNER = "ops.section_11_13_5_authenticated_private_runtime_read_and_runtime_permit_issuance_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "authenticated_private_runtime_read_and_runtime_permit_issuance.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE_V1"
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_REMAINING_EXECUTION_PATH_END_TO_END_CENSUS_MAXIMUM_SAFE_LEVERAGE_V1"
)
WORKPACKAGE_ID = "OKX_EEA_AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE_V1"
THIS_SLICE = "11.13.5.AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE"
PREDECESSOR_SLICE = "11.13.5.REMAINING_EXECUTION_PATH_END_TO_END_CENSUS"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = (
    "SECTION_11_13_5_AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE"
)
EXPECTED_ORIGIN_MAIN_SHA = "9bf1c3c23a90ec6878cbdf9e6da5fdbb2bfc80ed"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = (
    "EXACTLY_ONE_AUTHENTICATED_NON_MUTATING_UNFILTERED_PRIVATE_GET_ACCOUNT_POSITIONS"
    "_THEN_RUNTIME_PERMIT_ISSUANCE_IF_GATES_PASS"
)
AUTHORIZED_SCOPE = "D_THEN_F_AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE"
AUTHORIZED_ENDPOINT = "GET /api/v5/account/positions"
MAX_NETWORK_REQUEST_COUNT = 1
MAX_HTTP_EXCHANGE_COUNT = 1
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
SECOND_GET_ALLOWED = False
ALTERNATE_ENDPOINT_ALLOWED = False
INSTID_FILTER_ALLOWED = False
PUBLIC_GET_ALLOWED = False
PENDING_ORDERS_GET_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
FUNDING_ALLOWED = False
BALANCE_GET_ALLOWED = False
CONFIG_GET_ALLOWED = False
MAX_SIZE_GET_ALLOWED = False
LEVERAGE_GET_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
POSITION_CREATION_ALLOWED = False
POSITION_MODIFICATION_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False

ENDPOINT = ENDPOINT_ACCOUNT_POSITIONS
ENDPOINT_METHOD = "GET"
FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/config",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
    "/api/v5/trade/cancel-order",
    "/api/v5/trade/orders-pending",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
REUSED_CLASSIFIER = "classify_target_position_state_v1"
REUSED_QUERY_BUILDER = "build_account_positions_query_v1"
PERMIT_OWNER_GO_CANONICAL = BOUNDED_ACTIVATION_OWNER_GO_CANONICAL
FRESHNESS_POLICY_MAX_AGE_MS = POSITION_OBSERVATION_FRESHNESS_MAX_AGE_MS
FRESHNESS_POLICY = (
    f"FLATTEN_PRE_SEND_MAX_AGE_MS={POSITION_OBSERVATION_FRESHNESS_MAX_AGE_MS};"
    "PERMIT_NOT_AFTER_EQUALS_OBSERVATION_RECEIVED_PLUS_MAX_AGE;"
    "STALE_OR_MISSING_OBSERVATION_DENIES_ISSUANCE"
)
EMPTY_DATA_IS_ZERO_VALUE = EMPTY_DATA_IS_ZERO
ABSENT_TARGET_ROW_IS_ZERO_VALUE = ABSENT_TARGET_ROW_IS_ZERO

NAMED_REMAINING_HIGHER_AUTHORITY: tuple[str, ...] = ("PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION",)
EARLIEST_UNRESOLVED_DEPENDENCY = "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION"
NEXT_AUTHORITY_BOUNDARY = "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION"
NEXT_WORKPACKAGE = "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION"
NEXT_OWNER_GO_REQUIRED = "NOT_PERSISTED_IN_CURRENT_REPO_EVIDENCE"
MINIMUM_ADDITIONAL_OWNER_GO_COUNT = 1
WORKPACKAGE_COUNT = 1
CENSUS_RUNTIME_RESIDUAL = "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_REMAINS_SEPARATE_OWNER_GO"

AUTHENTICATED_PRIVATE_RUNTIME_READ_AUTHORIZED_VALUE = AUTHENTICATED_PRIVATE_RUNTIME_READ_AUTHORIZED
RUNTIME_PERMIT_ISSUANCE_AUTHORIZED_VALUE = RUNTIME_PERMIT_ISSUANCE_AUTHORIZED
PRODUCTIVE_FLATTEN_POST_AUTHORIZED_VALUE = PRODUCTIVE_FLATTEN_POST_AUTHORIZED
PRODUCTIVE_RECONCILIATION_AUTHORIZED_VALUE = PRODUCTIVE_RECONCILIATION_AUTHORIZED
FLATTEN_EXECUTE_AUTHORIZED_VALUE = FLATTEN_EXECUTE_AUTHORIZED
NETWORK_SESSION_AUTHORIZED_VALUE = NETWORK_SESSION_AUTHORIZED
CENSUS_TEXT_REWRITTEN_VALUE = CENSUS_TEXT_REWRITTEN
THIS_GO_DOES_NOT_AUTHORIZE_POST_VALUE = THIS_GO_DOES_NOT_AUTHORIZE_POST
THIS_GO_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = THIS_GO_DOES_NOT_AUTHORIZE_FLATTEN
THIS_GO_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = THIS_GO_DOES_NOT_SET_LIVE_AUTHORIZED
THIS_GO_DOES_NOT_AUTHORIZE_FLATTEN_NETWORK_SESSION_VALUE = (
    THIS_GO_DOES_NOT_AUTHORIZE_FLATTEN_NETWORK_SESSION
)
FAIL_CLOSED_IF_MARKED_FLATTEN_PROVEN_FROM_PERMIT_ALONE_VALUE = (
    FAIL_CLOSED_IF_MARKED_FLATTEN_PROVEN_FROM_PERMIT_ALONE
)

GET_ALLOWED = True
PRIVATE_GET_ALLOWED = True
POSITION_GET_ALLOWED = True
POSITION_GET_REQUIRED_THIS_PERSIST = True
POSITION_GET_AUTHORIZED_BY_THIS_OWNER_GO = True
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED_VALUE = LIVE_EXECUTION_ALLOWED
CANARY_EXECUTION_ALLOWED_VALUE = CANARY_EXECUTION_ALLOWED
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P25_CLOSED = True
STP_CLOSED = True
APT_CLOSED = True
STPR_CLOSED = True
CENSUS_CLOSED = True

RESULT_CLASS_200_OKX_0 = "HTTP_200_OKX_0"
RESULT_CLASS_401_50110 = "HTTP_401_OKX_50110"
RESULT_CLASS_OTHER = "OTHER_FAIL_CLOSED"
RESULT_CLASS_TRANSPORT = "TRANSPORT_OR_CLIENT_FAIL"

CASE_A_TARGET_NONZERO = "CASE_A_TARGET_NONZERO"
CASE_B_TARGET_ZERO = "CASE_B_TARGET_ZERO"
CASE_C_EMPTY_DATA_NOT_ZERO = "CASE_C_EMPTY_DATA_NOT_ZERO"
CASE_D_TARGET_NOT_OBSERVED = "CASE_D_TARGET_NOT_OBSERVED"
CASE_E_HTTP_OR_OKX_ERROR = "CASE_E_HTTP_OR_OKX_ERROR"
CASE_F_AMBIGUOUS = "CASE_F_AMBIGUOUS"

DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
EVIDENCE_DIRNAME = (
    "section_11_13_5_authenticated_private_runtime_read_and_runtime_permit_issuance_v1"
)
CANONICAL_EVIDENCE_RUN_ID = "20260904T052554Z"
PR_CHANGED_PATHS_FREEZE_DIRNAME = "pr_changed_paths_freeze_v1"
PR_CHANGED_PATHS_FREEZE_CONTRACT_VERSION = "pr_changed_paths_freeze.v1"
PR_CHANGED_PATHS_FREEZE_BASE_SHA = EXPECTED_ORIGIN_MAIN_SHA
PR_CHANGED_PATHS_FREEZE_HEAD_SHA = "13e88e3f64231aae73a6d5fa4b1edbb30f7e82ca"
PR_CHANGED_PATHS_FREEZE_COUNT = 31
PR_CHANGED_PATHS_FREEZE_SET_HASH = (
    "732643e2109a7f605e6a2945f9b7902d07e2d7f2cee545081a435d79fd1d615d"
)
PR_CHANGED_PATHS_FREEZE_GIT_SEMANTICS = "THREE_DOT_NAME_ONLY_LC_ALL_C_SORT"
PR_CHANGED_PATHS_FREEZE_GENERATOR_COMMAND = (
    "git diff --name-only "
    f"{PR_CHANGED_PATHS_FREEZE_BASE_SHA}...{PR_CHANGED_PATHS_FREEZE_HEAD_SHA}"
    " | LC_ALL=C sort"
)
PR_CHANGED_PATHS_TEMP_HISTORICAL = "/tmp/aprpi_changed_files_v2.txt"
