"""Failure / reason codes for Cap 4.1 pre-activation closure."""

from __future__ import annotations

from enum import Enum


class PreActivationFailureCodeV1(str, Enum):
    MISSING_RUNTIME_TRUTH = "MISSING_RUNTIME_TRUTH"
    STALE_RUNTIME_TRUTH = "STALE_RUNTIME_TRUTH"
    CONFIG_MISMATCH = "CONFIG_MISMATCH"
    UNSAFE_DEFAULT_FALLBACK = "UNSAFE_DEFAULT_FALLBACK"
    MISSING_RECONCILIATION_PROOF = "MISSING_RECONCILIATION_PROOF"
    UNRECONCILED_STATE = "UNRECONCILED_STATE"
    STALE_UNIVERSE = "STALE_UNIVERSE"
    STALE_RANKING = "STALE_RANKING"
    MISSING_SELECTION = "MISSING_SELECTION"
    STALE_INVALID_SELECTION = "STALE_INVALID_SELECTION"
    SELECTION_DIGEST_MISMATCH = "SELECTION_DIGEST_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    NATIVE_INSTRUMENT_MISMATCH = "NATIVE_INSTRUMENT_MISMATCH"
    MISSING_TYPED_VOLATILITY_PRESENCE = "MISSING_TYPED_VOLATILITY_PRESENCE"
    MISSING_CONTRACT_METADATA = "MISSING_CONTRACT_METADATA"
    MISSING_MARK_PRICE = "MISSING_MARK_PRICE"
    MISSING_PORTFOLIO_STATE = "MISSING_PORTFOLIO_STATE"
    ACCOUNTING_STATE_MISMATCH = "ACCOUNTING_STATE_MISMATCH"
    RISK_STATE_MISMATCH = "RISK_STATE_MISMATCH"
    DUPLICATE_WRITER = "DUPLICATE_WRITER"
    PARALLEL_LEGACY_AUTHORITY = "PARALLEL_LEGACY_AUTHORITY"
    DASHBOARD_DERIVED_AUTHORITY = "DASHBOARD_DERIVED_AUTHORITY"
    MULTI_FUTURE_ENABLED = "MULTI_FUTURE_ENABLED"
    MAX_POSITIONS_GREATER_THAN_ONE = "MAX_POSITIONS_GREATER_THAN_ONE"
    NUMERIC_MAX_AGE_ENFORCEMENT_ENABLED = "NUMERIC_MAX_AGE_ENFORCEMENT_ENABLED"
    LIVE_ORDER_PATH_REACHABLE = "LIVE_ORDER_PATH_REACHABLE"
    TESTNET_ORDER_PATH_REACHABLE = "TESTNET_ORDER_PATH_REACHABLE"
    VERIFIER_FAILURE = "VERIFIER_FAILURE"
    PARTIAL_RESTART_STATE = "PARTIAL_RESTART_STATE"
    AUTHORIZATION_CONSUMPTION_ATTEMPTED = "AUTHORIZATION_CONSUMPTION_ATTEMPTED"
    NETWORK_SESSION_STARTED = "NETWORK_SESSION_STARTED"
    RUNTIME_ACTIVATION_ATTEMPTED = "RUNTIME_ACTIVATION_ATTEMPTED"
    FORBIDDEN_STATUS = "FORBIDDEN_STATUS"
    CALL_GRAPH_INCOMPLETE = "CALL_GRAPH_INCOMPLETE"
    PREDECESSOR_CAPABILITY_MISSING = "PREDECESSOR_CAPABILITY_MISSING"
    GATE_FLAG_FALSE = "GATE_FLAG_FALSE"
    SESSION_LOCK_CONFLICT = "SESSION_LOCK_CONFLICT"
    ALPHA_BEFORE_RECONCILIATION = "ALPHA_BEFORE_RECONCILIATION"
    HARD_STOP = "HARD_STOP"


ALL_FAILURE_CODES = frozenset(code.value for code in PreActivationFailureCodeV1)
