"""Fail-closed reason codes for explicit D_t proposal validation."""

from __future__ import annotations

from enum import Enum


class ExplicitDtProposalFailureCodeV1(str, Enum):
    VALUE_MISSING = "VALUE_MISSING"
    VALUE_NOT_FINITE = "VALUE_NOT_FINITE"
    VALUE_NOT_POSITIVE = "VALUE_NOT_POSITIVE"
    VALUE_TYPE_INVALID = "VALUE_TYPE_INVALID"
    PRODUCER_ID_MISSING = "PRODUCER_ID_MISSING"
    PROPOSAL_ID_MISSING = "PROPOSAL_ID_MISSING"
    OBSERVATION_LINEAGE_ID_MISSING = "OBSERVATION_LINEAGE_ID_MISSING"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    PARAMETER_PROVENANCE_MISSING = "PARAMETER_PROVENANCE_MISSING"
    PARAMETER_PROVENANCE_EMPTY = "PARAMETER_PROVENANCE_EMPTY"
    INSTRUMENT_ID_MISSING = "INSTRUMENT_ID_MISSING"
    VENUE_MISSING = "VENUE_MISSING"
    VENUE_INSTRUMENT_ID_MISSING = "VENUE_INSTRUMENT_ID_MISSING"
    IDENTITY_FIELD_NORMALIZATION_FORBIDDEN = "IDENTITY_FIELD_NORMALIZATION_FORBIDDEN"
    INSTRUMENT_ID_MISMATCH = "INSTRUMENT_ID_MISMATCH"
    VENUE_MISMATCH = "VENUE_MISMATCH"
    VENUE_INSTRUMENT_ID_MISMATCH = "VENUE_INSTRUMENT_ID_MISMATCH"
    CONTEXT_INSTRUMENT_ID_MISSING = "CONTEXT_INSTRUMENT_ID_MISSING"
    CONTEXT_VENUE_MISSING = "CONTEXT_VENUE_MISSING"
    CONTEXT_VENUE_INSTRUMENT_ID_MISSING = "CONTEXT_VENUE_INSTRUMENT_ID_MISSING"
