"""Failure / reason codes for Cap 5.2 public-MD no-order shadow evidence."""

from __future__ import annotations

from enum import Enum


class PublicMdShadowFailureCodeV1(str, Enum):
    MISSING_RUNTIME_TRUTH = "MISSING_RUNTIME_TRUTH"
    STALE_RUNTIME_TRUTH = "STALE_RUNTIME_TRUTH"
    CONFIG_MISMATCH = "CONFIG_MISMATCH"
    CAPTURE_INVALID = "CAPTURE_INVALID"
    CAPTURE_DIGEST_MISMATCH = "CAPTURE_DIGEST_MISMATCH"
    MISSING_SELECTION = "MISSING_SELECTION"
    STALE_SELECTION = "STALE_SELECTION"
    SELECTION_DIGEST_MISMATCH = "SELECTION_DIGEST_MISMATCH"
    MISSING_MARK_PRICE = "MISSING_MARK_PRICE"
    MISSING_TYPED_VOLATILITY = "MISSING_TYPED_VOLATILITY"
    STALE_MARKET_DATA = "STALE_MARKET_DATA"
    DUPLICATE_OBSERVATION = "DUPLICATE_OBSERVATION"
    MISSING_OBSERVATION = "MISSING_OBSERVATION"
    INVALID_CONTRACT_METADATA = "INVALID_CONTRACT_METADATA"
    CORRUPTED_PORTFOLIO_CHECKPOINT = "CORRUPTED_PORTFOLIO_CHECKPOINT"
    CORRUPTED_RISK_CHECKPOINT = "CORRUPTED_RISK_CHECKPOINT"
    ACCOUNTING_PERSISTENCE_FAILURE = "ACCOUNTING_PERSISTENCE_FAILURE"
    VERIFIER_MISMATCH = "VERIFIER_MISMATCH"
    NON_DETERMINISTIC_SHADOW = "NON_DETERMINISTIC_SHADOW"
    RESTART_MISMATCH = "RESTART_MISMATCH"
    CALL_GRAPH_INCOMPLETE = "CALL_GRAPH_INCOMPLETE"
    PREDECESSOR_CAPABILITY_MISSING = "PREDECESSOR_CAPABILITY_MISSING"
    GATE_FLAG_FALSE = "GATE_FLAG_FALSE"
    AUTHORIZATION_INVALID = "AUTHORIZATION_INVALID"
    AUTHORIZATION_ALREADY_CONSUMED = "AUTHORIZATION_ALREADY_CONSUMED"
    AUTHORIZATION_CONSUMPTION_REQUIRED = "AUTHORIZATION_CONSUMPTION_REQUIRED"
    AUTHORIZATION_NOT_CONSUMED = "AUTHORIZATION_NOT_CONSUMED"
    PRIVATE_API_ATTEMPTED = "PRIVATE_API_ATTEMPTED"
    ORDER_PATH_ATTEMPTED = "ORDER_PATH_ATTEMPTED"
    NETWORK_SCOPE_VIOLATION = "NETWORK_SCOPE_VIOLATION"
    RUNTIME_ACTIVATION_ATTEMPTED = "RUNTIME_ACTIVATION_ATTEMPTED"
    FORBIDDEN_STATUS = "FORBIDDEN_STATUS"
    LIVE_ORDER_PATH_REACHABLE = "LIVE_ORDER_PATH_REACHABLE"
    TESTNET_ORDER_PATH_REACHABLE = "TESTNET_ORDER_PATH_REACHABLE"
    PAPER_ORDER_PATH_REACHABLE = "PAPER_ORDER_PATH_REACHABLE"
    MULTI_FUTURE_ENABLED = "MULTI_FUTURE_ENABLED"
    NUMERIC_MAX_AGE_ENFORCEMENT_ENABLED = "NUMERIC_MAX_AGE_ENFORCEMENT_ENABLED"
    PARALLEL_LEGACY_AUTHORITY = "PARALLEL_LEGACY_AUTHORITY"
    SESSION_LOCK_CONFLICT = "SESSION_LOCK_CONFLICT"
    CORE_LOGIC_CHANGED = "CORE_LOGIC_CHANGED"
    TRANSPORT_FAILURE = "TRANSPORT_FAILURE"
    HARD_STOP = "HARD_STOP"


ALL_FAILURE_CODES = frozenset(code.value for code in PublicMdShadowFailureCodeV1)
