"""CAPABILITY_O7 constants — governed end-to-end offline evidence."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_O7_GOVERNED_END_TO_END_RUNTIME_AND_DASHBOARD_EVIDENCE_V1"
SCHEMA_VERSION = "o7_governed_end_to_end_runtime_and_dashboard_evidence_v1"
PACKAGE_MARKER = "GOVERNED_END_TO_END_RUNTIME_AND_DASHBOARD_EVIDENCE_V1=true"
EVIDENCE_DIRNAME = "capability_o7_governed_end_to_end_runtime_and_dashboard_evidence_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"

# Reuse O1–O6 canonical owners — never invent parallel authorities.
O1_ENVIRONMENT_PACKAGE = "canonical_runtime_environment_contract_v1"
O2_LAUNCHER_PACKAGE = "canonical_local_launcher_and_process_supervision_v1"
O3_TOKEN_PACKAGE = "secure_confirm_token_family_and_hidden_input_handoff_v1"
O4_TRANSPORT_PACKAGE = "canonical_public_md_and_ohlcv_transport_reconciliation_v1"
O5_READ_MODEL_PACKAGE = "canonical_read_model_and_market_dashboard_rebuild_v1"
O6_HEALTH_PACKAGE = "runtime_health_recovery_and_failure_injection_closure_v1"

PRODUCTION_SURFACES_REUSED = (
    O1_ENVIRONMENT_PACKAGE,
    O2_LAUNCHER_PACKAGE,
    O3_TOKEN_PACKAGE,
    O4_TRANSPORT_PACKAGE,
    O5_READ_MODEL_PACKAGE,
    O6_HEALTH_PACKAGE,
)

LADDER_PROVEN_ITEMS = (
    "LAUNCHER_SMOKE",
    "STATUS_AND_COMPOSITE_HEALTH_CONTINUITY",
    "STOP_RESTART_RECOVER_LIFECYCLE",
    "PROCESS_CRASH_DETECTION_AND_BOUNDED_RECOVERY",
    "DASHBOARD_RESTART_WITHOUT_RUNTIME_SCAFFOLD_RESTART",
    "RUNTIME_SCAFFOLD_RESTART_WITH_DERIVED_READ_MODEL_RECOVERY",
    "DUPLICATE_SESSION_PREVENTION_AND_SEQUENTIAL_MULTI_SESSION_CONTINUITY",
    "STALE_DISCONNECTED_MISSING_SOURCE_VISIBILITY",
    "GRACEFUL_SHUTDOWN_AND_PROCESS_CLEANUP",
    "REPOSITORY_CONFIG_ORDER_CREDENTIAL_BOUNDARY_PRESERVATION",
)

LADDER_DEFERRED_ITEMS = (
    "LONG_RUNNING_PUBLIC_MD_SESSION",
    "LIVE_OHLCV_MATRIX_CONTINUITY",
    "END_TO_END_NETWORK_LATENCY",
)

# Productive wiring landed offline; network-bound proof remains deferred.
PRODUCTIVE_WIRING_IMPLEMENTED = {
    "O2_SUPERVISED_FASTAPI_HTTP_HOST": True,
    "PSO_TO_O4_LIVE_BRIDGE": True,
    "O4_TO_O5_DURABLE_READ_MODEL": True,
    "JOINED_TIMESTAMP_PROVENANCE": True,
    "DASHBOARD_RESTART_WITHOUT_PSO_RESTART": True,
    "NETWORK_BOUND_PROOF_STILL_REQUIRED": True,
}

DEFERRED_CLASSIFICATIONS = {
    "LONG_RUNNING_PUBLIC_MD_SESSION": "DEFERRED",
    "LIVE_OHLCV_MATRIX_CONTINUITY": "DEFERRED",
    "END_TO_END_NETWORK_LATENCY": "DEFERRED",
    "DASHBOARD_HTTP_POLL_CONTINUITY": "WIRING_READY_NETWORK_PROOF_DEFERRED",
    "NETWORK_FAILURE_RECOVERY_EVIDENCE": "WIRING_READY_NETWORK_PROOF_DEFERRED",
    "SEPARATE_NETWORK_SESSION_OWNER_GO_REQUIRED": True,
}

REQUIRED_TRUTH_CLASSIFICATIONS = {
    "O7_BOUNDED_OFFLINE_EVIDENCE_COMPLETE": True,
    "O7_NETWORK_BOUND_EVIDENCE_COMPLETE": False,
    "O7_NETWORK_BOUND_EVIDENCE_DEFERRED": True,
    "O7_FULL_CAPABILITY_CLOSED": False,
    "O7_READY_FOR_LOCAL_COMMIT_VERIFICATION_PUSH_AND_NON_DRAFT_PR": True,
    "DASHBOARD_TRADING_AUTHORITY": False,
    "READ_MODEL_CLASSIFICATION": "DERIVED",
    "READ_MODEL_SSOT": False,
    "READ_MODEL_AUTHORITY_EFFECT": "NONE",
    "MASTER_RUNBOOK_IS_ONLY_SSOT": True,
    "SECOND_SSOT_CREATED": False,
}

SAFETY_INVARIANTS = {
    "CORE_LOGIC_CHANGE_ALLOWED": False,
    "CONFIG_CHANGE_ALLOWED": False,
    "NETWORK_SESSION_ALLOWED": False,
    "AUTHORIZATION_CONSUMPTION_ALLOWED": False,
    "CONFIRM_TOKEN_MINT_ALLOWED": False,
    "ORDERS_ALLOWED": False,
    "LIVE_TRADING_ALLOWED": False,
    "TESTNET_ALLOWED": False,
    "PAPER_EXCHANGE_ORDERS_ALLOWED": False,
    "EXCHANGE_CREDENTIAL_USE_ALLOWED": False,
    "REAL_CAPITAL_MOVEMENT_ALLOWED": False,
    "NOTION_MUTATION_ALLOWED": False,
    "RULESET_MUTATION_ALLOWED": False,
    "DASHBOARD_TRADING_AUTHORITY": False,
    "PARALLEL_LAUNCHER_FORBIDDEN": True,
    "PARALLEL_SUPERVISOR_FORBIDDEN": True,
    "PARALLEL_OHLCV_PRODUCER_FORBIDDEN": True,
    "PARALLEL_READ_MODEL_AUTHORITY_FORBIDDEN": True,
    "PARALLEL_HEALTH_MODEL_FORBIDDEN": True,
    "PARALLEL_RECOVERY_MODEL_FORBIDDEN": True,
    "PHASE_9_2_SUBSTITUTION_FORBIDDEN": True,
    "O8_DEAUTHORIZATION_FORBIDDEN": True,
}
