"""P5.9D layered mechanical SideState FSM contract (definition only; no bind)."""

from __future__ import annotations

PACKAGE_MARKER = "P5_9D_LAYERED_MECHANICAL_SIDESTATE_FSM_CONTRACT_V1=true"
OWNER = "ops.p5_9d_layered_mechanical_sidestate_fsm_contract_v1"
CONTRACT_VERSION = "layered_mechanical_sidestate_fsm.v1"

LAYERED_MECHANICAL_FSM_CONTRACT_V1_DEFINED = True

from src.ops.p5_2_productive_cycle_seam_invoke_and_authority_bind_v1.constants_v1 import (  # noqa: E402
    AUTHORITY_CUTOVER_OCCURRED,
    EXTERNAL_EFFECT_AUTHORIZED,
    FINAL_D_T_FORMULA_SELECTED,
    P5_AUTHORITY_CUTOVER_AUTHORIZED,
    PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED,
    REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED,
)

assert LAYERED_MECHANICAL_FSM_CONTRACT_V1_DEFINED is True
assert REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED is False
assert PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED is True
assert FINAL_D_T_FORMULA_SELECTED is False
assert P5_AUTHORITY_CUTOVER_AUTHORIZED is False
assert AUTHORITY_CUTOVER_OCCURRED is False
assert EXTERNAL_EFFECT_AUTHORIZED is False

__all__ = [
    "AUTHORITY_CUTOVER_OCCURRED",
    "CONTRACT_VERSION",
    "EXTERNAL_EFFECT_AUTHORIZED",
    "FINAL_D_T_FORMULA_SELECTED",
    "LAYERED_MECHANICAL_FSM_CONTRACT_V1_DEFINED",
    "OWNER",
    "P5_AUTHORITY_CUTOVER_AUTHORIZED",
    "PACKAGE_MARKER",
    "PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED",
    "REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED",
]
