"""Authority / activation inventory matrix for Cap 7.2."""

from __future__ import annotations

from typing import Any

from src.ops.single_future_stateful_no_order_runtime_activation_v1.constants_v1 import (
    LEGACY_ACTIVATION_FLAG_OWNERS,
    OWNER,
    PRODUCTIVE_HOST,
    PRODUCTIVE_HOST_ENTRY,
    RUNTIME_MODE,
    RUNTIME_MODE_OWNER,
    SIMULATED_EXECUTION_PORT_OWNER,
)


def inventory_activation_authority_v1() -> dict[str, Any]:
    matrix = [
        {
            "SYMBOL_OR_CONFIG": "FULL_CANONICAL_STATEFUL_RUNTIME_ACTIVE",
            "CURRENT_OWNER": OWNER,
            "PRODUCTIVE_CONSUMER": PRODUCTIVE_HOST_ENTRY,
            "CURRENT_EFFECT": "INACTIVE_UNTIL_CAP72_GATE",
            "TARGET_EFFECT": "ACTIVE_NO_ORDER_STATEFUL_RUNTIME",
            "PERSISTED": True,
            "RESTART_LOADED": True,
            "FAILURE_BEHAVIOR": "FAIL_CLOSED_ALPHA_BLOCKED",
            "CAP_7_2_CHANGE_REQUIRED": True,
            "CORE_LOGIC_EFFECT": False,
        },
        {
            "SYMBOL_OR_CONFIG": "SIMULATED_EXECUTION_ACTIVE",
            "CURRENT_OWNER": OWNER,
            "PRODUCTIVE_CONSUMER": SIMULATED_EXECUTION_PORT_OWNER,
            "CURRENT_EFFECT": "INACTIVE_UNTIL_CAP72_GATE",
            "TARGET_EFFECT": "SIMULATED_EXECUTION_PORT_ACTIVE",
            "PERSISTED": True,
            "RESTART_LOADED": True,
            "FAILURE_BEHAVIOR": "FAIL_CLOSED",
            "CAP_7_2_CHANGE_REQUIRED": True,
            "CORE_LOGIC_EFFECT": False,
        },
        {
            "SYMBOL_OR_CONFIG": "STATEFUL_RUNTIME_READY_FOR_ACTIVATION",
            "CURRENT_OWNER": OWNER,
            "PRODUCTIVE_CONSUMER": PRODUCTIVE_HOST_ENTRY,
            "CURRENT_EFFECT": "READY_AFTER_PRECONDITIONS",
            "TARGET_EFFECT": "READY_TRUE",
            "PERSISTED": True,
            "RESTART_LOADED": True,
            "FAILURE_BEHAVIOR": "FAIL_CLOSED",
            "CAP_7_2_CHANGE_REQUIRED": True,
            "CORE_LOGIC_EFFECT": False,
        },
        {
            "SYMBOL_OR_CONFIG": "runtime_mode",
            "CURRENT_OWNER": RUNTIME_MODE_OWNER,
            "PRODUCTIVE_CONSUMER": PRODUCTIVE_HOST_ENTRY,
            "CURRENT_EFFECT": RUNTIME_MODE,
            "TARGET_EFFECT": RUNTIME_MODE,
            "PERSISTED": True,
            "RESTART_LOADED": True,
            "FAILURE_BEHAVIOR": "RUNTIME_MODE_MISMATCH_FAIL_CLOSED",
            "CAP_7_2_CHANGE_REQUIRED": True,
            "CORE_LOGIC_EFFECT": False,
        },
        {
            "SYMBOL_OR_CONFIG": "SimulatedExecutionPortV1",
            "CURRENT_OWNER": SIMULATED_EXECUTION_PORT_OWNER,
            "PRODUCTIVE_CONSUMER": PRODUCTIVE_HOST,
            "CURRENT_EFFECT": "ONLY_SIMULATED_PORT_CONSTRUCTIBLE",
            "TARGET_EFFECT": "ONLY_SIMULATED_PORT_CONSTRUCTIBLE",
            "PERSISTED": False,
            "RESTART_LOADED": True,
            "FAILURE_BEHAVIOR": "INVALID_EXECUTION_PORT",
            "CAP_7_2_CHANGE_REQUIRED": True,
            "CORE_LOGIC_EFFECT": False,
        },
        {
            "SYMBOL_OR_CONFIG": "LIVE_ORDERS/TESTNET_ORDERS/PAPER_EXCHANGE_ORDERS",
            "CURRENT_OWNER": "bridge.constants_v1 + cap72.config",
            "PRODUCTIVE_CONSUMER": PRODUCTIVE_HOST_ENTRY,
            "CURRENT_EFFECT": "false",
            "TARGET_EFFECT": "false",
            "PERSISTED": True,
            "RESTART_LOADED": True,
            "FAILURE_BEHAVIOR": "NO_ORDER_MODE_VIOLATION",
            "CAP_7_2_CHANGE_REQUIRED": False,
            "CORE_LOGIC_EFFECT": False,
        },
        {
            "SYMBOL_OR_CONFIG": "RUNTIME_BRIDGE_LIVE_ACTIVATED",
            "CURRENT_OWNER": "ops.wallclock_...constants_v1",
            "PRODUCTIVE_CONSUMER": PRODUCTIVE_HOST,
            "CURRENT_EFFECT": "false",
            "TARGET_EFFECT": "false",
            "PERSISTED": False,
            "RESTART_LOADED": False,
            "FAILURE_BEHAVIOR": "INVARIANT_VIOLATION",
            "CAP_7_2_CHANGE_REQUIRED": False,
            "CORE_LOGIC_EFFECT": False,
        },
        {
            "SYMBOL_OR_CONFIG": "legacy Cap4.1/5.x RUNTIME_ACTIVATED flags",
            "CURRENT_OWNER": "legacy package constants (non-authoritative)",
            "PRODUCTIVE_CONSUMER": "none_for_cap72",
            "CURRENT_EFFECT": "false_documentation_only",
            "TARGET_EFFECT": "false_not_reactivated",
            "PERSISTED": False,
            "RESTART_LOADED": False,
            "FAILURE_BEHAVIOR": "PARALLEL_ACTIVATION_PATH_REJECTED",
            "CAP_7_2_CHANGE_REQUIRED": False,
            "CORE_LOGIC_EFFECT": False,
        },
    ]
    return {
        "ok": True,
        "ONE_CANONICAL_ACTIVATION_AUTHORITY": True,
        "ONE_CANONICAL_RUNTIME_MODE": True,
        "ONE_PRODUCTIVE_STATEFUL_HOST": True,
        "NO_PARALLEL_ACTIVATION_PATH": True,
        "NO_LEGACY_HOST_BYPASS": True,
        "canonical_activation_authority": OWNER,
        "canonical_runtime_mode_source": RUNTIME_MODE_OWNER,
        "productive_stateful_host": PRODUCTIVE_HOST,
        "simulated_execution_port_owner": SIMULATED_EXECUTION_PORT_OWNER,
        "legacy_activation_flag_owners": list(LEGACY_ACTIVATION_FLAG_OWNERS),
        "matrix": matrix,
    }
