"""Fail-closed reason codes for Cap 7.2 activation."""

from __future__ import annotations

from enum import Enum


class ActivationFailureCodeV1(str, Enum):
    PRECONDITION_GAP = "PRECONDITION_GAP"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    CORRUPT_CHECKPOINT = "CORRUPT_CHECKPOINT"
    WRITER_CONFLICT = "WRITER_CONFLICT"
    RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
    MISSING_SELECTED_FUTURE = "MISSING_SELECTED_FUTURE"
    INVALID_INSTRUMENT_BINDING = "INVALID_INSTRUMENT_BINDING"
    INVALID_EXECUTION_PORT = "INVALID_EXECUTION_PORT"
    INVALID_ENDPOINT = "INVALID_ENDPOINT"
    INVALID_HTTP_METHOD = "INVALID_HTTP_METHOD"
    AUTH_HEADER_REJECTED = "AUTH_HEADER_REJECTED"
    CREDENTIAL_LOADER_REACHABLE = "CREDENTIAL_LOADER_REACHABLE"
    REAL_EXECUTION_REACHABLE = "REAL_EXECUTION_REACHABLE"
    EVIDENCE_VERIFIER_FAILURE = "EVIDENCE_VERIFIER_FAILURE"
    ACTIVATION_COMMIT_CRASH = "ACTIVATION_COMMIT_CRASH"
    NO_ORDER_MODE_VIOLATION = "NO_ORDER_MODE_VIOLATION"
    RUNTIME_MODE_MISMATCH = "RUNTIME_MODE_MISMATCH"
    PARALLEL_ACTIVATION_PATH = "PARALLEL_ACTIVATION_PATH"
    LEGACY_HOST_BYPASS = "LEGACY_HOST_BYPASS"
    ACTIVATION_NOT_READY = "ACTIVATION_NOT_READY"
    MISSING_ACTIVATION_STATE = "MISSING_ACTIVATION_STATE"
    SILENT_DEFAULT_ACTIVATION = "SILENT_DEFAULT_ACTIVATION"
    ENV_OVERRIDE_REJECTED = "ENV_OVERRIDE_REJECTED"
