"""Constants for CAPABILITY_11_4 testnet execution adapter and lifecycle closure."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_11_4_TESTNET_EXECUTION_ADAPTER_AND_LIFECYCLE_CLOSURE_V1"
PACKAGE_MARKER = "CAPABILITY_11_4_TESTNET_EXECUTION_ADAPTER_AND_LIFECYCLE_CLOSURE_V1=true"
OWNER = "ops.capability_11_4_testnet_execution_adapter_and_lifecycle_closure_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "capability_11_4_testnet_execution_adapter_and_lifecycle_closure.v1"
PRODUCER_VERSION = "capability_11_4_testnet_execution_adapter_and_lifecycle_closure.v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID_11_1 = "CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1"
PREDECESSOR_OWNER_11_1 = "ops.capability_11_1_execution_domain_and_order_lifecycle_contracts_v1"
PREDECESSOR_CAPABILITY_ID_11_2 = (
    "CAPABILITY_11_2_CREDENTIAL_AUTHORIZATION_AND_ACCOUNT_IDENTITY_BOUNDARY_V1"
)
PREDECESSOR_OWNER_11_2 = (
    "ops.capability_11_2_credential_authorization_and_account_identity_boundary_v1"
)
PREDECESSOR_CAPABILITY_ID_11_3 = (
    "CAPABILITY_11_3_PRIVATE_READONLY_VENUE_INTEGRATION_AND_RECONCILIATION_V1"
)
PREDECESSOR_OWNER_11_3 = (
    "ops.capability_11_3_private_readonly_venue_integration_and_reconciliation_v1"
)

# Hard safety bindings (contracts/scaffolding only; non-authorizing).
CORE_LOGIC_CHANGE = False
CORE_LOGIC_CHANGE_ALLOWED = False
ACTIVATION_STATE = "not_activated"
ACTIVATION_CHANGED = False
RUNTIME_ACTIVATED = False
LIVE_TRADING_ALLOWED = False
TESTNET_ALLOWED = False
PAPER_EXCHANGE_ORDERS_ALLOWED = False
EXCHANGE_CREDENTIAL_USE_ALLOWED = False
REAL_CAPITAL_MOVEMENT_ALLOWED = False
NETWORK_SESSION_ALLOWED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
RULESET_MUTATION_ALLOWED = False
NOTION_MUTATION_ALLOWED = False

TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False
EXCHANGE_CREDENTIAL_USE_AUTHORIZED = False
REAL_CAPITAL_MOVEMENT_AUTHORIZED = False
OWNER_GO_REQUIRED_FOR_EACH_ACTIVATION = True

LIVE_PATH_CHANGED = False
TESTNET_PATH_CHANGED = False
ORDER_PATH_CHANGED = False
EXCHANGE_CREDENTIAL_PATH_CHANGED = False
NETWORK_SESSION_STARTED = False

VOLATILITY_NUMERIC_MAX_AGE_ENFORCING = False
NUMERIC_MAX_AGE_EFFECT = "DIAGNOSTIC_ONLY"

# Cap 11.1 contracts that must not be weakened.
CAPABILITY_11_1_FAIL_CLOSED_RETAINED = True
CAPABILITY_11_1_IDEMPOTENCY_RETAINED = True
CAPABILITY_11_1_UNKNOWN_SEMANTICS_RETAINED = True
CAPABILITY_11_1_LIFECYCLE_RETAINED = True
CAPABILITY_11_1_AUDIT_CONTRACTS_RETAINED = True
CAPABILITY_11_1_ANTI_CORRUPTION_RETAINED = True
CAPABILITY_11_1_JOURNALING_RETAINED = True

# Cap 11.2 contracts that must not be weakened.
CAPABILITY_11_2_CREDENTIAL_BOUNDARY_RETAINED = True
CAPABILITY_11_2_AUTHORIZATION_BOUNDARY_RETAINED = True
CAPABILITY_11_2_ACCOUNT_IDENTITY_BOUNDARY_RETAINED = True
CAPABILITY_11_2_NO_CREDENTIAL_LOAD_RETAINED = True
CAPABILITY_11_2_NO_AUTH_CONSUMPTION_RETAINED = True

# Cap 11.3 contracts that must not be weakened / activated.
CAPABILITY_11_3_PRIVATE_READONLY_BOUNDARY_RETAINED = True
CAPABILITY_11_3_RECONCILIATION_HIERARCHY_RETAINED = True
CAPABILITY_11_3_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_3_NO_NETWORK_FETCH_RETAINED = True
CAPABILITY_11_3_NO_CREDENTIAL_LOAD_RETAINED = True

# Reachability claims for Cap 11.4 (contracts only — no real Testnet execution).
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
EXCHANGE_CREDENTIAL_ACCESS_REACHABLE = False
REAL_CAPITAL_MOVEMENT_REACHABLE = False
PRIVATE_READONLY_NETWORK_REACHABLE = False
PRIVATE_READONLY_VENUE_INTEGRATION_ACTIVATED = False
CREDENTIAL_PLAINTEXT_LOADED = False
CREDENTIAL_LOAD_PERFORMED_IN_CAPABILITY_11_4 = False
TESTNET_EXECUTION_ADAPTER_ACTIVATED = False
TESTNET_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_4 = False
TESTNET_NETWORK_SESSION_STARTED_IN_CAPABILITY_11_4 = False
ORDER_SERIALIZATION_NETWORK_EFFECT = "NONE"

# Cap 11.4 contract surface claims.
TESTNET_EXECUTION_ADAPTER_DECLARED = True
ORDER_SERIALIZATION_DRY_RUN_CONTRACT_BOUND = True
TESTNET_LIFECYCLE_CLOSURE_CONTRACT_BOUND = True
TESTNET_LIFECYCLE_FIXTURE_ONLY = True
TESTNET_ENTRY_PARTIAL_FILL_CANCEL_EXIT_PATHS_BOUND = True
VENUE_ADAPTER_DECISION_AUTHORITY = False
VENUE_NATIVE_EVENT_NORMALIZED = True
ROUNDING_AND_PRECISION_EXPLICIT = True
MIN_SIZE_AND_NOTIONAL_VALIDATED = True
ORDER_TYPE_SUPPORT_EXPLICIT = True
RATE_LIMIT_BUDGET_EXPLICIT = True
ERROR_TAXONOMY_EXPLICIT = True
NATIVE_ORDER_SERIALIZATION_EXPLICIT = True

# Cap 11.4 does NOT claim real Testnet proving-ground closure (§11.12 closure flags).
TESTNET_ORDER_LIFECYCLE_PROVEN = False
TESTNET_RECONCILIATION_PROVEN = False
TESTNET_RESTART_PROVEN = False
TESTNET_UNKNOWN_SUBMIT_RECOVERY_PROVEN = False
TESTNET_DUPLICATE_ORDER_PREVENTION_PROVEN = False
TESTNET_KILL_SWITCH_PROVEN = False
TESTNET_AUTONOMOUS_RECOVERY_PROVEN = False
TESTNET_EVIDENCE_VERIFIED = False

# Explicit Cap 11.5+ surfaces remain out of scope / unbound.
CAPABILITY_11_5_RESTART_RECOVERY_KILL_SWITCH_STARTED = False
UNKNOWN_SUBMIT_RECONNECT_RECOVERY_CONTRACT_ACTIVATED = False
KILL_SWITCH_CONTRACT_ACTIVATED = False

VENUE_ADAPTER_ALLOWED_RESPONSIBILITIES: tuple[str, ...] = (
    "authentication_transport",
    "venue_native_instrument_translation",
    "request_signing",
    "endpoint_and_rate_limit_handling",
    "native_order_serialization",
    "venue_event_normalization",
    "exchange_clock_synchronization",
    "idempotent_lookup_by_canonical_identifiers",
)

VENUE_ADAPTER_FORBIDDEN_AUTHORITIES: tuple[str, ...] = (
    "decision",
    "alpha",
    "master_v2",
    "double_play",
    "portfolio_strategy",
    "risk_limit_policy",
    "safety_policy",
    "accounting_authority",
    "autonomous_limit_changes",
    "kill_switch_authority",
    "restart_recovery_authority",
)

TESTNET_LIFECYCLE_PATHS: tuple[str, ...] = (
    "single_controlled_order_lifecycle",
    "entry_lifecycle",
    "partial_fill_lifecycle",
    "cancel_lifecycle",
    "exit_lifecycle",
)

ORDER_SERIALIZATION_REQUIRED_FIELDS: tuple[str, ...] = (
    "client_order_id",
    "instrument_id",
    "side",
    "order_type",
    "quantity",
    "execution_mode",
)

TESTNET_EXECUTION_ADAPTER_OWNER = OWNER
ORDER_SERIALIZATION_DRY_RUN_OWNER = OWNER
TESTNET_LIFECYCLE_CLOSURE_OWNER = OWNER
VENUE_ADAPTER_ANTI_CORRUPTION_OWNER = OWNER

EVIDENCE_DIRNAME = "capability_11_4_testnet_execution_adapter_and_lifecycle_closure_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
