"""Dedicated §11.13.5 flatten-execute authority (confirm token + purpose).

Invocation-scoped only. Standing live flags remain false. This module does
not authorize GET, POST, or flatten execution. Missing/wrong/stale/wrong-purpose
tokens deny. Implementation Owner-GOs are forbidden as execute tokens.
"""

from __future__ import annotations

from typing import Any

FLATTEN_EXECUTE_PURPOSE_CANONICAL = "SECTION_11_13_5_FLATTEN_EXECUTE"
FLATTEN_EXECUTE_CONFIRM_TOKEN_CANONICAL = "I_AUTHORIZE_SECTION_11_13_5_FLATTEN_EXECUTE"
FLATTEN_EXECUTE_OWNER_GO_CANONICAL = "SECTION_11_13_5_FLATTEN_EXECUTE_OWNER_GO"
FLATTEN_EXECUTE_AUTHORITY_KIND = "FLATTEN_EXECUTE_CONFIRM"

# Mechanism expected-value only. Presence in source is not execute authorization.
# Default supplied token remains empty/absent → deny.
FORBIDDEN_FLATTEN_EXECUTE_OWNER_GOS: frozenset[str] = frozenset(
    {
        "SECTION_11_13_5_POST_Z2AU_PRODUCTIVE_LIVE_FLATTEN_WIRING_MAX_SAFE_SLICE_FAIL_CLOSED_NO_NETWORK_NO_GET_NO_POST_NO_EXECUTE",
        "SECTION_11_13_5_Z2AP_PRODUCTIVE_LIVE_FLATTEN_PROVABILITY_NEXT_MAX_SAFE_SLICE_FAIL_CLOSED_NO_IMPLICIT_EXECUTE",
        "SECTION_11_13_5_PRODUCTIVE_LIVE_FLATTEN_PROOF_PRE_EXECUTION_GATE_AND_RUNTIME_READINESS_ONLY",
        "SECTION_11_13_5_Z2AP_PRODUCTIVE_LIVE_FLATTEN_PROVABILITY_NEXT_MAX_SAFE_SLICE_FAIL_CLOSED_NO_IMPLICIT_EXECUTE",
        "OWNER_GO_SECTION_11_13_LIVE_CANARY_PRODUCTIVE_SURFACE_AUTHORING",
        "OWNER_GO_LIVE_CANARY_MINIMUM_EXPOSURE",
        "PEAK_TRADE_11_13_5_Z2CM_FAIL_CLOSED_POSITION_STATE_PREDICATE_AND_FLATTEN_EXECUTE_POST_ACTION_WIRING_V1",
        "PEAK_TRADE_CANONICAL_STATE_RECONSTITUTION_AND_HIGHEST_LEVERAGE_BLOCKER_EXECUTION_V1",
        "PEAK_TRADE_POST_Z2CM_FRESH_UNFILTERED_TARGET_POSITION_RUNTIME_OBSERVATION_AND_PERSIST_V1",
        "PEAK_TRADE_POST_Z2CM_MAXIMUM_LEVERAGE_CANONICAL_PROGRESSION_V1",
        "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_Z2AP_FLATTEN_NON_POSITION_CONTRACT_RESIDUALS_DOCS_ONLY_V1",
        "PEAK_TRADE_OWNER_DECISION_POSITION_OBSERVATION_FRESHNESS_POLICY_V1",
        "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_POSITION_OBSERVATION_FRESHNESS_PERSIST_IMPLEMENT_PR_V1",
        "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_POST_Z2CP_MAXIMUM_SAFE_LEVERAGE_CLUSTER_V1",
        "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_PREREQUISITE_08_FRESH_POSITION_OBSERVATION_CLUSTER_V1",
        "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_PREREQUISITE_08_RESOLUTION_AUTHORITY_ADJUDICATION_V1",
        "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_PREREQUISITE_08_SINGLE_UNFILTERED_POSITION_OBSERVATION_V1",
        "PEAK_TRADE_OWNER_GO_POST_Z2CT_NAMED_PROGRESSION_TRACK_ADJUDICATION_V1",
        "PEAK_TRADE_OWNER_GO_Z2AR_COVER_USDC_REPROOF_OFFLINE_V1",
        "PEAK_TRADE_OWNER_GO_Z2AR_FX_REPROOF_OFFLINE_V1",
        "PEAK_TRADE_OWNER_GO_Z2AR_REMAINING_UNRANKED_OFFLINE_REPROOF_BUNDLE_V1",
        "PEAK_TRADE_OWNER_GO_POST_Z2CX_P3_DEPENDENCY_RECONCILIATION_AND_NEXT_BLOCKER_V1",
        "PEAK_TRADE_OWNER_GO_PREREQUISITE_08_SINGLE_UNFILTERED_POSITIONS_GET_V1",
        "PEAK_TRADE_OWNER_GO_POST_Z2CZ_POSITION_CREATION_AUTONOMY_SEMANTIC_REBIND_PERSIST_V1",
        "PEAK_TRADE_OWNER_GO_PREREQUISITE_08_POSITION_SOURCE_POLICY_PERSIST_IMPLEMENT_PR_V1",
        "PEAK_TRADE_OWNER_GO_ROUTE_C_OFFLINE_GATED_PRODUCTIVE_SUBMIT_COMPOSITION_V1",
        "PEAK_TRADE_OWNER_GO_POST_Z2DO_FRESH_CREATE_READINESS_EVIDENCE_V1",
        "PEAK_TRADE_OWNER_GO_ROUTE_C_NET_MODE_POSSIDE_FIRST_PARTY_CONTRACT_EVIDENCE_V1",
        "PEAK_TRADE_OWNER_GO_POST_Z2DQ_MAXIMUM_SAFE_LEVERAGE_V1",
        "PEAK_TRADE_OWNER_GO_POST_Z2DR_RUNTIME_READ_ONLY_EVIDENCE_MAX_LEVERAGE_V1",
        "PEAK_TRADE_OWNER_GO_OKX_EEA_PRIVATE_GET_CURRENT_50110_EGRESS_CAPTURE_V1",
        "PEAK_TRADE_OWNER_GO_OKX_EEA_EXTERNAL_IP_WHITELIST_MINIMUM_ADD_CURRENT_50110_EGRESS_V1",
        "PEAK_TRADE_OWNER_GO_OKX_EEA_EXTERNAL_IP_WHITELIST_ADD_FROM_CAPTURED_50110_EVIDENCE_20260903T171133Z_V1",
        "PEAK_TRADE_OWNER_GO_POST_WHITELIST_PRIVATE_AUTH_ATTESTATION_SINGLE_GET_V1",
        "PEAK_TRADE_OWNER_GO_P08_POSITION_OBSERVATION_V1",
        "PEAK_TRADE_OWNER_GO_P08_EMPTY_DATA_NOT_ZERO_MAXIMUM_SAFE_LEVERAGE_V1",
        "PEAK_TRADE_OWNER_GO_P08_DISTINCT_FIRST_PARTY_EVIDENCE_MAXIMUM_SAFE_LEVERAGE_V2",
        "PEAK_TRADE_OWNER_GO_P08_READ_ONLY_CLOSURE_MAXIMUM_SAFE_LEVERAGE_V3",
        "PEAK_TRADE_OWNER_GO_P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY_MAXIMUM_SAFE_LEVERAGE_V1",
        "PEAK_TRADE_OWNER_GO_P08_NONZERO_POSITION_ADJUDICATE_PERSIST_CLOSE_AND_PR_MAX_LEVERAGE_V1",
        "PEAK_TRADE_OWNER_GO_EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT_FORENSIC_ADJUDICATE_OFFLINE_PERSIST_PR_V1",
        "PEAK_TRADE_OWNER_GO_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF_NO_ALIAS_PROMOTION_V1",
    }
)


class LiveCanaryFlattenExecuteAuthorityError(RuntimeError):
    """Fail-closed flatten-execute authority violation."""


def evaluate_flatten_execute_authority_v1(
    *,
    token: str | None,
    purpose: str | None,
    owner_go: str | None,
) -> tuple[bool, tuple[str, ...]]:
    """Return (accepted, deny_reasons). Never treats this implementation GO as execute."""
    reasons: list[str] = []
    supplied = str(token or "")
    if not supplied.strip():
        reasons.append("FLATTEN_EXECUTE_TOKEN_MISSING")
    elif supplied != FLATTEN_EXECUTE_CONFIRM_TOKEN_CANONICAL:
        reasons.append("FLATTEN_EXECUTE_TOKEN_MISMATCH")

    purpose_norm = str(purpose or "").strip()
    if not purpose_norm:
        reasons.append("FLATTEN_EXECUTE_PURPOSE_MISSING")
    elif purpose_norm != FLATTEN_EXECUTE_PURPOSE_CANONICAL:
        reasons.append("FLATTEN_EXECUTE_PURPOSE_INVALID")

    go = str(owner_go or "").strip()
    if not go:
        reasons.append("FLATTEN_EXECUTE_OWNER_GO_MISSING")
    elif go in FORBIDDEN_FLATTEN_EXECUTE_OWNER_GOS:
        reasons.append("FLATTEN_EXECUTE_OWNER_GO_FORBIDDEN")
    elif "NO_EXECUTE" in go.upper() or "NO_IMPLICIT_EXECUTE" in go.upper():
        reasons.append("FLATTEN_EXECUTE_OWNER_GO_FORBIDDEN")
    elif "AUTHORING" in go.upper() or "WIRING" in go.upper() or "READINESS" in go.upper():
        reasons.append("FLATTEN_EXECUTE_OWNER_GO_FORBIDDEN")
    elif go != FLATTEN_EXECUTE_OWNER_GO_CANONICAL:
        reasons.append("FLATTEN_EXECUTE_OWNER_GO_MISMATCH")

    return (not reasons, tuple(reasons))


def flatten_execute_authority_audit_v1(
    *,
    token: str | None,
    purpose: str | None,
    owner_go: str | None,
) -> dict[str, Any]:
    accepted, reasons = evaluate_flatten_execute_authority_v1(
        token=token,
        purpose=purpose,
        owner_go=owner_go,
    )
    return {
        "kind": FLATTEN_EXECUTE_AUTHORITY_KIND,
        "accepted": accepted,
        "reasons": list(reasons),
        "purpose_canonical": FLATTEN_EXECUTE_PURPOSE_CANONICAL,
        "token_supplied": bool(str(token or "").strip()),
        "implementation_go_is_not_execute_token": True,
    }
