"""Offline post-Z2CX P3 / §11.13.5 / Z2AR dependency reconciliation.

Census-driven. Distinguishes remaining-unranked exhaustion from
NOT_REPROVEN classes, and flatten-path earliest 08 from non-critical
offline remainder. Never GETs, never POSTs, never authorizes flatten,
live, testnet, or canary, never consumes Class D or Z2AP, never reopens
FX, never adjudicates COVER_USDC, and never invents a unique next.
"""

from __future__ import annotations

from typing import Any, Mapping

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.execution_prerequisite_08_cluster_contract_v1 import (
    EARLIEST_UNRESOLVED_DEPENDENCY as CLUSTER_EARLIEST_UNRESOLVED_DEPENDENCY,
    Z2CN_COMMITTED_BODY_SHA256,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.prerequisite_08_resolution_authority_adjudication_v1 import (
    AUTHORIZED_RESOLUTION_PATH,
    CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION,
    CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH,
    FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH,
    MINIMUM_FUTURE_RUNTIME_AUTHORITY,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.z2ar_cover_usdc_offline_reproof_v1 import (
    COVER_USDC_STATUS as BOUND_COVER_USDC_UNINSTANTIATED,
    CURRENT_COVER_USDC_STATUS,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.z2ar_fx_offline_reproof_v1 import (
    CURRENT_FX_STATUS,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.z2ar_remaining_unranked_offline_reproof_bundle_v1 import (
    COVER_USDC_ADJUDICATED as Z2CX_COVER_USDC_ADJUDICATED,
    FX_REOPENED as Z2CX_FX_REOPENED,
    REMAINING_UNRANKED_AFTER_THIS_BUNDLE,
)

OWNER_GO = "PEAK_TRADE_OWNER_GO_POST_Z2CX_P3_DEPENDENCY_RECONCILIATION_AND_NEXT_BLOCKER_V1"
THIS_SLICE = "11.13.5.Z2CY"
PREDECESSOR_SLICE = "11.13.5.Z2CX"
LAST_CANONICALLY_CLOSED_11_13_5_SLICE = "SECTION_11_13_5_Z2CT"
THIS_PERSIST_DOES_NOT_SUPERSEDE_Z2CT_AS_LAST_CANONICALLY_CLOSED_11_13_5_SLICE = True
THIS_NAMED_CLASS_PERSIST_ID = "SECTION_11_13_5_Z2CY"
BASELINE_ORIGIN_MAIN_SHA = "00910a2f67f94ad3ebc84b48d441648cc04b1ea1"
LAST_MERGED_PR = "6198"

ADJUDICATION = "CRITICAL_PATH_BLOCKER_IDENTIFIED_NO_UNIQUE_CANONICAL_NEXT"
UNIQUE_CANONICAL_NEXT_TRACK = "NONE"
P3_INDEPENDENT_PARALLEL_TRACKS_POLICY = True
GLOBAL_UNIQUE_CANONICAL_NEXT_STEP = "NONE_BY_P3_POLICY"
P3_INTENTIONALLY_LEAVES_SUCCESSOR_SELECTION_TO_OWNER = True
IDENTICAL_UNFILTERED_GET_IS_UNIQUE_CANONICAL_NEXT = False
IDENTICAL_UNFILTERED_GET_IS_PERMITTED_OBSERVATION_PATH_ONLY = True
AUTOMATIC_PREREQUISITE_08_REOBSERVATION_AUTHORIZED = False
RUNTIME_REOBSERVATION_IS_ONLY_VALID_NEXT_TRACK = False

EARLIEST_UNRESOLVED_DEPENDENCY = CLUSTER_EARLIEST_UNRESOLVED_DEPENDENCY
NEXT_ACTIONABLE_BLOCKER = "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
BLOCKER_CLASS = "NEW_FIRST_PARTY_GET_REQUIRED"
OFFLINE_RESOLUTION_POSSIBLE = False
OFFLINE_REMAINING_UNRANKED_Z2AR_SURFACE = "EXHAUSTED"
REMAINING_UNRANKED_AFTER_Z2CX = "NONE"
REMAINING_UNADJUDICATED_Z2AR_UNRANKED_CLASSES: tuple[str, ...] = ()
Z2AR_SUI_TRACK_STATUS = "OPEN_UNCONSUMED"
SUI_REPROOF_CLASSES_RANKED = False
NO_RANKING_OF_REMAINDER = True

FX_STATUS = CURRENT_FX_STATUS
FX_REOPENED = False
COVER_USDC_ADJUDICATED = False
COVER_USDC_STATUS = BOUND_COVER_USDC_UNINSTANTIATED
ROUNDING_STATUS = "NOT_REPROVEN_MISSING_EVIDENCE"
FINISHED_RISK_ENVELOPE_NUMERIC_STATUS = "NOT_REPROVEN_MISSING_EVIDENCE"
USD_USDC_ACCOUNT_SETTLEMENT_STATUS = "NOT_REPROVEN_MISSING_EVIDENCE"

CLASS_A_CONSUMED = True
CLASS_B_CANONICALLY_COMPLETED = False
CLASS_C_CONSUMED = True
CLASS_D_CONSUMED = False
Z2AP_CONSUMED = False
EXECUTION_READY = False
LIVE_FLATTEN_PROVABILITY = "UNPROVEN"
PREREQUISITE_08_STATUS = "UNRESOLVED_TARGET_NOT_OBSERVED_THIS_WINDOW"
TARGET_POSITION_NONZERO_PROVEN = False
TARGET_POSITION_STATE = "NOT_OBSERVED"
EMPTY_DATA_IS_ZERO = False
CURRENT_CANONICAL_INSTRUMENT = "SUI-USD_UM_XPERP-310404"
THIS_GO_AUTHORIZES_GET = False
THIS_GO_AUTHORIZES_POST = False
THIS_GO_AUTHORIZES_FLATTEN = False
RUNTIME_AUTHORIZATION_EFFECT = "NONE"

WHY_THIS_IS_NEXT = (
    "Z2CU remaining-unranked offline surface is exhausted "
    "(REMAINING_UNRANKED_AFTER_THIS_BUNDLE=NONE). Five named classes are "
    "fail-closed NOT_REPROVEN, not unadjudicated. Flatten-path numbered "
    "earliest unresolved remains EXECUTION_PREREQUISITE_08. Z2CS already "
    "proved 08 cannot be satisfied without a further unfiltered positions "
    "GET. Three empty windows (Z2CN/Z2CR/Z2CT) do not close 08. Non-critical "
    "offline remainder exists and is not selected as substitute work."
)
NEXT_AUTHORITY_BOUNDARY = MINIMUM_FUTURE_RUNTIME_AUTHORITY
NON_CRITICAL_OFFLINE_REMAINDER_NOT_SELECTED = True

NOT_REPROVEN_Z2AR_CLASSES: tuple[str, ...] = (
    "COVER_USDC",
    "FX",
    "ROUNDING",
    "FINISHED_RISK_ENVELOPE_NUMERIC",
    "USD_USDC_ACCOUNT_SETTLEMENT",
)

REPROVEN_THIS_CLASS_ONLY: tuple[str, ...] = (
    "SUI_OPERATIVE_QTY",
    "MMR_TIER_MAPPING",
    "MARKPX_NUMERIC_USE",
    "MARKPX_NUMERIC_OPERAND",
    "SLIPPAGE_RESERVE_NUMERIC_THIS_TERM",
    "MM_LIQ_BUFFER_NUMERIC_THIS_TERM",
)

POLICY_OR_INTERNAL_BOUND_NOT_EXCHANGE_TRUTH: tuple[str, ...] = (
    "INSTRUMENT_CONTRACT_METADATA_Z2BD",
    "POSITION_VALUE_ALGEBRA_PV1_INTERNAL",
    "PV1_CTVAL_OPERAND",
    "PV1_INTERNAL_NUMERIC_INSTANCE",
    "RESERVE_COVER_COMPOSITION_MEMBERSHIP_FORM",
    "FEE_AND_DELIVERY_INTERNAL_POLICY_AND_Z2BV_NUMERICS",
    "COMPOSITION_NUMERIC_SUM_INTERNAL",
    "RISK_ENVELOPE_IDENTITY_PLUS_COVER_NEGATIVE",
    "SUI_IDENTITY_REBIND_Z2BY",
)

CRITICAL_PATH_OPEN_DEPENDENCIES: tuple[str, ...] = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN",
    "EXECUTION_PREREQUISITE_09_TARGET_POSITION_QTY_NUMERIC",
    "EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT",
    "EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE",
    "EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION",
    "EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED",
    "EXECUTION_PREREQUISITE_20_MUTATION_LIMITED_TO_PROVEN_POSITION",
    "EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED",
    "SEND_TIME_PASS_18_19_21_24",
    "AUTHENTICATED_PRODUCTIVE_TRANSPORT",
)
OPEN_DEPENDENCY_COUNT = len(CRITICAL_PATH_OPEN_DEPENDENCIES)

NON_CRITICAL_ELIGIBLE_OFFLINE_TRACKS: tuple[str, ...] = (
    "P3_POST_ACTION_READBACK_FRESHNESS_POLICY",
    "P3_AUTHENTICATED_PRODUCTIVE_TRANSPORT",
    "P3_PREREQUISITE_10_UNIT_IDENTITY_OWNER_POLICY_FORM",
)

TRACK_DISPOSITIONS: tuple[Mapping[str, Any], ...] = (
    {
        "TRACK_ID": "P3_Z2AR_REMAINING_UNRANKED_SUI_REPROOF",
        "DISPOSITION": "EXHAUSTED_OFFLINE_REPROOF_SURFACE",
        "CRITICAL_PATH": False,
        "REQUIRES_RUNTIME": False,
        "EVIDENCE": "Z2CX REMAINING_UNRANKED_AFTER_THIS_BUNDLE=NONE",
    },
    {
        "TRACK_ID": "P3_PREREQUISITE_08_UNFILTERED_POSITION_REOBSERVATION",
        "DISPOSITION": "ELIGIBLE_NEXT_REQUIRES_SEPARATE_GET_GO",
        "CRITICAL_PATH": True,
        "REQUIRES_RUNTIME": True,
        "EVIDENCE": "Z2CS AUTHORIZED_RESOLUTION_PATH; CURRENT_UNCONSUMED_RUNTIME_GO=NONE",
    },
    {
        "TRACK_ID": "P3_POST_ACTION_READBACK_FRESHNESS_POLICY",
        "DISPOSITION": "ELIGIBLE_OFFLINE_NOT_CRITICAL_PATH",
        "CRITICAL_PATH": False,
        "REQUIRES_RUNTIME": False,
        "EVIDENCE": "Z2CP SEPARATE_LATER_IF_REQUIRED; LATER_THAN_08_ON_FLATTEN_PATH",
    },
    {
        "TRACK_ID": "P3_AUTHENTICATED_PRODUCTIVE_TRANSPORT",
        "DISPOSITION": "ELIGIBLE_OFFLINE_NOT_CRITICAL_PATH",
        "CRITICAL_PATH": False,
        "REQUIRES_RUNTIME": False,
        "EVIDENCE": "Z2CQ HMAC_HANDLE_REORDERED_BEFORE_08=false",
    },
    {
        "TRACK_ID": "P3_PREREQUISITE_10_UNIT_IDENTITY_OWNER_POLICY_FORM",
        "DISPOSITION": "ELIGIBLE_OFFLINE_NOT_CRITICAL_PATH",
        "CRITICAL_PATH": False,
        "REQUIRES_RUNTIME": False,
        "EVIDENCE": "Z2CQ UNIT_IDENTITY_UNPROVEN; MUST_NOT_CLAIM_OBSERVATION_PROVEN",
    },
    {
        "TRACK_ID": "P3_CLASS_D_PRODUCTIVE_FLATTEN_MUTATION",
        "DISPOSITION": "BLOCKED",
        "CRITICAL_PATH": True,
        "REQUIRES_RUNTIME": True,
        "EVIDENCE": "CLASS_D_CONSUMED=false; blocked by 08 nonzero",
    },
    {
        "TRACK_ID": "P3_Z2AP_PRODUCTIVE_LIVE_FLATTEN_PROOF",
        "DISPOSITION": "BLOCKED",
        "CRITICAL_PATH": True,
        "REQUIRES_RUNTIME": True,
        "EVIDENCE": "Z2AP_CONSUMED=false; blocked by 08 nonzero",
    },
)


class LiveCanaryPostZ2cxP3DependencyReconciliationError(RuntimeError):
    """Fail-closed post-Z2CX P3 dependency reconciliation violation."""


def _fail(code: str) -> None:
    raise LiveCanaryPostZ2cxP3DependencyReconciliationError(code)


def reject_unique_canonical_next_invention_v1(*, claimed_unique: str | None) -> str:
    claimed = str(claimed_unique or "").strip()
    if not claimed or claimed in {"NONE", UNIQUE_CANONICAL_NEXT_TRACK}:
        return "UNIQUE_CANONICAL_NEXT_TRACK_NONE_BY_P3_POLICY"
    _fail(f"UNIQUE_CANONICAL_NEXT_INVENTED:{claimed}")
    raise AssertionError("unreachable")


def reject_offline_substitute_for_08_v1(*, claimed_offline_resolves_08: bool) -> str:
    if claimed_offline_resolves_08:
        _fail("FORBIDDEN_OFFLINE_SUBSTITUTE_FOR_PREREQUISITE_08")
    return "OFFLINE_RESOLUTION_OF_08_IMPOSSIBLE"


def reject_busywork_remainder_v1(*, selected_non_critical_offline: bool) -> str:
    if selected_non_critical_offline:
        _fail("FORBIDDEN_NON_CRITICAL_OFFLINE_REMAINDER_AS_BUSYWORK")
    return "NON_CRITICAL_OFFLINE_REMAINDER_NOT_SELECTED"


def reject_remaining_unranked_still_open_v1(*, claimed_remaining_unranked: str | None) -> str:
    claimed = str(claimed_remaining_unranked or "NONE").strip()
    if claimed not in {"", "NONE"}:
        _fail(f"FORBIDDEN_REMAINING_UNRANKED_STILL_CLAIMED:{claimed}")
    if REMAINING_UNRANKED_AFTER_THIS_BUNDLE != ():
        _fail("DRIFT_Z2CX_REMAINING_UNRANKED_NOT_NONE")
    return "REMAINING_UNRANKED_AFTER_Z2CX_NONE"


def reject_fx_reopen_or_cover_readjudication_v1(
    *,
    reopen_fx: bool,
    adjudicate_cover_usdc: bool,
) -> str:
    if reopen_fx:
        _fail("FORBIDDEN_FX_REOPEN")
    if adjudicate_cover_usdc:
        _fail("FORBIDDEN_COVER_USDC_ADJUDICATION")
    if CURRENT_FX_STATUS != "NOT_REPROVEN_MISSING_EVIDENCE":
        _fail("DRIFT_FX_STATUS")
    if CURRENT_COVER_USDC_STATUS != "NOT_REPROVEN_MISSING_EVIDENCE":
        _fail("DRIFT_COVER_USDC_STATUS")
    if Z2CX_FX_REOPENED is not False:
        _fail("DRIFT_Z2CX_FX_REOPENED")
    if Z2CX_COVER_USDC_ADJUDICATED is not False:
        _fail("DRIFT_Z2CX_COVER_USDC_ADJUDICATED")
    return "FX_AND_COVER_USDC_NEGATIVES_PRESERVED"


def adjudicate_post_z2cx_p3_dependency_reconciliation_v1(
    *,
    claimed_unique_next: str | None = None,
    claimed_offline_resolves_08: bool = False,
    selected_non_critical_offline: bool = False,
    claimed_remaining_unranked: str | None = "NONE",
    reopen_fx: bool = False,
    adjudicate_cover_usdc: bool = False,
) -> dict[str, Any]:
    """Return the bound post-Z2CX census. Not GET and not flatten."""
    unique_token = reject_unique_canonical_next_invention_v1(claimed_unique=claimed_unique_next)
    offline_token = reject_offline_substitute_for_08_v1(
        claimed_offline_resolves_08=claimed_offline_resolves_08
    )
    busywork_token = reject_busywork_remainder_v1(
        selected_non_critical_offline=selected_non_critical_offline
    )
    remainder_token = reject_remaining_unranked_still_open_v1(
        claimed_remaining_unranked=claimed_remaining_unranked
    )
    negative_token = reject_fx_reopen_or_cover_readjudication_v1(
        reopen_fx=reopen_fx,
        adjudicate_cover_usdc=adjudicate_cover_usdc,
    )
    if CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION:
        _fail("DRIFT_08_OFFLINE_SATISFIABLE")
    if CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH != "NONE":
        _fail("DRIFT_UNCONSUMED_RUNTIME_GO")
    if EARLIEST_UNRESOLVED_DEPENDENCY != NEXT_ACTIONABLE_BLOCKER:
        _fail("DRIFT_EARLIEST_NE_NEXT_ACTIONABLE")
    return {
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "LAST_CANONICALLY_CLOSED_11_13_5_SLICE": LAST_CANONICALLY_CLOSED_11_13_5_SLICE,
        "ADJUDICATION": ADJUDICATION,
        "UNIQUE_CANONICAL_NEXT_TRACK": UNIQUE_CANONICAL_NEXT_TRACK,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_ACTIONABLE_BLOCKER": NEXT_ACTIONABLE_BLOCKER,
        "BLOCKER_CLASS": BLOCKER_CLASS,
        "WHY_THIS_IS_NEXT": WHY_THIS_IS_NEXT,
        "OFFLINE_RESOLUTION_POSSIBLE": OFFLINE_RESOLUTION_POSSIBLE,
        "OFFLINE_REMAINING_UNRANKED_Z2AR_SURFACE": OFFLINE_REMAINING_UNRANKED_Z2AR_SURFACE,
        "REMAINING_UNRANKED_AFTER_Z2CX": REMAINING_UNRANKED_AFTER_Z2CX,
        "REMAINING_UNADJUDICATED_Z2AR_UNRANKED_CLASSES": (
            REMAINING_UNADJUDICATED_Z2AR_UNRANKED_CLASSES
        ),
        "NOT_REPROVEN_Z2AR_CLASSES": NOT_REPROVEN_Z2AR_CLASSES,
        "REPROVEN_THIS_CLASS_ONLY": REPROVEN_THIS_CLASS_ONLY,
        "POLICY_OR_INTERNAL_BOUND_NOT_EXCHANGE_TRUTH": (
            POLICY_OR_INTERNAL_BOUND_NOT_EXCHANGE_TRUTH
        ),
        "CRITICAL_PATH_OPEN_DEPENDENCIES": CRITICAL_PATH_OPEN_DEPENDENCIES,
        "OPEN_DEPENDENCY_COUNT": OPEN_DEPENDENCY_COUNT,
        "NON_CRITICAL_ELIGIBLE_OFFLINE_TRACKS": NON_CRITICAL_ELIGIBLE_OFFLINE_TRACKS,
        "NON_CRITICAL_OFFLINE_REMAINDER_NOT_SELECTED": (
            NON_CRITICAL_OFFLINE_REMAINDER_NOT_SELECTED
        ),
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "AUTHORIZED_RESOLUTION_PATH": AUTHORIZED_RESOLUTION_PATH,
        "CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION": (
            CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION
        ),
        "CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH": (
            CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH
        ),
        "FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH": (
            FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH
        ),
        "FX_STATUS": FX_STATUS,
        "FX_REOPENED": FX_REOPENED,
        "COVER_USDC_ADJUDICATED": COVER_USDC_ADJUDICATED,
        "COVER_USDC_STATUS": COVER_USDC_STATUS,
        "CURRENT_COVER_USDC_STATUS": CURRENT_COVER_USDC_STATUS,
        "ROUNDING_STATUS": ROUNDING_STATUS,
        "FINISHED_RISK_ENVELOPE_NUMERIC_STATUS": FINISHED_RISK_ENVELOPE_NUMERIC_STATUS,
        "USD_USDC_ACCOUNT_SETTLEMENT_STATUS": USD_USDC_ACCOUNT_SETTLEMENT_STATUS,
        "CLASS_A_CONSUMED": CLASS_A_CONSUMED,
        "CLASS_B_CANONICALLY_COMPLETED": CLASS_B_CANONICALLY_COMPLETED,
        "CLASS_C_CONSUMED": CLASS_C_CONSUMED,
        "CLASS_D_CONSUMED": CLASS_D_CONSUMED,
        "Z2AP_CONSUMED": Z2AP_CONSUMED,
        "Z2AR_SUI_TRACK_STATUS": Z2AR_SUI_TRACK_STATUS,
        "EXECUTION_READY": EXECUTION_READY,
        "LIVE_FLATTEN_PROVABILITY": LIVE_FLATTEN_PROVABILITY,
        "PREREQUISITE_08_STATUS": PREREQUISITE_08_STATUS,
        "TARGET_POSITION_STATE": TARGET_POSITION_STATE,
        "EMPTY_DATA_IS_ZERO": EMPTY_DATA_IS_ZERO,
        "Z2CT_WINDOW_BODY_SHA256": Z2CN_COMMITTED_BODY_SHA256,
        "CURRENT_CANONICAL_INSTRUMENT": CURRENT_CANONICAL_INSTRUMENT,
        "THIS_GO_AUTHORIZES_GET": THIS_GO_AUTHORIZES_GET,
        "THIS_GO_AUTHORIZES_POST": THIS_GO_AUTHORIZES_POST,
        "THIS_GO_AUTHORIZES_FLATTEN": THIS_GO_AUTHORIZES_FLATTEN,
        "RUNTIME_AUTHORIZATION_EFFECT": RUNTIME_AUTHORIZATION_EFFECT,
        "UNIQUE_NEXT_DENY_TOKEN": unique_token,
        "OFFLINE_08_DENY_TOKEN": offline_token,
        "BUSYWORK_DENY_TOKEN": busywork_token,
        "REMAINDER_DENY_TOKEN": remainder_token,
        "NEGATIVE_PRESERVE_TOKEN": negative_token,
        "census": tuple(dict(row) for row in TRACK_DISPOSITIONS),
    }
