"""Offline post-Z2CT named progression-track adjudication.

Encodes the forensic census of named tracks that could follow §11.13.5.Z2CT
and the P3-governed finding that no unique canonical successor is mandated.
Evaluates caller-supplied facts only. Never GETs, never POSTs, never
authorizes flatten, live, testnet, or canary, never consumes Class D or
Z2AP, never ranks remaining Z2AR SUI reproof classes, and never treats
another unfiltered positions GET as the unique next action.
"""

from __future__ import annotations

from typing import Any, Mapping

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.execution_prerequisite_08_cluster_contract_v1 import (
    EARLIEST_UNRESOLVED_DEPENDENCY as CLUSTER_EARLIEST_UNRESOLVED_DEPENDENCY,
    Z2CN_COMMITTED_BODY_SHA256,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.prerequisite_08_resolution_authority_adjudication_v1 import (
    AUTHORIZED_RESOLUTION_PATH,
    CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION,
    CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH as Z2CS_CURRENT_UNCONSUMED_RUNTIME_GO,
    FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH,
    MINIMUM_FUTURE_RUNTIME_AUTHORITY,
)

OWNER_GO = "PEAK_TRADE_OWNER_GO_POST_Z2CT_NAMED_PROGRESSION_TRACK_ADJUDICATION_V1"
THIS_SLICE = "11.13.5.Z2CU"
PREDECESSOR_SLICE = "11.13.5.Z2CT"
LAST_CANONICALLY_CLOSED_11_13_5_SLICE = "SECTION_11_13_5_Z2CT"
THIS_PERSIST_DOES_NOT_SUPERSEDE_Z2CT_AS_LAST_CANONICALLY_CLOSED_11_13_5_SLICE = True
THIS_NAMED_CLASS_PERSIST_ID = "SECTION_11_13_5_Z2CU"

ADJUDICATION = "MULTIPLE_OWNER_SELECTABLE_TRACKS"
UNIQUE_CANONICAL_NEXT_TRACK = "NONE"
P3_INDEPENDENT_PARALLEL_TRACKS_POLICY = True
GLOBAL_UNIQUE_CANONICAL_NEXT_STEP = "NONE_BY_P3_POLICY"
P3_INTENTIONALLY_LEAVES_SUCCESSOR_SELECTION_TO_OWNER = True
OFFLINE_PROGRESSION_AVAILABLE = True
RUNTIME_REOBSERVATION_IS_ONLY_VALID_NEXT_TRACK = False
IDENTICAL_UNFILTERED_GET_IS_UNIQUE_CANONICAL_NEXT = False
IDENTICAL_UNFILTERED_GET_IS_PERMITTED_OBSERVATION_PATH_ONLY = True
AUTOMATIC_PREREQUISITE_08_REOBSERVATION_AUTHORIZED = False

Z2CT_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_PREREQUISITE_08_SINGLE_UNFILTERED_POSITION_OBSERVATION_V1"
)
Z2CT_OWNER_GO_STATUS = "CONSUMED"
Z2CS_OWNER_GO_STATUS = "CONSUMED"
Z2CR_OWNER_GO_STATUS = "CONSUMED"
Z2CN_OWNER_GO_STATUS = "CONSUMED"
CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH = "NONE"
Z2CT_WINDOW_TARGET_POSITION_STATE = "NOT_OBSERVED"
Z2CT_WINDOW_BODY_SHA256 = Z2CN_COMMITTED_BODY_SHA256
EMPTY_DATA_IS_ZERO = False
POSITION_QTY_UNIT_STATUS = "UNPROVEN"
PREREQUISITE_08_STATUS = "UNRESOLVED_TARGET_NOT_OBSERVED_THIS_WINDOW"
PREREQUISITE_09_STATUS = "DEPENDENT_PREREQUISITE_BLOCKED_BY_08"
CLASS_A_CONSUMED = True
CLASS_B_CANONICALLY_COMPLETED = False
CLASS_C_CONSUMED = True
CLASS_D_CONSUMED = False
Z2AP_CONSUMED = False
Z2AR_SUI_TRACK_STATUS = "OPEN_UNCONSUMED"
EXECUTION_READY = False
LIVE_FLATTEN_PROVABILITY = "UNPROVEN"
CAP21_STATUS = "OPTION_C_DEFER_KEEP_UNPROVEN"
CAP21_OPTION_A_SELECTED = False
CAP21_OPTION_B_SELECTED = False
CURRENT_CANONICAL_INSTRUMENT = "SUI-USD_UM_XPERP-310404"
THIS_GO_AUTHORIZES_GET = False
THIS_GO_AUTHORIZES_POST = False
THIS_GO_AUTHORIZES_FLATTEN = False
RUNTIME_AUTHORIZATION_EFFECT = "NONE"

RECOMMENDED_TRACK = "P3_Z2AR_REMAINING_UNRANKED_SUI_REPROOF"
EXACT_NEXT_OWNER_GO = (
    "SEPARATE_SCOPED_OWNER_GO_NAMING_EXACTLY_ONE_REMAINING_Z2AR_SUI_REPROOF_CLASS"
    "_OFFLINE_DOCS_ONLY_NO_RANKING_OF_REMAINDER_NO_GET_UNLESS_SEPARATELY_NAMED"
    "_OR_ALTERNATIVELY_ONE_UNFILTERED_POSITIONS_GET_IF_OWNER_HAS_INDEPENDENT"
    "_REASON_TO_EXPECT_A_TARGET_ROW_NO_AUTOMATIC_REPETITION_NO_CLASS_D_NO_Z2AP"
    "_NO_FLATTEN_EXECUTE_NO_CAP21_OPTION_A_OR_B_NO_CAP_2_X_SEMANTIC_MUTATION"
)
WHY_RECOMMENDED = (
    "P3 leaves successor selection to Owner. Flatten-path numbered earliest"
    " unresolved dependency remains EXECUTION_PREREQUISITE_08_TARGET_POSITION"
    "_NONZERO_PROVEN, but three consecutive unfiltered empty windows"
    " (Z2CN/Z2CR/Z2CT) with byte-identical empty SHA do not close 08, and this"
    " GO forbids automatic repetition. Maximum safe leverage without crossing"
    " runtime or execution authority is therefore a named class on the already"
    "-open Z2AR SUI reproof track. Remaining classes stay unranked."
)

ELIGIBLE_NEXT_TRACK_IDS: tuple[str, ...] = (
    "P3_Z2AR_REMAINING_UNRANKED_SUI_REPROOF",
    "P3_PREREQUISITE_08_UNFILTERED_POSITION_REOBSERVATION",
    "P3_POST_ACTION_READBACK_FRESHNESS_POLICY",
    "P3_AUTHENTICATED_PRODUCTIVE_TRANSPORT",
    "P3_PREREQUISITE_10_UNIT_IDENTITY_OWNER_POLICY_FORM",
)
ALTERNATIVE_TRACKS: tuple[str, ...] = (
    "P3_PREREQUISITE_08_UNFILTERED_POSITION_REOBSERVATION",
    "P3_POST_ACTION_READBACK_FRESHNESS_POLICY",
    "P3_AUTHENTICATED_PRODUCTIVE_TRANSPORT",
    "P3_PREREQUISITE_10_UNIT_IDENTITY_OWNER_POLICY_FORM",
)

TRACK_CENSUS: tuple[Mapping[str, Any], ...] = (
    {
        "TRACK_ID": "P3_PREREQUISITE_08_UNFILTERED_POSITION_REOBSERVATION",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CS AUTHORIZED_RESOLUTION_PATH; §11.13.5.Z2CT consumed GET GO",
        "CURRENT_STATUS": "PATH_EXISTS_CURRENT_RUNTIME_GO_NONE_Z2CT_WINDOW_NOT_OBSERVED",
        "DEPENDENCIES": "SEPARATE_SCOPED_OWNER_GO_FOR_EXACTLY_ONE_UNFILTERED_AUTHENTICATED_GET",
        "BLOCKED_BY": "CURRENT_UNCONSUMED_RUNTIME_GO_NONE;THIS_GO_FORBIDS_AUTOMATIC_REPETITION",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "ELIGIBLE_NEXT",
        "EVIDENCE": "Z2CS RESOLUTION_PATH_ALREADY_EXISTS; Z2CT TARGET_POSITION_STATE=NOT_OBSERVED",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_EXECUTION_PREREQUISITE_09_TARGET_POSITION_QTY_NUMERIC",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CQ DEPENDENT_09_12_20_CANNOT_PASS_WITHOUT_08_NONZERO; §11.13.5.Z2CT",
        "CURRENT_STATUS": "DEPENDENT_PREREQUISITE_BLOCKED_BY_08",
        "DEPENDENCIES": "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN",
        "BLOCKED_BY": "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2CT EXECUTION_PREREQUISITE_09_STATUS=DEPENDENT_PREREQUISITE_BLOCKED_BY_08",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": True,
        "INDEPENDENT_OF_08": False,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_CLASS_D_PRODUCTIVE_FLATTEN_MUTATION",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CK CLASS_D=PRODUCTIVE_FLATTEN_MUTATION; §11.13.5.Z2CJ remaining pareto",
        "CURRENT_STATUS": "UNCONSUMED_EXECUTION_READY_FALSE",
        "DEPENDENCIES": "08_NONZERO;FLATTEN_EXECUTE_OWNER_GO;AUTHENTICATED_POST;SEPARATE_TRADING_OWNER_GO",
        "BLOCKED_BY": "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN;EXECUTION_READY=false",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": True,
        "WOULD_CONSUME_CLASS_D": True,
        "WOULD_CONSUME_Z2AP": True,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2CK CLASS_D_CONSUMED=false; Z2CT CLASS_D_CONSUMED=false EXECUTION_READY=false",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": True,
        "INDEPENDENT_OF_08": False,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_Z2AP_PRODUCTIVE_LIVE_FLATTEN_PROOF",
        "SOURCE_AUTHORITY": "§11.13.5.Z2AP; §11.13.5.Z2AS Z2AP_TRACK_STATUS=OPEN_UNCONSUMED",
        "CURRENT_STATUS": "OPEN_UNCONSUMED_PRODUCTIVE_PROOF_READY_LIVE_FLATTEN_UNPROVEN",
        "DEPENDENCIES": "08_NONZERO;CLASS_D_OR_FLATTEN_EXECUTE_OWNER_GO;NETWORK_SESSION;CONFIRM_TOKEN",
        "BLOCKED_BY": "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN;Z2AP_CONSUMED=false_not_execute",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": True,
        "WOULD_CONSUME_CLASS_D": True,
        "WOULD_CONSUME_Z2AP": True,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2AP PRODUCTIVE_PROOF_READY=true PRODUCTIVE_PROOF_EXECUTED=false; Z2CT Z2AP_CONSUMED=false",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": True,
        "INDEPENDENT_OF_08": False,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_FLATTEN_EXECUTE",
        "SOURCE_AUTHORITY": "flatten_execute_authority_v1 SECTION_11_13_5_FLATTEN_EXECUTE_OWNER_GO",
        "CURRENT_STATUS": "UNAUTHORIZED_CONFIRM_TOKEN_AND_OWNER_GO_ABSENT",
        "DEPENDENCIES": "SECTION_11_13_5_FLATTEN_EXECUTE_OWNER_GO;I_AUTHORIZE_SECTION_11_13_5_FLATTEN_EXECUTE;08_NONZERO",
        "BLOCKED_BY": "NO_FLATTEN_EXECUTE_OWNER_GO;08_UNRESOLVED;CLASS_D_UNCONSUMED",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": True,
        "WOULD_CONSUME_CLASS_D": True,
        "WOULD_CONSUME_Z2AP": True,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2CT FLATTEN_AUTHORIZED=false THIS_GO_AUTHORIZES_FLATTEN=false",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": True,
        "INDEPENDENT_OF_08": False,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_FILTERED_INSTID_ZERO_ELICITATION",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CE; §11.13.5.Z2CS FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH",
        "CURRENT_STATUS": "NOT_AN_08_PATH_NOT_CURRENT_SUI_ZERO_PROOF_POSID_ABSENT",
        "DEPENDENCIES": "PREVIOUSLY_HELD_PLUS_VALID_POSID_BOTH_ABSENT",
        "BLOCKED_BY": "SUI_EVER_OPENED_OR_HELD_CANONICAL_EVIDENCE_STATUS=ABSENT",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "NOT_APPLICABLE",
        "EVIDENCE": "Z2CS FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH=true; Z2CT Z2CT_DOES_NOT_PERFORM_FILTERED_INSTID_ZERO_PROOF",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_CLASS_B_CURRENT_SUI_ZERO_AND_GLOBAL_UNIVERSE",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CH; §11.13.5.Z2CI CLASS_B_CANONICALLY_COMPLETED=false",
        "CURRENT_STATUS": "KNOWN_FIRST_PARTY_SURFACES_EXHAUSTED_GLOBAL_UNIVERSE_NOT_EXHAUSTED_ZERO_UNPROVEN",
        "DEPENDENCIES": "GENUINELY_NEW_CLASS_B_INFORMATION_CARRIER_OR_OBSERVED_ZERO_ROW",
        "BLOCKED_BY": "EMPTY_DATA_IS_ZERO=false;NO_NEW_IDENTIFIED_INFORMATION_CARRIER;POSID_ABSENT",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2CI GLOBAL_CLASS_B_EVIDENCE_UNIVERSE_EXHAUSTED=false; Z2CT CURRENT_SUI_ZERO_STATE_STATUS=UNPROVEN",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_CLASS_C_AUTHENTICATED_SUI_RUNTIME_GET",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CJ CLASS_C_CONSUMED=true",
        "CURRENT_STATUS": "CANONICALLY_CONSUMED_BY_Z2CJ",
        "DEPENDENCIES": "NONE",
        "BLOCKED_BY": "NONE",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "SUPERSEDED",
        "EVIDENCE": "Z2CJ CLASS_C_CONSUMED_ONCE=true; Z2CT CLASS_C_CONSUMED=true",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_Z2AR_REMAINING_UNRANKED_SUI_REPROOF",
        "SOURCE_AUTHORITY": "§11.13.5.Z2AS; §11.13.5.Z2BX remaining unranked SUI reproof classes",
        "CURRENT_STATUS": "OPEN_UNCONSUMED_UNRANKED_COVER_USDC_FX_ROUNDING_FINISHED_RISK_ENVELOPE_NUMERIC",
        "DEPENDENCIES": "SEPARATE_SCOPED_OWNER_GO_NAMING_EXACTLY_ONE_REMAINING_CLASS",
        "BLOCKED_BY": "NONE",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "ELIGIBLE_NEXT",
        "EVIDENCE": "Z2AS Z2AR_SUI_TRACK_STATUS=OPEN_UNCONSUMED; Z2BX COVER_USDC_STATUS=UNINSTANTIATED SUI_REPROOF_CLASSES_RANKED=false",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_POST_ACTION_READBACK_FRESHNESS_POLICY",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CP POST_ACTION_READBACK_FRESHNESS_POLICY=SEPARATE_LATER_IF_REQUIRED",
        "CURRENT_STATUS": "UNBOUND_SEPARATE_LATER_IF_REQUIRED",
        "DEPENDENCIES": "SEPARATE_SCOPED_OWNER_GO;MUST_NOT_REORDER_BEFORE_08",
        "BLOCKED_BY": "NONE_FOR_OFFLINE_FORM;LATER_THAN_08_ON_FLATTEN_PATH",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "ELIGIBLE_NEXT",
        "EVIDENCE": "Z2CP POST_ACTION_READBACK_FRESHNESS_POLICY=SEPARATE_LATER_IF_REQUIRED; Z2CQ Z2CQ_PERSIST_IS_NOT_POST_ACTION_READBACK_FRESHNESS_BIND",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_AUTHENTICATED_PRODUCTIVE_TRANSPORT",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CL offline urllib; §11.13.5.Z2CQ AUTHENTICATED_PRODUCTIVE_TRANSPORT_STATUS",
        "CURRENT_STATUS": "REMAINS_UNRESOLVED_OFFLINE_URLLIB_PRESENT_AUTH_UNSIGNED_HMAC_HANDLE_ABSENT",
        "DEPENDENCIES": "SEPARATE_SCOPED_OWNER_GO;MUST_NOT_REORDER_HMAC_BEFORE_08",
        "BLOCKED_BY": "NONE_FOR_OFFLINE_WIRING;Z2CQ_HMAC_HANDLE_REORDERED_BEFORE_08=false",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "ELIGIBLE_NEXT",
        "EVIDENCE": "Z2CQ HMAC_HANDLE_REORDERED_BEFORE_08=false AUTHENTICATED_PRODUCTIVE_TRANSPORT_STATUS=REMAINS_UNRESOLVED",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_PREREQUISITE_10_UNIT_IDENTITY_OWNER_POLICY_FORM",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CQ UNIT_CHAIN_VERDICT; POSITION_QTY_UNIT_STATUS=UNPROVEN",
        "CURRENT_STATUS": "UNPROVEN_HIGHER_AUTHORITY_MUST_NOT_CLAIM_OBSERVATION_PROVEN",
        "DEPENDENCIES": "SEPARATE_SCOPED_OWNER_GO_POLICY_FORM_ONLY_NO_PROVEN_CLAIM",
        "BLOCKED_BY": "NONE_FOR_POLICY_FORM;OBSERVATION_PROVEN_BLOCKED_BY_08",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "ELIGIBLE_NEXT",
        "EVIDENCE": "Z2CQ UNIT_CHAIN_VERDICT=PASSTHROUGH_POS_TO_SZ_UNIT_IDENTITY_UNPROVEN FAIL_CLOSED_IF_UNIT_IDENTITY_CLAIMED_PROVEN",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_PREREQUISITE_11_POSSIDE_WIRE_POLICY",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CB FLATTEN_POS_SIDE=OMITTED_FROM_VENUE_NATIVE_BODY; §11.13.5.Z2CQ",
        "CURRENT_STATUS": "OMITTED_FROM_VENUE_NATIVE_BODY_ALREADY_BOUND",
        "DEPENDENCIES": "NONE_UNLESS_OWNER_CHANGES_BOUND_OMISSION",
        "BLOCKED_BY": "INVENTING_POSSIDE_WIRE_FIELD_FAIL_CLOSED",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "NOT_APPLICABLE",
        "EVIDENCE": "Z2CQ POSSIDE_ADDED_TO_FLATTEN_BODY=false FAIL_CLOSED_IF_POSSIDE_WIRE_POLICY_INVENTED",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_CAP21_OPTION_C_DEFER_KEEP_UNPROVEN",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CJ REMAINING_PARETO_FRONTIER; CAP21_STATUS=OPTION_C_DEFER_KEEP_UNPROVEN",
        "CURRENT_STATUS": "OPTION_C_DEFER_KEEP_UNPROVEN_OPTION_A_AND_B_FAIL_CLOSED",
        "DEPENDENCIES": "SEPARATE_OWNER_GO_IF_REOPENED;MUST_NOT_SELECT_A_OR_B_HERE",
        "BLOCKED_BY": "OPTION_C_DEFER;FAIL_CLOSED_IF_CAP21_OPTION_A_OR_B_SELECTED",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "DEFERRED",
        "EVIDENCE": "Z2CL/Z2CM CAP21_STATUS=OPTION_C_DEFER_KEEP_UNPROVEN; Z2CT NO_CAP21_OPTION_A_OR_B",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "CAP_2_X_MASTER_V2_PARALLEL",
        "SOURCE_AUTHORITY": "Master V2 Cap 2.1-2.4 specs; Atlas GAP:cap23_not_wired_to_canary ADJUDICATED",
        "CURRENT_STATUS": "NOT_EARLIEST_11_13_5_DEPENDENCY_SUI_ALREADY_BOUND_Z2BY",
        "DEPENDENCIES": "SEPARATE_CORE_MASTER_V2_OWNER_GO_FORBIDDEN_BY_THIS_GO",
        "BLOCKED_BY": "THIS_GO_NO_CORE_MASTER_V2_DOUBLE_PLAY_SEMANTIC_MUTATION",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "DEFERRED",
        "EVIDENCE": "Atlas GAP:cap23_not_wired_to_canary STATUS=ADJUDICATED; Z2BY CURRENT_CANONICAL_INSTRUMENT=SUI",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "NAVIGATION_INDEX_ONLY",
    },
    {
        "TRACK_ID": "P3_EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CQ PREREQUISITE_16_CURRENT_STATUS",
        "CURRENT_STATUS": "OFFLINE_IMPLEMENTED_RUNTIME_UNAUTHORIZED_STILL_BLOCKING",
        "DEPENDENCIES": "SEPARATE_RUNTIME_ACTIVATION_OWNER_GO",
        "BLOCKED_BY": "RUNTIME_UNAUTHORIZED",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": True,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2CQ PREREQUISITE_16_CURRENT_STATUS=OFFLINE_IMPLEMENTED_RUNTIME_UNAUTHORIZED_STILL_BLOCKING",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_SEND_TIME_PASS_18_19_21_24",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CO; §11.13.5.Z2CT SEND_TIME_PASS_18_19_21_24=UNPROVEN",
        "CURRENT_STATUS": "UNPROVEN_REQUIRES_AUTHORIZED_SEND",
        "DEPENDENCIES": "FLATTEN_SEND;08_NONZERO_PRE_SEND",
        "BLOCKED_BY": "NO_AUTHORIZED_SEND;08_UNRESOLVED",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": True,
        "WOULD_CONSUME_CLASS_D": True,
        "WOULD_CONSUME_Z2AP": True,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2CT SEND_TIME_PASS=UNPROVEN FLATTEN_PRE_SEND_PERMIT_EVALUATED=false",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": True,
        "INDEPENDENT_OF_08": False,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_LIVE_CANARY_TESTNET",
        "SOURCE_AUTHORITY": "§11.13.5 standing LIVE_AUTHORIZED=false; Z2CT LIVE_AUTHORIZED=false",
        "CURRENT_STATUS": "UNAUTHORIZED",
        "DEPENDENCIES": "SEPARATE_LIVE_OR_TESTNET_OR_CANARY_OWNER_GO",
        "BLOCKED_BY": "LIVE_AUTHORIZED=false;TESTNET_AUTHORIZED=false;CANARY_AUTHORIZED=false",
        "REQUIRES_RUNTIME": True,
        "REQUIRES_SECRET_ACCESS": True,
        "REQUIRES_EXECUTION_AUTHORITY": True,
        "WOULD_CONSUME_CLASS_D": True,
        "WOULD_CONSUME_Z2AP": True,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": False,
        "DISPOSITION": "BLOCKED",
        "EVIDENCE": "Z2CT LIVE_AUTHORIZED=false FAIL_CLOSED_IF_LIVE_OR_TESTNET_OR_CANARY_FLIPPED_TRUE",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": True,
        "INDEPENDENT_OF_08": False,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
    {
        "TRACK_ID": "P3_CLASS_A_SUI_SAME_PACK_FRESHNESS_VS_IDENTITY",
        "SOURCE_AUTHORITY": "§11.13.5.Z2CG CLASS_A_CONSUMED=true",
        "CURRENT_STATUS": "CANONICALLY_CONSUMED_BY_Z2CG",
        "DEPENDENCIES": "NONE",
        "BLOCKED_BY": "NONE",
        "REQUIRES_RUNTIME": False,
        "REQUIRES_SECRET_ACCESS": False,
        "REQUIRES_EXECUTION_AUTHORITY": False,
        "WOULD_CONSUME_CLASS_D": False,
        "WOULD_CONSUME_Z2AP": False,
        "COMPATIBLE_WITH_CURRENT_INVARIANTS": True,
        "DISPOSITION": "SUPERSEDED",
        "EVIDENCE": "Z2CG CLASS_A persist consumed; later slices CLASS_A_CONSUMED=true",
        "REQUIRES_PREREQUISITE_08_NONZERO_FIRST": False,
        "INDEPENDENT_OF_08": True,
        "EPISTEMIC_CLASS": "CANONICAL_AUTHORITY",
    },
)

CANDIDATE_TRACK_COUNT = len(TRACK_CENSUS)
CANDIDATE_TRACKS: tuple[str, ...] = tuple(str(row["TRACK_ID"]) for row in TRACK_CENSUS)
STALE_OR_SUPERSEDED_TRACK_IDS: tuple[str, ...] = (
    "P3_CLASS_C_AUTHENTICATED_SUI_RUNTIME_GET",
    "P3_CLASS_A_SUI_SAME_PACK_FRESHNESS_VS_IDENTITY",
    "P3_FILTERED_INSTID_ZERO_ELICITATION",
    "P3_PREREQUISITE_11_POSSIDE_WIRE_POLICY",
)


class LiveCanaryPostZ2ctNamedProgressionTrackAdjudicationError(RuntimeError):
    """Fail-closed named-track adjudication violation."""


def _track_by_id(track_id: str) -> Mapping[str, Any]:
    for row in TRACK_CENSUS:
        if row["TRACK_ID"] == track_id:
            return row
    raise LiveCanaryPostZ2ctNamedProgressionTrackAdjudicationError(f"UNKNOWN_TRACK_ID:{track_id}")


def reject_unique_canonical_next_invention_v1(*, claimed_unique: str | None) -> str:
    """P3 forbids inventing a unique global next from numbering or empty GET repetition."""
    claimed = str(claimed_unique or "").strip()
    if not claimed or claimed in {"NONE", UNIQUE_CANONICAL_NEXT_TRACK}:
        return "UNIQUE_CANONICAL_NEXT_TRACK_NONE_BY_P3_POLICY"
    raise LiveCanaryPostZ2ctNamedProgressionTrackAdjudicationError(
        f"UNIQUE_CANONICAL_NEXT_INVENTED:{claimed}"
    )


def reject_automatic_08_reobservation_v1(*, claimed_next_is_identical_get: bool) -> str:
    """Identical unfiltered GET is a permitted path, not the unique next action."""
    if claimed_next_is_identical_get:
        raise LiveCanaryPostZ2ctNamedProgressionTrackAdjudicationError(
            "IDENTICAL_UNFILTERED_GET_IS_NOT_UNIQUE_CANONICAL_NEXT"
        )
    return "IDENTICAL_UNFILTERED_GET_IS_PERMITTED_OBSERVATION_PATH_ONLY"


def adjudicate_post_z2ct_named_progression_tracks_v1(
    *,
    claimed_unique_next: str | None = None,
    claimed_next_is_identical_get: bool = False,
) -> dict[str, Any]:
    """Return the bound census. Not flatten authorization and not a GET."""
    unique_token = reject_unique_canonical_next_invention_v1(claimed_unique=claimed_unique_next)
    get_token = reject_automatic_08_reobservation_v1(
        claimed_next_is_identical_get=claimed_next_is_identical_get
    )
    eligible = tuple(_track_by_id(track_id) for track_id in ELIGIBLE_NEXT_TRACK_IDS)
    requires_08 = tuple(
        str(row["TRACK_ID"])
        for row in TRACK_CENSUS
        if row["REQUIRES_PREREQUISITE_08_NONZERO_FIRST"] is True
    )
    independent = tuple(
        str(row["TRACK_ID"])
        for row in TRACK_CENSUS
        if row["INDEPENDENT_OF_08"] is True and row["DISPOSITION"] == "ELIGIBLE_NEXT"
    )
    return {
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "LAST_CANONICALLY_CLOSED_11_13_5_SLICE": LAST_CANONICALLY_CLOSED_11_13_5_SLICE,
        "THIS_PERSIST_DOES_NOT_SUPERSEDE_Z2CT_AS_LAST_CANONICALLY_CLOSED_11_13_5_SLICE": (
            THIS_PERSIST_DOES_NOT_SUPERSEDE_Z2CT_AS_LAST_CANONICALLY_CLOSED_11_13_5_SLICE
        ),
        "ADJUDICATION": ADJUDICATION,
        "UNIQUE_CANONICAL_NEXT_TRACK": UNIQUE_CANONICAL_NEXT_TRACK,
        "RECOMMENDED_TRACK": RECOMMENDED_TRACK,
        "ALTERNATIVE_TRACKS": ALTERNATIVE_TRACKS,
        "WHY_RECOMMENDED": WHY_RECOMMENDED,
        "EXACT_NEXT_OWNER_GO": EXACT_NEXT_OWNER_GO,
        "P3_INDEPENDENT_PARALLEL_TRACKS_POLICY": P3_INDEPENDENT_PARALLEL_TRACKS_POLICY,
        "GLOBAL_UNIQUE_CANONICAL_NEXT_STEP": GLOBAL_UNIQUE_CANONICAL_NEXT_STEP,
        "P3_INTENTIONALLY_LEAVES_SUCCESSOR_SELECTION_TO_OWNER": (
            P3_INTENTIONALLY_LEAVES_SUCCESSOR_SELECTION_TO_OWNER
        ),
        "OFFLINE_PROGRESSION_AVAILABLE": OFFLINE_PROGRESSION_AVAILABLE,
        "RUNTIME_REOBSERVATION_IS_ONLY_VALID_NEXT_TRACK": (
            RUNTIME_REOBSERVATION_IS_ONLY_VALID_NEXT_TRACK
        ),
        "IDENTICAL_UNFILTERED_GET_IS_UNIQUE_CANONICAL_NEXT": (
            IDENTICAL_UNFILTERED_GET_IS_UNIQUE_CANONICAL_NEXT
        ),
        "IDENTICAL_UNFILTERED_GET_IS_PERMITTED_OBSERVATION_PATH_ONLY": (
            IDENTICAL_UNFILTERED_GET_IS_PERMITTED_OBSERVATION_PATH_ONLY
        ),
        "AUTOMATIC_PREREQUISITE_08_REOBSERVATION_AUTHORIZED": (
            AUTOMATIC_PREREQUISITE_08_REOBSERVATION_AUTHORIZED
        ),
        "CANDIDATE_TRACK_COUNT": CANDIDATE_TRACK_COUNT,
        "CANDIDATE_TRACKS": CANDIDATE_TRACKS,
        "ELIGIBLE_NEXT_TRACK_IDS": ELIGIBLE_NEXT_TRACK_IDS,
        "TRACKS_REQUIRING_08_NONZERO_FIRST": requires_08,
        "ELIGIBLE_TRACKS_INDEPENDENT_OF_08": independent,
        "STALE_OR_SUPERSEDED_TRACK_IDS": STALE_OR_SUPERSEDED_TRACK_IDS,
        "EARLIEST_UNRESOLVED_DEPENDENCY": CLUSTER_EARLIEST_UNRESOLVED_DEPENDENCY,
        "PREREQUISITE_08_STATUS": PREREQUISITE_08_STATUS,
        "PREREQUISITE_09_STATUS": PREREQUISITE_09_STATUS,
        "EMPTY_DATA_IS_ZERO": EMPTY_DATA_IS_ZERO,
        "POSITION_QTY_UNIT_STATUS": POSITION_QTY_UNIT_STATUS,
        "CLASS_D_CONSUMED": CLASS_D_CONSUMED,
        "Z2AP_CONSUMED": Z2AP_CONSUMED,
        "Z2AR_SUI_TRACK_STATUS": Z2AR_SUI_TRACK_STATUS,
        "EXECUTION_READY": EXECUTION_READY,
        "LIVE_FLATTEN_PROVABILITY": LIVE_FLATTEN_PROVABILITY,
        "CAP21_STATUS": CAP21_STATUS,
        "Z2CT_OWNER_GO_STATUS": Z2CT_OWNER_GO_STATUS,
        "CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH": (
            CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH
        ),
        "AUTHORIZED_RESOLUTION_PATH": AUTHORIZED_RESOLUTION_PATH,
        "CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION": (
            CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION
        ),
        "FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH": (
            FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH
        ),
        "MINIMUM_FUTURE_RUNTIME_AUTHORITY": MINIMUM_FUTURE_RUNTIME_AUTHORITY,
        "Z2CS_CURRENT_UNCONSUMED_RUNTIME_GO": Z2CS_CURRENT_UNCONSUMED_RUNTIME_GO,
        "Z2CT_WINDOW_TARGET_POSITION_STATE": Z2CT_WINDOW_TARGET_POSITION_STATE,
        "Z2CT_WINDOW_BODY_SHA256": Z2CT_WINDOW_BODY_SHA256,
        "CURRENT_CANONICAL_INSTRUMENT": CURRENT_CANONICAL_INSTRUMENT,
        "THIS_GO_AUTHORIZES_GET": THIS_GO_AUTHORIZES_GET,
        "THIS_GO_AUTHORIZES_POST": THIS_GO_AUTHORIZES_POST,
        "THIS_GO_AUTHORIZES_FLATTEN": THIS_GO_AUTHORIZES_FLATTEN,
        "RUNTIME_AUTHORIZATION_EFFECT": RUNTIME_AUTHORIZATION_EFFECT,
        "UNIQUE_NEXT_DENY_TOKEN": unique_token,
        "IDENTICAL_GET_DENY_TOKEN": get_token,
        "eligible_track_count": len(eligible),
        "census": tuple(dict(row) for row in TRACK_CENSUS),
    }
