"""Offline Prerequisite-08 resolution-authority adjudication.

Encodes the post-Z2CR forensic census: which already-canonical path can
satisfy EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN, and
that TARGET_POSITION_STATE=NOT_OBSERVED is fail-closed rather than a
zero-semantics gap. Evaluates caller-supplied facts only. Never GETs,
never POSTs, never authorizes flatten, live, testnet, or canary, never
promotes empty or absent to zero, and never claims 08 PROVEN from the
committed empty windows.
"""

from __future__ import annotations

from typing import Any, Mapping

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.execution_prerequisite_08_cluster_contract_v1 import (
    EARLIEST_UNRESOLVED_DEPENDENCY as CLUSTER_EARLIEST_UNRESOLVED_DEPENDENCY,
    Z2CN_COMMITTED_BODY_SHA256,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.pre_submit_state_v1 import (
    TARGET_POSITION_NONZERO_PROVEN,
    TARGET_POSITION_NOT_OBSERVED,
    TARGET_POSITION_ZERO_PROVEN,
    classify_target_position_state_v1,
)

OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_13_5_PREREQUISITE_08_RESOLUTION_AUTHORITY_ADJUDICATION_V1"
)
THIS_SLICE = "11.13.5.Z2CS"
PREDECESSOR_SLICE = "11.13.5.Z2CR"
LAST_CANONICALLY_CLOSED_11_13_5_SLICE = "SECTION_11_13_5_Z2CR"
THIS_PERSIST_DOES_NOT_SUPERSEDE_Z2CR_AS_LAST_CANONICALLY_CLOSED_11_13_5_SLICE = True

PREREQUISITE_08_REQUIRED_PROPOSITION = "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
CANONICAL_PRODUCER = (
    "classify_target_position_state_v1"
    "+build_account_positions_query_v1(unfiltered)"
    "+run_authorized_fresh_position_observation_v1"
)
CANONICAL_CONSUMER = (
    "flatten_pre_send_gate_v1.TARGET_POSITION_STATE"
    "+observe_target_position_flatten_candidate_v1"
    "+adjudicate_prerequisite_08_window_v1"
)
AUTHORIZED_RESOLUTION_PATH = (
    "UNFILTERED_GET_API_V5_ACCOUNT_POSITIONS_PLUS_CLASSIFY_TARGET_POSITION_STATE_V1"
)
AUTHORIZED_RESOLUTION_PATH_COUNT = 1
CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH = "NONE"
Z2CR_OWNER_GO_STATUS = "CONSUMED"
Z2CN_OWNER_GO_STATUS = "CONSUMED"

TARGET_NOT_OBSERVED_SEMANTICS = (
    "INTENTIONAL_FAIL_CLOSED_THIS_WINDOW_NOT_ZERO_NOT_NONZERO_NOT_COMPLETENESS"
)
EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False
ZERO_SEMANTICS_CANONICAL_AUTHORITY = (
    "docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md#11.13.5.Z2CE"
    ";EMPTY_EQUALS_ZERO=false"
    ";UNFILTERED_EMPTY_SEMANTICS_STATUS="
    "TARGET_INSTRUMENT_NOT_OBSERVED_NOT_TARGET_POSITION_ZERO"
)
OMISSION_OF_INSTRUMENT_ROW_MEANS_ZERO_CANONICAL_RULE = "NONE"
POSITION_QTY_UNIT_STATUS = "UNPROVEN"
FRESHNESS_REQUIREMENT = (
    "NORMATIVE_AT_FLATTEN_PRE_SEND_PERMIT_5000MS;"
    "WINDOW_ADJUDICATION_AGE_MAY_BE_SAMPLED_AFTER_GET_AND_IS_NOT_SEND_TIME_PASS"
)
FRESHNESS_POLICY_MAX_AGE_MS = 5000
AGE_EVALUATION_POINT_PRE_SEND = "IMMEDIATELY_BEFORE_FLATTEN_SEND_PERMIT_DECISION"
AGE_EVALUATION_POINT_Z2CR_WINDOW = "ADJUDICATION_AFTER_GET_NOT_FLATTEN_SEND"

ADJUDICATION = "RESOLUTION_PATH_ALREADY_EXISTS"
CONTRACT_GAP_CLASS = "NONE"
ABSENT_ROW_MAKES_08_IMPOSSIBLE = True
ABSENT_ROW_08_IMPOSSIBILITY_CLASS = (
    "PREREQUISITE_DEFINITION_POSITIVE_NONZERO_PROOF_WORKING_AS_DESIGNED_NOT_A_GAP"
)
NOT_OBSERVED_EXPOSES_ZERO_SEMANTICS_CONTRACT_GAP_FOR_08 = False
CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION = False
MINIMUM_FUTURE_RUNTIME_AUTHORITY = (
    "SEPARATE_SCOPED_OWNER_GO_FOR_EXACTLY_ONE_UNFILTERED_AUTHENTICATED_"
    "GET_ACCOUNT_POSITIONS_REUSING_EXISTING_PRODUCER_NO_FILTERED_INSTID_"
    "ZERO_PROOF_NO_POST_NO_FLATTEN_NO_CLASS_D"
)

FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH = True
Z2CL_CHOICE_B_IS_NOT_PRE_SEND_08_PATH = True
Z2CA_Z2CN_Z2CR_EMPTY_SHA_IS_NOT_CURRENT_08_PROOF = True
FIXTURE_NONZERO_IS_NOT_PRODUCTIVE_08_PROOF = True
QUERY_COMPLETENESS_PROVEN = False
HTTP_OK_DOES_NOT_PROVE_COMPLETENESS = True
CLASS_D_CONSUMED = False
Z2AP_CONSUMED = False
EXECUTION_READY = False
LIVE_FLATTEN_PROVABILITY = "UNPROVEN"
THIS_GO_AUTHORIZES_GET = False
THIS_GO_AUTHORIZES_POST = False
THIS_GO_AUTHORIZES_FLATTEN = False
RUNTIME_AUTHORIZATION_EFFECT = "NONE"

Z2CR_EMPTY_ENVELOPE_SHA256 = Z2CN_COMMITTED_BODY_SHA256
CURRENT_CANONICAL_INSTRUMENT = "SUI-USD_UM_XPERP-310404"

NON_RESOLUTION_PATHS: tuple[str, ...] = (
    "FILTERED_INSTID_GET_ACCOUNT_POSITIONS",
    "EXPLICIT_POSID_CLOSED_ELICITATION",
    "Z2CL_CHOICE_B_POST_ACTION_MISSING_TARGET",
    "HISTORICAL_Z2CA_OR_Z2CN_OR_Z2CR_EMPTY_ENVELOPE",
    "OFFLINE_FIXTURE_NONZERO_PAYLOAD",
    "EMPTY_DATA_PROMOTED_TO_ZERO",
    "ABSENT_ROW_PROMOTED_TO_ZERO",
    "NEVER_HELD_INFERRED_FROM_ABSENCE",
)


class LiveCanaryPrerequisite08ResolutionAuthorityError(RuntimeError):
    """Fail-closed resolution-authority adjudication violation."""


def reject_absent_or_empty_as_08_proof_v1(
    *,
    classifier_state: str,
    empty_data_is_zero_claim: bool = False,
    body_sha256: str | None = None,
) -> str:
    """Return the deny token. Never promotes not-observed or empty to 08 PASS."""
    if empty_data_is_zero_claim or EMPTY_DATA_IS_ZERO:
        raise LiveCanaryPrerequisite08ResolutionAuthorityError(
            "EMPTY_DATA_MUST_NOT_BE_PROMOTED_TO_ZERO"
        )
    claimed = str(body_sha256 or "").strip().lower()
    if claimed == Z2CR_EMPTY_ENVELOPE_SHA256:
        return "HISTORICAL_EMPTY_ENVELOPE_IS_NOT_CURRENT_08_PROOF"
    if classifier_state == TARGET_POSITION_NONZERO_PROVEN:
        return "WINDOW_NONZERO_IS_NOT_SEND_TIME_OR_CLASS_D_PROOF"
    if classifier_state == TARGET_POSITION_ZERO_PROVEN:
        return "ZERO_ROW_DOES_NOT_SATISFY_PREREQUISITE_08"
    if classifier_state == TARGET_POSITION_NOT_OBSERVED:
        return "NOT_OBSERVED_DOES_NOT_SATISFY_PREREQUISITE_08"
    return "UNKNOWN_OR_MISSING_OBSERVATION_DOES_NOT_SATISFY_PREREQUISITE_08"


def reject_non_resolution_path_v1(*, claimed_path: str) -> str:
    """Named non-paths cannot resolve Prerequisite 08."""
    path = str(claimed_path or "").strip()
    if path == AUTHORIZED_RESOLUTION_PATH:
        return "CANONICAL_PATH_IDENTIFIED_CURRENT_RUNTIME_GO_NONE"
    if path in NON_RESOLUTION_PATHS:
        return f"NOT_AN_08_RESOLUTION_PATH:{path}"
    raise LiveCanaryPrerequisite08ResolutionAuthorityError("UNKNOWN_CLAIMED_RESOLUTION_PATH")


def adjudicate_prerequisite_08_resolution_authority_v1(
    *,
    positions_payload: Mapping[str, Any] | None = None,
    instrument_id: str = CURRENT_CANONICAL_INSTRUMENT,
    claimed_body_sha256: str | None = None,
) -> dict[str, Any]:
    """Classify resolution authority. Not flatten authorization and not a GET."""
    classified = classify_target_position_state_v1(
        positions_payload=positions_payload,
        instrument_id=instrument_id,
    )
    deny = reject_absent_or_empty_as_08_proof_v1(
        classifier_state=classified.state,
        body_sha256=claimed_body_sha256,
    )
    return {
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "LAST_CANONICALLY_CLOSED_11_13_5_SLICE": LAST_CANONICALLY_CLOSED_11_13_5_SLICE,
        "PREREQUISITE_08_REQUIRED_PROPOSITION": PREREQUISITE_08_REQUIRED_PROPOSITION,
        "CANONICAL_PRODUCER": CANONICAL_PRODUCER,
        "CANONICAL_CONSUMER": CANONICAL_CONSUMER,
        "AUTHORIZED_RESOLUTION_PATH_COUNT": AUTHORIZED_RESOLUTION_PATH_COUNT,
        "AUTHORIZED_RESOLUTION_PATHS": AUTHORIZED_RESOLUTION_PATH,
        "CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH": (
            CURRENT_UNCONSUMED_RUNTIME_GO_FOR_RESOLUTION_PATH
        ),
        "TARGET_NOT_OBSERVED_SEMANTICS": TARGET_NOT_OBSERVED_SEMANTICS,
        "EMPTY_DATA_IS_ZERO": EMPTY_DATA_IS_ZERO,
        "ABSENT_TARGET_ROW_IS_ZERO": ABSENT_TARGET_ROW_IS_ZERO,
        "ZERO_SEMANTICS_CANONICAL_AUTHORITY": ZERO_SEMANTICS_CANONICAL_AUTHORITY,
        "OMISSION_OF_INSTRUMENT_ROW_MEANS_ZERO_CANONICAL_RULE": (
            OMISSION_OF_INSTRUMENT_ROW_MEANS_ZERO_CANONICAL_RULE
        ),
        "POSITION_QTY_UNIT_STATUS": POSITION_QTY_UNIT_STATUS,
        "FRESHNESS_REQUIREMENT": FRESHNESS_REQUIREMENT,
        "ADJUDICATION": ADJUDICATION,
        "CONTRACT_GAP_CLASS": CONTRACT_GAP_CLASS,
        "ABSENT_ROW_MAKES_08_IMPOSSIBLE": ABSENT_ROW_MAKES_08_IMPOSSIBLE,
        "ABSENT_ROW_08_IMPOSSIBILITY_CLASS": ABSENT_ROW_08_IMPOSSIBILITY_CLASS,
        "NOT_OBSERVED_EXPOSES_ZERO_SEMANTICS_CONTRACT_GAP_FOR_08": (
            NOT_OBSERVED_EXPOSES_ZERO_SEMANTICS_CONTRACT_GAP_FOR_08
        ),
        "CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION": (
            CAN_08_BE_SATISFIED_WITHOUT_FURTHER_RUNTIME_OBSERVATION
        ),
        "MINIMUM_FUTURE_RUNTIME_AUTHORITY": MINIMUM_FUTURE_RUNTIME_AUTHORITY,
        "EARLIEST_UNRESOLVED_DEPENDENCY": CLUSTER_EARLIEST_UNRESOLVED_DEPENDENCY,
        "classifier_state": classified.state,
        "classifier_reason": classified.reason,
        "08_PROOF_DENY_TOKEN": deny,
        "prerequisite_08_proven": False,
        "FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH": (
            FILTERED_INSTID_GET_IS_NOT_08_RESOLUTION_PATH
        ),
        "Z2CL_CHOICE_B_IS_NOT_PRE_SEND_08_PATH": Z2CL_CHOICE_B_IS_NOT_PRE_SEND_08_PATH,
        "Z2CA_Z2CN_Z2CR_EMPTY_SHA_IS_NOT_CURRENT_08_PROOF": (
            Z2CA_Z2CN_Z2CR_EMPTY_SHA_IS_NOT_CURRENT_08_PROOF
        ),
        "FIXTURE_NONZERO_IS_NOT_PRODUCTIVE_08_PROOF": (FIXTURE_NONZERO_IS_NOT_PRODUCTIVE_08_PROOF),
        "QUERY_COMPLETENESS_PROVEN": QUERY_COMPLETENESS_PROVEN,
        "HTTP_OK_DOES_NOT_PROVE_COMPLETENESS": HTTP_OK_DOES_NOT_PROVE_COMPLETENESS,
        "CLASS_D_CONSUMED": CLASS_D_CONSUMED,
        "Z2AP_CONSUMED": Z2AP_CONSUMED,
        "EXECUTION_READY": EXECUTION_READY,
        "LIVE_FLATTEN_PROVABILITY": LIVE_FLATTEN_PROVABILITY,
        "THIS_GO_AUTHORIZES_GET": THIS_GO_AUTHORIZES_GET,
        "THIS_GO_AUTHORIZES_POST": THIS_GO_AUTHORIZES_POST,
        "THIS_GO_AUTHORIZES_FLATTEN": THIS_GO_AUTHORIZES_FLATTEN,
        "RUNTIME_AUTHORIZATION_EFFECT": RUNTIME_AUTHORIZATION_EFFECT,
        "empty_data_is_zero": classified.empty_data_is_zero,
    }
