"""Remaining productive execution-path census from permit issuance to terminal.

Read-only inventory. Does not GET, POST, flatten, issue a runtime permit,
open a network session, or set LIVE_AUTHORIZED. Atlas is not authority.
"""

from __future__ import annotations

from typing import Any, Mapping

PASS_OFFLINE_CONTRACT = "PASS_OFFLINE_CONTRACT"
START_NODE = "BOUNDED_RUNTIME_PERMIT_ISSUANCE"
TERMINAL_EXECUTION_ENDPOINT = "LIVE_FLATTEN_PROVABILITY_PROVEN"
TERMINAL_ENDPOINT_PROOF = (
    "POST https://eea.okx.com/api/v5/trade/order reduce-only LIMIT flatten of "
    "SUI-USD_UM_XPERP-310404 plus post-action PRE_POS!=0 then POS==0, PENDING empty, "
    "NO_FLIP (flatten_post_action_proof_contract_v1). HTTP 200 and OKX code=0 and "
    "sCode=0 are not flatten success. send_completed is not LIVE_FLATTEN_PROVABILITY."
)
TERMINAL_ENDPOINT_AUTHORITY_CLASS = "I_THEN_J"
SECTION_11_14_LADDER_ROLE = "SUBSEQUENT_LIVE_EVIDENCE_PROGRAM_NOT_CURRENT_FLATTEN_PATH_TERMINAL"

CENSUS_IMPLEMENTATION_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_REMAINING_EXECUTION_PATH_END_TO_END_CENSUS_MAXIMUM_SAFE_LEVERAGE_V1"
)


def _node(
    *,
    node_id: str,
    canonical_name: str,
    source_of_authority: str,
    semantic_role: str,
    current_status: str,
    producer: str,
    consumer: str,
    inputs: str,
    outputs: str,
    blocked_by: str,
    enables: str,
    fail_closed_behavior: str,
    offline_contract_proven: bool,
    offline_wiring_proven: bool,
    runtime_proven: bool,
    requires_network: bool,
    requires_dns_tls: bool,
    requires_credential_read: bool,
    requires_credential_use: bool,
    requires_public_get: bool,
    requires_private_get: bool,
    requires_post: bool,
    requires_order_submit: bool,
    requires_flatten_execute: bool,
    requires_permit: bool,
    requires_funding: bool,
    requires_live: bool,
    requires_canary: bool,
    authority_class: str,
    owner_go_required: bool,
    external_state_required: bool,
    can_be_prepared_offline: bool,
    can_be_bundled_with: str,
    implementation_paths: str,
    test_paths: str,
    evidence_paths: str,
    open_questions: str,
) -> dict[str, Any]:
    return {
        "NODE_ID": node_id,
        "CANONICAL_NAME": canonical_name,
        "SOURCE_OF_AUTHORITY": source_of_authority,
        "SEMANTIC_ROLE": semantic_role,
        "CURRENT_STATUS": current_status,
        "PRODUCER": producer,
        "CONSUMER": consumer,
        "INPUTS": inputs,
        "OUTPUTS": outputs,
        "BLOCKED_BY": blocked_by,
        "ENABLES": enables,
        "FAIL_CLOSED_BEHAVIOR": fail_closed_behavior,
        "OFFLINE_CONTRACT_PROVEN": offline_contract_proven,
        "OFFLINE_WIRING_PROVEN": offline_wiring_proven,
        "RUNTIME_PROVEN": runtime_proven,
        "REQUIRES_NETWORK": requires_network,
        "REQUIRES_DNS_TLS": requires_dns_tls,
        "REQUIRES_CREDENTIAL_READ": requires_credential_read,
        "REQUIRES_CREDENTIAL_USE": requires_credential_use,
        "REQUIRES_PUBLIC_GET": requires_public_get,
        "REQUIRES_PRIVATE_GET": requires_private_get,
        "REQUIRES_POST": requires_post,
        "REQUIRES_ORDER_SUBMIT": requires_order_submit,
        "REQUIRES_FLATTEN_EXECUTE": requires_flatten_execute,
        "REQUIRES_PERMIT": requires_permit,
        "REQUIRES_FUNDING": requires_funding,
        "REQUIRES_LIVE": requires_live,
        "REQUIRES_CANARY": requires_canary,
        "AUTHORITY_CLASS": authority_class,
        "OWNER_GO_REQUIRED": owner_go_required,
        "EXTERNAL_STATE_REQUIRED": external_state_required,
        "CAN_BE_PREPARED_OFFLINE": can_be_prepared_offline,
        "CAN_BE_BUNDLED_WITH": can_be_bundled_with,
        "IMPLEMENTATION_PATHS": implementation_paths,
        "TEST_PATHS": test_paths,
        "EVIDENCE_PATHS": evidence_paths,
        "OPEN_QUESTIONS": open_questions,
    }


def _edge(
    *,
    edge_from: str,
    edge_to: str,
    edge_type: str,
    proof: str,
    mandatory: str,
    fail_closed_if_missing: bool,
) -> dict[str, Any]:
    return {
        "EDGE_FROM": edge_from,
        "EDGE_TO": edge_to,
        "EDGE_TYPE": edge_type,
        "CANONICAL_OR_IMPLEMENTATION_PROOF": proof,
        "MANDATORY_OR_OPTIONAL": mandatory,
        "FAIL_CLOSED_IF_MISSING": fail_closed_if_missing,
    }


REMAINING_EXECUTION_PATH_NODES: tuple[dict[str, Any], ...] = (
    _node(
        node_id="N01",
        canonical_name="BOUNDED_RUNTIME_PERMIT_ISSUANCE",
        source_of_authority="§11.13.5 STPR remaining set; P16 issuance residual",
        semantic_role="Named residual: issuance contract for BoundedActivationPermitV1",
        current_status="CASE_B_OFFLINE_CONTRACT_THIS_PERSIST",
        producer="evaluate_bounded_runtime_permit_issuance_v1",
        consumer="evaluate_flatten_pre_send_gate_v1",
        inputs="STPR PASS; kind; purpose; owner_go; origin-main SHA; instrument; expiry",
        outputs="PASS_OFFLINE_CONTRACT; runtime issuance remains false",
        blocked_by="STPR predecessor",
        enables="Named remaining advances to runtime cluster",
        fail_closed_behavior="Deny runtime-issuance claims and implementation-GO as permit",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=True,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="F",
        owner_go_required=True,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N02;N03;N04;N05",
        implementation_paths="bounded_activation_permit_v1.py;bounded_runtime_permit_issuance_v1.py",
        test_paths="tests/ops/test_section_11_13_5_remaining_execution_path_end_to_end_census_v1.py",
        evidence_paths="evidence/ops/section_11_13_5_remaining_execution_path_end_to_end_census_v1/",
        open_questions="NONE",
    ),
    _node(
        node_id="N02",
        canonical_name="PERMIT_INPUT_SCHEMA",
        source_of_authority="P16 BoundedActivationPermitV1",
        semantic_role="Permit input contract",
        current_status="PASS_OFFLINE_CONTRACT",
        producer="BoundedActivationPermitV1",
        consumer="evaluate_bounded_activation_permit_v1",
        inputs="kind; purpose; owner_go; bound_origin_main_sha; instrument_id; not_after_monotonic_ms",
        outputs="typed permit object or deny reasons",
        blocked_by="NONE",
        enables="N01",
        fail_closed_behavior="Missing/malformed fields deny",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="A",
        owner_go_required=False,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N01",
        implementation_paths="bounded_activation_permit_v1.py",
        test_paths="tests/ops/test_section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.py",
        evidence_paths="evidence/ops/section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1/",
        open_questions="NONE",
    ),
    _node(
        node_id="N03",
        canonical_name="PERMIT_OUTPUT_SCHEMA",
        source_of_authority="P16 BoundedActivationPermitV1.to_dict",
        semantic_role="Permit output contract without runtime issuance",
        current_status="PASS_OFFLINE_CONTRACT",
        producer="offline_contract_proof_bounded_activation_permit_v1",
        consumer="bounded_activation_permit_audit_v1",
        inputs="N02",
        outputs="audit dict; accepted bool; deny reasons",
        blocked_by="N02",
        enables="N01",
        fail_closed_behavior="Fixture is not a productive runtime permit",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="A",
        owner_go_required=False,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N01",
        implementation_paths="bounded_activation_permit_v1.py",
        test_paths="tests/ops/test_section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.py",
        evidence_paths="evidence/ops/section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1/",
        open_questions="NONE",
    ),
    _node(
        node_id="N04",
        canonical_name="PERMIT_EXPIRY_AND_SHA_INSTRUMENT_BINDING",
        source_of_authority="P16 evaluate_bounded_activation_permit_v1",
        semantic_role="Expiry, origin-main SHA, and instrument binding",
        current_status="PASS_OFFLINE_CONTRACT",
        producer="evaluate_bounded_activation_permit_v1",
        consumer="evaluate_flatten_pre_send_gate_v1",
        inputs="permit; origin_main_sha; instrument_id; evaluation_monotonic_ms",
        outputs="accepted; deny reasons",
        blocked_by="N02",
        enables="pre-send BOUNDED_ACTIVATION_PERMIT gate",
        fail_closed_behavior="Expired/stale/wrong-instrument deny",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=True,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="A",
        owner_go_required=False,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N01",
        implementation_paths="bounded_activation_permit_v1.py;flatten_pre_send_gate_v1.py",
        test_paths="tests/ops/test_section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.py",
        evidence_paths="evidence/ops/section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1/",
        open_questions="Size/price/observation-identity binding not in proven P16 schema",
    ),
    _node(
        node_id="N05",
        canonical_name="FLATTEN_EXECUTE_AUTHORITY_CONTRACT",
        source_of_authority="flatten_execute_authority_v1.py; STPR remaining set",
        semantic_role="Confirm-token + purpose + owner-go evaluator",
        current_status="CASE_B_OFFLINE_CONTRACT_THIS_PERSIST",
        producer="evaluate_flatten_execute_authority_v1",
        consumer="evaluate_flatten_pre_send_gate_v1",
        inputs="token; purpose; owner_go",
        outputs="accepted; deny reasons; authorized remains false",
        blocked_by="N01 named residual close does not authorize execute",
        enables="Later runtime flatten-execute Owner-GO",
        fail_closed_behavior="Missing/wrong/forbidden GO deny; this census GO forbidden",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=True,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="I",
        owner_go_required=True,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N01 census persist; not bundled with POST",
        implementation_paths="flatten_execute_authority_v1.py",
        test_paths="tests/ops/test_section_11_13_5_z2cm_flatten_execute_post_action_wiring_v1.py",
        evidence_paths="NONE_SEPARATE_NAMED_PERSIST_BEFORE_THIS_CENSUS",
        open_questions="NONE",
    ),
    _node(
        node_id="N06",
        canonical_name="NETWORK_SESSION_GATE",
        source_of_authority="GatedProductiveFlattenTransportV1; STPR remaining set",
        semantic_role="Independent network-session flag; default false; never set true here",
        current_status="CASE_B_OFFLINE_CONTRACT_THIS_PERSIST",
        producer="GatedProductiveFlattenTransportV1; AuthenticatedGatedProductiveFlattenTransportV1",
        consumer="transport.send",
        inputs="network_session_authorized flag",
        outputs="PRODUCTIVE_NETWORK_SESSION_NOT_AUTHORIZED deny unless independently true",
        blocked_by="Owner-GO for actual session start",
        enables="Later urllib open only after independent true flag",
        fail_closed_behavior="Default false; this package never sets true",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=True,
        requires_dns_tls=True,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="E",
        owner_go_required=True,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N11 runtime read GO; not this persist runtime",
        implementation_paths="flatten_productive_transport_v1.py;authenticated_productive_transport_v1.py",
        test_paths="tests/ops/test_section_11_13_5_productive_flatten_wiring_v1.py",
        evidence_paths="NONE_SEPARATE_NAMED_PERSIST_BEFORE_THIS_CENSUS",
        open_questions="NONE",
    ),
    _node(
        node_id="N07",
        canonical_name="HMAC_HEADER_PRESENCE_AND_SIGNING_INPUT",
        source_of_authority="§11.13.5 AUTHENTICATED_PRODUCTIVE_TRANSPORT",
        semantic_role="OKX header presence + signing-input digest without secret",
        current_status="PASS_OFFLINE_CONTRACT",
        producer="assert_authenticated_productive_headers_v1; signing_input_digest_v1",
        consumer="AuthenticatedGatedProductiveFlattenTransportV1",
        inputs="headers; OkxSigningInputV1 prehash",
        outputs="presence doc; digest; wire still unauthorized",
        blocked_by="Credential use for real HMAC",
        enables="Authenticated send class",
        fail_closed_behavior="Unsigned headers deny; empty secret deny",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=True,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="A",
        owner_go_required=True,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N11 runtime HMAC",
        implementation_paths="authenticated_productive_transport_v1.py;okx_live_canary_signer_v1.py",
        test_paths="tests/ops/test_section_11_13_5_authenticated_productive_transport_v1.py",
        evidence_paths="evidence/ops/section_11_13_5_authenticated_productive_transport_v1/",
        open_questions="Unsigned GatedProductiveFlattenTransportV1 remains a parallel opener class",
    ),
    _node(
        node_id="N08",
        canonical_name="FLATTEN_PAYLOAD_AND_PRE_SEND_GATE",
        source_of_authority="P13; flatten_pre_send_gate_v1 GATE_NAMES",
        semantic_role="Exact flatten body + independent pre-send predicates",
        current_status="PASS_OFFLINE_CONTRACT",
        producer="build_canary_flatten_submit_request_v1; evaluate_flatten_pre_send_gate_v1",
        consumer="FlattenGatedSubmitBoundaryV1",
        inputs="permit; plan; price_permit; positions; pending; freshness",
        outputs="receipt; approved request identity; allowed is not venue proof",
        blocked_by="Any gate deny",
        enables="N12 send boundary",
        fail_closed_behavior="Generic allow flag never sufficient",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=True,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="G",
        owner_go_required=False,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N01 census",
        implementation_paths="flatten_pre_send_gate_v1.py;flatten_submit_transport_v1.py",
        test_paths="tests/ops/test_section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1.py",
        evidence_paths="evidence/ops/section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1/",
        open_questions="NONE",
    ),
    _node(
        node_id="N09",
        canonical_name="RESPONSE_PARSER_AND_POST_ACTION_CONTRACT",
        source_of_authority="flatten_gated_submit_v1; flatten_post_submit_evidence_state_v1; flatten_post_action_proof_contract_v1",
        semantic_role="Offline response/reconciliation classifiers",
        current_status="PASS_OFFLINE_CONTRACT",
        producer="_venue_acceptance_from_response; evaluate_canary_flatten_post_action_proof_contract_v1",
        consumer="LIVE_FLATTEN_PROVABILITY remaining runtime",
        inputs="HTTP response; pre/post positions; pending",
        outputs="venue_acceptance_proven; evidence_state; position_closed_contract; productive_venue_proof=false",
        blocked_by="Runtime POST and post-exec GET",
        enables="Terminal proof definition",
        fail_closed_behavior="HTTP 200 not success; injected snapshots not venue proof",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="J",
        owner_go_required=False,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N01 census",
        implementation_paths="flatten_gated_submit_v1.py;flatten_post_submit_evidence_state_v1.py;flatten_post_action_proof_contract_v1.py",
        test_paths="tests/ops/test_section_11_13_5_flatten_post_action_proof_contract_v1.py",
        evidence_paths="NONE",
        open_questions="NONE",
    ),
    _node(
        node_id="N10",
        canonical_name="KILL_SWITCH_AND_FAIL_CLOSED_LIFECYCLE",
        source_of_authority="lifecycle_v1.py; cybersecurity_canary_gate_v1.py",
        semantic_role="Halt/cancel/flatten-path interaction; no new entry while halted",
        current_status="PASS_OFFLINE_CONTRACT",
        producer="lifecycle_v1; cybersecurity_canary_gate_v1",
        consumer="orchestration failure matrix",
        inputs="halt; kill switch; unknown submit",
        outputs="NO_NEW_ENTRY_WHILE_HALTED; no blind retry",
        blocked_by="NONE for offline contract",
        enables="Fail-closed terminals",
        fail_closed_behavior="Unknown/timeout/duplicate do not retry",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="A",
        owner_go_required=False,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="N01 census",
        implementation_paths="lifecycle_v1.py;flatten_orchestration_contract_v1.py",
        test_paths="tests/ops/test_section_11_13_5_live_flatten_offline_lifecycle_failure_matrix_v1.py",
        evidence_paths="NONE",
        open_questions="NONE",
    ),
    _node(
        node_id="N11",
        canonical_name="AUTHENTICATED_PRIVATE_RUNTIME_READ",
        source_of_authority="STPR intended GET /api/v5/account/positions; pending orders for open-order gate",
        semantic_role="First runtime network+credential+private GET cluster",
        current_status="UNAUTHORIZED_REMAINING",
        producer="later Owner-GO session",
        consumer="STPR runtime; permit binding; open-order gate",
        inputs="network session; credentials; DNS/TLS",
        outputs="fresh positions and pending payloads inside 5000 ms window",
        blocked_by="N06 runtime session; credential use GO",
        enables="N12; N13; N14",
        fail_closed_behavior="No GET without scoped Owner-GO",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=True,
        requires_dns_tls=True,
        requires_credential_read=True,
        requires_credential_use=True,
        requires_public_get=False,
        requires_private_get=True,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="D",
        owner_go_required=True,
        external_state_required=True,
        can_be_prepared_offline=False,
        can_be_bundled_with="N13 runtime permit issuance in same session",
        implementation_paths="send_time_position_reobservation_v1.py names endpoint not invoked",
        test_paths="tests/ops/test_section_11_13_5_send_time_position_reobservation_v1.py",
        evidence_paths="NONE_RUNTIME",
        open_questions="Exact pending-orders endpoint for open-order gate at send time",
    ),
    _node(
        node_id="N12",
        canonical_name="PRODUCTIVE_FLATTEN_POST_AND_WIRE",
        source_of_authority="ENDPOINT_SUBMIT; FlattenGatedSubmitBoundaryV1",
        semantic_role="Authenticated POST /api/v5/trade/order reduce-only LIMIT flatten",
        current_status="UNAUTHORIZED_REMAINING",
        producer="AuthenticatedGatedProductiveFlattenTransportV1 after session+headers",
        consumer="venue; response parser",
        inputs="N05 token; N06 session; N07 HMAC; N08 receipt; N01 runtime permit",
        outputs="HTTP response; send_completed is not flatten proof",
        blocked_by="All prior runtime nodes",
        enables="N14; N15",
        fail_closed_behavior="Fake transport cannot masquerade; one-shot; no retry",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=True,
        requires_dns_tls=True,
        requires_credential_read=True,
        requires_credential_use=True,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=True,
        requires_order_submit=True,
        requires_flatten_execute=True,
        requires_permit=True,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="H",
        owner_go_required=True,
        external_state_required=True,
        can_be_prepared_offline=False,
        can_be_bundled_with="N05 runtime token supply; N14 recon GET in same session",
        implementation_paths="flatten_gated_submit_v1.py;flatten_productive_transport_v1.py",
        test_paths="tests/ops/test_section_11_13_5_productive_flatten_wiring_v1.py",
        evidence_paths="NONE_RUNTIME",
        open_questions="NONE",
    ),
    _node(
        node_id="N13",
        canonical_name="RUNTIME_PERMIT_ISSUANCE",
        source_of_authority="P16 later-send residual; this persist CASE_B is not issuance",
        semantic_role="Actually issue BoundedActivationPermitV1 bound to current SHA/time/instrument",
        current_status="UNAUTHORIZED_REMAINING",
        producer="later Owner-GO",
        consumer="pre-send BOUNDED_ACTIVATION_PERMIT gate",
        inputs="N11 fresh observation optional; origin-main SHA; monotonic expiry",
        outputs="runtime permit object",
        blocked_by="N01 CASE_B does not issue",
        enables="N12 send allow",
        fail_closed_behavior="Implementation GOs cannot satisfy permit",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=True,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="F",
        owner_go_required=True,
        external_state_required=False,
        can_be_prepared_offline=False,
        can_be_bundled_with="N11 same session",
        implementation_paths="bounded_activation_permit_v1.py",
        test_paths="tests/ops/test_section_11_13_5_remaining_execution_path_end_to_end_census_v1.py",
        evidence_paths="NONE_RUNTIME",
        open_questions="Whether issuance must bind observation identity (not in P16 schema)",
    ),
    _node(
        node_id="N14",
        canonical_name="POST_EXECUTION_RECONCILIATION_GET",
        source_of_authority="flatten_post_action_proof_contract_v1 productive sequence",
        semantic_role="Private GET after wire for POS==0 proof",
        current_status="UNAUTHORIZED_REMAINING",
        producer="later Owner-GO GET",
        consumer="LIVE_FLATTEN_PROVABILITY",
        inputs="post positions; post pending; causal submit binding",
        outputs="POSITION_CLOSED_PROVEN only with productive venue proof",
        blocked_by="N12 wire",
        enables="N15",
        fail_closed_behavior="Same GET cannot dual-use pre-send and post-readback",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=True,
        requires_dns_tls=True,
        requires_credential_read=True,
        requires_credential_use=True,
        requires_public_get=False,
        requires_private_get=True,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="J",
        owner_go_required=True,
        external_state_required=True,
        can_be_prepared_offline=False,
        can_be_bundled_with="N12 same session",
        implementation_paths="flatten_post_action_proof_contract_v1.py",
        test_paths="tests/ops/test_section_11_13_5_flatten_post_action_proof_contract_v1.py",
        evidence_paths="NONE_RUNTIME",
        open_questions="NONE",
    ),
    _node(
        node_id="N15",
        canonical_name="LIVE_FLATTEN_PROVABILITY_PROVEN",
        source_of_authority="LIVE_FLATTEN_PROVABILITY_STATUS; §11.13.5 canary flatten closeout",
        semantic_role="Terminal productive success of current remaining flatten path",
        current_status="UNPROVEN_TERMINAL",
        producer="productive venue + post-action proof",
        consumer="LIVE_CANARY_MINIMUM_EXPOSURE_PROVEN; not §11.14",
        inputs="N12 venue acceptance AND N14 POS==0",
        outputs="LIVE_FLATTEN_PROVABILITY=PROVEN",
        blocked_by="N12; N14",
        enables="Section 11.13.5 flatten closeout; §11.14 is subsequent program",
        fail_closed_behavior="Remains UNPROVEN without productive venue proof",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=True,
        requires_dns_tls=True,
        requires_credential_read=True,
        requires_credential_use=True,
        requires_public_get=False,
        requires_private_get=True,
        requires_post=True,
        requires_order_submit=True,
        requires_flatten_execute=True,
        requires_permit=True,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="I",
        owner_go_required=True,
        external_state_required=True,
        can_be_prepared_offline=False,
        can_be_bundled_with="N12;N14",
        implementation_paths="flatten_limit_price_contract_v1.py LIVE_FLATTEN_PROVABILITY_STATUS",
        test_paths="tests/ops/test_section_11_13_5_live_flatten_offline_permit_orchestration_v1.py",
        evidence_paths="NONE_RUNTIME",
        open_questions="NONE",
    ),
    _node(
        node_id="N16",
        canonical_name="FUNDING_AND_GLOBAL_LIVE_OR_CANARY_ACTIVATION",
        source_of_authority="P08 CASE_A existing position; P16 bounded activation",
        semantic_role="Not on current flatten-existing-position path",
        current_status="NOT_REQUIRED_FOR_CURRENT_FLATTEN_PATH",
        producer="NONE_THIS_PATH",
        consumer="NONE_THIS_PATH",
        inputs="NONE",
        outputs="LIVE_AUTHORIZED remains false; FUNDING not required to flatten existing pos",
        blocked_by="N/A",
        enables="NONE",
        fail_closed_behavior="Global LIVE cannot substitute for bounded permit",
        offline_contract_proven=True,
        offline_wiring_proven=True,
        runtime_proven=False,
        requires_network=False,
        requires_dns_tls=False,
        requires_credential_read=False,
        requires_credential_use=False,
        requires_public_get=False,
        requires_private_get=False,
        requires_post=False,
        requires_order_submit=False,
        requires_flatten_execute=False,
        requires_permit=False,
        requires_funding=False,
        requires_live=False,
        requires_canary=False,
        authority_class="K",
        owner_go_required=False,
        external_state_required=False,
        can_be_prepared_offline=True,
        can_be_bundled_with="NONE",
        implementation_paths="bounded_activation_permit_v1.py;constants_v1.py",
        test_paths="tests/ops/test_section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.py",
        evidence_paths="NONE",
        open_questions="NONE",
    ),
    _node(
        node_id="N17",
        canonical_name="SECTION_11_14_LIVE_EVIDENCE_LADDER",
        source_of_authority="Master Runbook §11.14",
        semantic_role="Subsequent live evidence program after canary flatten proven",
        current_status="NOT_CURRENT_PATH_TERMINAL",
        producer="later Live program",
        consumer="LIVE_END_TO_END_EVIDENCE_PROVEN",
        inputs="LIVE_FLATTEN_PROVABILITY_PROVEN then fill/fee/recon/restart ladder",
        outputs="LIVE_END_TO_END_EVIDENCE_PROVEN",
        blocked_by="N15",
        enables="Broader live program",
        fail_closed_behavior="No Testnet/fixture may satisfy Live evidence fields",
        offline_contract_proven=False,
        offline_wiring_proven=False,
        runtime_proven=False,
        requires_network=True,
        requires_dns_tls=True,
        requires_credential_read=True,
        requires_credential_use=True,
        requires_public_get=False,
        requires_private_get=True,
        requires_post=True,
        requires_order_submit=True,
        requires_flatten_execute=True,
        requires_permit=True,
        requires_funding=False,
        requires_live=True,
        requires_canary=False,
        authority_class="J",
        owner_go_required=True,
        external_state_required=True,
        can_be_prepared_offline=False,
        can_be_bundled_with="NONE_THIS_PATH",
        implementation_paths="docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md §11.14",
        test_paths="NONE",
        evidence_paths="NONE",
        open_questions="Not traversed as current flatten-path terminal",
    ),
)

REMAINING_EXECUTION_PATH_EDGES: tuple[dict[str, Any], ...] = (
    _edge(
        edge_from="N02",
        edge_to="N01",
        edge_type="ENABLES",
        proof="P16 schema is issuance input",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N03",
        edge_to="N01",
        edge_type="ENABLES",
        proof="P16 output schema",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N04",
        edge_to="N01",
        edge_type="ENABLES",
        proof="expiry/SHA/instrument evaluator",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N01",
        edge_to="N13",
        edge_type="BLOCKED_BY",
        proof="CASE_B contract does not issue runtime permit",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N05",
        edge_to="N12",
        edge_type="ENABLES",
        proof="confirm token required at send",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N06",
        edge_to="N11",
        edge_type="ENABLES",
        proof="session flag independent of permit",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N06",
        edge_to="N12",
        edge_type="ENABLES",
        proof="urllib opens only if session authorized",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N07",
        edge_to="N12",
        edge_type="ENABLES",
        proof="authenticated transport requires HMAC headers",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N08",
        edge_to="N12",
        edge_type="ENABLES",
        proof="gated submit requires passing receipt",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N11",
        edge_to="N13",
        edge_type="ENABLES",
        proof="fresh observation may bind permit expiry window",
        mandatory="OPTIONAL",
        fail_closed_if_missing=False,
    ),
    _edge(
        edge_from="N11",
        edge_to="N08",
        edge_type="ENABLES",
        proof="send-time positions and pending for pre-send",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N13",
        edge_to="N08",
        edge_type="ENABLES",
        proof="pre-send requires bounded activation permit object",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N12",
        edge_to="N09",
        edge_type="ENABLES",
        proof="parser consumes HTTP response",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N12",
        edge_to="N14",
        edge_type="ENABLES",
        proof="post-action requires causal submit binding",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N09",
        edge_to="N15",
        edge_type="ENABLES",
        proof="venue acceptance necessary not sufficient",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N14",
        edge_to="N15",
        edge_type="ENABLES",
        proof="POS==0 required for LIVE_FLATTEN_PROVABILITY",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N15",
        edge_to="N17",
        edge_type="ENABLES",
        proof="§11.14 subsequent after flatten proven",
        mandatory="OPTIONAL",
        fail_closed_if_missing=False,
    ),
    _edge(
        edge_from="N10",
        edge_to="N12",
        edge_type="FAIL_CLOSED",
        proof="kill switch / unknown submit deny send",
        mandatory="MANDATORY",
        fail_closed_if_missing=True,
    ),
    _edge(
        edge_from="N16",
        edge_to="N12",
        edge_type="NON_EDGE",
        proof="funding and global LIVE not required for flatten-existing-position",
        mandatory="OPTIONAL",
        fail_closed_if_missing=False,
    ),
)

LATENT_GAPS: tuple[dict[str, Any], ...] = (
    {
        "GAP_ID": "G01",
        "NODE": "N01",
        "DESCRIPTION": "Named residual BOUNDED_RUNTIME_PERMIT_ISSUANCE lacked CASE_B persist",
        "OFFLINE_OR_RUNTIME": "OFFLINE",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": True,
        "REQUIRES_NEW_AUTHORITY": False,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": False,
        "CLOSED_THIS_PERSIST": True,
    },
    {
        "GAP_ID": "G02",
        "NODE": "N05",
        "DESCRIPTION": "FLATTEN_EXECUTE confirm-token contract existed but was not CASE_B persisted",
        "OFFLINE_OR_RUNTIME": "OFFLINE",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": True,
        "REQUIRES_NEW_AUTHORITY": False,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": False,
        "CLOSED_THIS_PERSIST": True,
    },
    {
        "GAP_ID": "G03",
        "NODE": "N06",
        "DESCRIPTION": "NETWORK_SESSION default-deny gate existed but was not CASE_B persisted",
        "OFFLINE_OR_RUNTIME": "OFFLINE",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": True,
        "REQUIRES_NEW_AUTHORITY": False,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": False,
        "CLOSED_THIS_PERSIST": True,
    },
    {
        "GAP_ID": "G04",
        "NODE": "CENSUS",
        "DESCRIPTION": "Full remaining-path DAG was not canonically persisted",
        "OFFLINE_OR_RUNTIME": "OFFLINE",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": True,
        "REQUIRES_NEW_AUTHORITY": False,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": False,
        "CLOSED_THIS_PERSIST": True,
    },
    {
        "GAP_ID": "G05",
        "NODE": "N07",
        "DESCRIPTION": "Unsigned GatedProductiveFlattenTransportV1 can urllib if session flag flipped",
        "OFFLINE_OR_RUNTIME": "OFFLINE",
        "CANONICAL_OR_IMPLEMENTATION": "IMPLEMENTATION",
        "BLOCKING_OR_NONBLOCKING": "NONBLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": True,
        "REQUIRES_NEW_AUTHORITY": False,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": False,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G06",
        "NODE": "N04",
        "DESCRIPTION": "Permit schema does not bind size/price/observation identity",
        "OFFLINE_OR_RUNTIME": "OFFLINE",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "NONBLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G07",
        "NODE": "N11",
        "DESCRIPTION": "Send-time private GET not performed; STPR_RUNTIME_PROVEN=false",
        "OFFLINE_OR_RUNTIME": "RUNTIME",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": True,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G08",
        "NODE": "N13",
        "DESCRIPTION": "Runtime permit not issued",
        "OFFLINE_OR_RUNTIME": "RUNTIME",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G09",
        "NODE": "N06",
        "DESCRIPTION": "Network session not authorized; credentials not used",
        "OFFLINE_OR_RUNTIME": "RUNTIME",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": False,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G10",
        "NODE": "N12",
        "DESCRIPTION": "Productive flatten POST not authorized",
        "OFFLINE_OR_RUNTIME": "RUNTIME",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": True,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G11",
        "NODE": "N14",
        "DESCRIPTION": "Post-exec reconciliation GET not authorized",
        "OFFLINE_OR_RUNTIME": "RUNTIME",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": True,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G12",
        "NODE": "N15",
        "DESCRIPTION": "LIVE_FLATTEN_PROVABILITY remains UNPROVEN",
        "OFFLINE_OR_RUNTIME": "RUNTIME",
        "CANONICAL_OR_IMPLEMENTATION": "CANONICAL",
        "BLOCKING_OR_NONBLOCKING": "BLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": True,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
    {
        "GAP_ID": "G13",
        "NODE": "N11",
        "DESCRIPTION": "Open-order pending payload producer at send time not named as a dedicated GET Owner-GO",
        "OFFLINE_OR_RUNTIME": "RUNTIME",
        "CANONICAL_OR_IMPLEMENTATION": "IMPLEMENTATION",
        "BLOCKING_OR_NONBLOCKING": "NONBLOCKING",
        "KNOWN_NOW": True,
        "FIXABLE_UNDER_CURRENT_GO": False,
        "REQUIRES_NEW_AUTHORITY": True,
        "REQUIRES_EXTERNAL_STATE": True,
        "REQUIRES_OWNER_DECISION": True,
        "CLOSED_THIS_PERSIST": False,
    },
)

NAMED_REMAINING_AFTER_CENSUS: tuple[str, ...] = (
    "AUTHENTICATED_PRIVATE_RUNTIME_READ",
    "RUNTIME_PERMIT_ISSUANCE",
    "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION",
)
NAMED_REMAINING_AFTER_CENSUS_SET = frozenset(NAMED_REMAINING_AFTER_CENSUS)

AUTHORITY_MATRIX_ROWS: tuple[dict[str, str], ...] = (
    {
        "OPERATION": "NETWORK_SESSION",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N06",
        "AUTHORITY_CLASS": "E",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G09",
    },
    {
        "OPERATION": "DNS_TLS",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N11",
        "AUTHORITY_CLASS": "E",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G07",
    },
    {
        "OPERATION": "CREDENTIAL_READ",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N11",
        "AUTHORITY_CLASS": "D",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "false",
        "CURRENT_BLOCKER": "G07",
    },
    {
        "OPERATION": "CREDENTIAL_USE",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N11",
        "AUTHORITY_CLASS": "E",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "false",
        "CURRENT_BLOCKER": "G07",
    },
    {
        "OPERATION": "PUBLIC_GET",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "false",
        "FIRST_NODE_REQUIRING_IT": "NONE",
        "AUTHORITY_CLASS": "C",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "false",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "NOT_ON_CURRENT_FLATTEN_PATH",
    },
    {
        "OPERATION": "PRIVATE_GET",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N11",
        "AUTHORITY_CLASS": "D",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "false",
        "CURRENT_BLOCKER": "G07",
    },
    {
        "OPERATION": "POSITION_GET",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N11",
        "AUTHORITY_CLASS": "D",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "false",
        "CURRENT_BLOCKER": "G07",
    },
    {
        "OPERATION": "AUTH_HEADERS",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N07",
        "AUTHORITY_CLASS": "A",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G07",
    },
    {
        "OPERATION": "HMAC_SIGN",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N07",
        "AUTHORITY_CLASS": "E",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G07",
    },
    {
        "OPERATION": "PERMIT_ISSUANCE",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N13",
        "AUTHORITY_CLASS": "F",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G08",
    },
    {
        "OPERATION": "POST",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N12",
        "AUTHORITY_CLASS": "H",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "false",
        "CURRENT_BLOCKER": "G10",
    },
    {
        "OPERATION": "ORDER_SUBMIT",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N12",
        "AUTHORITY_CLASS": "I",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "false",
        "CURRENT_BLOCKER": "G10",
    },
    {
        "OPERATION": "FLATTEN_EXECUTE",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N05",
        "AUTHORITY_CLASS": "I",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G10",
    },
    {
        "OPERATION": "RESPONSE_READ",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N09",
        "AUTHORITY_CLASS": "J",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G10",
    },
    {
        "OPERATION": "POST_EXEC_RECONCILIATION",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N14",
        "AUTHORITY_CLASS": "J",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "G11",
    },
    {
        "OPERATION": "FUNDING",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "false",
        "FIRST_NODE_REQUIRING_IT": "N16",
        "AUTHORITY_CLASS": "K",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "false",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "NOT_ON_CURRENT_FLATTEN_PATH",
    },
    {
        "OPERATION": "ACCOUNT_MUTATION",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "true",
        "FIRST_NODE_REQUIRING_IT": "N12",
        "AUTHORITY_CLASS": "I",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "true",
        "CAN_PREPARE_OFFLINE_NOW": "false",
        "CURRENT_BLOCKER": "G10",
    },
    {
        "OPERATION": "LIVE_ACTIVATION",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "false",
        "FIRST_NODE_REQUIRING_IT": "N16",
        "AUTHORITY_CLASS": "L",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "false",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "NOT_REQUIRED_BOUNDED_ACTIVATION_PATH",
    },
    {
        "OPERATION": "CANARY_ACTIVATION",
        "REQUIRED_SOMEWHERE_DOWNSTREAM": "false",
        "FIRST_NODE_REQUIRING_IT": "N16",
        "AUTHORITY_CLASS": "L",
        "CURRENTLY_AUTHORIZED": "false",
        "SEPARATE_OWNER_GO_REQUIRED": "false",
        "CAN_PREPARE_OFFLINE_NOW": "true",
        "CURRENT_BLOCKER": "NOT_REQUIRED_BOUNDED_ACTIVATION_PATH",
    },
)


def remaining_execution_path_census_summary_v1() -> dict[str, Any]:
    nodes = list(REMAINING_EXECUTION_PATH_NODES)
    edges = list(REMAINING_EXECUTION_PATH_EDGES)
    gaps = list(LATENT_GAPS)
    class_counts: dict[str, int] = {}
    for node in nodes:
        klass = str(node["AUTHORITY_CLASS"])
        class_counts[klass] = class_counts.get(klass, 0) + 1
    closed = [g for g in gaps if g.get("CLOSED_THIS_PERSIST") is True]
    remaining = [g for g in gaps if g.get("CLOSED_THIS_PERSIST") is not True]
    offline_closed = [g for g in closed if g.get("OFFLINE_OR_RUNTIME") == "OFFLINE"]
    offline_remaining = [g for g in remaining if g.get("OFFLINE_OR_RUNTIME") == "OFFLINE"]
    runtime_remaining = [g for g in remaining if g.get("OFFLINE_OR_RUNTIME") == "RUNTIME"]
    owner_remaining = [g for g in remaining if g.get("REQUIRES_OWNER_DECISION") is True]
    external_remaining = [g for g in remaining if g.get("REQUIRES_EXTERNAL_STATE") is True]
    return {
        "START_NODE": START_NODE,
        "TERMINAL_EXECUTION_ENDPOINT": TERMINAL_EXECUTION_ENDPOINT,
        "TERMINAL_ENDPOINT_PROOF": TERMINAL_ENDPOINT_PROOF,
        "TERMINAL_ENDPOINT_AUTHORITY_CLASS": TERMINAL_ENDPOINT_AUTHORITY_CLASS,
        "SECTION_11_14_LADDER_ROLE": SECTION_11_14_LADDER_ROLE,
        "TOTAL_REMAINING_NODE_COUNT": len(nodes),
        "TOTAL_EDGE_COUNT": len(edges),
        "TOTAL_KNOWN_GAP_COUNT": len(gaps),
        "AUTHORITY_CLASS_COUNTS": class_counts,
        "LATENT_OFFLINE_GAPS_BEFORE_WORK": 6,
        "LATENT_OFFLINE_GAPS_CLOSED": len(offline_closed),
        "LATENT_OFFLINE_GAPS_REMAINING": len(offline_remaining),
        "RUNTIME_GAPS_REMAINING": len(runtime_remaining),
        "EXTERNAL_STATE_GAPS_REMAINING": len(external_remaining),
        "OWNER_DECISIONS_REMAINING": len(owner_remaining),
        "NAMED_REMAINING_AFTER_CENSUS": list(NAMED_REMAINING_AFTER_CENSUS),
        "NODES": nodes,
        "EDGES": edges,
        "GAPS": gaps,
        "AUTHORITY_MATRIX": list(AUTHORITY_MATRIX_ROWS),
    }


def assert_census_exhaustion_v1() -> None:
    summary = remaining_execution_path_census_summary_v1()
    if int(summary["TOTAL_REMAINING_NODE_COUNT"]) != 17:
        raise RuntimeError("CENSUS_NODE_COUNT_DRIFT")
    if int(summary["TOTAL_EDGE_COUNT"]) != 19:
        raise RuntimeError("CENSUS_EDGE_COUNT_DRIFT")
    if int(summary["TOTAL_KNOWN_GAP_COUNT"]) != 13:
        raise RuntimeError("CENSUS_GAP_COUNT_DRIFT")
    names = {str(n["CANONICAL_NAME"]) for n in summary["NODES"]}
    if START_NODE not in names or TERMINAL_EXECUTION_ENDPOINT not in {
        str(n["CANONICAL_NAME"]) for n in summary["NODES"]
    }:
        if "LIVE_FLATTEN_PROVABILITY_PROVEN" not in names:
            raise RuntimeError("CENSUS_TERMINAL_MISSING")


def assert_runtime_claims_not_true_v1(payload: Mapping[str, Any]) -> None:
    if payload.get("BOUNDED_RUNTIME_PERMIT_ISSUANCE_RUNTIME_PROVEN") is True:
        raise RuntimeError("RUNTIME_PERMIT_ISSUANCE_CLAIMED")
    if payload.get("FLATTEN_EXECUTE_AUTHORIZED") is True:
        raise RuntimeError("FLATTEN_EXECUTE_CLAIMED")
    if payload.get("NETWORK_SESSION_AUTHORIZED") is True:
        raise RuntimeError("NETWORK_SESSION_CLAIMED")
    if payload.get("LIVE_AUTHORIZED") is True:
        raise RuntimeError("LIVE_AUTHORIZED_CLAIMED")
    if payload.get("POST_PERFORMED") is True:
        raise RuntimeError("POST_CLAIMED")
    if payload.get("GET_PERFORMED_THIS_PERSIST") is True:
        raise RuntimeError("GET_CLAIMED")
