"""Constants for CURRENT MF N=5 Full-Autonomy occupied-lane bound ingest join.

S1 binds contract and authority only. The S2 ingest function is named, not
implemented.
"""

from __future__ import annotations

from src.ops.current_mf_n5_boundary_occupied_lane_cap24_n1_bind_join_v1.constants_v1 import (
    HOST_JOIN as BOUNDARY_HOST_JOIN,
    OWNER as BOUNDARY_BIND_JOIN_OWNER_VALUE,
    PREPARED_BOUND_CARDINALITY as BOUNDARY_PREPARED_BOUND_CARDINALITY,
    PRODUCTIVE_RUNTIME_CARDINALITY as BOUNDARY_PRODUCTIVE_RUNTIME_CARDINALITY,
)
from src.ops.current_mf_n5_isolated_lane_instance_topology_v1.constants_v1 import (
    CROSS_UNIVERSE_CANDIDATE_BORROWING as TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK as TOPOLOGY_CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN as TOPOLOGY_CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT as TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING as TOPOLOGY_CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION as TOPOLOGY_CROSS_UNIVERSE_SELECTION,
    FIVE_LANE_RUNTIME_CREATED as TOPOLOGY_FIVE_LANE_RUNTIME_CREATED,
    INSTRUMENT_ID_ALONE_SUFFICIENT as TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT,
    LANE_MAPPING_OWNER as TOPOLOGY_LANE_MAPPING_OWNER,
    MAX_POSITIONS_EFFECTIVE as TOPOLOGY_MAX_POSITIONS_EFFECTIVE,
    MF_PRODUCTIVE_JOIN as TOPOLOGY_MF_PRODUCTIVE_JOIN,
    MULTI_UNIVERSE_MERGE as TOPOLOGY_MULTI_UNIVERSE_MERGE,
)
from src.ops.current_mf_n5_occupied_lane_pin_consumer_join_v1.constants_v1 import (
    FIVE_LANE_CONTINUOUS_HOST_JOIN as PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN,
)
from src.ops.ranking_universe_to_full_core_ssf_handoff_contract_v1 import (
    FIRST_TRADING_DECISION_CONSUMER as HANDOFF_FIRST_TRADING_DECISION_CONSUMER,
    FULL_CORE_INGEST_OBJECT as HANDOFF_FULL_CORE_INGEST_OBJECT,
    LAST_RANKING_UNIVERSE_AUTHORITY as HANDOFF_LAST_RANKING_UNIVERSE_AUTHORITY,
)
from src.ops.single_selected_future_policy_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP23_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP23_OWNER_VALUE,
)
from src.ops.single_selected_future_runtime_binding_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP24_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP24_OWNER_VALUE,
    RUNTIME_ACTIVATION_ALLOWED as CAP24_RUNTIME_ACTIVATION_ALLOWED,
)

OWNER = "ops.current_mf_n5_full_autonomy_occupied_lane_bound_ingest_join_v1"
CONTRACT_ID = "CURRENT_MF_N5_FULL_AUTONOMY_OCCUPIED_LANE_BOUND_INGEST_JOIN_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_n5_full_autonomy_occupied_lane_bound_ingest_join.v1"
SLICE_ID = "S1_CONTRACT_BIND"
OWNER_GO_THIS_SLICE = (
    "OWNER_GO_CURRENT_MF_N5_FULL_AUTONOMY_OCCUPIED_LANE_BOUND_INGEST_JOIN_V1_S1_CONTRACT_BIND"
)

LANE_MAPPING_OWNER = TOPOLOGY_LANE_MAPPING_OWNER
CAP23_SELECTION_OWNER = CAP23_OWNER_VALUE
CAP24_BINDING_OWNER = CAP24_OWNER_VALUE
BOUNDARY_BIND_JOIN_OWNER = BOUNDARY_BIND_JOIN_OWNER_VALUE
FULL_AUTONOMY_HOST_OWNER = "stateful_no_order_host_join_v1"
FULL_CORE_LIVE_PATH_AUTHORITY = "full_core_live_path_authority_v1"

MAP_CONSUMER_ROLE = "FULL_AUTONOMY_INGEST"
MAP_CONSUMER_OWNER = OWNER
MAP_PRODUCER_OWNER = BOUNDARY_BIND_JOIN_OWNER
INGEST_INPUT_PRODUCER = "bind_occupied_lane_cap24_n1_instruments_v1"
INGEST_INPUT_OBJECT = "dict[lane_id, BoundInstrumentV1]"
INGEST_VALUE_TYPE_NAME = HANDOFF_FULL_CORE_INGEST_OBJECT
SLOT_IDENTITY = "lane_id"
SLOT_STATE_ROOT_RESOLVER = "lane_state_root_for"
LAST_RANKING_UNIVERSE_AUTHORITY = HANDOFF_LAST_RANKING_UNIVERSE_AUTHORITY
FIRST_TRADING_DECISION_CONSUMER = HANDOFF_FIRST_TRADING_DECISION_CONSUMER
S2_JOIN_SYMBOL = "admit_occupied_lane_bound_instruments_v1"
S2_IMPLEMENTED = False

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
JOIN_SELECTION_AUTHORITY = False
JOIN_CAP23_SELECTION_AUTHORITY = False
JOIN_CAP24_BINDING_AUTHORITY = False
JOIN_TRADING_AUTHORITY = False
JOIN_RUNTIME_ACTIVATION_AUTHORITY = False
JOIN_EXECUTION_AUTHORITY = False
JOIN_RANKING_AUTHORITY = False
JOIN_MEMBERSHIP_AUTHORITY = False
JOIN_MAPPING_AUTHORITY = False
JOIN_PERSISTENCE_AUTHORITY = False
JOIN_FULL_AUTONOMY_HOST_AUTHORITY = False
PARALLEL_AUTHORITY_CREATED = False
PICK_ONE_AMONG_PREPARED_BOUNDS = False
IDENTITY_PRESERVING_INGEST = True
THIS_SLICE_MAY_INVOKE_FIRST_TRADING_DECISION_CONSUMER = False
THIS_SLICE_MAY_REINVOKE_CAP23 = False
THIS_SLICE_MAY_REINVOKE_CAP24 = False
NEW_COLLECTION_DTO_CREATED = False
NEW_TOP5_HANDOFF_DTO_CREATED = False
NEW_MULTI_BOUND_AUTHORITY_DTO_CREATED = False

CROSS_UNIVERSE_SELECTION = TOPOLOGY_CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = TOPOLOGY_CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = TOPOLOGY_CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = TOPOLOGY_CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = TOPOLOGY_MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT
UNIVERSE_ISOLATION = "HARD"
UNIVERSE_ISOLATION_ENFORCED = True

MF_PRODUCTIVE_JOIN = TOPOLOGY_MF_PRODUCTIVE_JOIN
FIVE_LANE_RUNTIME_CREATED = TOPOLOGY_FIVE_LANE_RUNTIME_CREATED
FIVE_LANE_CONTINUOUS_HOST_JOIN = PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = False
MF_SINGLE_EGRESS_REWIRED = False
MAX_POSITIONS_EFFECTIVE = int(TOPOLOGY_MAX_POSITIONS_EFFECTIVE)
MULTI_FUTURE_RUNTIME_AUTHORIZED = bool(CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED)
PREPARED_BOUND_CARDINALITY = BOUNDARY_PREPARED_BOUND_CARDINALITY
PRODUCTIVE_RUNTIME_CARDINALITY = BOUNDARY_PRODUCTIVE_RUNTIME_CARDINALITY

assert HOST_JOIN is False
assert BOUNDARY_HOST_JOIN is False
assert MAX_POSITIONS_EFFECTIVE == int(CAP23_MAX_POSITIONS_EFFECTIVE)
assert MAX_POSITIONS_EFFECTIVE == int(CAP24_MAX_POSITIONS_EFFECTIVE) == 1
assert MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_RUNTIME_ACTIVATION_ALLOWED is False
assert MF_PRODUCTIVE_JOIN is False
assert FIVE_LANE_RUNTIME_CREATED is False
assert FIVE_LANE_CONTINUOUS_HOST_JOIN is False
assert PARALLEL_AUTHORITY_CREATED is False
assert JOIN_SELECTION_AUTHORITY is False
assert JOIN_CAP23_SELECTION_AUTHORITY is False
assert JOIN_CAP24_BINDING_AUTHORITY is False
assert JOIN_TRADING_AUTHORITY is False
assert JOIN_RUNTIME_ACTIVATION_AUTHORITY is False
assert JOIN_RANKING_AUTHORITY is False
assert JOIN_FULL_AUTONOMY_HOST_AUTHORITY is False
assert PICK_ONE_AMONG_PREPARED_BOUNDS is False
assert IDENTITY_PRESERVING_INGEST is True
assert S2_IMPLEMENTED is False
assert NEW_COLLECTION_DTO_CREATED is False
assert NEW_TOP5_HANDOFF_DTO_CREATED is False
assert NEW_MULTI_BOUND_AUTHORITY_DTO_CREATED is False
assert PREPARED_BOUND_CARDINALITY == "0..5"
assert PRODUCTIVE_RUNTIME_CARDINALITY == "1_UNJOINED"
assert INGEST_VALUE_TYPE_NAME == "BoundInstrumentV1"
assert CAP23_SELECTION_OWNER == "ops.single_selected_future_policy_v1"
assert CAP24_BINDING_OWNER == "ops.single_selected_future_runtime_binding_v1"
assert MAP_CONSUMER_OWNER == OWNER
assert MAP_PRODUCER_OWNER == "ops.current_mf_n5_boundary_occupied_lane_cap24_n1_bind_join_v1"

CAP23_CHANGE_REQUIRED = False
CAP24_CHANGE_REQUIRED = False
MASTER_V2_CHANGE_REQUIRED = False
DOUBLE_PLAY_CHANGE_REQUIRED = False
FULL_AUTONOMY_HOST_CHANGE_REQUIRED = False

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "produce_occupied_lane_cap23_n1_selections_v1",
        "run_single_selected_future_policy_v1",
        "produce_single_selected_future_v1",
        "produce_from_ranking_state_root_v1",
        "persist_selection_bundle_atomic_v1",
        "_pick_top_eligible",
        "run_single_selected_future_runtime_binding_gate_v1",
        "ensure_single_selected_future_runtime_binding_v1",
        "persist_binding_evidence_atomic_v1",
        "run_current_productive_master_v2_runtime_cycle_v1",
        "compose_core_live_execution_intent_v1",
        "mf_canonical_single_egress_authority_handoff_contract_v1",
        "master_v2",
        "double_play",
        "execution",
        "top_n_active_set",
        "LiveExecutionPort",
    }
)
