"""Failure / reason codes for Cap 5.1 deterministic offline evidence."""

from __future__ import annotations

from enum import Enum


class OfflineEvidenceFailureCodeV1(str, Enum):
    MISSING_RUNTIME_TRUTH = "MISSING_RUNTIME_TRUTH"
    STALE_RUNTIME_TRUTH = "STALE_RUNTIME_TRUTH"
    CONFIG_MISMATCH = "CONFIG_MISMATCH"
    FIXTURE_INVALID = "FIXTURE_INVALID"
    FIXTURE_DIGEST_MISMATCH = "FIXTURE_DIGEST_MISMATCH"
    MISSING_SELECTION = "MISSING_SELECTION"
    STALE_SELECTION = "STALE_SELECTION"
    SELECTION_DIGEST_MISMATCH = "SELECTION_DIGEST_MISMATCH"
    MISSING_MARK_PRICE = "MISSING_MARK_PRICE"
    MISSING_TYPED_VOLATILITY = "MISSING_TYPED_VOLATILITY"
    STALE_MARKET_DATA = "STALE_MARKET_DATA"
    DUPLICATE_OBSERVATION = "DUPLICATE_OBSERVATION"
    MISSING_OBSERVATION = "MISSING_OBSERVATION"
    INVALID_CONTRACT_METADATA = "INVALID_CONTRACT_METADATA"
    CORRUPTED_PORTFOLIO_CHECKPOINT = "CORRUPTED_PORTFOLIO_CHECKPOINT"
    CORRUPTED_RISK_CHECKPOINT = "CORRUPTED_RISK_CHECKPOINT"
    ACCOUNTING_PERSISTENCE_FAILURE = "ACCOUNTING_PERSISTENCE_FAILURE"
    VERIFIER_MISMATCH = "VERIFIER_MISMATCH"
    NON_DETERMINISTIC_REPLAY = "NON_DETERMINISTIC_REPLAY"
    RESTART_MISMATCH = "RESTART_MISMATCH"
    CALL_GRAPH_INCOMPLETE = "CALL_GRAPH_INCOMPLETE"
    PREDECESSOR_CAPABILITY_MISSING = "PREDECESSOR_CAPABILITY_MISSING"
    GATE_FLAG_FALSE = "GATE_FLAG_FALSE"
    AUTHORIZATION_CONSUMPTION_ATTEMPTED = "AUTHORIZATION_CONSUMPTION_ATTEMPTED"
    NETWORK_SESSION_STARTED = "NETWORK_SESSION_STARTED"
    NETWORK_ACCESS_ATTEMPTED = "NETWORK_ACCESS_ATTEMPTED"
    RUNTIME_ACTIVATION_ATTEMPTED = "RUNTIME_ACTIVATION_ATTEMPTED"
    FORBIDDEN_STATUS = "FORBIDDEN_STATUS"
    LIVE_ORDER_PATH_REACHABLE = "LIVE_ORDER_PATH_REACHABLE"
    TESTNET_ORDER_PATH_REACHABLE = "TESTNET_ORDER_PATH_REACHABLE"
    MULTI_FUTURE_ENABLED = "MULTI_FUTURE_ENABLED"
    NUMERIC_MAX_AGE_ENFORCEMENT_ENABLED = "NUMERIC_MAX_AGE_ENFORCEMENT_ENABLED"
    PARALLEL_LEGACY_AUTHORITY = "PARALLEL_LEGACY_AUTHORITY"
    SESSION_LOCK_CONFLICT = "SESSION_LOCK_CONFLICT"
    CORE_LOGIC_CHANGED = "CORE_LOGIC_CHANGED"
    HARD_STOP = "HARD_STOP"


ALL_FAILURE_CODES = frozenset(code.value for code in OfflineEvidenceFailureCodeV1)
