"""Constants for CAPABILITY_11_12 Fully autonomous Live readiness ratification."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_11_12_FULLY_AUTONOMOUS_LIVE_READINESS_RATIFICATION_V1"
PACKAGE_MARKER = "CAPABILITY_11_12_FULLY_AUTONOMOUS_LIVE_READINESS_RATIFICATION_V1=true"
OWNER = "ops.capability_11_12_fully_autonomous_live_readiness_ratification_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "capability_11_12_fully_autonomous_live_readiness_ratification.v1"
PRODUCER_VERSION = "capability_11_12_fully_autonomous_live_readiness_ratification.v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID_11_1 = "CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1"
PREDECESSOR_OWNER_11_1 = "ops.capability_11_1_execution_domain_and_order_lifecycle_contracts_v1"
PREDECESSOR_CAPABILITY_ID_11_2 = (
    "CAPABILITY_11_2_CREDENTIAL_AUTHORIZATION_AND_ACCOUNT_IDENTITY_BOUNDARY_V1"
)
PREDECESSOR_OWNER_11_2 = (
    "ops.capability_11_2_credential_authorization_and_account_identity_boundary_v1"
)
PREDECESSOR_CAPABILITY_ID_11_3 = (
    "CAPABILITY_11_3_PRIVATE_READONLY_VENUE_INTEGRATION_AND_RECONCILIATION_V1"
)
PREDECESSOR_OWNER_11_3 = (
    "ops.capability_11_3_private_readonly_venue_integration_and_reconciliation_v1"
)
PREDECESSOR_CAPABILITY_ID_11_4 = (
    "CAPABILITY_11_4_TESTNET_EXECUTION_ADAPTER_AND_LIFECYCLE_CLOSURE_V1"
)
PREDECESSOR_OWNER_11_4 = "ops.capability_11_4_testnet_execution_adapter_and_lifecycle_closure_v1"
PREDECESSOR_CAPABILITY_ID_11_5 = (
    "CAPABILITY_11_5_TESTNET_RESTART_RECOVERY_AND_KILL_SWITCH_CLOSURE_V1"
)
PREDECESSOR_OWNER_11_5 = "ops.capability_11_5_testnet_restart_recovery_and_kill_switch_closure_v1"
PREDECESSOR_CAPABILITY_ID_11_6 = "CAPABILITY_11_6_LONG_RUNNING_AUTONOMOUS_TESTNET_EVIDENCE_V1"
PREDECESSOR_OWNER_11_6 = "ops.capability_11_6_long_running_autonomous_testnet_evidence_v1"
PREDECESSOR_CAPABILITY_ID_11_7 = (
    "CAPABILITY_11_7_LIVE_PRIVATE_READONLY_AND_SHADOW_RECONCILIATION_V1"
)
PREDECESSOR_OWNER_11_7 = "ops.capability_11_7_live_private_readonly_and_shadow_reconciliation_v1"
PREDECESSOR_CAPABILITY_ID_11_8 = "CAPABILITY_11_8_LIVE_DRY_RUN_ORDER_PLAN_PARITY_V1"
PREDECESSOR_OWNER_11_8 = "ops.capability_11_8_live_dry_run_order_plan_parity_v1"
PREDECESSOR_CAPABILITY_ID_11_9 = "CAPABILITY_11_9_LIVE_CANARY_ORDER_EXECUTION_V1"
PREDECESSOR_OWNER_11_9 = "ops.capability_11_9_live_canary_order_execution_v1"
PREDECESSOR_CAPABILITY_ID_11_10 = "CAPABILITY_11_10_LIVE_BOUNDED_SINGLE_FUTURE_CONTINUITY_V1"
PREDECESSOR_OWNER_11_10 = "ops.capability_11_10_live_bounded_single_future_continuity_v1"
PREDECESSOR_CAPABILITY_ID_11_11 = (
    "CAPABILITY_11_11_LIVE_AUTONOMOUS_RECOVERY_AND_DEGRADATION_EVIDENCE_V1"
)
PREDECESSOR_OWNER_11_11 = (
    "ops.capability_11_11_live_autonomous_recovery_and_degradation_evidence_v1"
)

# Hard safety bindings (contracts/scaffolding only; non-authorizing).
CORE_LOGIC_CHANGE = False
CORE_LOGIC_CHANGE_ALLOWED = False
ACTIVATION_STATE = "not_activated"
ACTIVATION_CHANGED = False
RUNTIME_ACTIVATED = False
LIVE_TRADING_ALLOWED = False
TESTNET_ALLOWED = False
PAPER_EXCHANGE_ORDERS_ALLOWED = False
EXCHANGE_CREDENTIAL_USE_ALLOWED = False
REAL_CAPITAL_MOVEMENT_ALLOWED = False
NETWORK_SESSION_ALLOWED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
RULESET_MUTATION_ALLOWED = False
NOTION_MUTATION_ALLOWED = False

TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False
EXCHANGE_CREDENTIAL_USE_AUTHORIZED = False
REAL_CAPITAL_MOVEMENT_AUTHORIZED = False
OWNER_GO_REQUIRED_FOR_EACH_ACTIVATION = True

LIVE_PATH_CHANGED = False
TESTNET_PATH_CHANGED = False
ORDER_PATH_CHANGED = False
EXCHANGE_CREDENTIAL_PATH_CHANGED = False
NETWORK_SESSION_STARTED = False
PRIVATE_NETWORK_SESSION_STARTED = False

VOLATILITY_NUMERIC_MAX_AGE_ENFORCING = False
NUMERIC_MAX_AGE_EFFECT = "DIAGNOSTIC_ONLY"
DASHBOARD_AUTHORITY_EFFECT = "NONE"

# Cap 11.1–11.11 retention (must not be weakened / activated).
CAPABILITY_11_1_FAIL_CLOSED_RETAINED = True
CAPABILITY_11_1_IDEMPOTENCY_RETAINED = True
CAPABILITY_11_1_UNKNOWN_SEMANTICS_RETAINED = True
CAPABILITY_11_1_LIFECYCLE_RETAINED = True
CAPABILITY_11_1_AUDIT_CONTRACTS_RETAINED = True
CAPABILITY_11_1_ANTI_CORRUPTION_RETAINED = True
CAPABILITY_11_1_JOURNALING_RETAINED = True

CAPABILITY_11_2_CREDENTIAL_BOUNDARY_RETAINED = True
CAPABILITY_11_2_AUTHORIZATION_BOUNDARY_RETAINED = True
CAPABILITY_11_2_ACCOUNT_IDENTITY_BOUNDARY_RETAINED = True
CAPABILITY_11_2_NO_CREDENTIAL_LOAD_RETAINED = True
CAPABILITY_11_2_NO_AUTH_CONSUMPTION_RETAINED = True

CAPABILITY_11_3_PRIVATE_READONLY_BOUNDARY_RETAINED = True
CAPABILITY_11_3_RECONCILIATION_HIERARCHY_RETAINED = True
CAPABILITY_11_3_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_3_NO_NETWORK_FETCH_RETAINED = True
CAPABILITY_11_3_NO_CREDENTIAL_LOAD_RETAINED = True

CAPABILITY_11_4_TESTNET_ADAPTER_BOUNDARY_RETAINED = True
CAPABILITY_11_4_LIFECYCLE_CLOSURE_RETAINED = True
CAPABILITY_11_4_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_4_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_4_NO_NETWORK_SESSION_RETAINED = True

CAPABILITY_11_5_RESTART_RECOVERY_KILL_SWITCH_RETAINED = True
CAPABILITY_11_5_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_5_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_5_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_5_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_6_LONG_RUNNING_EVIDENCE_RETAINED = True
CAPABILITY_11_6_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_6_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_6_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_6_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_7_LIVE_PRIVATE_READONLY_RETAINED = True
CAPABILITY_11_7_SHADOW_RECONCILIATION_RETAINED = True
CAPABILITY_11_7_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_7_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_7_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_7_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_8_LIVE_DRY_RUN_ORDER_PLAN_RETAINED = True
CAPABILITY_11_8_ORDER_PLAN_PARITY_RETAINED = True
CAPABILITY_11_8_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_8_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_8_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_8_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_9_LIVE_CANARY_ORDER_EXECUTION_RETAINED = True
CAPABILITY_11_9_MINIMUM_EXPOSURE_RETAINED = True
CAPABILITY_11_9_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_9_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_9_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_9_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_10_LIVE_BOUNDED_SINGLE_FUTURE_CONTINUITY_RETAINED = True
CAPABILITY_11_10_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_10_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_10_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_10_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_11_LIVE_AUTONOMOUS_RECOVERY_AND_DEGRADATION_RETAINED = True
CAPABILITY_11_11_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_11_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_11_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_11_NO_PROVEN_CLAIMS_RETAINED = True

# Reachability claims for Cap 11.12 (contracts only — no Live readiness activation).
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
EXCHANGE_CREDENTIAL_ACCESS_REACHABLE = False
REAL_CAPITAL_MOVEMENT_REACHABLE = False
PRIVATE_READONLY_NETWORK_REACHABLE = False
PRIVATE_READONLY_VENUE_INTEGRATION_ACTIVATED = False
CREDENTIAL_PLAINTEXT_LOADED = False
CREDENTIAL_LOAD_PERFORMED_IN_CAPABILITY_11_12 = False
TESTNET_EXECUTION_ADAPTER_ACTIVATED = False
TESTNET_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_12 = False
TESTNET_NETWORK_SESSION_STARTED_IN_CAPABILITY_11_12 = False
LIVE_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_12 = False
PAPER_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_12 = False
LIVE_ORDER_EXECUTION_PERFORMED_IN_CAPABILITY_11_12 = False

# Cap 11.12 contract surface claims (bound, not activated, not ready-overclaimed).
AUTONOMY_CLOSURE_STANDARD_FIELD_CONTRACT_BOUND = True
AUTONOMY_CLOSURE_STANDARD_FIELD_CONTRACT_ACTIVATED = False
FULLY_AUTONOMOUS_LIVE_READINESS_RATIFICATION_CONTRACT_BOUND = True
FULLY_AUTONOMOUS_LIVE_READINESS_RATIFICATION_CONTRACT_ACTIVATED = False
FULLY_AUTONOMOUS_LIVE_READINESS_RATIFICATION_FIXTURE_ONLY = True
CAPABILITY_11_12_STARTED = True
CAPABILITY_11_12_FULLY_AUTONOMOUS_LIVE_READINESS_STARTED = True

# Cap 11.12 does NOT claim readiness or activation (§11.17 / §11.18 / §11.19 Cap 11.13).
# Predecessor Cap 11.1–11.11 remain contracts-only; §11.17 proven fields stay false.
FULLY_AUTONOMOUS_LIVE_TRADING_READY = False
FULLY_AUTONOMOUS_LIVE_TRADING_ACTIVE = False
LIVE_AUTHORIZATION_VALID = False
OWNER_LIVE_GO = False
LIVE_ACTIVATION_CAPABILITY_PASS = False
CAPABILITY_11_13_STARTED = False
CAPABILITY_11_13_SEPARATE_OWNER_AUTHORIZED_LIVE_ACTIVATION_STARTED = False

# §11.17 Autonomy closure standard fields — contract-bound; not proven in Cap 11.12.
CANONICAL_STATEFUL_CORE_PROVEN = False
SIMULATED_LIFECYCLE_PROVEN = False
TESTNET_LIFECYCLE_PROVEN = False
LIVE_PRIVATE_READ_ONLY_PROVEN = False
LIVE_ORDER_LIFECYCLE_PROVEN = False
LIVE_RECONCILIATION_PROVEN = False
LIVE_RESTART_PROVEN = False
LIVE_UNKNOWN_SUBMIT_RECOVERY_PROVEN = False
LIVE_DUPLICATE_ORDER_PREVENTION_PROVEN = False
LIVE_PARTIAL_FILL_RECOVERY_PROVEN = False
LIVE_KILL_SWITCH_PROVEN = False
LIVE_AUTONOMOUS_DEGRADATION_PROVEN = False
LIVE_AUTONOMOUS_RECOVERY_PROVEN = False
LIVE_ACCOUNTING_RECONSTRUCTION_PROVEN = False
LIVE_EVIDENCE_VERIFIED = False
OWNER_INTERVENTION_REQUIRED_FOR_ROUTINE_OPERATION = True
OWNER_INTERVENTION_REQUIRED_FOR_SCOPE_OR_LIMIT_CHANGE = True
CORE_LOGIC_PARITY_ACROSS_MODES = True

# §11.17 readiness prerequisite fields that must be True for READY=true.
AUTONOMY_CLOSURE_REQUIRED_TRUE_FIELDS: tuple[str, ...] = (
    "CANONICAL_STATEFUL_CORE_PROVEN",
    "SIMULATED_LIFECYCLE_PROVEN",
    "TESTNET_LIFECYCLE_PROVEN",
    "LIVE_PRIVATE_READ_ONLY_PROVEN",
    "LIVE_ORDER_LIFECYCLE_PROVEN",
    "LIVE_RECONCILIATION_PROVEN",
    "LIVE_RESTART_PROVEN",
    "LIVE_UNKNOWN_SUBMIT_RECOVERY_PROVEN",
    "LIVE_DUPLICATE_ORDER_PREVENTION_PROVEN",
    "LIVE_PARTIAL_FILL_RECOVERY_PROVEN",
    "LIVE_KILL_SWITCH_PROVEN",
    "LIVE_AUTONOMOUS_DEGRADATION_PROVEN",
    "LIVE_AUTONOMOUS_RECOVERY_PROVEN",
    "LIVE_ACCOUNTING_RECONSTRUCTION_PROVEN",
    "LIVE_EVIDENCE_VERIFIED",
    "OWNER_INTERVENTION_REQUIRED_FOR_SCOPE_OR_LIMIT_CHANGE",
    "CORE_LOGIC_PARITY_ACROSS_MODES",
)

# §11.17 readiness prerequisite fields that must be False for READY=true.
AUTONOMY_CLOSURE_REQUIRED_FALSE_FIELDS: tuple[str, ...] = (
    "OWNER_INTERVENTION_REQUIRED_FOR_ROUTINE_OPERATION",
)

# All §11.17 field names owned by Cap 11.12 ratification surface.
AUTONOMY_CLOSURE_STANDARD_FIELDS: tuple[str, ...] = (
    *AUTONOMY_CLOSURE_REQUIRED_TRUE_FIELDS,
    *AUTONOMY_CLOSURE_REQUIRED_FALSE_FIELDS,
    "FULLY_AUTONOMOUS_LIVE_TRADING_READY",
)

# §11.18 final operating-contract claims remain Cap 11.13+ only.
FINAL_AUTONOMOUS_LIVE_OPERATING_FORBIDDEN_FIELDS: tuple[str, ...] = (
    "FULLY_AUTONOMOUS_LIVE_TRADING_ACTIVE",
    "LIVE_EXECUTION_ACTIVE",
    "AUTONOMOUS_RECONCILIATION_ACTIVE",
    "AUTONOMOUS_RECOVERY_ACTIVE",
)

AUTONOMY_CLOSURE_STANDARD_FIELD_OWNER = OWNER
FULLY_AUTONOMOUS_LIVE_READINESS_RATIFICATION_OWNER = OWNER

EVIDENCE_DIRNAME = "capability_11_12_fully_autonomous_live_readiness_ratification_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
