"""Machine-readable failure and exclusion reason codes for Economic-MD input."""

from __future__ import annotations

from enum import Enum


class EconomicMdFailureCodeV1(str, Enum):
    UNIVERSE_SNAPSHOT_MISSING = "UNIVERSE_SNAPSHOT_MISSING"
    UNIVERSE_SNAPSHOT_INVALID = "UNIVERSE_SNAPSHOT_INVALID"
    UNIVERSE_SCHEMA_MISMATCH = "UNIVERSE_SCHEMA_MISMATCH"
    UNIVERSE_CAPABILITY_MISMATCH = "UNIVERSE_CAPABILITY_MISMATCH"
    CAP21_INELIGIBLE_INSTRUMENT = "CAP21_INELIGIBLE_INSTRUMENT"
    INSTRUMENT_NOT_IN_CAP21_ELIGIBLE_SET = "INSTRUMENT_NOT_IN_CAP21_ELIGIBLE_SET"
    INSUFFICIENT_FINALIZED_PT1M_MARKS = "INSUFFICIENT_FINALIZED_PT1M_MARKS"
    MISSING_MARK_BAR_NO_IMPLICIT_FILL = "MISSING_MARK_BAR_NO_IMPLICIT_FILL"
    NON_FINALIZED_MARK = "NON_FINALIZED_MARK"
    INVALID_MARK_PRICE = "INVALID_MARK_PRICE"
    MISSING_BIDPX = "MISSING_BIDPX"
    MISSING_ASKPX = "MISSING_ASKPX"
    NON_POSITIVE_BIDPX = "NON_POSITIVE_BIDPX"
    NON_POSITIVE_ASKPX = "NON_POSITIVE_ASKPX"
    CROSSED_MARKET_BID_GT_ASK = "CROSSED_MARKET_BID_GT_ASK"
    PROVENANCE_DIGEST_UNAVAILABLE = "PROVENANCE_DIGEST_UNAVAILABLE"
    PUBLIC_MD_SOURCE_UNAVAILABLE = "PUBLIC_MD_SOURCE_UNAVAILABLE"
    MALFORMED_PUBLIC_MD_PAYLOAD = "MALFORMED_PUBLIC_MD_PAYLOAD"
    FORBIDDEN_NETWORK_PATH = "FORBIDDEN_NETWORK_PATH"
    AUTH_HEADER_FORBIDDEN = "AUTH_HEADER_FORBIDDEN"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    PERSISTENCE_WRITE_FAILURE = "PERSISTENCE_WRITE_FAILURE"
    PARTIAL_WRITE = "PARTIAL_WRITE"
    CORRUPT_PERSISTED_SNAPSHOT = "CORRUPT_PERSISTED_SNAPSHOT"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    DUPLICATE_PRODUCER_WRITER = "DUPLICATE_PRODUCER_WRITER"
    DASHBOARD_INPUT_FORBIDDEN = "DASHBOARD_INPUT_FORBIDDEN"
    RANKING_OUTPUT_FORBIDDEN = "RANKING_OUTPUT_FORBIDDEN"
    NETWORK_READ_ON_REPLAY_FORBIDDEN = "NETWORK_READ_ON_REPLAY_FORBIDDEN"


ALL_FAILURE_CODES: frozenset[str] = frozenset(code.value for code in EconomicMdFailureCodeV1)
