"""Owner-adjudicated Master V2 minimal selector constants (policy V1).

OWNER_POLICY_VERSION=V1
HISTORICAL_CLAIM=false

This package is a new Owner policy surface. It does not rewrite Cap 2.1 GFU
eligibility, Cap 2.2 ranking authority, Cap 2.3 stickiness/ranking selection,
or Cap 2.4 ranking-gated binding.
"""

from __future__ import annotations

OWNER_SELECTOR_POLICY_VERSION = "V1"
HISTORICAL_CLAIM = False
OWNER_POLICY_CLASS = "OWNER_NEW_POLICY"

CAPABILITY_ID = "MASTER_V2_MINIMAL_SELECTOR_V1"
SCHEMA_VERSION = "master_v2_minimal_selector_decision.v1"
PRODUCER_VERSION = "master_v2_minimal_selector.v1"
PACKAGE_MARKER = "MASTER_V2_MINIMAL_SELECTOR_V1=true"
OWNER = "ops.master_v2_minimal_selector_v1"
AUTHORITY_OWNER = OWNER
POLICY_ID = "master_v2_minimal_selector_policy_v1"

VENUE = "OKX_EEA"
VENUE_DISCOVERY = "okx_eea"
VENUE_ALIASES = frozenset({"OKX_EEA", "okx_eea", "OKX-EEA", "okx-eea"})

D1_INSTRUMENT_CLASS = "PERP_SWAP_ONLY"
D1_CLASS = OWNER_POLICY_CLASS
D1_HISTORICAL_CLAIM = False

D2_BTC_OR_BASE_EXCLUSION = "NO_ASSET_EXCLUDE"
D2_CLASS = OWNER_POLICY_CLASS
D2_HISTORICAL_CLAIM = False

D3_MULTI_ELIGIBLE_RESOLUTION = "FAIL_CLOSED_UNLESS_EXACTLY_ONE"
D3_CLASS = OWNER_POLICY_CLASS
D3_HISTORICAL_CLAIM = False

D4_SELECTION_REFRESH_MODE = "EXPLICIT_CONTROL_PLANE_TRIGGER_ONLY"
D4_CLASS = OWNER_POLICY_CLASS
D4_HISTORICAL_CLAIM = False

SELECTED_COUNT = 1
NO_CANDIDATE_POLICY = "NO_SELECTION"
STALE_SELECTION_POLICY = "FAIL_CLOSED"
NO_IMPLICIT_FALLBACK_INSTRUMENT = True
NO_HOT_PATH_RESCAN = True

RANKING_POLICY_REQUIRED_NOW = False
CAP22_SELECTION_AUTHORITY_ALLOWED = False
CAP22_ROLE = "CONTEXT_ONLY_OR_UNUSED"
CAP22_SELECTION_AUTHORITY = False
CURRENT_GFU_SEMANTIC_IMPORT_ALLOWED = False

# Authority inventory — selector has none of these.
SELECTOR_HAS_TRADING_AUTHORITY = False
SELECTOR_HAS_POSITION_SIZING_AUTHORITY = False
SELECTOR_HAS_LEVERAGE_AUTHORITY = False
SELECTOR_HAS_DOUBLE_PLAY_SIDE_AUTHORITY = False
ALPHA_AUTHORITY_ADDED = False
EXECUTION_AUTHORITY_ADDED = False
DASHBOARD_AUTHORITY = False
RUNTIME_ACTIVATION_ALLOWED = False
LIVE_AUTHORIZED = False
ORDERS_AUTHORIZED = False
TESTNET_AUTHORIZED = False
CANARY_SUBMIT_AUTHORIZED = False
MULTI_FUTURE_RUNTIME_AUTHORIZED = False
MANUAL_OVERRIDE_ALLOWED = False
ALLOWLIST_SELECTION_AUTHORITY = False

STATUS_SELECTED = "SELECTED"
STATUS_NO_SELECTION = "NO_SELECTION"

REASON_SELECTED_EXACTLY_ONE = "SELECTED_EXACTLY_ONE"
REASON_NO_SELECTION_ZERO_ELIGIBLE = "NO_SELECTION_ZERO_ELIGIBLE"
REASON_NO_SELECTION_MULTIPLE_ELIGIBLE = "NO_SELECTION_MULTIPLE_ELIGIBLE"
REASON_NO_SELECTION_STALE_OR_INVALID_SOURCE = "NO_SELECTION_STALE_OR_INVALID_SOURCE"
REASON_NO_SELECTION_INCOMPLETE_SOURCE = "NO_SELECTION_INCOMPLETE_SOURCE"
REASON_NO_SELECTION_OVERRIDE_REJECTED = "NO_SELECTION_OVERRIDE_REJECTED"

DECISION_REASONS = frozenset(
    {
        REASON_SELECTED_EXACTLY_ONE,
        REASON_NO_SELECTION_ZERO_ELIGIBLE,
        REASON_NO_SELECTION_MULTIPLE_ELIGIBLE,
        REASON_NO_SELECTION_STALE_OR_INVALID_SOURCE,
        REASON_NO_SELECTION_INCOMPLETE_SOURCE,
        REASON_NO_SELECTION_OVERRIDE_REJECTED,
    }
)

ACTIVE_TRADING_STATE = "live"
INSTRUMENT_TYPE_SWAP = "SWAP"
INSTRUMENT_TYPE_SPOT = "SPOT"
INSTRUMENT_TYPE_FUTURES = "FUTURES"

EMPTY_EXPIRY_TOKENS = frozenset({"", "0", "None", "null", "NONE", "NULL", "none"})

SELECTION_FILENAME = "master_v2_minimal_selector_decision_v1.json"
MANIFEST_FILENAME = "MANIFEST.sha256"

CALL_GRAPH = (
    "okx_eea_census_discovery",
    "master_v2_structural_eligibility_v1",
    "exactly_one_or_no_selection_v1",
    "durable_selected_future_artifact",
    "narrowed_runtime_binding_adapter",
)

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "ranking_as_selection_authority",
        "hot_path_rescan",
        "automatic_refresh",
        "implicit_fallback_instrument",
        "asset_allowlist_selector",
        "asset_denylist_selector",
        "live_orders",
        "execution",
        "position_sizing",
        "leverage",
        "double_play_side",
        "dashboard_authority",
    }
)
