"""Constants for the offline Core→Live composition root.

Standing Live gates remain false. This package never arms wire send.
"""

from __future__ import annotations

from src.ops.governed_productive_account_equity_authority_producer_v1.constants_v1 import (
    ACCOUNT_EQUITY_AUTHORITY_OWNER as ACCOUNT_EQUITY_AUTHORITY_OWNER,
    ACCOUNT_EQUITY_AUTHORITY_OWNER_CLASS as ACCOUNT_EQUITY_AUTHORITY_OWNER_CLASS,
    EQUITY_DIMENSION_BOUND as EQUITY_DIMENSION_BOUND,
    GOVERNED_PRODUCER_CREATED as GOVERNED_PRODUCER_CREATED,
    GOVERNED_PRODUCTIVE_SOURCE_PRESENT as GOVERNED_PRODUCTIVE_SOURCE_PRESENT,
    GOVERNED_RUNNING_ACCOUNT_EQUITY_SAMPLE_SCHEMA_PRESENT as GOVERNED_RUNNING_ACCOUNT_EQUITY_SAMPLE_SCHEMA_PRESENT,
    MAPPED_TO_RUNNING_ACCOUNT_EQUITY_AVAILABLE_FOR_SIZING as MAPPED_TO_RUNNING_ACCOUNT_EQUITY_AVAILABLE_FOR_SIZING,
    OBSERVATION_AUTHORITY_EFFECT as OBSERVATION_AUTHORITY_EFFECT,
    OWNER_ASSIGNMENT_RATIFIED as OWNER_ASSIGNMENT_RATIFIED,
    RAW_TO_WITNESS_PROVEN as RAW_TO_WITNESS_PROVEN,
    SOURCE_OBJECT_PRESENT as SOURCE_OBJECT_PRESENT,
    SOURCE_OBJECT_PRESENT_SEMANTICS as SOURCE_OBJECT_PRESENT_SEMANTICS,
    SOURCE_SELECTED as SOURCE_SELECTED,
    VENUE_WITNESS_RUNTIME_INSTANCE_PRESENT as VENUE_WITNESS_RUNTIME_INSTANCE_PRESENT,
    VENUE_WITNESS_SCHEMA_PRESENT as VENUE_WITNESS_SCHEMA_PRESENT,
    VENUE_WITNESS_SELECTED as VENUE_WITNESS_SELECTED,
    WITNESS_CONTRACT_MISSING_CLOSED as WITNESS_CONTRACT_MISSING_CLOSED,
    NORMALIZATION_SCHEMA_PRESENT as NORMALIZATION_SCHEMA_PRESENT,
    NORMALIZATION_RUNTIME_INSTANCE_PRESENT as NORMALIZATION_RUNTIME_INSTANCE_PRESENT,
    NORMALIZATION_CONTRACT_MISSING_CLOSED as NORMALIZATION_CONTRACT_MISSING_CLOSED,
    NORMALIZATION_AUTHORITY_EFFECT as NORMALIZATION_AUTHORITY_EFFECT,
    FIELD_TO_DIMENSION_MAPPING_SCHEMA_PRESENT as FIELD_TO_DIMENSION_MAPPING_SCHEMA_PRESENT,
    FIELD_TO_DIMENSION_MAPPING_PRESENT as FIELD_TO_DIMENSION_MAPPING_PRESENT,
    SEMANTIC_MAPPING_PROVEN as SEMANTIC_MAPPING_PROVEN,
    INCLUSION_PROVEN as INCLUSION_PROVEN,
    INTERNAL_RECONSTRUCTION_CREATED as INTERNAL_RECONSTRUCTION_CREATED,
    INTERNAL_RECONSTRUCTION_SCHEMA_PRESENT as INTERNAL_RECONSTRUCTION_SCHEMA_PRESENT,
    INTERNAL_RECONSTRUCTION_RUNTIME_INSTANCE_PRESENT as INTERNAL_RECONSTRUCTION_RUNTIME_INSTANCE_PRESENT,
    INTERNAL_RECONSTRUCTION_CONTRACT_MISSING_CLOSED as INTERNAL_RECONSTRUCTION_CONTRACT_MISSING_CLOSED,
    INTERNAL_RECONSTRUCTION_PROVEN as INTERNAL_RECONSTRUCTION_PROVEN,
    INTERNAL_RECONSTRUCTION_AUTHORITY_EFFECT as INTERNAL_RECONSTRUCTION_AUTHORITY_EFFECT,
    RECONSTRUCTION_ALGEBRA_SCHEMA_PRESENT as RECONSTRUCTION_ALGEBRA_SCHEMA_PRESENT,
    RECONSTRUCTION_ALGEBRA_AUTHORITY_EFFECT as RECONSTRUCTION_ALGEBRA_AUTHORITY_EFFECT,
    RECONSTRUCTION_ALGEBRA_COMPLETE as RECONSTRUCTION_ALGEBRA_COMPLETE,
    P01_TERM_CONTRACT_SCHEMA_PRESENT as P01_TERM_CONTRACT_SCHEMA_PRESENT,
    P01_TERM_CONTRACT_RUNTIME_INSTANCE_PRESENT as P01_TERM_CONTRACT_RUNTIME_INSTANCE_PRESENT,
    P01_TERM_CONTRACT_AUTHORITY_EFFECT as P01_TERM_CONTRACT_AUTHORITY_EFFECT,
    P01_TERM_SEMANTICS_RESOLVED as P01_TERM_SEMANTICS_RESOLVED,
    P01_HAIRCUT_RESERVE_DEPLETION_UNSPECIFIED_CLOSED as P01_HAIRCUT_RESERVE_DEPLETION_UNSPECIFIED_CLOSED,
    P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_SCHEMA_PRESENT as P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_SCHEMA_PRESENT,
    P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_RUNTIME_INSTANCE_PRESENT as P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_RUNTIME_INSTANCE_PRESENT,
    P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_AUTHORITY_EFFECT as P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_AUTHORITY_EFFECT,
    P01_TERM_SET_RESOLVED as P01_TERM_SET_RESOLVED,
    P01_VALUE_UNIT_CLASS_RESOLVED as P01_VALUE_UNIT_CLASS_RESOLVED,
    LIVE_RESTART_RECONSTRUCTED as LIVE_RESTART_RECONSTRUCTED,
    RECONCILIATION_CONTRACT_CREATED as RECONCILIATION_CONTRACT_CREATED,
    DIVERGENCE_POLICY_CREATED as DIVERGENCE_POLICY_CREATED,
)

CAPABILITY_ID = "FULL_CORE_LIVE_PATH_COMPOSITION_ROOT_V1"
PACKAGE_MARKER = "FULL_CORE_LIVE_PATH_COMPOSITION_ROOT_V1=true"
OWNER = "ops.full_core_live_path_composition_root_v1"
SCHEMA_VERSION = "full_core_live_path_composition_root.v1"
CONTRACT_VERSION = "v1"

CORE_LOGIC_CHANGE = False
LIVE_AUTHORIZED = False
LIVE_ENABLED = False
LIVE_ENABLED_STANDING_ADMISSION_SEAM_IMPLEMENTED = True
LIVE_ENABLED_TRUE_IS_NOT_AUTOMATIC_ADMISSION = True
LIVE_ENABLED_FALSE_REMAINS_FAIL_CLOSED = True
LIVE_ENABLED_DOES_NOT_IMPLY_LIVE_ARMED = True
LIVE_ENABLED_DOES_NOT_IMPLY_WIRE_SEND = True
LIVE_ENABLED_DOES_NOT_IMPLY_PORT_CONSTRUCTION = True
LIVE_ARMED = False
LIVE_ARMED_STANDING_ADMISSION_SEAM_IMPLEMENTED = True
LIVE_ARMED_TRUE_IS_NOT_AUTOMATIC_ADMISSION = True
LIVE_ARMED_FALSE_REMAINS_FAIL_CLOSED = True
LIVE_ARMED_DOES_NOT_IMPLY_RISK_ADMISSIBLE = True
LIVE_ARMED_DOES_NOT_IMPLY_WIRE_SEND = True
LIVE_ARMED_DOES_NOT_IMPLY_PORT_CONSTRUCTION = True
SUBMIT_UNLOCKED = False
WIRE_SEND_PERMITTED = False
WIRE_SEND_PERMITTED_STANDING_ADMISSION_SEAM_IMPLEMENTED = True
WIRE_SEND_PERMITTED_TRUE_IS_NOT_AUTOMATIC_SEND = True
WIRE_SEND_PERMITTED_FALSE_REMAINS_FAIL_CLOSED = True
FULL_CORE_HOST_STANDING_PREDICATE_JOIN_IMPLEMENTED = True
CAP_7_2_HOST_JOIN_TO_LIVE_EXECUTION_PORT = False
LIVE_EXECUTION_PORT_CONSTRUCTION_ADMISSION_CONTRACT_IMPLEMENTED = True
LIVE_EXECUTION_PORT_CONSTRUCTIBLE = False
PRODUCTIVE_WIRE_SEND_REACHABLE = False
ORDERS_AUTHORIZED = False
TESTNET_AUTHORIZED = False
FULL_CORE_RESTART_TEST_AUTHORIZED = False
CURRENT_LIVE_CORE_PATH_PROVEN = False
FULL_CORE_SYSTEM_E2E_PROVEN = False
STANDING_LIVE_AUTHORIZATION = False

DURABLE_FILEGATE_RUNTIME_JOIN_IMPLEMENTED = True
OWNER_ONE_SHOT_TYPED_LIVE_EXECUTION_PERMIT_IMPLEMENTED = True
OWNER_ONE_SHOT_PERMIT_TOKEN = "OWNER_GO_FULL_CORE_LIVE_PATH_OFFLINE_V1"
FRESH_PRETRADE_RUNTIME_GET_IMPLEMENTED = True
LIVE_ACCOUNT_BOUND_IMPLEMENTED = True
CAPITAL_ADMISSION_IMPLEMENTED = True
STEP_29P_CAPITAL_RISK_ADMISSIBILITY_IMPLEMENTED = True
RISK_ADMISSIBLE_DOES_NOT_IMPLY_LIVE_ENABLED = True
RISK_ADMISSIBLE_DOES_NOT_IMPLY_LIVE_ARMED = True
RISK_ADMISSIBLE_DOES_NOT_IMPLY_WIRE_SEND = True
RISK_ADMISSIBLE_DOES_NOT_IMPLY_PORT_CONSTRUCTION = True
ACCOUNT_EQUITY_AUTHORITY_OWNER_CANDIDATE = "UNRESOLVED"
RUNNING_EQUITY_SOURCE_OBJECT = "NONE"
RUNNING_EQUITY_SOURCE_FIELD_OR_DERIVATION = "NONE"
RUNNING_EQUITY_SOURCE_SEMANTICS = "UNBOUND"
MAPPING_PROVEN = False
IMPLEMENTATION_OF_VALUE_BINDING = False
ADJUDICATION_RESULT = "NO_CANONICALLY_VALID_MAPPING_AVAILABLE"
SOURCE_CANDIDATE_COUNT = 16
C01_C16_REMAIN_REJECTED = True
RUNNING_EQUITY_POLICY_SEMANTICS_RATIFIED = True
SEMANTIC_REQUIREMENTS_COMPLETE = True
POLICY_SEMANTICS_COMPLETE = True
P01_STATUS = "DECIDED"
U01_STATUS = "DECIDED"
U02_STATUS = "DECIDED"
U03_STATUS = "DECIDED"
U04_STATUS = "DECIDED"
U05_STATUS = "DECIDED"
U06_STATUS = "DECIDED"
U07_STATUS = "DECIDED"
U08_STATUS = "DECIDED"
U09_STATUS = "DECIDED"
DECIDED_RUNNING_EQUITY_POLICY_IDS: tuple[str, ...] = (
    "P01",
    "U01",
    "U02",
    "U03",
    "U04",
    "U05",
    "U06",
    "U07",
    "U08",
    "U09",
)
P01_HAIRCUTS_RESERVE_DEPLETION = "REDUCTION_ONLY_UNSPECIFIED_FAIL_CLOSED"
P01_MAY_INCREASE_EQUITY = False
P01_ZERO_ONLY_BY_EXPLICIT_POLICY = True
U01_ACCOUNT_MODE_ROLE = "ELIGIBILITY_CONTEXT_NOT_NUMERIC_EQUITY_TERM"
U02_REALIZED_UNREALIZED_TREATMENT = "IN_EQUITY_BASE_ONLY_NO_SEPARATE_ADDEND"
U03_OPEN_POSITION_TREATMENT = "MTM_IN_EQUITY_BASE_ONLY_NO_NOTIONAL_ADD"
U04_PENDING_ORDER_RESERVATIONS = "ENTRY_SUBTRACT_IF_NOT_IN_BASE_REDUCE_ONLY_NO_PRE_FILL_INCREASE"
U05_LIABILITIES_BORROWINGS = "REDUCE_ONCE_UNKNOWN_FAIL_CLOSED"
U06_FEES = "ACCRUED_ONCE_FUTURE_NOT_IN_U06"
U07_RESTART_RECONCILIATION = "FAIL_CLOSED_UNTIL_FRESH_SAME_EPOCH_RECONCILED"
U08_MULTI_CURRENCY_CONVERSION = "USDC_NATIVE_OR_OWNER_RATIFIED_CONTRACT_ELSE_FAIL_CLOSED"
USD_EQUALS_USDC = False
U09_FRESHNESS_CLASS = "FRESH_GET_PER_PRETRADE_DECISION"
U09_SAME_PRETRADE_EPOCH_REQUIRED = True
NUMERIC_EQUITY_TTL_SECONDS = 5
U09_COPIES_AVAILABLE_MARGIN_TS_AGE_BOUND = False
DOUBLE_COUNT_CONTROL_U02_U03_MTM_ONCE = True
DOUBLE_COUNT_CONTROL_U04_HOLD_ONCE = True
DOUBLE_COUNT_CONTROL_U05_LIABILITY_ONCE = True
DOUBLE_COUNT_CONTROL_U06_FEE_ONCE = True
ARCHITECTURE_RATIFIED = True
FUTURE_ACCOUNT_EQUITY_AUTHORITY_OWNER_CLASS = (
    "GOVERNED_PRODUCTIVE_ACCOUNT_EQUITY_AUTHORITY_PRODUCER"
)
FUTURE_GOVERNED_SOURCE_OBJECT_CLASS = "GOVERNED_RUNNING_ACCOUNT_EQUITY_SAMPLE_V1"
FUTURE_PRODUCER_CLASS = "COMPOSITIONAL_RECONSTRUCTION_WITH_WITNESS_RECONCILIATION_V1"
RUNTIME_VALUE_BINDING_PRESENT = False
LIVE_ACCOUNT_BOUND_JOIN_PRESENT = False
RAW_VENUE_FIELD_AUTHORITY_FORBIDDEN = True
OBSERVATION_IS_NOT_AUTHORITY = True
STEP_29P_IS_NOT_EQUITY_AUTHORITY_OWNER = True
LIVE_ACCOUNT_BOUND_IDENTITY_IS_NOT_CAPITAL_AUTHORITY = True
SAMPLE_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "dimension_id",
    "bound_account_identity",
    "bound_venue_identity",
    "bound_td_mode",
    "settlement_currency",
    "value",
    "value_semantics",
    "producer_identity",
    "authority_contract_ref",
    "source_revision_or_digest",
    "input_set_digest",
    "decision_epoch",
    "observed_at/as_of",
    "freshness_max_age",
    "freshness_policy_status",
    "restart_reconciliation_status",
    "component_completeness",
    "component_provenance",
    "inclusion_vector",
    "component_term_vector",
    "double_count_guards",
    "currency_conversion_status",
    "witness_reconciliation_status",
    "policy_version",
    "semantic_digest",
    "sample_id",
    "observation_vs_authority_class",
)
LIVE_ACCOUNT_BOUND_JOIN_EXECUTED_THIS_SLICE = False
FULL_CORE_OFFLINE_E2E_PROVEN = True
FULL_CORE_OFFLINE_E2E_EVIDENCE_CLASS = "INJECTED_NON_PRODUCTIVE"

PATH_KIND = "FULL_CORE_LIVE_PATH"
FUTURE_PRODUCTIVE_LIVE_EXECUTION_PATH = "FULL_CORE_LIVE_PATH"
PRODUCTIVE_LIVE_NEXT_POINTER_AUTHORITY = "SECTION_11_2_1"
CANARY_VENUE_PROOF_PATH_KIND = "CANARY_VENUE_PROOF_ONLY"
CANARY_VENUE_PROOF_PATH_ROLE = "HISTORICAL_AND_SCOPED_VENUE_PROOF"
CANARY_VENUE_PROOF_PATH_IS_FULL_CORE_E2E = False
CANARY_PATH_IS_PARALLEL_PRODUCTIVE_LIVE_AUTHORITY = False
CANARY_VENUE_PROOF_PATH_DISTINCT = True
SECTION_11_13_5_NEXT_POINTER_DOMAIN = "SCOPED_CANARY_VENUE_PROOF_EVIDENCE_ONLY"
SECTION_11_14_NEXT_POINTER_DOMAIN = "HISTORICAL_CANARY_LIFECYCLE_EVIDENCE_LADDER_NOT_FULL_CORE_E2E"
SECTION_11_14_POST_IS_NOT_STEP_29Q = True
SECTION_11_14_ACCOUNTING_IS_NOT_FULL_CORE_E2E = True
G12_IS_NOT_FULL_CORE_E2E = True
CANARY_SUBMIT_EVIDENCE_IS_NOT_FULL_CORE_SUBMIT_EVIDENCE = True

SELECTION_OWNER = "CAPABILITY_2_3_SINGLE_SELECTED_FUTURE_POLICY_V1"
INSTRUMENT_BINDING_OWNER = "CAPABILITY_2_4_SINGLE_SELECTED_FUTURE_RUNTIME_BINDING_V1"
DECISION_OWNER = (
    "trading.master_v2.integrated_offline_trading_logic_replay_v1."
    "run_integrated_offline_trading_logic_replay_v1"
)
RISK_SIZING_OWNER = "STEP_29P"
SAFETY_OWNER = (
    "trading.master_v2.safety_kernel_offline_replay_binding_adapter_v0."
    "evaluate_offline_safety_kernel_boundary_v0"
)
ORDER_INTENT_OWNER = "STEP_29Q"
VENUE_TRANSLATION_OWNER = "TRANSLATOR_ONLY"
PRETRADE_OWNER = "VENUE_PRETRADE_GATES"
WIRE_SEND_OWNER = "LIVE_EXECUTION_BOUNDARY"
MAPPER_ROLE = "NO_ORDER_ANALYTICAL_TRANSLATOR_NOT_REQUIRED_FOR_LIVE"
LIVE_CANARY_HTTP_CLIENT_ROLE = "CANARY_VENUE_PROOF_ADAPTER_NOT_FULL_CORE"
LIVE_EXECUTION_PORT_ROLE = "DECLARED_CONSTRUCTION_FORBIDDEN_IN_CAP_11_1"
OFFLINE_BOUNDARY_ROLE = "HARD_STOP_BEFORE_WIRE"

MODE_SIMULATION = "SIMULATION"
MODE_TEST = "TEST"
MODE_LIVE = "LIVE"
ALLOWED_MODES = frozenset({MODE_SIMULATION, MODE_TEST, MODE_LIVE})

PRE_SUBMIT_RECON = "PRE_SUBMIT_RECON"
POST_SUBMIT_RECON = "POST_SUBMIT_RECON"
UNKNOWN_OUTCOME_RECON = "UNKNOWN_OUTCOME_RECON"
RESTART_RECON = "RESTART_RECON"

TREASURY_CLASSIFICATION = "REQUIRED_FOR_FULL_AUTONOMY"
FULL_AUTONOMY_CLASSIFICATION = "REQUIRED_FOR_FULL_AUTONOMY"
FUNDING_CLASSIFICATION = "REQUIRED_FOR_LIVE_OPERATION_NOT_THIS_TEST"

FORBIDDEN_IMPORT_TOKENS: tuple[str, ...] = (
    "LiveCanaryHttpClientV1",
    "post_entry_order",
    "construct_live_execution_port_v1",
    "UrllibLiveCanaryTransportV1",
)

CANARY_DEFAULT_INSTRUMENT_ID = "SUI-USD_UM_XPERP-310404"
CANARY_DEFAULT_SIDE = "BUY"


def standing_live_gate_fields_v1() -> dict[str, bool]:
    """Standing Full-Core live gates. Defaults remain false. Not admission."""
    return {
        "live_enabled": LIVE_ENABLED is True,
        "live_armed": LIVE_ARMED is True,
        "wire_send_permitted": WIRE_SEND_PERMITTED is True,
    }
