"""Constants for the offline Core→Live composition root.

Standing Live gates remain false. This package never arms wire send.
"""

from __future__ import annotations

CAPABILITY_ID = "FULL_CORE_LIVE_PATH_COMPOSITION_ROOT_V1"
PACKAGE_MARKER = "FULL_CORE_LIVE_PATH_COMPOSITION_ROOT_V1=true"
OWNER = "ops.full_core_live_path_composition_root_v1"
SCHEMA_VERSION = "full_core_live_path_composition_root.v1"
CONTRACT_VERSION = "v1"

CORE_LOGIC_CHANGE = False
LIVE_AUTHORIZED = False
LIVE_ENABLED = False
LIVE_ARMED = False
SUBMIT_UNLOCKED = False
WIRE_SEND_PERMITTED = False
ORDERS_AUTHORIZED = False
TESTNET_AUTHORIZED = False
FULL_CORE_RESTART_TEST_AUTHORIZED = False
CURRENT_LIVE_CORE_PATH_PROVEN = False
FULL_CORE_SYSTEM_E2E_PROVEN = False
STANDING_LIVE_AUTHORIZATION = False

DURABLE_FILEGATE_RUNTIME_JOIN_IMPLEMENTED = True
OWNER_ONE_SHOT_TYPED_LIVE_EXECUTION_PERMIT_IMPLEMENTED = True
OWNER_ONE_SHOT_PERMIT_TOKEN = "OWNER_GO_FULL_CORE_LIVE_PATH_OFFLINE_V1"
FRESH_PRETRADE_RUNTIME_GET_IMPLEMENTED = True
LIVE_ACCOUNT_BOUND_IMPLEMENTED = True
FULL_CORE_OFFLINE_E2E_PROVEN = True
FULL_CORE_OFFLINE_E2E_EVIDENCE_CLASS = "INJECTED_NON_PRODUCTIVE"

PATH_KIND = "FULL_CORE_LIVE_PATH"
FUTURE_PRODUCTIVE_LIVE_EXECUTION_PATH = "FULL_CORE_LIVE_PATH"
PRODUCTIVE_LIVE_NEXT_POINTER_AUTHORITY = "SECTION_11_2_1"
CANARY_VENUE_PROOF_PATH_KIND = "CANARY_VENUE_PROOF_ONLY"
CANARY_VENUE_PROOF_PATH_ROLE = "HISTORICAL_AND_SCOPED_VENUE_PROOF"
CANARY_VENUE_PROOF_PATH_IS_FULL_CORE_E2E = False
CANARY_PATH_IS_PARALLEL_PRODUCTIVE_LIVE_AUTHORITY = False
CANARY_VENUE_PROOF_PATH_DISTINCT = True
SECTION_11_13_5_NEXT_POINTER_DOMAIN = "SCOPED_CANARY_VENUE_PROOF_EVIDENCE_ONLY"
SECTION_11_14_NEXT_POINTER_DOMAIN = "HISTORICAL_CANARY_LIFECYCLE_EVIDENCE_LADDER_NOT_FULL_CORE_E2E"
SECTION_11_14_POST_IS_NOT_STEP_29Q = True
SECTION_11_14_ACCOUNTING_IS_NOT_FULL_CORE_E2E = True
G12_IS_NOT_FULL_CORE_E2E = True
CANARY_SUBMIT_EVIDENCE_IS_NOT_FULL_CORE_SUBMIT_EVIDENCE = True

SELECTION_OWNER = "CAPABILITY_2_3_SINGLE_SELECTED_FUTURE_POLICY_V1"
INSTRUMENT_BINDING_OWNER = "CAPABILITY_2_4_SINGLE_SELECTED_FUTURE_RUNTIME_BINDING_V1"
DECISION_OWNER = (
    "trading.master_v2.integrated_offline_trading_logic_replay_v1."
    "run_integrated_offline_trading_logic_replay_v1"
)
RISK_SIZING_OWNER = "STEP_29P"
SAFETY_OWNER = (
    "trading.master_v2.safety_kernel_offline_replay_binding_adapter_v0."
    "evaluate_offline_safety_kernel_boundary_v0"
)
ORDER_INTENT_OWNER = "STEP_29Q"
VENUE_TRANSLATION_OWNER = "TRANSLATOR_ONLY"
PRETRADE_OWNER = "VENUE_PRETRADE_GATES"
WIRE_SEND_OWNER = "LIVE_EXECUTION_BOUNDARY"
MAPPER_ROLE = "NO_ORDER_ANALYTICAL_TRANSLATOR_NOT_REQUIRED_FOR_LIVE"
LIVE_CANARY_HTTP_CLIENT_ROLE = "CANARY_VENUE_PROOF_ADAPTER_NOT_FULL_CORE"
LIVE_EXECUTION_PORT_ROLE = "DECLARED_CONSTRUCTION_FORBIDDEN_IN_CAP_11_1"
OFFLINE_BOUNDARY_ROLE = "HARD_STOP_BEFORE_WIRE"

MODE_SIMULATION = "SIMULATION"
MODE_TEST = "TEST"
MODE_LIVE = "LIVE"
ALLOWED_MODES = frozenset({MODE_SIMULATION, MODE_TEST, MODE_LIVE})

PRE_SUBMIT_RECON = "PRE_SUBMIT_RECON"
POST_SUBMIT_RECON = "POST_SUBMIT_RECON"
UNKNOWN_OUTCOME_RECON = "UNKNOWN_OUTCOME_RECON"
RESTART_RECON = "RESTART_RECON"

TREASURY_CLASSIFICATION = "REQUIRED_FOR_FULL_AUTONOMY"
FULL_AUTONOMY_CLASSIFICATION = "REQUIRED_FOR_FULL_AUTONOMY"
FUNDING_CLASSIFICATION = "REQUIRED_FOR_LIVE_OPERATION_NOT_THIS_TEST"

FORBIDDEN_IMPORT_TOKENS: tuple[str, ...] = (
    "LiveCanaryHttpClientV1",
    "post_entry_order",
    "construct_live_execution_port_v1",
    "UrllibLiveCanaryTransportV1",
)

CANARY_DEFAULT_INSTRUMENT_ID = "SUI-USD_UM_XPERP-310404"
CANARY_DEFAULT_SIDE = "BUY"
