"""Outcome phase tokens for Full-Core productive trade-order POST transport."""

from __future__ import annotations

NOT_ATTEMPTED = "NOT_ATTEMPTED"
SEND_INITIATED = "SEND_INITIATED"
HTTP_RESPONSE_RECEIVED = "HTTP_RESPONSE_RECEIVED"
VENUE_RESPONSE_PARSED = "VENUE_RESPONSE_PARSED"
VENUE_ACCEPTED = "VENUE_ACCEPTED"
VENUE_REJECTED = "VENUE_REJECTED"
TRANSPORT_FAILURE_BEFORE_RESPONSE = "TRANSPORT_FAILURE_BEFORE_RESPONSE"
RESPONSE_RECEIVED_PARSE_FAILED = "RESPONSE_RECEIVED_PARSE_FAILED"
UNKNOWN_EXTERNAL_STATE = "UNKNOWN_EXTERNAL_STATE"

__all__ = [
    "HTTP_RESPONSE_RECEIVED",
    "NOT_ATTEMPTED",
    "RESPONSE_RECEIVED_PARSE_FAILED",
    "SEND_INITIATED",
    "TRANSPORT_FAILURE_BEFORE_RESPONSE",
    "UNKNOWN_EXTERNAL_STATE",
    "VENUE_ACCEPTED",
    "VENUE_REJECTED",
    "VENUE_RESPONSE_PARSED",
]
