"""P5.1 layered-core authority seam — capability constants (no productive activation)."""

from __future__ import annotations

PACKAGE_MARKER = "P5_PRODUCTIVE_LAYERED_CORE_AUTHORITY_SEAM_V1=true"
OWNER = "ops.p5_productive_layered_core_authority_seam_v1"

P5_AUTHORITY_CUTOVER_AUTHORIZED = False
P4_PRODUCTIVE_BINDING = False
AUTHORITY_CUTOVER_OCCURRED = False
NUMERIC_FORMULA_AUTHORITY = "NONE"
MULTI_FUTURE_RUNTIME_AUTHORIZED = False
MAX_POSITIONS_EFFECTIVE = 1
EXTERNAL_EFFECT_AUTHORIZED = False
OPTIMIZER_PRODUCTIVE_AUTHORITY = "NONE"

PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED = False

__all__ = [
    "AUTHORITY_CUTOVER_OCCURRED",
    "EXTERNAL_EFFECT_AUTHORIZED",
    "MAX_POSITIONS_EFFECTIVE",
    "MULTI_FUTURE_RUNTIME_AUTHORIZED",
    "NUMERIC_FORMULA_AUTHORITY",
    "OPTIMIZER_PRODUCTIVE_AUTHORITY",
    "OWNER",
    "P4_PRODUCTIVE_BINDING",
    "P5_AUTHORITY_CUTOVER_AUTHORIZED",
    "PACKAGE_MARKER",
    "PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED",
]
