"""CAPABILITY_O6 constants — runtime health, recovery and failure injection."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_O6_RUNTIME_HEALTH_RECOVERY_AND_FAILURE_INJECTION_CLOSURE_V1"
SCHEMA_VERSION = "o6_runtime_health_recovery_and_failure_injection_closure_v1"
PACKAGE_MARKER = "RUNTIME_HEALTH_RECOVERY_AND_FAILURE_INJECTION_CLOSURE_V1=true"

# Reuse O2 / O4 / O5 canonical owners — never invent parallel producers.
O2_SUPERVISOR_PACKAGE = "canonical_local_launcher_and_process_supervision_v1"
O4_BAR_PRODUCER = "CanonicalPublicMdBarProducerV1"
O5_READ_MODEL_PACKAGE = "canonical_read_model_and_market_dashboard_rebuild_v1"
O5_READ_MODEL_CLASSIFICATION = "DERIVED"

# Explicit component health subjects.
COMPONENT_SUPERVISOR = "SUPERVISOR"
COMPONENT_MARKET_DATA = "MARKET_DATA"
COMPONENT_RUNTIME = "RUNTIME"
COMPONENT_PERSISTENCE = "PERSISTENCE"
COMPONENT_READ_MODEL_PROJECTOR = "READ_MODEL_PROJECTOR"
COMPONENT_DASHBOARD_BACKEND = "DASHBOARD_BACKEND"

HEALTH_COMPONENTS = (
    COMPONENT_SUPERVISOR,
    COMPONENT_MARKET_DATA,
    COMPONENT_RUNTIME,
    COMPONENT_PERSISTENCE,
    COMPONENT_READ_MODEL_PROJECTOR,
    COMPONENT_DASHBOARD_BACKEND,
)

REQUIRED_HEALTH_FIELDS = (
    "process_alive",
    "heartbeat_time",
    "last_success_time",
    "last_error_time",
    "error_class",
    "restart_count",
    "input_lag",
    "output_lag",
    "state_commit_position",
    "evidence_cursor",
    "session_id",
    "repository_sha",
    "config_digest",
)

# Health classification vocabulary (aligned with O5 connection states).
HEALTH_HEALTHY = "HEALTHY"
HEALTH_DEGRADED = "DEGRADED"
HEALTH_STALE = "STALE"
HEALTH_DISCONNECTED = "DISCONNECTED"
HEALTH_MISSING_SOURCE = "MISSING_SOURCE"

HEALTH_STATES = frozenset(
    {
        HEALTH_HEALTHY,
        HEALTH_DEGRADED,
        HEALTH_STALE,
        HEALTH_DISCONNECTED,
        HEALTH_MISSING_SOURCE,
    }
)

NON_HEALTHY_STATES = frozenset(
    {
        HEALTH_DEGRADED,
        HEALTH_STALE,
        HEALTH_DISCONNECTED,
        HEALTH_MISSING_SOURCE,
    }
)

# Composite health surfaces.
COMPOSITE_HOST_HEALTH = "HOST_HEALTH"
COMPOSITE_MARKET_DATA_HEALTH = "MARKET_DATA_HEALTH"
COMPOSITE_RUNTIME_HEALTH = "RUNTIME_HEALTH"
COMPOSITE_PERSISTENCE_HEALTH = "PERSISTENCE_HEALTH"
COMPOSITE_READ_MODEL_HEALTH = "READ_MODEL_HEALTH"
COMPOSITE_DASHBOARD_BACKEND_HEALTH = "DASHBOARD_BACKEND_HEALTH"
COMPOSITE_END_TO_END_DATA_HEALTH = "END_TO_END_DATA_HEALTH"

COMPOSITE_HEALTH_KEYS = (
    COMPOSITE_HOST_HEALTH,
    COMPOSITE_MARKET_DATA_HEALTH,
    COMPOSITE_RUNTIME_HEALTH,
    COMPOSITE_PERSISTENCE_HEALTH,
    COMPOSITE_READ_MODEL_HEALTH,
    COMPOSITE_DASHBOARD_BACKEND_HEALTH,
    COMPOSITE_END_TO_END_DATA_HEALTH,
)

# Severity order for composite derivation (worst first).
HEALTH_SEVERITY = {
    HEALTH_MISSING_SOURCE: 5,
    HEALTH_DISCONNECTED: 4,
    HEALTH_STALE: 3,
    HEALTH_DEGRADED: 2,
    HEALTH_HEALTHY: 1,
}

# Deterministic offline freshness windows (seconds).
HEALTHY_MAX_AGE_SECONDS = 30.0
DEGRADED_MAX_AGE_SECONDS = 120.0
HEARTBEAT_STALE_SECONDS = 30.0

# Bounded retry / recovery policy (authorized by ops contracts; no alpha authority).
DEFAULT_BOUNDED_RETRY_LIMIT = 3
DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT_SECONDS = 2.0

RECOVERY_INVARIANTS = {
    "SESSION_FENCED_BEFORE_RECOVERY": True,
    "RECONCILIATION_BEFORE_RESUME": True,
    "NO_DUPLICATE_CONFIRMATION_ADVANCE": True,
    "NO_DUPLICATE_MARKET_OBSERVATION_ADVANCE": True,
    "NO_DUPLICATE_FILL": True,
    "NO_DUPLICATE_BAR_FINALIZATION": True,
    "NO_DUPLICATE_READ_MODEL_COMMIT": True,
    "NO_STALE_DASHBOARD_GREEN_STATE": True,
    "SINGLE_WRITER_ENFORCED": True,
    "DUPLICATE_SESSION_START_BLOCKED": True,
    "PID_REUSE_SAFE": True,
    "STALE_PID_FILE_SAFE": True,
    "RECOVERY_HAS_ALPHA_AUTHORITY": False,
}

SAFETY_INVARIANTS = {
    "CORE_LOGIC_CHANGE_ALLOWED": False,
    "CONFIG_CHANGE_ALLOWED": False,
    "HEALTH_HAS_ALPHA_AUTHORITY": False,
    "DASHBOARD_TRADING_AUTHORITY": False,
    "READ_MODEL_CLASSIFICATION_DERIVED": True,
    "PARALLEL_OHLCV_PRODUCER_FORBIDDEN": True,
    "PARALLEL_READ_MODEL_PRODUCER_FORBIDDEN": True,
    "NETWORK_SESSION_ALLOWED": False,
    "AUTHORIZATION_CONSUMPTION_ALLOWED": False,
    "CONFIRM_TOKEN_MINT_ALLOWED": False,
    "ORDERS_ALLOWED": False,
    "LIVE_TRADING_ALLOWED": False,
    "TESTNET_ALLOWED": False,
    "EXCHANGE_CREDENTIAL_USE_ALLOWED": False,
    "NOTION_MUTATION_ALLOWED": False,
    "RULESET_MUTATION_ALLOWED": False,
    "STALE_CANNOT_RENDER_HEALTHY": True,
    "DISCONNECTED_CANNOT_RENDER_HEALTHY": True,
    "PROCESS_ALIVE_ALONE_INSUFFICIENT": True,
}

# Highest-value bounded offline failure classes (no network / no runtime auth).
BOUNDED_FAILURE_CLASSES = (
    "PROCESS_START_FAILURE",
    "UNEXPECTED_CHILD_PROCESS_EXIT",
    "STALE_PID_OR_SESSION_REGISTRY",
    "DUPLICATE_SESSION_START",
    "WRITER_CONFLICT",
    "HEARTBEAT_LOSS",
    "STALE_MARKET_DATA_STATE",
    "DISCONNECTED_SOURCE_STATE",
    "READ_MODEL_PROJECTION_FAILURE",
    "DASHBOARD_BACKEND_FAILURE",
    "DUPLICATE_MARKET_EVENT",
    "OUT_OF_ORDER_MARKET_EVENT",
    "DUPLICATE_OHLCV_FINALIZATION",
    "MISSED_OR_STALE_OHLCV_INTERVAL",
    "GRACEFUL_SHUTDOWN_TIMEOUT",
    "RECOVERY_FROM_PERSISTED_ACTIVE_STATE",
    "UNAVAILABLE_LOG_STATE_OR_EVIDENCE_PATH",
)

MANIFEST_FILENAME = "MANIFEST.sha256"
EVIDENCE_DIRNAME = "capability_o6_runtime_health_recovery_and_failure_injection_closure_v1"
