"""Fail-closed constants for the offline §11.14 evidence-ladder surface."""

from __future__ import annotations

CAPABILITY_ID = "SECTION_11_14_LIVE_ORDER_AND_ECONOMIC_EVIDENCE_LADDER_V1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "section_11_14_offline_evidence_ladder.v1"
EVIDENCE_RECORD_SCHEMA_VERSION = "section_11_14_evidence_record.v1"
METRICS_SCHEMA_VERSION = "section_11_14_mandatory_live_metrics.v1"
OWNER = "ops.section_11_14_live_order_and_economic_evidence_ladder_v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_EXECUTION_CODE_EXISTS_MAXIMUM_SAFE_LEVERAGE_V1"
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_OFFLINE_EVIDENCE_LADDER_SURFACE_MAXIMUM_SAFE_LEVERAGE_V1"
)
HISTORICAL_OFFLINE_SURFACE_OWNER_GO = PRIOR_OWNER_GO
WORKPACKAGE_ID = "SECTION_11_14_LIVE_EXECUTION_CODE_EXISTS_ADJUDICATION_V1"
THIS_SLICE = "11.14.LIVE_EXECUTION_CODE_EXISTS_ADJUDICATION"
PREDECESSOR_SLICE = "11.14.OFFLINE_EVIDENCE_LADDER_SURFACE"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_14_OFFLINE_EVIDENCE_LADDER_SURFACE"
CANONICAL_EVIDENCE_RUN_ID = "20260904T123100Z"
CANONICAL_BASE_SHA = "b09cac11f0eaecfc5c6f5c97e8b23e808e186b9a"
EXPECTED_ORIGIN_MAIN_SHA = CANONICAL_BASE_SHA
IMPLEMENTATION_SHA = CANONICAL_BASE_SHA
HISTORICAL_OFFLINE_SURFACE_SHA = "a558c108617d40c12bd1d8c480a6e5d797ccb308"
HISTORICAL_OFFLINE_SURFACE_RUN_ID = "20260904T121000Z"
G12_STATUS_REQUIRED = "CLOSED_LIVE_FLATTEN_PROVABILITY_PROVEN"

CANONICAL_RUNBOOK_PATH = "docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md"
CANONICAL_SECTION_HEADING = "## 11.14 Live order and economic evidence ladder"
CANONICAL_OFFLINE_SLICE_HEADING = "### 11.14 OFFLINE_EVIDENCE_LADDER_SURFACE"
CANONICAL_CODE_EXISTS_SLICE_HEADING = "### 11.14 LIVE_EXECUTION_CODE_EXISTS_ADJUDICATION"

LADDER_FIELDS: tuple[str, ...] = (
    "LIVE_EXECUTION_CODE_EXISTS",
    "LIVE_EXECUTION_PATH_REACHABLE",
    "LIVE_PRIVATE_READ_ONLY_PROVEN",
    "LIVE_ORDER_PLAN_OBSERVED",
    "LIVE_SUBMIT_ACK_OBSERVED",
    "LIVE_FILL_OBSERVED",
    "LIVE_FEE_OBSERVED",
    "LIVE_POSITION_RECONCILED",
    "LIVE_ACCOUNTING_RECONSTRUCTED",
    "LIVE_RESTART_RECONSTRUCTED",
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED",
    "LIVE_END_TO_END_EVIDENCE_PROVEN",
)
LADDER_FIELD_COUNT = 12

OBSERVED_OR_PROVEN_FIELDS_MUST_REMAIN_FALSE: tuple[str, ...] = (
    "LIVE_PRIVATE_READ_ONLY_PROVEN",
    "LIVE_ORDER_PLAN_OBSERVED",
    "LIVE_SUBMIT_ACK_OBSERVED",
    "LIVE_FILL_OBSERVED",
    "LIVE_FEE_OBSERVED",
    "LIVE_POSITION_RECONCILED",
    "LIVE_ACCOUNTING_RECONSTRUCTED",
    "LIVE_RESTART_RECONSTRUCTED",
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED",
    "LIVE_END_TO_END_EVIDENCE_PROVEN",
)

LIVE_EXECUTION_CODE_EXISTS = True
LIVE_EXECUTION_PATH_REACHABLE = False
LIVE_PRIVATE_READ_ONLY_PROVEN = False
LIVE_ORDER_PLAN_OBSERVED = False
LIVE_SUBMIT_ACK_OBSERVED = False
LIVE_FILL_OBSERVED = False
LIVE_FEE_OBSERVED = False
LIVE_POSITION_RECONCILED = False
LIVE_ACCOUNTING_RECONSTRUCTED = False
LIVE_RESTART_RECONSTRUCTED = False
LIVE_AUTONOMOUS_RECOVERY_OBSERVED = False
LIVE_END_TO_END_EVIDENCE_PROVEN = False

LADDER_FIELD_DEFAULTS: dict[str, bool] = {
    "LIVE_EXECUTION_CODE_EXISTS": LIVE_EXECUTION_CODE_EXISTS,
    "LIVE_EXECUTION_PATH_REACHABLE": LIVE_EXECUTION_PATH_REACHABLE,
    "LIVE_PRIVATE_READ_ONLY_PROVEN": LIVE_PRIVATE_READ_ONLY_PROVEN,
    "LIVE_ORDER_PLAN_OBSERVED": LIVE_ORDER_PLAN_OBSERVED,
    "LIVE_SUBMIT_ACK_OBSERVED": LIVE_SUBMIT_ACK_OBSERVED,
    "LIVE_FILL_OBSERVED": LIVE_FILL_OBSERVED,
    "LIVE_FEE_OBSERVED": LIVE_FEE_OBSERVED,
    "LIVE_POSITION_RECONCILED": LIVE_POSITION_RECONCILED,
    "LIVE_ACCOUNTING_RECONSTRUCTED": LIVE_ACCOUNTING_RECONSTRUCTED,
    "LIVE_RESTART_RECONSTRUCTED": LIVE_RESTART_RECONSTRUCTED,
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED": LIVE_AUTONOMOUS_RECOVERY_OBSERVED,
    "LIVE_END_TO_END_EVIDENCE_PROVEN": LIVE_END_TO_END_EVIDENCE_PROVEN,
}

# Exact SSOT names from Master Runbook §11.14 (lines 60698-60719). Count=20.
# Prior pre-auth census reported 19; that count is not used.
MANDATORY_LIVE_METRICS: tuple[str, ...] = (
    "orders_planned",
    "orders_submitted",
    "orders_acknowledged",
    "orders_rejected",
    "orders_unknown",
    "partial_fills",
    "fills",
    "cancels",
    "amends",
    "duplicate_submit_prevented",
    "fees_paid",
    "funding_paid_or_received",
    "realized_pnl",
    "unrealized_pnl",
    "margin_utilization",
    "reconciliation_divergences",
    "autonomous_recoveries",
    "degradation_transitions",
    "kill_switch_events",
    "owner_interventions",
)
MANDATORY_LIVE_METRIC_COUNT = 20
PRIOR_CENSUS_REPORTED_METRIC_COUNT = 19
METRIC_COUNT_DISCREPANCY_VS_PRIOR_CENSUS = True

FORBIDDEN_LIVE_SOURCE_KINDS: tuple[str, ...] = (
    "FIXTURE",
    "SIMULATION",
    "SIMULATED",
    "TESTNET",
    "PAPER",
    "SHADOW",
    "DEMO",
)
ADMISSIBLE_OFFLINE_SOURCE_KINDS: tuple[str, ...] = (
    "CANONICAL_RUNBOOK",
    "REPOSITORY_IMPLEMENTATION",
    "PREDECESSOR_EVIDENCE",
    "GOVERNED_OFFLINE_CONTRACT",
)

SECTION_11_14_AUTHORIZED = False
SECTION_11_14_COMPLETE = False
SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED = False
SECTION_11_14_LIVE_EVIDENCE_COLLECTION_AUTHORIZED = False
SECTION_11_14_OFFLINE_SURFACE_BOUND = True
LIVE_AUTHORIZED = False
LIVE_ENABLED = False
LIVE_ARMED = False
SUBMIT_UNLOCKED = False
CANARY_AUTHORIZED = False
TESTNET_AUTHORIZED = False
POST_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
CANCEL_ALLOWED = False
AMEND_ALLOWED = False
FLATTEN_EXECUTE_ALLOWED = False
FUNDING_ALLOWED = False
CREDENTIAL_USE_ALLOWED = False
PUBLIC_GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
COLLECTOR_ACTIVATED = False

REUSE_CLASSIFICATIONS: tuple[str, ...] = (
    "REUSABLE_AS_IDENTICAL_11_14_FACT",
    "SUPPORTING_CONTEXT_ONLY",
    "HISTORICAL_ONLY",
    "SEMANTICALLY_DIFFERENT",
    "REQUIRES_FRESH_OBSERVATION",
    "REQUIRES_OWNER_POLICY_DECISION",
    "CONTRADICTORY",
    "NOT_APPLICABLE",
)

EARLIEST_UNRESOLVED_DEPENDENCY = "LIVE_EXECUTION_PATH_REACHABLE"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_LIVE_EXECUTION_PATH_REACHABLE"
NEXT_OWNER_GO_REQUIRED = "SEPARATE_OWNER_GO_FOR_LIVE_EXECUTION_PATH_REACHABLE"
G12_DOES_NOT_AUTHORIZE_SECTION_11_14 = True
G12_DOES_NOT_SATISFY_SECTION_11_14_OBSERVED_FIELDS = True
CURRENTLY_REACHABLE_IS_NOT_LIVE_EXECUTION_PATH_REACHABLE = True
LIVE_RECONCILIATION_PROVEN_IS_NOT_LIVE_POSITION_RECONCILED = True
FIELD_NAME_SIMILARITY_IS_NOT_SEMANTIC_IDENTITY = True
HISTORICAL_EVIDENCE_IS_NOT_CURRENT_TRUTH = True
CODE_PRESENCE_IS_NOT_LIVE_EXECUTION_CODE_EXISTS = True
HISTORICAL_CODE_IS_NOT_LIVE_EXECUTION_CODE_EXISTS = True
FIXTURE_TESTNET_SIM_IS_NOT_LIVE_EXECUTION_CODE_EXISTS = True
LIVE_EXECUTION_CODE_EXISTS_DOES_NOT_IMPLY_PATH_REACHABLE = True
LIVE_EXECUTION_CODE_EXISTS_DOES_NOT_IMPLY_AUTHORIZATION = True
NO_TESTNET_FIXTURE_OR_SIMULATED_RESULT_MAY_SATISFY_A_LIVE_EVIDENCE_FIELD = True
LIVE_EXECUTION_CODE_EXISTS_CANONICAL_DEFINITION = (
    "LIVE_EXECUTION_CODE_EXISTS is the first §11.14 Live proof-claim field. "
    "It is true iff current origin/main contains a complete, integrated, "
    "non-historical, non-fixture, non-testnet, non-simulated static call graph "
    "from the canonical Live canary execution decision/gate boundary through "
    "order-plan consumption, venue-native payload construction including "
    "client-order-id, fail-closed submit gates, the Live HTTP execution port, "
    "and UrllibLiveCanaryTransportV1.send. File presence alone, historical "
    "implementation, Cap 11.7-11.11 contracts-only constants, and §4.9 "
    "CURRENTLY_REACHABLE are each insufficient. True does not imply "
    "LIVE_EXECUTION_PATH_REACHABLE, authorization, credential availability, "
    "runtime observation, or any later ladder field."
)
STATIC_EXECUTION_GRAPH_FILENAME = "STATIC_EXECUTION_GRAPH.json"
COMPONENT_CLASSIFICATION_FILENAME = "COMPONENT_CLASSIFICATION.json"

EVIDENCE_DIRNAME = "section_11_14_live_order_and_economic_evidence_ladder_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
CLAIMS_FILENAME = "claims.json"
SUMMARY_FILENAME = "SUMMARY.json"
ADJUDICATION_FILENAME = "ADJUDICATION.json"
TRACEABILITY_FILENAME = "TRACEABILITY.json"
REUSE_MATRIX_FILENAME = "REUSE_VS_FRESH.json"
METRICS_SCHEMA_FILENAME = "MANDATORY_LIVE_METRICS_SCHEMA.json"
LADDER_STATE_FILENAME = "LADDER_STATE.json"
LINEAGE_FILENAME = "LINEAGE.json"
STATIC_FIELD_PROOF_FILENAME = "STATIC_FIELD_ADJUDICATION.json"
MUTATION_BOUNDARY_FILENAME = "MUTATION_BOUNDARY.json"

SP01_PATH = "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/http_client_v1.py"
FLATTEN_EXECUTE_PATH = (
    "src/ops/section_11_13_5_productive_flatten_post_and_reconciliation_v1/execute_v1.py"
)
CANARY_SUBMIT_TRANSPORT_PATH = (
    "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/submit_transport_v1.py"
)
SECTION_4_9_ANCHOR = "docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md §4.9.4 SP-01"
