"""Fail-closed constants for the offline §11.14 evidence-ladder surface."""

from __future__ import annotations

CAPABILITY_ID = "SECTION_11_14_LIVE_ORDER_AND_ECONOMIC_EVIDENCE_LADDER_V1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "section_11_14_offline_evidence_ladder.v1"
EVIDENCE_RECORD_SCHEMA_VERSION = "section_11_14_evidence_record.v1"
METRICS_SCHEMA_VERSION = "section_11_14_mandatory_live_metrics.v1"
OWNER = "ops.section_11_14_live_order_and_economic_evidence_ladder_v1"
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_SUBMIT_ACK_CONTRACT_AND_MUTATION_BOUNDARY_"
    "FORENSIC_ADJUDICATION_V1"
)
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_ORDER_PLAN_OBSERVED_EXACT_LIVE_MUTATION_"
    "MAXIMUM_SAFE_LEVERAGE_V1"
)
HISTORICAL_ORDER_PLAN_OWNER_GO = PRIOR_OWNER_GO
HISTORICAL_PRIVATE_READ_ONLY_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_MAXIMUM_SAFE_LEVERAGE_CLOSE_ALL_NON_MUTATING_DEPENDENCIES_V1"
)
HISTORICAL_PATH_REACHABLE_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_EXECUTION_PATH_REACHABLE_MAXIMUM_SAFE_LEVERAGE_V1"
)
HISTORICAL_CODE_EXISTS_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_EXECUTION_CODE_EXISTS_MAXIMUM_SAFE_LEVERAGE_V1"
)
HISTORICAL_OFFLINE_SURFACE_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_OFFLINE_EVIDENCE_LADDER_SURFACE_MAXIMUM_SAFE_LEVERAGE_V1"
)
WORKPACKAGE_ID = (
    "SECTION_11_14_LIVE_SUBMIT_ACK_CONTRACT_AND_MUTATION_BOUNDARY_FORENSIC_ADJUDICATION_V1"
)
THIS_SLICE = "11.14.LIVE_SUBMIT_ACK_CONTRACT_AND_MUTATION_BOUNDARY_FORENSIC_ADJUDICATION"
PREDECESSOR_SLICE = "11.14.LIVE_ORDER_PLAN_OBSERVED_ADJUDICATION"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = (
    "SECTION_11_14_LIVE_SUBMIT_ACK_CONTRACT_AND_MUTATION_BOUNDARY_FORENSIC_ADJUDICATION"
)
CANONICAL_EVIDENCE_RUN_ID = "20260904T144800Z"
CANONICAL_BASE_SHA = "61fbec920741b3c6631e15723092e3b262740c4e"
EXPECTED_ORIGIN_MAIN_SHA = CANONICAL_BASE_SHA
IMPLEMENTATION_SHA = CANONICAL_BASE_SHA
HISTORICAL_ORDER_PLAN_SHA = "eca62c687d7fb42d0fa11c645d5f70bb26916c55"
HISTORICAL_ORDER_PLAN_RUN_ID = "20260904T140500Z"
HISTORICAL_PRIVATE_READ_ONLY_SHA = "6930807523ea7af3aff8cc653d335d5719d38d25"
HISTORICAL_PRIVATE_READ_ONLY_RUN_ID = "20260904T133200Z"
HISTORICAL_PATH_REACHABLE_SHA = "fa02c54468cc0320fe8c756bb4da08485fb84597"
HISTORICAL_PATH_REACHABLE_RUN_ID = "20260904T130000Z"
HISTORICAL_CODE_EXISTS_SHA = "b09cac11f0eaecfc5c6f5c97e8b23e808e186b9a"
HISTORICAL_CODE_EXISTS_RUN_ID = "20260904T123100Z"
HISTORICAL_OFFLINE_SURFACE_SHA = "a558c108617d40c12bd1d8c480a6e5d797ccb308"
HISTORICAL_OFFLINE_SURFACE_RUN_ID = "20260904T121000Z"
G12_STATUS_REQUIRED = "CLOSED_LIVE_FLATTEN_PROVABILITY_PROVEN"

CANONICAL_RUNBOOK_PATH = "docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md"
CANONICAL_SECTION_HEADING = "## 11.14 Live order and economic evidence ladder"
CANONICAL_OFFLINE_SLICE_HEADING = "### 11.14 OFFLINE_EVIDENCE_LADDER_SURFACE"
CANONICAL_CODE_EXISTS_SLICE_HEADING = "### 11.14 LIVE_EXECUTION_CODE_EXISTS_ADJUDICATION"
CANONICAL_PATH_REACHABLE_SLICE_HEADING = "### 11.14 LIVE_EXECUTION_PATH_REACHABLE_ADJUDICATION"
CANONICAL_PRIVATE_READ_ONLY_SLICE_HEADING = "### 11.14 LIVE_PRIVATE_READ_ONLY_PROVEN_ADJUDICATION"
CANONICAL_ORDER_PLAN_OBSERVED_SLICE_HEADING = "### 11.14 LIVE_ORDER_PLAN_OBSERVED_ADJUDICATION"
CANONICAL_SUBMIT_ACK_FORENSIC_SLICE_HEADING = (
    "### 11.14 LIVE_SUBMIT_ACK_CONTRACT_AND_MUTATION_BOUNDARY_FORENSIC_ADJUDICATION"
)

LADDER_FIELDS: tuple[str, ...] = (
    "LIVE_EXECUTION_CODE_EXISTS",
    "LIVE_EXECUTION_PATH_REACHABLE",
    "LIVE_PRIVATE_READ_ONLY_PROVEN",
    "LIVE_ORDER_PLAN_OBSERVED",
    "LIVE_SUBMIT_ACK_OBSERVED",
    "LIVE_FILL_OBSERVED",
    "LIVE_FEE_OBSERVED",
    "LIVE_POSITION_RECONCILED",
    "LIVE_ACCOUNTING_RECONSTRUCTED",
    "LIVE_RESTART_RECONSTRUCTED",
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED",
    "LIVE_END_TO_END_EVIDENCE_PROVEN",
)
LADDER_FIELD_COUNT = 12

OBSERVED_OR_PROVEN_FIELDS_MUST_REMAIN_FALSE: tuple[str, ...] = (
    "LIVE_SUBMIT_ACK_OBSERVED",
    "LIVE_FILL_OBSERVED",
    "LIVE_FEE_OBSERVED",
    "LIVE_POSITION_RECONCILED",
    "LIVE_ACCOUNTING_RECONSTRUCTED",
    "LIVE_RESTART_RECONSTRUCTED",
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED",
    "LIVE_END_TO_END_EVIDENCE_PROVEN",
)

LIVE_EXECUTION_CODE_EXISTS = True
LIVE_EXECUTION_PATH_REACHABLE = True
LIVE_PRIVATE_READ_ONLY_PROVEN = True
LIVE_ORDER_PLAN_OBSERVED = True
LIVE_SUBMIT_ACK_OBSERVED = False
LIVE_FILL_OBSERVED = False
LIVE_FEE_OBSERVED = False
LIVE_POSITION_RECONCILED = False
LIVE_ACCOUNTING_RECONSTRUCTED = False
LIVE_RESTART_RECONSTRUCTED = False
LIVE_AUTONOMOUS_RECOVERY_OBSERVED = False
LIVE_END_TO_END_EVIDENCE_PROVEN = False

LADDER_FIELD_DEFAULTS: dict[str, bool] = {
    "LIVE_EXECUTION_CODE_EXISTS": LIVE_EXECUTION_CODE_EXISTS,
    "LIVE_EXECUTION_PATH_REACHABLE": LIVE_EXECUTION_PATH_REACHABLE,
    "LIVE_PRIVATE_READ_ONLY_PROVEN": LIVE_PRIVATE_READ_ONLY_PROVEN,
    "LIVE_ORDER_PLAN_OBSERVED": LIVE_ORDER_PLAN_OBSERVED,
    "LIVE_SUBMIT_ACK_OBSERVED": LIVE_SUBMIT_ACK_OBSERVED,
    "LIVE_FILL_OBSERVED": LIVE_FILL_OBSERVED,
    "LIVE_FEE_OBSERVED": LIVE_FEE_OBSERVED,
    "LIVE_POSITION_RECONCILED": LIVE_POSITION_RECONCILED,
    "LIVE_ACCOUNTING_RECONSTRUCTED": LIVE_ACCOUNTING_RECONSTRUCTED,
    "LIVE_RESTART_RECONSTRUCTED": LIVE_RESTART_RECONSTRUCTED,
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED": LIVE_AUTONOMOUS_RECOVERY_OBSERVED,
    "LIVE_END_TO_END_EVIDENCE_PROVEN": LIVE_END_TO_END_EVIDENCE_PROVEN,
}

# Exact SSOT names from Master Runbook §11.14 (lines 60698-60719). Count=20.
# Prior pre-auth census reported 19; that count is not used.
MANDATORY_LIVE_METRICS: tuple[str, ...] = (
    "orders_planned",
    "orders_submitted",
    "orders_acknowledged",
    "orders_rejected",
    "orders_unknown",
    "partial_fills",
    "fills",
    "cancels",
    "amends",
    "duplicate_submit_prevented",
    "fees_paid",
    "funding_paid_or_received",
    "realized_pnl",
    "unrealized_pnl",
    "margin_utilization",
    "reconciliation_divergences",
    "autonomous_recoveries",
    "degradation_transitions",
    "kill_switch_events",
    "owner_interventions",
)
MANDATORY_LIVE_METRIC_COUNT = 20
PRIOR_CENSUS_REPORTED_METRIC_COUNT = 19
METRIC_COUNT_DISCREPANCY_VS_PRIOR_CENSUS = True

FORBIDDEN_LIVE_SOURCE_KINDS: tuple[str, ...] = (
    "FIXTURE",
    "SIMULATION",
    "SIMULATED",
    "TESTNET",
    "PAPER",
    "SHADOW",
    "DEMO",
)
ADMISSIBLE_OFFLINE_SOURCE_KINDS: tuple[str, ...] = (
    "CANONICAL_RUNBOOK",
    "REPOSITORY_IMPLEMENTATION",
    "PREDECESSOR_EVIDENCE",
    "GOVERNED_OFFLINE_CONTRACT",
    "GOVERNED_CURRENT_PRIVATE_GET",
    "GOVERNED_CURRENT_GATED_SUBMIT_PATH",
)

SECTION_11_14_AUTHORIZED = False
SECTION_11_14_COMPLETE = False
SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED = False
SECTION_11_14_LIVE_EVIDENCE_COLLECTION_AUTHORIZED = False
SECTION_11_14_OFFLINE_SURFACE_BOUND = True
LIVE_AUTHORIZED = False
LIVE_ENABLED = False
LIVE_ARMED = False
SUBMIT_UNLOCKED = False
CANARY_AUTHORIZED = False
TESTNET_AUTHORIZED = False
POST_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
CANCEL_ALLOWED = False
AMEND_ALLOWED = False
FLATTEN_EXECUTE_ALLOWED = False
FUNDING_ALLOWED = False
CREDENTIAL_USE_ALLOWED = True
PUBLIC_GET_ALLOWED = True
PRIVATE_GET_ALLOWED = True
COLLECTOR_ACTIVATED = False
AUTHORIZED_PRODUCTIVE_SUBMIT_COUNT_MAX = 1
RETRY_DEFAULT = False
SECOND_SUBMIT_DEFAULT = False
TIMEOUT_MUST_NOT_AUTO_POST = True
TRANSPORT_OK_IS_NOT_LIVE_SUBMIT_ACK_OBSERVED = True
HISTORICAL_ORDER_PLAN_ARTIFACT_REUSE_FOR_POST = False
LIVE_SUBMIT_ACK_OBSERVED_PRODUCER_BOUND = False
LIVE_SUBMIT_ACK_PROOF_CRITERION_BOUND = False
CASE_ADJUDICATION = "CASE_C_CANONICAL_SEMANTIC_GAP"

REUSE_CLASSIFICATIONS: tuple[str, ...] = (
    "REUSABLE_AS_IDENTICAL_11_14_FACT",
    "SUPPORTING_CONTEXT_ONLY",
    "HISTORICAL_ONLY",
    "SEMANTICALLY_DIFFERENT",
    "REQUIRES_FRESH_OBSERVATION",
    "REQUIRES_OWNER_POLICY_DECISION",
    "CONTRADICTORY",
    "NOT_APPLICABLE",
    "CURRENT_AND_ADMISSIBLE",
    "CURRENT_BUT_INSUFFICIENT",
    "STALE_FOR_REACHABILITY",
)

EARLIEST_UNRESOLVED_DEPENDENCY = "LIVE_SUBMIT_ACK_OBSERVED"
NEXT_AUTHORITY_BOUNDARY = "LIVE_SUBMIT_ACK_OBSERVED_PROOF_CRITERION"
NEXT_OWNER_GO_REQUIRED = "OWNER_GO_TO_BIND_LIVE_SUBMIT_ACK_OBSERVED_PROOF_CRITERION_BEFORE_ANY_POST"
SESSION_LIVE_GATE_ACTIVATION_AUTHORIZED = False
STANDING_LIVE_GATES_MUST_REMAIN_FALSE = True
POST_REQUIRED_FOR_LIVE_ORDER_PLAN_OBSERVED = False
CANARY_TECHNICAL_EXECUTE_TOKEN = "OWNER_GO_LIVE_CANARY_MINIMUM_EXPOSURE"
G12_DOES_NOT_AUTHORIZE_SECTION_11_14 = True
G12_DOES_NOT_SATISFY_SECTION_11_14_OBSERVED_FIELDS = True
CURRENTLY_REACHABLE_IS_NOT_LIVE_EXECUTION_PATH_REACHABLE = True
LIVE_RECONCILIATION_PROVEN_IS_NOT_LIVE_POSITION_RECONCILED = True
FIELD_NAME_SIMILARITY_IS_NOT_SEMANTIC_IDENTITY = True
HISTORICAL_EVIDENCE_IS_NOT_CURRENT_TRUTH = True
CODE_PRESENCE_IS_NOT_LIVE_EXECUTION_CODE_EXISTS = True
HISTORICAL_CODE_IS_NOT_LIVE_EXECUTION_CODE_EXISTS = True
FIXTURE_TESTNET_SIM_IS_NOT_LIVE_EXECUTION_CODE_EXISTS = True
LIVE_EXECUTION_CODE_EXISTS_DOES_NOT_IMPLY_PATH_REACHABLE = True
LIVE_EXECUTION_CODE_EXISTS_DOES_NOT_IMPLY_AUTHORIZATION = True
LIVE_EXECUTION_PATH_REACHABLE_DOES_NOT_IMPLY_SUBMIT_AUTHORIZATION = True
LIVE_EXECUTION_PATH_REACHABLE_DOES_NOT_IMPLY_PRIVATE_READ_ONLY_PROVEN = True
LIVE_PRIVATE_READ_ONLY_PROVEN_DOES_NOT_IMPLY_ORDER_PLAN_OBSERVED = True
LIVE_PRIVATE_READ_ONLY_PROVEN_DOES_NOT_IMPLY_SUBMIT_AUTHORIZATION = True
HISTORICAL_PRIVATE_READ_ONLY_IS_NOT_CURRENT = True
SINGLE_REACHABILITY_GET_IS_NOT_PRIVATE_READ_ONLY_PROVEN = True
SECTION_11_13_2_TRADE_FALSE_IS_NOT_A_1114_CONJUNCT = True
BLOCKED_DRY_RUN_IS_NOT_LIVE_ORDER_PLAN_OBSERVED = True
HISTORICAL_GET_IS_NOT_CURRENT_REACHABLE = True
CREDENTIAL_PRESENCE_IS_NOT_AUTHENTICATION_SUCCESS = True
AUTHENTICATION_SUCCESS_IS_NOT_SUBMIT_AUTHORIZATION = True
VENUE_CONNECTIVITY_IS_NOT_LATER_LADDER_FIELD = True
NO_TESTNET_FIXTURE_OR_SIMULATED_RESULT_MAY_SATISFY_A_LIVE_EVIDENCE_FIELD = True
LIVE_EXECUTION_CODE_EXISTS_CANONICAL_DEFINITION = (
    "LIVE_EXECUTION_CODE_EXISTS is the first §11.14 Live proof-claim field. "
    "It is true iff current origin/main contains a complete, integrated, "
    "non-historical, non-fixture, non-testnet, non-simulated static call graph "
    "from the canonical Live canary execution decision/gate boundary through "
    "order-plan consumption, venue-native payload construction including "
    "client-order-id, fail-closed submit gates, the Live HTTP execution port, "
    "and UrllibLiveCanaryTransportV1.send. File presence alone, historical "
    "implementation, Cap 11.7-11.11 contracts-only constants, and §4.9 "
    "CURRENTLY_REACHABLE are each insufficient. True does not imply "
    "LIVE_EXECUTION_PATH_REACHABLE, authorization, credential availability, "
    "runtime observation, or any later ladder field."
)
LIVE_EXECUTION_PATH_REACHABLE_CANONICAL_DEFINITION = (
    "LIVE_EXECUTION_PATH_REACHABLE is the second §11.14 Live proof-claim field. "
    "It is true iff every bound PART_OF_REACHABILITY constituent is proven: "
    "the current productive Live canary static graph is complete and the "
    "entrypoint is integrated and selectable; fail-closed submit gates are "
    "evaluable; UrllibLiveCanaryTransportV1 is constructible; required SecretRef "
    "credential material is present without value disclosure; the production "
    "EEA host is currently connectable; a current authenticated private GET "
    "proves functional authentication and account/venue read access; and no "
    "static blocker prevents reaching the pre-submit boundary "
    "(refuse_submit_unless_gates_pass_v1). Submit-authorization gates "
    "(LIVE_ENABLED, LIVE_ARMED, SUBMIT_UNLOCKED, CANARY_AUTHORIZED, "
    "LIVE_AUTHORIZED, Owner execute-permit, SECTION_11_14_AUTHORIZED) are not "
    "constituents. File presence, LIVE_EXECUTION_CODE_EXISTS, §4.9 "
    "CURRENTLY_REACHABLE, historical GET success, credential presence alone, "
    "configured defaults, and fixture/testnet/sim sources are each insufficient. "
    "True does not promote LIVE_PRIVATE_READ_ONLY_PROVEN, LIVE_ORDER_PLAN_OBSERVED, "
    "any later ladder field, submit authorization, or POST."
)
LIVE_PRIVATE_READ_ONLY_PROVEN_CANONICAL_DEFINITION = (
    "LIVE_PRIVATE_READ_ONLY_PROVEN is the third §11.14 Live proof-claim field. "
    "It is true iff LIVE_EXECUTION_CODE_EXISTS and LIVE_EXECUTION_PATH_REACHABLE "
    "are already true and current authenticated private GET "
    "/api/v5/account/config and GET /api/v5/account/balance each return HTTP 200 "
    "and OKX code 0 with parseable account data, both methods are GET, no POST "
    "occurs, and no redirect is followed. A single reachability GET, historical "
    "§11.13.2 LIVE_PRIVATE_READ_ONLY_PROVEN, credential presence alone, "
    "fixture/testnet/sim sources, and the §11.13.2 TRADE=false owner attestation "
    "are each insufficient. True does not promote LIVE_ORDER_PLAN_OBSERVED, "
    "submit authorization, POST, Live-gate mutation, or any later ladder field."
)
LIVE_ORDER_PLAN_OBSERVED_CANONICAL_DEFINITION = (
    "LIVE_ORDER_PLAN_OBSERVED is the fourth §11.14 Live proof-claim field. "
    "It is true iff a current Live canary order-plan artifact is produced on "
    "the productive submit path after refuse_submit_unless_gates_pass_v1 from "
    "current venue-derived inputs. Static builder presence, a blocked dry-run, "
    "and §11.13.4 LIVE_DRY_RUN_ORDER_PLAN_PROVEN are each insufficient. True "
    "does not imply LIVE_SUBMIT_ACK_OBSERVED or POST authorization by itself."
)
LIVE_SUBMIT_ACK_OBSERVED_CANONICAL_STATUS = (
    "LIVE_SUBMIT_ACK_OBSERVED is the fifth §11.14 Live proof-claim field. "
    "The Master Runbook currently states only that canonical ACK requires POST "
    "of the observed plan. No §11.14 proof criterion is bound for HTTP status, "
    "venue code, sCode, ordId, or clOrdId. The productive transport ok predicate "
    "and Cap 11.12.8 / flatten / lifecycle ACK handlers are not this field. "
    "No producer may set the field true under this forensic GO. True is not "
    "adjudicated. POST remains unauthorized."
)
STATIC_EXECUTION_GRAPH_FILENAME = "STATIC_EXECUTION_GRAPH.json"
COMPONENT_CLASSIFICATION_FILENAME = "COMPONENT_CLASSIFICATION.json"

EVIDENCE_DIRNAME = "section_11_14_live_order_and_economic_evidence_ladder_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
CLAIMS_FILENAME = "claims.json"
SUMMARY_FILENAME = "SUMMARY.json"
ADJUDICATION_FILENAME = "ADJUDICATION.json"
TRACEABILITY_FILENAME = "TRACEABILITY.json"
REUSE_MATRIX_FILENAME = "REUSE_VS_FRESH.json"
METRICS_SCHEMA_FILENAME = "MANDATORY_LIVE_METRICS_SCHEMA.json"
LADDER_STATE_FILENAME = "LADDER_STATE.json"
LINEAGE_FILENAME = "LINEAGE.json"
STATIC_FIELD_PROOF_FILENAME = "STATIC_FIELD_ADJUDICATION.json"
MUTATION_BOUNDARY_FILENAME = "MUTATION_BOUNDARY.json"
CONSTITUENT_MATRIX_FILENAME = "CONSTITUENT_MATRIX.json"
STATIC_REACHABILITY_GRAPH_FILENAME = "STATIC_REACHABILITY_GRAPH.json"
RUNTIME_DEPENDENCY_GRAPH_FILENAME = "RUNTIME_DEPENDENCY_GRAPH.json"
AUTHORITY_BOUNDARY_MAP_FILENAME = "AUTHORITY_BOUNDARY_MAP.json"
RUNTIME_GATE_CLASSIFICATION_FILENAME = "RUNTIME_GATE_CLASSIFICATION.json"
PRIVATE_GET_BINDING_FILENAME = "PRIVATE_GET_BINDING.json"
PRIVATE_GET_EVIDENCE_FILENAME = "PRIVATE_GET.sanitized.json"
PATH_REACHABLE_ADJUDICATION_FILENAME = "PATH_REACHABLE_ADJUDICATION.json"
PRIVATE_READ_ONLY_GET_BINDING_FILENAME = "PRIVATE_READ_ONLY_GET_BINDING.json"
PRIVATE_READ_ONLY_GET_EVIDENCE_FILENAME = "PRIVATE_READ_ONLY_GET.sanitized.json"
PRIVATE_READ_ONLY_ADJUDICATION_FILENAME = "PRIVATE_READ_ONLY_ADJUDICATION.json"
LATER_FIELD_CENSUS_FILENAME = "LATER_FIELD_CENSUS.json"
ORDER_PLAN_OBSERVED_ADJUDICATION_FILENAME = "ORDER_PLAN_OBSERVED_ADJUDICATION.json"
ORDER_PLAN_EVIDENCE_FILENAME = "ORDER_PLAN.sanitized.json"
GATE_STATE_FILENAME = "GATE_STATE.json"
PREFLIGHT_FILENAME = "PREFLIGHT.json"
SUBMIT_ACK_CONTRACT_FILENAME = "SUBMIT_ACK_CONTRACT.json"
SUBMIT_ACK_FAILURE_MATRIX_FILENAME = "SUBMIT_ACK_FAILURE_MATRIX.json"
SUBMIT_ACK_ADJUDICATION_FILENAME = "SUBMIT_ACK_ADJUDICATION.json"
EXACT_MUTATION_CONTRACT_FILENAME = "EXACT_MUTATION_CONTRACT.json"
POST_SUBMIT_RECON_FILENAME = "POST_SUBMIT_RECON.json"

SP01_PATH = "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/http_client_v1.py"
FLATTEN_EXECUTE_PATH = (
    "src/ops/section_11_13_5_productive_flatten_post_and_reconciliation_v1/execute_v1.py"
)
CANARY_SUBMIT_TRANSPORT_PATH = (
    "src/ops/section_11_13_5_live_canary_minimum_exposure_v1/submit_transport_v1.py"
)
SECTION_4_9_ANCHOR = "docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md §4.9.4 SP-01"
