"""Static claims for the offline §11.14 surface pack."""

from __future__ import annotations

from src.ops.section_11_14_live_order_and_economic_evidence_ladder_v1.constants_v1 import (
    CANONICAL_BASE_SHA,
    COLLECTOR_ACTIVATED,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    LADDER_FIELD_DEFAULTS,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    NEXT_OWNER_GO_REQUIRED,
    OWNER_GO,
    SECTION_11_14_AUTHORIZED,
    SECTION_11_14_COMPLETE,
    SECTION_11_14_LIVE_EVIDENCE_COLLECTION_AUTHORIZED,
    SECTION_11_14_OFFLINE_SURFACE_BOUND,
    SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED,
    SUBMIT_UNLOCKED,
    THIS_SLICE,
    WORKPACKAGE_ID,
)

CLAIMS: dict[str, object] = {
    "OWNER_GO": OWNER_GO,
    "THIS_SLICE": THIS_SLICE,
    "WORKPACKAGE_ID": WORKPACKAGE_ID,
    "CANONICAL_BASE_SHA": CANONICAL_BASE_SHA,
    "SECTION_11_14_AUTHORIZED": SECTION_11_14_AUTHORIZED,
    "SECTION_11_14_COMPLETE": SECTION_11_14_COMPLETE,
    "SECTION_11_14_OFFLINE_SURFACE_BOUND": SECTION_11_14_OFFLINE_SURFACE_BOUND,
    "SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED": (SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED),
    "SECTION_11_14_LIVE_EVIDENCE_COLLECTION_AUTHORIZED": (
        SECTION_11_14_LIVE_EVIDENCE_COLLECTION_AUTHORIZED
    ),
    "LIVE_AUTHORIZED": LIVE_AUTHORIZED,
    "LIVE_ENABLED": LIVE_ENABLED,
    "LIVE_ARMED": LIVE_ARMED,
    "SUBMIT_UNLOCKED": SUBMIT_UNLOCKED,
    "COLLECTOR_ACTIVATED": COLLECTOR_ACTIVATED,
    "POST_PERFORMED": False,
    "GET_PERFORMED": False,
    "CREDENTIAL_USE": False,
    "SECRET_VALUES_INCLUDED": False,
    "AUTHORITY": "NONE_FOR_EVIDENCE_ARTIFACTS",
    "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
    "NEXT_OWNER_GO_REQUIRED": NEXT_OWNER_GO_REQUIRED,
    **LADDER_FIELD_DEFAULTS,
}
