"""Census of productive and historically relevant position/quantity producers.

Callgraph and value-origin classified. Naming match is not identity.
Does not write. Does not GET. Does not POST.
"""

from __future__ import annotations

from typing import Any

_REJECTED = "POS_DERIVATION_REJECTED"
_UNPROVEN = "POS_DERIVATION_UNPROVEN"


def _row(
    *,
    producer_id: str,
    path: str,
    symbol: str,
    value_semantics: str,
    source_kind: str,
    pre_submit_or_post_submit: str,
    pre_ack_or_post_ack: str,
    pre_fill_or_post_fill: str,
    peak_trade_owned: bool,
    venue_owned: bool,
    accounting_only: bool,
    durable: bool,
    contemporaneous: bool,
    live_path: bool,
    testnet_only: bool,
    simulation_only: bool,
    can_satisfy: bool,
    why: str,
    evidence: str,
    disposition: str,
) -> dict[str, Any]:
    return {
        "PRODUCER_ID": producer_id,
        "PATH": path,
        "SYMBOL": symbol,
        "VALUE_SEMANTICS": value_semantics,
        "SOURCE_KIND": source_kind,
        "PRE_SUBMIT_OR_POST_SUBMIT": pre_submit_or_post_submit,
        "PRE_ACK_OR_POST_ACK": pre_ack_or_post_ack,
        "PRE_FILL_OR_POST_FILL": pre_fill_or_post_fill,
        "PEAK_TRADE_OWNED": peak_trade_owned,
        "VENUE_OWNED": venue_owned,
        "ACCOUNTING_ONLY": accounting_only,
        "DURABLE": durable,
        "CONTEMPORANEOUS": contemporaneous,
        "LIVE_PATH": live_path,
        "TESTNET_ONLY": testnet_only,
        "SIMULATION_ONLY": simulation_only,
        "CAN_SATISFY_SECTION_11_14_POS": can_satisfy,
        "WHY": why,
        "EVIDENCE": evidence,
        "DISPOSITION": disposition,
    }


_POS_PRODUCERS: tuple[dict[str, Any], ...] = (
    _row(
        producer_id="ORDER_PLAN_QTY",
        path="src/ops/section_11_13_5_live_canary_minimum_exposure_v1/order_plan_v1.py",
        symbol="LiveCanaryOrderPlanV1 / sz",
        value_semantics="intended_order_size_contracts",
        source_kind="PEAK_TRADE_ORDER_PLAN",
        pre_submit_or_post_submit="PRE_SUBMIT",
        pre_ack_or_post_ack="PRE_ACK",
        pre_fill_or_post_fill="PRE_FILL",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=False,
        contemporaneous=True,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Submitted/planned sz is not handoff pos. Authority does not equate them.",
        evidence="VENUE_NATIVE_BODY_KEYS sz; FILL_IS_NOT_POSITION_PROOF; POS_SEMANTICS=UNPROVEN",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="SUBMITTED_ORDER_SZ",
        path="src/ops/section_11_13_5_live_canary_minimum_exposure_v1/http_client_v1.py",
        symbol="CANARY_VENUE_NATIVE_REQUEST_FIELDS_V1.sz",
        value_semantics="wire_submitted_order_size",
        source_kind="PEAK_TRADE_WIRE_BODY",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="PRE_ACK",
        pre_fill_or_post_fill="PRE_FILL",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=False,
        contemporaneous=True,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Wire sz is submitted quantity, not filled or venue position.",
        evidence="extract_canary_venue_native_request_evidence_v1; submitted quantity != filled position",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="ACKNOWLEDGED_ORDER_SZ",
        path="src/ops/section_11_13_5_live_canary_minimum_exposure_v1/http_client_v1.py",
        symbol="OKX_ORDER_DATA_ENTRY_FIELDS_V1",
        value_semantics="absent_from_ack_allowlist",
        source_kind="LIVE_ACK_DATA_ENTRY",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="PRE_FILL",
        peak_trade_owned=True,
        venue_owned=True,
        accounting_only=False,
        durable=False,
        contemporaneous=True,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="ACK allowlist is sCode,sMsg,ordId,clOrdId,tag. sz and pos are omitted.",
        evidence="OKX_ORDER_DATA_ENTRY_FIELDS_V1; _entry_submit_returned_payload_v1",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="FILL_SZ",
        path="src/ops/section_11_14_live_order_and_economic_evidence_ladder_v1/fill_observed_predicate_v1.py",
        symbol="fillSz",
        value_semantics="venue_reported_executed_fill_quantity",
        source_kind="GOVERNED_CURRENT_PRIVATE_GET",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="POST_FILL",
        peak_trade_owned=False,
        venue_owned=True,
        accounting_only=False,
        durable=True,
        contemporaneous=False,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Fill quantity is not position proof and is a venue GET artifact.",
        evidence="LIVE_FILL_OBSERVED_CANONICAL_DEFINITION; FILL_IS_NOT_POSITION_PROOF",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="ACCUMULATED_FILLS",
        path="src/ops/section_11_13_5_live_canary_minimum_exposure_v1/flatten_post_submit_evidence_state_v1.py",
        symbol="accFillSz",
        value_semantics="accumulated_venue_fill_quantity",
        source_kind="VENUE_ORDER_STATE",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="POST_FILL",
        peak_trade_owned=False,
        venue_owned=True,
        accounting_only=False,
        durable=False,
        contemporaneous=False,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Accumulated fills remain fill quantity, not handoff pos.",
        evidence="FILL_IS_NOT_POSITION_PROOF; ORDER_STATE_IS_NOT_POSITION_PROOF",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="POSITION_GET_POS",
        path="src/ops/section_11_14_live_order_and_economic_evidence_ladder_v1/position_reconciled_predicate_v1.py",
        symbol="ADMISSIBLE_POS_FIELD=pos",
        value_semantics="venue_native_GET_account_positions_pos",
        source_kind="GOVERNED_CURRENT_PRIVATE_GET",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="POST_FILL",
        peak_trade_owned=False,
        venue_owned=True,
        accounting_only=True,
        durable=True,
        contemporaneous=False,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Venue GET pos is LIVE_POSITION_RECONCILED, not contemporaneous Peak_Trade handoff.",
        evidence="VENUE_GET_COPY_IS_NOT_CONTEMPORANEOUS_HANDOFF; POSITION_IS_NOT_RESTART_PROOF",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="ACCOUNTING_POSITION",
        path="src/ops/section_11_14_live_order_and_economic_evidence_ladder_v1/accounting_reconstructed_predicate_v1.py",
        symbol="position.pos via accounting reconstruction",
        value_semantics="accounting_reconstructed_from_venue_get_path",
        source_kind="GOVERNED_PERSISTED_IDENTITY_BOUND_LIVE_ECONOMIC_PATH",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="POST_FILL",
        peak_trade_owned=False,
        venue_owned=True,
        accounting_only=True,
        durable=True,
        contemporaneous=False,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Accounting reconstruction is predecessor, not restart handoff.",
        evidence="ACCOUNTING_ONLY_IS_NOT_RESTART; ACCOUNTING_RECONSTRUCTION_IS_PREDECESSOR_NOT_RESTART",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="PRODUCTIVE_PORTFOLIO",
        path="src/portfolio/base.py",
        symbol="get_position",
        value_semantics="internal_portfolio_units",
        source_kind="INTERNAL_PORTFOLIO",
        pre_submit_or_post_submit="UNKNOWN",
        pre_ack_or_post_ack="UNKNOWN",
        pre_fill_or_post_fill="UNKNOWN",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=True,
        durable=False,
        contemporaneous=False,
        live_path=False,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Portfolio position is accounting/internal state, not Live handoff pos.",
        evidence="ACCOUNTING_ONLY_IS_NOT_RESTART; no Live canary durable_state writer",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="EXECUTION_LEDGER",
        path="src/learning/deterministic_decision_outcome_v0/",
        symbol="DDO_DURABLE_EVIDENCE_STORAGE_OWNER",
        value_semantics="observation_ledger",
        source_kind="DDO_LEDGER",
        pre_submit_or_post_submit="UNKNOWN",
        pre_ack_or_post_ack="UNKNOWN",
        pre_fill_or_post_fill="UNKNOWN",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=True,
        contemporaneous=False,
        live_path=False,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="DDO ledger is observation-only. Forbidden owner reuse.",
        evidence="FORBIDDEN_OWNER_REUSE DDO_DURABLE_EVIDENCE_STORAGE_OWNER",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="RECONCILIATION_BUNDLE",
        path="src/ops/section_11_14_live_order_and_economic_evidence_ladder_v1/position_reconciled_adjudication_v1.py",
        symbol="adjudicate_live_position_reconciled_v1",
        value_semantics="position_reconciliation_claim",
        source_kind="SECTION_11_14_EVIDENCE_PACKS",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="POST_FILL",
        peak_trade_owned=False,
        venue_owned=True,
        accounting_only=True,
        durable=True,
        contemporaneous=False,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Evidence packs are forensic artifacts, not control handoff.",
        evidence="NO_RECLASSIFICATION_OF_EVIDENCE_PACK_AS_CONTROL_HANDOFF",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="SIDESTATE",
        path="src/ops/wallclock_full_canonical_decision_to_simulated_economics_runtime_bridge_v1/sidestate_restore_v1.py",
        symbol="Cap 7.2 SideState",
        value_semantics="strategy_lifecycle_side_state",
        source_kind="CAP_72_SIDESTATE_PERSIST",
        pre_submit_or_post_submit="UNKNOWN",
        pre_ack_or_post_ack="UNKNOWN",
        pre_fill_or_post_fill="UNKNOWN",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=True,
        contemporaneous=False,
        live_path=False,
        testnet_only=False,
        simulation_only=True,
        can_satisfy=False,
        why="SideState is strategy lifecycle, not Live submit-identity handoff.",
        evidence="FORBIDDEN_OWNER_REUSE CAP_72_SIDESTATE_PERSIST",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="ORDER_LIFECYCLE_STATE",
        path="src/ops/section_11_14_live_order_and_economic_evidence_ladder_v1/submit_ack_observed_predicate_v1.py",
        symbol="LIVE_SUBMIT_ACK_OBSERVED / order-state",
        value_semantics="ack_or_order_state_label",
        source_kind="ORDER_LIFECYCLE",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="PRE_FILL",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=False,
        contemporaneous=True,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Order-state is not position proof and does not produce pos.",
        evidence="ORDER_STATE_IS_NOT_POSITION_PROOF",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="VENUE_POSITION_SNAPSHOT",
        path="src/ops/section_11_13_5_live_canary_minimum_exposure_v1/pre_submit_state_v1.py",
        symbol="observe_target_position_flatten_candidate_v1 / row.pos",
        value_semantics="pre_submit_or_reobservation_venue_pos",
        source_kind="VENUE_GET",
        pre_submit_or_post_submit="PRE_SUBMIT",
        pre_ack_or_post_ack="PRE_ACK",
        pre_fill_or_post_fill="PRE_FILL",
        peak_trade_owned=False,
        venue_owned=True,
        accounting_only=False,
        durable=False,
        contemporaneous=False,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Fresh venue GET is not contemporaneous handoff.",
        evidence="VENUE_GET_COPY_IS_NOT_CONTEMPORANEOUS_HANDOFF",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="SIMULATED_EXECUTION_POSITION",
        path="src/ops/wallclock_full_canonical_decision_to_simulated_economics_runtime_bridge_v1/",
        symbol="SimulatedExecutionPort position",
        value_semantics="internal_simulated_position",
        source_kind="SIMULATED_EXECUTION",
        pre_submit_or_post_submit="UNKNOWN",
        pre_ack_or_post_ack="UNKNOWN",
        pre_fill_or_post_fill="UNKNOWN",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=False,
        contemporaneous=False,
        live_path=False,
        testnet_only=False,
        simulation_only=True,
        can_satisfy=False,
        why="No Testnet, fixture or simulated result may satisfy a Live evidence field.",
        evidence="NO_TESTNET_FIXTURE_OR_SIMULATED_RESULT_MAY_SATISFY_A_LIVE_EVIDENCE_FIELD",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="LIVE_CANARY_RETURN_PAYLOAD",
        path="src/ops/section_11_13_5_live_canary_minimum_exposure_v1/submit_transport_v1.py",
        symbol="_entry_submit_returned_payload_v1",
        value_semantics="partial_ack_identity_plus_plan",
        source_kind="CANARY_ACK_RETURN",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="PRE_FILL",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=False,
        contemporaneous=True,
        live_path=True,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="Return payload has ACK identity and plan sz. Complete identity including pos is unproven.",
        evidence="PRE_RESTART_CAPTURE_SEAM=CANARY_ACK_RETURN_PARTIAL_IDENTITY_ONLY",
        disposition=_UNPROVEN,
    ),
    _row(
        producer_id="DURABLE_LIVE_STATE",
        path="NONE",
        symbol="SECTION_11_14_LIVE_DURABLE_STATE_WRITER",
        value_semantics="absent",
        source_kind="ABSENT",
        pre_submit_or_post_submit="NONE",
        pre_ack_or_post_ack="NONE",
        pre_fill_or_post_fill="NONE",
        peak_trade_owned=False,
        venue_owned=False,
        accounting_only=False,
        durable=False,
        contemporaneous=False,
        live_path=False,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="No Live canary durable_state writer exists.",
        evidence="CODE_PATH_CENSUS LIVE_CANARY_DURABLE_STATE_WRITER_EXISTS=false",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="A1_WAL",
        path="src/learning/mutation_critical_control_state_storage_v1/",
        symbol="MUTATION_CRITICAL_CONTROL_STATE_STORAGE_OWNER",
        value_semantics="mutation_critical_control_wal",
        source_kind="A1_WAL",
        pre_submit_or_post_submit="UNKNOWN",
        pre_ack_or_post_ack="UNKNOWN",
        pre_fill_or_post_fill="UNKNOWN",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=True,
        contemporaneous=False,
        live_path=False,
        testnet_only=False,
        simulation_only=False,
        can_satisfy=False,
        why="A1 WAL is not Live identity-bound pre-restart handoff.",
        evidence="A1_WAL_AS_LIVE_HANDOFF_ALLOWED=false",
        disposition=_REJECTED,
    ),
    _row(
        producer_id="TESTNET_DURABLE_STATE",
        path="evidence/ops/section_11_12_testnet_restart_proven_v1/",
        symbol="restart_with_open_position_pre_restart_v1.json",
        value_semantics="testnet_restart_handoff",
        source_kind="TESTNET_CAMPAIGN_DURABLE_STATE",
        pre_submit_or_post_submit="POST_SUBMIT",
        pre_ack_or_post_ack="POST_ACK",
        pre_fill_or_post_fill="POST_FILL",
        peak_trade_owned=True,
        venue_owned=False,
        accounting_only=False,
        durable=True,
        contemporaneous=False,
        live_path=False,
        testnet_only=True,
        simulation_only=False,
        can_satisfy=False,
        why="TESTNET_RESTART_PROVEN is not this Live field.",
        evidence="TESTNET_RESTART_PROVEN_IS_NOT_THIS_FIELD",
        disposition=_REJECTED,
    ),
)


def bind_pos_producer_census_v1() -> dict[str, Any]:
    acceptable = [row for row in _POS_PRODUCERS if row["CAN_SATISFY_SECTION_11_14_POS"] is True]
    rejected = [row for row in _POS_PRODUCERS if row["DISPOSITION"] == _REJECTED]
    unproven = [row for row in _POS_PRODUCERS if row["DISPOSITION"] == _UNPROVEN]
    return {
        "DOCUMENT_CLASS": "SECTION_11_14_POS_PRODUCER_CENSUS_V1",
        "POS_PRODUCER_CANDIDATE_COUNT": len(_POS_PRODUCERS),
        "POS_ACCEPTABLE_PRODUCER_COUNT": len(acceptable),
        "POS_REJECTED_PRODUCER_COUNT": len(rejected),
        "POS_UNPROVEN_PRODUCER_COUNT": len(unproven),
        "CAN_SATISFY_SECTION_11_14_POS_COUNT": len(acceptable),
        "rows": [dict(row) for row in _POS_PRODUCERS],
        "NAMING_MATCH_IS_NOT_SEMANTIC_IDENTITY": True,
    }
