"""CAPABILITY_O5 constants — canonical derived read model + dashboard rebuild."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_O5_CANONICAL_READ_MODEL_AND_MARKET_DASHBOARD_REBUILD_V1"
SCHEMA_VERSION = "o5_canonical_read_model_and_market_dashboard_rebuild_v1"
PACKAGE_MARKER = "CANONICAL_READ_MODEL_AND_MARKET_DASHBOARD_REBUILD_V1=true"

# Derived read-model identity (non-authoritative, non-SSOT).
READ_MODEL_SCHEMA_NAME = "canonical_market_dashboard_read_model.v1"
READ_MODEL_RELATIVE_PATH = "readmodels/canonical_market_dashboard_read_model.v1.json"
READ_MODEL_CLASSIFICATION = "DERIVED"
READ_MODEL_SSOT = False
READ_MODEL_AUTHORITY_EFFECT = "NONE"

# Reuse O4 producer; never create a parallel OHLCV producer.
O4_AUTHORITATIVE_BAR_PRODUCER = "CanonicalPublicMdBarProducerV1"
O4_CANONICAL_NORMALIZED_EVENT_PATH = (
    "NormalizedPublicMarketDataV1+ObservationIdentityV1+DistinctMarketObservationAcceptorV1"
)
DASHBOARD_TRANSPORT = "HTTP_JSON_POLL"
CANONICAL_MARKET_ROUTE = "GET /market"
CANONICAL_OHLCV_API = "GET /api/market/landscape/ohlcv"

# Connection / freshness classifications (dashboard chrome vocabulary).
CONNECTION_HEALTHY = "HEALTHY"
CONNECTION_DEGRADED = "DEGRADED"
CONNECTION_STALE = "STALE"
CONNECTION_DISCONNECTED = "DISCONNECTED"
CONNECTION_MISSING_SOURCE = "MISSING_SOURCE"

CONNECTION_STATES = frozenset(
    {
        CONNECTION_HEALTHY,
        CONNECTION_DEGRADED,
        CONNECTION_STALE,
        CONNECTION_DISCONNECTED,
        CONNECTION_MISSING_SOURCE,
    }
)

# States that must never render as healthy/green.
NON_HEALTHY_RENDER_STATES = frozenset(
    {
        CONNECTION_DEGRADED,
        CONNECTION_STALE,
        CONNECTION_DISCONNECTED,
        CONNECTION_MISSING_SOURCE,
    }
)

# Deterministic freshness thresholds (seconds). Offline / contract defaults.
HEALTHY_MAX_AGE_SECONDS = 30.0
DEGRADED_MAX_AGE_SECONDS = 120.0

# Dashboard lifecycle components (read-only stack).
LIFECYCLE_COMPONENTS = (
    "DASHBOARD_BACKEND",
    "DASHBOARD_FRONTEND",
    "STREAM_OR_POLL_TRANSPORT",
    "READ_MODEL_STORE",
    "HEALTH_ENDPOINT",
)

CLOSED_FROM_O4_DEFERRED = (
    "DURABLE_READ_MODEL_BINDING_CLOSURE",
    "EXPECTED_MISSING_SOURCE_SEMANTICS",
    "DASHBOARD_BACKEND_FRONTEND_LIFECYCLE",
    "DASHBOARD_SUPERVISOR_BINDING",
    "REALTIME_METRICS_UX",
    "STALE_AND_DISCONNECTED_DASHBOARD_CHROME",
    "INSTRUMENT_AND_INTERVAL_UI_REBUILD",
)

SAFETY_INVARIANTS = {
    "CORE_LOGIC_CHANGE_ALLOWED": False,
    "CONFIG_CHANGED_ALLOWED": False,
    "MASTER_V2_CHANGE_ALLOWED": False,
    "DOUBLE_PLAY_CHANGE_ALLOWED": False,
    "BULL_BEAR_CHANGE_ALLOWED": False,
    "DYNAMIC_SCOPE_CHANGE_ALLOWED": False,
    "RISK_AUTHORITY_CHANGE_ALLOWED": False,
    "SAFETY_AUTHORITY_CHANGE_ALLOWED": False,
    "DASHBOARD_TRADING_AUTHORITY": False,
    "READ_MODEL_CLASSIFICATION_DERIVED": True,
    "READ_MODEL_SSOT": False,
    "READ_MODEL_AUTHORITY_EFFECT_NONE": True,
    "PARALLEL_OHLCV_PRODUCER_FORBIDDEN": True,
    "NETWORK_SESSION_ALLOWED": False,
    "AUTHORIZATION_CONSUMPTION_ALLOWED": False,
    "CONFIRM_TOKEN_MINT_ALLOWED": False,
    "ORDERS_ALLOWED": False,
    "EXCHANGE_CREDENTIAL_USE_ALLOWED": False,
    "LIVE_TRADING_ALLOWED": False,
    "TESTNET_ALLOWED": False,
    "REAL_CAPITAL_MOVEMENT_ALLOWED": False,
    "STALE_CANNOT_RENDER_HEALTHY": True,
    "DISCONNECTED_CANNOT_RENDER_HEALTHY": True,
    "NO_INSTRUMENT_CROSS_CONTAMINATION": True,
    "NO_INTERVAL_CROSS_CONTAMINATION": True,
    "DASHBOARD_READ_ONLY": True,
    "DIRECT_ORDER_SUBMIT": False,
    "DIRECT_RUNTIME_STATE_MUTATION": False,
}
