"""Track D03 — offline Market Intelligence forecast/calibration evidence stack (AUTHORITY=NONE)."""

from src.learning.market_intelligence_forecast_calibration_offline_stack_v1.constants_v1 import (
    CAP23_SOLE_PRODUCTIVE_SELECTION_OWNER,
    CONFIDENCE_IS_NOT_AUTHORITY,
    FORECAST_IS_NOT_DECISION,
    GLOBAL_MARKET_INTELLIGENCE_DEFAULT_N,
    MARKET_INTELLIGENCE_TRADING_AUTHORITY,
    MASTER_V2_DOUBLE_PLAY_SOLE_TRADING_AUTHORITY,
    NO_AUTOMATIC_PROMOTION,
    PRODUCTIVE_DDO_FEEDBACK_SEAM_UNCHANGED,
)

__all__ = [
    "CAP23_SOLE_PRODUCTIVE_SELECTION_OWNER",
    "CONFIDENCE_IS_NOT_AUTHORITY",
    "FORECAST_IS_NOT_DECISION",
    "GLOBAL_MARKET_INTELLIGENCE_DEFAULT_N",
    "MARKET_INTELLIGENCE_TRADING_AUTHORITY",
    "MASTER_V2_DOUBLE_PLAY_SOLE_TRADING_AUTHORITY",
    "NO_AUTOMATIC_PROMOTION",
    "PRODUCTIVE_DDO_FEEDBACK_SEAM_UNCHANGED",
]
