"""Failure / reason codes for Cap 2.4 runtime binding."""

from __future__ import annotations

from enum import Enum


class BindingFailureCodeV1(str, Enum):
    NO_SELECTION = "NO_SELECTION"
    SELECTION_MISSING = "SELECTION_MISSING"
    CORRUPT_SELECTION = "CORRUPT_SELECTION"
    SELECTION_DIGEST_MISMATCH = "SELECTION_DIGEST_MISMATCH"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    SELECTION_STALE = "SELECTION_STALE"
    SELECTION_EXPIRED = "SELECTION_EXPIRED"
    SELECTION_NOT_YET_VALID = "SELECTION_NOT_YET_VALID"
    RANKING_SNAPSHOT_MISSING = "RANKING_SNAPSHOT_MISSING"
    RANKING_SNAPSHOT_MISMATCH = "RANKING_SNAPSHOT_MISMATCH"
    RANKING_DIGEST_MISMATCH = "RANKING_DIGEST_MISMATCH"
    UNIVERSE_SNAPSHOT_MISSING = "UNIVERSE_SNAPSHOT_MISSING"
    UNIVERSE_SNAPSHOT_MISMATCH = "UNIVERSE_SNAPSHOT_MISMATCH"
    INSTRUMENT_NOT_GOVERNED = "INSTRUMENT_NOT_GOVERNED"
    INSTRUMENT_NOT_ELIGIBLE = "INSTRUMENT_NOT_ELIGIBLE"
    NATIVE_VENUE_ID_MISMATCH = "NATIVE_VENUE_ID_MISMATCH"
    INSTRUMENT_SUSPENDED = "INSTRUMENT_SUSPENDED"
    INSTRUMENT_EXPIRED = "INSTRUMENT_EXPIRED"
    INSTRUMENT_INVALID = "INSTRUMENT_INVALID"
    MARK_PRICE_MISSING = "MARK_PRICE_MISSING"
    MARKET_DATA_UNAVAILABLE = "MARKET_DATA_UNAVAILABLE"
    DASHBOARD_AUTHORITY_REJECTED = "DASHBOARD_AUTHORITY_REJECTED"
    DASHBOARD_CONFLICTING_INSTRUMENT_IGNORED = "DASHBOARD_CONFLICTING_INSTRUMENT_IGNORED"
    ALLOWLIST_SELECTION_AUTHORITY_REJECTED = "ALLOWLIST_SELECTION_AUTHORITY_REJECTED"
    ALLOWLIST_CONFLICT = "ALLOWLIST_CONFLICT"
    DIRECT_INSTRUMENT_OVERRIDE_REJECTED = "DIRECT_INSTRUMENT_OVERRIDE_REJECTED"
    DUPLICATE_SELECTION_CONSUMER = "DUPLICATE_SELECTION_CONSUMER"
    CONFLICTING_SELECTION_CONSUMER = "CONFLICTING_SELECTION_CONSUMER"
    SELECTED_FUTURE_COUNT_VIOLATION = "SELECTED_FUTURE_COUNT_VIOLATION"
    MAX_POSITIONS_VIOLATION = "MAX_POSITIONS_VIOLATION"
    MULTI_FUTURE_UNAUTHORIZED = "MULTI_FUTURE_UNAUTHORIZED"
    STATE_BLOCKS_NEW_ALPHA = "STATE_BLOCKS_NEW_ALPHA"
    RECONCILIATION_BLOCKED_ALPHA = "RECONCILIATION_BLOCKED_ALPHA"
    RECONCILIATION_HARD_STOP = "RECONCILIATION_HARD_STOP"
    POSITION_TRUTH_MISSING = "POSITION_TRUTH_MISSING"
    ALPHA_BLOCKED = "ALPHA_BLOCKED"
    LIVE_PATH_REACHABLE = "LIVE_PATH_REACHABLE"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"


ALL_FAILURE_CODES = frozenset(code.value for code in BindingFailureCodeV1)
