"""Canonical Shadow runtime enablement v1 — standing safety and mode constants.

Non-activating by default. Does not authorize external effects, Testnet, or Live.
"""

from __future__ import annotations

PACKAGE_MARKER = "CANONICAL_SHADOW_RUNTIME_ENABLEMENT_V1=true"
PRODUCER_FAMILY = "ops.canonical_shadow_runtime_enablement_v1"
CONTRACT_VERSION = "canonical_shadow_runtime_enablement.v1"
SCHEMA_ID = PRODUCER_FAMILY

EXECUTION_LANE_LIVE = "LIVE"
EXECUTION_LANE_SHADOW = "SHADOW"
EXECUTION_LANE_TESTNET = "TESTNET"

LIVE_PRE_EXTERNAL_TERMINAL = True
SHADOW_PRE_EXTERNAL_CONTINUATION = "EXPLICIT_NON_EXTERNAL_ONLY"

SHADOW_RUNTIME_MODE = "SHADOW"
SHADOW_ACTIVATION_OPERATOR_GO = "OWNER_GO_CANONICAL_SHADOW_RUNTIME_BOUNDED_ACTIVATION_V1"

RUNTIME_BRIDGE_STATE_BOUND_NOT_ACTIVATED = "BOUND_NOT_ACTIVATED"
RUNTIME_BRIDGE_STATE_BOUND_READY = "BOUND_READY"
RUNTIME_BRIDGE_STATE_ACTIVATED = "ACTIVATED"

# Standing fail-closed (Shadow lane must never imply these).
LIVE_ENABLED = False
LIVE_ARMED = False
POST_ALLOWED = False
REAL_VENUE_POST_ALLOWED = False
REAL_KEYCHAIN_ACCESS_AUTHORIZED = False
TESTNET_AUTHORIZED = False
EXTERNAL_EFFECT_AUTHORIZED = False
ORDERS_AUTHORIZED = False
WIRE_SEND_AUTHORIZED = False

SHADOW_TO_TESTNET_PROMOTION_COUNT = 0
