name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're experiencing...
        Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: |
        Describe any alternative solutions or features you've considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature affect?
      options:
        - Strategy Development
        - Risk Management
        - Backtesting
        - Live Trading
        - Portfolio Management
        - Data & Analytics
        - CI/CD & DevOps
        - Documentation
        - Testing
        - Performance
        - UI/UX
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking work)
        - High (important for productivity)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Use case 1...
        2. Use case 2...

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits will this feature provide?
      placeholder: |
        - Benefit 1...
        - Benefit 2...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas on how to implement this?
      placeholder: |
        Share any technical ideas or approaches...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have provided clear use cases
          required: true
        - label: I am willing to help implement this feature
          required: false
