"""Assemble the P13 EXECUTION_PREREQUISITE_12 exact flatten payload persist pack."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1.adjudicate_v1 import (
    adjudicate_execution_prerequisite_12_exact_flatten_payload_v1,
)
from src.ops.section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1.constants_v1 import (
    AUTHORIZED_ACCOUNT_UID,
    AUTHORIZED_HOST,
    AUTHORIZED_OPERATION,
    AUTHORIZED_SCOPE,
    CANONICAL_EVIDENCE_RUN_ID,
    CASE_VALUE,
    CLORDID_SOURCE_CLASS_VALUE,
    CONFLICT_COUNT,
    CONTRACT_BOUNDARY_VALUE,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EVIDENCE_DIRNAME,
    EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE,
    EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION,
    EXPECTED_ORIGIN_MAIN_SHA,
    EXACT_PAYLOAD_ALLOWED_KEYS,
    FLATTEN_ORDER_SIDE_RULE,
    LAST_CANONICALLY_CLOSED_STEP,
    NEXT_AUTHORITY_BOUNDARY,
    OFFLINE_CONTRACT_PROOF_PX_CLASS,
    OWNER_GO,
    P08_CLOSED,
    P10_CLOSED,
    P11_CLOSED,
    P11_POS_TO_SZ_CLOSED,
    P12_EXACT_FLATTEN_PAYLOAD_CLOSED_VALUE,
    P12_EXACT_FLATTEN_PAYLOAD_PROVEN_VALUE,
    P12_TEXT_REWRITTEN,
    P13_DOES_NOT_AUTHORIZE_FLATTEN,
    P13_DOES_NOT_GRANT_EXECUTION_READINESS,
    POS_TO_SZ_UNIT_IDENTITY,
    PREDECESSOR_SLICE,
    PRIOR_OWNER_GO,
    PRIVATE_AUTH_USED,
    PUBLIC_SPEC_RETRIEVAL_PERFORMED,
    PX_SOURCE_CLASS_VALUE,
    REDUCE_ONLY_WIRE_TYPE_STATUS_VALUE,
    REQUEST_POS_SIDE,
    RUNTIME_GET_PERFORMED,
    RUNTIME_GET_REQUIRED,
    SEND_TIME_PAYLOAD_INSTANCE_MINTED_VALUE,
    SEND_TIME_PX_MINTED_VALUE,
    SZ_UNIT_VALUE,
    TARGET_INSTRUMENT_ID,
    TARGET_POSITION_QTY_UNIT,
    THIS_GO_GET_COUNT,
    THIS_GO_POST_COUNT,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1.persist_v1 import (
    persist_p13_exact_flatten_payload_evidence_v1,
)


class P13ExactFlattenPayloadAssembleError(RuntimeError):
    """Fail-closed assemble violation."""


def assemble_p13_execution_prerequisite_12_exact_flatten_payload_v1(
    *,
    origin_main_sha: str,
    evidence_root: Path | None = None,
    run_id: str = CANONICAL_EVIDENCE_RUN_ID,
) -> dict[str, Any]:
    """Build and optionally persist prerequisite 12. No GET. No POST."""
    if str(origin_main_sha or "").strip() != EXPECTED_ORIGIN_MAIN_SHA:
        raise P13ExactFlattenPayloadAssembleError("ORIGIN_MAIN_SHA_MISMATCH")
    verdict = adjudicate_execution_prerequisite_12_exact_flatten_payload_v1(
        origin_main_sha=origin_main_sha
    )
    if verdict["EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION"] != "PASS":
        raise P13ExactFlattenPayloadAssembleError("PREREQUISITE_12_MUST_PASS")
    if verdict["P12_EXACT_FLATTEN_PAYLOAD_CLOSED"] is not True:
        raise P13ExactFlattenPayloadAssembleError("P12_EXACT_FLATTEN_PAYLOAD_MUST_BE_CLOSED")
    census = {
        "DOCUMENT_CLASS": "P13_EXECUTION_PREREQUISITE_12_CENSUS_V1",
        "DOCUMENT_ROLE": "FORENSIC_CENSUS_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "SEAM_COUNT": verdict["CENSUS"]["SEAM_COUNT"],
        "EPISTEMIC_CLASS_COUNTS": verdict["CENSUS"]["EPISTEMIC_CLASS_COUNTS"],
        "PROVEN_SEAMS": verdict["CENSUS"]["PROVEN_SEAMS"],
        "NOT_PROMOTED_SEAMS": verdict["CENSUS"]["NOT_PROMOTED_SEAMS"],
        "EXACT_PAYLOAD_FIELDS": list(EXACT_PAYLOAD_ALLOWED_KEYS),
        "CONTRACT_BOUNDARY": CONTRACT_BOUNDARY_VALUE,
        "REQUEST_POS_SIDE": REQUEST_POS_SIDE,
        "PX_SOURCE_CLASS": PX_SOURCE_CLASS_VALUE,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
    }
    lineage = {
        "DOCUMENT_CLASS": "P13_EXECUTION_PREREQUISITE_12_LINEAGE_V1",
        "DOCUMENT_ROLE": "FORENSIC_LINEAGE_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "LINEAGE_FIELD_NAMES": verdict["CENSUS"]["LINEAGE_FIELD_NAMES"],
        "SEAMS": verdict["LINEAGE"],
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
    }
    adjudication = {
        "DOCUMENT_CLASS": "P13_EXECUTION_PREREQUISITE_12_ADJUDICATION_V1",
        "DOCUMENT_ROLE": "INTERPRETATION_NOT_RAW_WIRE_NOT_SSOT",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION": (
            EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION
        ),
        "P12_EXACT_FLATTEN_PAYLOAD_PROVEN": P12_EXACT_FLATTEN_PAYLOAD_PROVEN_VALUE,
        "P12_EXACT_FLATTEN_PAYLOAD_CLOSED": P12_EXACT_FLATTEN_PAYLOAD_CLOSED_VALUE,
        "EXACT_PAYLOAD_FIELDS": list(EXACT_PAYLOAD_ALLOWED_KEYS),
        "VENUE_NATIVE_BODY": verdict["VENUE_NATIVE_BODY"],
        "BODY_SHA256": verdict["BODY_SHA256"],
        "CONTRACT_BOUNDARY": CONTRACT_BOUNDARY_VALUE,
        "INST_ID_PROVENANCE": verdict["INST_ID_PROVENANCE"],
        "TD_MODE_PROVENANCE": verdict["TD_MODE_PROVENANCE"],
        "SIDE_PROVENANCE": verdict["SIDE_PROVENANCE"],
        "SZ_PROVENANCE": verdict["SZ_PROVENANCE"],
        "POSSIDE_PROVENANCE": verdict["POSSIDE_PROVENANCE"],
        "ORD_TYPE_PROVENANCE": verdict["ORD_TYPE_PROVENANCE"],
        "REDUCE_ONLY_STATUS": verdict["REDUCE_ONLY_STATUS"],
        "PRICE_FIELD_STATUS": verdict["PRICE_FIELD_STATUS"],
        "CLORDID_PROVENANCE": verdict["CLORDID_PROVENANCE"],
        "PX_SOURCE_CLASS": PX_SOURCE_CLASS_VALUE,
        "CLORDID_SOURCE_CLASS": CLORDID_SOURCE_CLASS_VALUE,
        "OFFLINE_PROOF_PX_CLASS": OFFLINE_CONTRACT_PROOF_PX_CLASS,
        "SEND_TIME_PX_MINTED": SEND_TIME_PX_MINTED_VALUE,
        "SEND_TIME_PAYLOAD_INSTANCE_MINTED": SEND_TIME_PAYLOAD_INSTANCE_MINTED_VALUE,
        "FLATTEN_ORDER_SIDE_RULE": FLATTEN_ORDER_SIDE_RULE,
        "FLATTEN_ORDER_SIDE": verdict["FLATTEN_ORDER_SIDE"],
        "REQUEST_POS_SIDE": REQUEST_POS_SIDE,
        "signed_pos": verdict["signed_pos"],
        "SZ_UNIT": SZ_UNIT_VALUE,
        "REDUCE_ONLY_WIRE_TYPE_STATUS": REDUCE_ONLY_WIRE_TYPE_STATUS_VALUE,
        "FRESHNESS_STATUS": verdict["FRESHNESS_STATUS"],
        "PAYLOAD_DETERMINISM_STATUS": verdict["PAYLOAD_DETERMINISM_STATUS"],
        "PAYLOAD_TRACEABILITY_STATUS": verdict["PAYLOAD_TRACEABILITY_STATUS"],
        "FAIL_CLOSED_STATUS": verdict["FAIL_CLOSED_STATUS"],
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "FIELD_PROVENANCE": verdict["FIELD_PROVENANCE"],
        "TARGET_POSITION_QTY_UNIT": TARGET_POSITION_QTY_UNIT,
        "POS_TO_SZ_UNIT_IDENTITY": POS_TO_SZ_UNIT_IDENTITY,
        "P08_CLOSED": P08_CLOSED,
        "P10_CLOSED": P10_CLOSED,
        "P11_POS_TO_SZ_CLOSED": P11_POS_TO_SZ_CLOSED,
        "P11_CLOSED": P11_CLOSED,
        "P12_TEXT_REWRITTEN": P12_TEXT_REWRITTEN,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE": (
            EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE
        ),
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_POST_COUNT": THIS_GO_POST_COUNT,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "P13_DOES_NOT_GRANT_EXECUTION_READINESS": P13_DOES_NOT_GRANT_EXECUTION_READINESS,
        "P13_DOES_NOT_AUTHORIZE_FLATTEN": P13_DOES_NOT_AUTHORIZE_FLATTEN,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "VENUE_NATIVE_BODY_KEYS": verdict["VENUE_NATIVE_BODY_KEYS"],
    }
    summary = {
        "DOCUMENT_CLASS": "P13_EXECUTION_PREREQUISITE_12_PACKAGE_V1",
        "DOCUMENT_ROLE": "DERIVED_NON_SSOT",
        "OWNER_GO": OWNER_GO,
        "OWNER_GO_CONSUMED": True,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "AUTHORIZED_SCOPE": AUTHORIZED_SCOPE,
        "AUTHORIZED_OPERATION": AUTHORIZED_OPERATION,
        "HOST": AUTHORIZED_HOST,
        "AUTHORIZED_ACCOUNT_UID": AUTHORIZED_ACCOUNT_UID,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION": (
            EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION
        ),
        "P12_EXACT_FLATTEN_PAYLOAD_PROVEN": P12_EXACT_FLATTEN_PAYLOAD_PROVEN_VALUE,
        "P12_EXACT_FLATTEN_PAYLOAD_CLOSED": P12_EXACT_FLATTEN_PAYLOAD_CLOSED_VALUE,
        "REQUEST_POS_SIDE": REQUEST_POS_SIDE,
        "FLATTEN_ORDER_SIDE_RULE": FLATTEN_ORDER_SIDE_RULE,
        "BODY_SHA256": verdict["BODY_SHA256"],
        "CONTRACT_BOUNDARY": CONTRACT_BOUNDARY_VALUE,
        "PX_SOURCE_CLASS": PX_SOURCE_CLASS_VALUE,
        "SEND_TIME_PX_MINTED": SEND_TIME_PX_MINTED_VALUE,
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P08_CLOSED": True,
        "P10_CLOSED": True,
        "P11_POS_TO_SZ_CLOSED": True,
        "P11_CLOSED": True,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE": (
            EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE
        ),
        "GET_REQUEST_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "HTTP_EXCHANGE_COUNT": 0,
        "POST_COUNT": THIS_GO_POST_COUNT,
        "WRITE_REQUEST_COUNT": 0,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "CORE_CHANGED": False,
        "NEW_AUTHORITY_CREATED": False,
        "MERGE_AUTHORIZED": False,
        "P13_DOES_NOT_GRANT_EXECUTION_READINESS": True,
        "P13_DOES_NOT_AUTHORIZE_FLATTEN": True,
        "ATLAS_AUTHORITY": "NONE",
        "LANDSCAPE_AUTHORITY": "NONE",
        "SEND_TIME_PAYLOAD_INSTANCE_MINTED": SEND_TIME_PAYLOAD_INSTANCE_MINTED_VALUE,
    }
    result: dict[str, Any] = {
        "verdict": verdict,
        "census": census,
        "lineage": lineage,
        "adjudication": adjudication,
        "summary": summary,
    }
    if evidence_root is not None:
        pack = Path(evidence_root) / run_id
        verified = persist_p13_exact_flatten_payload_evidence_v1(
            pack=pack,
            origin_main_sha=origin_main_sha,
            census=census,
            lineage=lineage,
            adjudication=adjudication,
            summary=summary,
        )
        result["EVIDENCE_PACK"] = str(pack)
        result["MANIFEST_VERIFY_RC"] = verified.get("MANIFEST_VERIFY_RC")
        result["EVIDENCE_DIRNAME"] = EVIDENCE_DIRNAME
    return result
