"""Standing constants for EXECUTION_PREREQUISITE_12 exact flatten payload.

Offline CASE_B persist. No GET. No POST. No flatten execute. No Live/Canary
unlock. Does not mint a send-time px. Does not rewrite P12 text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    DEFAULT_TD_MODE,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1.contract_v1 import (
    CASE,
    CLORDID_SOURCE_CLASS,
    CONTRACT_BOUNDARY,
    EXACT_FLATTEN_PAYLOAD_ALLOWED_KEYS,
    EXECUTION_PREREQUISITE_12_STATUS,
    P12_EXACT_FLATTEN_PAYLOAD_CLOSED,
    P12_EXACT_FLATTEN_PAYLOAD_PROVEN,
    PX_SOURCE_CLASS,
    REDUCE_ONLY_JSON_BOOLEAN_REQUIRED,
    REDUCE_ONLY_WIRE_TYPE_STATUS,
    SEND_TIME_PAYLOAD_INSTANCE_MINTED,
    SEND_TIME_PX_MINTED,
    SZ_UNIT,
    VENUE_NATIVE_ORD_TYPE,
    VENUE_NATIVE_TD_MODE,
)

CAPABILITY_ID = "P13_EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_V1"
PACKAGE_MARKER = "P13_EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_V1=true"
OWNER = "ops.section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p13_execution_prerequisite_12_exact_flatten_payload.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_P12_EXACT_FLATTEN_PAYLOAD_MAXIMUM_SAFE_LEVERAGE_V1"
PRIOR_OWNER_GO = "PEAK_TRADE_OWNER_GO_P11_POSITION_SIDE_POSSIDE_MAXIMUM_SAFE_LEVERAGE_V1"
WORKPACKAGE_ID = "OKX_EEA_P13_EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_V1"
THIS_SLICE = "11.13.5.P13"
PREDECESSOR_SLICE = "11.13.5.P12"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_P13"
EXPECTED_ORIGIN_MAIN_SHA = "8c53428e3587c32cb44a7ceda89a28d46d0e9f3b"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_ADJUDICATE_PERSIST"
AUTHORIZED_SCOPE = "A_P13_EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD"
CANONICAL_EVIDENCE_RUN_ID = "20260904T003800Z"

CASE_VALUE = CASE
EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION = (
    EXECUTION_PREREQUISITE_12_STATUS
)
P12_EXACT_FLATTEN_PAYLOAD_PROVEN_VALUE = P12_EXACT_FLATTEN_PAYLOAD_PROVEN
P12_EXACT_FLATTEN_PAYLOAD_CLOSED_VALUE = P12_EXACT_FLATTEN_PAYLOAD_CLOSED
EXACT_PAYLOAD_ALLOWED_KEYS = tuple(sorted(EXACT_FLATTEN_PAYLOAD_ALLOWED_KEYS))
VENUE_NATIVE_TD_MODE_VALUE = VENUE_NATIVE_TD_MODE
VENUE_NATIVE_ORD_TYPE_VALUE = VENUE_NATIVE_ORD_TYPE
STANDING_TD_MODE = DEFAULT_TD_MODE
REDUCE_ONLY_JSON_BOOLEAN_REQUIRED_VALUE = REDUCE_ONLY_JSON_BOOLEAN_REQUIRED
REDUCE_ONLY_WIRE_TYPE_STATUS_VALUE = REDUCE_ONLY_WIRE_TYPE_STATUS
PX_SOURCE_CLASS_VALUE = PX_SOURCE_CLASS
CLORDID_SOURCE_CLASS_VALUE = CLORDID_SOURCE_CLASS
CONTRACT_BOUNDARY_VALUE = CONTRACT_BOUNDARY
SZ_UNIT_VALUE = SZ_UNIT
SEND_TIME_PX_MINTED_VALUE = SEND_TIME_PX_MINTED
SEND_TIME_PAYLOAD_INSTANCE_MINTED_VALUE = SEND_TIME_PAYLOAD_INSTANCE_MINTED
REQUEST_POS_SIDE = "OMITTED"
FLATTEN_ORDER_SIDE_RULE = "SELL_IF_OBSERVED_SIGNED_POS_GT_0_ELSE_BUY"
CURRENT_UNIT_CONTRACT = SZ_UNIT
POS_TO_SZ_UNIT_IDENTITY = "PROVEN"
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_POS_TO_SZ_CLOSED = True
P11_CLOSED = True
P12_TEXT_REWRITTEN = False
TARGET_POSITION_NONZERO_PROVEN = True
TARGET_POSITION_QTY_NUMERIC = "PASS"
TARGET_POSITION_QTY_UNIT = "PROVEN"
P13_DOES_NOT_GRANT_EXECUTION_READINESS = True
P13_DOES_NOT_AUTHORIZE_FLATTEN = True
EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED"
)
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION"
EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE = "PASS"
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
CENSUS_COMPLETE = True
LINEAGE_COMPLETE = True

OFFLINE_CONTRACT_PROOF_BID = "0.8209"
OFFLINE_CONTRACT_PROOF_ASK = "0.8210"
OFFLINE_CONTRACT_PROOF_TICK_SZ = "0.0001"
OFFLINE_CONTRACT_PROOF_QUOTE_TS = "1787145055768"
OFFLINE_CONTRACT_PROOF_EVAL_TS = "1787145056000"
OFFLINE_CONTRACT_PROOF_PX_CLASS = (
    "OFFLINE_CONTRACT_REGRESSION_FIXTURE_NOT_SEND_TIME_QUOTE_NOT_FROM_OBSERVED_POSITION"
)

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1"
