"""Fail-closed constants for the §11.14 fee/restart/durability forensic closure."""

from __future__ import annotations

CAPABILITY_ID = (
    "SECTION_11_14_LIVE_HANDOFF_EXACT_FEE_RESTART_DURABILITY_AND_PRE_EXECUTION_READINESS_CLOSURE_V1"
)
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = (
    "section_11_14_live_handoff_exact_fee_restart_durability_and_pre_execution_readiness_closure.v1"
)
OWNER = (
    "ops.section_11_14_live_handoff_exact_fee_restart_durability_"
    "and_pre_execution_readiness_closure_v1"
)
THIS_SLICE = "11.14.LIVE_HANDOFF_EXACT_FEE_RESTART_DURABILITY_AND_PRE_EXECUTION_READINESS_CLOSURE"
PREDECESSOR_SLICE = (
    "11.14.LIVE_HANDOFF_STANDING_FEE_SLIPPAGE_AND_COMPLETE_NON_EXECUTING_"
    "EXACT_SINGLE_FILL_EXECUTION_ENVELOPE"
)
LAST_CANONICALLY_CLOSED_PREDECESSOR = (
    "SECTION_11_14_LIVE_HANDOFF_STANDING_FEE_SLIPPAGE_AND_COMPLETE_NON_EXECUTING_"
    "EXACT_SINGLE_FILL_EXECUTION_ENVELOPE"
)
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_HANDOFF_EXACT_FEE_RESTART_DURABILITY_"
    "AND_PRE_EXECUTION_READINESS_CLOSURE_V1"
)
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_HANDOFF_STANDING_FEE_SLIPPAGE_AND_"
    "COMPLETE_NON_EXECUTING_EXACT_SINGLE_FILL_EXECUTION_ENVELOPE_V1"
)
CANONICAL_EVIDENCE_RUN_ID = "20260907T193200Z"
EXPECTED_ORIGIN_MAIN_SHA = "0731a62bec6dd7ef87d80b1c7959d30381f1b983"
PR_6334_MERGE_COMMIT_SHA = EXPECTED_ORIGIN_MAIN_SHA
PR_6334_HEAD_SHA = "572c44aabf3426be0fd0974bf27580cf8f7f92f5"
PR_6334_EXPECTED_TREE = "0033a378a9ca223f6ad34e75ed1f5276794f4198"

BOUND_INSTRUMENT_ID = "SUI-USD_UM_XPERP-310404"
BOUND_INST_FAMILY = "SUI-USD_UM_XPERP"
BOUND_INST_TYPE = "FUTURES"
BOUND_VENUE = "eea.okx.com"
BOUND_SIDE = "BUY"
BOUND_ORDER_TYPE = "LIMIT"
BOUND_ORDER_QTY = "1"
BOUND_ORDID = "3893505043080286208"
BOUND_CLORDID = "ptokxeprod1fec928b1fec928b00"
BOUND_FILL_SZ = "1"
BOUND_FILL_PX = "0.748"
BOUND_FILL_MARK_PX = "0.7479"
BOUND_FILL_IDX_PX = "0.7482"
BOUND_EXEC_TYPE = "T"
BOUND_FEE_RAW = "-0.000374"
BOUND_FEE_CCY = "USDC"
BOUND_CT_VAL = "1"
HISTORICAL_FILL_FEE_EVIDENCE_RUN_ID = "20260904T173813Z"
HISTORICAL_PRETRADE_GET_RUN_ID = "20260907T182140Z"
HYPOTHESIS_TAKER_RATE_MATCHING_FILL = "0.0005"
HYPOTHESIS_CLASS = "HYPOTHESIS_NOT_OEM_FORMULA"

EXACT_OKX_FEE_FORMULA_UNPROVEN = True
EXACT_OKX_FEE_FORMULA_STATUS = "UNPROVEN"
BOUNDED_FEE_ENVELOPE_POLICY_BOUND = True
BOUNDED_FEE_ENVELOPE_CURRENT_NUMERIC_PROVEN = False
BOUNDED_FEE_ENVELOPE_PROVEN = False
EXPECTED_FEE_PRETRADE_STATUS = "POLICY_BOUND_NUMERIC_UNPROVEN_CURRENT_GET_ABSENT"
VENUE_REPORTED_FEE_POST_FILL_STATUS = "PROVEN_HISTORICAL_IDENTITY_BOUND_SINGLE_FILL_ONLY"
LOCAL_FEE_ESTIMATE_STATUS = "CONSERVATIVE_INTERNAL_ENVELOPE_NOT_OEM"
EXACT_SETTLED_FEE_STATUS = "HISTORICAL_VENUE_REPORTED_SINGLE_FILL_NOT_GENERAL_FORMULA"

LIVE_RESTART_STATIC_RECONSTRUCTION_PROVEN = True
LIVE_RESTART_EMPIRICAL_RECONSTRUCTION_PROVEN = False
LIVE_RESTART_RECONSTRUCTED = False
CODE_PATH_EXISTS = True
PRODUCTIVE_BINDING_EXISTS = True
OFFLINE_RECONSTRUCTION_PROOF_EXISTS = True
LIVE_RESTART_OBSERVATION_EXISTS = False
POST_RESTART_RECONCILIATION_PROOF_EXISTS = False
HANDOFF_WRITTEN = False
CONTEMPORANEOUS_PRODUCTIVE_CAPTURE_EXECUTED = False

PROCESS_CRASH_DURABILITY_STATIC_MODEL = "SUPPORTED"
PROCESS_CRASH_DURABILITY_STATUS = "STATIC_MODEL_SUPPORTED_EMPIRICAL_UNPROVEN"
HOST_CRASH_DURABILITY_UNPROVEN = True
HOST_CRASH_DURABILITY_STATUS = "UNPROVEN"
POWER_LOSS_DURABILITY_STATUS = "UNPROVEN"
CODE_GAP_FOUND = False
REPAIR_IMPLEMENTED = False

CANARY_AUTHORIZED_EXACT_FIELD = "INDETERMINATE_ABSENT"
POST_ALLOWED_EXACT_FIELD = "INDETERMINATE_ABSENT"

OWNER_EXECUTION_AUTHORIZED = False
SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED = False
TECHNICAL_PRE_EXECUTION_READINESS = False
TECHNICAL_EXECUTION_READY = False
EXECUTION_AUTHORIZATION_STATUS = "NOT_AUTHORIZED"
EARLIEST_REMAINING_BLOCKER = "OWNER_EXECUTION_AUTHORIZED"
EARLIEST_TECHNICAL_BLOCKER = "CURRENT_SUI_FAMILY_TRADE_FEE_GET_ABSENT"
EARLIEST_LADDER_BLOCKER = "LIVE_RESTART_RECONSTRUCTED"

EVIDENCE_RELATIVE_ROOT = (
    "evidence/ops/section_11_14_live_handoff_exact_fee_restart_durability_"
    "and_pre_execution_readiness_closure_v1"
)
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
ADJUDICATION_FILENAME = "ADJUDICATION.json"
FEE_PROVENANCE_FILENAME = "FEE_PROVENANCE.json"
RESTART_ADJUDICATION_FILENAME = "RESTART_ADJUDICATION.json"
DURABILITY_ADJUDICATION_FILENAME = "DURABILITY_ADJUDICATION.json"
PREDICATE_TABLE_FILENAME = "PREDICATE_TABLE.json"
SAFETY_FILENAME = "SAFETY.json"
BASELINE_FILENAME = "BASELINE.json"
NON_EXECUTION_FILENAME = "NON_EXECUTION.json"
MANIFEST_FILENAME = "MANIFEST.sha256"
LINEAGE_FILENAME = "LINEAGE.json"
