"""Authority-bounded constants for the Cap 2.2 offline MVR evidence harness."""

from __future__ import annotations

HARNESS_ID = "CAP22_OFFLINE_MVR_THRESHOLD_SET_AND_EVIDENCE_HARNESS_V1"
HARNESS_VERSION = "cap22_offline_mvr_evidence_harness.v1"
CONTRACT_ID = "CAP22_OFFLINE_MVR_THRESHOLD_SET_AND_EVIDENCE_HARNESS_V1"
OWNER_GO_THIS_SLICE = "PEAK_TRADE_CAP22_OFFLINE_MVR_THRESHOLD_SET_AND_EVIDENCE_HARNESS_V1"
BOUND_ORIGIN_MAIN_SHA = "ea7582f298c4fbc032f50c18db756face6310497"
AUTHORITY_EFFECT = "OFFLINE_THRESHOLD_SET_AND_DETERMINISTIC_EVIDENCE_HARNESS_ONLY"
PRODUCTIVE_SELECTION_OWNER = "CAPABILITY_2_3_SINGLE_SELECTED_FUTURE_POLICY_V1"

MINIMUM_FINALIZED_PT1M_MARKS = 61
LOG_RETURN_COUNT = 60
VOLATILITY_UNITS = "PER_BAR_DECIMAL_RETURN_VOLATILITY"
VOLATILITY_ESTIMATOR = "POPULATION_SIGMA_DDOF_0_NOT_ANNUALIZED"
AUTHORIZED_VOLATILITY_WARMUP = "61_PT1M_MARKS_60_LOG_RETURNS"
PT1M_STEP_MS = 60_000

CHALLENGER_A_POLICY_ID = "CAP22_MVR_VOLATILITY_RANK_ONLY_V1"
CHALLENGER_B_POLICY_ID = "CAP22_MVR_HARD_SPREAD_GATE_THEN_VOL_V1"
CHALLENGER_C_POLICY_ID = "CAP22_MVR_VOLATILITY_TO_SPREAD_RATIO_V1"
CHALLENGER_D_POLICY_ID = "CAP22_MVR_LEXICOGRAPHIC_SPREAD_THEN_VOL_V1"
NEGATIVE_CONTROL_POLICY_ID = "CAP22_MVR_STRUCTURAL_NEGATIVE_CONTROL_V1"
POLICY_VERSION = "v1"

CHALLENGER_A_CLASS = "VOLATILITY_RANK_ONLY"
CHALLENGER_B_CLASS = "HARD_SPREAD_GATE_THEN_VOLATILITY_RANK"
CHALLENGER_C_CLASS = "VOLATILITY_TO_SPREAD_RATIO"
CHALLENGER_D_CLASS = "LEXICOGRAPHIC_SPREAD_THEN_VOL"
NEGATIVE_CONTROL_CLASS = "CURRENT_STRUCTURAL_THEN_VENUE_ID_ASC"
STRUCTURAL_RANKING_POLICY_ID = "productive_futures_universe_structural_ranking_v1"

OFFLINE_CHALLENGER_A_IS_NOT_ANTI_CHURN_POLICY_A = True
ANTI_CHURN_POLICY_A_UNCHANGED = True
POLICY_A_ROLE = "ANTI_CHURN_ADMISSION_ONLY"

POLICY_B_THRESHOLD_MODE = "VERSIONED_OFFLINE_THRESHOLD_SET"
POLICY_B_THRESHOLD_SET_ID = "CAP22_MVR_POLICY_B_INJECTED_THRESHOLD_SET_V1"
POLICY_B_THRESHOLD_SET_VERSION = "v1"
POLICY_B_THRESHOLD_UNITS = "RELATIVE_SPREAD_DECIMAL_FRACTION"
POLICY_B_SINGLE_THRESHOLD_RATIFIED = False
POLICY_B_THRESHOLD_SET_RATIFIED = False
AUTHORITATIVE_POLICY_B_THRESHOLD_SCALE_FOUND = False
POLICY_B_TEST_ONLY_VALUES_USED = True

ALLOWED_EVIDENCE_CLASSES: tuple[str, ...] = (
    "OFFLINE_FIXTURE_EVIDENCE",
    "OFFLINE_PERSISTED_SNAPSHOT_REPLAY",
)
FORBIDDEN_EVIDENCE_CLASSES: tuple[str, ...] = (
    "HISTORICAL_PIT_WALK_FORWARD_EVIDENCE",
    "PRODUCTIVE_EVIDENCE",
    "POLICY_RATIFICATION_EVIDENCE",
)
DEFAULT_EVIDENCE_CLASS = "OFFLINE_FIXTURE_EVIDENCE"

TOP20_DIAGNOSTIC_LIMIT = 20
TOP20_DIAGNOSTIC_ONLY = True
TOP20_IS_AUTHORITATIVE = False
ACTIVE_SET_SEMANTICS_CREATED = False
POLICY_WINNER_OUTPUT_PRESENT = False
FORWARD_LABEL_METRICS_PRESENT = False
HISTORICAL_PIT_WALK_FORWARD_EVIDENCE_PRESENT = False
HARNESS_NETWORK_READ_REQUIRED = False
LIBRARY_REUSE_AUTHORITY_TRANSFER = False

NEAR_ZERO_THRESHOLD_RATIFIED = False
FINAL_SCORE_FORMULA_RATIFIED = False
FINAL_WEIGHTS_RATIFIED = False
CROSS_SECTIONAL_NORMALIZATION_RATIFIED = False
STALE_SECONDS_RATIFIED = False
COLLECTION_SKEW_NUMERIC_BOUND_RATIFIED = False
RANKING_CADENCE_RATIFIED = False
FORWARD_LABEL_HORIZON_RATIFIED = False
HISTORICAL_REPLAY_HORIZON_RATIFIED = False
POLICY_RATIFICATION_JUSTIFIED = False
NO_CHALLENGER_WINS_BY_THIS_SLICE = True
NO_OFFLINE_POLICY_CLASS_HAS_PRODUCTIVE_AUTHORITY = True

ECONOMIC_MD_PRODUCER_IMPLEMENTED = True
ECONOMIC_MD_PRODUCER_PRODUCTIVELY_SCHEDULED = False
CAP22_PRODUCTIVE_ECONOMIC_RUNTIME_WIRED = False
ECONOMIC_RANK_ACTIVATED = False
CAP21_BOUNDARY_PRESERVED = True
CAP21_RANKING_AUTHORITY_ADDED = False
CAP21_ECONOMIC_MD_AUTHORITY_ADDED = False
CAP22_REMAINS_RANKING_OWNER = True
CAP22_DIRECT_LIVE_VENUE_DEPENDENCY = False
DOWNSTREAM_EXECUTION_MUST_NOT_RE_RANK = True
SECOND_SELECTION_DECISION_DOWNSTREAM = False
PDF_STEP_5_STATUS = "UNRESOLVED"
ROTATION_POLICY_STATUS = "FAIL_CLOSED_UNTIL_PDF_STEP_5"
PDF_STEP_7_STATUS = "FORBIDDEN"
PDF_STEP_7_RUNTIME_IMPLEMENTATION_ALLOWED = False
RUNTIME_AUTHORITY_GRANTED = False
PRODUCTIVE_MF_HOST_JOIN = False
MULTI_FUTURE_RUNTIME_AUTHORIZED = False
NEXT_CANONICAL_DECISION = "PDF_STEP_5_ANTI_CHURN_OWNER_RATIFICATION"
NEXT_CAP22_DEPENDENCY = (
    "SEPARATE_OWNER_GO_REQUIRED_TO_RUN_HISTORICAL_PIT_WALK_FORWARD_WITHOUT_WIRING"
)

FORBIDDEN_SOURCE_TOKENS: tuple[str, ...] = (
    "evaluate_policy_a_v1",
    "apply_rotation",
    "active_set",
    "submit_order",
    "place_order",
)

CALL_GRAPH: tuple[str, ...] = (
    "load_injected_or_persisted_economic_md_snapshot",
    "validate_snapshot_digest_and_provenance",
    "bind_cap21_universe_snapshot_at_same_t",
    "enforce_identical_candidate_universe",
    "compute_offline_mvr_features",
    "evaluate_offline_challengers_a_b_c_d",
    "evaluate_structural_negative_control",
    "persist_offline_digests_and_run_id",
)
