"""Fail-closed reason codes for the Cap 2.2 offline MVR evidence harness."""

from __future__ import annotations

from enum import Enum


class OfflineMvrHarnessFailureCodeV1(str, Enum):
    SNAPSHOT_DIGEST_MISMATCH = "SNAPSHOT_DIGEST_MISMATCH"
    PROVENANCE_MISMATCH = "PROVENANCE_MISMATCH"
    CAP21_UNIVERSE_BINDING_MISMATCH = "CAP21_UNIVERSE_BINDING_MISMATCH"
    INELIGIBLE_INSTRUMENT_INJECTION = "INELIGIBLE_INSTRUMENT_INJECTION"
    CANDIDATE_UNIVERSE_MISMATCH = "CANDIDATE_UNIVERSE_MISMATCH"
    INSUFFICIENT_MARKS = "INSUFFICIENT_MARKS"
    MISSING_MARK = "MISSING_MARK"
    NON_FINALIZED_MARK = "NON_FINALIZED_MARK"
    INVALID_BID_ASK = "INVALID_BID_ASK"
    CROSSED_QUOTE = "CROSSED_QUOTE"
    UNKNOWN_POLICY_ID = "UNKNOWN_POLICY_ID"
    POLICY_B_THRESHOLD_SET_MISSING = "POLICY_B_THRESHOLD_SET_MISSING"
    POLICY_B_THRESHOLD_SET_INVALID = "POLICY_B_THRESHOLD_SET_INVALID"
    POLICY_C_ZERO_SPREAD_INFINITY_FORBIDDEN = "POLICY_C_ZERO_SPREAD_INFINITY_FORBIDDEN"
    NONDETERMINISTIC_OUTPUT = "NONDETERMINISTIC_OUTPUT"
    EVIDENCE_CLASS_FORBIDDEN = "EVIDENCE_CLASS_FORBIDDEN"
    NETWORK_READ_FORBIDDEN = "NETWORK_READ_FORBIDDEN"
    TICKER_MISSING = "TICKER_MISSING"
    NONPOSITIVE_MARK = "NONPOSITIVE_MARK"
    FEATURE_COMPUTATION_FAILED = "FEATURE_COMPUTATION_FAILED"
    ECONOMIC_MD_SNAPSHOT_MISSING = "ECONOMIC_MD_SNAPSHOT_MISSING"
    UNIVERSE_SNAPSHOT_MISSING = "UNIVERSE_SNAPSHOT_MISSING"
    RAW_INPUT_NOT_ELIGIBLE = "RAW_INPUT_NOT_ELIGIBLE"
    POLICY_WINNER_OUTPUT_FORBIDDEN = "POLICY_WINNER_OUTPUT_FORBIDDEN"
    FORWARD_LABEL_METRIC_FORBIDDEN = "FORWARD_LABEL_METRIC_FORBIDDEN"
