"""CAPABILITY_O3_SECURE_CONFIRM_TOKEN_FAMILY_AND_HIDDEN_INPUT_HANDOFF_V1 constants."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_O3_SECURE_CONFIRM_TOKEN_FAMILY_AND_HIDDEN_INPUT_HANDOFF_V1"
SCHEMA_VERSION = "o3_secure_confirm_token_family_and_hidden_input_handoff_v1"
FAMILY_MATRIX_SCHEMA_VERSION = "o3_confirm_token_family_matrix_v1"
BINDING_DOMAIN = "PEAK_TRADE_O3_CONFIRM_TOKEN_FAMILY_BINDING_V1"

# Explicit input channel ownership (must never be conflated).
CHANNEL_CONTROL_STDIN = "CONTROL_STDIN"
CHANNEL_SECURE_TOKEN_INPUT = "SECURE_TOKEN_INPUT"
CHANNEL_RUNTIME_STDOUT = "RUNTIME_STDOUT"
CHANNEL_RUNTIME_STDERR = "RUNTIME_STDERR"
CHANNEL_OPERATOR_TERMINAL = "OPERATOR_TERMINAL"
CHANNEL_BACKGROUND_PROCESS_IO = "BACKGROUND_PROCESS_IO"

# Immutable family IDs.
FAMILY_PSO_GOVERNED_PUBLIC_MD = "FAMILY_PSO_GOVERNED_PUBLIC_MD_V1"
FAMILY_RESEARCH_S03 = "FAMILY_RESEARCH_S03_V1"
FAMILY_TESTNET_HARNESS = "FAMILY_TESTNET_HARNESS_V1"
FAMILY_LIVE_ARMED = "FAMILY_LIVE_ARMED_V1"
FAMILY_LEGACY_LITERAL = "FAMILY_LEGACY_LITERAL_V1"

# Purposes (bound with family).
PURPOSE_PSO_WALLCLOCK_OBSERVE = "PURPOSE_PSO_WALLCLOCK_PUBLIC_MD_OBSERVE_V1"
PURPOSE_S03_ADDITIONAL_EVIDENCE = "PURPOSE_S03_ADDITIONAL_EVIDENCE_SESSION_V1"
PURPOSE_TESTNET_REACHABILITY = "PURPOSE_TESTNET_REACHABILITY_INACTIVE_V1"
PURPOSE_LIVE_BOUNDED_PILOT = "PURPOSE_LIVE_BOUNDED_PILOT_INACTIVE_V1"
PURPOSE_LEGACY_ONE_SHOT = "PURPOSE_LEGACY_ONE_SHOT_INACTIVE_V1"

# Input / storage policies.
INPUT_EPHEMERAL_HANDLE = "SECURE_EPHEMERAL_IN_PROCESS_HANDLE"
INPUT_TOKEN_FILE_EXCEPTION = "SECURE_TOKEN_FILE_EXCEPTION_0600"
INPUT_GETPASS_HIDDEN = "HIDDEN_GETPASS_OPERATOR_TERMINAL"
INPUT_FORBIDDEN_ARGV = "FORBIDDEN_ARGV_PLAINTEXT"
INPUT_FORBIDDEN_GENERIC_ENV = "FORBIDDEN_GENERIC_ENV_PLAINTEXT"

STORAGE_MEMORY_ONLY = "PLAINTEXT_TOKEN_IN_MEMORY_ONLY"
STORAGE_FILE_EXCEPTION = "TOKEN_FILE_EXCEPTION_EXPLICIT_AND_EPHEMERAL"

# Governed env keys that must never carry plaintext for O3 handoff.
FORBIDDEN_GOVERNED_ENV_KEYS: frozenset[str] = frozenset(
    {
        "PEAK_TRADE_CONFIRM_TOKEN",
        "CONFIRM_TOKEN",
        "PT_CONFIRM_TOKEN",
        "PT_CONFIRM",
        "PEAK_TRADE_PSO_WALLCLOCK_CONFIRM_TOKEN",
    }
)

# Reserved O1/O2 path key (path only — never plaintext value).
RESERVED_CONFIRM_TOKEN_FILE_ENV = "PEAK_TRADE_CONFIRM_TOKEN_FILE"

TOKEN_FILE_MODE = 0o600
TOKEN_DIRECTORY_MODE = 0o700

SAFETY_INVARIANTS: dict[str, bool] = {
    "NETWORK_SESSION_STARTED": False,
    "AUTHORIZATION_CONSUMED": False,
    "CONFIRM_TOKEN_MINTED": False,
    "ORDERS_SUBMITTED": False,
    "CREDENTIALS_USED": False,
    "CORE_LOGIC_CHANGED": False,
    "O1_POLICY_CHANGED": False,
    "O2_SUPERVISION_SEMANTICS_CHANGED": False,
    "LIVE_TRADING_ACTIVATED": False,
    "TESTNET_ACTIVATED": False,
}
