"""Constants for CAPABILITY_CANONICAL_DECISION_ARCHIVE_SIBLING_EXPORTER_V1.

AUTHORITY_EFFECT=NONE
TRADING_SEMANTIC_CHANGE=false
DECISION_RECOMPUTE=false
AUTOMATIC_CALLER_ADDED=false
PRESENTATION_CHANGED=false
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_CANONICAL_DECISION_ARCHIVE_SIBLING_EXPORTER_V1"
PACKAGE_MARKER = "CANONICAL_DECISION_ARCHIVE_SIBLING_EXPORTER_V1=true"
OWNER = "ops.canonical_decision_archive_sibling_exporter_v1"
AUTHORITY_EFFECT = "NONE"
DECISION_AUTHORITY_EFFECT = "NONE"

TARGET_FILENAME = "canonical_trading_decision_evidence.v1.json"
TARGET_RELATIVE_PATH = f"readmodels/{TARGET_FILENAME}"
READMODELS_DIRNAME = "readmodels"

# Matches CanonicalTradingDecisionEvidenceV1 / presentation materializer contract.
SOURCE_EVIDENCE_SCHEMA_VERSION = "canonical_trading_decision_evidence_v1"
CONTRACT_NAME = SOURCE_EVIDENCE_SCHEMA_VERSION

REQUIRED_EVIDENCE_FIELDS: tuple[str, ...] = (
    "instrument_id",
    "decision_outcome",
    "next_direction_state",
    "decision_id",
    "evidence_schema_version",
)

ERROR_SOURCE_MISSING = "CANONICAL_DECISION_ARCHIVE_SIBLING_SOURCE_MISSING"
ERROR_SOURCE_CORRUPT = "CANONICAL_DECISION_ARCHIVE_SIBLING_SOURCE_CORRUPT"
ERROR_SOURCE_INVALID = "CANONICAL_DECISION_ARCHIVE_SIBLING_SOURCE_INVALID"
ERROR_SOURCE_SCHEMA_MISMATCH = "CANONICAL_DECISION_ARCHIVE_SIBLING_SOURCE_SCHEMA_MISMATCH"
ERROR_SOURCE_LOAD_FAILED = "CANONICAL_DECISION_ARCHIVE_SIBLING_SOURCE_LOAD_FAILED"
ERROR_IDENTICAL_PATHS = "CANONICAL_DECISION_ARCHIVE_SIBLING_IDENTICAL_SOURCE_TARGET"
ERROR_WRITE_FAILED = "CANONICAL_DECISION_ARCHIVE_SIBLING_WRITE_FAILED"
ERROR_DIGEST_MISMATCH = "CANONICAL_DECISION_ARCHIVE_SIBLING_DIGEST_MISMATCH"
ERROR_PATH_REQUIRED = "CANONICAL_DECISION_ARCHIVE_SIBLING_PATH_REQUIRED"
