"""Constants for CAPABILITY_11_7 Live private read-only and shadow reconciliation."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_11_7_LIVE_PRIVATE_READONLY_AND_SHADOW_RECONCILIATION_V1"
PACKAGE_MARKER = "CAPABILITY_11_7_LIVE_PRIVATE_READONLY_AND_SHADOW_RECONCILIATION_V1=true"
OWNER = "ops.capability_11_7_live_private_readonly_and_shadow_reconciliation_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "capability_11_7_live_private_readonly_and_shadow_reconciliation.v1"
PRODUCER_VERSION = "capability_11_7_live_private_readonly_and_shadow_reconciliation.v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID_11_1 = "CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1"
PREDECESSOR_OWNER_11_1 = "ops.capability_11_1_execution_domain_and_order_lifecycle_contracts_v1"
PREDECESSOR_CAPABILITY_ID_11_2 = (
    "CAPABILITY_11_2_CREDENTIAL_AUTHORIZATION_AND_ACCOUNT_IDENTITY_BOUNDARY_V1"
)
PREDECESSOR_OWNER_11_2 = (
    "ops.capability_11_2_credential_authorization_and_account_identity_boundary_v1"
)
PREDECESSOR_CAPABILITY_ID_11_3 = (
    "CAPABILITY_11_3_PRIVATE_READONLY_VENUE_INTEGRATION_AND_RECONCILIATION_V1"
)
PREDECESSOR_OWNER_11_3 = (
    "ops.capability_11_3_private_readonly_venue_integration_and_reconciliation_v1"
)
PREDECESSOR_CAPABILITY_ID_11_4 = (
    "CAPABILITY_11_4_TESTNET_EXECUTION_ADAPTER_AND_LIFECYCLE_CLOSURE_V1"
)
PREDECESSOR_OWNER_11_4 = "ops.capability_11_4_testnet_execution_adapter_and_lifecycle_closure_v1"
PREDECESSOR_CAPABILITY_ID_11_5 = (
    "CAPABILITY_11_5_TESTNET_RESTART_RECOVERY_AND_KILL_SWITCH_CLOSURE_V1"
)
PREDECESSOR_OWNER_11_5 = "ops.capability_11_5_testnet_restart_recovery_and_kill_switch_closure_v1"
PREDECESSOR_CAPABILITY_ID_11_6 = "CAPABILITY_11_6_LONG_RUNNING_AUTONOMOUS_TESTNET_EVIDENCE_V1"
PREDECESSOR_OWNER_11_6 = "ops.capability_11_6_long_running_autonomous_testnet_evidence_v1"

# Hard safety bindings (contracts/scaffolding only; non-authorizing).
CORE_LOGIC_CHANGE = False
CORE_LOGIC_CHANGE_ALLOWED = False
ACTIVATION_STATE = "not_activated"
ACTIVATION_CHANGED = False
RUNTIME_ACTIVATED = False
LIVE_TRADING_ALLOWED = False
TESTNET_ALLOWED = False
PAPER_EXCHANGE_ORDERS_ALLOWED = False
EXCHANGE_CREDENTIAL_USE_ALLOWED = False
REAL_CAPITAL_MOVEMENT_ALLOWED = False
NETWORK_SESSION_ALLOWED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
RULESET_MUTATION_ALLOWED = False
NOTION_MUTATION_ALLOWED = False

TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False
EXCHANGE_CREDENTIAL_USE_AUTHORIZED = False
REAL_CAPITAL_MOVEMENT_AUTHORIZED = False
OWNER_GO_REQUIRED_FOR_EACH_ACTIVATION = True

LIVE_PATH_CHANGED = False
TESTNET_PATH_CHANGED = False
ORDER_PATH_CHANGED = False
EXCHANGE_CREDENTIAL_PATH_CHANGED = False
NETWORK_SESSION_STARTED = False
PRIVATE_NETWORK_SESSION_STARTED = False

VOLATILITY_NUMERIC_MAX_AGE_ENFORCING = False
NUMERIC_MAX_AGE_EFFECT = "DIAGNOSTIC_ONLY"
DASHBOARD_AUTHORITY_EFFECT = "NONE"

# Cap 11.1 contracts that must not be weakened.
CAPABILITY_11_1_FAIL_CLOSED_RETAINED = True
CAPABILITY_11_1_IDEMPOTENCY_RETAINED = True
CAPABILITY_11_1_UNKNOWN_SEMANTICS_RETAINED = True
CAPABILITY_11_1_LIFECYCLE_RETAINED = True
CAPABILITY_11_1_AUDIT_CONTRACTS_RETAINED = True
CAPABILITY_11_1_ANTI_CORRUPTION_RETAINED = True
CAPABILITY_11_1_JOURNALING_RETAINED = True

# Cap 11.2 contracts that must not be weakened.
CAPABILITY_11_2_CREDENTIAL_BOUNDARY_RETAINED = True
CAPABILITY_11_2_AUTHORIZATION_BOUNDARY_RETAINED = True
CAPABILITY_11_2_ACCOUNT_IDENTITY_BOUNDARY_RETAINED = True
CAPABILITY_11_2_NO_CREDENTIAL_LOAD_RETAINED = True
CAPABILITY_11_2_NO_AUTH_CONSUMPTION_RETAINED = True

# Cap 11.3 contracts that must not be weakened / activated.
CAPABILITY_11_3_PRIVATE_READONLY_BOUNDARY_RETAINED = True
CAPABILITY_11_3_RECONCILIATION_HIERARCHY_RETAINED = True
CAPABILITY_11_3_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_3_NO_NETWORK_FETCH_RETAINED = True
CAPABILITY_11_3_NO_CREDENTIAL_LOAD_RETAINED = True

# Cap 11.4 contracts that must not be weakened / activated.
CAPABILITY_11_4_TESTNET_ADAPTER_BOUNDARY_RETAINED = True
CAPABILITY_11_4_LIFECYCLE_CLOSURE_RETAINED = True
CAPABILITY_11_4_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_4_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_4_NO_NETWORK_SESSION_RETAINED = True

# Cap 11.5 contracts that must not be weakened / activated.
CAPABILITY_11_5_RESTART_RECOVERY_KILL_SWITCH_RETAINED = True
CAPABILITY_11_5_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_5_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_5_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_5_NO_PROVEN_CLAIMS_RETAINED = True

# Cap 11.6 contracts that must not be weakened / activated.
CAPABILITY_11_6_LONG_RUNNING_EVIDENCE_RETAINED = True
CAPABILITY_11_6_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_6_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_6_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_6_NO_PROVEN_CLAIMS_RETAINED = True

# Reachability claims for Cap 11.7 (contracts only — no real private Live session).
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
EXCHANGE_CREDENTIAL_ACCESS_REACHABLE = False
REAL_CAPITAL_MOVEMENT_REACHABLE = False
PRIVATE_READONLY_NETWORK_REACHABLE = False
PRIVATE_READONLY_VENUE_INTEGRATION_ACTIVATED = False
CREDENTIAL_PLAINTEXT_LOADED = False
CREDENTIAL_LOAD_PERFORMED_IN_CAPABILITY_11_7 = False
TESTNET_EXECUTION_ADAPTER_ACTIVATED = False
TESTNET_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_7 = False
TESTNET_NETWORK_SESSION_STARTED_IN_CAPABILITY_11_7 = False
LIVE_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_7 = False
PAPER_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_7 = False

# Cap 11.7 contract surface claims (bound, not activated, not proven).
LIVE_PRIVATE_READONLY_PORT_DECLARED = True
LIVE_PRIVATE_READONLY_PORT_CONSTRUCTIBLE = False
LIVE_PRIVATE_READONLY_CONTRACT_BOUND = True
LIVE_PRIVATE_READONLY_CONTRACT_ACTIVATED = False
LIVE_SHADOW_RECONCILIATION_CONTRACT_BOUND = True
LIVE_SHADOW_RECONCILIATION_CONTRACT_ACTIVATED = False
LIVE_EVIDENCE_LADDER_CONTRACT_BOUND = True
LIVE_EVIDENCE_LADDER_CONTRACT_ACTIVATED = False
LIVE_PRIVATE_READONLY_AND_SHADOW_FIXTURE_ONLY = True
CAPABILITY_11_7_LIVE_PRIVATE_READONLY_STARTED = True
LIVE_PRIVATE_READONLY_ACTIVATED = False
LIVE_SHADOW_RECONCILIATION_ACTIVATED = False
LIVE_SHADOW_WITH_EXCHANGE_RECONCILIATION_ACTIVATED = False

# Cap 11.7 does NOT claim Live evidence-ladder proven / observed fields (§11.14).
LIVE_EXECUTION_CODE_EXISTS = False
LIVE_EXECUTION_PATH_REACHABLE = False
LIVE_PRIVATE_READ_ONLY_PROVEN = False
LIVE_ORDER_PLAN_OBSERVED = False
LIVE_SUBMIT_ACK_OBSERVED = False
LIVE_FILL_OBSERVED = False
LIVE_FEE_OBSERVED = False
LIVE_POSITION_RECONCILED = False
LIVE_ACCOUNTING_RECONSTRUCTED = False
LIVE_RESTART_RECONSTRUCTED = False
LIVE_AUTONOMOUS_RECOVERY_OBSERVED = False
LIVE_END_TO_END_EVIDENCE_PROVEN = False

# Explicit Cap 11.8+ surfaces remain out of scope / unbound.
CAPABILITY_11_8_STARTED = False
CAPABILITY_11_8_LIVE_DRY_RUN_ORDER_PLAN_STARTED = False
LIVE_DRY_RUN_ORDER_PLAN_ACTIVATED = False
LIVE_CANARY_EXECUTION_STARTED = False

# Live progression stages bound by Cap 11.7 (§11.13 first two only).
LIVE_PROGRESSION_STAGES_IN_SCOPE: tuple[str, ...] = (
    "LIVE_PRIVATE_READ_ONLY",
    "LIVE_SHADOW_WITH_EXCHANGE_RECONCILIATION",
)

LIVE_PROGRESSION_STAGES_FORBIDDEN: tuple[str, ...] = (
    "LIVE_DRY_RUN_ORDER_PLAN",
    "LIVE_CANARY_MINIMUM_EXPOSURE",
    "LIVE_BOUNDED_SINGLE_FUTURE",
    "LIVE_BOUNDED_MULTI_SESSION",
    "LIVE_AUTONOMOUS_SINGLE_FUTURE",
)

# Live private read-only GET allowlist (declaration only).
LIVE_PRIVATE_READONLY_GET_ENDPOINTS: tuple[str, ...] = (
    "accounts",
    "open_positions",
    "open_orders",
)

LIVE_PRIVATE_READONLY_FORBIDDEN_MUTATION_ACTIONS: tuple[str, ...] = (
    "submit_order",
    "cancel_order",
    "amend_order",
    "withdraw",
    "transfer",
    "sendorder",
    "batchorder",
)

# Shadow reconciliation reuses §11.5 layers/outcomes as Live-mode contracts.
SHADOW_RECONCILIATION_LAYERS: tuple[str, ...] = (
    "credential_and_account_identity",
    "venue_instrument_and_contract_metadata",
    "open_orders",
    "recent_orders_and_trades",
    "positions",
    "balances_equity_and_available_margin",
    "local_portfolio_and_accounting",
    "risk_reservations",
    "pending_commands",
    "evidence_and_commit_cursors",
)

SHADOW_RECONCILIATION_OUTCOMES: tuple[str, ...] = (
    "MATCH",
    "SAFE_REBUILD",
    "SAFE_ADOPT_EXCHANGE_TRUTH",
    "CANCEL_UNKNOWN_ORDERS",
    "EXIT_ONLY",
    "REDUCE_ONLY",
    "CANCEL_ALL_AND_HALT",
    "HARD_STOP_OWNER_REVIEW",
)

RECONCILIATION_BEFORE_ALPHA = True
RECONCILIATION_CONTINUOUS = True
UNRESOLVED_ECONOMIC_DIVERGENCE_BLOCKS_NEW_ENTRY = True
POSITION_PROTECTION_REMAINS_ACTIVE_WHERE_SAFE = True
EXCHANGE_TRUTH_ADOPTION_REQUIRES_EXPLICIT_POLICY = True
SILENT_LOCAL_HISTORY_OVERWRITE_FORBIDDEN = True
NO_AUTOMATIC_STAGE_PROMOTION = True
OWNER_GO_REQUIRED_FOR_STAGE_PROMOTION = True

# §11.14 Live evidence ladder fields (bound as contracts; not proven).
LIVE_EVIDENCE_LADDER_FIELDS: tuple[str, ...] = (
    "LIVE_EXECUTION_CODE_EXISTS",
    "LIVE_EXECUTION_PATH_REACHABLE",
    "LIVE_PRIVATE_READ_ONLY_PROVEN",
    "LIVE_ORDER_PLAN_OBSERVED",
    "LIVE_SUBMIT_ACK_OBSERVED",
    "LIVE_FILL_OBSERVED",
    "LIVE_FEE_OBSERVED",
    "LIVE_POSITION_RECONCILED",
    "LIVE_ACCOUNTING_RECONSTRUCTED",
    "LIVE_RESTART_RECONSTRUCTED",
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED",
    "LIVE_END_TO_END_EVIDENCE_PROVEN",
)

LIVE_PRIVATE_READONLY_PORT_OWNER = OWNER
LIVE_SHADOW_RECONCILIATION_OWNER = OWNER
LIVE_EVIDENCE_LADDER_OWNER = OWNER

EVIDENCE_DIRNAME = "capability_11_7_live_private_readonly_and_shadow_reconciliation_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
