"""P5.5 O-R2 semantic authority contracts — owner-selected cutover model (no activation)."""

from __future__ import annotations

PACKAGE_MARKER = "P5_5_O_R2_SEMANTIC_AUTHORITY_CONTRACTS_V1=true"
OWNER = "ops.p5_5_o_r2_semantic_authority_contracts_v1"

# Owner architecture decision (P5.5) — encoded exactly; does not activate cutover.
SIDESTATE_CUTOVER_MODEL = "O-R2"
L1_L10_BULL_BEAR_DECISION_AUTHORITY = "SOLE"
SIDESTATE_AS_COMPETING_BULL_BEAR_AUTHORITY = "FORBIDDEN_IN_LAYERED_MODE"
SIDESTATE_DOWNSTREAM_PROJECTION_LIFECYCLE_OCCUPANCY_ROLE = "PRESERVED"
VENUE_POSITION_OCCUPANCY_TRUTH = "PRESERVED"
BULL_TO_LONG_ACTIVE_IMPLICIT_MAPPING = "FORBIDDEN"
BEAR_TO_SHORT_ACTIVE_IMPLICIT_MAPPING = "FORBIDDEN"
LEGACY_TRANSITION_STATE_AUTHORITY = "PRESERVED_UNTIL_EXPLICIT_CUTOVER"

D_T_FORMULA_SELECTED = False
MISSING_AUTHORIZED_D_T = "FAIL_CLOSED"
PRODUCTIVE_BIND_ENABLE = False
AUTHORITY_CUTOVER = False

# Full-Core CURRENT productive decision entry (R-03 closure).
FULL_CORE_FIRST_TRADING_DECISION_CONSUMER = "run_current_productive_master_v2_runtime_cycle_v1"
FULL_CORE_FIRST_TRADING_DECISION_MODULE = (
    "ops.full_core_live_path_composition_root_v1.current_productive_master_v2_runtime_cycle_v1"
)
WALLCLOCK_BRIDGE_NOT_FULL_CORE_CURRENT_AUTHORITY = True

from src.ops.p4_l6_explicit_d_t_proposal_v1.constants_v1 import (  # noqa: E402
    NUMERIC_FORMULA_AUTHORITY as P4_NUMERIC_FORMULA_AUTHORITY,
)
from src.ops.p5_2_productive_cycle_seam_invoke_and_authority_bind_v1.constants_v1 import (  # noqa: E402
    AUTHORITY_CUTOVER_OCCURRED,
    EXTERNAL_EFFECT_AUTHORIZED,
    FINAL_D_T_FORMULA_SELECTED,
    MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED,
    P4_PRODUCTIVE_BINDING,
    P5_AUTHORITY_CUTOVER_AUTHORIZED,
    PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED,
    PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED,
    REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED,
)
from src.ops.p5_productive_layered_core_authority_seam_v1.constants_v1 import (  # noqa: E402
    OPTIMIZER_PRODUCTIVE_AUTHORITY,
)

assert SIDESTATE_CUTOVER_MODEL == "O-R2"
assert D_T_FORMULA_SELECTED is False
assert FINAL_D_T_FORMULA_SELECTED is False
assert PRODUCTIVE_BIND_ENABLE is False
assert AUTHORITY_CUTOVER is False
assert PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED is False
assert P5_AUTHORITY_CUTOVER_AUTHORIZED is False
assert PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED is False
assert P4_PRODUCTIVE_BINDING is False
assert REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED is False
assert P4_NUMERIC_FORMULA_AUTHORITY == "NONE"
assert MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert MAX_POSITIONS_EFFECTIVE == 1
assert EXTERNAL_EFFECT_AUTHORIZED is False
assert OPTIMIZER_PRODUCTIVE_AUTHORITY == "NONE"
assert AUTHORITY_CUTOVER_OCCURRED is False

NUMERIC_FORMULA_AUTHORITY = P4_NUMERIC_FORMULA_AUTHORITY

__all__ = [
    "AUTHORITY_CUTOVER",
    "AUTHORITY_CUTOVER_OCCURRED",
    "BEAR_TO_SHORT_ACTIVE_IMPLICIT_MAPPING",
    "BULL_TO_LONG_ACTIVE_IMPLICIT_MAPPING",
    "D_T_FORMULA_SELECTED",
    "EXTERNAL_EFFECT_AUTHORIZED",
    "FINAL_D_T_FORMULA_SELECTED",
    "FULL_CORE_FIRST_TRADING_DECISION_CONSUMER",
    "FULL_CORE_FIRST_TRADING_DECISION_MODULE",
    "L1_L10_BULL_BEAR_DECISION_AUTHORITY",
    "LEGACY_TRANSITION_STATE_AUTHORITY",
    "MAX_POSITIONS_EFFECTIVE",
    "MISSING_AUTHORIZED_D_T",
    "MULTI_FUTURE_RUNTIME_AUTHORIZED",
    "NUMERIC_FORMULA_AUTHORITY",
    "OPTIMIZER_PRODUCTIVE_AUTHORITY",
    "OWNER",
    "P4_PRODUCTIVE_BINDING",
    "P5_AUTHORITY_CUTOVER_AUTHORIZED",
    "PACKAGE_MARKER",
    "PRODUCTIVE_BIND_ENABLE",
    "PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED",
    "PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED",
    "REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED",
    "SIDESTATE_AS_COMPETING_BULL_BEAR_AUTHORITY",
    "SIDESTATE_CUTOVER_MODEL",
    "SIDESTATE_DOWNSTREAM_PROJECTION_LIFECYCLE_OCCUPANCY_ROLE",
    "VENUE_POSITION_OCCUPANCY_TRUTH",
    "WALLCLOCK_BRIDGE_NOT_FULL_CORE_CURRENT_AUTHORITY",
]
