"""Normative Full-System GHV Testnet Observation environment contract (v1).

Explicit mixed-environment contract for PRE_EXTERNAL observation only.
Does not authorize POST, external effect, Testnet execution, or Live execution.

RUNTIME_AUTHORIZATION_EFFECT=NONE
"""

from __future__ import annotations

PACKAGE_MARKER = "GHV_FULL_SYSTEM_TESTNET_OBSERVATION_PRE_EXTERNAL_V1=true"
CONTRACT_VERSION = "v1"
JOIN_SEAM_ID = "GHV_FULL_SYSTEM_TESTNET_OBSERVATION_PRE_EXTERNAL_BINDING_V1"

PUBLIC_MARKET_ENVIRONMENT = "OKX_EEA_PUBLIC"
PUBLIC_MARKET_HOST = "eea.okx.com"
PUBLIC_AUTH_REQUIRED = False
PUBLIC_DEMO_HEADER_REQUIRED = False

PRIVATE_ACCOUNT_ENVIRONMENT = "OKX_EEA_DEMO"
PRIVATE_ACCOUNT_HOST = "eea.okx.com"
PRIVATE_AUTH_REQUIRED = True
PRIVATE_DEMO_HEADER_REQUIRED = True
PRIVATE_DEMO_HEADER_NAME = "x-simulated-trading"
PRIVATE_DEMO_HEADER_VALUE = "1"

EXECUTION_BOUNDARY = "PRE_EXTERNAL_EFFECT"
POST_ALLOWED = False
ORDER_POST_ALLOWED = False
EXTERNAL_EFFECT_AUTHORIZED = False

SELECTED_INSTRUMENT_OWNER = "Cap23"
BOUND_INSTRUMENT_OWNER = "Cap24"
TESTNET_INSTRUMENT_SUBSTITUTION_ALLOWED = False
TESTNET_INSTRUMENT_MAPPING_ALLOWED = False
TESTNET_SECONDARY_SELECTION_ALLOWED = False

CREDENTIAL_CLASS = "OKX_EEA_DEMO_TRADING_API_KEY_ONLY"
CREDENTIAL_PURPOSE = "READ_ONLY_TESTNET_OBSERVATION"
LIVE_K1_REUSE = False
DEMO_CREDENTIAL_LIVE_K1_REUSE_ALLOWED = False
LIVE_CREDENTIAL_DEMO_REUSE_ALLOWED = False

DEMO_SECRET_REFERENCE = "secretref://vault/peak-trade/testnet-demo"

TRANSPORT_CLASS_DEMO_READ_ONLY_GET = "GHV_FULL_SYSTEM_TESTNET_DEMO_READ_ONLY_GET_V1"
USER_AGENT_DEMO_READ_ONLY_GET = "PeakTrade-GHV-FullSystem-Testnet-Demo-ReadOnly-GET/1"

STATE_ROOT_MARKER = "ghv_full_system_testnet_observation_v1"
FORBIDDEN_CROSS_ENV_ROOT_MARKERS: frozenset[str] = frozenset(
    {
        "paper_shadow",
        "bounded_paper",
        "shadow_campaign",
        "current_productive/live",
        "section_11_12_8",
    }
)

ACCOUNT_OBSERVATION_EVIDENCE_CLASS = "OKX_EEA_DEMO_PRIVATE_ACCOUNT_OBSERVATION"
OUTCOME_EVIDENCE_CLASS_UNCHANGED = "REAL_PUBLIC_OBSERVATION"

PRIVATE_GET_CATALOG_PATHS: frozenset[str] = frozenset(
    {
        "/api/v5/account/max-size",
        "/api/v5/account/leverage-info",
        "/api/v5/account/config",
        "/api/v5/account/positions",
        "/api/v5/account/balance",
    }
)

FORBIDDEN_HTTP_METHODS: frozenset[str] = frozenset({"POST", "PUT", "PATCH", "DELETE"})

READY_TO_EXECUTE_TESTNET_OBSERVATION = False


def write_contract_proof_v1() -> dict[str, str | bool]:
    return {
        "PACKAGE_MARKER": PACKAGE_MARKER,
        "PUBLIC_MARKET_ENVIRONMENT": PUBLIC_MARKET_ENVIRONMENT,
        "PUBLIC_MARKET_HOST": PUBLIC_MARKET_HOST,
        "PUBLIC_AUTH_REQUIRED": PUBLIC_AUTH_REQUIRED,
        "PUBLIC_DEMO_HEADER_REQUIRED": PUBLIC_DEMO_HEADER_REQUIRED,
        "PRIVATE_ACCOUNT_ENVIRONMENT": PRIVATE_ACCOUNT_ENVIRONMENT,
        "PRIVATE_ACCOUNT_HOST": PRIVATE_ACCOUNT_HOST,
        "PRIVATE_AUTH_REQUIRED": PRIVATE_AUTH_REQUIRED,
        "PRIVATE_DEMO_HEADER_REQUIRED": PRIVATE_DEMO_HEADER_REQUIRED,
        "PRIVATE_DEMO_HEADER": f"{PRIVATE_DEMO_HEADER_NAME}:{PRIVATE_DEMO_HEADER_VALUE}",
        "EXECUTION_BOUNDARY": EXECUTION_BOUNDARY,
        "POST_ALLOWED": POST_ALLOWED,
        "ORDER_POST_ALLOWED": ORDER_POST_ALLOWED,
        "EXTERNAL_EFFECT_AUTHORIZED": EXTERNAL_EFFECT_AUTHORIZED,
        "TESTNET_INSTRUMENT_SUBSTITUTION_ALLOWED": TESTNET_INSTRUMENT_SUBSTITUTION_ALLOWED,
        "TESTNET_SECONDARY_SELECTION_ALLOWED": TESTNET_SECONDARY_SELECTION_ALLOWED,
        "READY_TO_EXECUTE_TESTNET_OBSERVATION": READY_TO_EXECUTE_TESTNET_OBSERVATION,
    }
