"""Authority-bounded constants for B11 operator profile/explainability view."""

from __future__ import annotations

from src.ops.peak_trade_research_backtest_live_parity_v1.constants_v1 import (
    CAP23_RERANK_COUNT,
    CAP23_RESCORE_COUNT,
    CAP23_SOLE_SELECTION_OWNER,
    CROSS_UNIVERSE_AUTHORITY,
    LIVE_EXTERNAL_EFFECT_AUTHORIZED,
    MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED,
)

PACKAGE_MARKER = "PEAK_TRADE_OPERATOR_PROFILE_EXPLAINABILITY_V1=true"
PACKAGE_ID = "PEAK_TRADE_OPERATOR_PROFILE_EXPLAINABILITY_V1"
PACKAGE_VERSION = "peak_trade_operator_profile_explainability.v1"
SCHEMA_VERSION = "peak_trade_operator_profile_explainability.v1"
PRODUCER_VERSION = "peak_trade_operator_profile_explainability/v1"
OWNER_GO_THIS_SLICE = "OWNER_GO_B11_OPERATOR_PROFILE_AND_EXPLAINABILITY_V1"

AUTHORITY_EFFECT = "OBSERVABILITY_ONLY"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
CAP22_RANKING_OWNER = "CAPABILITY_2_2_PRODUCTIVE_FUTURES_RANKING_PRODUCER_V1"
CAP23_SELECTION_OWNER = "CAPABILITY_2_3_SINGLE_SELECTED_FUTURE_POLICY_V1"
CAP24_BINDING_BOUNDARY = "CAPABILITY_2_4_SINGLE_SELECTED_FUTURE_RUNTIME_BINDING_V1"

B11_FEATURE_RECOMPUTE_COUNT = 0
B11_RESCORE_COUNT = 0
B11_RERANK_COUNT = 0
B11_RESELECT_COUNT = 0
B12_STARTED = False

PROFILE_ONLY_RANKING_EFFECT = "NONE"
PROFILE_ONLY_SELECTION_EFFECT = "NONE"
UNCLASSIFIED_RANKING_EFFECT = "NONE"
UNCLASSIFIED_SELECTION_EFFECT = "NONE"

VIEW_STATE_AVAILABLE = "AVAILABLE"
VIEW_STATE_INCOMPLETE_REQUIRED_EVIDENCE = "INCOMPLETE_REQUIRED_EVIDENCE"

REASON_MISSING_SELECTION = "MISSING_SELECTION"
REASON_MISSING_RUNTIME_BINDING_EVIDENCE = "MISSING_RUNTIME_BINDING_EVIDENCE"
REASON_MISSING_RANKING_SNAPSHOT = "MISSING_RANKING_SNAPSHOT"
REASON_MISSING_RANKING_EXPLAINABILITY = "MISSING_RANKING_EXPLAINABILITY"
REASON_MISSING_FUTURE_PROFILE = "MISSING_FUTURE_PROFILE"
REASON_SELECTION_DIGEST_MISMATCH = "SELECTION_DIGEST_MISMATCH"
REASON_RANKING_DIGEST_MISMATCH = "RANKING_DIGEST_MISMATCH"
REASON_EXPLAINABILITY_DIGEST_MISMATCH = "RANKING_EXPLAINABILITY_DIGEST_MISMATCH"
REASON_PROFILE_DIGEST_MISMATCH = "FUTURE_PROFILE_DIGEST_MISMATCH"
REASON_SELECTED_IDENTITY_MISMATCH = "SELECTED_IDENTITY_MISMATCH"
REASON_SELECTED_RANK_MISMATCH = "SELECTED_RANK_MISMATCH"
REASON_SELECTED_CANDIDATE_NOT_RANKED = "SELECTED_CANDIDATE_NOT_RANKED"
REASON_SELECTED_EXPLAINABILITY_NOT_FOUND = "SELECTED_EXPLAINABILITY_NOT_FOUND"
REASON_SELECTED_PROFILE_NOT_FOUND = "SELECTED_PROFILE_NOT_FOUND"
REASON_BOUND_IDENTITY_MISMATCH = "BOUND_IDENTITY_MISMATCH"
REASON_BINDING_NOT_OK = "RUNTIME_BINDING_NOT_OK"
REASON_PROFILE_AUTHORITY_PROMOTION = "PROFILE_AUTHORITY_PROMOTION_FORBIDDEN"
REASON_AUTHORITY_INVARIANT_DRIFT = "AUTHORITY_INVARIANT_DRIFT"


def authority_block_v1() -> dict[str, object]:
    return {
        "AUTHORITY_EFFECT": AUTHORITY_EFFECT,
        "B11_FEATURE_RECOMPUTE_COUNT": B11_FEATURE_RECOMPUTE_COUNT,
        "B11_RERANK_COUNT": B11_RERANK_COUNT,
        "B11_RESELECT_COUNT": B11_RESELECT_COUNT,
        "B11_RESCORE_COUNT": B11_RESCORE_COUNT,
        "B12_STARTED": B12_STARTED,
        "CAP22_RANKING_OWNER": CAP22_RANKING_OWNER,
        "CAP23_RERANK_COUNT": CAP23_RERANK_COUNT,
        "CAP23_RESCORE_COUNT": CAP23_RESCORE_COUNT,
        "CAP23_SELECTION_OWNER": CAP23_SELECTION_OWNER,
        "CAP23_SOLE_SELECTION_OWNER": CAP23_SOLE_SELECTION_OWNER,
        "CAP24_BINDING_BOUNDARY": CAP24_BINDING_BOUNDARY,
        "CROSS_UNIVERSE_AUTHORITY": CROSS_UNIVERSE_AUTHORITY,
        "LIVE_EXTERNAL_EFFECT_AUTHORIZED": LIVE_EXTERNAL_EFFECT_AUTHORIZED,
        "MAX_POSITIONS_EFFECTIVE": MAX_POSITIONS_EFFECTIVE,
        "MULTI_FUTURE_RUNTIME_AUTHORIZED": MULTI_FUTURE_RUNTIME_AUTHORIZED,
        "PROFILE_ONLY_RANKING_EFFECT": PROFILE_ONLY_RANKING_EFFECT,
        "PROFILE_ONLY_SELECTION_EFFECT": PROFILE_ONLY_SELECTION_EFFECT,
        "RUNTIME_AUTHORIZATION_EFFECT": RUNTIME_AUTHORIZATION_EFFECT,
        "UNCLASSIFIED_RANKING_EFFECT": UNCLASSIFIED_RANKING_EFFECT,
        "UNCLASSIFIED_SELECTION_EFFECT": UNCLASSIFIED_SELECTION_EFFECT,
    }
