"""Standing constants for PL-TF-002 productive read-only session executor.

No network in package defaults. No standing credential load. No status flip.
"""

from __future__ import annotations

from src.ops.pl_tf_002_network_evidence_contract_v1.constants_v1 import (
    F1_REQUIRED_GET_ITEM_IDS,
    NE_TF_001_ENDPOINT_PATH,
    NE_TF_001_HTTP_METHOD,
    NE_TF_001_TASK_ID,
    NETWORK_EXECUTION_AUTHORIZED,
    PL_TF_002_STATUS_STANDING,
    PRODUCTIVE_TRANSPORT_CLASSES,
)
from src.ops.pl_tf_002_network_evidence_contract_v1.constants_v1 import (
    RUNTIME_AUTHORIZATION_EFFECT as PL_TF_002_CONTRACT_RUNTIME_EFFECT,
)

CAPABILITY_ID = "PL_TF_002_PRODUCTIVE_READ_ONLY_SESSION_EXECUTOR_V1"
PACKAGE_MARKER = "PL_TF_002_PRODUCTIVE_READ_ONLY_SESSION_EXECUTOR_V1=true"
OWNER = "ops.pl_tf_002_productive_read_only_session_executor_v1"
SCHEMA_VERSION = "pl_tf_002_productive_read_only_session_executor.v1"
CONTRACT_VERSION = "v1"
JOIN_SEAM_ID = "PL_TF_002_PRODUCTIVE_READ_ONLY_SESSION_EXECUTOR_V1"

WP_ID = "PL_TF_002_PRODUCTIVE_READ_ONLY_SESSION_EXECUTOR_V1"
OWNER_GO = "OWNER_GO_PL_TF_002_PRODUCTIVE_READ_ONLY_SESSION_EXECUTOR_V1"
# Runtime gate: declared origin/main must match git origin/main, HEAD, and protected wire paths.
# Hardcoded commit pins are forbidden (self-invalidate on squash merge of the rebind PR itself).

AUTHORIZED_HOST = "eea.okx.com"
METHOD_ALLOWLIST = ("GET",)
FORBIDDEN_HTTP_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})
FORBIDDEN_MUTATION_ENDPOINTS = (
    "/api/v5/trade/order",
    "/api/v5/trade/cancel-order",
    "/api/v5/asset/withdrawal",
    "/api/v5/asset/transfer",
)

K1_KEYCHAIN_UTF8_JSON_FIELD_API_KEY = "apiKey"
K1_KEYCHAIN_UTF8_JSON_FIELD_SECRET_KEY = "secretKey"
K1_KEYCHAIN_UTF8_JSON_FIELD_PASSPHRASE = "passphrase"
K1_KEYCHAIN_UTF8_JSON_REQUIRED_FIELDS: frozenset[str] = frozenset(
    {
        K1_KEYCHAIN_UTF8_JSON_FIELD_API_KEY,
        K1_KEYCHAIN_UTF8_JSON_FIELD_SECRET_KEY,
        K1_KEYCHAIN_UTF8_JSON_FIELD_PASSPHRASE,
    }
)

RUNTIME_AUTHORIZATION_EFFECT = "NONE"
NETWORK_SESSION_AUTHORIZED = False
CREDENTIAL_LOAD_AUTHORIZED = False
EXTERNAL_EFFECT_AUTHORIZED = False
TREASURY_MUTATION_AUTHORIZED = False
STEP_29P_AUTHORITY_CHANGED = False
K2_REMOVED = True
K2_REINTRODUCED = False

TRANSPORT_CLASS = "FULL_CORE_PRODUCTIVE_READ_ONLY_GET_V1"
EPHEMERAL_KEYCHAIN_CONSUMER = "PL_TF_002_PRODUCTIVE_READ_ONLY_SESSION_EXECUTOR_V1"

# Re-export contract bindings for capture-WP alignment (read-only references).
PL_TF_002_STATUS = PL_TF_002_STATUS_STANDING
F1_ITEM_IDS = F1_REQUIRED_GET_ITEM_IDS
F2_TASK_ID = NE_TF_001_TASK_ID
F2_HTTP_METHOD = NE_TF_001_HTTP_METHOD
F2_ENDPOINT_PATH = NE_TF_001_ENDPOINT_PATH
ALLOWED_PRODUCTIVE_TRANSPORT_CLASSES = PRODUCTIVE_TRANSPORT_CLASSES
CONTRACT_NETWORK_EXECUTION_AUTHORIZED = NETWORK_EXECUTION_AUTHORIZED
CONTRACT_RUNTIME_EFFECT = PL_TF_002_CONTRACT_RUNTIME_EFFECT
