"""Standing constants for SEND_TIME_POSITION_REOBSERVATION offline contract.

Offline CASE_B contract persist. No GET. No POST. No flatten execute. No
Live/Canary unlock. Does not issue a runtime permit. Does not rewrite APT text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.send_time_position_reobservation_v1 import (
    NAMED_REMAINING_AFTER_SEND_TIME_POSITION_REOBSERVATION,
    STPR_IMPLEMENTATION_OWNER_GO,
)
from src.ops.section_11_13_5_send_time_position_reobservation_v1.contract_v1 import (
    APT_TEXT_REWRITTEN,
    CASE,
    FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE,
    FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE,
    NETWORK_PROVEN,
    P16_TEXT_REWRITTEN,
    P20_TEXT_REWRITTEN,
    P25_TEXT_REWRITTEN,
    POSITION_GET_AUTHORIZED_BY_THIS_OWNER_GO,
    POSITION_GET_REQUIRED_THIS_PERSIST,
    POST_PROVEN,
    PREREQUISITE_18_PROVEN_AT_SEND,
    PREREQUISITE_19_PROVEN_AT_SEND,
    PREREQUISITE_21_PROVEN_AT_SEND,
    PREREQUISITE_24_PROVEN_AT_SEND,
    PRIVATE_GET_PROVEN,
    CREDENTIAL_USE_PROVEN,
    SEND_TIME_POSITION_REOBSERVATION_STATUS,
    STP_TEXT_REWRITTEN,
    STPR_DOES_NOT_AUTHORIZE_BOUNDED_RUNTIME_PERMIT_ISSUANCE,
    STPR_DOES_NOT_AUTHORIZE_FLATTEN,
    STPR_DOES_NOT_AUTHORIZE_NETWORK_SESSION,
    STPR_DOES_NOT_GRANT_EXECUTION_READINESS,
    STPR_DOES_NOT_ISSUE_RUNTIME_PERMIT,
    STPR_DOES_NOT_SET_LIVE_AUTHORIZED,
    STPR_FLATTEN_EXECUTE_AUTHORIZED,
    STPR_NAMED_REOBSERVATION_CONTRACT_CLOSED,
    STPR_NETWORK_SESSION_AUTHORIZED,
    STPR_OBSERVATION_RUNTIME_PROVEN,
    STPR_REOBSERVATION_GATE_IMPLEMENTED,
    STPR_RUNTIME_PROVEN,
)

CAPABILITY_ID = "SEND_TIME_POSITION_REOBSERVATION_V1"
PACKAGE_MARKER = "SEND_TIME_POSITION_REOBSERVATION_V1=true"
OWNER = "ops.section_11_13_5_send_time_position_reobservation_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "send_time_position_reobservation.v1"
OWNER_GO = STPR_IMPLEMENTATION_OWNER_GO
PRIOR_OWNER_GO = "PEAK_TRADE_OWNER_GO_AUTHENTICATED_PRODUCTIVE_TRANSPORT_MAXIMUM_SAFE_LEVERAGE_V1"
WORKPACKAGE_ID = "OKX_EEA_SEND_TIME_POSITION_REOBSERVATION_V1"
THIS_SLICE = "11.13.5.SEND_TIME_POSITION_REOBSERVATION"
PREDECESSOR_SLICE = "11.13.5.AUTHENTICATED_PRODUCTIVE_TRANSPORT"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_SEND_TIME_POSITION_REOBSERVATION"
EXPECTED_ORIGIN_MAIN_SHA = "97f01fed4f6a5e7c374cf7dda7baeb80a2b9923f"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_SEND_TIME_POSITION_REOBSERVATION"
AUTHORIZED_SCOPE = "A_SEND_TIME_POSITION_REOBSERVATION"
CANONICAL_EVIDENCE_RUN_ID = "20260904T035200Z"

CASE_VALUE = CASE
SEND_TIME_POSITION_REOBSERVATION = SEND_TIME_POSITION_REOBSERVATION_STATUS
STPR_NAMED_CONTRACT_CLOSED = STPR_NAMED_REOBSERVATION_CONTRACT_CLOSED
STPR_MECHANISM_IMPLEMENTED = STPR_REOBSERVATION_GATE_IMPLEMENTED
NAMED_REMAINING_HIGHER_AUTHORITY = NAMED_REMAINING_AFTER_SEND_TIME_POSITION_REOBSERVATION
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P25_CLOSED = True
STP_CLOSED = True
APT_CLOSED = True
APT_TEXT_REWRITTEN_VALUE = APT_TEXT_REWRITTEN
STP_TEXT_REWRITTEN_VALUE = STP_TEXT_REWRITTEN
P16_TEXT_REWRITTEN_VALUE = P16_TEXT_REWRITTEN
P20_TEXT_REWRITTEN_VALUE = P20_TEXT_REWRITTEN
P25_TEXT_REWRITTEN_VALUE = P25_TEXT_REWRITTEN
STPR_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE = STPR_DOES_NOT_GRANT_EXECUTION_READINESS
STPR_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = STPR_DOES_NOT_AUTHORIZE_FLATTEN
STPR_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = STPR_DOES_NOT_SET_LIVE_AUTHORIZED
STPR_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE = STPR_DOES_NOT_ISSUE_RUNTIME_PERMIT
STPR_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE = STPR_DOES_NOT_AUTHORIZE_NETWORK_SESSION
STPR_DOES_NOT_AUTHORIZE_BOUNDED_RUNTIME_PERMIT_ISSUANCE_VALUE = (
    STPR_DOES_NOT_AUTHORIZE_BOUNDED_RUNTIME_PERMIT_ISSUANCE
)
STPR_RUNTIME_PROVEN_VALUE = STPR_RUNTIME_PROVEN
STPR_OBSERVATION_RUNTIME_PROVEN_VALUE = STPR_OBSERVATION_RUNTIME_PROVEN
NETWORK_PROVEN_VALUE = NETWORK_PROVEN
CREDENTIAL_USE_PROVEN_VALUE = CREDENTIAL_USE_PROVEN
PRIVATE_GET_PROVEN_VALUE = PRIVATE_GET_PROVEN
POST_PROVEN_VALUE = POST_PROVEN
PREREQUISITE_18_PROVEN_AT_SEND_VALUE = PREREQUISITE_18_PROVEN_AT_SEND
PREREQUISITE_19_PROVEN_AT_SEND_VALUE = PREREQUISITE_19_PROVEN_AT_SEND
PREREQUISITE_21_PROVEN_AT_SEND_VALUE = PREREQUISITE_21_PROVEN_AT_SEND
PREREQUISITE_24_PROVEN_AT_SEND_VALUE = PREREQUISITE_24_PROVEN_AT_SEND
STPR_NETWORK_SESSION_AUTHORIZED_VALUE = STPR_NETWORK_SESSION_AUTHORIZED
STPR_FLATTEN_EXECUTE_AUTHORIZED_VALUE = STPR_FLATTEN_EXECUTE_AUTHORIZED
POSITION_GET_REQUIRED_THIS_PERSIST_VALUE = POSITION_GET_REQUIRED_THIS_PERSIST
POSITION_GET_AUTHORIZED_BY_THIS_OWNER_GO_VALUE = POSITION_GET_AUTHORIZED_BY_THIS_OWNER_GO
FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE_VALUE = (
    FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE
)
FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE_VALUE = (
    FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE
)
EARLIEST_UNRESOLVED_DEPENDENCY = "BOUNDED_RUNTIME_PERMIT_ISSUANCE"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_BOUNDED_RUNTIME_PERMIT_ISSUANCE"
STPR_RUNTIME_RESIDUAL = (
    "BOUNDED_RUNTIME_PERMIT_ISSUANCE_AND_FLATTEN_EXECUTE_AND_"
    "NETWORK_SESSION_REMAIN_SEPARATE_OWNER_GO"
)
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
CENSUS_COMPLETE = True
LINEAGE_COMPLETE = True

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_send_time_position_reobservation_v1"
