"""Fail-closed reason codes for Cap 6.3 decision-config ownership."""

from __future__ import annotations

from enum import Enum


class DecisionConfigFailureCodeV1(str, Enum):
    CONFIG_PATH_MISSING = "CONFIG_PATH_MISSING"
    CONFIG_SECTION_MISSING = "CONFIG_SECTION_MISSING"
    CONFIG_KEY_MISSING = "CONFIG_KEY_MISSING"
    CONFIG_TYPE_INVALID = "CONFIG_TYPE_INVALID"
    CONFIG_VALUE_INVALID = "CONFIG_VALUE_INVALID"
    CONFIG_VERSION_INCOMPATIBLE = "CONFIG_VERSION_INCOMPATIBLE"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    CONFIG_EFFECTIVE_VALUE_DRIFT = "CONFIG_EFFECTIVE_VALUE_DRIFT"
    LEGACY_BRIDGE_FALLBACK_ATTEMPT = "LEGACY_BRIDGE_FALLBACK_ATTEMPT"
    PARALLEL_CONFIG_OWNER_CONFLICT = "PARALLEL_CONFIG_OWNER_CONFLICT"
    PRODUCTIVE_CONSUMER_UNBOUND = "PRODUCTIVE_CONSUMER_UNBOUND"
    SILENT_FALLBACK_FORBIDDEN = "SILENT_FALLBACK_FORBIDDEN"
    MANIFEST_VERIFY_FAILED = "MANIFEST_VERIFY_FAILED"
    STATE_CORRUPT = "STATE_CORRUPT"
    RESTART_CONFIG_MISMATCH = "RESTART_CONFIG_MISMATCH"
