"""Standing constants for §11.13.5.Z2DS post-Z2DR read-only runtime evidence."""

from __future__ import annotations

from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_create_path_blocker_constants_v1 import (
    EARLIEST_UNRESOLVED_DEPENDENCY as Z2DR_EARLIEST_UNRESOLVED_DEPENDENCY,
    G_POSMODE_RESULT_CLASS,
    G_POSMODE_STATUS,
    G_POSMODE_STATUS_CLOSED_AS,
    OFFLINE_CLOSABLE_GAP_COUNT as Z2DR_OFFLINE_CLOSABLE_GAP_COUNT,
    THIS_SLICE as Z2DR_SLICE,
    Z2DP_EVIDENCE_PACK,
    Z2DQ_EVIDENCE_PACK,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    DEFAULT_ORDER_TYPE,
    DEFAULT_TD_MODE,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    POSITION_COUNT_LIMIT,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_submit_composition_constants_v1 import (
    CREATE_PATH_ARCHITECTURALLY_COMPLETE,
    CREATE_PATH_CURRENTLY_AUTHORIZED,
    CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
    CURRENT_PRODUCTIVE_WIRE_REACHABLE,
    POSITION_MODE_FAIL_CLOSED as ROUTE_C_POSITION_MODE_FAIL_CLOSED,
    POSITION_MODE_SUBMIT_BODY_SEMANTICS as ROUTE_C_POSITION_MODE_SUBMIT_BODY_SEMANTICS,
    PREREQUISITE_08_CLOSED as ROUTE_C_PREREQUISITE_08_CLOSED,
)

CAPABILITY_ID = "Z2DS_POST_Z2DR_RUNTIME_READ_ONLY_EVIDENCE_MAX_LEVERAGE_V1"
PACKAGE_MARKER = "Z2DS_POST_Z2DR_RUNTIME_READ_ONLY_EVIDENCE_MAX_LEVERAGE_V1=true"
OWNER = "ops.section_11_13_5_z2ds_post_z2dr_runtime_read_only_evidence_max_leverage_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "z2ds_post_z2dr_runtime_read_only_evidence_max_leverage.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_POST_Z2DR_RUNTIME_READ_ONLY_EVIDENCE_MAX_LEVERAGE_V1"
WORKPACKAGE_ID = "POST_Z2DR_RUNTIME_READ_ONLY_EVIDENCE_MAX_LEVERAGE_V1"
THIS_SLICE = "11.13.5.Z2DS"
PREDECESSOR_SLICE = Z2DR_SLICE
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "78e5055809c37bb264da2672ac2d5ea9a0e1165a"
AUTHORIZED_HOST = "eea.okx.com"

AUTHORIZED_OPERATION = "BOUNDED_READ_ONLY_RUNTIME_EVIDENCE_MAX_LEVERAGE_GET_PACKAGE"
MAX_NETWORK_REQUEST_COUNT = 15
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
TRANSFER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
FUNDING_GET_REQUIRED = False
FUNDING_GET_AUTHORIZED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET_PACKAGE = False

TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
TARGET_TD_MODE = DEFAULT_TD_MODE
TARGET_ORDER_TYPE = DEFAULT_ORDER_TYPE
MAX_POSITIONS_EFFECTIVE = POSITION_COUNT_LIMIT
BOUND_ACCOUNT_SCOPE = REUSED_BINDING_ACCOUNT_SCOPE

ENDPOINT_PUBLIC_INSTRUMENTS = "/api/v5/public/instruments"
ENDPOINT_PUBLIC_TICKER = "/api/v5/market/ticker"
ENDPOINT_ORDERS_PENDING = "/api/v5/trade/orders-pending"

FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
    "/api/v5/trade/cancel-order",
    "/api/v5/trade/close-position",
    "/api/v5/account/set-position-mode",
    "/api/v5/account/set-leverage",
)
FORBIDDEN_HTTP_METHODS: tuple[str, ...] = (
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "HEAD",
    "OPTIONS",
    "TRACE",
    "CONNECT",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

Z2DR_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_z2dr_post_z2dq_route_c_create_path_blocker_census_v1/"
    "20260903T174500Z/"
)
Z2DR_OFFLINE_CLOSABLE_GAP_COUNT_STANDING = Z2DR_OFFLINE_CLOSABLE_GAP_COUNT
Z2DR_G_POSMODE_STATUS = G_POSMODE_STATUS
Z2DR_G_POSMODE_STATUS_CLOSED_AS = G_POSMODE_STATUS_CLOSED_AS
Z2DR_G_POSMODE_RESULT_CLASS = G_POSMODE_RESULT_CLASS
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = Z2DR_EARLIEST_UNRESOLVED_DEPENDENCY

EVIDENCE_DIRNAME = "section_11_13_5_z2ds_post_z2dr_runtime_read_only_evidence_max_leverage_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"

ACCOUNT_CONFIG_PERSIST_FIELDS: tuple[str, ...] = (
    "uid",
    "mainUid",
    "acctLv",
    "posMode",
    "perm",
    "settleCcy",
    "label",
    "level",
    "kycLv",
)
ACCOUNT_CONFIG_REDACT_FIELDS: frozenset[str] = frozenset({"ip"})

OBSERVATION_OBSERVED = "OBSERVED"
OBSERVATION_NOT_OBSERVED = "NOT_OBSERVED"
OBSERVATION_PROVEN = "PROVEN"
OBSERVATION_NOT_PROVEN = "NOT_PROVEN"
OBSERVATION_SATISFIED = "SATISFIED"
OBSERVATION_UNSATISFIED = "UNSATISFIED"
OBSERVATION_STALE = "STALE"
OBSERVATION_AUTH_FAILED = "AUTH_FAILED"
OBSERVATION_NOT_EXECUTED = "NOT_EXECUTED"

NEXT_AUTHORITY_BOUNDARY = (
    "SEPARATE_OWNER_GO_REQUIRED_BEFORE_ANY_POST_OR_POSITION_CREATION_OR_FLATTEN_OR_LIVE_OR_CANARY"
)
