"""P5.2 productive-cycle ↔ layered-core bind — constants (disabled by default)."""

from __future__ import annotations

PACKAGE_MARKER = "P5_2_PRODUCTIVE_CYCLE_SEAM_INVOKE_AND_AUTHORITY_BIND_V1=true"
OWNER = "ops.p5_2_productive_cycle_seam_invoke_and_authority_bind_v1"

# Disabled until explicit Owner-GO for productive seam invoke + cutover prep.
PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED = False

# No canonical regime_post ↔ SideState mapping exists on main.
REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED = False

FINAL_D_T_FORMULA_SELECTED = False

# Re-export P5.1 guard constants for bind proofs (unchanged semantics).
from src.ops.p5_productive_layered_core_authority_seam_v1.constants_v1 import (  # noqa: E402
    AUTHORITY_CUTOVER_OCCURRED,
    EXTERNAL_EFFECT_AUTHORIZED,
    MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED,
    NUMERIC_FORMULA_AUTHORITY,
    OPTIMIZER_PRODUCTIVE_AUTHORITY,
    P4_PRODUCTIVE_BINDING,
    P5_AUTHORITY_CUTOVER_AUTHORIZED,
    PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED,
)

assert P5_AUTHORITY_CUTOVER_AUTHORIZED is False
assert PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED is False
assert P4_PRODUCTIVE_BINDING is False
assert PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED is False
assert REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED is False

__all__ = [
    "AUTHORITY_CUTOVER_OCCURRED",
    "EXTERNAL_EFFECT_AUTHORIZED",
    "FINAL_D_T_FORMULA_SELECTED",
    "MAX_POSITIONS_EFFECTIVE",
    "MULTI_FUTURE_RUNTIME_AUTHORIZED",
    "NUMERIC_FORMULA_AUTHORITY",
    "OPTIMIZER_PRODUCTIVE_AUTHORITY",
    "OWNER",
    "P4_PRODUCTIVE_BINDING",
    "P5_AUTHORITY_CUTOVER_AUTHORIZED",
    "PACKAGE_MARKER",
    "PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED",
    "PRODUCTIVE_DECISION_PATH_CUTOVER_ENABLED",
    "REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED",
]
