"""Fail-closed reason codes for Cap 3.1 futures accounting binding."""

from __future__ import annotations

from enum import Enum


class AccountingFailureCodeV1(str, Enum):
    INVALID_CONTRACT_METADATA = "INVALID_CONTRACT_METADATA"
    MISSING_MARK_PRICE = "MISSING_MARK_PRICE"
    INVALID_MARK_PRICE = "INVALID_MARK_PRICE"
    ZERO_QUANTITY = "ZERO_QUANTITY"
    NEGATIVE_QUANTITY = "NEGATIVE_QUANTITY"
    NON_REPRESENTABLE_QUANTITY = "NON_REPRESENTABLE_QUANTITY"
    OVER_REDUCE = "OVER_REDUCE"
    REDUCE_ONLY_VIOLATION = "REDUCE_ONLY_VIOLATION"
    POSITION_FLIP_BLOCKED = "POSITION_FLIP_BLOCKED"
    DUPLICATE_FILL = "DUPLICATE_FILL"
    CONFLICTING_WRITER = "CONFLICTING_WRITER"
    PERSISTENCE_INTERRUPTION = "PERSISTENCE_INTERRUPTION"
    PORTFOLIO_STATE_CONTRADICTION = "PORTFOLIO_STATE_CONTRADICTION"
    MISSING_FILL_ID = "MISSING_FILL_ID"
    INVALID_SIDE = "INVALID_SIDE"
    KERNEL_VALIDATION_FAILED = "KERNEL_VALIDATION_FAILED"
    WRITER_LOCK_NOT_HELD = "WRITER_LOCK_NOT_HELD"
    RESTART_LEDGER_CORRUPT = "RESTART_LEDGER_CORRUPT"


class AccountingSuccessCodeV1(str, Enum):
    LONG_OPEN = "LONG_OPEN"
    LONG_INCREASE = "LONG_INCREASE"
    LONG_REDUCE = "LONG_REDUCE"
    LONG_CLOSE = "LONG_CLOSE"
    SHORT_OPEN = "SHORT_OPEN"
    SHORT_INCREASE = "SHORT_INCREASE"
    SHORT_REDUCE = "SHORT_REDUCE"
    SHORT_CLOSE = "SHORT_CLOSE"
    MARK_TO_MARKET = "MARK_TO_MARKET"
    IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
    NO_FILL_HOLD = "NO_FILL_HOLD"
