"""Standing constants for the delayed posId-zero G12 conjunction contract.

Offline only. Does not GET, POST, flatten, close G12, or rewrite historical
same-session post-action semantics.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    ORDER_COUNT_LIMIT,
    POSITION_COUNT_LIMIT,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.flatten_limit_price_contract_v1 import (
    LIVE_FLATTEN_PROVABILITY_STATUS,
)

CAPABILITY_ID = "G12_DELAYED_POSID_ZERO_ROW_FULL_CONJUNCTION_PROOF_CONTRACT_V1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "g12_delayed_posid_zero_row_full_conjunction.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_G12_DELAYED_POSID_ZERO_ROW_FULL_CONJUNCTION_PROOF_CONTRACT_V1"
THIS_SLICE = "11.13.5.G12_DELAYED_POSID_ZERO_ROW_FULL_CONJUNCTION_PROOF_CONTRACT"
PREDECESSOR_SLICE = "11.13.5.PR_6252_MERGE_CLOSEOUT"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = (
    "SECTION_11_13_5_G12_DELAYED_POSID_ZERO_ROW_FULL_CONJUNCTION_PROOF_CONTRACT"
)
EXPECTED_ORIGIN_MAIN_SHA = "9613c1a5e39f793edde96a83d97c16714350b406"
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_HOST = "eea.okx.com"

POSITIONS_ENDPOINT = "/api/v5/account/positions"
PENDING_ENDPOINT = "/api/v5/trade/orders-pending"
HISTORY_ENDPOINT = "/api/v5/account/positions-history"

STATUS_PASS = "PASS"
STATUS_FAIL = "FAIL"
STATUS_NOT_PROVEN = "NOT_PROVEN"

EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False
FILL_IS_NOT_POSITION_ZERO_PROVEN = True
ORDER_FILLED_IS_NOT_POSITION_ZERO_PROVEN = True
DELAYED_ZERO_DOES_NOT_IMPLY_LIVE_FLATTEN_PROVEN = True
DELAYED_ZERO_DOES_NOT_IMPLY_PENDING_EMPTY = True
DELAYED_ZERO_DOES_NOT_IMPLY_RELATED_EMPTY = True
HISTORICAL_PENDING_IS_NOT_CURRENT_PENDING = True
POSID_FILTERED_ENVELOPE_DOES_NOT_PROVE_RELATED_COMPLETENESS = True
INSTID_FILTERED_ENVELOPE_DOES_NOT_PROVE_RELATED_COMPLETENESS = True
IDENTITY_EQUALITY_IS_NOT_CAUSAL_LINEAGE = True
CAUSAL_LINEAGE_IS_NOT_SAME_SESSION_READBACK = True
POST_READBACK_IDENTITY_REQUIRED_FOR_DELAYED_PROOF = False
NO_FLIP_SCOPE = "PAIRWISE_PRE_VS_DELAYED_EXPLICIT_ZERO_ROW_NOT_INTERMEDIATE_PATH"
RELATED_COMPLETENESS_SURFACE = "UNFILTERED_GET_ACCOUNT_POSITIONS_NONZERO_ORIENTED"
PENDING_EMPTY_SURFACE = "GET_TRADE_ORDERS_PENDING"
PENDING_DATA_EMPTY_MEANS_NO_REGULAR_OPEN_ORDERS = True
QUERY_COMPLETENESS_PROVEN = False
HTTP_OK_DOES_NOT_PROVE_COMPLETENESS = True
FORENSIC_LOCAL_OPS_LOCAL_IS_NOT_CANONICAL = True
OPS_LOCAL_CAPTURE_PATH = ".ops_local/g12_zero_elicitation_result.sanitized.json"

G12_STATUS = "OPEN_LIVE_FLATTEN_PROVABILITY_UNPROVEN"
CANONICAL_SSOT_TARGET_POSITION_ZERO_PROVEN = False
CANONICAL_SSOT_LIVE_FLATTEN_PROVABILITY_PROVEN = False
SECTION_11_14_AUTHORIZED = False
GET_PERFORMED_THIS_PERSIST = False
POST_PERFORMED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
NETWORK_EFFECT_NONE = "none"
ORDER_EFFECT_NONE = "none"
ACCOUNT_MUTATION_EFFECT_NONE = "none"

EARLIEST_UNRESOLVED_DEPENDENCY = "LIVE_FLATTEN_PROVABILITY_IF_NOT_PROVEN"
NEXT_AUTHORITY_BOUNDARY = (
    "SEPARATE_OWNER_GO_FOR_CANONICAL_DELAYED_ZERO_PERSIST_AND_P7_P9_OBSERVATIONS"
)
NEXT_OWNER_GO_REQUIRED = (
    "PEAK_TRADE_OWNER_GO_G12_CANONICAL_DELAYED_ZERO_PERSIST_AND_PENDING_RELATED_OBSERVATIONS_V1"
)
NEXT_PENDING_GET = "GET /api/v5/trade/orders-pending"
NEXT_RELATED_GET = "GET /api/v5/account/positions"
NEXT_P5_PERSISTENCE = (
    "PERSIST_SANITIZED_POSID_FILTERED_EXPLICIT_ZERO_ROW_AS_GOVERNED_EVIDENCE_OR_FRESH_EQUIVALENT"
)

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
STANDING_ORDER_COUNT_LIMIT = ORDER_COUNT_LIMIT
STANDING_POSITION_COUNT_LIMIT = POSITION_COUNT_LIMIT
OFFLINE_LIVE_FLATTEN_PROVABILITY_STATUS = LIVE_FLATTEN_PROVABILITY_STATUS
