"""Constants for Phase 11 §11.17 CANONICAL_STATEFUL_CORE_PROVEN evidence closure."""

from __future__ import annotations

CAPABILITY_ID = "PHASE_11_SECTION_11_17_CANONICAL_STATEFUL_CORE_PROVEN_EVIDENCE_CLOSURE_V1"
PACKAGE_MARKER = (
    "PHASE_11_SECTION_11_17_CANONICAL_STATEFUL_CORE_PROVEN_EVIDENCE_CLOSURE_V1=true"
)
OWNER = "ops.phase_11_section_11_17_canonical_stateful_core_proven_evidence_closure_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "phase_11_section_11_17_canonical_stateful_core_proven_evidence_closure.v1"
CONTRACT_VERSION = "v1"

SECTION_11_17_FIELD = "CANONICAL_STATEFUL_CORE_PROVEN"
CLOSURE_METHOD = "EXISTING_EVIDENCE_BINDING"

SOURCE_CAPABILITY_ID = "CAPABILITY_7_2_SINGLE_FUTURE_STATEFUL_NO_ORDER_RUNTIME_ACTIVATION_V1"
SOURCE_EVIDENCE_DIRNAME = "capability_7_2_single_future_stateful_no_order_runtime_activation_v1"
SOURCE_OWNER = "ops.single_future_stateful_no_order_runtime_activation_v1"
SOURCE_HISTORICAL_REPOSITORY_SHA = "1d447fcecc4886a690cd9e83da11c2c38995e43f"
SOURCE_EVIDENCE_DIGEST = "b131c2958c70d587a9a893e21899c1ff8f1143603a6f154d324bdc70287812f7"
SOURCE_CONFIG_DIGEST = "778d619cac4bf842da66c397cc0266a13a75ee1d93f7970ed9eda6fbaec6cb6b"

EVIDENCE_DIRNAME = (
    "phase_11_section_11_17_canonical_stateful_core_proven_evidence_closure_v1"
)
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"

CORE_LOGIC_CHANGE = False
ACTIVATION_STATE = "not_activated"
NETWORK_SESSION_STARTED = False
CREDENTIAL_ACCESS = False
ORDER_SUBMIT_REACHABLE = False
CAPABILITY_11_13_STARTED = False

# Bound field only. All other §11.17 residuals remain unproven/false polarity.
CANONICAL_STATEFUL_CORE_PROVEN = True
SIMULATED_LIFECYCLE_PROVEN = False
TESTNET_LIFECYCLE_PROVEN = False
LIVE_PRIVATE_READ_ONLY_PROVEN = False
LIVE_ORDER_LIFECYCLE_PROVEN = False
LIVE_RECONCILIATION_PROVEN = False
LIVE_RESTART_PROVEN = False
LIVE_UNKNOWN_SUBMIT_RECOVERY_PROVEN = False
LIVE_DUPLICATE_ORDER_PREVENTION_PROVEN = False
LIVE_PARTIAL_FILL_RECOVERY_PROVEN = False
LIVE_KILL_SWITCH_PROVEN = False
LIVE_AUTONOMOUS_DEGRADATION_PROVEN = False
LIVE_AUTONOMOUS_RECOVERY_PROVEN = False
LIVE_ACCOUNTING_RECONSTRUCTION_PROVEN = False
LIVE_EVIDENCE_VERIFIED = False
OWNER_INTERVENTION_REQUIRED_FOR_ROUTINE_OPERATION = True
OWNER_INTERVENTION_REQUIRED_FOR_SCOPE_OR_LIMIT_CHANGE = True
CORE_LOGIC_PARITY_ACROSS_MODES = True
FULLY_AUTONOMOUS_LIVE_TRADING_READY = False
FULLY_AUTONOMOUS_LIVE_TRADING_ACTIVE = False

# Cap 7.2 claim_matrix keys required for §11.17 CANONICAL_STATEFUL_CORE_PROVEN semantics.
REQUIRED_SOURCE_TRUE_CLAIMS: tuple[str, ...] = (
    "FULL_CANONICAL_STATEFUL_RUNTIME_ACTIVE",
    "ONE_PRODUCTIVE_STATEFUL_HOST",
    "ONE_CANONICAL_ACTIVATION_AUTHORITY",
    "ONE_CANONICAL_RUNTIME_MODE",
    "STATEFUL_RUNTIME_READY_FOR_ACTIVATION",
    "RESTART_WHILE_FLAT_PROVEN",
    "RESTART_WITH_OPEN_POSITION_PROVEN",
    "PRECONDITIONS_ALL_PROVEN",
    "PREDECESSOR_EVIDENCE_VERIFIED",
    "EVIDENCE_VERIFIER_PASS",
    "SIMULATED_EXECUTION_PORT_SEPARATE_FROM_REAL_EXECUTION_PORT",
    "NO_REAL_SUBMIT_ORDER_INTERFACE_IN_NO_ORDER_HOST",
)
REQUIRED_SOURCE_FALSE_CLAIMS: tuple[str, ...] = (
    "CORE_LOGIC_CHANGE",
    "LIVE_ORDERS",
    "TESTNET_ORDERS",
    "PAPER_EXCHANGE_ORDERS",
    "EXCHANGE_CREDENTIAL_USE",
    "NETWORK_SESSION_STARTED",
    "REAL_CAPITAL_MOVEMENT",
    "REAL_EXECUTION_ADAPTER_CONSTRUCTED",
    "EXCHANGE_ORDER_SUBMIT_REACHABLE",
    "EXCHANGE_CREDENTIAL_ACCESS_REACHABLE",
    "PRIVATE_ENDPOINT_REACHABLE",
    "MULTI_FUTURE_RUNTIME_AUTHORIZED",
    "AUTHORIZATION_CONSUMED",
)

CANONICAL_FIELD_SEMANTICS = (
    "Master Runbook §11.17 first readiness gate: the proven canonical stateful "
    "no-order trading core (Cap 7.2 Single-Future Canonical Stateful Runtime "
    "Activation, offline/no-order scope) that Phase 11 must extend without "
    "replacement (§11.0/§11.2). Distinct from SIMULATED_LIFECYCLE_PROVEN (Cap 7.1), "
    "Testnet/Live proven fields, READY, and Cap 11.13 activation."
)
