"""Constants for staged N=5 productive runtime admission, recovery, and audit."""

from __future__ import annotations

from src.ops.current_mf_n5_full_autonomy_productive_runtime_orchestrator_v1.constants_v1 import (
    AUTONOMY_TRADING_DECISION_AUTHORITY as ORCH_AUTONOMY_TRADING,
    EXTERNAL_EFFECT_AUTHORIZED as ORCH_EXTERNAL_EFFECT,
    MAX_POSITIONS_EFFECTIVE as ORCH_MAX_POSITIONS,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as ORCH_MF_RUNTIME,
    N_GT_1_ENABLED as ORCH_N_GT_1,
    PORTFOLIO_RESTART_STATUS as ORCH_PORTFOLIO_RESTART,
    POST_ALLOWED as ORCH_POST,
    PRODUCTIVE_ENTRYPOINT as ORCHESTRATOR_PRODUCTIVE_ENTRYPOINT,
)
from src.ops.portfolio_capital_reservation_budget_v1.contract_v1 import (
    CANONICAL_RESTART_RECONSTRUCTABLE as PORTFOLIO_CANONICAL_RESTART_RECONSTRUCTABLE,
)

OWNER = "ops.current_mf_n5_staged_productive_runtime_admission_recovery_audit_v1"
CONTRACT_ID = "CURRENT_MF_N5_STAGED_PRODUCTIVE_RUNTIME_ADMISSION_RECOVERY_AUDIT_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_n5_staged_productive_runtime_admission_recovery_audit.v1"
SLICE_ID = "STAGED_N5_ADMISSION_RECOVERY_AUDIT_CONTROL_PLANE"
OWNER_GO_THIS_SLICE = "OWNER_GO_PR3_STAGED_N5_ADMISSION_RECOVERY_AUDIT"

ENTRYPOINT_SYMBOL = "run_staged_productive_full_autonomy_n5_runtime_control_plane_v1"
PRODUCTIVE_CONTROL_PLANE_ENTRYPOINT = f"{OWNER}.{ENTRYPOINT_SYMBOL}"
UNDERLYING_ORCHESTRATOR_ENTRYPOINT = ORCHESTRATOR_PRODUCTIVE_ENTRYPOINT

TARGET_CARDINALITY_MIN = 1
TARGET_CARDINALITY_MAX = 5
TARGET_CARDINALITY_RANGE = f"{TARGET_CARDINALITY_MIN}..{TARGET_CARDINALITY_MAX}"

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "STAGED_ADMISSION_AND_AUDIT_COMPOSE_ONLY"
ATLAS_AUTHORITY = "NONE"

N5_ARCHITECTURE_COMPLETE = True
N5_PRODUCTIVE_COMPOSITION_COMPLETE = True
N_GT_1_CAPABILITY_PRESENT = True
N_GT_1_PRODUCTIVE_AUTHORIZATION = False
EXTERNAL_EFFECT_AUTHORIZATION = False

N_GT_1_ENABLED = bool(ORCH_N_GT_1)
MULTI_FUTURE_RUNTIME_AUTHORIZED = bool(ORCH_MF_RUNTIME)
MAX_POSITIONS_EFFECTIVE = int(ORCH_MAX_POSITIONS)
EXTERNAL_EFFECT_AUTHORIZED = ORCH_EXTERNAL_EFFECT
POST_ALLOWED = ORCH_POST
AUTONOMY_TRADING_DECISION_AUTHORITY = ORCH_AUTONOMY_TRADING
PORTFOLIO_RESTART_STATUS = ORCH_PORTFOLIO_RESTART

PRODUCTIVE_AUTHORIZED_MAX_CARDINALITY = (
    TARGET_CARDINALITY_MAX if N_GT_1_ENABLED else TARGET_CARDINALITY_MIN
)

PERMIT_MINT_STATUS = "FORBIDDEN"
VENUE_SUBMISSION_STATUS = "FORBIDDEN"
TERMINAL_BOUNDARY_PRE_EXTERNAL = "PRE_EXTERNAL_EFFECT_OR_EARLIER"
TERMINAL_BOUNDARY_FAIL_CLOSED = "FAIL_CLOSED"

ADMISSION_PRODUCTIVE = "PRODUCTIVE_ADMITTED"
ADMISSION_DENIED_N_GT_1 = "DENIED_N_GT_1_NOT_PRODUCTIVELY_AUTHORIZED"
ADMISSION_ARCHITECTURAL_HARNESS = "ARCHITECTURAL_COMPOSITION_HARNESS_ONLY"

AGGREGATE_ALL_LANES_SUCCESS = "ALL_LANES_TERMINAL_SUCCESS"
AGGREGATE_PARTIAL = "PARTIAL_LANE_NON_SUCCESS"
AGGREGATE_FAIL_CLOSED = "AGGREGATE_FAIL_CLOSED"
AGGREGATE_ADMISSION_DENIED = "ADMISSION_DENIED_BEFORE_ORCHESTRATION"

RECOVERY_LANE_DURABLE = "LANE_DURABLE_ASSIGNMENT_CANONICAL_PATH"
RECOVERY_PORTFOLIO_FAIL_CLOSED = "PORTFOLIO_FAIL_CLOSED_NO_UNPROVEN_RESTORE"
RESTART_SELF_AUTHORIZATION_FORBIDDEN = True

assert N_GT_1_ENABLED is False
assert MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert int(MAX_POSITIONS_EFFECTIVE) == 1
assert EXTERNAL_EFFECT_AUTHORIZED is False
assert POST_ALLOWED is False
assert AUTONOMY_TRADING_DECISION_AUTHORITY is False
assert N_GT_1_PRODUCTIVE_AUTHORIZATION is False
assert EXTERNAL_EFFECT_AUTHORIZATION is False
assert PORTFOLIO_CANONICAL_RESTART_RECONSTRUCTABLE is False
assert PORTFOLIO_RESTART_STATUS == "FAIL_CLOSED_NO_UNPROVEN_RESTORE"

FAILURE_AUTHORITY = "STAGED_N5_CONTROL_PLANE_AUTHORITY_FORBIDDEN"
FAILURE_CARDINALITY = "STAGED_N5_CONTROL_PLANE_CARDINALITY_OUT_OF_RANGE"
FAILURE_EXTERNAL_EFFECT = "STAGED_N5_CONTROL_PLANE_EXTERNAL_EFFECT"
FAILURE_FORBIDDEN_HARNESS = "STAGED_N5_CONTROL_PLANE_FORBIDDEN_HARNESS_ESCALATION"
FAILURE_TERMINAL = "STAGED_N5_CONTROL_PLANE_TERMINAL_FAIL_CLOSED"
