"""Constants for Surface-B OKX public PT1M raw-bytes + exclusive-tip proof v1.

SCOPE=STA_AUTHORIZED_DOWNLOAD_RAW_BYTES_DIGEST_AND_NUMERIC_PROOF_ONLY
AUTHORIZED_NETWORK_FETCH=true
PACK_MATERIALIZATION=false
RAW_INPUT_PACK_CREATED=false
CAMPAIGN_START=false
INPUT_AUTHORITY=false
RUNTIME_IMPLEMENTED=false
PRODUCTIVE_NUMERIC_VALUES_SET=0
DASHBOARD_AUTHORITY_EFFECT=NONE
INVENTED_VALUES=false
SILENT_DEFAULTS=false
PROPOSED_VALUES=false
"""

from __future__ import annotations

CAPABILITY_ID = (
    "CAPABILITY_PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_V1"
)
CAPABILITY_SCOPE = "SURFACE_B_OWNER_STA_OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF"
PACKAGE_MARKER = (
    "PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_V1=true"
)
OWNER = (
    "ops.productive_pure_stack_stage2_surface_b_owner_sta_"
    "okx_public_pt1m_raw_bytes_and_exclusive_tip_proof_v1"
)
SCHEMA_VERSION = (
    "productive_pure_stack_stage2_surface_b_owner_sta_"
    "okx_public_pt1m_raw_bytes_and_exclusive_tip_proof_decisions/v1"
)
DOCUMENT_TYPE = "OWNER_STA_OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_DECISIONS_MANIFEST"
STATUS_NUMERIC_TIP_PROOF_RESOLVED = (
    "OWNER_STA_OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_NUMERIC_TIP_DIGEST_PROOF_RESOLVED"
)

DECISION_ID = "DEC_RAW_INPUT_PACK_MATERIALIZATION"
DECISION_STATUS_RATIFIED = "RATIFIED"
OWNER_VALUE = "AUTHORIZE_SURFACE_B_RAW_INPUT_PACK_MATERIALIZATION"
OWNER_GO = "OWNER_STA_SURFACE_B_OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_V1"
OWNER_GO_BASE_SHA = "54642d8250bb59ba58d98da7ce7b6ab52558e43b"
AUTHORITY_SURFACE = "B"
SOLE_TRADING_AUTHORITY = "run_integrated_offline_trading_logic_replay_v1"

SCOPE = "STA_AUTHORIZED_DOWNLOAD_RAW_BYTES_DIGEST_AND_NUMERIC_PROOF_ONLY"
BAR_INTERVAL = "PT1M"
BAR_INTERVAL_SECONDS = 60
CANDLE_EVENT_TIME_SEMANTICS = "PT1M_BUCKET_OPEN_EVENT_TIME"
MARK_EVENT_TIME_SEMANTICS = "PT1M_BUCKET_OPEN_EVENT_TIME"
EXCLUSIVE_TIP_FORMULA = "last_finalized_common_bucket_open_event_time_epoch_s+60"
EXCLUSIVE_TIP_OFFSET_SECONDS = 60
DOWNLOAD_OR_NETWORK_FETCH_POLICY = "STA_EXPLICITLY_AUTHORIZED_ONLY"

CANDLE_AUTHORITY_SOURCE_REF = "venue://okx/public/rest/v5/market/history-candles?bar=1m&confirm=1"
MARK_AUTHORITY_SOURCE_REF = (
    "venue://okx/public/rest/v5/market/history-mark-price-candles?bar=1m&confirm=1"
)
CANDLE_ENDPOINT = "/api/v5/market/history-candles"
MARK_ENDPOINT = "/api/v5/market/history-mark-price-candles"
CANONICAL_PAGE_LIMIT = "300"
CANONICAL_PAGE_LIMIT_SOURCE = (
    "scripts/ops/ingest_okx_futures_public_market_data_canonical_dataset_staging_v1.py:PAGE_LIMIT"
)
REQUEST_WINDOW_SOURCE = (
    "CANONICAL_OKX_PUBLIC_INGEST_V1_PAGE_LIMIT_300_SINGLE_PAGE_MOST_RECENT_"
    "HISTORY_COMMON_FINALIZED_CONTIGUOUS_WINDOW"
)

REQUIRED_INSTRUMENT_BINDING_V1: dict[str, str] = {
    "venue": "okx",
    "canonical_instrument_id": "inst-eth-usdt-perp",
    "venue_instrument_id": "ETH-USDT-SWAP",
    "contract_type": "perpetual",
    "market_type": "futures",
    "quote_currency": "USDT",
    "settlement_currency": "USDT",
}
INSTRUMENT_BINDING_FIELDS: tuple[str, ...] = tuple(REQUIRED_INSTRUMENT_BINDING_V1.keys())

AUTHORIZED_SOURCE_CLASSES: tuple[str, ...] = (
    "VENUE_NATIVE_OKX_PUBLIC_HISTORY_CANDLES_PT1M_CONFIRM_1",
    "VENUE_NATIVE_OKX_PUBLIC_HISTORY_MARK_PRICE_CANDLES_PT1M_CONFIRM_1",
)

FORBIDDEN_SOURCE_CLASSES: tuple[str, ...] = (
    "DASHBOARD_SOURCE",
    "OKX_ARCHIVE_AS_AUTHORITY",
    "FIXTURE_DEMO_SYNTHETIC_SOURCE",
    "O4_PT1H_AS_PT1M_AUTHORITY",
    "CANDLE_CLOSE_AS_MARK",
    "NOTION_AS_AUTHORITY",
)

FORBIDDEN_SOURCE_TOKENS: tuple[str, ...] = (
    "dashboard",
    "okx_archive",
    "fixture",
    "demo",
    "synthetic",
    "o4_pt1h",
    "candle_close_as_mark",
    "notion",
)

# Sealed from OWNER_GO authorized public fetch against origin/main BASE_SHA.
SEALED_CANDLE_RAW_DIGEST = "e1da39436377d5c9eeae2470b7b21041e7894276e0fb32d9e96e2a60b826c739"
SEALED_MARK_RAW_DIGEST = "1a2a9d48dea7fe44663cc9b3f7a422a0ade9e9f19ca4ae6c0c5effab23aec610"
SEALED_RAW_SOURCE_DIGEST = "9ea3edd6b0b7051a647ff3e6dd64da524b0bbb3ca6850a699c37936ad9541a57"
SEALED_CANDLE_RAW_BYTE_COUNT = 29172
SEALED_MARK_RAW_BYTE_COUNT = 18436
SEALED_CANDLE_ROW_COUNT = 299
SEALED_MARK_ROW_COUNT = 299
SEALED_FIRST_FINALIZED_COMMON_BUCKET_OPEN_EVENT_TIME_EPOCH_S = 1_785_916_740
SEALED_LAST_FINALIZED_COMMON_BUCKET_OPEN_EVENT_TIME_EPOCH_S = 1_785_934_620
SEALED_EXCLUSIVE_TIP_EVENT_TIME_EPOCH_S = 1_785_934_680

UNRESOLVED_FIELDS: tuple[str, ...] = (
    "observation_pack_digest",
    "owner_partition_selection",
    "partition_boundaries_event_time_epoch_s",
    "campaign_id",
    "dataset_id",
    "scenario_id",
)

OWNER_DECISION_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_V1.md"
)
DECISIONS_MANIFEST_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_DECISIONS_V1.json"
)
SCHEMA_REL = (
    "docs/ops/schemas/productive_pure_stack_stage2_surface_b_owner_sta_"
    "okx_public_pt1m_raw_bytes_and_exclusive_tip_proof_decisions_v1.schema.json"
)
CYBERSECURITY_MIRROR_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "OKX_PUBLIC_PT1M_RAW_BYTES_AND_EXCLUSIVE_TIP_PROOF_CYBERSECURITY_MIRROR_V1.md"
)
ARTIFACTS_REL = (
    "docs/ops/artifacts/productive_pure_stack_stage2_surface_b_owner_sta_"
    "okx_public_pt1m_raw_bytes_and_exclusive_tip_proof_v1"
)
CANDLE_RAW_REL = f"{ARTIFACTS_REL}/candle_raw_http_response.json"
MARK_RAW_REL = f"{ARTIFACTS_REL}/mark_raw_http_response.json"
RAW_SOURCE_CONCAT_REL = f"{ARTIFACTS_REL}/raw_source_concat.bin"
NUMERIC_TIP_PROOF_REL = f"{ARTIFACTS_REL}/numeric_tip_proof.json"

PARENT_OBSERVATION_PROOF_DECISION_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "RAW_PT1M_OBSERVATION_INPUT_AND_EXCLUSIVE_TIP_PROOF_V1.md"
)
PARENT_OBSERVATION_PROOF_MANIFEST_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "RAW_PT1M_OBSERVATION_INPUT_AND_EXCLUSIVE_TIP_PROOF_DECISIONS_V1.json"
)
PARENT_MATERIALIZATION_DECISION_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "RAW_INPUT_PACK_MATERIALIZATION_DECISION_V1.md"
)
PARENT_TRIAD_DECISION_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "CANDLE_MARK_INSTRUMENT_AUTHORITY_DECISION_V1.md"
)

PROOF_CONTRACT_READY = True
STA_EXTERNAL_INPUT_FIELDS_READY = True
OWNER_PARTITION_SELECTION_READY = False
NUMERIC_PROOFS_RESOLVED = True
AUTHORIZED_NETWORK_FETCH = True
DOWNLOAD_OR_NETWORK_FETCH = True

PACK_MATERIALIZATION = False
RAW_INPUT_PACK_CREATED = False
RAW_INPUT_PACK_MATERIALIZATION_AUTHORIZED = False
CAMPAIGN_START = False
INPUT_AUTHORITY = False
RUNTIME_IMPLEMENTED = False
REGIME_COVERAGE_PRODUCER_AVAILABLE = False
PRODUCTIVE_NUMERIC_VALUES_SET = 0
PRODUCTIVE_THRESHOLDS_LOOKBACKS = False
TRADING_LOGIC_CHANGE = False
DASHBOARD_AUTHORITY_EFFECT = "NONE"
NOTION_SSOT = False
REPOSITORY_IS_SSOT = True
O4_UNCHANGED = True
O4_PT1H_AS_PT1M_FORBIDDEN = True
ORDERS_TESTNET_LIVE = False
INVENTED_VALUES = False
SILENT_DEFAULTS = False
PROPOSED_VALUES = False
FILL_PARTITION_BOUNDARIES = False
OWNER_PARTITION_SELECTION = False
WALLCLOCK_AS_DATA_AUTHORITY = False
