"""Constants for §11.12.8 OKX EEA Demo XPerp ephemeral campaign private-write gate.

Package default remains ORDER_POST_AUTHORIZED=false. This gate arms ephemeral
Demo mutation only under the full MODE_PRODUCTIVE_REAL precondition chain.
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_11_SECTION_11_12_8_OKX_EEA_DEMO_XPERP_CAMPAIGN_PRIVATE_WRITE_GATE_V1"
PACKAGE_MARKER = (
    "CAPABILITY_11_SECTION_11_12_8_OKX_EEA_DEMO_XPERP_CAMPAIGN_PRIVATE_WRITE_GATE_V1=true"
)
OWNER = "ops.section_11_12_8_okx_eea_demo_xperp_campaign_private_write_gate_v1"
CONTRACT_VERSION = "v1"

# Canonical Owner-GO scope for this path.
SCOPED_OWNER_GO_SCOPE = "EXECUTE_BOUNDED_SECTION_11_12_8_OKX_EEA_DEMO_XPERP_CAMPAIGN"
SCOPED_OWNER_GO_AUTHORIZATION = SCOPED_OWNER_GO_SCOPE
# Legacy aliases — identical XPerp/EEA Demo scope only.
LEGACY_OWNER_GO_SCOPE_LONG_RUNNING = "EXECUTE_BOUNDED_LONG_RUNNING_PRODUCTIVE_TESTNET_CAMPAIGN_NOW"
LEGACY_OWNER_GO_SCOPE_PRODUCTIVE = "EXECUTE_PRODUCTIVE_TESTNET_CAMPAIGN_NOW"
ACCEPTED_OWNER_GO_SCOPES: tuple[str, ...] = (
    SCOPED_OWNER_GO_SCOPE,
    LEGACY_OWNER_GO_SCOPE_LONG_RUNNING,
    LEGACY_OWNER_GO_SCOPE_PRODUCTIVE,
)
ACCEPTED_OWNER_GO_AUTHORIZATIONS: tuple[str, ...] = ACCEPTED_OWNER_GO_SCOPES

VENUE = "OKX_EEA_DEMO"
ENVIRONMENT = "DEMO"
RUNTIME_MODE = "TESTNET"
REST_HOST = "eea.okx.com"
REST_BASE = "https://eea.okx.com"
DEMO_MARKER_HEADER_NAME = "x-simulated-trading"
DEMO_MARKER_HEADER_VALUE = "1"
INSTRUMENT_SCOPE_EXACT = "BTC-USD_UM_XPERP-310328"
INSTRUMENT_TYPE = "FUTURES"
RULE_TYPE = "xperp"
CANONICAL_ORDER_SZ = "0.0001"

# Binding package default must remain false forever in this gate package.
PACKAGE_DEFAULT_ORDER_POST_AUTHORIZED = False
LIVE_AUTHORIZED = False
SECTION_11_13_STARTED = False
PRE_LIVE_CYBERSECURITY_GATE = "NOT_PASSED"
PRE_LIVE_CYBERSECURITY_GATE_CONTRACT = "MANDATORY"

SECTION_11_12_8_STATUS = "OPEN_OKX_EEA_DEMO_XPERP_CAMPAIGN_WRITE_PATH_READY_AWAITING_OWNER_EXECUTE"
CANONICAL_NEXT_STEP_AFTER_MERGE = (
    "OWNER_GO_EXECUTE_BOUNDED_SECTION_11_12_8_OKX_EEA_DEMO_XPERP_CAMPAIGN"
    "_WITH_HIDDEN_CONFIRM_AND_SECRETREF_VAULT_RUNTIME"
)

MUTATION_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/trade/order",
    "/api/v5/trade/cancel-order",
)

EVIDENCE_DIRNAME = "section_11_12_8_okx_eea_demo_xperp_campaign_private_write_gate_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
