"""Standing constants for remaining execution-path end-to-end census persist.

Offline CASE_B contract persist. No GET. No POST. No flatten execute. No
Live/Canary unlock. Does not issue a runtime permit. Does not rewrite STPR text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.remaining_execution_path_census_v1 import (
    CENSUS_IMPLEMENTATION_OWNER_GO,
    NAMED_REMAINING_AFTER_CENSUS,
    START_NODE,
    TERMINAL_EXECUTION_ENDPOINT,
)
from src.ops.section_11_13_5_remaining_execution_path_end_to_end_census_v1.contract_v1 import (
    APT_TEXT_REWRITTEN,
    BOUNDED_RUNTIME_PERMIT_ISSUANCE_STATUS,
    BRPI_NAMED_ISSUANCE_CONTRACT_CLOSED,
    BRPI_RUNTIME_PROVEN,
    CASE,
    CENSUS_COMPLETE,
    CENSUS_DOES_NOT_AUTHORIZE_FLATTEN,
    CENSUS_DOES_NOT_AUTHORIZE_GET,
    CENSUS_DOES_NOT_AUTHORIZE_NETWORK_SESSION,
    CENSUS_DOES_NOT_AUTHORIZE_POST,
    CENSUS_DOES_NOT_GRANT_EXECUTION_READINESS,
    CENSUS_DOES_NOT_ISSUE_RUNTIME_PERMIT,
    CENSUS_DOES_NOT_SET_LIVE_AUTHORIZED,
    CENSUS_EXHAUSTION_PROVEN,
    CREDENTIAL_USE_PROVEN,
    FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE,
    FLATTEN_EXECUTE_AUTHORIZED,
    FLATTEN_EXECUTE_NAMED_CONTRACT_CLOSED,
    FLATTEN_EXECUTE_STATUS,
    LATENT_GAP_CENSUS_COMPLETE,
    NETWORK_PROVEN,
    NETWORK_SESSION_AUTHORIZED,
    NETWORK_SESSION_NAMED_CONTRACT_CLOSED,
    NETWORK_SESSION_STATUS,
    P16_TEXT_REWRITTEN,
    P20_TEXT_REWRITTEN,
    P25_TEXT_REWRITTEN,
    POSITION_GET_AUTHORIZED_BY_THIS_OWNER_GO,
    POSITION_GET_REQUIRED_THIS_PERSIST,
    POST_PROVEN,
    PRIVATE_GET_PROVEN,
    REMAINING_EXECUTION_PATH_CENSUS_STATUS,
    RUNTIME_PERMIT_ISSUED,
    STP_TEXT_REWRITTEN,
    STPR_TEXT_REWRITTEN,
)

CAPABILITY_ID = "REMAINING_EXECUTION_PATH_END_TO_END_CENSUS_V1"
PACKAGE_MARKER = "REMAINING_EXECUTION_PATH_END_TO_END_CENSUS_V1=true"
OWNER = "ops.section_11_13_5_remaining_execution_path_end_to_end_census_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "remaining_execution_path_end_to_end_census.v1"
OWNER_GO = CENSUS_IMPLEMENTATION_OWNER_GO
PRIOR_OWNER_GO = "PEAK_TRADE_OWNER_GO_SEND_TIME_POSITION_REOBSERVATION_MAXIMUM_SAFE_LEVERAGE_V1"
WORKPACKAGE_ID = "OKX_EEA_REMAINING_EXECUTION_PATH_END_TO_END_CENSUS_V1"
THIS_SLICE = "11.13.5.REMAINING_EXECUTION_PATH_END_TO_END_CENSUS"
PREDECESSOR_SLICE = "11.13.5.SEND_TIME_POSITION_REOBSERVATION"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_REMAINING_EXECUTION_PATH_END_TO_END_CENSUS"
EXPECTED_ORIGIN_MAIN_SHA = "5e458798d42430647896e39835e565a7b2e15ffe"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_REMAINING_EXECUTION_PATH_END_TO_END_CENSUS"
AUTHORIZED_SCOPE = "A_REMAINING_EXECUTION_PATH_END_TO_END_CENSUS"
CANONICAL_EVIDENCE_RUN_ID = "20260904T042400Z"

CASE_VALUE = CASE
BOUNDED_RUNTIME_PERMIT_ISSUANCE = BOUNDED_RUNTIME_PERMIT_ISSUANCE_STATUS
FLATTEN_EXECUTE = FLATTEN_EXECUTE_STATUS
NETWORK_SESSION = NETWORK_SESSION_STATUS
REMAINING_EXECUTION_PATH_CENSUS = REMAINING_EXECUTION_PATH_CENSUS_STATUS
BRPI_NAMED_CONTRACT_CLOSED = BRPI_NAMED_ISSUANCE_CONTRACT_CLOSED
FLATTEN_EXECUTE_NAMED_CLOSED = FLATTEN_EXECUTE_NAMED_CONTRACT_CLOSED
NETWORK_SESSION_NAMED_CLOSED = NETWORK_SESSION_NAMED_CONTRACT_CLOSED
CENSUS_COMPLETE_VALUE = CENSUS_COMPLETE
CENSUS_EXHAUSTION_PROVEN_VALUE = CENSUS_EXHAUSTION_PROVEN
LATENT_GAP_CENSUS_COMPLETE_VALUE = LATENT_GAP_CENSUS_COMPLETE
START_NODE_VALUE = START_NODE
TERMINAL_EXECUTION_ENDPOINT_VALUE = TERMINAL_EXECUTION_ENDPOINT
NAMED_REMAINING_HIGHER_AUTHORITY = NAMED_REMAINING_AFTER_CENSUS
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P25_CLOSED = True
STP_CLOSED = True
APT_CLOSED = True
STPR_CLOSED = True
STPR_TEXT_REWRITTEN_VALUE = STPR_TEXT_REWRITTEN
APT_TEXT_REWRITTEN_VALUE = APT_TEXT_REWRITTEN
STP_TEXT_REWRITTEN_VALUE = STP_TEXT_REWRITTEN
P16_TEXT_REWRITTEN_VALUE = P16_TEXT_REWRITTEN
P20_TEXT_REWRITTEN_VALUE = P20_TEXT_REWRITTEN
P25_TEXT_REWRITTEN_VALUE = P25_TEXT_REWRITTEN
CENSUS_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE = CENSUS_DOES_NOT_GRANT_EXECUTION_READINESS
CENSUS_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = CENSUS_DOES_NOT_AUTHORIZE_FLATTEN
CENSUS_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = CENSUS_DOES_NOT_SET_LIVE_AUTHORIZED
CENSUS_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE = CENSUS_DOES_NOT_ISSUE_RUNTIME_PERMIT
CENSUS_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE = CENSUS_DOES_NOT_AUTHORIZE_NETWORK_SESSION
CENSUS_DOES_NOT_AUTHORIZE_GET_VALUE = CENSUS_DOES_NOT_AUTHORIZE_GET
CENSUS_DOES_NOT_AUTHORIZE_POST_VALUE = CENSUS_DOES_NOT_AUTHORIZE_POST
BRPI_RUNTIME_PROVEN_VALUE = BRPI_RUNTIME_PROVEN
NETWORK_PROVEN_VALUE = NETWORK_PROVEN
CREDENTIAL_USE_PROVEN_VALUE = CREDENTIAL_USE_PROVEN
PRIVATE_GET_PROVEN_VALUE = PRIVATE_GET_PROVEN
POST_PROVEN_VALUE = POST_PROVEN
FLATTEN_EXECUTE_AUTHORIZED_VALUE = FLATTEN_EXECUTE_AUTHORIZED
NETWORK_SESSION_AUTHORIZED_VALUE = NETWORK_SESSION_AUTHORIZED
RUNTIME_PERMIT_ISSUED_VALUE = RUNTIME_PERMIT_ISSUED
POSITION_GET_REQUIRED_THIS_PERSIST_VALUE = POSITION_GET_REQUIRED_THIS_PERSIST
POSITION_GET_AUTHORIZED_BY_THIS_OWNER_GO_VALUE = POSITION_GET_AUTHORIZED_BY_THIS_OWNER_GO
FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE_VALUE = (
    FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE
)
EARLIEST_UNRESOLVED_DEPENDENCY = "AUTHENTICATED_PRIVATE_RUNTIME_READ"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_AUTHENTICATED_PRIVATE_RUNTIME_READ"
CENSUS_RUNTIME_RESIDUAL = (
    "AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE_AND_"
    "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_REMAIN_SEPARATE_OWNER_GO"
)
NEXT_WORKPACKAGE = "AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE"
NEXT_OWNER_GO_REQUIRED = (
    "PEAK_TRADE_OWNER_GO_AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE_V1"
)
MINIMUM_ADDITIONAL_OWNER_GO_COUNT = 2
WORKPACKAGE_COUNT = 3
TOTAL_REMAINING_NODE_COUNT = 17
TOTAL_EDGE_COUNT = 19
TOTAL_KNOWN_GAP_COUNT = 13
OFFLINE_NODE_COUNT = 5
RUNTIME_READ_NODE_COUNT = 1
NETWORK_AUTH_NODE_COUNT = 1
PERMIT_NODE_COUNT = 2
PRODUCTIVE_PREPARATION_NODE_COUNT = 1
PRODUCTIVE_WIRE_NODE_COUNT = 1
PRODUCTIVE_EXECUTION_NODE_COUNT = 2
RECONCILIATION_NODE_COUNT = 3
EXTERNAL_STATE_NODE_COUNT = 5
OWNER_DECISION_NODE_COUNT = 0
UNKNOWN_NODE_COUNT = 0
LATENT_OFFLINE_GAPS_BEFORE_WORK = 6
LATENT_OFFLINE_GAPS_CLOSED = 4
LATENT_OFFLINE_GAPS_REMAINING = 2
RUNTIME_GAPS_REMAINING = 7
EXTERNAL_STATE_GAPS_REMAINING = 5
OWNER_DECISIONS_REMAINING = 8
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
LINEAGE_COMPLETE = True

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_remaining_execution_path_end_to_end_census_v1"
