"""Assemble the AUTHENTICATED_PRODUCTIVE_TRANSPORT persist pack."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_13_5_authenticated_productive_transport_v1.adjudicate_v1 import (
    adjudicate_authenticated_productive_transport_v1,
)
from src.ops.section_11_13_5_authenticated_productive_transport_v1.constants_v1 import (
    APT_AUTHENTICATION_PROVEN_VALUE,
    APT_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
    APT_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
    APT_DOES_NOT_AUTHORIZE_SEND_TIME_POSITION_REOBSERVATION_VALUE,
    APT_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
    APT_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
    APT_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
    APT_FLATTEN_EXECUTE_AUTHORIZED_VALUE,
    APT_MECHANISM_IMPLEMENTED,
    APT_NAMED_CONTRACT_CLOSED,
    APT_NETWORK_SESSION_AUTHORIZED_VALUE,
    APT_PRODUCTIVE_SIGNING_REUSE_WIRED_VALUE,
    APT_RUNTIME_PROVEN_VALUE,
    APT_RUNTIME_RESIDUAL,
    AUTHENTICATED_PRODUCTIVE_TRANSPORT,
    AUTHORIZED_ACCOUNT_UID,
    AUTHORIZED_HOST,
    AUTHORIZED_OPERATION,
    AUTHORIZED_SCOPE,
    CANONICAL_EVIDENCE_RUN_ID,
    CASE_VALUE,
    CONFLICT_COUNT,
    CREDENTIAL_USE_PROVEN_VALUE,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EXPECTED_ORIGIN_MAIN_SHA,
    FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE_VALUE,
    LAST_CANONICALLY_CLOSED_STEP,
    NAMED_REMAINING_HIGHER_AUTHORITY,
    NETWORK_PROVEN_VALUE,
    NEXT_AUTHORITY_BOUNDARY,
    OWNER_GO,
    P08_CLOSED,
    P10_CLOSED,
    P11_CLOSED,
    P12_CLOSED,
    P13_CLOSED,
    P16_CLOSED,
    P16_TEXT_REWRITTEN_VALUE,
    P20_CLOSED,
    P20_TEXT_REWRITTEN_VALUE,
    P25_CLOSED,
    P25_TEXT_REWRITTEN_VALUE,
    POST_PROVEN_VALUE,
    PREDECESSOR_SLICE,
    PRIOR_OWNER_GO,
    PRIVATE_AUTH_USED,
    PRIVATE_GET_PROVEN_VALUE,
    PRODUCTIVE_SIGNING_COMPONENT_VALUE,
    PUBLIC_SPEC_RETRIEVAL_PERFORMED,
    RUNTIME_GET_PERFORMED,
    RUNTIME_GET_REQUIRED,
    STP_CLOSED,
    STP_TEXT_REWRITTEN_VALUE,
    TARGET_INSTRUMENT_ID,
    THIS_GO_GET_COUNT,
    THIS_GO_POST_COUNT,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.section_11_13_5_authenticated_productive_transport_v1.persist_v1 import (
    persist_authenticated_productive_transport_evidence_v1,
)


class AuthenticatedProductiveTransportAssembleError(RuntimeError):
    """Fail-closed assemble violation."""


def assemble_authenticated_productive_transport_v1(
    *,
    origin_main_sha: str,
    evidence_root: Path | None = None,
    run_id: str = CANONICAL_EVIDENCE_RUN_ID,
) -> dict[str, Any]:
    """Build and optionally persist authenticated productive transport. No GET. No POST."""
    if str(origin_main_sha or "").strip() != EXPECTED_ORIGIN_MAIN_SHA:
        raise AuthenticatedProductiveTransportAssembleError("ORIGIN_MAIN_SHA_MISMATCH")
    verdict = adjudicate_authenticated_productive_transport_v1(origin_main_sha=origin_main_sha)
    if verdict["AUTHENTICATED_PRODUCTIVE_TRANSPORT"] != "PASS_OFFLINE_CONTRACT":
        raise AuthenticatedProductiveTransportAssembleError(
            "AUTHENTICATED_PRODUCTIVE_TRANSPORT_MUST_BE_PASS_OFFLINE_CONTRACT"
        )
    if verdict["AUTHENTICATED_PRODUCTIVE_TRANSPORT_RUNTIME_PROVEN"] is True:
        raise AuthenticatedProductiveTransportAssembleError("RUNTIME_PROVEN_MUST_REMAIN_FALSE")
    if verdict["AUTHENTICATION_PROVEN"] is True:
        raise AuthenticatedProductiveTransportAssembleError(
            "AUTHENTICATION_PROVEN_MUST_REMAIN_FALSE"
        )
    if verdict["APT_FLATTEN_EXECUTE_AUTHORIZED"] is True:
        raise AuthenticatedProductiveTransportAssembleError(
            "FLATTEN_EXECUTE_MUST_REMAIN_UNAUTHORIZED"
        )
    census = {
        "DOCUMENT_CLASS": "AUTHENTICATED_PRODUCTIVE_TRANSPORT_CENSUS_V1",
        "DOCUMENT_ROLE": "FORENSIC_CENSUS_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "SEAM_COUNT": verdict["CENSUS"]["SEAM_COUNT"],
        "EPISTEMIC_CLASS_COUNTS": verdict["CENSUS"]["EPISTEMIC_CLASS_COUNTS"],
        "PROVEN_SEAMS": verdict["CENSUS"]["PROVEN_SEAMS"],
        "NOT_PROMOTED_SEAMS": verdict["CENSUS"]["NOT_PROMOTED_SEAMS"],
        "NAMED_REMAINING_HIGHER_AUTHORITY": list(NAMED_REMAINING_HIGHER_AUTHORITY),
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
        "AUTHENTICATION_PROVEN": False,
        "NETWORK_PROVEN": False,
        "CREDENTIAL_USE_PROVEN": False,
    }
    lineage = {
        "DOCUMENT_CLASS": "AUTHENTICATED_PRODUCTIVE_TRANSPORT_LINEAGE_V1",
        "DOCUMENT_ROLE": "FORENSIC_LINEAGE_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "LINEAGE_FIELD_NAMES": verdict["CENSUS"]["LINEAGE_FIELD_NAMES"],
        "SEAMS": verdict["LINEAGE"],
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
    }
    adjudication = {
        "DOCUMENT_CLASS": "AUTHENTICATED_PRODUCTIVE_TRANSPORT_ADJUDICATION_V1",
        "DOCUMENT_ROLE": "INTERPRETATION_NOT_RAW_WIRE_NOT_SSOT",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "AUTHENTICATED_PRODUCTIVE_TRANSPORT": AUTHENTICATED_PRODUCTIVE_TRANSPORT,
        "AUTHENTICATED_PRODUCTIVE_TRANSPORT_OFFLINE_CONTRACT": AUTHENTICATED_PRODUCTIVE_TRANSPORT,
        "APT_NAMED_AUTHENTICATED_TRANSPORT_CONTRACT_CLOSED": APT_NAMED_CONTRACT_CLOSED,
        "APT_AUTHENTICATED_TRANSPORT_GATE_IMPLEMENTED": APT_MECHANISM_IMPLEMENTED,
        "APT_PRODUCTIVE_SIGNING_REUSE_WIRED": APT_PRODUCTIVE_SIGNING_REUSE_WIRED_VALUE,
        "PRODUCTIVE_SIGNING_COMPONENT": PRODUCTIVE_SIGNING_COMPONENT_VALUE,
        "AUTHENTICATED_PRODUCTIVE_TRANSPORT_RUNTIME_PROVEN": APT_RUNTIME_PROVEN_VALUE,
        "AUTHENTICATION_PROVEN": APT_AUTHENTICATION_PROVEN_VALUE,
        "NETWORK_PROVEN": NETWORK_PROVEN_VALUE,
        "CREDENTIAL_USE_PROVEN": CREDENTIAL_USE_PROVEN_VALUE,
        "PRIVATE_GET_PROVEN": PRIVATE_GET_PROVEN_VALUE,
        "POST_PROVEN": POST_PROVEN_VALUE,
        "APT_NETWORK_SESSION_AUTHORIZED": APT_NETWORK_SESSION_AUTHORIZED_VALUE,
        "APT_FLATTEN_EXECUTE_AUTHORIZED": APT_FLATTEN_EXECUTE_AUTHORIZED_VALUE,
        "NAMED_REMAINING_HIGHER_AUTHORITY": list(NAMED_REMAINING_HIGHER_AUTHORITY),
        "OFFLINE_CONTRACT_PROOF_CLASS": verdict["OFFLINE_CONTRACT_PROOF_CLASS"],
        "STRUCTURAL_ALLOW_IS_NOT_RUNTIME_MUTATION": True,
        "STRUCTURAL_ALLOW_IS_NOT_WIRE_SEND": True,
        "FAIL_CLOSED_STATUS": verdict["FAIL_CLOSED_STATUS"],
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P08_CLOSED": P08_CLOSED,
        "P10_CLOSED": P10_CLOSED,
        "P11_CLOSED": P11_CLOSED,
        "P12_CLOSED": P12_CLOSED,
        "P13_CLOSED": P13_CLOSED,
        "P16_CLOSED": P16_CLOSED,
        "P20_CLOSED": P20_CLOSED,
        "P25_CLOSED": P25_CLOSED,
        "STP_CLOSED": STP_CLOSED,
        "STP_TEXT_REWRITTEN": STP_TEXT_REWRITTEN_VALUE,
        "P16_TEXT_REWRITTEN": P16_TEXT_REWRITTEN_VALUE,
        "P20_TEXT_REWRITTEN": P20_TEXT_REWRITTEN_VALUE,
        "P25_TEXT_REWRITTEN": P25_TEXT_REWRITTEN_VALUE,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "APT_RUNTIME_RESIDUAL": APT_RUNTIME_RESIDUAL,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_POST_COUNT": THIS_GO_POST_COUNT,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "APT_DOES_NOT_GRANT_EXECUTION_READINESS": APT_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
        "APT_DOES_NOT_AUTHORIZE_FLATTEN": APT_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
        "APT_DOES_NOT_SET_LIVE_AUTHORIZED": APT_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
        "APT_DOES_NOT_ISSUE_RUNTIME_PERMIT": APT_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
        "APT_DOES_NOT_AUTHORIZE_NETWORK_SESSION": APT_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
        "APT_DOES_NOT_AUTHORIZE_SEND_TIME_POSITION_REOBSERVATION": (
            APT_DOES_NOT_AUTHORIZE_SEND_TIME_POSITION_REOBSERVATION_VALUE
        ),
        "FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE": (
            FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE_VALUE
        ),
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "NETWORK_SESSION_AUTHORIZED_DEFAULT": False,
        "IMPLEMENTATION_GO_FORBIDDEN_AS_FLATTEN_EXECUTE": True,
        "CENSUS": verdict["CENSUS"],
        "LINEAGE": verdict["LINEAGE"],
        "WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY": verdict["WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY"],
    }
    summary = {
        "DOCUMENT_CLASS": "AUTHENTICATED_PRODUCTIVE_TRANSPORT_PACKAGE_V1",
        "DOCUMENT_ROLE": "DERIVED_NON_SSOT",
        "OWNER_GO": OWNER_GO,
        "OWNER_GO_CONSUMED": True,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "AUTHORIZED_SCOPE": AUTHORIZED_SCOPE,
        "AUTHORIZED_OPERATION": AUTHORIZED_OPERATION,
        "HOST": AUTHORIZED_HOST,
        "AUTHORIZED_ACCOUNT_UID": AUTHORIZED_ACCOUNT_UID,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "AUTHENTICATED_PRODUCTIVE_TRANSPORT": AUTHENTICATED_PRODUCTIVE_TRANSPORT,
        "AUTHENTICATED_PRODUCTIVE_TRANSPORT_OFFLINE_CONTRACT": AUTHENTICATED_PRODUCTIVE_TRANSPORT,
        "AUTHENTICATED_PRODUCTIVE_TRANSPORT_RUNTIME_PROVEN": False,
        "AUTHENTICATION_PROVEN": False,
        "NETWORK_PROVEN": False,
        "CREDENTIAL_USE_PROVEN": False,
        "PRIVATE_GET_PROVEN": False,
        "POST_PROVEN": False,
        "APT_FLATTEN_EXECUTE_AUTHORIZED": False,
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "STP_CLOSED": True,
        "STP_TEXT_REWRITTEN": False,
        "P25_CLOSED": True,
        "P25_TEXT_REWRITTEN": False,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "APT_RUNTIME_RESIDUAL": APT_RUNTIME_RESIDUAL,
        "GET_REQUEST_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "HTTP_EXCHANGE_COUNT": 0,
        "POST_COUNT": THIS_GO_POST_COUNT,
        "WRITE_REQUEST_COUNT": 0,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "PRIVATE_AUTH_USED": False,
        "LIVE_AUTHORIZED": False,
        "CANARY_AUTHORIZED": False,
        "SUBMIT_UNLOCKED": False,
        "LIVE_ENABLED": False,
        "LIVE_ARMED": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
        "APT_DOES_NOT_GRANT_EXECUTION_READINESS": True,
        "EXECUTION_READY": False,
        "ATLAS_AUTHORITY": "NONE",
        "LANDSCAPE_AUTHORITY": "NONE",
    }
    result: dict[str, Any] = {
        "verdict": verdict,
        "census": census,
        "lineage": lineage,
        "adjudication": adjudication,
        "summary": summary,
    }
    if evidence_root is not None:
        pack = Path(evidence_root) / run_id
        verified = persist_authenticated_productive_transport_evidence_v1(
            pack=pack,
            origin_main_sha=origin_main_sha,
            census=census,
            lineage=lineage,
            adjudication=adjudication,
            summary=summary,
        )
        result["EVIDENCE_PACK"] = str(pack)
        result["MANIFEST_VERIFY_RC"] = int(verified.get("MANIFEST_VERIFY_RC", 1))
    return result
