"""Standing constants for AUTHENTICATED_PRODUCTIVE_TRANSPORT offline contract.

Offline CASE_B contract persist. No GET. No POST. No flatten execute. No
Live/Canary unlock. Does not issue a runtime permit. Does not rewrite STP text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_authenticated_productive_transport_v1.contract_v1 import (
    APT_AUTHENTICATION_PROVEN,
    APT_AUTHENTICATED_TRANSPORT_GATE_IMPLEMENTED,
    APT_DOES_NOT_AUTHORIZE_FLATTEN,
    APT_DOES_NOT_AUTHORIZE_NETWORK_SESSION,
    APT_DOES_NOT_AUTHORIZE_SEND_TIME_POSITION_REOBSERVATION,
    APT_DOES_NOT_GRANT_EXECUTION_READINESS,
    APT_DOES_NOT_ISSUE_RUNTIME_PERMIT,
    APT_DOES_NOT_SET_LIVE_AUTHORIZED,
    APT_FLATTEN_EXECUTE_AUTHORIZED,
    APT_NAMED_AUTHENTICATED_TRANSPORT_CONTRACT_CLOSED,
    APT_NETWORK_SESSION_AUTHORIZED,
    APT_PRODUCTIVE_SIGNING_REUSE_WIRED,
    APT_RUNTIME_PROVEN,
    AUTHENTICATED_PRODUCTIVE_TRANSPORT_STATUS,
    CASE,
    CREDENTIAL_USE_PROVEN,
    FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE,
    NETWORK_PROVEN,
    P16_TEXT_REWRITTEN,
    P20_TEXT_REWRITTEN,
    P25_TEXT_REWRITTEN,
    POST_PROVEN,
    PRIVATE_GET_PROVEN,
    STP_TEXT_REWRITTEN,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.authenticated_productive_transport_v1 import (
    APT_IMPLEMENTATION_OWNER_GO,
    NAMED_REMAINING_AFTER_AUTHENTICATED_PRODUCTIVE_TRANSPORT,
    PRODUCTIVE_SIGNING_COMPONENT,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)

CAPABILITY_ID = "AUTHENTICATED_PRODUCTIVE_TRANSPORT_V1"
PACKAGE_MARKER = "AUTHENTICATED_PRODUCTIVE_TRANSPORT_V1=true"
OWNER = "ops.section_11_13_5_authenticated_productive_transport_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "authenticated_productive_transport.v1"
OWNER_GO = APT_IMPLEMENTATION_OWNER_GO
PRIOR_OWNER_GO = "PEAK_TRADE_OWNER_GO_SEND_TIME_PASS_18_19_21_24_MAXIMUM_SAFE_LEVERAGE_V1"
WORKPACKAGE_ID = "OKX_EEA_AUTHENTICATED_PRODUCTIVE_TRANSPORT_V1"
THIS_SLICE = "11.13.5.AUTHENTICATED_PRODUCTIVE_TRANSPORT"
PREDECESSOR_SLICE = "11.13.5.SEND_TIME_PASS"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_AUTHENTICATED_PRODUCTIVE_TRANSPORT"
EXPECTED_ORIGIN_MAIN_SHA = "031ba38766fa2f3ac821d45ca84f88f8a0894bf1"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_AUTHENTICATED_PRODUCTIVE_TRANSPORT"
AUTHORIZED_SCOPE = "A_AUTHENTICATED_PRODUCTIVE_TRANSPORT"
CANONICAL_EVIDENCE_RUN_ID = "20260904T031700Z"

CASE_VALUE = CASE
AUTHENTICATED_PRODUCTIVE_TRANSPORT = AUTHENTICATED_PRODUCTIVE_TRANSPORT_STATUS
APT_NAMED_CONTRACT_CLOSED = APT_NAMED_AUTHENTICATED_TRANSPORT_CONTRACT_CLOSED
APT_MECHANISM_IMPLEMENTED = APT_AUTHENTICATED_TRANSPORT_GATE_IMPLEMENTED
NAMED_REMAINING_HIGHER_AUTHORITY = NAMED_REMAINING_AFTER_AUTHENTICATED_PRODUCTIVE_TRANSPORT
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P25_CLOSED = True
STP_CLOSED = True
STP_TEXT_REWRITTEN_VALUE = STP_TEXT_REWRITTEN
P16_TEXT_REWRITTEN_VALUE = P16_TEXT_REWRITTEN
P20_TEXT_REWRITTEN_VALUE = P20_TEXT_REWRITTEN
P25_TEXT_REWRITTEN_VALUE = P25_TEXT_REWRITTEN
APT_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE = APT_DOES_NOT_GRANT_EXECUTION_READINESS
APT_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = APT_DOES_NOT_AUTHORIZE_FLATTEN
APT_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = APT_DOES_NOT_SET_LIVE_AUTHORIZED
APT_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE = APT_DOES_NOT_ISSUE_RUNTIME_PERMIT
APT_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE = APT_DOES_NOT_AUTHORIZE_NETWORK_SESSION
APT_DOES_NOT_AUTHORIZE_SEND_TIME_POSITION_REOBSERVATION_VALUE = (
    APT_DOES_NOT_AUTHORIZE_SEND_TIME_POSITION_REOBSERVATION
)
APT_PRODUCTIVE_SIGNING_REUSE_WIRED_VALUE = APT_PRODUCTIVE_SIGNING_REUSE_WIRED
APT_AUTHENTICATION_PROVEN_VALUE = APT_AUTHENTICATION_PROVEN
APT_RUNTIME_PROVEN_VALUE = APT_RUNTIME_PROVEN
NETWORK_PROVEN_VALUE = NETWORK_PROVEN
CREDENTIAL_USE_PROVEN_VALUE = CREDENTIAL_USE_PROVEN
PRIVATE_GET_PROVEN_VALUE = PRIVATE_GET_PROVEN
POST_PROVEN_VALUE = POST_PROVEN
APT_NETWORK_SESSION_AUTHORIZED_VALUE = APT_NETWORK_SESSION_AUTHORIZED
APT_FLATTEN_EXECUTE_AUTHORIZED_VALUE = APT_FLATTEN_EXECUTE_AUTHORIZED
FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE_VALUE = (
    FAIL_CLOSED_IF_MARKED_RUNTIME_PROVEN_FROM_OFFLINE_CODE_ALONE
)
PRODUCTIVE_SIGNING_COMPONENT_VALUE = PRODUCTIVE_SIGNING_COMPONENT
EARLIEST_UNRESOLVED_DEPENDENCY = "SEND_TIME_POSITION_REOBSERVATION"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_SEND_TIME_POSITION_REOBSERVATION"
APT_RUNTIME_RESIDUAL = (
    "SEND_TIME_POSITION_REOBSERVATION_AND_FLATTEN_EXECUTE_AND_"
    "BOUNDED_RUNTIME_PERMIT_ISSUANCE_AND_NETWORK_SESSION_REMAIN_SEPARATE_OWNER_GO"
)
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
CENSUS_COMPLETE = True
LINEAGE_COMPLETE = True

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_authenticated_productive_transport_v1"
