"""Assemble the P16 EXECUTION_PREREQUISITE_16 bounded activation persist pack."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.adjudicate_v1 import (
    adjudicate_execution_prerequisite_16_bounded_activation_v1,
)
from src.ops.section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.constants_v1 import (
    AUTHORIZED_ACCOUNT_UID,
    AUTHORIZED_HOST,
    AUTHORIZED_OPERATION,
    AUTHORIZED_SCOPE,
    BOUNDED_ACTIVATION_NARROWER_THAN_GLOBAL_LIVE_VALUE,
    BOUNDED_ACTIVATION_OWNER_GO_CANONICAL_VALUE,
    BOUNDED_ACTIVATION_PERMIT_KIND_VALUE,
    BOUNDED_ACTIVATION_PURPOSE_VALUE,
    CANONICAL_EVIDENCE_RUN_ID,
    CASE_VALUE,
    CONFLICT_COUNT,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED,
    EXPECTED_ORIGIN_MAIN_SHA,
    FAIL_CLOSED_IF_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE,
    GLOBAL_LIVE_AUTHORIZED_REQUIRED_VALUE,
    LAST_CANONICALLY_CLOSED_STEP,
    NEXT_AUTHORITY_BOUNDARY,
    OWNER_GO,
    P08_CLOSED,
    P10_CLOSED,
    P11_CLOSED,
    P12_CLOSED,
    P13_CLOSED,
    P13_TEXT_REWRITTEN_VALUE,
    P16_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
    P16_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
    P16_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
    P16_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
    P16_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
    P16_MECHANISM_IMPLEMENTED,
    P16_NAMED_CONTRACT_CLOSED,
    P16_RUNTIME_RESIDUAL,
    PREDECESSOR_SLICE,
    PRIOR_OWNER_GO,
    PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN_VALUE,
    PREREQUISITE_16_FLATTEN_EXECUTE_AUTHORIZED_VALUE,
    PREREQUISITE_16_NETWORK_SESSION_AUTHORIZED_VALUE,
    PRIVATE_AUTH_USED,
    PUBLIC_SPEC_RETRIEVAL_PERFORMED,
    RUNTIME_GET_PERFORMED,
    RUNTIME_GET_REQUIRED,
    TARGET_INSTRUMENT_ID,
    THIS_GO_GET_COUNT,
    THIS_GO_POST_COUNT,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.persist_v1 import (
    persist_p16_bounded_activation_evidence_v1,
)


class P16BoundedActivationAssembleError(RuntimeError):
    """Fail-closed assemble violation."""


def assemble_p16_execution_prerequisite_16_bounded_activation_v1(
    *,
    origin_main_sha: str,
    evidence_root: Path | None = None,
    run_id: str = CANONICAL_EVIDENCE_RUN_ID,
) -> dict[str, Any]:
    """Build and optionally persist prerequisite 16. No GET. No POST."""
    if str(origin_main_sha or "").strip() != EXPECTED_ORIGIN_MAIN_SHA:
        raise P16BoundedActivationAssembleError("ORIGIN_MAIN_SHA_MISMATCH")
    verdict = adjudicate_execution_prerequisite_16_bounded_activation_v1(
        origin_main_sha=origin_main_sha
    )
    if (
        verdict["EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED"]
        != "PASS_OFFLINE_CONTRACT"
    ):
        raise P16BoundedActivationAssembleError("PREREQUISITE_16_MUST_BE_PASS_OFFLINE_CONTRACT")
    if verdict["PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN"] is True:
        raise P16BoundedActivationAssembleError("RUNTIME_ACTIVATION_MUST_REMAIN_UNPROVEN")
    census = {
        "DOCUMENT_CLASS": "P16_EXECUTION_PREREQUISITE_16_CENSUS_V1",
        "DOCUMENT_ROLE": "FORENSIC_CENSUS_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "SEAM_COUNT": verdict["CENSUS"]["SEAM_COUNT"],
        "EPISTEMIC_CLASS_COUNTS": verdict["CENSUS"]["EPISTEMIC_CLASS_COUNTS"],
        "PROVEN_SEAMS": verdict["CENSUS"]["PROVEN_SEAMS"],
        "NOT_PROMOTED_SEAMS": verdict["CENSUS"]["NOT_PROMOTED_SEAMS"],
        "BOUNDED_ACTIVATION_PERMIT_KIND": BOUNDED_ACTIVATION_PERMIT_KIND_VALUE,
        "GLOBAL_LIVE_AUTHORIZED_REQUIRED": GLOBAL_LIVE_AUTHORIZED_REQUIRED_VALUE,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
    }
    lineage = {
        "DOCUMENT_CLASS": "P16_EXECUTION_PREREQUISITE_16_LINEAGE_V1",
        "DOCUMENT_ROLE": "FORENSIC_LINEAGE_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "LINEAGE_FIELD_NAMES": verdict["CENSUS"]["LINEAGE_FIELD_NAMES"],
        "SEAMS": verdict["LINEAGE"],
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
    }
    adjudication = {
        "DOCUMENT_CLASS": "P16_EXECUTION_PREREQUISITE_16_ADJUDICATION_V1",
        "DOCUMENT_ROLE": "INTERPRETATION_NOT_RAW_WIRE_NOT_SSOT",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED": (
            EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED
        ),
        "P16_NAMED_WITHOUT_GLOBAL_LIVE_AUTHORIZED_CONTRACT_CLOSED": P16_NAMED_CONTRACT_CLOSED,
        "P16_BOUNDED_ACTIVATION_PERMIT_MECHANISM_IMPLEMENTED": P16_MECHANISM_IMPLEMENTED,
        "PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN": (
            PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN_VALUE
        ),
        "PREREQUISITE_16_NETWORK_SESSION_AUTHORIZED": (
            PREREQUISITE_16_NETWORK_SESSION_AUTHORIZED_VALUE
        ),
        "PREREQUISITE_16_FLATTEN_EXECUTE_AUTHORIZED": (
            PREREQUISITE_16_FLATTEN_EXECUTE_AUTHORIZED_VALUE
        ),
        "GLOBAL_LIVE_AUTHORIZED_REQUIRED": GLOBAL_LIVE_AUTHORIZED_REQUIRED_VALUE,
        "BOUNDED_ACTIVATION_NARROWER_THAN_GLOBAL_LIVE": (
            BOUNDED_ACTIVATION_NARROWER_THAN_GLOBAL_LIVE_VALUE
        ),
        "BOUNDED_ACTIVATION_PERMIT_KIND": BOUNDED_ACTIVATION_PERMIT_KIND_VALUE,
        "BOUNDED_ACTIVATION_PURPOSE": BOUNDED_ACTIVATION_PURPOSE_VALUE,
        "BOUNDED_ACTIVATION_OWNER_GO_CANONICAL": BOUNDED_ACTIVATION_OWNER_GO_CANONICAL_VALUE,
        "STRUCTURAL_BOUNDED_PATH_ALLOWED_WITHOUT_LIVE_AUTHORIZED": verdict[
            "STRUCTURAL_BOUNDED_PATH_ALLOWED_WITHOUT_LIVE_AUTHORIZED"
        ],
        "STRUCTURAL_ALLOW_IS_NOT_RUNTIME_ACTIVATION": True,
        "STRUCTURAL_ALLOW_IS_NOT_WIRE_SEND": True,
        "OFFLINE_CONTRACT_PROOF_PERMIT_CLASS": verdict["OFFLINE_CONTRACT_PROOF_PERMIT_CLASS"],
        "FAIL_CLOSED_STATUS": verdict["FAIL_CLOSED_STATUS"],
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P08_CLOSED": P08_CLOSED,
        "P10_CLOSED": P10_CLOSED,
        "P11_CLOSED": P11_CLOSED,
        "P12_CLOSED": P12_CLOSED,
        "P13_CLOSED": P13_CLOSED,
        "P13_TEXT_REWRITTEN": P13_TEXT_REWRITTEN_VALUE,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "P16_RUNTIME_RESIDUAL": P16_RUNTIME_RESIDUAL,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_POST_COUNT": THIS_GO_POST_COUNT,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "P16_DOES_NOT_GRANT_EXECUTION_READINESS": P16_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
        "P16_DOES_NOT_AUTHORIZE_FLATTEN": P16_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
        "P16_DOES_NOT_SET_LIVE_AUTHORIZED": P16_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
        "P16_DOES_NOT_ISSUE_RUNTIME_PERMIT": P16_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
        "P16_DOES_NOT_AUTHORIZE_NETWORK_SESSION": P16_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
        "FAIL_CLOSED_IF_PREREQUISITE_16_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE": (
            FAIL_CLOSED_IF_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE
        ),
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "NETWORK_SESSION_AUTHORIZED_DEFAULT": False,
        "IMPLEMENTATION_GO_FORBIDDEN_AS_FLATTEN_EXECUTE": True,
        "IMPLEMENTATION_GO_FORBIDDEN_AS_BOUNDED_PERMIT": True,
        "MISSING_PERMIT_DENIES": True,
        "EXPIRED_PERMIT_DENIES": True,
        "STALE_BOUND_PERMIT_DENIES": True,
        "GLOBAL_LIVE_AUTHORIZED_SUBSTITUTE_DENIES": True,
        "CENSUS": verdict["CENSUS"],
        "LINEAGE": verdict["LINEAGE"],
        "WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY": verdict["WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY"],
    }
    summary = {
        "DOCUMENT_CLASS": "P16_EXECUTION_PREREQUISITE_16_PACKAGE_V1",
        "DOCUMENT_ROLE": "DERIVED_NON_SSOT",
        "OWNER_GO": OWNER_GO,
        "OWNER_GO_CONSUMED": True,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "AUTHORIZED_SCOPE": AUTHORIZED_SCOPE,
        "AUTHORIZED_OPERATION": AUTHORIZED_OPERATION,
        "HOST": AUTHORIZED_HOST,
        "AUTHORIZED_ACCOUNT_UID": AUTHORIZED_ACCOUNT_UID,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED": (
            EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED
        ),
        "P16_NAMED_WITHOUT_GLOBAL_LIVE_AUTHORIZED_CONTRACT_CLOSED": P16_NAMED_CONTRACT_CLOSED,
        "PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN": False,
        "GLOBAL_LIVE_AUTHORIZED_REQUIRED": False,
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P13_CLOSED": True,
        "P13_TEXT_REWRITTEN": False,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "P16_RUNTIME_RESIDUAL": P16_RUNTIME_RESIDUAL,
        "GET_REQUEST_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "HTTP_EXCHANGE_COUNT": 0,
        "POST_COUNT": THIS_GO_POST_COUNT,
        "WRITE_REQUEST_COUNT": 0,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "PRIVATE_AUTH_USED": False,
        "LIVE_AUTHORIZED": False,
        "CANARY_AUTHORIZED": False,
        "SUBMIT_UNLOCKED": False,
        "LIVE_ENABLED": False,
        "LIVE_ARMED": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "P16_DOES_NOT_GRANT_EXECUTION_READINESS": True,
        "EXECUTION_READY": False,
        "ATLAS_AUTHORITY": "NONE",
        "LANDSCAPE_AUTHORITY": "NONE",
    }
    result: dict[str, Any] = {
        "verdict": verdict,
        "census": census,
        "lineage": lineage,
        "adjudication": adjudication,
        "summary": summary,
    }
    if evidence_root is not None:
        pack = Path(evidence_root) / run_id
        verified = persist_p16_bounded_activation_evidence_v1(
            pack=pack,
            origin_main_sha=origin_main_sha,
            census=census,
            lineage=lineage,
            adjudication=adjudication,
            summary=summary,
        )
        result["EVIDENCE_PACK"] = str(pack)
        result["MANIFEST_VERIFY_RC"] = int(verified.get("MANIFEST_VERIFY_RC", 1))
    return result
