"""Standing constants for EXECUTION_PREREQUISITE_16 bounded activation.

Offline CASE_B contract persist. No GET. No POST. No flatten execute. No
Live/Canary unlock. Does not set LIVE_AUTHORIZED. Does not rewrite P13 text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.bounded_activation_permit_v1 import (
    BOUNDED_ACTIVATION_OWNER_GO_CANONICAL,
    BOUNDED_ACTIVATION_PERMIT_KIND,
    BOUNDED_ACTIVATION_PURPOSE_CANONICAL,
    P16_IMPLEMENTATION_OWNER_GO,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1.contract_v1 import (
    BOUNDED_ACTIVATION_NARROWER_THAN_GLOBAL_LIVE,
    CASE,
    EXECUTION_PREREQUISITE_16_STATUS,
    FAIL_CLOSED_IF_PREREQUISITE_16_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE,
    GLOBAL_LIVE_AUTHORIZED_REQUIRED,
    P13_TEXT_REWRITTEN,
    P16_BOUNDED_ACTIVATION_PERMIT_MECHANISM_IMPLEMENTED,
    P16_DOES_NOT_AUTHORIZE_FLATTEN,
    P16_DOES_NOT_AUTHORIZE_NETWORK_SESSION,
    P16_DOES_NOT_GRANT_EXECUTION_READINESS,
    P16_DOES_NOT_ISSUE_RUNTIME_PERMIT,
    P16_DOES_NOT_SET_LIVE_AUTHORIZED,
    P16_NAMED_WITHOUT_GLOBAL_LIVE_AUTHORIZED_CONTRACT_CLOSED,
    PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN,
    PREREQUISITE_16_FLATTEN_EXECUTE_AUTHORIZED,
    PREREQUISITE_16_NETWORK_SESSION_AUTHORIZED,
)

CAPABILITY_ID = "P16_EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_V1"
PACKAGE_MARKER = "P16_EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_V1=true"
OWNER = "ops.section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p16_execution_prerequisite_16_bounded_activation.v1"
OWNER_GO = P16_IMPLEMENTATION_OWNER_GO
PRIOR_OWNER_GO = "PEAK_TRADE_OWNER_GO_P12_EXACT_FLATTEN_PAYLOAD_MAXIMUM_SAFE_LEVERAGE_V1"
WORKPACKAGE_ID = "OKX_EEA_P16_EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_V1"
THIS_SLICE = "11.13.5.P16"
PREDECESSOR_SLICE = "11.13.5.P13"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_P16"
EXPECTED_ORIGIN_MAIN_SHA = "02a3946ccf8343d0cf526becc932c93092d55811"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = (
    "OFFLINE_EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED"
)
AUTHORIZED_SCOPE = "A_P16_EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION"
CANONICAL_EVIDENCE_RUN_ID = "20260904T011500Z"

CASE_VALUE = CASE
EXECUTION_PREREQUISITE_16_BOUNDED_ACTIVATION_WITHOUT_GLOBAL_LIVE_AUTHORIZED = (
    EXECUTION_PREREQUISITE_16_STATUS
)
P16_NAMED_CONTRACT_CLOSED = P16_NAMED_WITHOUT_GLOBAL_LIVE_AUTHORIZED_CONTRACT_CLOSED
P16_MECHANISM_IMPLEMENTED = P16_BOUNDED_ACTIVATION_PERMIT_MECHANISM_IMPLEMENTED
BOUNDED_ACTIVATION_PERMIT_KIND_VALUE = BOUNDED_ACTIVATION_PERMIT_KIND
BOUNDED_ACTIVATION_PURPOSE_VALUE = BOUNDED_ACTIVATION_PURPOSE_CANONICAL
BOUNDED_ACTIVATION_OWNER_GO_CANONICAL_VALUE = BOUNDED_ACTIVATION_OWNER_GO_CANONICAL
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P13_TEXT_REWRITTEN_VALUE = P13_TEXT_REWRITTEN
P16_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE = P16_DOES_NOT_GRANT_EXECUTION_READINESS
P16_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = P16_DOES_NOT_AUTHORIZE_FLATTEN
P16_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = P16_DOES_NOT_SET_LIVE_AUTHORIZED
P16_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE = P16_DOES_NOT_ISSUE_RUNTIME_PERMIT
P16_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE = P16_DOES_NOT_AUTHORIZE_NETWORK_SESSION
GLOBAL_LIVE_AUTHORIZED_REQUIRED_VALUE = GLOBAL_LIVE_AUTHORIZED_REQUIRED
BOUNDED_ACTIVATION_NARROWER_THAN_GLOBAL_LIVE_VALUE = BOUNDED_ACTIVATION_NARROWER_THAN_GLOBAL_LIVE
PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN_VALUE = (
    PREREQUISITE_16_BOUNDED_RUNTIME_ACTIVATION_PROVEN
)
PREREQUISITE_16_NETWORK_SESSION_AUTHORIZED_VALUE = PREREQUISITE_16_NETWORK_SESSION_AUTHORIZED
PREREQUISITE_16_FLATTEN_EXECUTE_AUTHORIZED_VALUE = PREREQUISITE_16_FLATTEN_EXECUTE_AUTHORIZED
FAIL_CLOSED_IF_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE = (
    FAIL_CLOSED_IF_PREREQUISITE_16_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE
)
EARLIEST_UNRESOLVED_DEPENDENCY = "EXECUTION_PREREQUISITE_20_MUTATION_LIMITED_TO_PROVEN_POSITION"
NEXT_AUTHORITY_BOUNDARY = (
    "SEPARATE_OWNER_GO_FOR_EXECUTION_PREREQUISITE_20_MUTATION_LIMITED_TO_PROVEN_POSITION"
)
P16_RUNTIME_RESIDUAL = (
    "BOUNDED_RUNTIME_PERMIT_ISSUANCE_AND_NETWORK_SESSION_REMAIN_SEPARATE_OWNER_GO"
)
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
CENSUS_COMPLETE = True
LINEAGE_COMPLETE = True

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_p16_execution_prerequisite_16_bounded_activation_v1"
