"""S2: external capital decrease → productive capital admission runtime join. Not an owner."""

from __future__ import annotations

CAPABILITY_ID = "TREASURY_EXTERNAL_CAPITAL_DECREASE_S2_ADMISSION_RUNTIME_JOIN_V1"
PACKAGE_MARKER = "TREASURY_EXTERNAL_CAPITAL_DECREASE_S2_ADMISSION_RUNTIME_JOIN_V1=true"
OWNER = "ops.treasury_external_capital_decrease_s2_admission_runtime_join_v1"
SCHEMA_VERSION = "treasury_external_capital_decrease_s2_admission_runtime_join.v1"
CONTRACT_VERSION = "v1"

JOIN_SEAM_ID = "TREASURY_EXTERNAL_CAPITAL_DECREASE_S2_ADMISSION_RUNTIME_JOIN_V1"
UPSTREAM_S1_EDGE_SEAM_ID = "EXTERNAL_CAPITAL_DECREASE_TO_TREASURY_PHASE_2_VENUE_OBSERVATION_V1"
CAPITAL_ADMISSION_OWNER = "capital_admission_contract_v1"
PHASE_2_RECONCILIATION_JOIN_OWNER = "ops.treasury_phase_2_read_only_reconciliation_v1"

JOIN_CLASS = "TYPED_RUNTIME_JOIN_NOT_OWNER"
PARALLEL_CAPITAL_AUTHORITY_ADDED = False
SECOND_CAPITAL_AUTHORITY_ADDED = False

RUNTIME_AUTHORIZATION_EFFECT = "NONE"
NETWORK_EXECUTION_AUTHORIZED = False
TREASURY_MUTATION_AUTHORIZED = False
EXTERNAL_EFFECT_AUTHORIZED = False
AVAILABLE_FOR_SIZING_MINT_AUTHORIZED = False
DEPOSIT_E5_TOUCHED = False
DEPOSIT_INCREASE_SEMANTICS_ENABLED = False
