"""Standing constants for STEP-29P fresh venue GET evidence.

Reuses LiveCanaryHttpClientV1 GET mechanism only. Distinct User-Agent.
Not Full-Core. Not Cap-11.1 construction. Not wire send.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    DEFAULT_TD_MODE,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
)

CAPABILITY_ID = "FULL_CORE_STEP_29P_FRESH_VENUE_EVIDENCE_V1"
PACKAGE_MARKER = "FULL_CORE_STEP_29P_FRESH_VENUE_EVIDENCE_V1=true"
OWNER = "ops.full_core_step_29p_fresh_venue_evidence_v1"
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_FRESH_VENUE_EVIDENCE_AND_STEP_29P_"
    "RISK_ADMISSIBILITY_TO_PRE_CONSTRUCTION_BOUNDARY_V1"
)
THIS_SLICE = "11.2.1.Q.FULL_CORE_STEP_29P_RISK_ADMISSIBILITY_PRE_CONSTRUCTION"
EXPECTED_ORIGIN_MAIN_SHA = "5198c3988fd4d0c3390b999d0bb1d251b51838fa"
AUTHORIZED_HOST = "eea.okx.com"
REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_REST_BASE = f"https://{AUTHORIZED_HOST}"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
USER_AGENT_STEP_29P_FRESH_GET = "PeakTrade-FullCore-Step29P-FreshGET/1"
BOUND_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
BOUND_TD_MODE = DEFAULT_TD_MODE
BOUND_INST_TYPE = "FUTURES"
BOUND_SETTLEMENT_CURRENCY = "USDC"
BOUND_ACCOUNT_IDENTITY = REUSED_BINDING_ACCOUNT_SCOPE
EMPTY_DATA_IS_ZERO = False
TICKER_IS_NOT_29P_PRICE_AUTHORITY = True
AVAILEQ_IS_NOT_29P_EQUITY_AUTHORITY = True
METHOD_ALLOWLIST = ("GET",)
FORBIDDEN_HTTP_METHODS = ("POST", "PUT", "DELETE", "PATCH")
FORBIDDEN_ENDPOINTS = (
    "/api/v5/trade/order",
    "/api/v5/trade/cancel-order",
    "/api/v5/asset/withdrawal",
    "/api/v5/asset/transfer",
)
MAX_NETWORK_REQUEST_COUNT = 8
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 20
EVIDENCE_DIRNAME = "full_core_step_29p_fresh_venue_evidence_v1"
ENDPOINT_PUBLIC_TICKER = "/api/v5/market/ticker"
TICKER_CONSUMER = "MAX_AVAILABLE_QUERY_PX_ONLY_NOT_29P_PRICE_AUTHORITY"
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
POST_ALLOWED = False
ORDER_ALLOWED = False
WIRE_SEND_ALLOWED = False
PORT_CONSTRUCTION_ALLOWED = False
CANARY_EXECUTE_AUTHORIZED = False
CAP_11_1_CONSTRUCTION_POLICY_LIFT_AUTHORIZED = False
CAP_7_2_HOST_JOIN_TO_LIVE_EXECUTION_PORT_AUTHORIZED = False
