"""Constants for CAPABILITY_DYNAMIC_SCOPE_ARCHIVE_SIBLING_EXPORTER_V1.

AUTHORITY_EFFECT=NONE
TRADING_SEMANTIC_CHANGE=false
EXISTING_PERSISTENCE_FLOW_CHANGED=false
AUTOMATIC_CALLER_ADDED=false
"""

from __future__ import annotations

from src.ops.dynamic_scope_persistence_binding_v1.constants_v1 import (
    SCHEMA_VERSION,
    SCOPE_STATE_FILENAME,
    STATE_VERSION,
)

CAPABILITY_ID = "CAPABILITY_DYNAMIC_SCOPE_ARCHIVE_SIBLING_EXPORTER_V1"
PACKAGE_MARKER = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_EXPORTER_V1=true"
OWNER = "ops.dynamic_scope_archive_sibling_exporter_v1"
AUTHORITY_EFFECT = "NONE"

TARGET_FILENAME = SCOPE_STATE_FILENAME
TARGET_RELATIVE_PATH = f"readmodels/{TARGET_FILENAME}"
READMODELS_DIRNAME = "readmodels"

SOURCE_SCHEMA = SCHEMA_VERSION
SOURCE_STATE_VERSION = STATE_VERSION

ERROR_SOURCE_MISSING = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_SOURCE_MISSING"
ERROR_SOURCE_CORRUPT = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_SOURCE_CORRUPT"
ERROR_SOURCE_SCHEMA_MISMATCH = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_SOURCE_SCHEMA_MISMATCH"
ERROR_SOURCE_STATE_VERSION_MISMATCH = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_SOURCE_STATE_VERSION_MISMATCH"
ERROR_SOURCE_LOAD_FAILED = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_SOURCE_LOAD_FAILED"
ERROR_IDENTICAL_PATHS = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_IDENTICAL_SOURCE_TARGET"
ERROR_WRITE_FAILED = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_WRITE_FAILED"
ERROR_DIGEST_MISMATCH = "DYNAMIC_SCOPE_ARCHIVE_SIBLING_DIGEST_MISMATCH"
