"""Fail-closed reason codes for Cap 6.1 confirmation binding."""

from __future__ import annotations

from enum import Enum


class ConfirmationBindingFailureCodeV1(str, Enum):
    CONFLICTING_WRITER = "CONFLICTING_WRITER"
    WRITER_LOCK_NOT_HELD = "WRITER_LOCK_NOT_HELD"
    CHECKPOINT_MISSING_BEFORE_FIRST_STATE = "CHECKPOINT_MISSING_BEFORE_FIRST_STATE"
    CHECKPOINT_MISSING_AFTER_PRIOR_COMMIT = "CHECKPOINT_MISSING_AFTER_PRIOR_COMMIT"
    CORRUPTED_CHECKPOINT = "CORRUPTED_CHECKPOINT"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    STATE_VERSION_MISMATCH = "STATE_VERSION_MISMATCH"
    INSTRUMENT_ISOLATION_VIOLATION = "INSTRUMENT_ISOLATION_VIOLATION"
    SILENT_REINITIALIZATION_BLOCKED = "SILENT_REINITIALIZATION_BLOCKED"
    SESSION_ID_UNSTABLE = "SESSION_ID_UNSTABLE"
    PERSISTENCE_INTERRUPTION = "PERSISTENCE_INTERRUPTION"
    MANIFEST_VERIFY_FAILED = "MANIFEST_VERIFY_FAILED"
    COMMIT_MARKER_MISSING = "COMMIT_MARKER_MISSING"
    INVALID_OBSERVATION_CYCLE = "INVALID_OBSERVATION_CYCLE"
    CORE_LOGIC_DRIFT = "CORE_LOGIC_DRIFT"
    PARITY_FAILURE = "PARITY_FAILURE"
