"""Standing safety pins — orchestrator has no trading authority."""

from __future__ import annotations

ORCHESTRATOR_TRADING_AUTHORITY = "NONE"
ORCHESTRATOR_SELECTION_AUTHORITY = "NONE"
ORCHESTRATOR_DECISION_AUTHORITY = "NONE"
ORCHESTRATOR_RISK_AUTHORITY = "NONE"
ORCHESTRATOR_PROMOTION_AUTHORITY = "NONE"

ALLOWED_AUTHORITY = (
    "BOUNDED_LIFECYCLE_COORDINATION",
    "RUN_LIMIT_ENFORCEMENT",
    "EXISTING_GATE_INVOCATION",
    "EVIDENCE_COLLECTION",
    "FAIL_CLOSED_STOP",
)

LIVE_ENABLED = False
LIVE_ARMED = False
POST_ALLOWED = False
REAL_VENUE_POST_ALLOWED = False
REAL_KEYCHAIN_ACCESS_AUTHORIZED = False
TESTNET_AUTHORIZED = False
EXTERNAL_EFFECT_AUTHORIZED = False

DEFAULT_CONTRACT_RUN_ID = "PAPER_SHADOW_RUN_001"
