"""Machine-readable failure and exclusion reason codes for Capability 2.2."""

from __future__ import annotations

from enum import Enum


class RankingFailureCodeV1(str, Enum):
    UNIVERSE_SNAPSHOT_MISSING = "UNIVERSE_SNAPSHOT_MISSING"
    UNIVERSE_SNAPSHOT_INVALID = "UNIVERSE_SNAPSHOT_INVALID"
    UNIVERSE_SNAPSHOT_STALE = "UNIVERSE_SNAPSHOT_STALE"
    UNIVERSE_DIGEST_MISMATCH = "UNIVERSE_DIGEST_MISMATCH"
    UNIVERSE_SCHEMA_MISMATCH = "UNIVERSE_SCHEMA_MISMATCH"
    UNIVERSE_CAPABILITY_MISMATCH = "UNIVERSE_CAPABILITY_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    MISSING_REQUIRED_METADATA = "MISSING_REQUIRED_METADATA"
    MARK_PRICE_UNSUPPORTED = "MARK_PRICE_UNSUPPORTED"
    MARKET_DATA_UNSUPPORTED = "MARKET_DATA_UNSUPPORTED"
    INVALID_INSTRUMENT_METADATA = "INVALID_INSTRUMENT_METADATA"
    DATA_QUALITY_FAIL = "DATA_QUALITY_FAIL"
    UNIVERSE_ELIGIBILITY_FALSE = "UNIVERSE_ELIGIBILITY_FALSE"
    INACTIVE_OR_SUSPENDED = "INACTIVE_OR_SUSPENDED"
    NO_ELIGIBLE_CANDIDATES = "NO_ELIGIBLE_CANDIDATES"
    PERSISTENCE_WRITE_FAILURE = "PERSISTENCE_WRITE_FAILURE"
    PARTIAL_WRITE = "PARTIAL_WRITE"
    CORRUPT_PERSISTED_SNAPSHOT = "CORRUPT_PERSISTED_SNAPSHOT"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    DUPLICATE_PRODUCER_WRITER = "DUPLICATE_PRODUCER_WRITER"
    SNAPSHOT_ID_CONTENT_CONFLICT = "SNAPSHOT_ID_CONTENT_CONFLICT"
    DASHBOARD_INPUT_FORBIDDEN = "DASHBOARD_INPUT_FORBIDDEN"
    LEGACY_RANKER_INPUT_FORBIDDEN = "LEGACY_RANKER_INPUT_FORBIDDEN"
    INTEGRITY_FAILURE = "INTEGRITY_FAILURE"
    MISSING_UNIVERSE_EVENT_TIME = "MISSING_UNIVERSE_EVENT_TIME"
    MISSING_UNIVERSE_SNAPSHOT_ID = "MISSING_UNIVERSE_SNAPSHOT_ID"
    MISSING_UNIVERSE_SOURCE_DIGEST = "MISSING_UNIVERSE_SOURCE_DIGEST"
    VENUE_NOT_OKX_EEA = "VENUE_NOT_OKX_EEA"
    FORBIDDEN_INSTRUMENT_REINTRODUCTION = "FORBIDDEN_INSTRUMENT_REINTRODUCTION"


ALL_FAILURE_CODES: frozenset[str] = frozenset(code.value for code in RankingFailureCodeV1)
