"""Constants for CURRENT MF N=5 recovered topology consumer join V1."""

from __future__ import annotations

from src.ops.current_mf_n5_durable_lane_assignment_persistence_v1.constants_v1 import (
    FIVE_LANE_CONTINUOUS_HOST_JOIN as PERSISTENCE_FIVE_LANE_CONTINUOUS_HOST_JOIN,
    OWNER as PERSISTENCE_OWNER_VALUE,
)
from src.ops.current_mf_n5_isolated_lane_instance_topology_v1.constants_v1 import (
    CROSS_UNIVERSE_CANDIDATE_BORROWING as TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK as TOPOLOGY_CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN as TOPOLOGY_CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT as TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING as TOPOLOGY_CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION as TOPOLOGY_CROSS_UNIVERSE_SELECTION,
    FIVE_LANE_RUNTIME_CREATED as TOPOLOGY_FIVE_LANE_RUNTIME_CREATED,
    INSTRUMENT_ID_ALONE_SUFFICIENT as TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT,
    LANE_MAPPING_OWNER as TOPOLOGY_LANE_MAPPING_OWNER,
    MAX_POSITIONS_EFFECTIVE as TOPOLOGY_MAX_POSITIONS_EFFECTIVE,
    MF_PRODUCTIVE_JOIN as TOPOLOGY_MF_PRODUCTIVE_JOIN,
    MULTI_UNIVERSE_MERGE as TOPOLOGY_MULTI_UNIVERSE_MERGE,
)
from src.ops.single_selected_future_policy_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP23_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED,
)

OWNER = "ops.current_mf_n5_recovered_topology_consumer_join_v1"
CONTRACT_ID = "CURRENT_MF_N5_RECOVERED_TOPOLOGY_CONSUMER_JOIN_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_n5_recovered_topology_consumer_join.v1"

LANE_MAPPING_OWNER = TOPOLOGY_LANE_MAPPING_OWNER
PERSISTENCE_OWNER = PERSISTENCE_OWNER_VALUE

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
CONSUMER_RANKING_AUTHORITY = False
CONSUMER_MEMBERSHIP_AUTHORITY = False
CONSUMER_MAPPING_AUTHORITY = False
CONSUMER_PERSISTENCE_AUTHORITY = False
CONSUMER_CAP23_SELECTION_AUTHORITY = False
CONSUMER_CAP24_BINDING_AUTHORITY = False
CONSUMER_TRADING_AUTHORITY = False
CONSUMER_EXECUTION_AUTHORITY = False

CROSS_UNIVERSE_SELECTION = TOPOLOGY_CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = TOPOLOGY_CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = TOPOLOGY_CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = TOPOLOGY_CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = TOPOLOGY_MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT
UNIVERSE_ISOLATION = "HARD"
UNIVERSE_ISOLATION_ENFORCED = True

MF_PRODUCTIVE_JOIN = TOPOLOGY_MF_PRODUCTIVE_JOIN
FIVE_LANE_RUNTIME_CREATED = TOPOLOGY_FIVE_LANE_RUNTIME_CREATED
FIVE_LANE_CONTINUOUS_HOST_JOIN = PERSISTENCE_FIVE_LANE_CONTINUOUS_HOST_JOIN
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = False
MF_SINGLE_EGRESS_REWIRED = False
MAX_POSITIONS_EFFECTIVE = int(TOPOLOGY_MAX_POSITIONS_EFFECTIVE)
MULTI_FUTURE_RUNTIME_AUTHORIZED = bool(CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED)
assert MAX_POSITIONS_EFFECTIVE == int(CAP23_MAX_POSITIONS_EFFECTIVE) == 1
assert MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert MF_PRODUCTIVE_JOIN is False
assert FIVE_LANE_RUNTIME_CREATED is False
assert FIVE_LANE_CONTINUOUS_HOST_JOIN is False

CAP23_CHANGE_REQUIRED = False
CAP24_CHANGE_REQUIRED = False
MASTER_V2_CHANGE_REQUIRED = False
DOUBLE_PLAY_CHANGE_REQUIRED = False

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "build_occupied_lane_pins_v1",
        "produce_single_selected_future_v1",
        "run_single_selected_future_policy_v1",
        "persist_selection_bundle_atomic_v1",
        "_pick_top_eligible",
        "mf_canonical_single_egress_authority_handoff_contract_v1",
        "master_v2",
        "double_play",
        "execution",
        "top_n_active_set",
    }
)
