"""Constants for Surface-B regime-coverage + dashboard input-gap closeout v1.

CAMPAIGN_START=false
INPUT_AUTHORITY_FLIP=false
RUNTIME_IMPLEMENTED_FLIP=false
DASHBOARD_LOGIC_CHANGE=false
DASHBOARD_AUTHORITY_EFFECT=NONE
TRADING_LOGIC_CHANGE=false
ORDERS_TESTNET_LIVE=false
REGIME_COVERAGE_PRODUCER_AVAILABLE=false
REGIME_COVERAGE_STATUS=SEMANTICALLY_UNRESOLVED
"""

from __future__ import annotations

CAPABILITY_ID = (
    "CAPABILITY_PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_"
    "REGIME_COVERAGE_AND_DASHBOARD_INPUT_GAP_CLOSEOUT_V1"
)
CAPABILITY_SCOPE = "SURFACE_B_REGIME_COVERAGE_AND_DASHBOARD_INPUT_GAP_CLOSEOUT"
PACKAGE_MARKER = (
    "PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_"
    "REGIME_COVERAGE_AND_DASHBOARD_INPUT_GAP_CLOSEOUT_V1=true"
)
OWNER = (
    "ops.productive_pure_stack_stage2_surface_b_regime_coverage_and_dashboard_input_gap_closeout_v1"
)
SCHEMA_VERSION = (
    "productive_pure_stack_stage2_surface_b_regime_coverage_and_dashboard_input_gap_closeout/v1"
)
DOCUMENT_TYPE = "SURFACE_B_REGIME_COVERAGE_AND_DASHBOARD_INPUT_GAP_CLOSEOUT_EXECUTION_MANIFEST"
STATUS = (
    "OWNER_STA_SURFACE_B_REGIME_COVERAGE_EXECUTED_PACK_INPUT_GAP_CLOSED_"
    "DASHBOARD_PRESENTATION_GAP_UNCHANGED"
)

NEXT_STEP_ID = "EXECUTE_SURFACE_B_REGIME_COVERAGE_AND_CLOSE_DASHBOARD_INPUT_GAP_V1"
OWNER_GO_BASE_SHA = "13d9a12ed45cdf82ed93c38154a425a9fd8ca752"
OBSERVATION_PACK_DIGEST = "268b2e67b350bfa0cf2310a75b1d2710a45dca277b182205dfe12692131a0676"
PRODUCER_DIGEST = "952b7b63c369dccfc01d5ee2802473c12911da18b1df57be8a91ba566ffe9d57"
PARTITION_ID = "surface_b_regime_coverage_structural_partition_v1"
VERSIONED_PRODUCER_ID = "productive_pure_stack_stage2_surface_b_regime_coverage_producer/v1"
INSTRUMENT_ID = "inst-eth-usdt-perp"
AS_OF_EVENT_TIME_EPOCH_S = 1_785_934_680
BAR_COUNT = 299
OBSERVATION_COUNT = 299

REGIME_COVERAGE_COUNTS: dict[str, int] = {"missing": 299, "unknown": 0}

USE_CANONICAL_MERGED_PACK = True
EXECUTE_REGIME_COVERAGE_PRODUCER = True
REQUIRE_REGIME_COVERAGE_COUNTS = True
REQUIRE_REGIME_COVERAGE_INSTANCE = True
REQUIRE_CANONICAL_BINDING = True
REQUIRE_MISSING_SOURCE_DELTA_REPORT = True
REQUIRE_TOPIC_CLOSEOUT_VERDICT = True
CAMPAIGN_ID_REQUIRED = False
CAMPAIGN_START = False
INPUT_AUTHORITY_FLIP = False
RUNTIME_IMPLEMENTED_FLIP = False
DASHBOARD_LOGIC_CHANGE = False
DASHBOARD_AUTHORITY_EFFECT = "NONE"
TRADING_LOGIC_CHANGE = False
ORDERS_TESTNET_LIVE = False
FAIL_CLOSED = True

INPUT_AUTHORITY = False
RUNTIME_IMPLEMENTED = False
REGIME_COVERAGE_PRODUCER_AVAILABLE = False
REGIME_COVERAGE_STATUS = "SEMANTICALLY_UNRESOLVED"
PRODUCTIVE_EMISSION = False

OVERALL_TOPIC_CLOSEOUT_VERDICT = (
    "SURFACE_B_REGIME_COVERAGE_INPUT_GAP_CLOSED_DASHBOARD_PRESENTATION_GAP_UNCHANGED"
)

OWNER_DECISION_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_"
    "REGIME_COVERAGE_AND_DASHBOARD_INPUT_GAP_CLOSEOUT_V1.md"
)
DECISIONS_MANIFEST_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_"
    "REGIME_COVERAGE_AND_DASHBOARD_INPUT_GAP_CLOSEOUT_DECISIONS_V1.json"
)
SCHEMA_REL = (
    "docs/ops/schemas/productive_pure_stack_stage2_surface_b_"
    "regime_coverage_and_dashboard_input_gap_closeout_v1.schema.json"
)
CYBERSECURITY_MIRROR_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_"
    "REGIME_COVERAGE_AND_DASHBOARD_INPUT_GAP_CLOSEOUT_CYBERSECURITY_MIRROR_V1.md"
)
ARTIFACTS_REL = (
    "docs/ops/artifacts/productive_pure_stack_stage2_surface_b_"
    "regime_coverage_and_dashboard_input_gap_closeout_v1/"
)
OBSERVATION_PACK_REL = (
    "docs/ops/artifacts/productive_pure_stack_stage2_surface_b_owner_sta_"
    "raw_input_pack_materialization_v1/observation_pack.json"
)
INVENTORY_REL = (
    "docs/ops/market_dashboard/market_dashboard_missing_source_not_bound_inventory_v1/"
    "INVENTORY.json"
)
TRIAD_MANIFEST_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "CANDLE_MARK_INSTRUMENT_AUTHORITY_DECISIONS_V1.json"
)
PARENT_MATERIALIZATION_DECISION_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "RAW_INPUT_PACK_MATERIALIZATION_DECISION_V1.md"
)
PARENT_REGIME_COVERAGE_PRODUCER_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_REGIME_COVERAGE_PRODUCER_V1.md"
)
PARENT_STA_OPEN_INPUTS_CLOSEOUT_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "REGIME_COVERAGE_STA_OPEN_INPUTS_CLOSEOUT_V1.md"
)

EXECUTION_PROOF_REL = ARTIFACTS_REL + "regime_coverage_execution_proof.json"
COUNTS_ARTIFACT_REL = ARTIFACTS_REL + "regime_coverage_counts.json"
INSTANCE_ARTIFACT_REL = ARTIFACTS_REL + "regime_coverage_instance.json"
DELTA_REPORT_REL = ARTIFACTS_REL + "missing_source_delta_report.json"
TOPIC_CLOSEOUT_REL = ARTIFACTS_REL + "topic_closeout_verdict.json"
PRODUCER_DIGEST_TXT_REL = ARTIFACTS_REL + "producer_digest.txt"
OBSERVATION_PACK_DIGEST_TXT_REL = ARTIFACTS_REL + "observation_pack_digest.txt"

THRESHOLD_AUTHORITY_REF = "OWNER_NUMERIC_THRESHOLD_AUTHORITY_UNSET_V1"
LOOKBACK_WINDOW_AUTHORITY_REF = "OWNER_NUMERIC_LOOKBACK_AUTHORITY_UNSET_V1"

CANDLE_JOIN_REF = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "CANDLE_MARK_INSTRUMENT_AUTHORITY_DECISION_V1.md#candle_source_authority"
)
MARK_JOIN_REF = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_OWNER_STA_"
    "CANDLE_MARK_INSTRUMENT_AUTHORITY_DECISION_V1.md#mark_source_authority"
)
RAW_PT1M_PACK_REF = (
    "docs/ops/PRODUCTIVE_PURE_STACK_STAGE2_SURFACE_B_RAW_PT1M_INPUT_PACK_OWNER_DECISION_V1.md"
)

INVENTORY_BEFORE_AFTER: dict[str, object] = {
    "TOTAL_MISSING_SOURCE_COUNT": 50,
    "TOTAL_NOT_BOUND_COUNT": 18,
    "regime_bull_bear_switch_affected_presentation_element_count": 5,
    "regime_bull_bear_switch_family_status": "BLOCKED",
}
