"""Constants for WALLCLOCK_FULL_CANONICAL_DECISION_TO_SIMULATED_ECONOMICS_RUNTIME_BRIDGE_V1."""

from __future__ import annotations

CAPABILITY_ID = "WALLCLOCK_FULL_CANONICAL_DECISION_TO_SIMULATED_ECONOMICS_RUNTIME_BRIDGE_V1"
PACKAGE_MARKER = "WALLCLOCK_FULL_CANONICAL_DECISION_TO_SIMULATED_ECONOMICS_RUNTIME_BRIDGE_V1=true"
SCHEMA_VERSION = "v1"
PRODUCER_FAMILY = "ops.wallclock_full_canonical_decision_to_simulated_economics_runtime_bridge_v1"
OWNER = PRODUCER_FAMILY

# Fulfills closeout next-capability obligation under the GO-ratified name.
CLOSES_NEXT_CAPABILITY_ALIAS = (
    "INTEGRATED_PAPER_SHADOW_STRATEGY_INTENT_AND_PORTFOLIO_ECONOMICS_EVIDENCE_V1"
)

AUTHORITY_EFFECT_NONE = "NONE"
RUNTIME_EFFECT_NONE = "NONE"
ORDER_EFFECT_NONE = "NONE"
ACTIVATION_EFFECT_NONE = "NONE"
ECONOMIC_GATE_EFFECT_NONE = "NONE"

EXECUTION_CLASS_ANALYTICAL = "ANALYTICAL_SIMULATION_NOT_PAPER_EXECUTION"
DECISION_AUTHORITY_OWNER = (
    "trading.master_v2.integrated_offline_trading_logic_replay_v1."
    "run_integrated_offline_trading_logic_replay_v1"
)
PORTFOLIO_MODEL_OWNER = (
    "ops.integrated_paper_shadow_observation_session_v1.portfolio_economics_model_v1"
)

MIN_PRICE_PATH_LEN = 2
FEATURE_WINDOW_MIN = 3
PRICE_PATH_MAX_LEN = 64

ORDERS_AUTHORIZED = False
TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False
PAPER_EXECUTION_AUTHORIZED = False
CREDENTIALS_AUTHORIZED = False
AUTO_PROMOTION_AUTHORIZED = False
ECONOMIC_VALIDITY_PASS = False
PROMOTION_PASS = False
RUNTIME_BRIDGE_LIVE_ACTIVATED = False  # live order runtime remains BOUND_NOT_ACTIVATED
SECOND_DECISION_AUTHORITY_FORBIDDEN = True
