"""Standing constants for PL-TF-002 productive read-only GET completion WP.

Network capture requires explicit Owner-GO; standing pins remain false.
"""

from __future__ import annotations

from src.ops.pl_tf_002_network_evidence_contract_v1.constants_v1 import (
    DEFAULT_FRESHNESS_MAX_AGE_MS,
    NE_TF_001_ENDPOINT_PATH,
    NE_TF_001_HTTP_METHOD,
    NE_TF_001_TASK_ID,
    PL_TF_002_STATUS_CLOSED,
    PRODUCTIVE_TRANSPORT_CLASSES,
)
from src.ops.pl_tf_002_productive_read_only_session_executor_v1.constants_v1 import (
    AUTHORIZED_HOST,
    OWNER_GO as SESSION_EXECUTOR_OWNER_GO,
    TRANSPORT_CLASS,
)

CAPABILITY_ID = "PL_TF_002_PRODUCTIVE_READ_ONLY_GET_COMPLETE_V1"
PACKAGE_MARKER = "PL_TF_002_PRODUCTIVE_READ_ONLY_GET_COMPLETE_V1=true"
OWNER = "ops.pl_tf_002_productive_read_only_get_complete_v1"
SCHEMA_VERSION = "pl_tf_002_productive_read_only_get_complete.v1"
CONTRACT_VERSION = "v1"
JOIN_SEAM_ID = "PL_TF_002_PRODUCTIVE_READ_ONLY_GET_COMPLETE_V1"

WP_ID = "PL_TF_002_PRODUCTIVE_READ_ONLY_GET_COMPLETE_V1"
OWNER_GO = "OWNER_GO_PL_TF_002_PRODUCTIVE_READ_ONLY_GET_COMPLETE_V1"
SESSION_OWNER_GO = SESSION_EXECUTOR_OWNER_GO

RUNTIME_AUTHORIZATION_EFFECT = "NONE"
NETWORK_EXECUTION_AUTHORIZED = False
CREDENTIAL_LOAD_AUTHORIZED = False
EXTERNAL_EFFECT_AUTHORIZED = False
TREASURY_MUTATION_AUTHORIZED = False
STEP_29P_AUTHORITY_CHANGED = False
K1_AUTHORITY_CHANGED = False
TRADING_AUTHORITY_CHANGED = False

EVIDENCE_DIRNAME = "pl_tf_002_productive_read_only_get_complete_v1"
EVIDENCE_RELROOT = f"evidence/ops/{EVIDENCE_DIRNAME}"

FRESH_PRETRADE_VENUE_INST_ID = "ETH-USDT-SWAP"
FRESH_PRETRADE_TD_MODE = "cross"
FRESH_PRETRADE_INST_TYPE = "SWAP"

NE_TF_001 = NE_TF_001_TASK_ID
F2_ENDPOINT_PATH = NE_TF_001_ENDPOINT_PATH
F2_HTTP_METHOD = NE_TF_001_HTTP_METHOD

CLOSURE_STATUS = PL_TF_002_STATUS_CLOSED
PRODUCTIVE_TRANSPORT_CLASS = TRANSPORT_CLASS
ALLOWED_TRANSPORT_CLASSES = PRODUCTIVE_TRANSPORT_CLASSES
AUTHORIZED_NETWORK_HOST = AUTHORIZED_HOST
FRESHNESS_MAX_AGE_MS = DEFAULT_FRESHNESS_MAX_AGE_MS

MAX_NETWORK_REQUEST_COUNT = 16
