"""Machine-readable failure and exclusion reason codes for Capability 2.1."""

from __future__ import annotations

from enum import Enum


class UniverseFailureCodeV1(str, Enum):
    OKX_SOURCE_UNAVAILABLE = "OKX_SOURCE_UNAVAILABLE"
    MALFORMED_SOURCE_PAYLOAD = "MALFORMED_SOURCE_PAYLOAD"
    MISSING_NATIVE_INST_ID = "MISSING_NATIVE_INST_ID"
    UNSUPPORTED_INSTRUMENT_TYPE = "UNSUPPORTED_INSTRUMENT_TYPE"
    SPOT_INSTRUMENT = "SPOT_INSTRUMENT"
    BTC_INSTRUMENT = "BTC_INSTRUMENT"
    MISSING_TICK_SIZE = "MISSING_TICK_SIZE"
    INVALID_TICK_SIZE = "INVALID_TICK_SIZE"
    MISSING_LOT_SIZE = "MISSING_LOT_SIZE"
    INVALID_LOT_SIZE = "INVALID_LOT_SIZE"
    MISSING_MINIMUM_ORDER_SIZE = "MISSING_MINIMUM_ORDER_SIZE"
    INVALID_MINIMUM_ORDER_SIZE = "INVALID_MINIMUM_ORDER_SIZE"
    MISSING_CONTRACT_VALUE = "MISSING_CONTRACT_VALUE"
    INVALID_CONTRACT_VALUE = "INVALID_CONTRACT_VALUE"
    MISSING_CONTRACT_VALUE_CURRENCY = "MISSING_CONTRACT_VALUE_CURRENCY"
    MISSING_BASE_CURRENCY = "MISSING_BASE_CURRENCY"
    MISSING_QUOTE_CURRENCY = "MISSING_QUOTE_CURRENCY"
    MISSING_SETTLEMENT_CURRENCY = "MISSING_SETTLEMENT_CURRENCY"
    UNSUPPORTED_CONTRACT_TYPE = "UNSUPPORTED_CONTRACT_TYPE"
    UNKNOWN_TRADING_STATUS = "UNKNOWN_TRADING_STATUS"
    INACTIVE_OR_SUSPENDED = "INACTIVE_OR_SUSPENDED"
    MARK_PRICE_UNSUPPORTED = "MARK_PRICE_UNSUPPORTED"
    MARKET_DATA_UNSUPPORTED = "MARKET_DATA_UNSUPPORTED"
    STALE_SOURCE_EVENT_TIME = "STALE_SOURCE_EVENT_TIME"
    MISSING_SOURCE_EVENT_TIME = "MISSING_SOURCE_EVENT_TIME"
    MISSING_EXPIRY_FOR_DATED_FUTURE = "MISSING_EXPIRY_FOR_DATED_FUTURE"
    INVALID_EXPIRY_FOR_DATED_FUTURE = "INVALID_EXPIRY_FOR_DATED_FUTURE"
    CANONICALIZATION_FAILED = "CANONICALIZATION_FAILED"
    DUPLICATE_INSTRUMENT = "DUPLICATE_INSTRUMENT"
    CONFLICTING_NATIVE_IDS = "CONFLICTING_NATIVE_IDS"
    CONFLICTING_CANONICAL_IDS = "CONFLICTING_CANONICAL_IDS"
    EMPTY_ELIGIBLE_UNIVERSE = "EMPTY_ELIGIBLE_UNIVERSE"
    PERSISTENCE_WRITE_FAILURE = "PERSISTENCE_WRITE_FAILURE"
    PARTIAL_WRITE = "PARTIAL_WRITE"
    CORRUPT_PERSISTED_SNAPSHOT = "CORRUPT_PERSISTED_SNAPSHOT"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    DUPLICATE_PRODUCER_WRITER = "DUPLICATE_PRODUCER_WRITER"
    VENUE_NOT_OKX_EEA = "VENUE_NOT_OKX_EEA"
    MISSING_REQUIRED_METADATA = "MISSING_REQUIRED_METADATA"
    DASHBOARD_INPUT_FORBIDDEN = "DASHBOARD_INPUT_FORBIDDEN"


ALL_FAILURE_CODES: frozenset[str] = frozenset(code.value for code in UniverseFailureCodeV1)
