"""Standing constants for §11.13.5.Z2DP fresh create-readiness GET evidence.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1, and
build_okx_live_canary_auth_headers_v1. Does not mint a second HTTP client,
signer, SecretRef owner, live/testnet/canary authority, or mutation path.
Does not reuse consumed Z2DO/Z2DL Owner-GOs as execute tokens.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    DEFAULT_ORDER_TYPE,
    DEFAULT_TD_MODE,
    ENDPOINT_ACCOUNT_BALANCE,
    ENDPOINT_ACCOUNT_CONFIG,
    ENDPOINT_ACCOUNT_LEVERAGE_INFO,
    ENDPOINT_ACCOUNT_MAX_SIZE,
    ENDPOINT_ACCOUNT_POSITIONS,
    ENDPOINT_ASSET_BALANCES,
    ENDPOINT_ORDERS_ALGO_PENDING,
    ENDPOINT_PUBLIC_PRICE_LIMIT,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    POSITION_COUNT_LIMIT,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)
from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_submit_composition_constants_v1 import (
    CREATE_PATH_ARCHITECTURALLY_COMPLETE,
    CREATE_PATH_CURRENTLY_AUTHORIZED,
    CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE,
    CURRENT_PRODUCTIVE_WIRE_REACHABLE,
    POSITION_MODE_FAIL_CLOSED as ROUTE_C_POSITION_MODE_FAIL_CLOSED,
    POSITION_MODE_SUBMIT_BODY_SEMANTICS as ROUTE_C_POSITION_MODE_SUBMIT_BODY_SEMANTICS,
    PREREQUISITE_08_CLOSED as ROUTE_C_PREREQUISITE_08_CLOSED,
)

CAPABILITY_ID = "Z2DP_POST_Z2DO_FRESH_CREATE_READINESS_EVIDENCE_V1"
PACKAGE_MARKER = "Z2DP_POST_Z2DO_FRESH_CREATE_READINESS_EVIDENCE_V1=true"
OWNER = "ops.section_11_13_5_z2dp_post_z2do_fresh_create_readiness_evidence_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "z2dp_post_z2do_fresh_create_readiness_evidence.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_POST_Z2DO_FRESH_CREATE_READINESS_EVIDENCE_V1"
WORKPACKAGE_ID = "POST_Z2DO_FRESH_CREATE_READINESS_EVIDENCE_V1"
THIS_SLICE = "11.13.5.Z2DP"
PREDECESSOR_SLICE = "11.13.5.Z2DO"
CURRENT_CANONICAL_SECTION = "11.13.5.Z2DP"
EXPECTED_ORIGIN_MAIN_SHA = "6aa4a81fd75380ff10aeb0c031020fc3e32aa87b"
AUTHORIZED_HOST = "eea.okx.com"

AUTHORIZED_OPERATION = "BOUNDED_READ_ONLY_FRESH_CREATE_READINESS_GET_PACKAGE"
MAX_NETWORK_REQUEST_COUNT = 15
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
TRANSFER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
FUNDING_GET_REQUIRED = False
FUNDING_GET_AUTHORIZED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET_PACKAGE = False

TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
TARGET_TD_MODE = DEFAULT_TD_MODE
TARGET_ORDER_TYPE = DEFAULT_ORDER_TYPE
MAX_POSITIONS_EFFECTIVE = POSITION_COUNT_LIMIT
BOUND_ACCOUNT_SCOPE = REUSED_BINDING_ACCOUNT_SCOPE

ENDPOINT_PUBLIC_INSTRUMENTS = "/api/v5/public/instruments"
ENDPOINT_PUBLIC_TICKER = "/api/v5/market/ticker"
ENDPOINT_ORDERS_PENDING = "/api/v5/trade/orders-pending"

FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
    "/api/v5/trade/cancel-order",
    "/api/v5/trade/close-position",
    "/api/v5/account/set-position-mode",
    "/api/v5/account/set-leverage",
)
FORBIDDEN_HTTP_METHODS: tuple[str, ...] = (
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "HEAD",
    "OPTIONS",
    "TRACE",
    "CONNECT",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

ROUTE_C_POSITION_MODE_SUBMIT_BODY_SEMANTICS_STANDING = ROUTE_C_POSITION_MODE_SUBMIT_BODY_SEMANTICS
ROUTE_C_POSITION_MODE_FAIL_CLOSED_STANDING = ROUTE_C_POSITION_MODE_FAIL_CLOSED
CREATE_PATH_ARCHITECTURALLY_COMPLETE_STANDING = CREATE_PATH_ARCHITECTURALLY_COMPLETE
CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE_STANDING = CREATE_PATH_PRODUCTIVE_WIRE_CAPABLE
CURRENT_PRODUCTIVE_WIRE_REACHABLE_STANDING = CURRENT_PRODUCTIVE_WIRE_REACHABLE
CREATE_PATH_CURRENTLY_AUTHORIZED_STANDING = CREATE_PATH_CURRENTLY_AUTHORIZED
ROUTE_C_PREREQUISITE_08_CLOSED_STANDING = ROUTE_C_PREREQUISITE_08_CLOSED

EVIDENCE_DIRNAME = "section_11_13_5_z2dp_post_z2do_fresh_create_readiness_evidence_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)

ACCOUNT_CONFIG_PERSIST_FIELDS: tuple[str, ...] = (
    "uid",
    "mainUid",
    "acctLv",
    "posMode",
    "perm",
    "settleCcy",
    "label",
    "level",
    "kycLv",
)
ACCOUNT_CONFIG_REDACT_FIELDS: frozenset[str] = frozenset({"ip"})

FRESHNESS_SENDTIME_REFRESH_REQUIRED = "PROVEN_CURRENT_BUT_SENDTIME_REFRESH_REQUIRED"
FRESHNESS_SENDTIME_REUSABLE = "PROVEN_CURRENT_AND_SENDTIME_REUSABLE"
FRESHNESS_UNPROVEN = "UNPROVEN"
FRESHNESS_NOT_APPLICABLE = "NOT_APPLICABLE"

POSITION_MODE_SEMANTICS_UNPROVEN = "UNPROVEN"
POSITION_MODE_SEMANTICS_OMIT = "PROVEN_OMIT_POSSIDE"
POSITION_MODE_SEMANTICS_EMIT_NET = "PROVEN_EMIT_POSSIDE_NET"
POSITION_MODE_SEMANTICS_OTHER = "PROVEN_OTHER_CANONICAL_VALUE"

CREATE_READINESS_READY = "READY_FOR_SEPARATE_RISK_BEARING_OWNER_GO"
CREATE_READINESS_BLOCKED_POSITION_MODE = "BLOCKED_BY_POSITION_MODE_SEMANTICS"
CREATE_READINESS_BLOCKED_FUNDING = "BLOCKED_BY_FUNDING_OR_CAPACITY"
CREATE_READINESS_BLOCKED_EXPOSURE = "BLOCKED_BY_EXISTING_EXPOSURE"
CREATE_READINESS_BLOCKED_IDENTITY = "BLOCKED_BY_ACCOUNT_IDENTITY"
CREATE_READINESS_BLOCKED_PRETRADE = "BLOCKED_BY_OTHER_PRETRADE_GATE"
CREATE_READINESS_BLOCKED_MULTIPLE = "BLOCKED_BY_MULTIPLE_GAPS"
CREATE_READINESS_NOT_DETERMINABLE = "NOT_DETERMINABLE"

VENUE_CAPACITY_POSITIVE = "PROVEN_POSITIVE"
VENUE_CAPACITY_ZERO = "PROVEN_ZERO"
VENUE_CAPACITY_UNPROVEN = "UNPROVEN"

QTY_POTENTIALLY_ADMISSIBLE = "POTENTIALLY_ADMISSIBLE_SUBJECT_TO_29P"
QTY_BLOCKED_CAPACITY = "BLOCKED_BY_VENUE_CAPACITY"
QTY_BLOCKED_FUNDING = "BLOCKED_BY_FUNDING"
QTY_UNPROVEN = "UNPROVEN"

FUNDING_GET_NOT_REQUIRED_REASON = (
    "CREATE_READINESS_USES_TRADING_ACCOUNT_DETAILS_AVAILEQ_NOT_ASSET_BALANCES"
)
