"""Standing constants for the P08 post-read-only-exhaustion authority boundary.

Offline forensic adjudication only. Does not mint live, testnet, canary,
submit, flatten, funding, or Core trading authority. Does not close P08.
Does not repeat equivalent unfiltered positions empty-envelope probes.
"""

from __future__ import annotations

from src.ops.offline_execution_permission_and_position_creation_producer_wiring_v1.route_c_create_path_blocker_constants_v1 import (
    G_POSMODE_RESULT_CLASS,
    G_POSMODE_STATUS,
    G_POSMODE_STATUS_CLOSED_AS,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    CANARY_SUBMIT_TRANSPORT_IMPLEMENTED,
    DEFAULT_INST_TYPE,
    DEFAULT_INSTRUMENT_ID,
    DEFAULT_ORDER_TYPE,
    DEFAULT_SIDE,
    DEFAULT_TD_MODE,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    POSITION_COUNT_LIMIT,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.prerequisite_08_position_source_policy_rebind_v1 import (
    EXTERNAL_OR_PREEXISTING_POSITION_MAY_SATISFY_PREREQUISITE_08_IF_CANONICAL_NONZERO_OBSERVATION_IS_PROVEN,
    EXTERNAL_POSITION_ALLOWED,
    POSITION_MUST_BE_CREATED_BY_PEAK_TRADE,
    POSITION_SOURCE_POLICY,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.prerequisite_08_resolution_authority_adjudication_v1 import (
    AUTHORIZED_RESOLUTION_PATH,
    CANONICAL_PRODUCER,
    PREREQUISITE_08_REQUIRED_PROPOSITION,
)
from src.ops.section_11_13_5_p08_position_observation_v1.constants_v1 import (
    AUTHORIZED_ENDPOINT as P08_AUTHORIZED_ENDPOINT,
    P08_CANONICAL_DEFINITION,
)

CAPABILITY_ID = "P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY_V1"
PACKAGE_MARKER = "P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY_V1=true"
OWNER = "ops.section_11_13_5_p08_post_read_only_exhaustion_authority_boundary_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p08_post_read_only_exhaustion_authority_boundary.v1"
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY_MAXIMUM_SAFE_LEVERAGE_V1"
)
WORKPACKAGE_ID = "OKX_EEA_P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY_V1"
THIS_SLICE = "11.13.5.P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY"
PREDECESSOR_SLICE = "11.13.5.P08_READ_ONLY_CLOSURE"
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "c13d01e20f78cfb4f8d745c1b31a628bba24c275"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
TARGET_INST_TYPE = DEFAULT_INST_TYPE
BOUND_ACCOUNT_SCOPE = REUSED_BINDING_ACCOUNT_SCOPE
MAX_POSITIONS_EFFECTIVE = POSITION_COUNT_LIMIT
TARGET_TD_MODE = DEFAULT_TD_MODE
TARGET_ORDER_TYPE = DEFAULT_ORDER_TYPE
TARGET_SIDE = DEFAULT_SIDE
TARGET_LEVERAGE = "3"

AUTHORIZED_OPERATION = "OFFLINE_P08_AUTHORITY_BOUNDARY_ADJUDICATION_NO_POST"
AUTHORIZED_SCOPE = "A_P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY_OFFLINE"
P08_CANONICAL_ENDPOINT = P08_AUTHORIZED_ENDPOINT
P08_REQUIRED_PROPOSITION = PREREQUISITE_08_REQUIRED_PROPOSITION
P08_CANONICAL_PRODUCER = CANONICAL_PRODUCER
P08_AUTHORIZED_RESOLUTION_PATH = AUTHORIZED_RESOLUTION_PATH
P08_DEFINITION = P08_CANONICAL_DEFINITION

POST_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
POSITION_CREATION_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
TESTNET_EXECUTION_ALLOWED = False
FUNDING_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
P09_WORK_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
RETRY_ALLOWED = False
REDIRECT_FOLLOW_ALLOWED = False
EQUIVALENT_ACCOUNT_POSITIONS_EMPTY_PROBE_ALLOWED = False
GET_REQUIRED_THIS_PERSIST = False
PUBLIC_GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
STANDING_CANARY_SUBMIT_TRANSPORT_IMPLEMENTED = CANARY_SUBMIT_TRANSPORT_IMPLEMENTED
STANDING_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
STANDING_SECRETREF_URI = REQUIRED_SECRETREF_URI

POSITION_SOURCE_POLICY_BOUND = POSITION_SOURCE_POLICY
PEAK_TRADE_CREATION_REQUIRED_FOR_P08 = POSITION_MUST_BE_CREATED_BY_PEAK_TRADE
EXTERNAL_MAY_SATISFY_P08_IF_NONZERO_OBSERVED = EXTERNAL_OR_PREEXISTING_POSITION_MAY_SATISFY_PREREQUISITE_08_IF_CANONICAL_NONZERO_OBSERVATION_IS_PROVEN
EXTERNAL_POSITION_ALLOWED_GENERAL = EXTERNAL_POSITION_ALLOWED
G_POSMODE_STATUS_BOUND = G_POSMODE_STATUS
G_POSMODE_STATUS_CLOSED_AS_BOUND = G_POSMODE_STATUS_CLOSED_AS
G_POSMODE_RESULT_CLASS_BOUND = G_POSMODE_RESULT_CLASS
G_POSMODE_SUBMIT_BODY_PROVEN = False

EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False
P08_CLOSED = False
TARGET_POSITION_ZERO_PROVEN = False
TARGET_POSITION_NONZERO_PROVEN = False
P08_READ_ONLY_CLOSURE_RESULT = "READ_ONLY_EXHAUSTED"
POSITION_OBSERVATION_CLASS = "CASE_C_EMPTY_DATA_NOT_ZERO"

P08_NEXT_AUTHORITY_RESULT = "EXTERNAL_STATE_APPEARANCE_SUFFICIENT"
MINIMUM_HIGHER_AUTHORITY = "EXTERNAL_MANUAL_POSITION_APPEARANCE"
CURRENT_EXECUTION_READINESS = (
    "FIRST_PARTY_CREATE_BLOCKED_BY_G_POSMODE_AND_AUTH_AND_HISTORICAL_CAPACITY_ZERO;"
    "EXTERNAL_APPEARANCE_SEMANTICALLY_SUFFICIENT_NOT_CURRENTLY_OBSERVED"
)
NEXT_AUTHORITY_BOUNDARY = (
    "SEPARATE_OWNER_GO_REQUIRED_FOR_EXTERNAL_MANUAL_TARGET_POSITION_APPEARANCE_"
    "ON_LIVE_CANARY_ACCOUNT_THEN_ONE_UNFILTERED_ACCOUNT_POSITIONS_GET_"
    "NO_PEAK_TRADE_POST_NO_FLATTEN"
)
FUTURE_EXECUTION_GO_DRAFT_ID = (
    "PEAK_TRADE_OWNER_GO_P08_EXTERNAL_MANUAL_TARGET_POSITION_APPEARANCE_"
    "THEN_UNFILTERED_POSITIONS_GET_V1"
)
FUTURE_EXECUTION_GO_DRAFT_STATUS = "COMPLETE"
FUTURE_GO_IS_NOT_CONSUMED = True
FUTURE_GO_AUTHORIZES_POST = False
FUTURE_GO_AUTHORIZES_FLATTEN = False
FLATTEN_REQUIRES_SEPARATE_OWNER_GO = True
P08_CLOSE_DOES_NOT_GRANT_EXECUTION_READINESS = True
CORE_LOGIC_CHANGE = False
SECOND_TRADING_AUTHORITY_INTRODUCED = False

GET_NOT_REQUIRED_REASON = (
    "IDENTICAL_UNFILTERED_POSITIONS_GET_LOW_INFORMATION;"
    "G_POSMODE_BLOCKS_FIRST_PARTY_CREATE_INDEPENDENT_OF_FUNDING;"
    "EXTERNAL_PATH_DOES_NOT_REQUIRE_PEAK_TRADE_PRETRADE_GET;"
    "Z2DP_AND_P08_PACKS_REUSED_AS_HISTORICAL_NOT_CURRENT_08_PROOF"
)

HISTORICAL_P08_READ_ONLY_PACK = (
    "evidence/ops/section_11_13_5_p08_read_only_closure_v1/20260903T210317Z/"
)
HISTORICAL_P08_EMPTY_DATA_PACK = (
    "evidence/ops/section_11_13_5_p08_empty_data_not_zero_v1/20260903T193620Z/"
)
HISTORICAL_Z2DP_PACK = (
    "evidence/ops/section_11_13_5_z2dp_post_z2do_fresh_create_readiness_evidence_v1/"
    "20260903T114921Z/"
)
EVIDENCE_DIRNAME = "section_11_13_5_p08_post_read_only_exhaustion_authority_boundary_v1"
CANONICAL_EVIDENCE_RUN_ID = "20260903T212800Z"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)

RUNTIME_AUTHORIZATION_EFFECT = "NONE"
ATLAS_AUTHORITY = "NONE"
LANDSCAPE_AUTHORITY = "NONE"
NO_MAP_OF_TRUTH_MUTATION = True
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
