"""Draft future Owner-GO for the proven minimum P08-capable path.

Design output only. Never activates, consumes, or submits under this draft.
Flatten remains a separate later Owner-GO.
"""

from __future__ import annotations

from typing import Any

from src.ops.section_11_13_5_p08_post_read_only_exhaustion_authority_boundary_v1.constants_v1 import (
    AUTHORIZED_HOST,
    BOUND_ACCOUNT_SCOPE,
    FLATTEN_REQUIRES_SEPARATE_OWNER_GO,
    FUTURE_EXECUTION_GO_DRAFT_ID,
    FUTURE_EXECUTION_GO_DRAFT_STATUS,
    FUTURE_GO_AUTHORIZES_FLATTEN,
    FUTURE_GO_AUTHORIZES_POST,
    FUTURE_GO_IS_NOT_CONSUMED,
    MAX_POSITIONS_EFFECTIVE,
    P08_CANONICAL_ENDPOINT,
    STANDING_SECRETREF_URI,
    TARGET_INSTRUMENT_ID,
    TARGET_INST_TYPE,
    TARGET_LEVERAGE,
    TARGET_ORDER_TYPE,
    TARGET_SIDE,
    TARGET_TD_MODE,
)


def build_future_execution_go_draft_v1() -> dict[str, Any]:
    """Return the complete external-appearance plus observation-GET draft."""
    return {
        "FUTURE_EXECUTION_GO_DRAFT_STATUS": FUTURE_EXECUTION_GO_DRAFT_STATUS,
        "FUTURE_OWNER_GO_ID": FUTURE_EXECUTION_GO_DRAFT_ID,
        "FUTURE_GO_IS_NOT_CONSUMED": FUTURE_GO_IS_NOT_CONSUMED,
        "THIS_PERSIST_DOES_NOT_ACTIVATE_THE_DRAFT": True,
        "ENVIRONMENT": "LIVE_CANARY_ACCOUNT_OBSERVATION_ONLY",
        "HOST": AUTHORIZED_HOST,
        "ACCOUNT_UID": BOUND_ACCOUNT_SCOPE,
        "TARGET_INSTRUMENT": TARGET_INSTRUMENT_ID,
        "TARGET_INST_TYPE": TARGET_INST_TYPE,
        "MAX_POSITIONS": MAX_POSITIONS_EFFECTIVE,
        "MAXIMUM_POSITION_QUANTITY": "1",
        "MAXIMUM_ORDER_QUANTITY": "1",
        "ORDER_TYPE": TARGET_ORDER_TYPE,
        "SIDE": TARGET_SIDE,
        "POS_SIDE_SEMANTICS": "VENUE_UI_NET_MODE_OWNER_MANAGED_NOT_PEAK_TRADE_SUBMIT_BODY",
        "LEVERAGE": TARGET_LEVERAGE,
        "MARGIN_MODE": TARGET_TD_MODE,
        "PEAK_TRADE_POST_AUTHORIZED": FUTURE_GO_AUTHORIZES_POST,
        "PEAK_TRADE_FLATTEN_AUTHORIZED": FUTURE_GO_AUTHORIZES_FLATTEN,
        "LIVE_ENABLED_REQUIRED": False,
        "LIVE_ARMED_REQUIRED": False,
        "CANARY_AUTHORIZED_REQUIRED": False,
        "SUBMIT_UNLOCKED_REQUIRED": False,
        "DRY_RUN_CONFIRM_TOKEN": "NONE_NO_PEAK_TRADE_SUBMIT",
        "OWNER_VENUE_ACTIONS": [
            "OPTIONAL_FUND_LIVE_CANARY_ACCOUNT_IF_VENUE_REJECTS_UNFUNDED_OPEN",
            (
                "OPEN_EXACTLY_ONE_TARGET_POSITION_ON_EEA_OKX_UI_FOR_"
                f"{TARGET_INSTRUMENT_ID}_QTY_1_CROSS_LEVERAGE_3_NO_OTHER_INSTRUMENT"
            ),
            "DO_NOT_ASK_PEAK_TRADE_TO_POST",
        ],
        "PEAK_TRADE_ACTIONS_AFTER_APPEARANCE": [
            "SEPARATE_SCOPED_OWNER_GO_FOR_EXACTLY_ONE_UNFILTERED_GET_ACCOUNT_POSITIONS",
            P08_CANONICAL_ENDPOINT,
            "REUSE_EXISTING_PRODUCER_CLASSIFY_TARGET_POSITION_STATE_V1",
            "NO_FILTERED_INSTID_ZERO_PROOF",
            "NO_RETRY",
            "NO_POST",
            "NO_FLATTEN",
        ],
        "FRESH_PRETRADE_REQUIREMENTS": [
            "POST_ACTION_UNFILTERED_POSITIONS_GET_HTTP_200_OKX_0",
            "EXACTLY_ONE_TARGET_INSTRUMENT_ROW",
            "CANONICALLY_NONZERO_POS",
            "NO_SECOND_INSTRUMENT_NONZERO_ROW",
            "MAX_POSITIONS=1_STILL_HOLDS",
        ],
        "SAFETY_GATES": [
            "NO_PEAK_TRADE_POST",
            "NO_LIVE_ENABLED_MUTATION",
            "NO_LIVE_ARMED_MUTATION",
            "NO_CANARY_AUTHORIZED_MUTATION",
            "NO_SUBMIT_UNLOCKED_MUTATION",
            "NO_CREDENTIAL_MUTATION",
            "NO_WHITELIST_MUTATION",
            "NO_CORE_LOGIC_MUTATION",
            "SECRETREF_UNCHANGED=" + STANDING_SECRETREF_URI,
        ],
        "MAXIMUM_FINANCIAL_EXPOSURE": (
            "OWNER_VENUE_QTY_1_SUI_USD_UM_XPERP_310404_CROSS_LEVERAGE_3;"
            "NOT_A_PEAK_TRADE_SIZING_DECISION;STEP_29P_NOT_REPLACED"
        ),
        "SUCCESS_EVIDENCE_REQUIRED": [
            "HTTP_200",
            "OKX_0",
            "UNFILTERED_GET_ACCOUNT_POSITIONS",
            "CASE_A_TARGET_NONZERO",
            "TARGET_POSITION_NONZERO_PROVEN=true",
            "P08_CLOSED=true",
        ],
        "FAILURE_ABORT_CONDITIONS": [
            "EMPTY_DATA_STILL_NOT_ZERO",
            "ZERO_ROW",
            "AMBIGUOUS_ROWS",
            "NON_TARGET_INSTRUMENT_PRESENT",
            "HTTP_OR_OKX_ERROR",
            "ANY_PEAK_TRADE_POST_ATTEMPT",
        ],
        "POST_ACTION_READBACK_REQUIRED_TO_CLOSE_P08": P08_CANONICAL_ENDPOINT,
        "FLATTEN_EXIT_AUTHORITY_STATUS": "NOT_GRANTED",
        "SEPARATE_FLATTEN_AUTHORITY_REQUIRED": FLATTEN_REQUIRES_SEPARATE_OWNER_GO,
        "FIRST_PARTY_CANARY_OR_LIVE_POST_ANNEX": {
            "STATUS": "BLOCKED_NOT_THE_MINIMUM_PATH",
            "PRIMARY_BLOCKER": "G_POSMODE_SUBMIT_BODY_UNPROVEN",
            "ADDITIONAL_BLOCKERS": [
                "LIVE_ENABLED=false",
                "LIVE_ARMED=false",
                "SUBMIT_UNLOCKED=false",
                "CANARY_AUTHORIZED=false",
                "HISTORICAL_VENUE_CAPACITY_PROVEN_ZERO",
            ],
        },
    }
