"""Standing constants for Treasury PDF current-head rebind census.

No network. No mutation. PDF is never authority.
"""

from __future__ import annotations

CAPABILITY_ID = "TREASURY_PDF_CURRENT_HEAD_REBIND_AND_CENSUS_V1"
PACKAGE_MARKER = "TREASURY_PDF_CURRENT_HEAD_REBIND_AND_CENSUS_V1=true"
OWNER = "ops.treasury_pdf_current_head_rebind_and_census_v1"
SCHEMA_VERSION = "treasury_pdf_current_head_rebind_and_census.v1"
CONTRACT_VERSION = "v1"

WP_ID = "TREASURY_PDF_CURRENT_HEAD_REBIND_AND_CENSUS_V1"
OWNER_GO = WP_ID
ALLOWED_OWNER_GOS = frozenset({OWNER_GO, f"OWNER_GO_{OWNER_GO}", "OWNER_GO=true"})

EXPECTED_ORIGIN_MAIN_SHA = "3d3262e17711703d71a3f349f1f49900f9984c10"
CANONICAL_PACK_RELPATH = "evidence/ops/treasury_pdf_current_head_rebind_and_census_v1"
CANONICAL_PACK_AS_OF_FOLDER = "2026-09-21T010000Z"
SCHEMA_CLASS = "TREASURY_PDF_CURRENT_HEAD_REBIND_AND_CENSUS_V1"
AUTHORITY_EFFECT = "NONE"
PDF_AUTHORITY = "NONE"
ATLAS_AUTHORITY = "NONE"

NETWORK_ALLOWED = False
EXTERNAL_EFFECT_AUTHORIZED = False
TREASURY_MUTATION_AUTHORIZED = False

CURRENT_CANONICAL_TREASURY_AUTHORITY = (
    "docs/runbooks/canonical/PEAK_TRADE_MASTER_RUNBOOK.md#CURRENT-Treasury-Phase-Bindings"
)

EARLIEST_REAL_TREASURY_BLOCKER = (
    "CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_BASE_UNBOUND_AFTER_PRODUCER_DEFINED"
)
BLOCKER_CLASS = "PRODUCTIVE_SIZING_SOURCE_BINDING"
MISSING_FACT_OR_AUTHORITY = (
    "C08 reconciled base-candidate transport bound; numeric "
    "CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_BASE value remains UNBOUND until "
    "separate Owner-GO observation binding."
)

FULL_CORE_P1_STATUS = "CLOSED"
FULL_CORE_P1_PR_BUDGET_SLOT = "1_OF_2"
FULL_CORE_P2_P3_ON_CURRENT_HEAD = "NOT_CANONICALLY_DEFINED"

TRUE_TOKEN = "true"
FALSE_TOKEN = "false"
