"""Constants for §11.12.8 real productive Testnet execute-path unlock."""

from __future__ import annotations

from src.ops.section_11_12_8_actual_productive_testnet_campaign_run_start_v1.constants_v1 import (
    CAPABILITY_ID as PREDECESSOR_CAPABILITY_ID,
    SCOPED_OWNER_GO_AUTHORIZATION,
    SCOPED_OWNER_GO_SCOPE,
    SCOPED_OWNER_GO_TOKEN,
)

CAPABILITY_ID = "CAPABILITY_11_SECTION_11_12_8_REAL_PRODUCTIVE_TESTNET_EXECUTE_PATH_UNLOCK_V1"
PACKAGE_MARKER = "CAPABILITY_11_SECTION_11_12_8_REAL_PRODUCTIVE_TESTNET_EXECUTE_PATH_UNLOCK_V1=true"
OWNER = "ops.section_11_12_8_real_productive_testnet_execute_path_unlock_v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID_BOUND = PREDECESSOR_CAPABILITY_ID
# Fresh canonical next step AFTER the bounded long-running package merges.
CANONICAL_NEXT_STEP_AFTER_MERGE = (
    "SEPARATE_OWNER_GO_EXECUTE_BOUNDED_LONG_RUNNING_PRODUCTIVE_TESTNET_CAMPAIGN_NOW"
)
NEXT_CONSUMER_CAPABILITY_ID = CANONICAL_NEXT_STEP_AFTER_MERGE
AUTHORIZATION_REQUIRED_AFTER_MERGE = "PRESENT_OWNER_GO_EXECUTE"
REQUEST_MATCHES_CANONICAL_NEXT_STEP_FOR_EXECUTE_GO = True
LONG_RUNNING_CAMPAIGN_PATH_PRESENT = True

SCOPED_OWNER_GO_TOKEN_BOUND = SCOPED_OWNER_GO_TOKEN
SCOPED_OWNER_GO_SCOPE_BOUND = SCOPED_OWNER_GO_SCOPE
SCOPED_OWNER_GO_AUTHORIZATION_BOUND = SCOPED_OWNER_GO_AUTHORIZATION

CORE_LOGIC_CHANGE = False
REFERENCE_ONLY = False
PATH_IMPLEMENTATION_ONLY_REFUSAL_REMOVED = True
AUTHORIZED_RUNTIME_PATH_IMPLEMENTATION_ONLY = False
AUTHORIZED_RUNTIME_PATH_PRODUCTIVE_REAL_TESTNET_EXECUTION_FORBIDDEN = False
MODE_PRODUCTIVE_REAL_PERMITTED_FOR_TESTNET_ONLY = True
MODE_PRODUCTIVE_REAL_REQUIRES_ALL_EXISTING_GATES_PASS = True
NO_ADDITIONAL_IMPLEMENTATION_GO_REQUIRED_BEFORE_EXECUTE = True
NO_ADDITIONAL_GOVERNANCE_UNLOCK_PR_REQUIRED_BEFORE_EXECUTE = True
NO_ADDITIONAL_CAPABILITY_PR_REQUIRED_BEFORE_EXECUTE = True
SECRETREF_MATERIAL_IS_RUNTIME_PRECONDITION_ONLY = True
HIDDEN_CONFIRM_SINGLE_USE_IS_RUNTIME_PRECONDITION_ONLY = True
SECRETREF_AND_HIDDEN_CONFIRM_ARE_NOT_FUTURE_GOVERNANCE_DEPENDENCIES = True

PRODUCTIVE_TESTNET_CAMPAIGN_STARTED = False
PRODUCTIVE_TESTNET_CAMPAIGN_COMPLETED = False
NETWORK_SESSION_STARTED = False
NETWORK_EFFECT = "NONE"
ORDER_EFFECT = "NONE"
LIVE_ORDER_EFFECT = "NONE"
LIVE_AUTHORIZED = False
SECTION_11_13_STARTED = False
CAPABILITY_11_13_STARTED = False
CREDENTIAL_PLAINTEXT_LOADED = False
PRE_MERGE_REAL_NETWORK_EFFECT = False
PRE_MERGE_ORDER_EFFECT = False
LIVE_HARD_BLOCK_PRESERVED = True

BOUND_CLIENT_KIND = "BOUND_REAL_TESTNET_HTTP_CLIENT"
VAULT_BACKEND_KIND = "PRODUCTIVE_SECRETREF_VAULT_RESOLVER"

# Cloudflare / OKX EEA gateway rejects Python-urllib default UA (error 1010).
# Browser-compatible UA is transport-only; it does not alter signing or auth semantics.
BOUND_OKX_TESTNET_HTTP_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/127.0.0.0 Safari/537.36"
)
# OKX private REST accepts ISO-8601 UTC with millisecond precision (…SSS Z).
# Bare str(time.time()) can yield excess fractional digits → OKX 50112.
BOUND_OKX_ACCESS_TIMESTAMP_FORMAT = "ISO8601_MS_Z"

REQUIRED_RUNTIME_CHAIN: tuple[str, ...] = (
    "OWNER_GO_EXECUTE",
    "ACTIVATION_ENABLED_ARMED",
    "TESTNET_AUTHORIZED",
    "PRODUCTIVE_SECRETREF_RESOLVER",
    "EPHEMERAL_SECRET_LOAD",
    "RISK_GATE",
    "KILL_SWITCH",
    "EMERGENCY_CONTROL",
    "HIDDEN_CONFIRM_SINGLE_USE",
    "PRODUCTIVE_REAL_CONSUMER",
    "PRODUCTIVE_REAL_EXECUTOR",
    "TESTNET_ACCOUNT_BINDING",
    "ENDPOINT_ALLOWLIST",
    "BOUND_REAL_TESTNET_HTTP_CLIENT",
    "NETWORK_SESSION_ENTRY",
    "FIRST_PERMITTED_TESTNET_SIDE_EFFECT",
    "CAMPAIGN_RUNNING",
    "EXECUTION_EVIDENCE",
    "EVIDENCE_SEAL",
    "COMPLETED_OR_ABORTED",
)

FORBIDDEN_TRACE_TOKENS: tuple[str, ...] = (
    "IMPLEMENTATION_ONLY",
    "STUBBED_ACCEPTANCE",
    "REAL_PRODUCTIVE_CAMPAIGN_FORBIDDEN_IN_IMPLEMENTATION_GO",
    "HTTP_CLIENT_NOT_BOUND",
    "NO_REAL_EXECUTE_ENTRYPOINT",
    "REAL_VAULT_NOT_INVOKED_IN_IMPLEMENTATION_GO",
    "DEAD_EDGE",
    "PLACEHOLDER_EXECUTOR",
    "WIRE_SEND_FORBIDDEN_IN_UNLOCK_IMPLEMENTATION_GO",
)

EVIDENCE_DIRNAME = "capability_11_section_11_12_8_real_productive_testnet_execute_path_unlock_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
ACCEPTANCE_PROOF_FILENAME = "pre_merge_acceptance_gate_proof.json"
RUNTIME_TRACE_FILENAME = "runtime_call_chain_audit.json"
FORENSIC_TRACE_FILENAME = "forensic_blocker_trace.json"
GOVERNANCE_ACCEPTANCE_FILENAME = "governance_acceptance_proof.json"
