"""Governance acceptance proof for post-unlock EXECUTE next-step authority."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_12_8_real_productive_testnet_execute_path_unlock_v1.constants_v1 import (
    AUTHORIZATION_REQUIRED_AFTER_MERGE,
    AUTHORIZED_RUNTIME_PATH_IMPLEMENTATION_ONLY,
    AUTHORIZED_RUNTIME_PATH_PRODUCTIVE_REAL_TESTNET_EXECUTION_FORBIDDEN,
    CANONICAL_NEXT_STEP_AFTER_MERGE,
    CAPABILITY_ID,
    HIDDEN_CONFIRM_SINGLE_USE_IS_RUNTIME_PRECONDITION_ONLY,
    LIVE_HARD_BLOCK_PRESERVED,
    LONG_RUNNING_CAMPAIGN_PATH_PRESENT,
    MODE_PRODUCTIVE_REAL_PERMITTED_FOR_TESTNET_ONLY,
    MODE_PRODUCTIVE_REAL_REQUIRES_ALL_EXISTING_GATES_PASS,
    NO_ADDITIONAL_CAPABILITY_PR_REQUIRED_BEFORE_EXECUTE,
    NO_ADDITIONAL_GOVERNANCE_UNLOCK_PR_REQUIRED_BEFORE_EXECUTE,
    NO_ADDITIONAL_IMPLEMENTATION_GO_REQUIRED_BEFORE_EXECUTE,
    REQUEST_MATCHES_CANONICAL_NEXT_STEP_FOR_EXECUTE_GO,
    SECRETREF_AND_HIDDEN_CONFIRM_ARE_NOT_FUTURE_GOVERNANCE_DEPENDENCIES,
    SECRETREF_MATERIAL_IS_RUNTIME_PRECONDITION_ONLY,
    SECTION_11_13_STARTED,
)

_MASTER_RUNBOOK = (
    Path(__file__).resolve().parents[3]
    / "docs"
    / "runbooks"
    / "canonical"
    / "PEAK_TRADE_MASTER_RUNBOOK.md"
)

_REQUIRED_RUNBOOK_MARKERS: tuple[str, ...] = (
    "CANONICAL_NEXT_STEP_AFTER_BOUNDED_LONG_RUNNING_PATH_MERGE=SEPARATE_OWNER_GO_EXECUTE_BOUNDED_LONG_RUNNING_PRODUCTIVE_TESTNET_CAMPAIGN_NOW",
    "AUTHORIZATION_REQUIRED=PRESENT_OWNER_GO_EXECUTE",
    "NO_ADDITIONAL_IMPLEMENTATION_GO_REQUIRED_BEFORE_EXECUTE=true",
    "MODE_PRODUCTIVE_REAL_PERMITTED_FOR_TESTNET_ONLY=true",
    "AUTHORIZED_RUNTIME_PATH_IMPLEMENTATION_ONLY=false",
    "SECRETREF_AND_HIDDEN_CONFIRM_ARE_NOT_FUTURE_GOVERNANCE_DEPENDENCIES=true",
    "LIVE_HARD_BLOCK_PRESERVED=true",
    "SECTION_11_13_STARTED=false",
    "SECTION_11_12_8_CAMPAIGN_DURATION_BOUND_SECONDS=3600",
    "LONG_RUNNING_CAMPAIGN_PATH_PRESENT=true",
    "WIRE_SENT_IS_NOT_EXCHANGE_ACK=true",
    "CYCLE_COMPLETE_IS_NOT_CAMPAIGN_COMPLETED=true",
    "SECTION_11_12_8_BOUNDED_CAMPAIGN_RUN_ID=20260808T181528Z",
    "CANONICAL_NEXT_STEP_AFTER_HTTP_403_FORENSIC=OWNER_GO_RESOLVE_EXTERNAL_OKX_TESTNET_ACCOUNT_OR_CREDENTIAL_BLOCKER_AND_RETRY_TARGETED_PROOF",
    "SECTION_11_12_8_CLOSED=true",
    "LONG_RUNNING_TESTNET_PROVEN=false",
    "LONG_RUNNING_TESTNET_PROVEN_PREP_PATH_READY=true",
    "CANONICAL_EXECUTE_OWNER_GO_SCOPE=EXECUTE_BOUNDED_LONG_RUNNING_PRODUCTIVE_TESTNET_CAMPAIGN_NOW",
    "SECTION_11_12_8_REOPENED=false",
    "PERMANENT_BOUND_CLIENT_QUERY_SIGN_FIX=true",
)

_FORBIDDEN_RUNBOOK_RESIDUALS: tuple[str, ...] = (
    "AUTHORIZED_RUNTIME_PATH_IMPLEMENTATION_ONLY=true",
    "AUTHORIZED_RUNTIME_PATH_PRODUCTIVE_REAL_TESTNET_EXECUTION_FORBIDDEN=true",
    "NO_ADDITIONAL_IMPLEMENTATION_GO_REQUIRED_BEFORE_EXECUTE=false",
)

_EXPECTED_NEXT = "SEPARATE_OWNER_GO_EXECUTE_BOUNDED_LONG_RUNNING_PRODUCTIVE_TESTNET_CAMPAIGN_NOW"


def prove_governance_acceptance_v1() -> dict[str, Any]:
    residual: list[str] = []
    text = _MASTER_RUNBOOK.read_text(encoding="utf-8") if _MASTER_RUNBOOK.is_file() else ""
    if not text:
        residual.append("MASTER_RUNBOOK_MISSING")
    for marker in _REQUIRED_RUNBOOK_MARKERS:
        if marker not in text:
            residual.append(f"MISSING_RUNBOOK_MARKER:{marker}")
    for bad in _FORBIDDEN_RUNBOOK_RESIDUALS:
        if bad in text:
            residual.append(f"FORBIDDEN_RUNBOOK_RESIDUAL:{bad}")

    claims = {
        "CAPABILITY_ID": CAPABILITY_ID,
        "CANONICAL_NEXT_STEP_AFTER_MERGE": CANONICAL_NEXT_STEP_AFTER_MERGE,
        "REQUEST_MATCHES_CANONICAL_NEXT_STEP": (REQUEST_MATCHES_CANONICAL_NEXT_STEP_FOR_EXECUTE_GO),
        "AUTHORIZATION_REQUIRED": AUTHORIZATION_REQUIRED_AFTER_MERGE,
        "NO_ADDITIONAL_IMPLEMENTATION_GO_REQUIRED_BEFORE_EXECUTE": (
            NO_ADDITIONAL_IMPLEMENTATION_GO_REQUIRED_BEFORE_EXECUTE
        ),
        "NO_ADDITIONAL_GOVERNANCE_UNLOCK_PR_REQUIRED_BEFORE_EXECUTE": (
            NO_ADDITIONAL_GOVERNANCE_UNLOCK_PR_REQUIRED_BEFORE_EXECUTE
        ),
        "NO_ADDITIONAL_CAPABILITY_PR_REQUIRED_BEFORE_EXECUTE": (
            NO_ADDITIONAL_CAPABILITY_PR_REQUIRED_BEFORE_EXECUTE
        ),
        "MODE_PRODUCTIVE_REAL_PERMITTED_FOR_TESTNET_ONLY": (
            MODE_PRODUCTIVE_REAL_PERMITTED_FOR_TESTNET_ONLY
        ),
        "MODE_PRODUCTIVE_REAL_REQUIRES_ALL_EXISTING_GATES_PASS": (
            MODE_PRODUCTIVE_REAL_REQUIRES_ALL_EXISTING_GATES_PASS
        ),
        "AUTHORIZED_RUNTIME_PATH_IMPLEMENTATION_ONLY": (
            AUTHORIZED_RUNTIME_PATH_IMPLEMENTATION_ONLY
        ),
        "AUTHORIZED_RUNTIME_PATH_PRODUCTIVE_REAL_TESTNET_EXECUTION_FORBIDDEN": (
            AUTHORIZED_RUNTIME_PATH_PRODUCTIVE_REAL_TESTNET_EXECUTION_FORBIDDEN
        ),
        "SECRETREF_MATERIAL_IS_RUNTIME_PRECONDITION_ONLY": (
            SECRETREF_MATERIAL_IS_RUNTIME_PRECONDITION_ONLY
        ),
        "HIDDEN_CONFIRM_SINGLE_USE_IS_RUNTIME_PRECONDITION_ONLY": (
            HIDDEN_CONFIRM_SINGLE_USE_IS_RUNTIME_PRECONDITION_ONLY
        ),
        "SECRETREF_AND_HIDDEN_CONFIRM_ARE_NOT_FUTURE_GOVERNANCE_DEPENDENCIES": (
            SECRETREF_AND_HIDDEN_CONFIRM_ARE_NOT_FUTURE_GOVERNANCE_DEPENDENCIES
        ),
        "LIVE_HARD_BLOCK_PRESERVED": LIVE_HARD_BLOCK_PRESERVED,
        "SECTION_11_13_STARTED": SECTION_11_13_STARTED,
        "LONG_RUNNING_CAMPAIGN_PATH_PRESENT": LONG_RUNNING_CAMPAIGN_PATH_PRESENT,
    }

    if CANONICAL_NEXT_STEP_AFTER_MERGE != _EXPECTED_NEXT:
        residual.append("CANONICAL_NEXT_STEP_MISMATCH")
    if AUTHORIZATION_REQUIRED_AFTER_MERGE != "PRESENT_OWNER_GO_EXECUTE":
        residual.append("AUTHORIZATION_REQUIRED_MISMATCH")
    if not REQUEST_MATCHES_CANONICAL_NEXT_STEP_FOR_EXECUTE_GO:
        residual.append("REQUEST_MATCHES_FALSE")
    if AUTHORIZED_RUNTIME_PATH_IMPLEMENTATION_ONLY:
        residual.append("PATH_STILL_IMPLEMENTATION_ONLY")
    if AUTHORIZED_RUNTIME_PATH_PRODUCTIVE_REAL_TESTNET_EXECUTION_FORBIDDEN:
        residual.append("PATH_STILL_FORBIDS_PRODUCTIVE_REAL")
    if not NO_ADDITIONAL_IMPLEMENTATION_GO_REQUIRED_BEFORE_EXECUTE:
        residual.append("ADDITIONAL_IMPLEMENTATION_GO_STILL_REQUIRED")
    if SECTION_11_13_STARTED:
        residual.append("SECTION_11_13_STARTED")
    if not LIVE_HARD_BLOCK_PRESERVED:
        residual.append("LIVE_HARD_BLOCK_NOT_PRESERVED")
    if not LONG_RUNNING_CAMPAIGN_PATH_PRESENT:
        residual.append("LONG_RUNNING_PATH_ABSENT")

    ok = len(residual) == 0
    return {
        "ok": ok,
        "GOVERNANCE_ACCEPTANCE": "PASS" if ok else "FAIL",
        "claims": claims,
        "residual_blockers": residual,
        "master_runbook_path": str(_MASTER_RUNBOOK),
    }
