"""Constants for CURRENT MF N=5 durable lane-assignment persistence V1."""

from __future__ import annotations

from src.ops.current_mf_n5_isolated_lane_instance_topology_v1.constants_v1 import (
    CONTRACT_ID as TOPOLOGY_CONTRACT_ID,
    CROSS_UNIVERSE_CANDIDATE_BORROWING as TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK as TOPOLOGY_CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN as TOPOLOGY_CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT as TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING as TOPOLOGY_CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION as TOPOLOGY_CROSS_UNIVERSE_SELECTION,
    INSTRUMENT_ID_ALONE_SUFFICIENT as TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT,
    LANE_MAPPING_OWNER as TOPOLOGY_LANE_MAPPING_OWNER,
    MAX_POSITIONS_EFFECTIVE as TOPOLOGY_MAX_POSITIONS_EFFECTIVE,
    MULTI_UNIVERSE_MERGE as TOPOLOGY_MULTI_UNIVERSE_MERGE,
    SCHEMA_VERSION as TOPOLOGY_SCHEMA_VERSION,
)

OWNER = "ops.current_mf_n5_durable_lane_assignment_persistence_v1"
CONTRACT_ID = "CURRENT_MF_N5_DURABLE_LANE_ASSIGNMENT_PERSISTENCE_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_n5_durable_lane_assignment.v1"

LANE_MAPPING_OWNER = TOPOLOGY_LANE_MAPPING_OWNER
TOPOLOGY_CONTRACT_ID = TOPOLOGY_CONTRACT_ID
TOPOLOGY_SCHEMA_VERSION = TOPOLOGY_SCHEMA_VERSION

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
PERSISTENCE_RANKING_AUTHORITY = False
PERSISTENCE_MEMBERSHIP_AUTHORITY = False
PERSISTENCE_LANE_MAPPING_AUTHORITY = False
PERSISTENCE_CAP23_SELECTION_AUTHORITY = False
PERSISTENCE_CAP24_BINDING_AUTHORITY = False
PERSISTENCE_TRADING_AUTHORITY = False
PERSISTENCE_EXECUTION_AUTHORITY = False

CROSS_UNIVERSE_SELECTION = TOPOLOGY_CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = TOPOLOGY_CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = TOPOLOGY_CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = TOPOLOGY_CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = TOPOLOGY_MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT
UNIVERSE_ISOLATION = "HARD"
UNIVERSE_ISOLATION_ENFORCED = True

MF_PRODUCTIVE_JOIN = False
FIVE_LANE_RUNTIME_CREATED = False
FIVE_LANE_CONTINUOUS_HOST_JOIN = False
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = False
MF_SINGLE_EGRESS_REWIRED = False
MAX_POSITIONS_EFFECTIVE = int(TOPOLOGY_MAX_POSITIONS_EFFECTIVE)
assert MAX_POSITIONS_EFFECTIVE == 1

CAP23_CHANGE_REQUIRED = False
CAP24_CHANGE_REQUIRED = False
MASTER_V2_CHANGE_REQUIRED = False
DOUBLE_PLAY_CHANGE_REQUIRED = False

CHECKPOINT_DIRNAME = "durable_lane_assignment_v1"
CHECKPOINT_FILENAME = "durable_lane_assignment_checkpoint_v1.json"
COMMIT_MARKER_FILENAME = "durable_lane_assignment_commit_marker_v1.json"
MANIFEST_FILENAME = "MANIFEST.sha256"
WRITER_LOCK_FILENAME = "durable_lane_assignment_writer.lock"
STAGING_DIRNAME_PREFIX = ".durable_lane_assignment_staging_"
SINGLE_WRITER_IDENTITY = "durable_lane_assignment_persistence_v1_writer"

RECOVERY_MODE_BOOTSTRAP = "BOOTSTRAP"
RECOVERY_MODE_RESTART = "RESTART"
RECOVERY_MODES = frozenset({RECOVERY_MODE_BOOTSTRAP, RECOVERY_MODE_RESTART})

ATOMICITY = "PER_FILE_REPLACE_PLUS_STAGING_THEN_PUBLISH"
BUNDLE_CRASH = "FAIL_CLOSED_ON_MANIFEST_OR_MARKER_MISMATCH"
PREVIOUS_CHECKPOINT_SURVIVAL_MID_PUBLISH = "NOT_GUARANTEED"

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "apply_isolated_lane_topology_v1",
        "build_occupied_lane_pins_v1",
        "produce_single_selected_future_v1",
        "run_single_selected_future_policy_v1",
        "persist_selection_bundle_atomic_v1",
        "_pick_top_eligible",
        "mf_canonical_single_egress_authority_handoff_contract_v1",
        "master_v2",
        "double_play",
        "execution",
        "top_n_active_set",
    }
)
