"""Assemble the P12 EXECUTION_PREREQUISITE_11 position-side persist pack."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_13_5_p12_execution_prerequisite_11_position_side_posside_v1.adjudicate_v1 import (
    adjudicate_execution_prerequisite_11_position_side_posside_v1,
)
from src.ops.section_11_13_5_p12_execution_prerequisite_11_position_side_posside_v1.constants_v1 import (
    AUTHORIZED_ACCOUNT_UID,
    AUTHORIZED_HOST,
    AUTHORIZED_OPERATION,
    AUTHORIZED_SCOPE,
    CANONICAL_EVIDENCE_RUN_ID,
    CASE_VALUE,
    CONFLICT_COUNT,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EVIDENCE_DIRNAME,
    EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT,
    EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE,
    EXPECTED_ORIGIN_MAIN_SHA,
    FLATTEN_ORDER_SIDE_RULE,
    HISTORICAL_EVIDENCE_PROMOTED_TO_CURRENT_AUTHORITY,
    HISTORICAL_POSMODE_NET_STATUS,
    HISTORICAL_POSSIDE_NET_STATUS,
    LAST_CANONICALLY_CLOSED_STEP,
    LONG_SHORT_IS_NOT_BUY_SELL_VALUE,
    NEXT_AUTHORITY_BOUNDARY,
    OWNER_GO,
    P08_CLOSED,
    P10_CLOSED,
    P11_CLOSED_VALUE,
    P11_POS_TO_SZ_CLOSED,
    P11_PROVEN_VALUE,
    P11_TEXT_REWRITTEN,
    P12_DOES_NOT_AUTHORIZE_FLATTEN,
    P12_DOES_NOT_GRANT_EXECUTION_READINESS,
    POS_MODE_IS_NOT_POSITION_SIDE_VALUE,
    POS_MODE_NET_MODE_DOES_NOT_IMPLY_REQUEST_POS_SIDE_NET_VALUE,
    POS_TO_SZ_UNIT_IDENTITY,
    POSITION_ROW_POS_SIDE_IS_NOT_REQUEST_POS_SIDE_VALUE,
    POSITION_ROW_POS_SIDE_OBSERVED_P08_VALUE,
    PREDECESSOR_SLICE,
    PRIOR_OWNER_GO,
    PRIVATE_AUTH_USED,
    PUBLIC_SPEC_RETRIEVAL_PERFORMED,
    REQUEST_POS_SIDE_POLICY_VALUE,
    REQUEST_POS_SIDE_VALUE_CURRENT,
    RUNTIME_GET_PERFORMED,
    RUNTIME_GET_REQUIRED,
    TARGET_INSTRUMENT_ID,
    TARGET_POSITION_QTY_UNIT,
    THIS_GO_GET_COUNT,
    THIS_GO_POST_COUNT,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.section_11_13_5_p12_execution_prerequisite_11_position_side_posside_v1.persist_v1 import (
    persist_p12_position_side_evidence_v1,
)


class P12PositionSideAssembleError(RuntimeError):
    """Fail-closed assemble violation."""


def assemble_p12_execution_prerequisite_11_position_side_v1(
    *,
    origin_main_sha: str,
    evidence_root: Path | None = None,
    run_id: str = CANONICAL_EVIDENCE_RUN_ID,
) -> dict[str, Any]:
    """Build and optionally persist prerequisite 11. No GET. No POST."""
    if str(origin_main_sha or "").strip() != EXPECTED_ORIGIN_MAIN_SHA:
        raise P12PositionSideAssembleError("ORIGIN_MAIN_SHA_MISMATCH")
    verdict = adjudicate_execution_prerequisite_11_position_side_posside_v1(
        origin_main_sha=origin_main_sha
    )
    if verdict["EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE"] != "PASS":
        raise P12PositionSideAssembleError("PREREQUISITE_11_MUST_PASS")
    if verdict["P11_CLOSED"] is not True:
        raise P12PositionSideAssembleError("P11_MUST_BE_CLOSED")
    census = {
        "DOCUMENT_CLASS": "P12_EXECUTION_PREREQUISITE_11_CENSUS_V1",
        "DOCUMENT_ROLE": "FORENSIC_CENSUS_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "SEAM_COUNT": verdict["CENSUS"]["SEAM_COUNT"],
        "EPISTEMIC_CLASS_COUNTS": verdict["CENSUS"]["EPISTEMIC_CLASS_COUNTS"],
        "PROVEN_SEAMS": verdict["CENSUS"]["PROVEN_SEAMS"],
        "NOT_PROMOTED_SEAMS": verdict["CENSUS"]["NOT_PROMOTED_SEAMS"],
        "REQUEST_POS_SIDE_POLICY": REQUEST_POS_SIDE_POLICY_VALUE,
        "FLATTEN_ORDER_SIDE_RULE": FLATTEN_ORDER_SIDE_RULE,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
    }
    lineage = {
        "DOCUMENT_CLASS": "P12_EXECUTION_PREREQUISITE_11_LINEAGE_V1",
        "DOCUMENT_ROLE": "FORENSIC_LINEAGE_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "LINEAGE_FIELD_NAMES": verdict["CENSUS"]["LINEAGE_FIELD_NAMES"],
        "SEAMS": verdict["LINEAGE"],
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
    }
    adjudication = {
        "DOCUMENT_CLASS": "P12_EXECUTION_PREREQUISITE_11_ADJUDICATION_V1",
        "DOCUMENT_ROLE": "INTERPRETATION_NOT_RAW_WIRE_NOT_SSOT",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE": (
            EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE
        ),
        "P11_PROVEN": P11_PROVEN_VALUE,
        "P11_CLOSED": P11_CLOSED_VALUE,
        "FLATTEN_ORDER_SIDE_RULE": FLATTEN_ORDER_SIDE_RULE,
        "FLATTEN_ORDER_SIDE": verdict["FLATTEN_ORDER_SIDE"],
        "REQUEST_POS_SIDE_POLICY": REQUEST_POS_SIDE_POLICY_VALUE,
        "REQUEST_POS_SIDE": REQUEST_POS_SIDE_VALUE_CURRENT,
        "POSITION_ROW_POS_SIDE_OBSERVED_P08": POSITION_ROW_POS_SIDE_OBSERVED_P08_VALUE,
        "POSITION_ROW_POS_SIDE_IS_NOT_REQUEST_POS_SIDE": (
            POSITION_ROW_POS_SIDE_IS_NOT_REQUEST_POS_SIDE_VALUE
        ),
        "POS_MODE_IS_NOT_POSITION_SIDE": POS_MODE_IS_NOT_POSITION_SIDE_VALUE,
        "POS_MODE_NET_MODE_DOES_NOT_IMPLY_REQUEST_POS_SIDE_NET": (
            POS_MODE_NET_MODE_DOES_NOT_IMPLY_REQUEST_POS_SIDE_NET_VALUE
        ),
        "LONG_SHORT_IS_NOT_BUY_SELL": LONG_SHORT_IS_NOT_BUY_SELL_VALUE,
        "HISTORICAL_POSMODE_NET_STATUS": HISTORICAL_POSMODE_NET_STATUS,
        "HISTORICAL_POSSIDE_NET_STATUS": HISTORICAL_POSSIDE_NET_STATUS,
        "HISTORICAL_EVIDENCE_PROMOTED_TO_CURRENT_AUTHORITY": (
            HISTORICAL_EVIDENCE_PROMOTED_TO_CURRENT_AUTHORITY
        ),
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "signed_pos": verdict["signed_pos"],
        "TARGET_POSITION_QTY_UNIT": TARGET_POSITION_QTY_UNIT,
        "POS_TO_SZ_UNIT_IDENTITY": POS_TO_SZ_UNIT_IDENTITY,
        "P08_CLOSED": P08_CLOSED,
        "P10_CLOSED": P10_CLOSED,
        "P11_POS_TO_SZ_CLOSED": P11_POS_TO_SZ_CLOSED,
        "P11_TEXT_REWRITTEN": P11_TEXT_REWRITTEN,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT": (
            EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT
        ),
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_POST_COUNT": THIS_GO_POST_COUNT,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "P12_DOES_NOT_GRANT_EXECUTION_READINESS": P12_DOES_NOT_GRANT_EXECUTION_READINESS,
        "P12_DOES_NOT_AUTHORIZE_FLATTEN": P12_DOES_NOT_AUTHORIZE_FLATTEN,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "VENUE_NATIVE_BODY_KEYS": verdict["VENUE_NATIVE_BODY_KEYS"],
    }
    summary = {
        "DOCUMENT_CLASS": "P12_EXECUTION_PREREQUISITE_11_PACKAGE_V1",
        "DOCUMENT_ROLE": "DERIVED_NON_SSOT",
        "OWNER_GO": OWNER_GO,
        "OWNER_GO_CONSUMED": True,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "AUTHORIZED_SCOPE": AUTHORIZED_SCOPE,
        "AUTHORIZED_OPERATION": AUTHORIZED_OPERATION,
        "HOST": AUTHORIZED_HOST,
        "AUTHORIZED_ACCOUNT_UID": AUTHORIZED_ACCOUNT_UID,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE": (
            EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE
        ),
        "P11_PROVEN": P11_PROVEN_VALUE,
        "P11_CLOSED": P11_CLOSED_VALUE,
        "REQUEST_POS_SIDE_POLICY": REQUEST_POS_SIDE_POLICY_VALUE,
        "REQUEST_POS_SIDE": REQUEST_POS_SIDE_VALUE_CURRENT,
        "FLATTEN_ORDER_SIDE_RULE": FLATTEN_ORDER_SIDE_RULE,
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P08_CLOSED": True,
        "P10_CLOSED": True,
        "P11_POS_TO_SZ_CLOSED": True,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT": (
            EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT
        ),
        "GET_REQUEST_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "HTTP_EXCHANGE_COUNT": 0,
        "POST_COUNT": THIS_GO_POST_COUNT,
        "WRITE_REQUEST_COUNT": 0,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "CORE_CHANGED": False,
        "NEW_AUTHORITY_CREATED": False,
        "MERGE_AUTHORIZED": False,
        "P12_DOES_NOT_GRANT_EXECUTION_READINESS": True,
        "P12_DOES_NOT_AUTHORIZE_FLATTEN": True,
        "ATLAS_AUTHORITY": "NONE",
        "LANDSCAPE_AUTHORITY": "NONE",
        "HISTORICAL_EVIDENCE_PROMOTED_TO_CURRENT_AUTHORITY": (
            HISTORICAL_EVIDENCE_PROMOTED_TO_CURRENT_AUTHORITY
        ),
        "HISTORICAL_POSMODE_NET_STATUS": HISTORICAL_POSMODE_NET_STATUS,
        "HISTORICAL_POSSIDE_NET_STATUS": HISTORICAL_POSSIDE_NET_STATUS,
    }
    result: dict[str, Any] = {
        "verdict": verdict,
        "census": census,
        "lineage": lineage,
        "adjudication": adjudication,
        "summary": summary,
    }
    if evidence_root is not None:
        pack = Path(evidence_root) / run_id
        verified = persist_p12_position_side_evidence_v1(
            pack=pack,
            origin_main_sha=origin_main_sha,
            census=census,
            lineage=lineage,
            adjudication=adjudication,
            summary=summary,
        )
        result["EVIDENCE_PACK"] = str(pack)
        result["MANIFEST_VERIFY_RC"] = verified.get("MANIFEST_VERIFY_RC")
        result["EVIDENCE_DIRNAME"] = EVIDENCE_DIRNAME
    return result
