"""Standing constants for EXECUTION_PREREQUISITE_11 position-side / posSide.

Offline CASE_B persist. No GET. No POST. No flatten execute. No Live/Canary
unlock. Does not rewrite account posMode into request posSide. Does not copy
position-row posSide onto the Place Order body.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_p12_execution_prerequisite_11_position_side_posside_v1.contract_v1 import (
    CASE,
    EXECUTION_PREREQUISITE_11_STATUS,
    LONG_SHORT_IS_NOT_BUY_SELL,
    ORDER_SIDE_DOMAIN,
    P11_CLOSED,
    P11_PROVEN,
    POS_MODE_IS_NOT_POSITION_SIDE,
    POS_MODE_NET_MODE_DOES_NOT_IMPLY_REQUEST_POS_SIDE_NET,
    POSITION_ROW_POS_SIDE_IS_NOT_REQUEST_POS_SIDE,
    POSITION_ROW_POS_SIDE_OBSERVED_P08,
    REQUEST_POS_SIDE_POLICY,
    REQUEST_POS_SIDE_VALUE,
)

CAPABILITY_ID = "P12_EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE_V1"
PACKAGE_MARKER = "P12_EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE_V1=true"
OWNER = "ops.section_11_13_5_p12_execution_prerequisite_11_position_side_posside_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p12_execution_prerequisite_11_position_side_posside.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_P11_POSITION_SIDE_POSSIDE_MAXIMUM_SAFE_LEVERAGE_V1"
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF_NO_ALIAS_PROMOTION_V1"
)
WORKPACKAGE_ID = "OKX_EEA_P12_EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE_V1"
THIS_SLICE = "11.13.5.P12"
PREDECESSOR_SLICE = "11.13.5.P11"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_P12"
EXPECTED_ORIGIN_MAIN_SHA = "dec8c5bb2fcd25d0c5bed9d6553af4e10da80601"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE_ADJUDICATE_PERSIST"
AUTHORIZED_SCOPE = "A_P12_EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE"
CANONICAL_EVIDENCE_RUN_ID = "20260904T001300Z"

CASE_VALUE = CASE
EXECUTION_PREREQUISITE_11_POSITION_SIDE_POSSIDE = EXECUTION_PREREQUISITE_11_STATUS
P11_PROVEN_VALUE = P11_PROVEN
P11_CLOSED_VALUE = P11_CLOSED
ORDER_SIDE_DOMAIN_VALUE = tuple(sorted(ORDER_SIDE_DOMAIN))
FLATTEN_ORDER_SIDE_RULE = "SELL_IF_OBSERVED_SIGNED_POS_GT_0_ELSE_BUY"
REQUEST_POS_SIDE_POLICY_VALUE = REQUEST_POS_SIDE_POLICY
REQUEST_POS_SIDE_VALUE_CURRENT = REQUEST_POS_SIDE_VALUE
POSITION_ROW_POS_SIDE_OBSERVED_P08_VALUE = POSITION_ROW_POS_SIDE_OBSERVED_P08
POSITION_ROW_POS_SIDE_IS_NOT_REQUEST_POS_SIDE_VALUE = POSITION_ROW_POS_SIDE_IS_NOT_REQUEST_POS_SIDE
POS_MODE_IS_NOT_POSITION_SIDE_VALUE = POS_MODE_IS_NOT_POSITION_SIDE
POS_MODE_NET_MODE_DOES_NOT_IMPLY_REQUEST_POS_SIDE_NET_VALUE = (
    POS_MODE_NET_MODE_DOES_NOT_IMPLY_REQUEST_POS_SIDE_NET
)
LONG_SHORT_IS_NOT_BUY_SELL_VALUE = LONG_SHORT_IS_NOT_BUY_SELL
HISTORICAL_POSMODE_NET_STATUS = "HISTORICAL_FORENSIC_BINDING_NOT_PROMOTED_TO_REQUEST_POSSIDE"
HISTORICAL_POSSIDE_NET_STATUS = "P08_POSITION_ROW_OBSERVATION_NOT_PROMOTED_TO_REQUEST_POSSIDE"
HISTORICAL_EVIDENCE_PROMOTED_TO_CURRENT_AUTHORITY = False
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_POS_TO_SZ_CLOSED = True
TARGET_POSITION_NONZERO_PROVEN = True
TARGET_POSITION_QTY_NUMERIC = "PASS"
TARGET_POSITION_QTY_UNIT = "PROVEN"
POS_TO_SZ_UNIT_IDENTITY = "PROVEN"
P12_DOES_NOT_GRANT_EXECUTION_READINESS = True
P12_DOES_NOT_AUTHORIZE_FLATTEN = True
P11_TEXT_REWRITTEN = False
EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD_FROM_OBSERVED_POSITION"
)
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_EXECUTION_PREREQUISITE_12_EXACT_FLATTEN_PAYLOAD"
EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT = "PASS"
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
CENSUS_COMPLETE = True
LINEAGE_COMPLETE = True

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_p12_execution_prerequisite_11_position_side_posside_v1"
