"""Static claims for the delayed-zero persist and P7/P9 observation pack."""

from __future__ import annotations

from src.ops.section_11_13_5_g12_canonical_delayed_zero_persist_and_pending_related_observations_v1.constants_v1 import (
    EMPTY_DATA_IS_ZERO,
    FORENSIC_LOCAL_OPS_LOCAL_IS_NOT_CANONICAL,
    MERGE_AUTHORIZED_BY_THIS_PERSIST,
    OWNER_GO,
    POSID_FILTERED_ENVELOPE_DOES_NOT_PROVE_RELATED_COMPLETENESS,
    POST_ALLOWED,
    SECTION_11_14_AUTHORIZED,
    THIS_SLICE,
    WORKPACKAGE_ID,
)

CLAIMS: dict[str, object] = {
    "OWNER_GO": OWNER_GO,
    "THIS_SLICE": THIS_SLICE,
    "WORKPACKAGE_ID": WORKPACKAGE_ID,
    "EMPTY_DATA_IS_ZERO": EMPTY_DATA_IS_ZERO,
    "FORENSIC_LOCAL_OPS_LOCAL_IS_NOT_CANONICAL": FORENSIC_LOCAL_OPS_LOCAL_IS_NOT_CANONICAL,
    "POSID_FILTERED_ENVELOPE_DOES_NOT_PROVE_RELATED_COMPLETENESS": (
        POSID_FILTERED_ENVELOPE_DOES_NOT_PROVE_RELATED_COMPLETENESS
    ),
    "SECTION_11_14_AUTHORIZED": SECTION_11_14_AUTHORIZED,
    "POST_PERFORMED": POST_ALLOWED,
    "MERGE_AUTHORIZED_BY_THIS_PERSIST": MERGE_AUTHORIZED_BY_THIS_PERSIST,
    "SECRET_VALUES_INCLUDED": False,
    "AUTHORITY": "NONE_FOR_EVIDENCE_ARTIFACTS",
}
