"""Constants for Treasury Phase-1 offline contracts.

No network. No productive mutation. Standing Live gates remain false.
"""

from __future__ import annotations

CAPABILITY_ID = "TREASURY_PHASE_1_OFFLINE_CONTRACTS_V1"
PACKAGE_MARKER = "TREASURY_PHASE_1_OFFLINE_CONTRACTS_V1=true"
OWNER = "ops.treasury_phase_1_offline_contracts_v1"
SCHEMA_VERSION = "treasury_phase_1_offline_contract.v1"
CONTRACT_VERSION = "v1"
CANONICAL_SERIALIZATION_VERSION = "treasury_phase_1_canonical_json_v1"

CORE_LOGIC_CHANGE = False
LIVE_AUTHORIZED = False
LIVE_ENABLED = False
LIVE_ARMED = False
WIRE_SEND_PERMITTED = False
SUBMIT_UNLOCKED = False
ORDERS_AUTHORIZED = False
TESTNET_AUTHORIZED = False
RUNTIME_AUTHORIZATION_EFFECT = "NONE"

TREASURY_PHASE_1_STATUS = "CLOSED_OFFLINE_CONTRACTS"
TREASURY_PHASE_2_STATUS = "NOT_STARTED"
PL_TF_001_STATUS = "CLOSED_TYPED_ADMISSION_SEAM"
PL_TF_002_STATUS = "FROZEN_PENDING_NETWORK_EVIDENCE"
VENUE_PERMISSION_UNKNOWN = True
VENUE_PERMISSION_GET_PERFORMED = False
VENUE_IDEMPOTENCY_GUARANTEE = "NOT_PROVEN"
TARGET_AUTHORITY = "NONE"

PRODUCTIVE_DEPOSIT_PATH = False
PRODUCTIVE_WITHDRAWAL_PATH = False
PRODUCTIVE_INTERNAL_TRANSFER_PATH = False
TRANSFER_RECONCILIATION = False
CURRENT_END_TO_END_TREASURY_GATE = False
TREASURY_COMPLETE_PRODUCTIVE_SUBSYSTEM_PROVEN = False

TREASURY_MUTATION_REACHABLE_FROM_TRADING = False
TREASURY_SEPARATION_GATE_WIRED = False
TREASURY_OBSERVER_CAN_AUTHORIZE_MUTATION = False
TREASURY_MUTATION_AUTHORIZED = False
DURABLE_INTENT_BEFORE_REMOTE_MUTATION = True

TREASURY_PHASE_1_CAN_MOVE_FUNDS = False
TREASURY_PHASE_1_CAN_SEND_NETWORK_REQUEST = False
TREASURY_PHASE_1_CAN_WITHDRAW = False
TREASURY_PHASE_1_CAN_INTERNAL_TRANSFER = False
TREASURY_PHASE_1_CAN_GENERATE_DEPOSIT_ADDRESS = False
TREASURY_PHASE_1_CAN_ENABLE_LIVE = False
TREASURY_PHASE_1_CAN_ARM_LIVE = False
TREASURY_PHASE_1_CAN_ENABLE_WIRE = False
TREASURY_PHASE_1_CAN_SUBMIT_ORDER = False
TREASURY_PHASE_1_CAN_MINT_RISK_ADMISSIBLE_CAPITAL = False
TREASURY_PHASE_1_CAN_MINT_TRADING_AUTHORITY = False

OUTCOME_UNKNOWN_IS_FAILURE = False
OUTCOME_UNKNOWN_SAFE_TO_RETRY = False
TERMINAL_VENUE_STATE_IMPLIES_RECONCILED = False
TREASURY_RECONCILED_IMPLIES_RISK_ADMISSIBLE = False
RISK_ADMISSIBLE_GRANTED = False

CAPITAL_ADMISSION_AUTHORITY = "capital_admission_contract_v1"
SECOND_CAPITAL_AUTHORITY_ADDED = False
ECONOMIC_POLICY_INVENTED = False

FORBIDDEN_IMPORT_TOKENS: tuple[str, ...] = (
    "LiveCanaryHttpClientV1",
    "UrllibLiveCanaryTransportV1",
    "construct_live_execution_port_v1",
    "post_entry_order",
    "requests",
    "http.client",
    "urllib.request",
    "enforce_treasury_policy",
)

FORBIDDEN_SECRET_FIELD_MARKERS: tuple[str, ...] = (
    "apikey",
    "api_key",
    "secret",
    "passphrase",
    "password",
    "authorization",
    "privatekey",
    "private_key",
    "signingmaterial",
    "signing_material",
    "recoverycode",
    "recovery_code",
    "rawenv",
    "raw_env",
    "bearer",
    "hmacsecret",
    "okxsecret",
)

INTENT_ID_PATTERN = r"^[A-Za-z0-9._:-]{8,128}$"
MAX_REF_LEN = 128
MAX_ASSET_LEN = 32
