"""Fail-closed constants for the §11.14 GET-only trade-fee refresh."""

from __future__ import annotations

CAPABILITY_ID = (
    "SECTION_11_14_CURRENT_ORIGIN_MAIN_8605BF_GET_ONLY_TRADE_FEE_AND_"
    "STALE_PRETRADE_PREDICATE_REFRESH_V1"
)
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = (
    "section_11_14_current_origin_main_8605bf_get_only_trade_fee_and_"
    "stale_pretrade_predicate_refresh.v1"
)
OWNER = (
    "ops.section_11_14_current_origin_main_8605bf_get_only_trade_fee_and_"
    "stale_pretrade_predicate_refresh_v1"
)
THIS_SLICE = (
    "11.14.CURRENT_ORIGIN_MAIN_8605BF_GET_ONLY_TRADE_FEE_AND_STALE_PRETRADE_PREDICATE_REFRESH"
)
PREDECESSOR_SLICE = (
    "11.14.LIVE_HANDOFF_EXACT_FEE_RESTART_DURABILITY_AND_PRE_EXECUTION_READINESS_CLOSURE"
)
LAST_CANONICALLY_CLOSED_STEP = (
    "SECTION_11_14_CURRENT_ORIGIN_MAIN_8605BF_GET_ONLY_TRADE_FEE_AND_"
    "STALE_PRETRADE_PREDICATE_REFRESH"
)
OWNER_GET_ONLY_GO = (
    "PEAK_TRADE_OWNER_GET_ONLY_GO_SECTION_11_14_CURRENT_ORIGIN_MAIN_8605BF_"
    "GET_ONLY_TRADE_FEE_AND_STALE_PRETRADE_PREDICATE_REFRESH_V1"
)
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_SECTION_11_14_LIVE_HANDOFF_EXACT_FEE_RESTART_DURABILITY_"
    "AND_PRE_EXECUTION_READINESS_CLOSURE_V1"
)
CANONICAL_EVIDENCE_RUN_ID = "20260907T203636Z"
EXPECTED_ORIGIN_MAIN_SHA = "8605bf596ef773419e99157b143befbcb69fa6a7"
EXPECTED_ORIGIN_MAIN_TREE = "e18506952ce968a63d23b67ec1875fa9dd3e60a7"
PREVIOUS_GET_PACK_RUN_ID = "20260907T182140Z"
PREVIOUS_GET_PACK_ORIGIN_MAIN_SHA = "7f8dcf6d120f0ec59bcb932f5f6d1e8a6360b663"

BOUND_INSTRUMENT_ID = "SUI-USD_UM_XPERP-310404"
BOUND_INST_FAMILY = "SUI-USD_UM_XPERP"
BOUND_INST_TYPE = "FUTURES"
BOUND_VENUE = "eea.okx.com"
BOUND_REST_BASE = "https://eea.okx.com"
TRADE_FEE_QUERY = "/api/v5/account/trade-fee?instType=FUTURES&instFamily=SUI-USD_UM_XPERP"

GET_PACK_RELATIVE_ROOT = (
    "evidence/ops/section_11_14_live_handoff_current_origin_main_bound_"
    "get_only_pretrade_readiness_v1"
)
EVIDENCE_RELATIVE_ROOT = (
    "evidence/ops/section_11_14_current_origin_main_8605bf_get_only_"
    "trade_fee_and_stale_pretrade_predicate_refresh_v1"
)

EXACT_OKX_FEE_FORMULA_STATUS = "UNPROVEN"
EXACT_OKX_FEE_FORMULA_UNPROVEN = True
OWNER_EXECUTION_AUTHORIZED = False
SECTION_11_14_RUNTIME_EXECUTION_AUTHORIZED = False
LIVE_RESTART_RECONSTRUCTED = False
HOST_CRASH_DURABILITY_STATUS = "UNPROVEN"
PROCESS_CRASH_DURABILITY_STATUS = "STATIC_MODEL_SUPPORTED_EMPIRICAL_UNPROVEN"
CANARY_AUTHORIZED_EXACT_FIELD = "INDETERMINATE_ABSENT"
POST_ALLOWED_EXACT_FIELD = "INDETERMINATE_ABSENT"
EARLIEST_LADDER_BLOCKER = "LIVE_RESTART_RECONSTRUCTED"
EARLIEST_UNRESOLVED_AUTHORITY_PREDICATE = "OWNER_EXECUTION_AUTHORIZED"
NEXT_OWNER_GO_REQUIRED = "OWNER_MERGE_GO_THEN_SEPARATE_OWNER_EXECUTION_GO"
PROPOSED_NEXT_SLICE = (
    "SECTION_11_14_LIVE_HANDOFF_EXACT_SINGLE_LIVE_FILL_REQUIRES_SEPARATE_OWNER_EXECUTION_GO_V1"
)

SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
ADJUDICATION_FILENAME = "ADJUDICATION.json"
TRADE_FEE_ADJUDICATION_FILENAME = "TRADE_FEE_ADJUDICATION.json"
PREDICATE_TABLE_FILENAME = "PREDICATE_TABLE.json"
BOUNDED_FEE_ENVELOPE_FILENAME = "BOUNDED_FEE_ENVELOPE.json"
SAFETY_FILENAME = "SAFETY.json"
BASELINE_FILENAME = "BASELINE.json"
NON_EXECUTION_FILENAME = "NON_EXECUTION.json"
LINEAGE_FILENAME = "LINEAGE.json"
CENSUS_FILENAME = "CENSUS.json"
MANIFEST_FILENAME = "MANIFEST.sha256"
