"""Standing constants for the P10 TARGET_POSITION_QTY unit forensic persist.

Offline census and fail-closed adjudication only. Does not GET, POST,
flatten, mutate live gates, or promote alias names into a proven unit.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.execution_prerequisite_08_cluster_contract_v1 import (
    UNIT_CHAIN_VERDICT,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.venue_contract_count_v1 import (
    ORDER_PLAN_QTY_DOMAIN,
    ORDER_PLAN_QTY_UNIT,
    SUI_OPERATIVE_ORDER_SZ,
    SUI_OPERATIVE_ORDER_SZ_UNIT,
)

CAPABILITY_ID = "P10_TARGET_POSITION_QTY_UNIT_FORENSIC_ADJUDICATION_PERSIST_V1"
PACKAGE_MARKER = "P10_TARGET_POSITION_QTY_UNIT_FORENSIC_ADJUDICATION_PERSIST_V1=true"
OWNER = "ops.section_11_13_5_p10_target_position_qty_unit_forensic_adjudicate_persist_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p10_target_position_qty_unit_forensic_adjudication_persist.v1"
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT"
    "_FORENSIC_ADJUDICATE_OFFLINE_PERSIST_PR_V1"
)
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_P08_NONZERO_POSITION_ADJUDICATE_PERSIST_CLOSE_AND_PR_MAX_LEVERAGE_V1"
)
WORKPACKAGE_ID = "OKX_EEA_P10_TARGET_POSITION_QTY_UNIT_FORENSIC_ADJUDICATION_PERSIST_V1"
THIS_SLICE = "11.13.5.P10"
PREDECESSOR_SLICE = "11.13.5.P08"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_P10"
EXPECTED_ORIGIN_MAIN_SHA = "aed88b91da7fe61f8bbd1fc5a51357729a678c72"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_FORENSIC_CENSUS_AND_ADJUDICATION_OF_TARGET_POSITION_QTY_UNIT"
AUTHORIZED_SCOPE = "A_P10_TARGET_POSITION_QTY_UNIT_FORENSIC_ADJUDICATE_PERSIST_OFFLINE"
CANONICAL_EVIDENCE_RUN_ID = "20260903T231500Z"

TARGET_POSITION_QTY_UNIT = "UNPROVEN"
CURRENT_UNIT_CONTRACT = "UNPROVEN"
QTY_UNIT_CENSUS_COMPLETE = True
QTY_UNIT_LINEAGE_COMPLETE = True
EARLIEST_MISSING_QTY_UNIT_PROOF = "POS_TO_SZ_UNIT_IDENTITY"
EARLIEST_UNRESOLVED_DEPENDENCY = "EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT"
NEXT_AUTHORITY_BOUNDARY = (
    "SEPARATE_OWNER_GO_FOR_POS_TO_SZ_UNIT_IDENTITY_INDEPENDENT_PROOF_NO_ALIAS_PROMOTION"
)
CONFLICT_COUNT = 0
UNIT_CHAIN_VERDICT_CURRENT = UNIT_CHAIN_VERDICT
ORDER_PLAN_QTY_UNIT_CURRENT = ORDER_PLAN_QTY_UNIT
ORDER_PLAN_QTY_DOMAIN_CURRENT = ORDER_PLAN_QTY_DOMAIN
SUI_OPERATIVE_ORDER_SZ_CURRENT = SUI_OPERATIVE_ORDER_SZ
SUI_OPERATIVE_ORDER_SZ_UNIT_CURRENT = SUI_OPERATIVE_ORDER_SZ_UNIT
ORDER_PLAN_QTY_IS_NOT_TARGET_POSITION_QTY = True
SUI_OPERATIVE_ORDER_SZ_IS_NOT_TARGET_POSITION_QTY = True
ONE_CONTRACT_EQUALS_ONE_SUI = False
NUMERIC_POS_EQUALS_SZ_IS_NOT_UNIT_PROOF = True
MINSZ_1_IS_NOT_UNIT_PROOF = True
CTVAL_1_IS_NOT_UNIT_PROOF = True
HISTORICAL_ORDER_PLAN_VENUE_CONTRACT_COUNT_IS_NOT_CURRENT_TARGET_POSITION_QTY_UNIT = True
HISTORICAL_BTC_DENOMINATION_IS_NOT_CURRENT_SUI_XPERP_TARGET_POSITION_QTY_UNIT = True
STEP_29P_IS_NOT_TARGET_POSITION_QTY_PRODUCER = True
STEP_29Q_IS_NOT_TARGET_POSITION_QTY_PRODUCER = True
SIMULATED_EXECUTION_PORT_IS_NOT_TARGET_POSITION_QTY_PRODUCER = True
P08_CLOSED = True
TARGET_POSITION_NONZERO_PROVEN = True
TARGET_POSITION_QTY_NUMERIC = "PASS"
P10_DOES_NOT_GRANT_EXECUTION_READINESS = True
P10_DOES_NOT_PROVE_TARGET_POSITION_QTY_UNIT = True
IMPLICIT_PASSTHROUGH_PRESENT = True
IMPLICIT_PASSTHROUGH_IS_NOT_UNIT_PROOF = True
ORIGINAL_WIRE_BODY_BYTES_AVAILABLE = False
POSCCY_PRESENT_IN_AUTHORIZED_P08_CAPTURE = False

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_p10_target_position_qty_unit_forensic_adjudicate_persist_v1"
FORBIDDEN_PROMOTION_ALIASES: tuple[str, ...] = (
    "qty",
    "sz",
    "size",
    "contracts",
    "contract count",
    "base amount",
    "quote amount",
    "notional",
    "position size",
    ORDER_PLAN_QTY_UNIT,
    ORDER_PLAN_QTY_DOMAIN,
    SUI_OPERATIVE_ORDER_SZ_UNIT,
    "VENUE_CONTRACT_COUNT",
    "CONTRACTS_SZ",
    "minSz",
    "lotSz",
    "ctVal",
    "ctValCcy",
)

PROVEN_UNIT_TOKENS: frozenset[str] = frozenset(
    {
        "PROVEN",
        "contracts",
        "CONTRACTS_SZ",
        "VENUE_CONTRACT_COUNT",
        "base",
        "quote",
        "notional",
        "dimensionless",
    }
)
