"""Standing constants for the post-Z2DS one-shot 50110 egress-capture GET.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1, and
build_okx_live_canary_auth_headers_v1. Does not mint a second HTTP client,
signer, SecretRef owner, live/testnet/canary authority, or mutation path.
Does not consume the already-authorized whitelist GO.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    ENDPOINT_ACCOUNT_CONFIG,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)

CAPABILITY_ID = "POST_Z2DS_PRIVATE_GET_CURRENT_50110_EGRESS_CAPTURE_V1"
PACKAGE_MARKER = "POST_Z2DS_PRIVATE_GET_CURRENT_50110_EGRESS_CAPTURE_V1=true"
OWNER = "ops.section_11_13_5_post_z2ds_private_get_current_50110_egress_capture_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "post_z2ds_private_get_current_50110_egress_capture.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_OKX_EEA_PRIVATE_GET_CURRENT_50110_EGRESS_CAPTURE_V1"
WHITELIST_GO_NOT_CONSUMED = (
    "PEAK_TRADE_OWNER_GO_OKX_EEA_EXTERNAL_IP_WHITELIST_MINIMUM_ADD_CURRENT_50110_EGRESS_V1"
)
WORKPACKAGE_ID = "OKX_EEA_PRIVATE_GET_CURRENT_50110_EGRESS_CAPTURE_V1"
THIS_SLICE = "11.13.5.POST_Z2DS_50110_EGRESS_CAPTURE"
PREDECESSOR_SLICE = "11.13.5.Z2DS"
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "36e8d281d91c0423a22da3bfded5c6be803b17b5"
AUTHORIZED_HOST = "eea.okx.com"

AUTHORIZED_OPERATION = "EXACTLY_ONE_ACTUAL_AUTHENTICATED_READ_ONLY_GET_50110_EGRESS_CAPTURE"
AUTHORIZED_ENDPOINT = "GET /api/v5/account/config"
MAX_NETWORK_REQUEST_COUNT = 1
MAX_HTTP_EXCHANGE_COUNT = 1
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
SECOND_GET_ALLOWED = False
ALTERNATE_ENDPOINT_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
PUBLIC_GET_ALLOWED = False
P08_OBSERVATION_ALLOWED = False
P08_CLOSE_ALLOWED = False
FUNDING_ALLOWED = False
HISTORICAL_IP_FALLBACK_ALLOWED = False
HISTORICAL_Z2DS_IP_IS_BINDING = False

ENDPOINT = ENDPOINT_ACCOUNT_CONFIG
ENDPOINT_METHOD = "GET"
FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/positions",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET = False

EVIDENCE_DIRNAME = "section_11_13_5_post_z2ds_private_get_current_50110_egress_capture_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)
NEXT_AUTHORITY_BOUNDARY = (
    "EXISTING_WHITELIST_GO_MAY_USE_THIS_50110_ONLY_IF_STILL_PROVABLY_CURRENT_AT_MUTATION_TIME"
)
RESULT_CLASS_401_50110 = "HTTP_401_OKX_50110"
RESULT_CLASS_200_OKX_0 = "HTTP_200_OKX_0"
RESULT_CLASS_OTHER = "OTHER_READ_ONLY_FAILURE"
