"""Constants for CAPABILITY_11_5 testnet restart, recovery and kill-switch closure."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_11_5_TESTNET_RESTART_RECOVERY_AND_KILL_SWITCH_CLOSURE_V1"
PACKAGE_MARKER = "CAPABILITY_11_5_TESTNET_RESTART_RECOVERY_AND_KILL_SWITCH_CLOSURE_V1=true"
OWNER = "ops.capability_11_5_testnet_restart_recovery_and_kill_switch_closure_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "capability_11_5_testnet_restart_recovery_and_kill_switch_closure.v1"
PRODUCER_VERSION = "capability_11_5_testnet_restart_recovery_and_kill_switch_closure.v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID_11_1 = "CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1"
PREDECESSOR_OWNER_11_1 = "ops.capability_11_1_execution_domain_and_order_lifecycle_contracts_v1"
PREDECESSOR_CAPABILITY_ID_11_2 = (
    "CAPABILITY_11_2_CREDENTIAL_AUTHORIZATION_AND_ACCOUNT_IDENTITY_BOUNDARY_V1"
)
PREDECESSOR_OWNER_11_2 = (
    "ops.capability_11_2_credential_authorization_and_account_identity_boundary_v1"
)
PREDECESSOR_CAPABILITY_ID_11_3 = (
    "CAPABILITY_11_3_PRIVATE_READONLY_VENUE_INTEGRATION_AND_RECONCILIATION_V1"
)
PREDECESSOR_OWNER_11_3 = (
    "ops.capability_11_3_private_readonly_venue_integration_and_reconciliation_v1"
)
PREDECESSOR_CAPABILITY_ID_11_4 = (
    "CAPABILITY_11_4_TESTNET_EXECUTION_ADAPTER_AND_LIFECYCLE_CLOSURE_V1"
)
PREDECESSOR_OWNER_11_4 = "ops.capability_11_4_testnet_execution_adapter_and_lifecycle_closure_v1"

# Hard safety bindings (contracts/scaffolding only; non-authorizing).
CORE_LOGIC_CHANGE = False
CORE_LOGIC_CHANGE_ALLOWED = False
ACTIVATION_STATE = "not_activated"
ACTIVATION_CHANGED = False
RUNTIME_ACTIVATED = False
LIVE_TRADING_ALLOWED = False
TESTNET_ALLOWED = False
PAPER_EXCHANGE_ORDERS_ALLOWED = False
EXCHANGE_CREDENTIAL_USE_ALLOWED = False
REAL_CAPITAL_MOVEMENT_ALLOWED = False
NETWORK_SESSION_ALLOWED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
RULESET_MUTATION_ALLOWED = False
NOTION_MUTATION_ALLOWED = False

TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False
EXCHANGE_CREDENTIAL_USE_AUTHORIZED = False
REAL_CAPITAL_MOVEMENT_AUTHORIZED = False
OWNER_GO_REQUIRED_FOR_EACH_ACTIVATION = True

LIVE_PATH_CHANGED = False
TESTNET_PATH_CHANGED = False
ORDER_PATH_CHANGED = False
EXCHANGE_CREDENTIAL_PATH_CHANGED = False
NETWORK_SESSION_STARTED = False

VOLATILITY_NUMERIC_MAX_AGE_ENFORCING = False
NUMERIC_MAX_AGE_EFFECT = "DIAGNOSTIC_ONLY"

# Cap 11.1 contracts that must not be weakened.
CAPABILITY_11_1_FAIL_CLOSED_RETAINED = True
CAPABILITY_11_1_IDEMPOTENCY_RETAINED = True
CAPABILITY_11_1_UNKNOWN_SEMANTICS_RETAINED = True
CAPABILITY_11_1_LIFECYCLE_RETAINED = True
CAPABILITY_11_1_AUDIT_CONTRACTS_RETAINED = True
CAPABILITY_11_1_ANTI_CORRUPTION_RETAINED = True
CAPABILITY_11_1_JOURNALING_RETAINED = True

# Cap 11.2 contracts that must not be weakened.
CAPABILITY_11_2_CREDENTIAL_BOUNDARY_RETAINED = True
CAPABILITY_11_2_AUTHORIZATION_BOUNDARY_RETAINED = True
CAPABILITY_11_2_ACCOUNT_IDENTITY_BOUNDARY_RETAINED = True
CAPABILITY_11_2_NO_CREDENTIAL_LOAD_RETAINED = True
CAPABILITY_11_2_NO_AUTH_CONSUMPTION_RETAINED = True

# Cap 11.3 contracts that must not be weakened / activated.
CAPABILITY_11_3_PRIVATE_READONLY_BOUNDARY_RETAINED = True
CAPABILITY_11_3_RECONCILIATION_HIERARCHY_RETAINED = True
CAPABILITY_11_3_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_3_NO_NETWORK_FETCH_RETAINED = True
CAPABILITY_11_3_NO_CREDENTIAL_LOAD_RETAINED = True

# Cap 11.4 contracts that must not be weakened / activated.
CAPABILITY_11_4_TESTNET_ADAPTER_BOUNDARY_RETAINED = True
CAPABILITY_11_4_LIFECYCLE_CLOSURE_RETAINED = True
CAPABILITY_11_4_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_4_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_4_NO_NETWORK_SESSION_RETAINED = True

# Reachability claims for Cap 11.5 (contracts only — no real Testnet execution).
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
EXCHANGE_CREDENTIAL_ACCESS_REACHABLE = False
REAL_CAPITAL_MOVEMENT_REACHABLE = False
PRIVATE_READONLY_NETWORK_REACHABLE = False
PRIVATE_READONLY_VENUE_INTEGRATION_ACTIVATED = False
CREDENTIAL_PLAINTEXT_LOADED = False
CREDENTIAL_LOAD_PERFORMED_IN_CAPABILITY_11_5 = False
TESTNET_EXECUTION_ADAPTER_ACTIVATED = False
TESTNET_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_5 = False
TESTNET_NETWORK_SESSION_STARTED_IN_CAPABILITY_11_5 = False

# Cap 11.5 contract surface claims (bound, not activated, not proven).
UNKNOWN_SUBMIT_RECONNECT_RECOVERY_CONTRACT_BOUND = True
UNKNOWN_SUBMIT_RECONNECT_RECOVERY_CONTRACT_ACTIVATED = False
RESTART_WITH_OPEN_ORDER_POSITION_CONTRACT_BOUND = True
RESTART_WITH_OPEN_ORDER_POSITION_CONTRACT_ACTIVATED = False
KILL_SWITCH_AND_EMERGENCY_CONTROL_CONTRACT_BOUND = True
KILL_SWITCH_CONTRACT_ACTIVATED = False
AUTONOMOUS_RECOVERY_DEGRADATION_CONTRACT_BOUND = True
AUTONOMOUS_RECOVERY_CONTRACT_ACTIVATED = False
TESTNET_RESTART_RECOVERY_KILL_SWITCH_FIXTURE_ONLY = True
CAPABILITY_11_5_RESTART_RECOVERY_KILL_SWITCH_STARTED = True

# Cap 11.5 does NOT claim real Testnet proving-ground closure (§11.12 closure flags).
TESTNET_ORDER_LIFECYCLE_PROVEN = False
TESTNET_RECONCILIATION_PROVEN = False
TESTNET_RESTART_PROVEN = False
TESTNET_UNKNOWN_SUBMIT_RECOVERY_PROVEN = False
TESTNET_DUPLICATE_ORDER_PREVENTION_PROVEN = False
TESTNET_KILL_SWITCH_PROVEN = False
TESTNET_AUTONOMOUS_RECOVERY_PROVEN = False
TESTNET_EVIDENCE_VERIFIED = False

# Explicit Cap 11.6+ surfaces remain out of scope / unbound.
CAPABILITY_11_6_LONG_RUNNING_AUTONOMOUS_TESTNET_STARTED = False
LONG_RUNNING_AUTONOMOUS_TESTNET_CAMPAIGN_ACTIVATED = False

# Kill-switch properties from §11.9 (contract declarations; not activated).
KILL_SWITCH_PERSISTED = True
KILL_SWITCH_FAIL_CLOSED = True
KILL_SWITCH_CHECKED_BEFORE_EVERY_SIDE_EFFECT = True
KILL_SWITCH_SURVIVES_RESTART = True
KILL_SWITCH_CANNOT_BE_CLEARED_BY_RUNTIME = True
OWNER_AUTHORITY_REQUIRED_TO_CLEAR = True
CANCEL_ALL_PATH_INDEPENDENT_OF_ALPHA = True
EXIT_OR_REDUCE_POLICY_INDEPENDENT_OF_ALPHA = True

# Operating / degradation states from §11.8.
OPERATING_STATES: tuple[str, ...] = (
    "OFF",
    "PREFLIGHT",
    "RECONCILING",
    "READY",
    "ACTIVE",
    "DEGRADED_NO_NEW_ENTRY",
    "EXIT_ONLY",
    "REDUCE_ONLY",
    "CANCEL_ALL",
    "RECOVERING",
    "HALTED",
    "OWNER_LOCKED",
)

EMERGENCY_COMMANDS: tuple[str, ...] = (
    "BLOCK_NEW_ENTRY",
    "EXIT_ONLY",
    "REDUCE_ONLY",
    "CANCEL_ALL",
    "HALT_AFTER_CANCEL",
    "PERSISTENT_KILL",
)

RECOVERY_FORBIDDEN_CONDITIONS: tuple[str, ...] = (
    "credential_scope_mismatch",
    "repository_or_config_integrity_mismatch",
    "unknown_account_identity",
    "unexplained_position_divergence",
    "kill_switch_activation",
    "repeated_duplicate_order_evidence",
    "risk_limit_breach_requiring_limit_change",
    "evidence_chain_corruption_affecting_economic_truth",
    "unauthorized_mode_or_venue_transition",
)

UNKNOWN_SUBMIT_RECOVERY_PATHS: tuple[str, ...] = (
    "unknown_submit_query_before_retry",
    "reconnect_after_unknown_submit",
)

RESTART_RECOVERY_PATHS: tuple[str, ...] = (
    "restart_with_open_order",
    "restart_with_open_position",
)

UNKNOWN_SUBMIT_RECONNECT_RECOVERY_OWNER = OWNER
RESTART_WITH_OPEN_ORDER_POSITION_OWNER = OWNER
KILL_SWITCH_AND_EMERGENCY_CONTROL_OWNER = OWNER
AUTONOMOUS_RECOVERY_DEGRADATION_OWNER = OWNER

EVIDENCE_DIRNAME = "capability_11_5_testnet_restart_recovery_and_kill_switch_closure_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
