"""Constants for productive Pure-Stack display-decision host binding.

CORE_LOGIC_CHANGE=false
TRADING_LOGIC_CHANGE=false
DASHBOARD_AUTHORITY_EFFECT=NONE
RESULTV1_MAPPING_AUTHORIZED=false
FIXTURE_FALLBACK_AUTHORIZED=false
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_PRODUCTIVE_PURE_STACK_DISPLAY_DECISION_HOST_BINDING_V1"
PACKAGE_MARKER = "PRODUCTIVE_PURE_STACK_DISPLAY_DECISION_HOST_BINDING_V1=true"
OWNER = "ops.productive_pure_stack_display_decision_host_binding_v1"
SCHEMA_VERSION = "productive_pure_stack_display_decision_bundle.v1"
BUNDLE_STATE_VERSION = "v1"
PRODUCER_VERSION = SCHEMA_VERSION

AUTHORITY_EFFECT = "NONE"
DASHBOARD_AUTHORITY_EFFECT = "NONE"
DASHBOARD_ROLE = "READ_ONLY_CONSUMER"

STATUS_BLOCKED_CANONICAL_INPUT_AUTHORITY_ABSENT = "BLOCKED_CANONICAL_INPUT_AUTHORITY_ABSENT"
STATUS_BUNDLE_READY = "PURE_STACK_DISPLAY_DECISION_BUNDLE_READY"
STATUS_TRANSITION_PASSTHROUGH_ONLY = "TRANSITION_DECISION_PASSTHROUGH_ONLY"

BUNDLE_FILENAME = "pure_stack_display_decision_bundle.v1.json"
CAPITAL_SLOT_STATE_FILENAME = "capital_slot_state.v1.json"

# Explicit authority inventory — productive host has no ratified config/state
# owners for these Pure-Stack display inputs (forensic discovery @ HEAD).
INPUT_AUTHORITY_FUTURES_INPUT_SNAPSHOT = False
INPUT_AUTHORITY_SURVIVAL_ENVELOPE = False
INPUT_AUTHORITY_SUITABILITY_PROJECTION = False
INPUT_AUTHORITY_CAPITAL_SLOT_CONFIG = False
INPUT_AUTHORITY_CAPITAL_SLOT_STATE_INIT = False
# TransitionDecision is produced by transition_state inside the sole trading
# authority path; passthrough of the identical object is authorized.
INPUT_AUTHORITY_TRANSITION_DECISION_PASSTHROUGH = True

RESULTV1_MAPPING_AUTHORIZED = False
FIXTURE_FALLBACK_AUTHORIZED = False
SCENARIO_DEFAULT_AUTHORIZED = False
WEBUI_DATA_AUTHORIZED = False

LIVE_ORDERS = False
TESTNET_ORDERS = False
PAPER_EXCHANGE_ORDERS = False
EXCHANGE_CREDENTIAL_USE = False
REAL_CAPITAL_MOVEMENT = False
