"""Assemble the P25 EXECUTION_PREREQUISITE_25 no-additional-owner-decision persist pack."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_13_5_p25_execution_prerequisite_25_no_additional_owner_decision_v1.adjudicate_v1 import (
    adjudicate_execution_prerequisite_25_no_additional_owner_decision_v1,
)
from src.ops.section_11_13_5_p25_execution_prerequisite_25_no_additional_owner_decision_v1.constants_v1 import (
    AUTHORIZED_ACCOUNT_UID,
    AUTHORIZED_HOST,
    AUTHORIZED_OPERATION,
    AUTHORIZED_SCOPE,
    CANONICAL_EVIDENCE_RUN_ID,
    CASE_VALUE,
    CONFLICT_COUNT,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED,
    EXPECTED_ORIGIN_MAIN_SHA,
    FAIL_CLOSED_IF_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE,
    LAST_CANONICALLY_CLOSED_STEP,
    NAMED_REMAINING_HIGHER_AUTHORITY,
    NEXT_AUTHORITY_BOUNDARY,
    OWNER_GO,
    P08_CLOSED,
    P10_CLOSED,
    P11_CLOSED,
    P12_CLOSED,
    P13_CLOSED,
    P16_CLOSED,
    P16_TEXT_REWRITTEN_VALUE,
    P20_CLOSED,
    P20_TEXT_REWRITTEN_VALUE,
    P25_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
    P25_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
    P25_DOES_NOT_AUTHORIZE_SEND_TIME_PASS_VALUE,
    P25_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
    P25_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
    P25_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
    P25_MECHANISM_IMPLEMENTED,
    P25_NAMED_CONTRACT_CLOSED,
    P25_RUNTIME_RESIDUAL,
    PREDECESSOR_SLICE,
    PRIOR_OWNER_GO,
    PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED_VALUE,
    PREREQUISITE_25_NETWORK_SESSION_AUTHORIZED_VALUE,
    PREREQUISITE_25_SEND_TIME_REOBSERVATION_PROVEN_VALUE,
    PRIVATE_AUTH_USED,
    PUBLIC_SPEC_RETRIEVAL_PERFORMED,
    RUNTIME_GET_PERFORMED,
    RUNTIME_GET_REQUIRED,
    TARGET_INSTRUMENT_ID,
    THIS_GO_GET_COUNT,
    THIS_GO_POST_COUNT,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.section_11_13_5_p25_execution_prerequisite_25_no_additional_owner_decision_v1.persist_v1 import (
    persist_p25_no_additional_owner_decision_evidence_v1,
)


class P25NoAdditionalOwnerDecisionAssembleError(RuntimeError):
    """Fail-closed assemble violation."""


def assemble_p25_execution_prerequisite_25_no_additional_owner_decision_v1(
    *,
    origin_main_sha: str,
    evidence_root: Path | None = None,
    run_id: str = CANONICAL_EVIDENCE_RUN_ID,
) -> dict[str, Any]:
    """Build and optionally persist prerequisite 25. No GET. No POST."""
    if str(origin_main_sha or "").strip() != EXPECTED_ORIGIN_MAIN_SHA:
        raise P25NoAdditionalOwnerDecisionAssembleError("ORIGIN_MAIN_SHA_MISMATCH")
    verdict = adjudicate_execution_prerequisite_25_no_additional_owner_decision_v1(
        origin_main_sha=origin_main_sha
    )
    if (
        verdict["EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED"]
        != "PASS_OFFLINE_CONTRACT"
    ):
        raise P25NoAdditionalOwnerDecisionAssembleError(
            "PREREQUISITE_25_MUST_BE_PASS_OFFLINE_CONTRACT"
        )
    if verdict["PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED"] is True:
        raise P25NoAdditionalOwnerDecisionAssembleError("FLATTEN_EXECUTE_MUST_REMAIN_UNAUTHORIZED")
    census = {
        "DOCUMENT_CLASS": "P25_EXECUTION_PREREQUISITE_25_CENSUS_V1",
        "DOCUMENT_ROLE": "FORENSIC_CENSUS_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "SEAM_COUNT": verdict["CENSUS"]["SEAM_COUNT"],
        "EPISTEMIC_CLASS_COUNTS": verdict["CENSUS"]["EPISTEMIC_CLASS_COUNTS"],
        "PROVEN_SEAMS": verdict["CENSUS"]["PROVEN_SEAMS"],
        "NOT_PROMOTED_SEAMS": verdict["CENSUS"]["NOT_PROMOTED_SEAMS"],
        "NAMED_REMAINING_HIGHER_AUTHORITY": list(NAMED_REMAINING_HIGHER_AUTHORITY),
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
    }
    lineage = {
        "DOCUMENT_CLASS": "P25_EXECUTION_PREREQUISITE_25_LINEAGE_V1",
        "DOCUMENT_ROLE": "FORENSIC_LINEAGE_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "LINEAGE_FIELD_NAMES": verdict["CENSUS"]["LINEAGE_FIELD_NAMES"],
        "SEAMS": verdict["LINEAGE"],
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
    }
    adjudication = {
        "DOCUMENT_CLASS": "P25_EXECUTION_PREREQUISITE_25_ADJUDICATION_V1",
        "DOCUMENT_ROLE": "INTERPRETATION_NOT_RAW_WIRE_NOT_SSOT",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED": (
            EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED
        ),
        "P25_NAMED_NO_ADDITIONAL_OWNER_DECISION_CONTRACT_CLOSED": P25_NAMED_CONTRACT_CLOSED,
        "P25_EXHAUSTION_GATE_IMPLEMENTED": P25_MECHANISM_IMPLEMENTED,
        "PREREQUISITE_25_SEND_TIME_REOBSERVATION_PROVEN": (
            PREREQUISITE_25_SEND_TIME_REOBSERVATION_PROVEN_VALUE
        ),
        "PREREQUISITE_25_NETWORK_SESSION_AUTHORIZED": (
            PREREQUISITE_25_NETWORK_SESSION_AUTHORIZED_VALUE
        ),
        "PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED": (
            PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED_VALUE
        ),
        "NAMED_REMAINING_HIGHER_AUTHORITY": list(NAMED_REMAINING_HIGHER_AUTHORITY),
        "ADDITIONAL_OWNER_DECISIONS": [],
        "OFFLINE_CONTRACT_PROOF_CLASS": verdict["OFFLINE_CONTRACT_PROOF_CLASS"],
        "STRUCTURAL_ALLOW_IS_NOT_RUNTIME_MUTATION": True,
        "STRUCTURAL_ALLOW_IS_NOT_WIRE_SEND": True,
        "FAIL_CLOSED_STATUS": verdict["FAIL_CLOSED_STATUS"],
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P08_CLOSED": P08_CLOSED,
        "P10_CLOSED": P10_CLOSED,
        "P11_CLOSED": P11_CLOSED,
        "P12_CLOSED": P12_CLOSED,
        "P13_CLOSED": P13_CLOSED,
        "P16_CLOSED": P16_CLOSED,
        "P20_CLOSED": P20_CLOSED,
        "P16_TEXT_REWRITTEN": P16_TEXT_REWRITTEN_VALUE,
        "P20_TEXT_REWRITTEN": P20_TEXT_REWRITTEN_VALUE,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "P25_RUNTIME_RESIDUAL": P25_RUNTIME_RESIDUAL,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_POST_COUNT": THIS_GO_POST_COUNT,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "P25_DOES_NOT_GRANT_EXECUTION_READINESS": P25_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
        "P25_DOES_NOT_AUTHORIZE_FLATTEN": P25_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
        "P25_DOES_NOT_SET_LIVE_AUTHORIZED": P25_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
        "P25_DOES_NOT_ISSUE_RUNTIME_PERMIT": P25_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
        "P25_DOES_NOT_AUTHORIZE_NETWORK_SESSION": P25_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
        "P25_DOES_NOT_AUTHORIZE_SEND_TIME_PASS": P25_DOES_NOT_AUTHORIZE_SEND_TIME_PASS_VALUE,
        "FAIL_CLOSED_IF_PREREQUISITE_25_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE": (
            FAIL_CLOSED_IF_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE
        ),
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "NETWORK_SESSION_AUTHORIZED_DEFAULT": False,
        "IMPLEMENTATION_GO_FORBIDDEN_AS_FLATTEN_EXECUTE": True,
        "MISSING_P16_DENIES": True,
        "UNPROVEN_P16_DENIES": True,
        "MISSING_P20_DENIES": True,
        "UNPROVEN_P20_DENIES": True,
        "ADDITIONAL_OWNER_DECISION_DENIES": True,
        "REMAINING_SET_MISMATCH_DENIES": True,
        "GLOBAL_LIVE_AUTHORIZED_SUBSTITUTE_DENIES": True,
        "RUNTIME_PERMIT_CLAIM_DENIES": True,
        "FLATTEN_EXECUTE_CLAIM_DENIES": True,
        "NETWORK_SESSION_CLAIM_DENIES": True,
        "POST_CLAIM_DENIES": True,
        "GET_CLAIM_DENIES": True,
        "IMPLEMENTATION_GO_AS_EXECUTE_DENIES": True,
        "WRONG_INSTRUMENT_DENIES": True,
        "LINEAGE_MISMATCH_DENIES": True,
        "CENSUS": verdict["CENSUS"],
        "LINEAGE": verdict["LINEAGE"],
        "WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY": verdict["WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY"],
    }
    summary = {
        "DOCUMENT_CLASS": "P25_EXECUTION_PREREQUISITE_25_PACKAGE_V1",
        "DOCUMENT_ROLE": "DERIVED_NON_SSOT",
        "OWNER_GO": OWNER_GO,
        "OWNER_GO_CONSUMED": True,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "AUTHORIZED_SCOPE": AUTHORIZED_SCOPE,
        "AUTHORIZED_OPERATION": AUTHORIZED_OPERATION,
        "HOST": AUTHORIZED_HOST,
        "AUTHORIZED_ACCOUNT_UID": AUTHORIZED_ACCOUNT_UID,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED": (
            EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED
        ),
        "P25_NAMED_NO_ADDITIONAL_OWNER_DECISION_CONTRACT_CLOSED": P25_NAMED_CONTRACT_CLOSED,
        "PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED": False,
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P20_CLOSED": True,
        "P20_TEXT_REWRITTEN": False,
        "P16_CLOSED": True,
        "P16_TEXT_REWRITTEN": False,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "P25_RUNTIME_RESIDUAL": P25_RUNTIME_RESIDUAL,
        "GET_REQUEST_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "HTTP_EXCHANGE_COUNT": 0,
        "POST_COUNT": THIS_GO_POST_COUNT,
        "WRITE_REQUEST_COUNT": 0,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "PRIVATE_AUTH_USED": False,
        "LIVE_AUTHORIZED": False,
        "CANARY_AUTHORIZED": False,
        "SUBMIT_UNLOCKED": False,
        "LIVE_ENABLED": False,
        "LIVE_ARMED": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
        "P25_DOES_NOT_GRANT_EXECUTION_READINESS": True,
        "EXECUTION_READY": False,
        "ATLAS_AUTHORITY": "NONE",
        "LANDSCAPE_AUTHORITY": "NONE",
    }
    result: dict[str, Any] = {
        "verdict": verdict,
        "census": census,
        "lineage": lineage,
        "adjudication": adjudication,
        "summary": summary,
    }
    if evidence_root is not None:
        pack = Path(evidence_root) / run_id
        verified = persist_p25_no_additional_owner_decision_evidence_v1(
            pack=pack,
            origin_main_sha=origin_main_sha,
            census=census,
            lineage=lineage,
            adjudication=adjudication,
            summary=summary,
        )
        result["EVIDENCE_PACK"] = str(pack)
        result["MANIFEST_VERIFY_RC"] = int(verified.get("MANIFEST_VERIFY_RC", 1))
    return result
