"""Standing constants for EXECUTION_PREREQUISITE_25 no additional owner decision.

Offline CASE_B contract persist. No GET. No POST. No flatten execute. No
Live/Canary unlock. Does not issue a runtime permit. Does not rewrite P20 text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.no_additional_owner_decision_required_v1 import (
    NAMED_REMAINING_HIGHER_AUTHORITY_BOUNDARIES,
    P25_IMPLEMENTATION_OWNER_GO,
)
from src.ops.section_11_13_5_p25_execution_prerequisite_25_no_additional_owner_decision_v1.contract_v1 import (
    CASE,
    EXECUTION_PREREQUISITE_25_STATUS,
    FAIL_CLOSED_IF_PREREQUISITE_25_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE,
    P16_TEXT_REWRITTEN,
    P20_TEXT_REWRITTEN,
    P25_DOES_NOT_AUTHORIZE_FLATTEN,
    P25_DOES_NOT_AUTHORIZE_NETWORK_SESSION,
    P25_DOES_NOT_AUTHORIZE_SEND_TIME_PASS,
    P25_DOES_NOT_GRANT_EXECUTION_READINESS,
    P25_DOES_NOT_ISSUE_RUNTIME_PERMIT,
    P25_DOES_NOT_SET_LIVE_AUTHORIZED,
    P25_EXHAUSTION_GATE_IMPLEMENTED,
    P25_NAMED_NO_ADDITIONAL_OWNER_DECISION_CONTRACT_CLOSED,
    PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED,
    PREREQUISITE_25_NETWORK_SESSION_AUTHORIZED,
    PREREQUISITE_25_SEND_TIME_REOBSERVATION_PROVEN,
)

CAPABILITY_ID = "P25_EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_V1"
PACKAGE_MARKER = "P25_EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_V1=true"
OWNER = "ops.section_11_13_5_p25_execution_prerequisite_25_no_additional_owner_decision_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p25_execution_prerequisite_25_no_additional_owner_decision.v1"
OWNER_GO = P25_IMPLEMENTATION_OWNER_GO
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_EXECUTION_PREREQUISITE_20_MUTATION_LIMITED_TO_PROVEN_POSITION"
    "_MAXIMUM_SAFE_LEVERAGE_V1"
)
WORKPACKAGE_ID = "OKX_EEA_P25_EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_V1"
THIS_SLICE = "11.13.5.P25"
PREDECESSOR_SLICE = "11.13.5.P20"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_P25"
EXPECTED_ORIGIN_MAIN_SHA = "82a2ceb6a39d67a6c8635d2d4e1e3053881c566e"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION"
AUTHORIZED_SCOPE = "A_P25_EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION"
CANONICAL_EVIDENCE_RUN_ID = "20260904T021800Z"

CASE_VALUE = CASE
EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION_REQUIRED = EXECUTION_PREREQUISITE_25_STATUS
P25_NAMED_CONTRACT_CLOSED = P25_NAMED_NO_ADDITIONAL_OWNER_DECISION_CONTRACT_CLOSED
P25_MECHANISM_IMPLEMENTED = P25_EXHAUSTION_GATE_IMPLEMENTED
NAMED_REMAINING_HIGHER_AUTHORITY = NAMED_REMAINING_HIGHER_AUTHORITY_BOUNDARIES
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P16_TEXT_REWRITTEN_VALUE = P16_TEXT_REWRITTEN
P20_TEXT_REWRITTEN_VALUE = P20_TEXT_REWRITTEN
P25_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE = P25_DOES_NOT_GRANT_EXECUTION_READINESS
P25_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = P25_DOES_NOT_AUTHORIZE_FLATTEN
P25_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = P25_DOES_NOT_SET_LIVE_AUTHORIZED
P25_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE = P25_DOES_NOT_ISSUE_RUNTIME_PERMIT
P25_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE = P25_DOES_NOT_AUTHORIZE_NETWORK_SESSION
P25_DOES_NOT_AUTHORIZE_SEND_TIME_PASS_VALUE = P25_DOES_NOT_AUTHORIZE_SEND_TIME_PASS
PREREQUISITE_25_SEND_TIME_REOBSERVATION_PROVEN_VALUE = (
    PREREQUISITE_25_SEND_TIME_REOBSERVATION_PROVEN
)
PREREQUISITE_25_NETWORK_SESSION_AUTHORIZED_VALUE = PREREQUISITE_25_NETWORK_SESSION_AUTHORIZED
PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED_VALUE = PREREQUISITE_25_FLATTEN_EXECUTE_AUTHORIZED
FAIL_CLOSED_IF_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE = (
    FAIL_CLOSED_IF_PREREQUISITE_25_MARKED_PROVEN_FROM_OFFLINE_CODE_ALONE
)
EARLIEST_UNRESOLVED_DEPENDENCY = "SEND_TIME_PASS_18_19_21_24"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_SEND_TIME_PASS_18_19_21_24"
P25_RUNTIME_RESIDUAL = (
    "SEND_TIME_PASS_18_19_21_24_AND_AUTHENTICATED_PRODUCTIVE_TRANSPORT_AND_"
    "SEND_TIME_POSITION_REOBSERVATION_AND_FLATTEN_EXECUTE_AND_BOUNDED_RUNTIME_"
    "PERMIT_ISSUANCE_REMAIN_SEPARATE_OWNER_GO"
)
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
CENSUS_COMPLETE = True
LINEAGE_COMPLETE = True

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_p25_execution_prerequisite_25_no_additional_owner_decision_v1"
