"""Empty governed account-equity authority-owner slot. No producer."""

from __future__ import annotations

from src.ops.governed_productive_account_equity_authority_producer_v1.constants_v1 import (
    ACCOUNT_EQUITY_AUTHORITY_OWNER,
    ACCOUNT_EQUITY_AUTHORITY_OWNER_CLASS,
    C01_C16_NOT_ELEVATED,
    GOVERNED_PRODUCER_CREATED,
    GOVERNED_PRODUCTIVE_SOURCE_PRESENT,
    OWNER,
    OWNER_ASSIGNMENT_RATIFIED,
    PRODUCER_IMPLEMENTATION_PRESENT,
    SLOT_IS_EMPTY,
    SLOT_KIND,
    STEP_29P_IS_NOT_EQUITY_AUTHORITY_OWNER,
)

__all__ = [
    "ACCOUNT_EQUITY_AUTHORITY_OWNER",
    "ACCOUNT_EQUITY_AUTHORITY_OWNER_CLASS",
    "C01_C16_NOT_ELEVATED",
    "GOVERNED_PRODUCER_CREATED",
    "GOVERNED_PRODUCTIVE_SOURCE_PRESENT",
    "OWNER",
    "OWNER_ASSIGNMENT_RATIFIED",
    "PRODUCER_IMPLEMENTATION_PRESENT",
    "SLOT_IS_EMPTY",
    "SLOT_KIND",
    "STEP_29P_IS_NOT_EQUITY_AUTHORITY_OWNER",
]
