"""Governed account-equity authority-owner slot.

Owner assignment plus typed sample schema, typed venue-witness
observation contract, typed normalization/inclusion adjudication schema,
and typed internal reconstruction contract schema, plus typed
reconstruction algebra contract schema, plus typed P01
haircut/reserve-depletion term contract schema, plus typed P01
term-set and unit-class adjudication contract schema, plus typed P01
applicability adjudication contract schema, plus typed P01
equity-base inclusion adjudication contract schema, plus typed P01
broader embedding-state adjudication contract schema, plus typed P01
overlap/equivalence adjudication versus U04 and U05, plus typed P01
numeric value provenance adjudication, plus typed P01 member freshness
inheritance adjudication, plus typed P01 haircut/reserve/depletion
semantics adjudication, plus typed P01 exact member identity
ratification, plus typed P01 value unit class ratification, plus typed
P01 applicability class ratification, plus typed P01 application
predicate identity and boundary ratification, plus typed P01
application-predicate input-domain identity and boundary ratification,
plus typed C17+ source-candidate/acceptance/promotion/reopen contracts
and a read-only candidate census, plus OPTION_D SSOT architecture,
checkpoint, event-taxonomy, fresh-eq reconciliation-target
contracts, bound account-identity contract, and typed
checkpoint-observation acquisition, plus typed D6 scoped
read-only observation-boundary contract, plus PATH_B CLASS_C
PACKAGE_1 trading-account observation rules, plus D4 durable runtime
binding and D5 checkpoint-window binding contracts.
No producer implementation. No
runtime source object. No mapping. No value binding. No
Live-account-bound join. No wire. Event acquisition remains typed and
completeness-unproven. Classified kind-set and event-source seam
census remain fail-closed. Observation remains defined-not-executed.
PACKAGE_1 persists selected observation surfaces and semantic laws
only. PATH_B_PREAUTHORIZATION_READY is not execution.
D4/D5 runtime binding contracts do not mint concrete UID values or
window timestamps. Observation S0 remains blocked without persisted
runtime payloads. No reconstruction engine.
"""

from __future__ import annotations

CAPABILITY_ID = "GOVERNED_PRODUCTIVE_ACCOUNT_EQUITY_AUTHORITY_PRODUCER_V1"
PACKAGE_MARKER = "GOVERNED_PRODUCTIVE_ACCOUNT_EQUITY_AUTHORITY_PRODUCER_V1=true"
OWNER = "ops.governed_productive_account_equity_authority_producer_v1"
SCHEMA_VERSION = "governed_productive_account_equity_authority_producer.v1"
CONTRACT_VERSION = "v1"

ACCOUNT_EQUITY_AUTHORITY_OWNER = "ops.governed_productive_account_equity_authority_producer_v1"
ACCOUNT_EQUITY_AUTHORITY_OWNER_CLASS = "GOVERNED_PRODUCTIVE_ACCOUNT_EQUITY_AUTHORITY_PRODUCER"
OWNER_ASSIGNMENT_RATIFIED = True
SLOT_KIND = "EMPTY_GOVERNED_AUTHORITY_OWNER_SLOT"
SLOT_IS_EMPTY = True
C01_C16_NOT_ELEVATED = True
STEP_29P_IS_NOT_EQUITY_AUTHORITY_OWNER = True
PRODUCER_IMPLEMENTATION_PRESENT = False
GOVERNED_PRODUCER_CREATED = False
GOVERNED_PRODUCTIVE_SOURCE_PRESENT = False
SOURCE_OBJECT_PRESENT = False
SOURCE_OBJECT_PRESENT_SEMANTICS = "RUNTIME_SAMPLE_INSTANCE_NOT_SCHEMA_DEFINITION"
SOURCE_SELECTED = False
GOVERNED_RUNNING_ACCOUNT_EQUITY_SAMPLE_SCHEMA_PRESENT = True
VENUE_WITNESS_SCHEMA_PRESENT = True
VENUE_WITNESS_RUNTIME_INSTANCE_PRESENT = False
VENUE_WITNESS_SELECTED = False
WITNESS_CONTRACT_MISSING_CLOSED = True
NORMALIZATION_SCHEMA_PRESENT = True
NORMALIZATION_RUNTIME_INSTANCE_PRESENT = False
NORMALIZATION_CONTRACT_MISSING_CLOSED = True
NORMALIZATION_AUTHORITY_EFFECT = "NONE"
FIELD_TO_DIMENSION_MAPPING_SCHEMA_PRESENT = True
FIELD_TO_DIMENSION_MAPPING_PRESENT = False
SEMANTIC_MAPPING_PROVEN = False
INCLUSION_PROVEN = False
INTERNAL_RECONSTRUCTION_CREATED = False
INTERNAL_RECONSTRUCTION_SCHEMA_PRESENT = True
INTERNAL_RECONSTRUCTION_RUNTIME_INSTANCE_PRESENT = False
INTERNAL_RECONSTRUCTION_CONTRACT_MISSING_CLOSED = True
INTERNAL_RECONSTRUCTION_PROVEN = False
INTERNAL_RECONSTRUCTION_AUTHORITY_EFFECT = "NONE"
RECONSTRUCTION_ALGEBRA_SCHEMA_PRESENT = True
RECONSTRUCTION_ALGEBRA_COMPLETE = False
RECONSTRUCTION_ALGEBRA_AUTHORITY_EFFECT = "NONE"
P01_TERM_CONTRACT_SCHEMA_PRESENT = True
P01_TERM_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_TERM_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_TERM_SEMANTICS_RESOLVED = True
P01_HAIRCUT_RESERVE_DEPLETION_UNSPECIFIED_CLOSED = True
P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_SCHEMA_PRESENT = True
P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_TERM_SET_AND_UNIT_CLASS_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_TERM_SET_RESOLVED = True
P01_VALUE_UNIT_CLASS_RESOLVED = True
P01_VALUE_UNIT_CLASS = "ABSOLUTE_MONETARY_REDUCTION_AMOUNT"
P01_SEMANTIC_DIMENSION = "PARENT_EQUITY_DIMENSION_REDUCTION_AMOUNT"
P01_PARENT_DIMENSION_COMPATIBILITY = (
    "SAME_DIMENSION_CLASS_AS_RUNNING_ACCOUNT_EQUITY_AVAILABLE_FOR_SIZING"
)
P01_REQUIRES_DIMENSIONAL_TRANSFORMATION = False
P01_DIRECT_ADDITIVE_SUBTRACTION_COMPATIBLE = True
P01_UNIT_IDENTITY_IS_DISTINCT_FROM_AUTHORITY_IDENTITY = True
P01_UNIT_IDENTITY_IS_DISTINCT_FROM_MEMBER_IDENTITY = True
P01_SETTLEMENT_CURRENCY_IS_NOT_UNIT_IDENTITY = True
P01_PARENT_DIMENSION_IS_NOT_AUTHORITY_SOURCE = True
P01_VALUE_UNIT_CLASS_SELECTED_OPTION = "P01_OP_VU_ABSOLUTE_MONETARY_REDUCTION_V1"
P01_EXACT_MEMBER_IDENTITY_CONTRACT_SCHEMA_PRESENT = True
P01_EXACT_MEMBER_IDENTITY_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_EXACT_MEMBER_IDENTITY_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_EXACT_MEMBER_IDENTITY_SET = "P01M_GOVERNED_DEPLOYABILITY_CONSERVATISM_REDUCTION"
P01_EXACT_MEMBER_COUNT = 1
P01_VALUE_UNIT_CLASS_CONTRACT_SCHEMA_PRESENT = True
P01_VALUE_UNIT_CLASS_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_VALUE_UNIT_CLASS_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_APPLICABILITY_CLASS_CONTRACT_SCHEMA_PRESENT = True
P01_APPLICABILITY_CLASS_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_APPLICABILITY_CLASS_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_APPLICABILITY_CLASS_RESOLVED = True
P01_APPLICABILITY_CLASS = "GOVERNED_CONDITIONAL"
P01_APPLICABILITY_STATE_MODEL = "APPLIES_DOES_NOT_APPLY_UNKNOWN_FAIL_CLOSED"
P01_APPLICABILITY_CLASS_SELECTED_OPTION = "P01_OP_APPLICABILITY_GOVERNED_CONDITIONAL_V1"
P01_APPLICATION_PREDICATE_RESOLVED = True
P01_APPLICATION_PREDICATE = "GOVERNED_P01_REDUCTION_DIRECTIVE_PREDICATE_V1"
P01_APPLICATION_PREDICATE_IDENTITY_CONTRACT_SCHEMA_PRESENT = True
P01_APPLICATION_PREDICATE_IDENTITY_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_APPLICATION_PREDICATE_IDENTITY_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_APPLICATION_PREDICATE_IDENTITY_RESOLVED = True
P01_APPLICATION_PREDICATE_MODEL = "TYPED_GOVERNED_APPLICABILITY_DECISION_V1"
P01_APPLICATION_PREDICATE_IDENTITY_SELECTED_OPTION = (
    "P01_OP_APPLICATION_PREDICATE_TYPED_GOVERNED_APPLICABILITY_DECISION_V1"
)
P01_APPLICABILITY_DECISION_STATE_MODEL = "APPLIES_DOES_NOT_APPLY_UNKNOWN_FAIL_CLOSED"
P01_APPLICATION_PREDICATE_INPUT_DOMAIN_RESOLVED = True
P01_APPLICATION_TRUE_RULE_RESOLVED = True
P01_APPLICATION_FALSE_RULE_RESOLVED = True
P01_APPLICATION_PREDICATE_INPUT_DOMAIN_IDENTITY_CONTRACT_SCHEMA_PRESENT = True
P01_APPLICATION_PREDICATE_INPUT_DOMAIN_IDENTITY_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_APPLICATION_PREDICATE_INPUT_DOMAIN_IDENTITY_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_PREDICATE_INPUT_DOMAIN_IDENTITY_RESOLVED = True
P01_PREDICATE_INPUT_DOMAIN_BOUNDARY_RESOLVED = True
P01_PREDICATE_INPUT_DOMAIN_CLASS = "TYPED_GOVERNED_P01_RECONSTRUCTION_CONTEXT_V1"
P01_PREDICATE_INPUT_DOMAIN_TYPED = True
P01_PREDICATE_INPUT_DOMAIN_GOVERNED = True
P01_APPLICATION_PREDICATE_INPUT_DOMAIN_IDENTITY_SELECTED_OPTION = (
    "P01_OP_APPLICATION_PREDICATE_INPUT_DOMAIN_TYPED_RECONSTRUCTION_CONTEXT_V1"
)
P01_PREDICATE_INPUT_DOMAIN_ALLOWED_INPUT_CLASS = "TYPED_GOVERNED_P01_RECONSTRUCTION_FACTS_ONLY"
P01_PREDICATE_INPUT_DOMAIN_IS_CLOSED_WORLD = True
P01_PREDICATE_INPUT_DOMAIN_DEFAULT = "NO_IMPLICIT_MEMBERS"
P01_PREDICATE_CONCRETE_INPUT_MEMBERS_RESOLVED = True
P01_PREDICATE_CONCRETE_INPUT_MEMBER_COUNT = 1
P01_PREDICATE_INPUT_MEMBER = "GOVERNED_P01_REDUCTION_DIRECTIVE_V1"
P01_PREDICATE_INPUT_MEMBER_CLASS = "TYPED_GOVERNED_P01_RECONSTRUCTION_FACT"
P01_PREDICATE_REQUIRED_FIELDS_RESOLVED = True
P01_PREDICATE_OPTIONAL_FIELDS_RESOLVED = True
P01_INPUT_READINESS_RULE_RESOLVED = True
P01_INPUT_FRESHNESS_RULE_RESOLVED = False
P01_INPUT_NORMALIZATION_RULE_RESOLVED = True
P01_APPLICABILITY_IS_DISTINCT_FROM_VALUE = True
P01_APPLICABILITY_IS_DISTINCT_FROM_ZERO = True
P01_APPLICABILITY_IS_DISTINCT_FROM_ABSENCE = True
P01_APPLICABILITY_IS_DISTINCT_FROM_NOT_APPLICABLE_VALUE_ENCODING = True
P01_REQUIREDNESS_RESOLVED = True
P01_OPTIONALITY_RESOLVED = True
P01_ZERO_SEMANTICS_RESOLVED = True
P01_ABSENCE_SEMANTICS_RESOLVED = True
P01_INPUT_PRECONDITIONS_RESOLVED = True
P01_RECONSTRUCTION_STATE_PRECONDITIONS_RESOLVED = True
P01_MEMBER_ROLE_SIGN_UNIT_RESOLVED = True
P01_ZERO_ABSENCE_NA_RESOLVED = True
P01_COMBINATION_PRECEDENCE_RESOLVED = True
P01_APPLICABILITY_CONTRACT_SCHEMA_PRESENT = True
P01_APPLICABILITY_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_APPLICABILITY_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_APPLICABILITY_RESOLVED = True
P01_EQUITY_BASE_INCLUSION_CONTRACT_SCHEMA_PRESENT = True
P01_EQUITY_BASE_INCLUSION_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_EQUITY_BASE_INCLUSION_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_EQUITY_BASE_INCLUSION_RESOLVED = True
P01_EMBEDDING_STATE_CONTRACT_SCHEMA_PRESENT = True
P01_EMBEDDING_STATE_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_EMBEDDING_STATE_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_EMBEDDED_STATE_RESOLVED = True
P01_OVERLAP_WITH_U04_U05_CONTRACT_SCHEMA_PRESENT = True
P01_OVERLAP_WITH_U04_U05_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_OVERLAP_WITH_U04_U05_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_U04_OVERLAP_RESOLVED = True
P01_U05_OVERLAP_RESOLVED = True
P01_NUMERIC_VALUE_PROVENANCE_CONTRACT_SCHEMA_PRESENT = True
P01_NUMERIC_VALUE_PROVENANCE_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_NUMERIC_VALUE_PROVENANCE_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_NUMERIC_VALUE_PROVENANCE_RESOLVED = False
P01_MEMBER_FRESHNESS_INHERITANCE_CONTRACT_SCHEMA_PRESENT = True
P01_MEMBER_FRESHNESS_INHERITANCE_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_MEMBER_FRESHNESS_INHERITANCE_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_MEMBER_FRESHNESS_INHERITANCE_RESOLVED = False
P01_HAIRCUT_RESERVE_DEPLETION_SEMANTICS_CONTRACT_SCHEMA_PRESENT = True
P01_HAIRCUT_RESERVE_DEPLETION_SEMANTICS_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_HAIRCUT_RESERVE_DEPLETION_SEMANTICS_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_HAIRCUT_SEMANTICS_RESOLVED = False
P01_RESERVE_SEMANTICS_RESOLVED = False
P01_DEPLETION_SEMANTICS_RESOLVED = False
P01_RUNTIME_INSTANCE_PRESENT = False
P01_AUTHORITY_EFFECT = "NONE"
P01_CLOSEOUT_MODEL = "GOVERNED_REDUCTION_DIRECTIVE_SINGLE_PR_CLOSEOUT_V1"
P01_OPERATOR = "SUBTRACTION"
P01_SIGN_SEMANTICS = "NON_NEGATIVE_ABSOLUTE_MONETARY_REDUCTION"
P01_NEGATIVE_AMOUNT_FORBIDDEN = True
FORMULA_RATIFIED = True
OPERATOR_RATIFIED = True
SIGN_RATIFIED = True
P01_NUMERIC_VALUE_SEMANTICS_RESOLVED = True
P01_INTERNAL_VALUE_SEMANTICS_RESOLVED = True
P01_PRODUCTIVE_EXTERNAL_SOURCE_MAPPING_RESOLVED = False
P01_PRODUCTIVE_DIRECTIVE_PRODUCER_IMPLEMENTED = False
P01_PRODUCTIVE_RUNTIME_BINDING_ADDED = False
P01_PRODUCT_SEMANTICS_COMPLETE = True
P01_RECONSTRUCTION_ALGEBRA_CONTRACT_COMPLETE = True
P01_PRODUCTIVE_EXTERNAL_SOURCE_MAPPING_BLOCKER = (
    "NO_CANONICALLY_VALID_P01_GOVERNED_REDUCTION_DIRECTIVE_SOURCE"
)
P01_EQUITY_BASE_INCLUSION_STATUS = "EXCLUDED_FROM_EQUITY_BASE"
P01_EMBEDDED_STATE = "NOT_EMBEDDED"
P01_U04_OVERLAP_STATE = "DISJOINT"
P01_U05_OVERLAP_STATE = "DISJOINT"
DOUBLE_COUNTING_FORBIDDEN = True
PRE_P01_EQUITY_BASE_EXCLUDES_P01_GOVERNED_REDUCTION = True
P01_GOVERNED_REDUCTION_IS_SEPARATE_RECONSTRUCTION_TERM = True
P01_RECONSTRUCTION_SEMANTIC_AND_ALGEBRA_CLOSEOUT_CONTRACT_SCHEMA_PRESENT = True
P01_RECONSTRUCTION_SEMANTIC_AND_ALGEBRA_CLOSEOUT_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
P01_RECONSTRUCTION_SEMANTIC_AND_ALGEBRA_CLOSEOUT_CONTRACT_AUTHORITY_EFFECT = "NONE"
P01_CLOSEOUT_SELECTED_OPTION = "P01_OP_GOVERNED_REDUCTION_DIRECTIVE_SINGLE_PR_CLOSEOUT_V1"
C01_C16_REJECTION_STILL_BINDING = True
C01_C16_REVIVAL_ALLOWED = False
NEW_CANDIDATE_NAMESPACE_START = "C17"
NEW_SOURCE_GENERATION_MECHANISM_RATIFIED = True
SOURCE_ACCEPTANCE_CONJUNCTION_RATIFIED = True
SOURCE_PROMOTION_STATE_MACHINE_RATIFIED = True
MAPPING_REOPEN_MECHANISM_EXISTS = True
MAPPING_BOUNDARY_CURRENTLY_OPEN = False
CANONICALLY_VALID_ACCOUNT_EQUITY_SOURCE_MAPPING = False
OWNER_RATIFICATION_REQUIRED = True
GENERATION_AUTHORITY_EFFECT = "NONE"
EVIDENCE_AUTHORITY_EFFECT = "NONE"
ACCEPTANCE_AUTHORITY_EFFECT = "NONE"
CANDIDATE_CENSUS_COMPLETE = True
C17_CREATED = False
GENUINELY_NEW_CANDIDATE_COUNT = 0
ACCEPTABLE_FOR_OWNER_RATIFICATION_COUNT = 0
CANDIDATE_IDS_CREATED = "NONE"
NEXT_EVIDENCE_GENERATION_BLOCKER = (
    "NO_GOVERNED_RUNNING_ACCOUNT_EQUITY_SAMPLE_RUNTIME_INSTANCE_WITH_DISTINCT_C17_PLUS_PROVENANCE"
)
GOVERNED_ACCOUNT_EQUITY_SOURCE_CANDIDATE_SCHEMA_PRESENT = True
SOURCE_ACCEPTANCE_CONJUNCTION_SCHEMA_PRESENT = True
SOURCE_PROMOTION_STATE_MACHINE_SCHEMA_PRESENT = True
MAPPING_BOUNDARY_REOPEN_CONTRACT_SCHEMA_PRESENT = True
OPTION_D_SELECTED = True
OPTION_A_REJECTED_AS_LONG_TERM_TARGET = True
OPTION_B_FORBIDDEN = True
OPTION_C_FAIL_CLOSED_FALLBACK_ONLY = True
OPTION_D_SSOT_PERSISTED = True
CHECKPOINT_EVENT_SOURCE_ARCHITECTURE_RATIFIED = True
DIMENSION_EQUITY_STOCK = "RUNNING_ACCOUNT_EQUITY_STOCK"
DIMENSION_AVAILABLE_FOR_SIZING = "RUNNING_ACCOUNT_EQUITY_AVAILABLE_FOR_SIZING"
DIMENSION_MARGIN_REQUIREMENTS = "MARGIN_REQUIREMENTS"
DIMENSION_P01_RISK_CAPITAL_REDUCTION = "P01_GOVERNED_RISK_CAPITAL_REDUCTION"
DIMENSION_SPLIT_PERSISTED = True
U04_PLACEMENT = "AVAILABLE_FOR_SIZING_OR_RISK_SIZING"
U05_PLACEMENT = "EQUITY_STOCK_ONLY_IF_BORROW_LIAB_NOT_ALREADY_EMBEDDED"
U06_PLACEMENT = "EVENT_OR_RECONCILIATION_NOT_BLIND_SUBTRACTION"
P01_PLACEMENT = "AFTER_EQUITY_RISK_CAPITAL_REDUCTION_NOT_IN_SOURCE"
RAW_EQ_SOURCE_AUTHORITY = False
EQ_RECONCILIATION_TARGET_ONLY = True
CHECKPOINT_CONTRACT_SCHEMA_PRESENT = True
CHECKPOINT_CONTRACT_RUNTIME_INSTANCE_PRESENT = False
CHECKPOINT_CAN_MINT_EQUITY = False
EVENT_TAXONOMY_SCHEMA_PRESENT = True
EVENT_TAXONOMY_RUNTIME_INSTANCE_PRESENT = False
UNCLASSIFIED_EVENT_FAIL_CLOSED = True
EQ_RECONCILIATION_TARGET_CONTRACT_SCHEMA_PRESENT = True
EQ_RECONCILIATION_TARGET_RUNTIME_INSTANCE_PRESENT = False
EVENT_ACQUISITION_CREATED = True
EVENT_ACQUISITION_SCHEMA_PRESENT = True
EVENT_ACQUISITION_RUNTIME_INSTANCE_PRESENT = False
EVENT_ACQUISITION_NETWORK_GET_AUTHORIZED = False
COMPLETE_EVENT_STREAM_PROVEN = False
KIND_SET_CENSUS_CREATED = True
KIND_SET_RESOLVED = False
RATIFIED_CLASSIFIED_EVENT_KIND_SET_TOKEN = "EMPTY_FAIL_CLOSED"
KIND_SET_CLOSEOUT_CREATED = True
KIND_SET_CLOSEOUT_STATUS = "FAIL_CLOSED_NAMED_REMAINING_UNKNOWN"
KIND_SET_EVIDENCE_PERSIST_CREATED = True
KIND_SET_EVIDENCE_PERSIST_STATUS = "FAIL_CLOSED_THREE_CANDIDATES_REMAIN_UNKNOWN"
OBSERVATION_BOUNDARY_CONTRACT_CREATED = True
OBSERVATION_BOUNDARY_CONTRACT_STATUS = "DEFINED_NOT_EXECUTED_GET_UNAUTHORIZED"
OBSERVATION_EXECUTED = False
OBSERVATION_EXECUTION_AUTHORIZED = False
OBSERVATION_NETWORK_GET_AUTHORIZED = False
ACCOUNT_COMPOSITION_OBSERVATION_DEFINED = True
LIABILITY_OBSERVATION_DEFINED = True
FEE_EMBEDDING_OBSERVATION_DEFINED = True
EXOGENOUS_EVENT_COVERAGE_OBSERVATION_DEFINED = True
OBSERVATION_IS_NOT_SOURCE_AUTHORITY = True
OBSERVATION_IS_NOT_KIND_RATIFICATION = True
OBSERVATION_IS_NOT_MS2_RELEASE = True
OBSERVATION_IS_NOT_D7_AUTHORIZATION = True
OBSERVATION_IS_NOT_RAW_EQ_SOURCE_AUTHORITY = True
OBSERVATION_IS_NOT_COMPLETENESS_UNLESS_RANGE_ORDERING_PROVENANCE_PROVEN = True
PAPER_SIMULATED_FEE_ACCOUNTING_IS_NON_VENUE_EVIDENCE = True
C01_REHABILITATION_FORBIDDEN = True
ACCOUNT_BILLS_REMAINS_CURRENT_NONCANONICAL = True
ACCOUNT_BILLS_ATLAS_AUTHORITY = "NONE"
CANDIDATE_SURFACE_SELECTION = "NONE_SELECTED"
PATH_A_ARCHIVE_OR_REPO_SEARCH = "REJECT"
PATH_B_SCOPED_READ_ONLY_OBSERVATION = "SELECTED_BUT_BLOCKED_ON_NEW_AUTHORIZATION"
PATH_C_ARCHITECTURAL_UNKNOWN_CLOSEOUT = "REJECT"
PATH_B_CLASS_C_PACKAGE_1_SELECTED = True
PACKAGE_1_PERSISTED = True
PATH_B_PREAUTHORIZATION_READY = True
EXECUTION_READY = False
PACKAGE_1_AUTHORITY_EFFECT = "NONE"
SELECTED_OBSERVATION_SURFACES: tuple[str, ...] = (
    "GET_/api/v5/account/config",
    "GET_/api/v5/account/balance",
    "GET_/api/v5/account/bills",
    "GET_/api/v5/account/bills-archive",
    "GET_/api/v5/account/subtypes",
)
D4_RULE_PERSISTED = True
D4_OBSERVED_FIELDS_ARE_RUNTIME_EVIDENCE_ONLY = True
D4_OBSERVATION_MUST_NOT_MINT_IDENTITY = True
BALANCE_RULE_PERSISTED = True
BALANCE_OBSERVATION_DOES_NOT_REHABILITATE_C01 = True
EQ_ROLE = "RECONCILIATION_OR_EMBEDDING_TARGET_ONLY"
OBSERVED_COMPONENT_FIELDS_HAVE_AUTHORITY_EFFECT = "NONE"
BALANCE_OBSERVATION_ALLOWED_FIELDS: tuple[str, ...] = (
    "eq",
    "cashBal",
    "liab",
    "crossLiab",
    "isoLiab",
    "interest",
    "upl",
    "uplLiab",
    "uTime",
)
EMPTY_COVERAGE_RULE_PERSISTED = True
EMPTY_ROWS_MEAN_ONLY_NO_ROWS_OBSERVED_WITHIN_EXECUTED_QUERY = True
EMPTY_ROWS_PROVE_ZERO_EVENTS = False
EMPTY_ROWS_PROVE_KIND_ABSENCE = False
PAGINATION_EXHAUSTION_PROVES_QUERY_TRAVERSAL_COMPLETED = True
PAGINATION_EXHAUSTION_PROVES_COMPLETENESS = False
RETENTION_GAP_FAIL_CLOSED = True
ORDERING_OR_TIE_AMBIGUITY_FAIL_CLOSED = True
EMBEDDING_RULE_PERSISTED = True
EMBEDDING_OPTION = "E_OPTION_A_FAIL_CLOSED_UNKNOWN_ALLOWED"
UNKNOWN_EMBEDDING_FACTS: tuple[str, ...] = (
    "F12_LIABILITY_AFFECTS_EQUITY_STOCK",
    "F13_LIABILITY_ALREADY_EMBEDDED_IN_EQ",
    "F16_FEE_ALREADY_EMBEDDED_IN_EQ",
    "F17_FEE_SEPARATE_ACCOUNT_DELTA",
    "F18_FEE_RECONCILIATION_ONLY",
)
U05_KIND_DECISION = "REMAIN_UNKNOWN"
U06_KIND_DECISION = "REMAIN_UNKNOWN"
RESIDUAL_KIND_DECISION = "REMAIN_UNKNOWN"
U05_LEGACY_KIND_DECISION = "REMAIN_UNKNOWN"
U05_LEGACY_INCLUDE_EXCLUDE_PROOF_RETIRED_AS_PRODUCTIVE_BLOCKER = True
PRODUCTIVE_U05_EQUITY_STOCK_KIND_MEMBERSHIP = "NOT_IN_CURRENT_PRODUCTIVE_KIND_SET"
PRODUCTIVE_REMAINING_NECESSARY_EQUITY_STOCK_CLASSES: tuple[str, ...] = (
    "U06_FEE_AS_CLASSIFIED_EQUITY_STOCK_KIND",
    "RESIDUAL_UNNAMED_NECESSARY_EQUITY_STOCK_EVENT_CLASS",
)
U06_LEGACY_KIND_DECISION = "REMAIN_UNKNOWN"
U06_LEGACY_INCLUDE_EXCLUDE_PROOF_RETIRED_AS_PRODUCTIVE_BLOCKER = True
PRODUCTIVE_U06_EQUITY_STOCK_KIND_MEMBERSHIP = "NOT_IN_CURRENT_PRODUCTIVE_KIND_SET"
RESIDUAL_LEGACY_KIND_DECISION = "REMAIN_UNKNOWN"
RESIDUAL_LEGACY_INCLUDE_EXCLUDE_PROOF_RETIRED_AS_PRODUCTIVE_BLOCKER = True
PRODUCTIVE_RESIDUAL_EQUITY_STOCK_KIND_MEMBERSHIP = "NOT_IN_CURRENT_PRODUCTIVE_KIND_SET"
CURRENT_PRODUCTIVE_REMAINING_NECESSARY_EQUITY_STOCK_CLASSES: tuple[str, ...] = ()
U04_LEGACY_STATUS = "UNRESOLVED"
U04_LEGACY_ALGEBRA_IN_BASE_VS_NOT_IN_BASE = "UNRESOLVED"
U04_LEGACY_INCLUDE_EXCLUDE_AS_EQUITY_STOCK_KIND_RETIRED_AS_PRODUCTIVE_BLOCKER = True
PRODUCTIVE_U04_EQUITY_STOCK_KIND_MEMBERSHIP = "NOT_IN_CURRENT_PRODUCTIVE_KIND_SET"
PRODUCTIVE_U04_EQUITY_STOCK_ROLE = "NOT_EQUITY_STOCK_AFFECTING"
PRODUCTIVE_U04_AVAILABLE_CAPITAL_ROLE = "AVAILABLE_FOR_SIZING_OR_RISK_SIZING"
ACCOUNT_EQUITY_SOURCE_MAPPING_DENIED_THIS_WORKPACKAGE = True
NON_EQ_EQUITY_STOCK_SOURCE_KIND_STATUS = "NONE_INSUFFICIENT_NO_RATIFIABLE_KIND"
RATIFIED_NON_EQ_EQUITY_STOCK_SOURCE_KINDS: tuple[str, ...] = ()
SOURCE_KIND_COMPLETENESS_STATUS = "INSUFFICIENT_UNPROVEN"
SOURCE_KIND_COMPLETENESS_RATIFICATION = "INSUFFICIENT_NOT_KIND_SET_CLOSURE"
KIND_SET_UPLIFT_THIS_WORKPACKAGE = False
EQ_TREATED_AS_SOURCE_THIS_WORKPACKAGE = False
PRIMARY_PROOF_SURFACE_STATUS = "NONE_IN_EXISTING_REPO_HISTORICAL_FORENSIC_EVIDENCE"
PRIMARY_PROOF_SURFACE = "NONE"
PRIMARY_PROOF_SURFACE_BINDING_STATUS = "NOT_BOUND"
PRIMARY_PROOF_SURFACE_BOUND_THIS_WORKPACKAGE = False
CURRENT_PRODUCTIVE_ACCOUNT_EQUITY_MODEL_VERSION = "CURRENT_PRODUCTIVE_ACCOUNT_EQUITY_MODEL_V1"
CURRENT_PRODUCTIVE_ARCHITECTURE_RATIFIED = True
CURRENT_PRODUCTIVE_ARCHITECTURE_IS_NOT_HISTORICAL_RECONSTRUCTION = True
LEGACY_RECONSTRUCTION_REQUIRED_FOR_LIVE = False
SEALED_LEGACY_CENSUS_REOPENED = False
CURRENT_PRODUCTIVE_EQUITY_STOCK_ROLE = "ACCOUNT_EQUITY_STOCK_NOT_29P_SIZING_INPUT"
CURRENT_PRODUCTIVE_EQUITY_STOCK_SOURCE_STATUS = "UNBOUND"
CURRENT_PRODUCTIVE_RECONCILIATION_TARGET_ROLE = "EQ_RECONCILIATION_TARGET_ONLY"
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_DIMENSION = "RUNNING_ACCOUNT_EQUITY_AVAILABLE_FOR_SIZING"
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_SOURCE_STATUS = "UNBOUND"
CURRENT_PRODUCTIVE_LIVE_CRITICAL_DEPENDENCY = (
    "CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_SOURCE_UNBOUND"
)
CURRENT_PRODUCTIVE_SOURCE_SELECTED = False
CURRENT_PRODUCTIVE_PRODUCER_MINT_AUTHORIZED = False
CURRENT_PRODUCTIVE_29P_CONSUMER_BINDING_STATUS = "BOUND_AVAILABLE_FOR_SIZING_ONLY"
CURRENT_PRODUCTIVE_RESTART_RECONSTRUCTION_STATUS = (
    "FAIL_CLOSED_UNTIL_CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_SOURCE_BOUND"
)
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_SOURCE_SELECTION_RATIFIED = True
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_SOURCE_SELECTION_STATUS = (
    "NO_SEMANTICALLY_ADMISSIBLE_CANDIDATE"
)
CURRENT_PRODUCTIVE_SELECTED_AVAILABLE_FOR_SIZING_SOURCE = "NONE"
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_TRANSFORMATION = "NONE_NO_SOURCE"
CURRENT_PRODUCTIVE_U04_APPLICATION_STATUS = "REDUCTION_ONLY_NOT_SOURCE_NOT_APPLIED"
CURRENT_PRODUCTIVE_FRESH_GET_EXECUTED = False
CURRENT_PRODUCTIVE_FRESH_GET_NOT_REQUIRED_FOR_BINDING_DECISION = True
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_PRODUCER_CREATED = True
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_PRODUCER_IDENTITY = (
    "CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_PRODUCER_V1"
)
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_PRODUCER_ALGEBRA = (
    "BASE_MINUS_U04_MINUS_CONDITIONAL_P01_USDC_V1"
)
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_BASE_FACT_ID = (
    "CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_BASE"
)
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_BASE_STATUS = "UNBOUND"
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_PRODUCER_MINT_AUTHORIZED = False
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_PRODUCER_IS_SOURCE_OBJECT = True
CURRENT_PRODUCTIVE_U04_CURRENT_APPLICATION = "SUBTRACT_AFTER_BASE_ONCE_NOT_SOURCE"
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_RESTART_POLICY = (
    "RECOMPUTE_FROM_FRESH_CURRENT_FACTS_SAME_EPOCH_ELSE_FAIL_CLOSED"
)
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_29P_BINDING_STATUS = (
    "CONSUMER_BOUND_TO_PRODUCER_OUTPUT_VALUE_UNBOUND"
)
CURRENT_PRODUCTIVE_AVAILABLE_FOR_SIZING_OUTPUT_CLASS = "SIZING_INPUT_NOT_LIVE_CAPITAL_AUTHORITY"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_MODEL_CREATED = True
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_SELECTED_OPTION = "OPTION_B"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_ALGEBRA = "DETAILS_USDC_AVAILEQ_MINUS_CONDITIONAL_P01_USDC_V1"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_OBSERVATION_SURFACE = "details[ccy=USDC].availEq"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_OBSERVATION_CLASS = "CURRENCY_SCOPED_CROSS_MARGIN_FREE_MARGIN"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_BASE_ABSTRACTION = "RETIRED_UNNECESSARY_INTERMEDIATE"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_U04_APPLICATION = (
    "DO_NOT_SUBTRACT_ALREADY_NETTED_IN_VENUE_FREE_MARGIN"
)
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_P01_APPLICATION = (
    "SUBTRACT_ONLY_IF_APPLIES_PEAK_TRADE_POLICY_NOT_IN_VENUE_AVAILEQ"
)
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_AVAIL_EQ_VERDICT = (
    "CURRENT_PRODUCTIVE_RECLASSIFICATION_JUSTIFIED"
)
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_TOTAL_EQ_VERDICT = "KEEP_FORBIDDEN"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_ADJ_EQ_VERDICT = "KEEP_FORBIDDEN"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_AVAIL_BAL_VERDICT = "KEEP_FORBIDDEN"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_CASH_BAL_VERDICT = "KEEP_FORBIDDEN"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_ACCOUNT_LEVEL_AVAIL_EQ_VERDICT = "KEEP_FORBIDDEN"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_EQ_VERDICT = "KEEP_RECONCILIATION_TARGET_ONLY"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_FALLBACK_CHAIN_VERDICT = "KEEP_FORBIDDEN"
CURRENT_PRODUCTIVE_29P_RISK_CAPITAL_29P_BINDING_STATUS = (
    "CONSUMER_BOUND_TO_PRODUCER_OUTPUT_SURFACE_BOUND_VALUE_REQUIRES_FRESH_GET"
)
CURRENT_PRODUCTIVE_29P_FRESH_GET_AND_PRODUCE_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_29P_FRESH_GET_ENDPOINT = "/api/v5/account/balance"
CURRENT_PRODUCTIVE_29P_FRESH_GET_AUTHORIZED_COUNT = 1
CURRENT_PRODUCTIVE_29P_FRESH_GET_POST_COUNT = 0
CURRENT_PRODUCTIVE_U01_ACCOUNT_MODE_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_U01_RAW_FIELD = "acctLv"
CURRENT_PRODUCTIVE_U01_REQUIRED_RAW_TOKEN = "2"
CURRENT_PRODUCTIVE_U01_CANONICAL_SEMANTIC_TOKEN = "FUTURES_MODE"
CURRENT_PRODUCTIVE_U01_OPEN_AUTHORITY_STATUS = "RETIRED_NOT_CURRENT_PRODUCTIVE_AUTHORITY"
CURRENT_PRODUCTIVE_U01_GET_ENDPOINT = "/api/v5/account/config"
CURRENT_PRODUCTIVE_U01_GET_AUTHORIZED_COUNT = 1
CURRENT_PRODUCTIVE_U01_GET_POST_COUNT = 0
CURRENT_PRODUCTIVE_P01_POLICY_CREATED = True
CURRENT_PRODUCTIVE_P01_POLICY_DECISION = "DOES_NOT_APPLY"
CURRENT_PRODUCTIVE_P01_POLICY_DECISION_BASIS = "ARCHITECTURAL_REDUNDANCY_NOT_HISTORICAL_ABSENCE"
CURRENT_PRODUCTIVE_P01_INDEPENDENT_SAFETY_FUNCTION = False
CURRENT_PRODUCTIVE_P01_POLICY_BINDING_PRESENT = True
CURRENT_PRODUCTIVE_P01_RECONSTRUCTION_RUNTIME_INSTANCE_PRESENT = False
CURRENT_PRODUCTIVE_29P_LAB_AND_INSTRUMENT_SCOPE_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_EEA_UNIVERSE_INVENTORY_TO_CAP24_AND_29P_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_LIVE_ENABLED_STANDING_GATE_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_LIVE_ARMED_STANDING_GATE_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_WIRE_SEND_PERMITTED_STANDING_GATE_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_EXECUTION_ADMISSION_REMAINDER_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_LIVE_EXECUTION_PORT_CONSTRUCTION_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_CAP72_HOST_JOIN_TO_LIVE_EXECUTION_PORT_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_SUBMISSION_AUTHORIZED_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_LIVE_AUTHORIZED_AND_CAP_11_1_SEND_CAPABLE_ADAPTER_CREATED = True
CURRENT_PRODUCTIVE_ENVELOPE_BOUND_SINGLE_USE_EXTERNAL_EFFECT_SEND_SEAM_CREATED = True
CURRENT_PRODUCTIVE_FRESH_CAP23_CAP24_DECISION_AND_ONE_SHOT_REAL_POST_READINESS_CREATED = True
CURRENT_PRODUCTIVE_FRESH_RUNTIME_CYCLE_TO_EXACT_ENVELOPE_BOUND_SINGLE_USE_POST_BOUNDARY_CREATED = (
    True
)
CURRENT_PRODUCTIVE_EXACT_OBJECT_DISPOSITION_TO_ONE_SHOT_FLATTEN_POST_BOUNDARY_CREATED = True
CURRENT_PRODUCTIVE_POST_FLATTEN_EVIDENCE_ADJUDICATION_AND_CANONICAL_STATE_ADVANCE_CREATED = True
CURRENT_PRODUCTIVE_FRESH_RUNTIME_CYCLE_AFTER_FLATTEN_OCCUPANCY_ABSENT_CREATED = True
CURRENT_PRODUCTIVE_FRESH_RUNTIME_CYCLE_AFTER_NON_EXECUTABLE_DECISION_CREATED = True
CURRENT_PRODUCTIVE_FRESH_RUNTIME_CYCLE_AFTER_NON_EXECUTABLE_DECISION_V2_CREATED = True
CURRENT_PRODUCTIVE_FRESH_RUNTIME_CYCLE_AFTER_NON_EXECUTABLE_DECISION_V3_CREATED = True
CURRENT_PRODUCTIVE_ONESHOT_SIDESTATE_CONFIRMATION_CURSOR_JOIN_CREATED = True
CURRENT_PRODUCTIVE_HOST_ENTER_29P_INVALID_STOP_PRICE_REPAIR_CREATED = True
CURRENT_PRODUCTIVE_FRESH_RUNTIME_TO_PRE_EXTERNAL_EFFECT_APPLICABILITY_CREATED = True
CURRENT_PRODUCTIVE_FRESH_RUNTIME_FROM_PERSISTED_CURSOR_TO_PRE_EXTERNAL_EFFECT_APPLICABILITY_CREATED = True
CURRENT_PRODUCTIVE_ONE_RUNTIME_CYCLE_AFTER_NEW_FINALIZED_1M_C1_OBSERVATION_CREATED = True
CURRENT_PRODUCTIVE_ONE_RUNTIME_CYCLE_AFTER_NEW_FINALIZED_1M_C1_OBSERVATION_V2_CREATED = True
CURRENT_PRODUCTIVE_ONE_RUNTIME_CYCLE_AFTER_NEW_FINALIZED_1M_C1_OBSERVATION_V3_CREATED = True
CURRENT_PRODUCTIVE_EEA_UNIVERSE_ACQUISITION_OWNER = (
    "CURRENT_PRODUCTIVE_EEA_UNIVERSE_INVENTORY_ACQUISITION_V1"
)
CURRENT_PRODUCTIVE_29P_CANARY_INSTRUMENT_AUTHORITY_IMPORTED = False
RESIDUAL_COMPLETENESS_PROVEN = False
RESIDUAL_NO_REMAINDER_NORMALIZED = False
UNKNOWN_NECESSARY_CLASS_REMAINS = True
MS1_KIND_SET_FULLY_CLOSED = False
MS2_AUTHORIZED = False
D6_FULLY_CLOSED = False
D7_AUTHORIZED = False
SOURCE_MAPPING_RATIFICATION_CREATED = True
D6_ACCOUNT_EQUITY_SOURCE_MAPPING_PERSISTED = True
D6_ACCOUNT_EQUITY_SOURCE_MAPPING_COVERAGE_STATUS = "PARTIAL_FAIL_CLOSED_NO_RATIFIED_SOURCE_KIND"
SOURCE_MAPPING_AND_COMPLETE_EVENT_STREAM_ACQUISITION_CREATED = True
F12_F13_F16_F17_F18_NECESSARY_EQUITY_STOCK_KIND_RESOLUTION_CREATED = True
F12_F13_PRIMARY_LIABILITY_STOCK_OBSERVATION_CREATED = True
EQ_IDENTITY_AND_F12_F13_LIABILITY_STOCK_KIND_RATIFICATION_CREATED = True
F12_F13_KIND_SET_REMAINING_UNKNOWN_PIN_CREATED = True
BJ_SEMANTICS_BOUNDED_IMPLEMENTATION_CREATED = True
BK_BOUNDED_IMPLEMENTATION_CREATED = True
EARLIEST_REMAINING_D6_BLOCKER = (
    "F12_F13_REMAIN_UNKNOWN_AFTER_EQ_IDENTITY_NONE_AND_AUTHORIZED_FRESH_BALANCE_GET_"
    "EMPTY_OR_ZERO_DOES_NOT_PROVE_ABSENCE"
)
KIND_SET_INCLUDE_EXCLUDE_BLOCKED_BY = (
    "F12_F13_EQ_IDENTITY_NONE_AND_AUTHORIZED_FRESH_BALANCE_GET_EMPTY_OR_ZERO_DOES_NOT_PROVE_ABSENCE"
)
COMPLETE_CLASSIFIED_EVENT_STREAM_ACQUISITION_STATUS = (
    "FAIL_CLOSED_KIND_SET_AND_RETENTION_ORDERING_SEAM_UNPROVEN"
)
NAMED_REMAINING_UNKNOWN_NECESSARY_CLASSES: tuple[str, ...] = (
    "U05_LIABILITY_AS_CLASSIFIED_EQUITY_STOCK_KIND",
    "U06_FEE_AS_CLASSIFIED_EQUITY_STOCK_KIND",
    "RESIDUAL_UNNAMED_NECESSARY_EQUITY_STOCK_EVENT_CLASS",
)
HYPOTHESIS_ONLY_EQUITY_STOCK_EVENT_CLASSES: tuple[str, ...] = (
    "DEPOSIT",
    "WITHDRAWAL",
    "TRANSFER",
    "FUNDING",
    "INTEREST",
    "LIQUIDATION",
    "CONVERT",
)
AUTHORIZED_PRODUCTIVE_EVENT_SOURCE_SEAM_PRESENT = False
SOURCE_COVERAGE_COMPLETE = False
ORDERING_PROVEN = False
GAP_DETECTION_FAIL_CLOSED = True
IDEMPOTENCY_REPLAY_IDENTITY_PROVEN = False
D6_COMPLETENESS_PRECONDITIONS_PROVEN = False
EVENT_KIND_SOURCE_SEAM_SELECTED = False
EVENT_KIND_SOURCE_BINDING_IS_NOT_EQUITY_SOURCE_AUTHORITY = True
EVENT_KIND_SOURCE_BINDING_IS_NOT_RAW_EQ_SOURCE_AUTHORITY = True
EVENT_KIND_SOURCE_BINDING_IS_NOT_MAPPING_PROVEN = True
EARLIEST_D6_COMPLETENESS_DEPENDENCY = (
    "RATIFIED_CLASSIFIED_EVENT_KIND_SET_AND_AUTHORIZED_PRODUCTIVE_EVENT_SOURCE_SEAM"
)
EARLIEST_D6_KIND_SET_DEPENDENCY = "NAMED_REMAINING_UNKNOWN_NECESSARY_EQUITY_STOCK_KIND_SET"
RECONSTRUCTION_ENGINE_CREATED = False
RESTART_PROVEN = False
BOUND_ACCOUNT_IDENTITY_PROVEN = True
BOUND_ACCOUNT_IDENTITY_CONTRACT_SCHEMA_PRESENT = True
BOUND_ACCOUNT_IDENTITY_RUNTIME_INSTANCE_PRESENT = False
BOUND_ACCOUNT_IDENTITY_FROM_ENV_FORBIDDEN = True
BOUND_ACCOUNT_IDENTITY_FROM_CREDENTIAL_FORBIDDEN = True
BOUND_ACCOUNT_IDENTITY_IMPLICIT_DEFAULT_FORBIDDEN = True
BOUND_ACCOUNT_CONCRETE_UID_OBSERVED = False
D4_RUNTIME_BINDING_CONTRACT_PRESENT = True
D4_RUNTIME_BINDING_CREATED = True
D4_CONCRETE_UID_CORROBORATED = False
D4_D5_GENESIS_REBASELINE_CONTRACT_PRESENT = True
GENESIS_REBASELINE_SELECTED_BY_OWNER = True
LEGACY_D4_D5_RUNTIME_CHAIN_RECONSTRUCTED = False
HISTORICAL_CONTINUITY_CLAIMED = False
D4_GENESIS_BOOTSTRAP_SOURCE = "FRESH_AUTHENTICATED_ACCOUNT_CONFIG"
D4_GENESIS_ACCOUNT_CONFIG_GET_AUTHORIZED = True
D4_GENESIS_POSITIONS_GET_AUTHORIZED = True
D4_BOUND_TD_MODE_SOURCE = "FRESH_AUTHENTICATED_POSITION_MGN_MODE"
D4_BOUND_TD_MODE_DERIVATION = "OKX_FUTURES_SWAP_MGN_MODE_TO_TD_MODE_IDENTITY_MAPPING"
D4_BOUND_ACCOUNT_IDENTITY_SOURCE = "FRESH_AUTHENTICATED_ACCOUNT_CONFIG_UID"
D4_GENESIS_ACCOUNT_CONFIG_UID_RECAPTURE_GET_AUTHORIZED = True
D4_POST_GENESIS_OBSERVATION_MUST_NOT_MINT_IDENTITY = True
POINT_WINDOW_DOES_NOT_ASSERT_ZERO_PRIOR_EVENTS = True
HISTORICAL_COMPLETENESS_CLAIMED = False
NEW_CANONICAL_RUNTIME_CHAIN_STARTS_AT_GENESIS_AS_OF = True
PRE_GENESIS_DATA_IMPORTED = False
PRE_GENESIS_PERIOD = "OUT_OF_SCOPE_FOR_NEW_RUNTIME_CHAIN"
D4_D5_GENESIS_RUNTIME_STORE_RELPATH = "evidence/ops/full_core_d6_path_b_d4_d5_genesis_rebaseline_v1"
PACKAGE_1_OBSERVATION_EXECUTION_STORE_RELPATH = (
    "evidence/ops/full_core_d6_path_b_package_1_observation_execution_v1"
)
CHECKPOINT_OBSERVATION_ACQUISITION_SCHEMA_PRESENT = True
CHECKPOINT_OBSERVATION_ACQUISITION_CREATED = True
CHECKPOINT_OBSERVATION_PROVEN = True
CHECKPOINT_OBSERVATION_RUNTIME_INSTANCE_PRESENT = False
CHECKPOINT_OBSERVATION_NETWORK_GET_AUTHORIZED = False
D5_WINDOW_BINDING_CONTRACT_PRESENT = True
D5_WINDOW_BINDING_CREATED = True
CHECKPOINT_OBSERVATION_WINDOW_RUNTIME_INSTANCE_PRESENT = False
D5_WINDOW_END_EQUALS_OBSERVED_AT_AS_OF_RELATION_AUTHORITY_PRESENT = False
OBSERVATION_S0_STRUCTURAL_BLOCKERS_CLEARED = True
OBSERVATION_S0_RUNTIME_PAYLOADS_PRESENT = False
EARLIEST_OPTION_D_DEPENDENCY = "D6_COMPLETE_CLASSIFIED_EVENT_STREAM_ACQUISITION"
C17_CREATION_FROZEN_UNTIL_D1_D9_PROVEN = True
LIVE_RESTART_RECONSTRUCTED = False
RECONCILIATION_CONTRACT_CREATED = False
DIVERGENCE_POLICY_CREATED = False
OBSERVATION_AUTHORITY_EFFECT = "NONE"
EQUITY_DIMENSION_BOUND = False
MAPPED_TO_RUNNING_ACCOUNT_EQUITY_AVAILABLE_FOR_SIZING = False
RAW_TO_WITNESS_PROVEN = False
RUNTIME_VALUE_PRESENT = False
SAMPLE_PRESENT = False
LIVE_ACCOUNT_BOUND_JOIN_PRESENT = False
CORE_LOGIC_CHANGE = False
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
NUMERIC_EQUITY_TTL_SECONDS = 5
SAMPLE_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "dimension_id",
    "bound_account_identity",
    "bound_venue_identity",
    "bound_td_mode",
    "settlement_currency",
    "value",
    "value_semantics",
    "producer_identity",
    "authority_contract_ref",
    "source_revision_or_digest",
    "input_set_digest",
    "decision_epoch",
    "observed_at/as_of",
    "freshness_max_age",
    "freshness_policy_status",
    "restart_reconciliation_status",
    "component_completeness",
    "component_provenance",
    "inclusion_vector",
    "component_term_vector",
    "double_count_guards",
    "currency_conversion_status",
    "witness_reconciliation_status",
    "policy_version",
    "semantic_digest",
    "sample_id",
    "observation_vs_authority_class",
)
WITNESS_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "witness_id",
    "bound_account_identity",
    "bound_venue_identity",
    "rest_host",
    "bound_td_mode",
    "account_mode",
    "currency_domain",
    "endpoint",
    "method",
    "request_identity",
    "decision_epoch",
    "observed_at/as_of",
    "response_received_at",
    "provider_timestamp",
    "raw_field_path",
    "observation_semantic_class",
    "raw_value_representation",
    "presence_state",
    "raw_payload_state",
    "payload_digest",
    "raw_payload",
    "request_provenance",
    "response_provenance",
    "observation_vs_authority_class",
    "observation_authority_effect",
    "equity_dimension_bound_status",
    "mapping_status",
    "freshness_evidence_status",
    "clock_source_status",
    "provenance_digest",
)
NORMALIZATION_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "adjudication_id",
    "source_witness_id",
    "bound_account_identity",
    "bound_venue_identity",
    "rest_host",
    "bound_td_mode",
    "account_mode",
    "currency_domain",
    "decision_epoch",
    "raw_field_path",
    "observation_semantic_class",
    "raw_value_representation",
    "presence_state",
    "requested_target_dimension_id",
    "field_to_dimension_mapping_status",
    "observation_participation_state",
    "normalizable_status",
    "semantic_mapping_status",
    "inclusion_status",
    "source_selection_status",
    "observation_vs_authority_class",
    "normalization_authority_effect",
    "exclusion_reason_codes",
    "account_scope_compatibility_status",
    "currency_domain_compatibility_status",
    "unit_compatibility_status",
    "freshness_evidence_status",
    "freshness_evidence_ref",
    "provenance_status",
    "ambiguity_status",
    "contradiction_status",
    "semantic_mapping_proven_status",
    "inclusion_proven_status",
    "source_selected_status",
    "provenance_digest",
)
RECONSTRUCTION_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "reconstruction_id",
    "source_normalization_adjudication_id",
    "bound_account_identity",
    "bound_venue_identity",
    "rest_host",
    "bound_td_mode",
    "account_mode",
    "currency_domain",
    "reconstruction_epoch",
    "target_semantic_dimension_id",
    "reconstruction_semantic_class",
    "reconstruction_semantic_class_version",
    "inclusion_vector",
    "component_term_vector",
    "component_completeness",
    "reconstruction_algebra_status",
    "reconstruction_algebra_representation",
    "reconstructed_value_state",
    "reconstructed_value_representation",
    "contradiction_status",
    "same_epoch_status",
    "freshness_status",
    "freshness_evidence_ref",
    "restart_invalidation_status",
    "restart_provenance_class",
    "reconstruction_eligibility",
    "reconstruction_proven_status",
    "observation_vs_authority_class",
    "internal_reconstruction_authority_effect",
    "provenance_digest",
)
ALGEBRA_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "algebra_contract_id",
    "algebra_contract_version",
    "reconstruction_contract_schema_class",
    "target_semantic_dimension_id",
    "algebra_representation",
    "algebra_completeness_status",
    "canonical_formula_status",
    "canonical_formula_representation",
    "unresolved_required_terms",
    "contradiction_status",
    "currency_unit_compatibility_status",
    "valuation_dependency_status",
    "reconstruction_algebra_authority_effect",
    "term_vector",
    "provenance_digest",
)
P01_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_term_contract_id",
    "p01_term_contract_version",
    "algebra_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "semantic_class",
    "algebraic_role",
    "economic_meaning",
    "value_unit_class",
    "currency_valuation_domain",
    "applicability_state",
    "provenance_requirements",
    "origin_class",
    "inclusion_state",
    "embedded_state",
    "overlap_state",
    "double_counting_guard",
    "sign_constraints",
    "negative_allowed",
    "zero_validity_semantics",
    "freshness_epoch_requirements",
    "completeness_resolution_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "p01_term_contract_authority_effect",
    "numeric_state",
    "provenance_digest",
)
P01_TERM_SET_AND_UNIT_CLASS_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_term_set_and_unit_class_contract_id",
    "p01_term_set_and_unit_class_contract_version",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "family_class_labels",
    "family_labels_are_not_exact_term_set",
    "p01_term_set",
    "p01_term_set_resolved_status",
    "p01_term_set_adjudication",
    "p01_value_unit_class",
    "p01_value_unit_class_resolved_status",
    "p01_value_unit_class_adjudication",
    "currency_valuation_domain",
    "algebraic_role",
    "sign_constraints",
    "negative_allowed",
    "rejected_term_set_inferences",
    "rejected_unit_class_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_term_set_and_unit_class_contract_authority_effect",
    "provenance_digest",
)
P01_APPLICABILITY_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_applicability_contract_id",
    "p01_applicability_contract_version",
    "parent_p01_term_set_and_unit_class_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "p01_applicability_status",
    "p01_applicability_resolved_status",
    "p01_applicability_rule",
    "p01_applicability_adjudication",
    "typed_applicability_state",
    "unknown_is_not_not_applicable",
    "zero_is_not_not_applicable",
    "absence_is_not_not_applicable",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "term_set_unresolved_does_not_decide_applicability",
    "unit_unresolved_does_not_decide_applicability",
    "rejected_applicability_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_applicability_contract_authority_effect",
    "provenance_digest",
)
P01_EQUITY_BASE_INCLUSION_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_equity_base_inclusion_contract_id",
    "p01_equity_base_inclusion_contract_version",
    "parent_p01_applicability_contract_schema_class",
    "parent_p01_term_set_and_unit_class_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "p01_equity_base_inclusion_status",
    "p01_equity_base_inclusion_resolved_status",
    "p01_equity_base_inclusion_rule",
    "p01_equity_base_inclusion_adjudication",
    "typed_inclusion_state",
    "unknown_is_not_excluded",
    "zero_is_not_embedded_or_excluded",
    "absence_is_not_not_embedded",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "term_set_unresolved_does_not_decide_inclusion",
    "applicability_unresolved_does_not_decide_inclusion",
    "unit_unresolved_does_not_decide_inclusion",
    "separate_schema_does_not_prove_independent_deduction",
    "unknown_inclusion_cannot_authorize_subtraction",
    "unknown_inclusion_cannot_authorize_omission",
    "no_double_counting_permission",
    "rejected_inclusion_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_equity_base_inclusion_contract_authority_effect",
    "provenance_digest",
)
P01_EMBEDDING_STATE_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_embedding_state_contract_id",
    "p01_embedding_state_contract_version",
    "parent_p01_equity_base_inclusion_contract_schema_class",
    "parent_p01_applicability_contract_schema_class",
    "parent_p01_term_set_and_unit_class_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "p01_embedded_state",
    "p01_embedded_state_resolved_status",
    "p01_embedding_rule",
    "p01_embedding_adjudication",
    "typed_embedding_state",
    "family_level_embedding_state",
    "member_level_embedding_state",
    "economic_overlap_state",
    "representational_nesting_state",
    "arithmetic_inclusion_state",
    "semantic_equivalence_state",
    "p01_overlap_state",
    "unknown_is_not_not_embedded",
    "unknown_is_not_embedded",
    "zero_does_not_prove_embedding",
    "absence_does_not_prove_embedding",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "term_set_unresolved_does_not_decide_embedding",
    "applicability_unresolved_does_not_decide_embedding",
    "unit_unresolved_does_not_decide_embedding",
    "equity_base_inclusion_unresolved_does_not_decide_broader_embedding",
    "u04_u05_u06_labels_do_not_decide_embedding",
    "equal_values_do_not_prove_embedding",
    "shared_source_does_not_prove_embedding",
    "separate_schema_does_not_prove_independence",
    "unknown_embedding_cannot_authorize_subtraction",
    "unknown_embedding_cannot_authorize_omission",
    "unknown_embedding_cannot_authorize_netting",
    "no_double_counting_permission",
    "rejected_embedding_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_embedding_state_contract_authority_effect",
    "provenance_digest",
)
P01_OVERLAP_WITH_U04_U05_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_overlap_with_u04_u05_contract_id",
    "p01_overlap_with_u04_u05_contract_version",
    "parent_p01_embedding_state_contract_schema_class",
    "parent_p01_equity_base_inclusion_contract_schema_class",
    "parent_p01_applicability_contract_schema_class",
    "parent_p01_term_set_and_unit_class_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "p01_u04_overlap_state",
    "p01_u04_overlap_resolved_status",
    "p01_u04_overlap_adjudication",
    "typed_u04_overlap_state",
    "p01_u05_overlap_state",
    "p01_u05_overlap_resolved_status",
    "p01_u05_overlap_adjudication",
    "typed_u05_overlap_state",
    "semantic_equivalence_state",
    "economic_overlap_state",
    "representational_nesting_state",
    "shared_provenance_state",
    "shared_numeric_value_state",
    "shared_unit_state",
    "simultaneous_applicability_state",
    "arithmetic_interaction_state",
    "p01_overlap_state",
    "u06_accrued_fees_distinct_pin",
    "unknown_is_not_disjoint",
    "unknown_is_not_equivalent",
    "unknown_is_not_non_overlapping",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "zero_does_not_prove_non_overlap",
    "absence_does_not_prove_disjoint",
    "equal_values_do_not_prove_equivalence",
    "shared_source_does_not_prove_equivalence",
    "shared_unit_does_not_prove_equivalence",
    "term_set_unresolved_does_not_decide_overlap",
    "applicability_unresolved_does_not_decide_overlap",
    "embedding_unresolved_does_not_decide_overlap",
    "u04_u05_labels_do_not_decide_overlap",
    "u06_distinctness_does_not_decide_p01_u06",
    "unknown_overlap_cannot_authorize_summation",
    "unknown_overlap_cannot_authorize_deduplication",
    "unknown_overlap_cannot_authorize_netting",
    "unknown_overlap_cannot_authorize_subtraction",
    "unknown_overlap_cannot_authorize_omission",
    "no_double_counting_permission",
    "rejected_overlap_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_overlap_with_u04_u05_contract_authority_effect",
    "provenance_digest",
)
P01_NUMERIC_VALUE_PROVENANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_numeric_value_provenance_contract_id",
    "p01_numeric_value_provenance_contract_version",
    "parent_p01_overlap_with_u04_u05_contract_schema_class",
    "parent_p01_embedding_state_contract_schema_class",
    "parent_p01_equity_base_inclusion_contract_schema_class",
    "parent_p01_applicability_contract_schema_class",
    "parent_p01_term_set_and_unit_class_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "p01_numeric_value_provenance_resolved_status",
    "p01_numeric_value_provenance_status",
    "p01_numeric_value_source",
    "p01_numeric_value_transformation",
    "typed_provenance_class",
    "producer_state",
    "source_object_id",
    "source_field_id",
    "source_contract_id",
    "transformation_chain_state",
    "time_semantics_state",
    "unit_dimension_transform_state",
    "missing_value_treatment",
    "stale_value_treatment",
    "unavailable_value_treatment",
    "contradictory_value_treatment",
    "partial_evidence_treatment",
    "multiple_candidate_treatment",
    "fallback_source_state",
    "numeric_computation_rule_state",
    "haircut_reserve_depletion_construction_state",
    "unknown_is_not_numeric_authorization",
    "unspecified_is_not_numeric_authorization",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "zero_is_not_p01_value",
    "absence_is_not_p01_value",
    "venue_field_is_not_p01_value",
    "name_similarity_does_not_prove_source",
    "numeric_equality_does_not_prove_source",
    "policy_slot_is_not_numeric_source",
    "algebra_slot_is_not_numeric_source",
    "unspecified_haircut_cannot_construct_p01",
    "unspecified_cannot_authorize_subtraction",
    "unspecified_cannot_authorize_addition",
    "unspecified_cannot_authorize_netting",
    "unspecified_cannot_authorize_omission",
    "unspecified_cannot_authorize_ignore",
    "rejected_provenance_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "candidate_sources_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_numeric_value_provenance_contract_authority_effect",
    "provenance_digest",
)
P01_MEMBER_FRESHNESS_INHERITANCE_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_member_freshness_inheritance_contract_id",
    "p01_member_freshness_inheritance_contract_version",
    "parent_p01_numeric_value_provenance_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "p01_member_freshness_inheritance_resolved_status",
    "p01_member_freshness_status",
    "p01_member_freshness_rule",
    "p01_u09_freshness_relation",
    "p01_freshness_dimension_state",
    "p01_timestamp_state",
    "p01_level_freshness_metadata_state",
    "member_level_freshness_metadata_state",
    "inheritance_rule_state",
    "u09_comparison_evidence_only",
    "u09_is_not_p01_freshness_authority",
    "p01_freshness_does_not_inherit_u09",
    "p01_freshness_not_equivalent_to_u09",
    "unknown_is_not_freshness_authority",
    "unproven_is_not_freshness_authority",
    "unspecified_is_not_freshness_authority",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "oldest_member_wins_unproven",
    "newest_member_wins_unproven",
    "min_freshness_unproven",
    "max_freshness_unproven",
    "all_members_same_epoch_unproven",
    "weighted_composite_unproven",
    "source_specific_freshness_unproven",
    "independent_p01_timestamp_unproven",
    "producer_timestamp_unproven",
    "reconstruction_epoch_unproven",
    "valuation_epoch_unproven",
    "accounting_epoch_unproven",
    "current_time_is_not_p01_freshness",
    "missing_freshness_is_not_fresh",
    "stale_p01_is_not_admissible",
    "unproven_cannot_authorize_ignore",
    "unproven_cannot_authorize_fallback",
    "unproven_cannot_authorize_stale_filter",
    "fallback_freshness_state",
    "numeric_provenance_unspecified_does_not_decide_freshness",
    "term_set_unresolved_does_not_decide_freshness",
    "parent_time_semantics_state",
    "parent_freshness_epoch_requirements",
    "u09_freshness_class_comparison",
    "rejected_freshness_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "candidate_freshness_rules_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_member_freshness_inheritance_contract_authority_effect",
    "provenance_digest",
)
P01_HAIRCUT_RESERVE_DEPLETION_SEMANTICS_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_haircut_reserve_depletion_semantics_contract_id",
    "p01_haircut_reserve_depletion_semantics_contract_version",
    "parent_p01_member_freshness_inheritance_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "family_class_labels",
    "family_labels_are_not_exact_term_set",
    "family_labels_are_not_independent_members",
    "family_reduction_only",
    "family_must_not_increase_equity",
    "family_negative_allowed",
    "family_zero_only_by_explicit_policy",
    "family_reduction_only_is_not_per_term_role",
    "family_sign_constraint_is_not_per_term_sign",
    "venue_raw_haircuts_forbidden",
    "future_fees_permission_is_not_reserve_definition",
    "u06_accrued_distinct_is_not_p01_definition",
    "terms_insufficiently_defined_for_algebraic_role",
    "p01_haircut_semantics_resolved_status",
    "p01_haircut_identity_class",
    "p01_haircut_role",
    "p01_haircut_sign_semantics",
    "p01_haircut_unit_class",
    "p01_haircut_applicability",
    "p01_haircut_positive_definition_state",
    "p01_reserve_semantics_resolved_status",
    "p01_reserve_identity_class",
    "p01_reserve_role",
    "p01_reserve_sign_semantics",
    "p01_reserve_unit_class",
    "p01_reserve_applicability",
    "p01_reserve_positive_definition_state",
    "p01_depletion_semantics_resolved_status",
    "p01_depletion_identity_class",
    "p01_depletion_role",
    "p01_depletion_sign_semantics",
    "p01_depletion_unit_class",
    "p01_depletion_applicability",
    "p01_depletion_positive_definition_state",
    "p01_zero_absence_na_rule",
    "p01_haircut_reserve_depletion_combination_rule",
    "p01_precedence_rule",
    "unknown_is_not_zero",
    "unspecified_is_not_zero",
    "missing_is_not_zero",
    "not_applicable_is_not_zero",
    "absent_is_not_zero",
    "unavailable_is_not_zero",
    "embedded_is_not_omit",
    "overlap_is_not_deduplicate",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "unspecified_cannot_authorize_subtraction",
    "unspecified_cannot_authorize_multiplication",
    "unspecified_cannot_authorize_addition",
    "unspecified_cannot_authorize_netting",
    "unspecified_cannot_authorize_omission",
    "unspecified_cannot_authorize_ignore",
    "naming_does_not_prove_algebra",
    "separate_labels_do_not_prove_separate_numeric_effect",
    "same_source_does_not_prove_shared_semantics",
    "missing_implementation_is_not_zero",
    "missing_implementation_is_not_not_applicable",
    "u04_u05_u06_u09_are_not_p01_term_authority",
    "rejected_role_inferences",
    "rejected_formula_inferences",
    "rejected_combination_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "candidate_roles_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_runtime_instance_present",
    "p01_authority_effect",
    "p01_haircut_reserve_depletion_semantics_contract_authority_effect",
    "provenance_digest",
)
P01_EXACT_MEMBER_IDENTITY_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_exact_member_identity_contract_id",
    "p01_exact_member_identity_contract_version",
    "parent_p01_haircut_reserve_depletion_semantics_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "ratification_scope",
    "p01_term_set_resolved_status",
    "p01_exact_member_identity_set",
    "p01_exact_member_count",
    "member_id",
    "identity_level_meaning",
    "identity_is_not_numeric_value",
    "identity_is_not_operator",
    "identity_is_not_formula",
    "identity_is_not_sign",
    "identity_is_not_unit",
    "identity_is_not_applicability",
    "identity_is_not_source",
    "identity_is_not_producer",
    "identity_is_not_freshness",
    "identity_is_not_equity_base_inclusion",
    "identity_is_not_embedding",
    "identity_is_not_u04_u05_u06_overlap",
    "identity_is_not_zero_absence_na",
    "identity_is_not_combination",
    "identity_is_not_precedence",
    "identity_is_not_runtime_binding",
    "identity_is_not_execution_effect",
    "p01m_governed_deployability_conservatism_reduction_is_not_haircut_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_reserve_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_depletion_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_u04",
    "p01m_governed_deployability_conservatism_reduction_is_not_u05",
    "p01m_governed_deployability_conservatism_reduction_is_not_u06",
    "p01m_governed_deployability_conservatism_reduction_is_not_venue_raw",
    "p01m_governed_deployability_conservatism_reduction_is_not_availeq",
    "p01m_governed_deployability_conservatism_reduction_is_not_eq",
    "p01m_governed_deployability_conservatism_reduction_is_not_totaleq",
    "p01m_governed_deployability_conservatism_reduction_is_not_canary_envelope",
    "p01m_governed_deployability_conservatism_reduction_is_not_margin_reserve_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_future_fee_permission",
    "p01_member_role_sign_unit_resolved_status",
    "p01_zero_absence_na_resolved_status",
    "p01_combination_precedence_resolved_status",
    "p01_value_unit_class_resolved_status",
    "p01_applicability_resolved_status",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "identity_does_not_authorize_arithmetic",
    "identity_does_not_close_p01_term_semantics",
    "identity_does_not_close_haircut_reserve_depletion_unspecified",
    "rejected_member_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_runtime_instance_present",
    "p01_authority_effect",
    "p01_exact_member_identity_contract_authority_effect",
    "provenance_digest",
)
P01_VALUE_UNIT_CLASS_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_value_unit_class_contract_id",
    "p01_value_unit_class_contract_version",
    "parent_p01_exact_member_identity_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "member_id",
    "ratification_scope",
    "selected_option",
    "p01_term_set_resolved_status",
    "p01_value_unit_class_resolved_status",
    "p01_value_unit_class",
    "p01_semantic_dimension",
    "p01_parent_dimension_compatibility",
    "p01_requires_dimensional_transformation",
    "p01_direct_additive_subtraction_compatible",
    "p01_unit_identity_is_distinct_from_authority_identity",
    "p01_unit_identity_is_distinct_from_member_identity",
    "p01_settlement_currency_is_not_unit_identity",
    "p01_parent_dimension_is_not_authority_source",
    "unit_does_not_ratify_formula",
    "unit_does_not_ratify_operator",
    "unit_does_not_ratify_sign",
    "unit_does_not_ratify_applicability",
    "unit_does_not_ratify_source_mapping",
    "unit_does_not_close_p01_term_semantics",
    "unit_does_not_close_haircut_reserve_depletion_unspecified",
    "p01_value_unit_class_is_not_ratio",
    "p01_value_unit_class_is_not_percentage",
    "p01_value_unit_class_is_not_bps",
    "p01_value_unit_class_is_not_contracts_qty",
    "p01_value_unit_class_is_not_python_numeric_type",
    "p01m_governed_deployability_conservatism_reduction_is_not_haircut_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_reserve_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_depletion_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_u04",
    "p01m_governed_deployability_conservatism_reduction_is_not_u05",
    "p01m_governed_deployability_conservatism_reduction_is_not_u06",
    "p01m_governed_deployability_conservatism_reduction_is_not_venue_raw",
    "p01m_governed_deployability_conservatism_reduction_is_not_availeq",
    "p01m_governed_deployability_conservatism_reduction_is_not_eq",
    "p01m_governed_deployability_conservatism_reduction_is_not_totaleq",
    "p01m_governed_deployability_conservatism_reduction_is_not_canary_envelope",
    "p01m_governed_deployability_conservatism_reduction_is_not_margin_reserve_alias",
    "p01m_governed_deployability_conservatism_reduction_is_not_future_fee_permission",
    "p01_applicability_resolved_status",
    "p01_member_role_sign_unit_resolved_status",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "rejected_unit_class_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_runtime_instance_present",
    "p01_authority_effect",
    "p01_value_unit_class_contract_authority_effect",
    "provenance_digest",
)
P01_APPLICABILITY_CLASS_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_applicability_class_contract_id",
    "p01_applicability_class_contract_version",
    "parent_p01_value_unit_class_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "member_id",
    "ratification_scope",
    "selected_option",
    "p01_term_set_resolved_status",
    "p01_value_unit_class_resolved_status",
    "p01_value_unit_class",
    "p01_applicability_class_resolved_status",
    "p01_applicability_class",
    "p01_applicability_state_model",
    "p01_applicability_state_applies",
    "p01_applicability_state_does_not_apply",
    "p01_applicability_state_unknown_fail_closed",
    "p01_application_predicate_resolved_status",
    "p01_application_predicate",
    "p01_applicability_resolved_status",
    "p01_applicability_is_distinct_from_value",
    "p01_applicability_is_distinct_from_zero",
    "p01_applicability_is_distinct_from_absence",
    "p01_applicability_is_distinct_from_not_applicable_value_encoding",
    "class_is_not_unconditional_always_on",
    "class_is_not_unconditional_never_on",
    "class_does_not_ratify_predicate",
    "class_does_not_ratify_formula",
    "class_does_not_ratify_operator",
    "class_does_not_ratify_sign",
    "class_does_not_ratify_source_mapping",
    "class_does_not_close_p01_term_semantics",
    "class_does_not_close_haircut_reserve_depletion_unspecified",
    "predicate_true_may_mean_applies",
    "predicate_false_may_mean_does_not_apply",
    "predicate_unknown_must_fail_closed",
    "unknown_cannot_become_false",
    "unknown_cannot_become_does_not_apply",
    "unknown_cannot_become_not_applicable",
    "unknown_cannot_become_zero",
    "missing_cannot_become_zero",
    "missing_cannot_auto_become_does_not_apply",
    "does_not_apply_is_not_numeric_zero",
    "applies_does_not_imply_valid_numeric_value",
    "p01_requiredness_resolved_status",
    "p01_optionality_resolved_status",
    "p01_zero_semantics_resolved_status",
    "p01_absence_semantics_resolved_status",
    "p01_zero_absence_na_resolved_status",
    "p01_input_preconditions_resolved_status",
    "p01_reconstruction_state_preconditions_resolved_status",
    "master_v2_is_not_p01_applicability_authority",
    "double_play_is_not_p01_applicability_authority",
    "top20_is_not_p01_applicability_authority",
    "learning_is_not_p01_applicability_authority",
    "full_core_autonomy_is_not_p01_applicability_authority",
    "venue_raw_is_not_p01_applicability_authority",
    "step_29p_is_not_p01_applicability_authority",
    "live_account_bound_is_not_p01_applicability_authority",
    "u04_u05_u06_applicability_inheritance_forbidden",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "rejected_applicability_class_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_runtime_instance_present",
    "p01_authority_effect",
    "p01_applicability_class_contract_authority_effect",
    "provenance_digest",
)
P01_APPLICATION_PREDICATE_IDENTITY_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_application_predicate_identity_contract_id",
    "p01_application_predicate_identity_contract_version",
    "parent_p01_applicability_class_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "member_id",
    "ratification_scope",
    "selected_option",
    "p01_term_set_resolved_status",
    "p01_value_unit_class_resolved_status",
    "p01_value_unit_class",
    "p01_applicability_class_resolved_status",
    "p01_applicability_class",
    "p01_application_predicate_identity_resolved_status",
    "p01_application_predicate_model",
    "p01_applicability_decision_state_model",
    "p01_applicability_decision_state_applies",
    "p01_applicability_decision_state_does_not_apply",
    "p01_applicability_decision_state_unknown_fail_closed",
    "p01_applicability_decision_is_typed",
    "p01_applicability_decision_is_governed",
    "p01_applicability_decision_must_remain_inside_existing_reconstruction_boundary",
    "p01_applicability_decision_is_not_account_equity_authority",
    "p01_applicability_decision_is_not_parallel_producer",
    "p01_applicability_decision_is_not_trading_logic_authority",
    "p01_applicability_decision_is_distinct_from_p01_value",
    "p01_applicability_decision_is_distinct_from_p01_zero",
    "p01_applicability_decision_is_distinct_from_p01_absence",
    "p01_applicability_decision_is_distinct_from_p01_requiredness",
    "p01_applicability_decision_is_distinct_from_p01_completeness",
    "p01_application_predicate_resolved_status",
    "p01_application_predicate",
    "p01_application_predicate_input_domain_resolved_status",
    "p01_application_true_rule_resolved_status",
    "p01_application_false_rule_resolved_status",
    "identity_does_not_ratify_input_domain",
    "identity_does_not_ratify_true_rule",
    "identity_does_not_ratify_false_rule",
    "identity_does_not_ratify_formula",
    "identity_does_not_ratify_operator",
    "identity_does_not_ratify_sign",
    "identity_does_not_ratify_source_mapping",
    "identity_does_not_close_p01_term_semantics",
    "unknown_or_missing_decision_must_fail_closed",
    "malformed_decision_must_fail_closed",
    "contradictory_decision_must_fail_closed",
    "unsupported_decision_must_fail_closed",
    "unknown_cannot_become_false",
    "unknown_cannot_become_does_not_apply",
    "unknown_cannot_become_not_applicable",
    "unknown_cannot_become_zero",
    "missing_cannot_become_zero",
    "missing_cannot_auto_become_does_not_apply",
    "does_not_apply_is_not_numeric_zero",
    "applies_does_not_imply_valid_numeric_value",
    "p01_requiredness_resolved_status",
    "p01_optionality_resolved_status",
    "p01_zero_semantics_resolved_status",
    "p01_absence_semantics_resolved_status",
    "p01_zero_absence_na_resolved_status",
    "p01_input_preconditions_resolved_status",
    "p01_reconstruction_state_preconditions_resolved_status",
    "master_v2_is_not_p01_predicate_authority",
    "double_play_is_not_p01_predicate_authority",
    "top20_is_not_p01_predicate_authority",
    "learning_is_not_p01_predicate_authority",
    "full_core_autonomy_is_not_p01_predicate_authority",
    "venue_raw_is_not_p01_predicate_authority",
    "step_29p_is_not_p01_predicate_authority",
    "live_account_bound_is_not_p01_predicate_authority",
    "u04_u05_u06_predicate_inheritance_forbidden",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "rejected_application_predicate_identity_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_runtime_instance_present",
    "p01_authority_effect",
    "p01_application_predicate_identity_contract_authority_effect",
    "provenance_digest",
)
P01_APPLICATION_PREDICATE_INPUT_DOMAIN_IDENTITY_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_application_predicate_input_domain_identity_contract_id",
    "p01_application_predicate_input_domain_identity_contract_version",
    "parent_p01_application_predicate_identity_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "member_id",
    "ratification_scope",
    "selected_option",
    "p01_term_set_resolved_status",
    "p01_value_unit_class_resolved_status",
    "p01_value_unit_class",
    "p01_applicability_class_resolved_status",
    "p01_applicability_class",
    "p01_application_predicate_identity_resolved_status",
    "p01_application_predicate_model",
    "p01_predicate_input_domain_identity_resolved_status",
    "p01_predicate_input_domain_boundary_resolved_status",
    "p01_predicate_input_domain_class",
    "p01_predicate_input_domain_typed",
    "p01_predicate_input_domain_governed",
    "p01_predicate_input_domain_must_remain_inside_existing_reconstruction_boundary",
    "p01_predicate_input_domain_is_not_account_equity_authority",
    "p01_predicate_input_domain_is_not_parallel_producer",
    "p01_predicate_input_domain_is_not_trading_logic_authority",
    "allowed_input_class",
    "input_domain_is_closed_world",
    "input_domain_default",
    "input_domain_authority_effect",
    "new_authority_owner",
    "new_parallel_producer",
    "new_universe",
    "cross_system_inputs_allowed",
    "trading_logic_inputs_allowed",
    "venue_raw_inputs_allowed",
    "live_execution_state_inputs_allowed",
    "unratified_fact_admission",
    "implicit_input_promotion",
    "foreign_system_state_promotion",
    "missing_required_input_result",
    "malformed_input_result",
    "contradictory_input_result",
    "unsupported_input_result",
    "unratified_input_result",
    "does_not_apply_requires_explicit_false_rule",
    "missing_does_not_mean_does_not_apply",
    "zero_does_not_mean_does_not_apply",
    "absence_does_not_mean_does_not_apply",
    "reconstruction_incomplete_does_not_mean_does_not_apply",
    "p01_application_predicate_input_domain_resolved_status",
    "p01_predicate_concrete_input_members_resolved_status",
    "p01_predicate_required_fields_resolved_status",
    "p01_predicate_optional_fields_resolved_status",
    "p01_application_true_rule_resolved_status",
    "p01_application_false_rule_resolved_status",
    "p01_input_readiness_rule_resolved_status",
    "p01_input_freshness_rule_resolved_status",
    "p01_input_normalization_rule_resolved_status",
    "identity_does_not_ratify_concrete_members",
    "identity_does_not_ratify_required_fields",
    "identity_does_not_ratify_optional_fields",
    "identity_does_not_ratify_true_rule",
    "identity_does_not_ratify_false_rule",
    "identity_does_not_ratify_formula",
    "identity_does_not_ratify_operator",
    "identity_does_not_ratify_sign",
    "identity_does_not_ratify_source_mapping",
    "identity_does_not_close_p01_term_semantics",
    "master_v2_is_not_p01_predicate_input_authority",
    "double_play_is_not_p01_predicate_input_authority",
    "top20_is_not_p01_predicate_input_authority",
    "learning_is_not_p01_predicate_input_authority",
    "full_core_autonomy_is_not_p01_predicate_input_authority",
    "venue_raw_is_not_p01_predicate_input_authority",
    "step_29p_is_not_p01_predicate_input_authority",
    "live_account_bound_is_not_p01_predicate_input_authority",
    "u04_u05_u06_input_inheritance_forbidden",
    "risk_sizing_input_domains_are_not_p01_predicate_input",
    "missing_input_fail_closed",
    "malformed_input_fail_closed",
    "rejected_application_predicate_input_domain_identity_inferences",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "term_semantics_resolved_status",
    "unspecified_closed_status",
    "p01_runtime_instance_present",
    "p01_authority_effect",
    "p01_application_predicate_input_domain_identity_contract_authority_effect",
    "provenance_digest",
)
P01_RECONSTRUCTION_SEMANTIC_AND_ALGEBRA_CLOSEOUT_REQUIRED_FIELDS: tuple[str, ...] = (
    "p01_reconstruction_semantic_and_algebra_closeout_contract_id",
    "p01_reconstruction_semantic_and_algebra_closeout_contract_version",
    "parent_p01_application_predicate_input_domain_identity_contract_schema_class",
    "parent_p01_term_contract_schema_class",
    "target_semantic_dimension_id",
    "policy_id",
    "term_id",
    "member_id",
    "ratification_scope",
    "selected_option",
    "p01_closeout_model",
    "p01_predicate_input_member",
    "p01_predicate_input_member_class",
    "p01_predicate_concrete_input_member_count",
    "p01_predicate_concrete_input_members_resolved_status",
    "p01_predicate_required_fields_resolved_status",
    "p01_predicate_optional_fields_resolved_status",
    "p01_application_true_rule_resolved_status",
    "p01_application_false_rule_resolved_status",
    "p01_application_predicate_resolved_status",
    "p01_application_predicate",
    "p01_application_predicate_input_domain_resolved_status",
    "p01_requiredness_resolved_status",
    "p01_optionality_resolved_status",
    "p01_zero_semantics_resolved_status",
    "p01_absence_semantics_resolved_status",
    "p01_zero_absence_na_resolved_status",
    "p01_input_readiness_rule_resolved_status",
    "p01_input_freshness_rule_resolved_status",
    "p01_input_normalization_rule_resolved_status",
    "p01_numeric_value_semantics_resolved_status",
    "p01_internal_value_semantics_resolved_status",
    "p01_productive_external_source_mapping_resolved_status",
    "formula_ratified_status",
    "operator_ratified_status",
    "sign_ratified_status",
    "p01_operator",
    "p01_sign_semantics",
    "p01_equity_base_inclusion_resolved_status",
    "p01_equity_base_inclusion_status",
    "p01_embedded_state_resolved_status",
    "p01_embedded_state",
    "p01_u04_overlap_resolved_status",
    "p01_u04_overlap_state",
    "p01_u05_overlap_resolved_status",
    "p01_u05_overlap_state",
    "double_counting_forbidden",
    "pre_p01_equity_base_excludes_p01_governed_reduction",
    "p01_governed_reduction_is_separate_reconstruction_term",
    "p01_product_semantics_complete_status",
    "p01_reconstruction_algebra_contract_complete_status",
    "p01_haircut_reserve_depletion_unspecified_closed_status",
    "reconstruction_algebra_complete_status",
    "p01_productive_directive_producer_implemented_status",
    "p01_productive_runtime_binding_added_status",
    "external_p01_runtime_blocker",
    "identity_does_not_promote_prior_candidates",
    "u04_u05_u06_input_inheritance_forbidden",
    "u04_u05_u06_predicate_inheritance_forbidden",
    "master_v2_is_not_p01_authority",
    "double_play_is_not_p01_authority",
    "live_execution_is_not_p01_authority",
    "missing_does_not_mean_does_not_apply",
    "zero_does_not_mean_does_not_apply",
    "absence_does_not_mean_does_not_apply",
    "reconstruction_incomplete_does_not_mean_does_not_apply",
    "does_not_apply_requires_explicit_false_rule",
    "p01_authority_effect",
    "p01_reconstruction_semantic_and_algebra_closeout_contract_authority_effect",
    "remaining_unresolved_semantics",
    "evidence_classification",
    "contradiction_state",
    "p01_runtime_instance_present",
    "provenance_digest",
)
