"""CURRENT MF N≤5 instrument runtime identity closure — authority pins."""

from __future__ import annotations

OWNER = "ops.current_mf_n5_instrument_runtime_identity_closure_v1"
CONTRACT_ID = "CURRENT_MF_N5_INSTRUMENT_RUNTIME_IDENTITY_CLOSURE_CONTRACT_V1"
SLICE_ID = "N5_INSTRUMENT_RUNTIME_IDENTITY_CLOSURE_V1"

POST_ALLOWED = False
EXTERNAL_EFFECT_AUTHORIZED = False
MULTI_FUTURE_RUNTIME_AUTHORIZED = False
N_GT_1_ENABLED = False
MAX_POSITIONS_EFFECTIVE = 1

JOIN_CAP23_SELECTION_AUTHORITY = False
JOIN_CAP24_BINDING_AUTHORITY = False
JOIN_TRADING_AUTHORITY = False

FAILURE_C1_FANOUT_SHARED_FORBIDDEN = "N5_IDENTITY_C1_FANOUT_SHARED_FORBIDDEN"
FAILURE_C1_LANE_MISSING = "N5_IDENTITY_C1_LANE_MISSING"
FAILURE_C1_INSTRUMENT_MISMATCH = "N5_IDENTITY_C1_INSTRUMENT_MISMATCH"
FAILURE_POSITION_SHARED_FORBIDDEN = "N5_IDENTITY_POSITION_SHARED_FORBIDDEN"
FAILURE_DUPLICATE_INSTRUMENT_OWNERSHIP = "N5_IDENTITY_DUPLICATE_INSTRUMENT_OWNERSHIP"
FAILURE_DUPLICATE_LANE_OWNERSHIP = "N5_IDENTITY_DUPLICATE_LANE_OWNERSHIP"
FAILURE_BINDING_MISMATCH = "N5_IDENTITY_BINDING_MISMATCH"
FAILURE_RECONCILIATION_GLOBAL = "N5_IDENTITY_RECONCILIATION_GLOBAL_FAIL_CLOSED"
FAILURE_RECONCILIATION_INSTRUMENT = "N5_IDENTITY_RECONCILIATION_INSTRUMENT_FAIL_CLOSED"
FAILURE_LANE_GENERATION_STALE = "N5_IDENTITY_LANE_GENERATION_STALE"
FAILURE_LIFECYCLE_ORPHAN = "N5_IDENTITY_LIFECYCLE_ORPHAN_FORBIDDEN"

LANE_IDENTITY_MANIFEST_BASENAME = "lane_runtime_instrument_identity_manifest_v1.json"
