"""P1 Master V2 / Double Play Evidence & Input Plane — authority + schema constants (contract only)."""

from __future__ import annotations

from typing import Final

PACKAGE_MARKER: Final[str] = (
    "MASTER_V2_DOUBLE_PLAY_EVIDENCE_INPUT_PLANE_P1_AUTHORITY_CONTRACTS_AND_SCHEMAS_V1=true"
)
WORKPACKAGE_ID: Final[str] = (
    "P1_MASTER_V2_DOUBLE_PLAY_EVIDENCE_INPUT_PLANE_AUTHORITY_CONTRACTS_AND_SCHEMAS_V1"
)
OWNER: Final[str] = (
    "governance.master_v2_double_play_evidence_input_plane_p1_authority_contracts_and_schemas_v1"
)
NORMATIVE_SPEC: Final[str] = (
    "docs/ops/specs/EVIDENCE_INPUT_PLANE_P1_AUTHORITY_CONTRACTS_AND_SCHEMAS_V1.md"
)
OWNER_DECISION_CONFIG: Final[str] = (
    "config/governance/master_v2_double_play_evidence_input_plane_p1_owner_decision_v1.json"
)
BASELINE_SHA: Final[str] = "43f98b74e39f1e85d2fda20eb4c90ce70f3e62de"

# Owner O-002 ratification (encoded exactly from OWNER_GO).
O_002_RATIFIED: Final[bool] = True
L6_EXTERNAL_EVIDENCE_ADMISSIBILITY: Final[str] = "YES_BOUNDED_TYPED_ONLY"
L6_SELECTED_DIRECTION: Final[str] = "OPTION_B_TYPED_L6_EVIDENCE_SEAM"

PRESERVE_EXISTING_PROPOSED_D_T_SEAM: Final[bool] = True
PRESERVE_EXISTING_P4_SEMANTICS: Final[bool] = True
PROPOSED_D_T_MUST_NOT_BECOME_A_B_INFORMATION_CARRIER: Final[bool] = True

A_AUTHORITY: Final[str] = "BOUNDED_EVIDENCE_ADJUDICATION_ONLY"
A_TRADING_AUTHORITY: Final[str] = "NONE"
B_AUTHORITY: Final[str] = "BOUNDED_DP_INPUT_CREATION_AND_BINDING_ONLY"
B_TRADING_AUTHORITY: Final[str] = "NONE"
B_DP_STATE_MUTATION_AUTHORITY: Final[str] = "NONE"

L6_SEMANTIC_AUTHORITY: Final[str] = "UNCHANGED"
L6_INTERPRETATION_AUTHORITY: Final[str] = "L6_ONLY"

B_MAY_BIND_TYPED_L6_EVIDENCE: Final[bool] = True
B_MAY_COMPUTE_FINAL_D_T: Final[bool] = False
B_MAY_SELECT_D_T_FORMULA: Final[bool] = False
B_MAY_COLLAPSE_HETEROGENEOUS_EVIDENCE_TO_PROPOSED_D_T: Final[bool] = False

DIRECT_PRODUCER_TO_B: Final[bool] = False
DIRECT_PRODUCER_TO_DP: Final[bool] = False
DIRECT_MI_LEARNING_OPTIMIZATION_META_LEARNING_RESEARCH_TO_L6: Final[bool] = False

INSTRUMENT_BINDING_REQUIRED: Final[bool] = True
EPOCH_BINDING_REQUIRED: Final[bool] = True
FRESHNESS_REQUIRED: Final[bool] = True
PROVENANCE_REQUIRED: Final[bool] = True
SOURCE_EVIDENCE_DIGEST_REQUIRED: Final[bool] = True
DETERMINISTIC_BINDING_REQUIRED: Final[bool] = True
FAIL_CLOSED: Final[bool] = True

FINAL_D_T_FORMULA_SELECTED: Final[bool] = False
NO_D_T_FORMULA_SELECTION_IN_P1: Final[bool] = True

O_001_REMAINS_SEPARATE: Final[bool] = True
NO_O_001_REPAIR_OR_ADJUDICATION: Final[bool] = True

PRODUCTIVE_L6_BINDING_AUTHORIZED: Final[bool] = False
A_RUNTIME_IMPLEMENTATION_AUTHORIZED: Final[bool] = False
B_RUNTIME_IMPLEMENTATION_AUTHORIZED: Final[bool] = False
PRODUCTIVE_ACTIVATION_AUTHORIZED: Final[bool] = False

RUNTIME_AUTHORIZATION_EFFECT: Final[str] = "NONE"
IMPLEMENTS_COMPONENT_A_RUNTIME: Final[bool] = False
IMPLEMENTS_COMPONENT_B_RUNTIME: Final[bool] = False

ENVELOPE_SCHEMA_VERSION: Final[str] = "canonical_master_v2_evidence_envelope.v1"
BINDING_SCHEMA_VERSION: Final[str] = "canonical_dp_layer_input_binding.v1"
L6_TYPED_INPUT_SCHEMA_VERSION: Final[str] = "l6_bounded_typed_external_evidence_input.v1"

# P1 admissibility epistemic label for census (post O-002).
L6_CENSUS_EXTERNAL_EVIDENCE_ADMISSIBILITY: Final[str] = "PROVEN_BOUNDED_TYPED_ONLY"

assert O_002_RATIFIED is True
assert L6_EXTERNAL_EVIDENCE_ADMISSIBILITY == "YES_BOUNDED_TYPED_ONLY"
assert L6_SELECTED_DIRECTION == "OPTION_B_TYPED_L6_EVIDENCE_SEAM"
assert A_TRADING_AUTHORITY == "NONE"
assert B_TRADING_AUTHORITY == "NONE"
assert B_DP_STATE_MUTATION_AUTHORITY == "NONE"
assert B_MAY_COMPUTE_FINAL_D_T is False
assert B_MAY_SELECT_D_T_FORMULA is False
assert B_MAY_COLLAPSE_HETEROGENEOUS_EVIDENCE_TO_PROPOSED_D_T is False
assert FINAL_D_T_FORMULA_SELECTED is False
assert A_RUNTIME_IMPLEMENTATION_AUTHORIZED is False
assert B_RUNTIME_IMPLEMENTATION_AUTHORIZED is False
assert PRODUCTIVE_L6_BINDING_AUTHORIZED is False

__all__ = [
    "A_AUTHORITY",
    "A_RUNTIME_IMPLEMENTATION_AUTHORIZED",
    "A_TRADING_AUTHORITY",
    "B_AUTHORITY",
    "B_DP_STATE_MUTATION_AUTHORITY",
    "B_MAY_BIND_TYPED_L6_EVIDENCE",
    "B_MAY_COLLAPSE_HETEROGENEOUS_EVIDENCE_TO_PROPOSED_D_T",
    "B_MAY_COMPUTE_FINAL_D_T",
    "B_MAY_SELECT_D_T_FORMULA",
    "B_RUNTIME_IMPLEMENTATION_AUTHORIZED",
    "B_TRADING_AUTHORITY",
    "BASELINE_SHA",
    "BINDING_SCHEMA_VERSION",
    "DETERMINISTIC_BINDING_REQUIRED",
    "DIRECT_MI_LEARNING_OPTIMIZATION_META_LEARNING_RESEARCH_TO_L6",
    "DIRECT_PRODUCER_TO_B",
    "DIRECT_PRODUCER_TO_DP",
    "ENVELOPE_SCHEMA_VERSION",
    "EPOCH_BINDING_REQUIRED",
    "FAIL_CLOSED",
    "FINAL_D_T_FORMULA_SELECTED",
    "FRESHNESS_REQUIRED",
    "IMPLEMENTS_COMPONENT_A_RUNTIME",
    "IMPLEMENTS_COMPONENT_B_RUNTIME",
    "INSTRUMENT_BINDING_REQUIRED",
    "L6_CENSUS_EXTERNAL_EVIDENCE_ADMISSIBILITY",
    "L6_EXTERNAL_EVIDENCE_ADMISSIBILITY",
    "L6_INTERPRETATION_AUTHORITY",
    "L6_SELECTED_DIRECTION",
    "L6_SEMANTIC_AUTHORITY",
    "L6_TYPED_INPUT_SCHEMA_VERSION",
    "NO_D_T_FORMULA_SELECTION_IN_P1",
    "NO_O_001_REPAIR_OR_ADJUDICATION",
    "NORMATIVE_SPEC",
    "O_001_REMAINS_SEPARATE",
    "O_002_RATIFIED",
    "OWNER",
    "OWNER_DECISION_CONFIG",
    "PACKAGE_MARKER",
    "PRESERVE_EXISTING_P4_SEMANTICS",
    "PRESERVE_EXISTING_PROPOSED_D_T_SEAM",
    "PRODUCTIVE_ACTIVATION_AUTHORIZED",
    "PRODUCTIVE_L6_BINDING_AUTHORIZED",
    "PROPOSED_D_T_MUST_NOT_BECOME_A_B_INFORMATION_CARRIER",
    "PROVENANCE_REQUIRED",
    "RUNTIME_AUTHORIZATION_EFFECT",
    "SOURCE_EVIDENCE_DIGEST_REQUIRED",
    "WORKPACKAGE_ID",
]
