"""Constants for CURRENT MF N=5 isolated lane-instance topology V1."""

from __future__ import annotations

from src.ops.current_mf_member_to_pinned_cap23_n1_adapter_v1.constants_v1 import (
    CROSS_UNIVERSE_CANDIDATE_BORROWING as PIN_CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK as PIN_CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN as PIN_CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT as PIN_CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING as PIN_CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION as PIN_CROSS_UNIVERSE_SELECTION,
    INSTRUMENT_ID_ALONE_SUFFICIENT as PIN_INSTRUMENT_ID_ALONE_SUFFICIENT,
    MULTI_UNIVERSE_MERGE as PIN_MULTI_UNIVERSE_MERGE,
)
from src.ops.mf_membership_context_artifact_contract_v1 import (
    CARDINALITY_MODE as MEMBERSHIP_CARDINALITY_MODE,
    N_VALUE as MEMBERSHIP_N_VALUE,
)
from src.ops.single_selected_future_policy_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP23_MAX_POSITIONS_EFFECTIVE,
)

OWNER = "ops.current_mf_n5_isolated_lane_instance_topology_v1"
CONTRACT_ID = "CURRENT_MF_N5_ISOLATED_LANE_INSTANCE_TOPOLOGY_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_n5_isolated_lane_instance_topology.v1"

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
LANE_TOPOLOGY_RANKING_AUTHORITY = False
LANE_TOPOLOGY_MEMBERSHIP_AUTHORITY = False
LANE_TOPOLOGY_CAP23_SELECTION_AUTHORITY = False
LANE_TOPOLOGY_CAP24_BINDING_AUTHORITY = False
LANE_TOPOLOGY_TRADING_AUTHORITY = False
LANE_TOPOLOGY_EXECUTION_AUTHORITY = False

MEMBERSHIP_OWNER = "ops.mf_membership_rotation_controller_v1"
LANE_MAPPING_OWNER = OWNER
CAP23_SELECTION_OWNER = "ops.single_selected_future_policy_v1"
CAP24_BINDING_OWNER = "ops.single_selected_future_runtime_binding_v1"

MAX_LANE_COUNT = int(MEMBERSHIP_N_VALUE)
assert MAX_LANE_COUNT == 5
LANE_IDS: tuple[str, ...] = tuple(f"LANE_{index}" for index in range(1, MAX_LANE_COUNT + 1))
LANE_CARDINALITY_MODE = MEMBERSHIP_CARDINALITY_MODE
LANE_IDENTITY_ENCODES_RANK = False
NO_PADDING = True
ONE_INSTRUMENT_PER_LANE = True
ONE_LANE_PER_INSTRUMENT = True
PURE_RANK_REORDER_CAUSES_LANE_MOVE = False

OCCUPANCY_EMPTY = "EMPTY"
OCCUPANCY_OCCUPIED = "OCCUPIED"

INITIAL_ASSIGNMENT_POLICY = "BOOTSTRAP_PREFIX_FILL_LOWEST_LANE_IDS_FROM_MEMBERSHIP_ORDER"
RETAINED_MEMBER_POLICY = "KEEP_EXISTING_LANE_ID"
EXIT_POLICY = "RELEASE_LANE_TO_EMPTY"
ENTRY_POLICY = "ASSIGN_DETERMINISTIC_AVAILABLE_LANE"
FREE_LANE_ASSIGNMENT_POLICY = (
    "LOWEST_EMPTY_LANE_ID_IN_LANE_1_TO_LANE_5_ORDER_ENTERED_ORDER_FROM_CURRENT_MEMBERSHIP_DELTA"
)
RESTART_RECONSTRUCTION_POLICY = (
    "FAIL_CLOSED_WITHOUT_EXPLICIT_PRIOR_TOPOLOGY_NO_MEMBERSHIP_OR_RANKING_RECONSTRUCTION"
)

UNIVERSE_ISOLATION = "HARD"
UNIVERSE_ISOLATION_ENFORCED = True
CROSS_UNIVERSE_SELECTION = PIN_CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = PIN_CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = PIN_CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = PIN_CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = PIN_CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = PIN_CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = PIN_MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = PIN_INSTRUMENT_ID_ALONE_SUFFICIENT

MF_PRODUCTIVE_JOIN = False
FIVE_LANE_RUNTIME_CREATED = False
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = False
MF_SINGLE_EGRESS_REWIRED = False
MAX_POSITIONS_EFFECTIVE = int(CAP23_MAX_POSITIONS_EFFECTIVE)
assert MAX_POSITIONS_EFFECTIVE == 1

CAP23_CHANGE_REQUIRED = False
CAP24_CHANGE_REQUIRED = False
MASTER_V2_CHANGE_REQUIRED = False
DOUBLE_PLAY_CHANGE_REQUIRED = False
DURABLE_TOPOLOGY_PERSISTENCE_IMPLEMENTED = False
DURABLE_RESTART_AUTHORITY_INVENTED = False

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(
    {
        "produce_single_selected_future_v1",
        "run_single_selected_future_policy_v1",
        "persist_selection_bundle_atomic_v1",
        "_pick_top_eligible",
        "mf_canonical_single_egress_authority_handoff_contract_v1",
        "master_v2",
        "double_play",
        "execution",
        "top_n_active_set",
    }
)
