"""E4 productive host join — transport only, not an authority owner."""

from __future__ import annotations

from src.ops.governed_productive_account_equity_authority_producer_v1.constants_v1 import (
    ACCOUNT_EQUITY_AUTHORITY_OWNER,
)
from src.ops.treasury_capital_admission_to_account_equity_orchestration_v1.constants_v1 import (
    ACCOUNT_EQUITY_AUTHORITY as E4_ACCOUNT_EQUITY_AUTHORITY,
    CAPITAL_ADMISSION_AUTHORITY,
    EDGE_SEAM_ID as E4_EDGE_SEAM_ID,
)

CAPABILITY_ID = "TREASURY_CAPITAL_ADMISSION_TO_ACCOUNT_EQUITY_ORCHESTRATION_PRODUCTIVE_HOST_JOIN_V1"
PACKAGE_MARKER = (
    "TREASURY_CAPITAL_ADMISSION_TO_ACCOUNT_EQUITY_ORCHESTRATION_PRODUCTIVE_HOST_JOIN_V1=true"
)
OWNER = "ops.treasury_capital_admission_to_account_equity_orchestration_productive_host_join_v1"
SCHEMA_VERSION = (
    "treasury_capital_admission_to_account_equity_orchestration_productive_host_join.v1"
)
CONTRACT_VERSION = "v1"

WP_ID = CAPABILITY_ID
OWNER_GO = f"OWNER_GO_{WP_ID}"
ALLOWED_WP_OWNER_GOS = frozenset({OWNER_GO, WP_ID, "OWNER_GO=true"})

JOIN_SEAM_ID = "TREASURY_CAPITAL_ADMISSION_TO_ACCOUNT_EQUITY_ORCHESTRATION_PRODUCTIVE_HOST_JOIN_V1"
UPSTREAM_E4_EDGE_SEAM_ID = E4_EDGE_SEAM_ID
PHASE_2_RECONCILIATION_JOIN_OWNER = "ops.treasury_phase_2_read_only_reconciliation_v1"
E4_ORCHESTRATION_JOIN_OWNER = "ops.treasury_capital_admission_to_account_equity_orchestration_v1"
PRODUCTIVE_ACCOUNT_EQUITY_HOST = ACCOUNT_EQUITY_AUTHORITY_OWNER

JOIN_CLASS = "TYPED_PRODUCTIVE_HOST_JOIN_NOT_OWNER"
PARALLEL_ACCOUNT_EQUITY_AUTHORITY_ADDED = False
SECOND_ACCOUNT_EQUITY_AUTHORITY_ADDED = False

RUNTIME_AUTHORIZATION_EFFECT = "NONE"
NETWORK_ALLOWED = False
NETWORK_EXECUTION_AUTHORIZED = False
CREDENTIAL_LOAD_AUTHORIZED = False
TREASURY_MUTATION_AUTHORIZED = False
EXTERNAL_EFFECT_AUTHORIZED = False
RISK_ADMISSIBLE_MINT_AUTHORIZED = False
STEP_29P_MINT_AUTHORIZED = False
AVAILABLE_FOR_SIZING_MINT_AUTHORIZED = False
SIZING_AUTHORITY_CHANGED = False

CAPITAL_ADMISSION_OWNER = CAPITAL_ADMISSION_AUTHORITY
assert E4_ACCOUNT_EQUITY_AUTHORITY == PRODUCTIVE_ACCOUNT_EQUITY_HOST

EARLIEST_NEW_REAL_BLOCKER_AFTER_WP = (
    "C08_TREASURY_OBSERVED_OR_RECONCILED_CAPITAL_PRODUCTIVE_SIZING_SOURCE_NOT_BOUND"
)
