"""Constants for Phase 11 §11.17 SIMULATED_LIFECYCLE_PROVEN evidence closure."""

from __future__ import annotations

CAPABILITY_ID = "PHASE_11_SECTION_11_17_SIMULATED_LIFECYCLE_PROVEN_EVIDENCE_CLOSURE_V1"
PACKAGE_MARKER = "PHASE_11_SECTION_11_17_SIMULATED_LIFECYCLE_PROVEN_EVIDENCE_CLOSURE_V1=true"
OWNER = "ops.phase_11_section_11_17_simulated_lifecycle_proven_evidence_closure_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "phase_11_section_11_17_simulated_lifecycle_proven_evidence_closure.v1"
CONTRACT_VERSION = "v1"

SECTION_11_17_FIELD = "SIMULATED_LIFECYCLE_PROVEN"
CLOSURE_METHOD = "EXISTING_EVIDENCE_BINDING"

SOURCE_CAPABILITY_ID = "CAPABILITY_7_1_SIMULATED_ENTRY_REDUCE_EXIT_ACTIONABILITY_EVIDENCE_V1"
SOURCE_EVIDENCE_DIRNAME = "capability_7_1_simulated_entry_reduce_exit_actionability_evidence_v1"
SOURCE_OWNER = "ops.simulated_entry_reduce_exit_actionability_evidence_v1"
SOURCE_HISTORICAL_REPOSITORY_SHA = "5d09b88c8ee415cc39ddff3cde1ab1348e1147b3"
SOURCE_EVIDENCE_DIGEST = "e19001d4c3bc4f3bd9d5ab91c5d880a39df3c3a0edaea3dc2e3f200c7e62c13b"
SOURCE_CONFIG_DIGEST = "59f3062f719dcf4efe73aaa52b74527969aa1fb746b7cb9b12cdd69a5bdfc31b"

EVIDENCE_DIRNAME = "phase_11_section_11_17_simulated_lifecycle_proven_evidence_closure_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"

CORE_LOGIC_CHANGE = False
ACTIVATION_STATE = "not_activated"
NETWORK_SESSION_STARTED = False
CREDENTIAL_ACCESS = False
ORDER_SUBMIT_REACHABLE = False
CAPABILITY_11_13_STARTED = False

# Predecessor §11.17 field retained; this package binds only SIMULATED_LIFECYCLE_PROVEN.
CANONICAL_STATEFUL_CORE_PROVEN = True
SIMULATED_LIFECYCLE_PROVEN = True
TESTNET_LIFECYCLE_PROVEN = False
LIVE_PRIVATE_READ_ONLY_PROVEN = False
LIVE_ORDER_LIFECYCLE_PROVEN = False
LIVE_RECONCILIATION_PROVEN = False
LIVE_RESTART_PROVEN = False
LIVE_UNKNOWN_SUBMIT_RECOVERY_PROVEN = False
LIVE_DUPLICATE_ORDER_PREVENTION_PROVEN = False
LIVE_PARTIAL_FILL_RECOVERY_PROVEN = False
LIVE_KILL_SWITCH_PROVEN = False
LIVE_AUTONOMOUS_DEGRADATION_PROVEN = False
LIVE_AUTONOMOUS_RECOVERY_PROVEN = False
LIVE_ACCOUNTING_RECONSTRUCTION_PROVEN = False
LIVE_EVIDENCE_VERIFIED = False
OWNER_INTERVENTION_REQUIRED_FOR_ROUTINE_OPERATION = True
OWNER_INTERVENTION_REQUIRED_FOR_SCOPE_OR_LIMIT_CHANGE = True
CORE_LOGIC_PARITY_ACROSS_MODES = True
FULLY_AUTONOMOUS_LIVE_TRADING_READY = False
FULLY_AUTONOMOUS_LIVE_TRADING_ACTIVE = False

# Cap 7.1 claim keys required for §11.17 SIMULATED_LIFECYCLE_PROVEN semantics.
REQUIRED_SOURCE_TRUE_CLAIMS: tuple[str, ...] = (
    "ENTRY_END_TO_END_EVIDENCE_PROVEN",
    "EXIT_END_TO_END_EVIDENCE_PROVEN",
    "NONZERO_FEE_EVIDENCE_PROVEN",
    "NONZERO_SLIPPAGE_EVIDENCE_PROVEN",
    "LONG_LIFECYCLE_PROVEN",
    "SHORT_LIFECYCLE_PROVEN",
    "PARTIAL_REDUCE_LIFECYCLE_PROVEN",
    "ACCOUNTING_RECONSTRUCTION_MATCH",
    "RESTART_DURING_OPEN_POSITION_PROVEN",
    "DETERMINISTIC_REPLAY_PROVEN",
    "EVIDENCE_VERIFIER_PASS",
    "ADVERSE_EXIT_PROVEN",
    "PROFIT_EXIT_PROVEN",
    "TIME_OR_INVALIDATION_EXIT_PROVEN",
    "CORE_LOGIC_UNCHANGED",
)
REQUIRED_SOURCE_FALSE_CLAIMS: tuple[str, ...] = (
    "ORDER_SIDE_EFFECT_OCCURRED",
    "NETWORK_SESSION_STARTED",
    "AUTHORIZATION_CONSUMED",
    "ACTIVATION_CHANGED",
    "POSITION_FLIP_ALLOWED",
)

CANONICAL_FIELD_SEMANTICS = (
    "Master Runbook §11.17 second readiness gate: deterministic simulated "
    "Entry/Reduce/Exit lifecycle evidence (Cap 7.1 Simulated Entry, Reduce and "
    "Exit Actionability Evidence) with nonzero Fee/Slippage, accounting "
    "reconstruction, and restart proofs on the no-order simulated path. "
    "Distinct from CANONICAL_STATEFUL_CORE_PROVEN (Cap 7.2), Testnet/Live proven "
    "fields, READY, and Cap 11.13 activation."
)
