"""Constants for productive max-age research evidence accumulation v1."""

from __future__ import annotations

PACKAGE_MARKER = (
    "MASTER_V2_CANONICAL_VOLATILITY_MAX_AGE_PRODUCTIVE_RESEARCH_"
    "EVIDENCE_ACCUMULATION_CAPABILITY_V1=true"
)

CAPABILITY_ID = (
    "MASTER_V2_CANONICAL_VOLATILITY_MAX_AGE_PRODUCTIVE_RESEARCH_EVIDENCE_ACCUMULATION_CAPABILITY_V1"
)
# Review-mode alias for the numeric productive evidence-accumulation step.
REVIEW_MODE_ID = (
    "MASTER_V2_CANONICAL_VOLATILITY_NUMERIC_MAX_AGE_PRODUCTIVE_RESEARCH_EVIDENCE_ACCUMULATION_V1"
)
NUMERIC_PRODUCTIVE_ACCUMULATION_CAPABILITY_ID = REVIEW_MODE_ID
CAPABILITY_VERSION = "canonical_volatility_max_age_productive_research_evidence_accumulation/v1"
NUMERIC_PRODUCTIVE_ACCUMULATION_SPEC_REL_PATH = (
    "docs/ops/specs/"
    "MASTER_V2_CANONICAL_VOLATILITY_NUMERIC_MAX_AGE_PRODUCTIVE_"
    "RESEARCH_EVIDENCE_ACCUMULATION_V1.md"
)
EVIDENCE_SCHEMA_VERSION = "canonical_volatility_max_age_productive_research_evidence_record/v1"
LEDGER_SCHEMA_VERSION = "canonical_volatility_max_age_productive_research_evidence_ledger/v1"
SESSION_CONTRACT_VERSION = "canonical_volatility_max_age_productive_research_evidence_session/v1"
COVERAGE_SCHEMA_VERSION = "canonical_volatility_max_age_productive_research_evidence_coverage/v1"

OWNER = "research.canonical_volatility_max_age_productive_research_evidence_accumulation_v1"

# Hard safety — accumulation only; never trading / threshold authority.
NUMERIC_MAX_AGE_DECIDED = False
THRESHOLD_STATUS = "UNRESOLVED_MAX_AGE"
NUMERIC_THRESHOLD_SELECTED = False
PARAMETER_PROMOTED = False
ENFORCEMENT_APPLIED = False
ALPHA_MUTATION_OCCURRED = False
PRODUCTIVE_POLICY_MUTATION_OCCURRED = False
CONFIG_MUTATION_OCCURRED = False
PRODUCTIVE_TRADING_BEHAVIOR_CHANGED = False
LIVE_TESTNET_ORDER_ACTIVATION_OCCURRED = False
ORDER_AUTHORITY_INTRODUCED = False
REGIME_LABEL_MUTATES_ALPHA = False
REGIME_LABEL_MUTATES_POLICY = False
REGIME_LABEL_MUTATES_POSITION = False
REGIME_LABEL_IS_RESEARCH_METADATA_ONLY = True
LIVE_AUTHORIZATION = False
HARD_STOP = True
READY_FOR_THRESHOLD_SELECTION = False
READY_FOR_PARAMETER_PROMOTION = False
READY_FOR_ENFORCEMENT = False

AGE_REFERENCE_CLOCK = "MARKET_EVENT_TIME"
AGE_FORMULA_VERSION = "reference_market_event_time_minus_volatility_as_of_event_time/v1"

EVIDENCE_WRITE_FAILURE_BEHAVIOR = (
    "DIAGNOSTIC_ONLY_NO_TRADING_MUTATION;"
    "NO_SILENT_FALSE_RESEARCH_RECORD;"
    "QUARANTINE_OR_SKIP;"
    "NEVER_ALTER_ALPHA_POSITION_RISK_SAFETY_OR_TRADING_GATE"
)

DEFAULT_PRODUCTIVE_LEDGER_RELATIVE_PATH = (
    "docs/evidence/canonical_volatility_max_age_productive_research_evidence_ledger_v1/"
    "productive_research_evidence_ledger.jsonl"
)
DEFAULT_JOIN_LEDGER_RELATIVE_PATH = (
    "docs/evidence/canonical_volatility_numeric_max_age_research_evidence_ledger_v1/"
    "research_evidence_ledger.jsonl"
)
DEFAULT_QUARANTINE_LEDGER_RELATIVE_PATH = (
    "docs/evidence/canonical_volatility_max_age_productive_research_evidence_ledger_v1/"
    "productive_research_evidence_quarantine.jsonl"
)

KNOWN_VOLATILITY_UNITS = frozenset(
    {
        "DECIMAL_FRACTION",
        "PERCENT",
        "ANNUALIZED_DECIMAL",
        "ANNUALIZED_PERCENT",
        "UNKNOWN",
    }
)

FORBIDDEN_IMPORT_SUBSTRINGS: tuple[str, ...] = (
    "trading.execution",
    "src.execution",
    "trading.live",
    "src.live",
    "exchange_order",
    "place_order",
    "submit_order",
    "broker_adapter",
)

CLI_REL_PATH = (
    "scripts/ops/run_canonical_volatility_max_age_productive_research_evidence_accumulation_v1.py"
)
SPEC_REL_PATH = (
    "docs/ops/specs/"
    "MASTER_V2_CANONICAL_VOLATILITY_MAX_AGE_PRODUCTIVE_RESEARCH_"
    "EVIDENCE_ACCUMULATION_CAPABILITY_V1.md"
)

AUTHORITY_SCOPE = "PRODUCTIVE_RESEARCH_EVIDENCE_ACCUMULATION_ONLY"
NON_AUTHORITY_SCOPE = (
    "NOT_THRESHOLD_SELECTION;"
    "NOT_CANDIDATE_PROMOTION;"
    "NOT_POLICY_MUTATION;"
    "NOT_ALPHA_MUTATION;"
    "NOT_ENFORCEMENT;"
    "NOT_ORDER_AUTHORITY;"
    "NOT_LIVE_AUTHORITY"
)

AUTHORITATIVE_BRIDGE_CYCLE_OUTPUT_ID = (
    "MASTER_V2_FULL_CANONICAL_DECISION_TO_SIMULATED_ECONOMICS_HARDENED_BRIDGE_CYCLE_OUTPUT"
)
PRODUCTIVE_BRIDGE_BINDING_CAPABILITY_ID = (
    "MASTER_V2_CANONICAL_VOLATILITY_MAX_AGE_PRODUCTIVE_BRIDGE_CYCLE_"
    "INPUT_AUTHORIZATION_AND_ACCUMULATION_BINDING_V1"
)
PRODUCTIVE_BRIDGE_BINDING_SPEC_REL_PATH = (
    "docs/ops/specs/"
    "MASTER_V2_CANONICAL_VOLATILITY_MAX_AGE_PRODUCTIVE_BRIDGE_CYCLE_"
    "INPUT_AUTHORIZATION_AND_ACCUMULATION_BINDING_V1.md"
)
DEFAULT_PRODUCTIVE_BRIDGE_VENUE = "okx_europe"
DEFAULT_PRODUCTIVE_BRIDGE_VENUE_INSTRUMENT_ID = "ETH-USD_UM_XPERP-310404"
DEFAULT_PRODUCTIVE_BRIDGE_CANONICAL_INSTRUMENT_ID = "ETH-USD_UM_XPERP-310404"
RUNTIME_CYCLE_IS_NOT_MARKET_SAMPLE = True
DUPLICATE_MARKET_SAMPLE_CANNOT_CREATE_NEW_AGE_OBSERVATION = True
REPEATED_POLL_RESULT_CANNOT_ADVANCE_OBSERVATION_COVERAGE = True
EVENT_TIME_REMAINS_AUTHORITATIVE = True
COUNTERFACTUAL_ONLY = True
BLOCKED_FOR_PARAMETER_DECISION = True
EVIDENCE_SUFFICIENT_FOR_PARAMETER_DECISION = False
PRODUCTIVE_CLI_MODE = "productive-bridge-accumulate"
EVALUABILITY_CLI_MODE = "evaluability-report"
SESSION_PREREGISTRATION_RENDER_CLI_MODE = "render-session-preregistration"
SESSION_PREREGISTRATION_VERIFY_CLI_MODE = "verify-session-preregistration"
SESSION_PREREGISTRATION_CAPABILITY_ID = (
    "MASTER_V2_CANONICAL_VOLATILITY_NUMERIC_MAX_AGE_PRODUCTIVE_EVIDENCE_SESSION_PREREGISTRATION_V1"
)
SESSION_PREREGISTRATION_SPEC_REL_PATH = (
    "docs/ops/specs/"
    "MASTER_V2_CANONICAL_VOLATILITY_NUMERIC_MAX_AGE_PRODUCTIVE_"
    "EVIDENCE_SESSION_PREREGISTRATION_V1.md"
)
SESSION_PREREGISTRATION_ARTIFACT_REL_PATH = (
    "config/research/"
    "canonical_volatility_numeric_max_age_productive_evidence_session_preregistration_v1.json"
)
MAX_PRODUCTIVE_BRIDGE_CYCLES_PER_SESSION = 128
MAX_PRODUCTIVE_BRIDGE_SESSIONS_PER_RUN = 8
LEGACY_FALLBACK_VALUES_FORBIDDEN_AS_RESEARCH_TRUTH: tuple[float, ...] = (0.02, 0.2, 1.0)
