"""Exhaustive P08 read-only candidate census. Navigation inventory, not SSOT."""

from __future__ import annotations

from typing import Any

from src.ops.section_11_13_5_p08_read_only_closure_v1.constants_v1 import (
    HISTORICAL_P08_DISTINCT_EVIDENCE_PACK,
    HISTORICAL_P08_EMPTY_DATA_EVIDENCE_PACK,
    TARGET_INST_TYPE,
    TARGET_INSTRUMENT_ID,
)

DISPOSITION_REUSE = "REUSE_EXISTING_EVIDENCE"
DISPOSITION_DISTINCT = "DISTINCT_READ_ONLY_ELICITATION"
DISPOSITION_REDUNDANT = "REDUNDANT_ALREADY_CONSUMED"
DISPOSITION_HISTORICAL = "HISTORICAL_ONLY"
DISPOSITION_INDIRECT = "INDIRECT_ONLY"
DISPOSITION_ID_NOT_PROVEN = "IDENTIFIER_NOT_PROVEN"
DISPOSITION_INSUFFICIENT = "SEMANTICALLY_INSUFFICIENT"
DISPOSITION_CURRENT_NOT_PROVEN = "CURRENT_STATE_NOT_PROVEN"
DISPOSITION_TARGET_ID_NOT_PROVEN = "TARGET_IDENTITY_NOT_PROVEN"
DISPOSITION_NONZERO_NOT_PROVEN = "NONZERO_NOT_PROVEN"
DISPOSITION_HIGHER = "HIGHER_AUTHORITY_REQUIRED"

CANDIDATES: tuple[dict[str, Any], ...] = (
    {
        "ID": "UNFILTERED_ACCOUNT_POSITIONS",
        "OWNER": "ops.section_11_13_5_p08_position_observation_v1",
        "ENDPOINT": "GET /api/v5/account/positions",
        "FILTER": "none",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "pos field when row present",
        "ZERO_NONZERO": "empty is not zero; zero row does not close P08",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": False,
        "IMPLEMENTED": True,
        "CONSUMED": True,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": True,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_REDUNDANT,
        "CANONICAL_P08_SURFACE": True,
        "CONSUMED_BY": HISTORICAL_P08_EMPTY_DATA_EVIDENCE_PACK,
    },
    {
        "ID": "INSTID_ACCOUNT_POSITIONS",
        "OWNER": "ops.section_11_13_5_p08_empty_data_not_zero_v1",
        "ENDPOINT": "GET /api/v5/account/positions?instId=",
        "FILTER": f"instId={TARGET_INSTRUMENT_ID}",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "pos field when row present",
        "ZERO_NONZERO": "filtered empty is not zero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": False,
        "IMPLEMENTED": True,
        "CONSUMED": True,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_REDUNDANT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": HISTORICAL_P08_EMPTY_DATA_EVIDENCE_PACK,
    },
    {
        "ID": "INSTTYPE_FUTURES_ACCOUNT_POSITIONS",
        "OWNER": "ops.section_11_13_5_p08_empty_data_not_zero_v1",
        "ENDPOINT": "GET /api/v5/account/positions?instType=FUTURES",
        "FILTER": f"instType={TARGET_INST_TYPE}",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "pos field when row present",
        "ZERO_NONZERO": "typed empty is not zero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": False,
        "IMPLEMENTED": True,
        "CONSUMED": True,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_REDUNDANT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": HISTORICAL_P08_EMPTY_DATA_EVIDENCE_PACK,
    },
    {
        "ID": "POSID_ACCOUNT_POSITIONS",
        "OWNER": "ops.section_11_13_5_p08_distinct_first_party_evidence_v1",
        "ENDPOINT": "GET /api/v5/account/positions?posId=",
        "FILTER": "posId=INDEPENDENTLY_PROVEN",
        "REQUIRED_IDENTIFIERS": "independently proven target posId",
        "IDENTIFIER_PROVEN": False,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "pos field when row present",
        "ZERO_NONZERO": "empty is not zero; nonzero row may close via posId surface",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": True,
        "CAN_SATISFY_NONZERO": True,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_ID_NOT_PROVEN,
        "CANONICAL_P08_SURFACE": True,
        "CONSUMED_BY": None,
    },
    {
        "ID": "TARGET_POSITIONS_HISTORY",
        "OWNER": "ops.section_11_13_5_p08_distinct_first_party_evidence_v1",
        "ENDPOINT": "GET /api/v5/account/positions-history",
        "FILTER": f"instType={TARGET_INST_TYPE}&instId={TARGET_INSTRUMENT_ID}",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "HISTORICAL",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "closed-position history; not current pos",
        "ZERO_NONZERO": "empty is not never-held and not current zero",
        "FRESHNESS": "last-3-months window; not current",
        "INDEPENDENCE": False,
        "IMPLEMENTED": True,
        "CONSUMED": True,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_REDUNDANT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": HISTORICAL_P08_DISTINCT_EVIDENCE_PACK,
    },
    {
        "ID": "TYPED_POSITIONS_HISTORY",
        "OWNER": "ops.section_11_13_5_p08_distinct_first_party_evidence_v1",
        "ENDPOINT": "GET /api/v5/account/positions-history",
        "FILTER": f"instType={TARGET_INST_TYPE}",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "HISTORICAL",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "closed-position history; not current pos",
        "ZERO_NONZERO": "empty is not never-held and not current zero",
        "FRESHNESS": "last-3-months window; not current",
        "INDEPENDENCE": False,
        "IMPLEMENTED": True,
        "CONSUMED": True,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_REDUNDANT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": HISTORICAL_P08_DISTINCT_EVIDENCE_PACK,
    },
    {
        "ID": "ACCOUNT_POSITION_RISK_FUTURES",
        "OWNER": "ops.section_11_13_5_p08_distinct_first_party_evidence_v1",
        "ENDPOINT": "GET /api/v5/account/account-position-risk",
        "FILTER": f"instType={TARGET_INST_TYPE}",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT_CROSS_CHECK",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "posData is not canonical P08 pos",
        "ZERO_NONZERO": "posData=[] is not zero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": False,
        "IMPLEMENTED": True,
        "CONSUMED": True,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_REDUNDANT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": HISTORICAL_P08_DISTINCT_EVIDENCE_PACK,
    },
    {
        "ID": "ACCOUNT_POSITION_RISK_UNFILTERED",
        "OWNER": "ops.section_11_13_5_p08_distinct_first_party_evidence_v1.query_grammar_v1",
        "ENDPOINT": "GET /api/v5/account/account-position-risk",
        "FILTER": "none",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT_CROSS_CHECK",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "posData is not canonical P08 pos",
        "ZERO_NONZERO": "posData=[] is not zero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": False,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
        "REASON": "Z2V proven grammar requires instType; unfiltered risk is not a verified first-party contract",
    },
    {
        "ID": "INSTFAMILY_ACCOUNT_POSITIONS",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1.account_positions_query_grammar_v1",
        "ENDPOINT": "GET /api/v5/account/positions?instFamily=",
        "FILTER": "instFamily",
        "REQUIRED_IDENTIFIERS": "instFamily",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "not a REST query param",
        "ZERO_NONZERO": "n/a",
        "FRESHNESS": "n/a",
        "INDEPENDENCE": False,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
        "REASON": "INSTFAMILY_FORBIDDEN by Z2CE positions REST grammar",
    },
    {
        "ID": "ACCOUNT_BALANCE",
        "OWNER": "ops.offline_funding_balance_read_producer_v1",
        "ENDPOINT": "GET /api/v5/account/balance",
        "FILTER": "none",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "equity/balance not position qty",
        "ZERO_NONZERO": "balance/equity must not become position zero/nonzero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "ACCOUNT_CONFIG_POSMODE",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1.account_mode_observation_v1",
        "ENDPOINT": "GET /api/v5/account/config",
        "FILTER": "none",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "posMode/acctLv not position qty",
        "ZERO_NONZERO": "config is not position state",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "ACCOUNT_MAX_SIZE",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1.max_available_observation_v1",
        "ENDPOINT": "GET /api/v5/account/max-size",
        "FILTER": "instId/tdMode required for sizing",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "maxBuy/maxSell not current pos",
        "ZERO_NONZERO": "max-size zeros are not position zeros",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "ACCOUNT_LEVERAGE_INFO",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1",
        "ENDPOINT": "GET /api/v5/account/leverage-info",
        "FILTER": "instId",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "leverage not position qty",
        "ZERO_NONZERO": "leverage is not position state",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "ACCOUNT_BILLS",
        "OWNER": "atlas VENUE_ENDPOINT:okx_account_bills",
        "ENDPOINT": "GET /api/v5/account/bills",
        "FILTER": "optional instType/instId",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "HISTORICAL",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "ledger bills not current pos",
        "ZERO_NONZERO": "no bills is not current zero",
        "FRESHNESS": "historical ledger",
        "INDEPENDENCE": True,
        "IMPLEMENTED": False,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
        "REASON": "ledger is not a verified P08 position-observation contract",
    },
    {
        "ID": "ASSET_BALANCES",
        "OWNER": "ops.offline_funding_balance_read_producer_v1",
        "ENDPOINT": "GET /api/v5/asset/balances",
        "FILTER": "ccy optional",
        "REQUIRED_IDENTIFIERS": "none",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": False,
        "QTY_SEMANTICS": "funding balance not position qty",
        "ZERO_NONZERO": "funding empty is not position zero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "PUBLIC_INSTRUMENTS",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1",
        "ENDPOINT": "GET /api/v5/public/instruments",
        "FILTER": f"instType={TARGET_INST_TYPE}&instId={TARGET_INSTRUMENT_ID}",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "instrument metadata not account position",
        "ZERO_NONZERO": "instrument-level evidence is not account position evidence",
        "FRESHNESS": "public metadata",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "PUBLIC_GET",
        "DISPOSITION": DISPOSITION_INSUFFICIENT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "TRADE_ORDER_GET_WITHOUT_ORDID",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1",
        "ENDPOINT": "GET /api/v5/trade/order",
        "FILTER": "ordId or clOrdId required",
        "REQUIRED_IDENTIFIERS": "ordId/clOrdId",
        "IDENTIFIER_PROVEN": False,
        "CURRENT_VS_HISTORICAL": "CURRENT_OR_HISTORICAL",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "single order not current pos",
        "ZERO_NONZERO": "missing order is not position zero",
        "FRESHNESS": "order snapshot",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": False,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_ID_NOT_PROVEN,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "TARGET_ORDERS_PENDING",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1",
        "ENDPOINT": "GET /api/v5/trade/orders-pending",
        "FILTER": f"instType={TARGET_INST_TYPE}&instId={TARGET_INSTRUMENT_ID}",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT_INDIRECT",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "working order size not current pos; may carry posId",
        "ZERO_NONZERO": "no pending orders is not current zero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": True,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_DISTINCT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
        "REASON": "Post-whitelist HTTP 200 pending observation does not exist; Z2DS pending was 50110",
    },
    {
        "ID": "TARGET_ORDERS_HISTORY",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1",
        "ENDPOINT": "GET /api/v5/trade/orders-history",
        "FILTER": f"instType={TARGET_INST_TYPE}&instId={TARGET_INSTRUMENT_ID}",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "HISTORICAL",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "historical orders not current pos; may carry posId",
        "ZERO_NONZERO": "no orders is not current zero",
        "FRESHNESS": "historical; not current",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": True,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_DISTINCT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
    },
    {
        "ID": "TARGET_ORDERS_ALGO_PENDING",
        "OWNER": "ops.section_11_13_5_live_canary_minimum_exposure_v1.category_c_open_algo_pending_observer_v1",
        "ENDPOINT": "GET /api/v5/trade/orders-algo-pending",
        "FILTER": f"ordType variants + instType={TARGET_INST_TYPE}&instId={TARGET_INSTRUMENT_ID}",
        "REQUIRED_IDENTIFIERS": "target instId already bound; proven ordType variants",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "CURRENT_INDIRECT",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "algo pending not current pos; may carry posId",
        "ZERO_NONZERO": "no algo pending is not current zero",
        "FRESHNESS": "this-window GET only",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": True,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_DISTINCT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
        "REASON": "Z2DS algo-pending was not an HTTP-success P08 observation",
    },
    {
        "ID": "TARGET_FILLS",
        "OWNER": "atlas VENUE_ENDPOINT:okx_trade_fills",
        "ENDPOINT": "GET /api/v5/trade/fills",
        "FILTER": f"instType={TARGET_INST_TYPE}&instId={TARGET_INSTRUMENT_ID}",
        "REQUIRED_IDENTIFIERS": "target instId already bound",
        "IDENTIFIER_PROVEN": True,
        "CURRENT_VS_HISTORICAL": "HISTORICAL",
        "TARGET_SPECIFIC": True,
        "QTY_SEMANTICS": "fills not current pos; may carry posId",
        "ZERO_NONZERO": "no fills is not current zero",
        "FRESHNESS": "recent fills window; not current position state",
        "INDEPENDENCE": True,
        "IMPLEMENTED": True,
        "CONSUMED": False,
        "NEW_GET_ADDS_INFORMATION": True,
        "CAN_SATISFY_NONZERO": False,
        "AUTHORITY_CLASS": "READ_ONLY_PRIVATE_GET",
        "DISPOSITION": DISPOSITION_DISTINCT,
        "CANONICAL_P08_SURFACE": False,
        "CONSUMED_BY": None,
        "REASON": "Atlas-modeled first-party private GET; not consumed by P08 V1/V2",
    },
)


def distinct_unconsumed_candidates_v1() -> tuple[dict[str, Any], ...]:
    return tuple(item for item in CANDIDATES if item["DISPOSITION"] == DISPOSITION_DISTINCT)


def census_payload_v1() -> dict[str, Any]:
    distinct = distinct_unconsumed_candidates_v1()
    return {
        "AUTHORITY": "NONE",
        "DOCUMENT_CLASS": "P08_READ_ONLY_CLOSURE_CENSUS_V3",
        "DOCUMENT_ROLE": "NAVIGATION_INVENTORY_NOT_SSOT_NOT_AUTHORITY",
        "P08_READ_ONLY_CANDIDATE_COUNT": len(CANDIDATES),
        "P08_DISTINCT_UNCONSUMED_CANDIDATE_COUNT": len(distinct),
        "CANDIDATES": list(CANDIDATES),
        "DISTINCT_UNCONSUMED": [item["ID"] for item in distinct],
        "NOT_REPEATED": [
            "GET /api/v5/account/positions unfiltered",
            "GET /api/v5/account/positions?instId=",
            "GET /api/v5/account/positions?instType=FUTURES",
            "GET /api/v5/account/positions-history",
            "GET /api/v5/account/account-position-risk",
        ],
        "PREDECESSOR_PACKS_HISTORICAL": [
            HISTORICAL_P08_EMPTY_DATA_EVIDENCE_PACK,
            HISTORICAL_P08_DISTINCT_EVIDENCE_PACK,
        ],
        "PREDECESSOR_IS_NOT_CURRENT_08_PROOF": True,
    }
