"""Standing constants for P08 read-only closure V3.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1,
build_okx_live_canary_auth_headers_v1, classify_position_observation_v1,
build_account_positions_query_v1 (posId path only), and the Category-C
algo-pending query builder. Does not mint a second HTTP client, signer,
SecretRef owner, live/testnet/canary authority, or mutation path. Does
not repeat equivalent /account/positions empty-envelope probes. Does not
repeat consumed V2 history/risk probes. Does not authorize POST, flatten,
P09 work, posSide submit-body proof, funding, balance GET, or treating
empty/history/risk/order/fill absence as zero.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INST_TYPE,
    DEFAULT_INSTRUMENT_ID,
    ENDPOINT_ACCOUNT_POSITIONS,
    ENDPOINT_ORDERS_ALGO_PENDING,
    ENDPOINT_ORDERS_HISTORY,
    ENDPOINT_ORDERS_PENDING,
    ENDPOINT_TRADE_FILLS,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)
from src.ops.section_11_13_5_p08_position_observation_v1.constants_v1 import (
    CASE_A_TARGET_NONZERO,
    CASE_B_TARGET_ZERO,
    CASE_C_EMPTY_DATA_NOT_ZERO,
    CASE_D_TARGET_NOT_OBSERVED,
    CASE_E_HTTP_OR_OKX_ERROR,
    CASE_F_AMBIGUOUS,
    EMPTY_DATA_IS_ZERO as PREDECESSOR_EMPTY_DATA_IS_ZERO,
    P08_CANONICAL_DEFINITION,
    RESULT_CLASS_200_OKX_0,
    RESULT_CLASS_401_50110,
    RESULT_CLASS_OTHER,
    RESULT_CLASS_TRANSPORT,
)

CAPABILITY_ID = "P08_READ_ONLY_CLOSURE_V3"
PACKAGE_MARKER = "P08_READ_ONLY_CLOSURE_V3=true"
OWNER = "ops.section_11_13_5_p08_read_only_closure_v1"
CONTRACT_VERSION = "v3"
SCHEMA_VERSION = "p08_read_only_closure.v3"
OWNER_GO = "PEAK_TRADE_OWNER_GO_P08_READ_ONLY_CLOSURE_MAXIMUM_SAFE_LEVERAGE_V3"
WORKPACKAGE_ID = "OKX_EEA_P08_READ_ONLY_CLOSURE_MAX_SAFE_LEVERAGE_V3"
THIS_SLICE = "11.13.5.P08_READ_ONLY_CLOSURE"
PREDECESSOR_SLICE = "11.13.5.P08_DISTINCT_FIRST_PARTY_EVIDENCE"
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "ac2ea2d40d1d8a3f0ccfc4a5650567fc27a06ea6"
AUTHORIZED_HOST = "eea.okx.com"
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
TARGET_INST_TYPE = DEFAULT_INST_TYPE

AUTHORIZED_OPERATION = (
    "DISTINCT_AUTHENTICATED_NON_MUTATING_PRIVATE_GETS_FOR_P08_IDENTIFIER_RECOVERY"
)
AUTHORIZED_ENDPOINTS = (
    "GET /api/v5/trade/orders-pending",
    "GET /api/v5/trade/orders-history",
    "GET /api/v5/trade/orders-algo-pending",
    "GET /api/v5/trade/fills",
    "GET /api/v5/account/positions?posId=",
)
AUTHORIZED_ENDPOINT_PATHS: tuple[str, ...] = (
    ENDPOINT_ORDERS_PENDING,
    ENDPOINT_ORDERS_HISTORY,
    ENDPOINT_ORDERS_ALGO_PENDING,
    ENDPOINT_TRADE_FILLS,
    ENDPOINT_ACCOUNT_POSITIONS,
)

MAX_NETWORK_REQUEST_COUNT = 8
MAX_HTTP_EXCHANGE_COUNT = 8
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
PAGE_LIMIT = 100
RETRY_ALLOWED = False
RETRY_AUTHORIZED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
PUBLIC_GET_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
P08_OBSERVATION_ALLOWED = True
P08_CLOSE_ALLOWED = True
FUNDING_ALLOWED = False
BALANCE_GET_ALLOWED = False
CONFIG_GET_ALLOWED = False
MAX_SIZE_GET_ALLOWED = False
POSITIONS_UNFILTERED_GET_ALLOWED = False
POSITIONS_INSTID_GET_ALLOWED = False
POSITIONS_INSTTYPE_GET_ALLOWED = False
POSITIONS_HISTORY_GET_ALLOWED = False
ACCOUNT_POSITION_RISK_GET_ALLOWED = False
ORDERS_PENDING_GET_ALLOWED = True
ORDERS_HISTORY_GET_ALLOWED = True
ORDERS_ALGO_PENDING_GET_ALLOWED = True
FILLS_GET_ALLOWED = True
POSID_POSITIONS_GET_ALLOWED = True
POSID_GET_REQUIRES_INDEPENDENT_PROOF = True
KEY_ROTATION_ALLOWED = False
PERMISSION_CHANGE_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
POSITION_CREATION_ALLOWED = False
POSITION_MODIFICATION_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
G_POSMODE_REOPEN_ALLOWED = False
G_POSMODE_CLOSE_ALLOWED = False
P09_WORK_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False

EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False
FILTERED_EMPTY_IS_ZERO = False
HISTORY_EMPTY_IS_ZERO = False
HISTORY_EMPTY_IS_NEVER_HELD = False
HISTORY_EMPTY_IS_CURRENT_ZERO = False
ORDERS_EMPTY_IS_ZERO = False
ORDERS_EMPTY_IS_NEVER_HELD = False
ORDERS_EMPTY_IS_CURRENT_ZERO = False
FILLS_EMPTY_IS_ZERO = False
FILLS_EMPTY_IS_NEVER_HELD = False
FILLS_EMPTY_IS_CURRENT_ZERO = False
RISK_POSDATA_EMPTY_IS_ZERO = False
CROSS_CHECK_IS_CANONICAL_AUTHORITY = False
HISTORICAL_STATE_IS_CURRENT_STATE = False
DOCUMENTATION_SEMANTICS_ARE_OBSERVED_ACCOUNT_STATE = False
PREDECESSOR_EMPTY_DATA_IS_ZERO_REUSED = PREDECESSOR_EMPTY_DATA_IS_ZERO

ID_CLASS_EMPTY = "IDENTIFIER_CHANNEL_EMPTY_NOT_NEVER_HELD_NOT_CURRENT_ZERO"
ID_CLASS_TARGET_NOT_OBSERVED = "IDENTIFIER_CHANNEL_TARGET_NOT_OBSERVED"
ID_CLASS_TARGET_POSID_PROVEN = "IDENTIFIER_CHANNEL_TARGET_POSID_PROVEN"
ID_CLASS_AMBIGUOUS_POSID = "IDENTIFIER_CHANNEL_AMBIGUOUS_POSID"
ID_CLASS_TARGET_POSID_ABSENT = "IDENTIFIER_CHANNEL_TARGET_POSID_ABSENT"
ID_CLASS_HTTP_OR_OKX_ERROR = "IDENTIFIER_CHANNEL_HTTP_OR_OKX_ERROR"

GET_ROLE_ORDERS_PENDING = "TARGET_ORDERS_PENDING"
GET_ROLE_ORDERS_HISTORY = "TARGET_ORDERS_HISTORY"
GET_ROLE_ALGO_CONDITIONAL_OCO = "TARGET_ALGO_PENDING_CONDITIONAL_OCO"
GET_ROLE_ALGO_TRIGGER = "TARGET_ALGO_PENDING_TRIGGER"
GET_ROLE_ALGO_MOVE_ORDER_STOP = "TARGET_ALGO_PENDING_MOVE_ORDER_STOP"
GET_ROLE_FILLS = "TARGET_FILLS"
GET_ROLE_POSID_POSITIONS = "POSID_ACCOUNT_POSITIONS"

GET_PURPOSE_ORDERS_PENDING = "POSID_RECOVERY_FROM_WORKING_ORDERS_NOT_CURRENT_POSITION"
GET_PURPOSE_ORDERS_HISTORY = "POSID_RECOVERY_FROM_ORDER_HISTORY_NOT_CURRENT_POSITION"
GET_PURPOSE_ALGO_PENDING = "POSID_RECOVERY_FROM_ALGO_PENDING_NOT_CURRENT_POSITION"
GET_PURPOSE_FILLS = "POSID_RECOVERY_FROM_FILLS_NOT_CURRENT_POSITION"
GET_PURPOSE_POSID_POSITIONS = "EXPLICIT_POSID_CLOSED_ELICITATION_CURRENT_STATE"

ALGO_ORD_TYPE_BY_ROLE: tuple[tuple[str, str], ...] = (
    (GET_ROLE_ALGO_CONDITIONAL_OCO, "conditional,oco"),
    (GET_ROLE_ALGO_TRIGGER, "trigger"),
    (GET_ROLE_ALGO_MOVE_ORDER_STOP, "move_order_stop"),
)

FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/config",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/account/adjust-leverage-info",
    "/api/v5/account/max-avail-size",
    "/api/v5/account/bills",
    "/api/v5/account/positions-history",
    "/api/v5/account/account-position-risk",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
)

FORBIDDEN_HTTP_METHODS: tuple[str, ...] = (
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "HEAD",
    "OPTIONS",
    "TRACE",
    "CONNECT",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
REUSED_POSITION_OBSERVATION_CLASSIFIER = "classify_position_observation_v1"
REUSED_POSITIONS_QUERY_BUILDER = "build_account_positions_query_v1"
REUSED_ALGO_QUERY_BUILDER = "build_category_c_orders_algo_pending_endpoint_v1"
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False
SECOND_POSITION_AUTHORITY_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET_PACKAGE = False

EVIDENCE_DIRNAME = "section_11_13_5_p08_read_only_closure_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)
P08_CANONICAL_DEFINITION_REUSED = P08_CANONICAL_DEFINITION
FRESHNESS_POLICY = (
    "FLATTEN_PRE_SEND_MAX_AGE_MS=5000;"
    "THIS_WINDOW_SAMPLES_AGE_AFTER_LAST_GET_AND_IS_NOT_FLATTEN_SEND_PERMIT"
)

CLOSURE_RESULT_CLOSED_NONZERO = "CLOSED_NONZERO_PROVEN"
CLOSURE_RESULT_OPEN_DISTINCT_REMAINS = "OPEN_DISTINCT_PATH_REMAINS"
CLOSURE_RESULT_READ_ONLY_EXHAUSTED = "READ_ONLY_EXHAUSTED"

NEXT_AUTHORITY_BOUNDARY_READ_ONLY_EXHAUSTED = (
    "SEPARATE_OWNER_GO_REQUIRED_P08_READ_ONLY_EXHAUSTED_"
    "CURRENT_NONZERO_REQUIRES_TARGET_ROW_ON_UNFILTERED_ACCOUNT_POSITIONS_"
    "ENTRY_OR_EXTERNAL_APPEARANCE_NOT_AUTHORIZED"
)
NEXT_AUTHORITY_BOUNDARY_CONTRADICTION = (
    "SEPARATE_OWNER_GO_REQUIRED_P08_CONTRADICTORY_IDENTIFIER_OR_CURRENT_STATE"
)

HISTORICAL_P08_DISTINCT_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_p08_distinct_first_party_evidence_v1/20260903T200738Z"
)
HISTORICAL_P08_EMPTY_DATA_EVIDENCE_PACK = (
    "evidence/ops/section_11_13_5_p08_empty_data_not_zero_v1/20260903T193620Z"
)
HISTORICAL_Z2DS_PENDING_WAS_50110 = True
