"""Constants for F1/M9 authorized campaign run orchestration owner v1."""

from __future__ import annotations

from typing import Final

ORCHESTRATION_WORKPACKAGE_ID: Final[str] = (
    "F1_M9_PROSPECTIVE_CAMPAIGN_AUTHORIZED_RUN_ORCHESTRATION_OWNER_V1"
)
ORCHESTRATION_OWNER_ID: Final[str] = "f1_m9_prospective_campaign_authorized_run_orchestration_v1"
ORCHESTRATION_SCHEMA_VERSION: Final[str] = (
    "f1_m9_prospective_campaign_authorized_run_orchestration/v1"
)

ORCHESTRATION_NORMATIVE_SPEC: Final[str] = (
    "docs/ops/specs/F1_M9_PROSPECTIVE_CAMPAIGN_AUTHORIZED_RUN_ORCHESTRATION_NORMATIVE_V1.md"
)
ORCHESTRATION_DECISION_CONFIG: Final[str] = (
    "config/governance/f1_m9_prospective_campaign_authorized_run_orchestration_v1_decision_v1.json"
)

CONSUMPTION_LEDGER_FILENAME: Final[str] = "consumption_ledger.jsonl"
AUTHORIZATION_REF_FILENAME: Final[str] = "runtime_execution_authorization_ref.json"
EXECUTION_STATE_FILENAME: Final[str] = "execution_state.json"

STATUS_TERMINAL_VERDICT_PASS: Final[str] = "F1_M9_AUTHORIZED_CAMPAIGN_RUN_TERMINAL_VERDICT_PASS"
STATUS_ORCHESTRATION_DENIED: Final[str] = "DENIED_FAIL_CLOSED"
STATUS_BUILD_SLICE_BOUND_ONLY: Final[str] = "F1_M9_ORCHESTRATION_BOUND_WITHOUT_REAL_EFFECT"
STATUS_ALREADY_COMPLETE_REPLAY: Final[str] = "F1_M9_CAMPAIGN_ALREADY_COMPLETE_REPLAY_ONLY"

NEXT_TRUE_BLOCKER_AFTER_ORCHESTRATION: Final[str] = (
    "F1_M9_PROSPECTIVE_SELECTION_CAMPAIGN_EXECUTION_V1_REQUIRES_FRESH_RUNTIME_AUTHORIZATION"
)

__all__ = [
    "AUTHORIZATION_REF_FILENAME",
    "CONSUMPTION_LEDGER_FILENAME",
    "EXECUTION_STATE_FILENAME",
    "NEXT_TRUE_BLOCKER_AFTER_ORCHESTRATION",
    "ORCHESTRATION_DECISION_CONFIG",
    "ORCHESTRATION_NORMATIVE_SPEC",
    "ORCHESTRATION_OWNER_ID",
    "ORCHESTRATION_SCHEMA_VERSION",
    "ORCHESTRATION_WORKPACKAGE_ID",
    "STATUS_ALREADY_COMPLETE_REPLAY",
    "STATUS_BUILD_SLICE_BOUND_ONLY",
    "STATUS_ORCHESTRATION_DENIED",
    "STATUS_TERMINAL_VERDICT_PASS",
]
