"""Constants for CAPABILITY_DOUBLE_PLAY_ARCHIVE_SIBLING_EXPORTER_V1.

AUTHORITY_EFFECT=NONE
TRADING_SEMANTIC_CHANGE=false
DOUBLE_PLAY_RECOMPUTE=false
AUTOMATIC_CALLER_ADDED=false
PRESENTATION_CHANGED=false
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_DOUBLE_PLAY_ARCHIVE_SIBLING_EXPORTER_V1"
PACKAGE_MARKER = "DOUBLE_PLAY_ARCHIVE_SIBLING_EXPORTER_V1=true"
OWNER = "ops.double_play_archive_sibling_exporter_v1"
AUTHORITY_EFFECT = "NONE"
DOUBLE_PLAY_AUTHORITY_EFFECT = "NONE"

TARGET_FILENAME = "double_play_dashboard_display.v1.json"
TARGET_RELATIVE_PATH = f"readmodels/{TARGET_FILENAME}"
READMODELS_DIRNAME = "readmodels"

# Sibling contract name (display-only; no trading authority).
CONTRACT_NAME = "double_play_dashboard_display.v1"
FAMILY_ID = "double_play"

REQUIRED_DISPLAY_FIELDS: tuple[str, ...] = (
    "overall_status",
    "panel_summaries",
)

PANEL_SUMMARY_KEYS: tuple[str, ...] = (
    "name",
    "status",
    "summary",
    "blockers",
)

ERROR_SOURCE_MISSING = "DOUBLE_PLAY_ARCHIVE_SIBLING_SOURCE_MISSING"
ERROR_SOURCE_CORRUPT = "DOUBLE_PLAY_ARCHIVE_SIBLING_SOURCE_CORRUPT"
ERROR_SOURCE_INVALID = "DOUBLE_PLAY_ARCHIVE_SIBLING_SOURCE_INVALID"
ERROR_SOURCE_LOAD_FAILED = "DOUBLE_PLAY_ARCHIVE_SIBLING_SOURCE_LOAD_FAILED"
ERROR_IDENTICAL_PATHS = "DOUBLE_PLAY_ARCHIVE_SIBLING_IDENTICAL_SOURCE_TARGET"
ERROR_WRITE_FAILED = "DOUBLE_PLAY_ARCHIVE_SIBLING_WRITE_FAILED"
ERROR_DIGEST_MISMATCH = "DOUBLE_PLAY_ARCHIVE_SIBLING_DIGEST_MISMATCH"
ERROR_PATH_REQUIRED = "DOUBLE_PLAY_ARCHIVE_SIBLING_PATH_REQUIRED"
ERROR_TARGET_CONFLICT = "DOUBLE_PLAY_ARCHIVE_SIBLING_TARGET_CONFLICT"
