"""Constants for CAPABILITY_11_11 Live autonomous recovery and degradation evidence."""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_11_11_LIVE_AUTONOMOUS_RECOVERY_AND_DEGRADATION_EVIDENCE_V1"
PACKAGE_MARKER = "CAPABILITY_11_11_LIVE_AUTONOMOUS_RECOVERY_AND_DEGRADATION_EVIDENCE_V1=true"
OWNER = "ops.capability_11_11_live_autonomous_recovery_and_degradation_evidence_v1"
AUTHORITY_OWNER = OWNER
SCHEMA_VERSION = "capability_11_11_live_autonomous_recovery_and_degradation_evidence.v1"
PRODUCER_VERSION = "capability_11_11_live_autonomous_recovery_and_degradation_evidence.v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID_11_1 = "CAPABILITY_11_1_EXECUTION_DOMAIN_AND_ORDER_LIFECYCLE_CONTRACTS_V1"
PREDECESSOR_OWNER_11_1 = "ops.capability_11_1_execution_domain_and_order_lifecycle_contracts_v1"
PREDECESSOR_CAPABILITY_ID_11_2 = (
    "CAPABILITY_11_2_CREDENTIAL_AUTHORIZATION_AND_ACCOUNT_IDENTITY_BOUNDARY_V1"
)
PREDECESSOR_OWNER_11_2 = (
    "ops.capability_11_2_credential_authorization_and_account_identity_boundary_v1"
)
PREDECESSOR_CAPABILITY_ID_11_3 = (
    "CAPABILITY_11_3_PRIVATE_READONLY_VENUE_INTEGRATION_AND_RECONCILIATION_V1"
)
PREDECESSOR_OWNER_11_3 = (
    "ops.capability_11_3_private_readonly_venue_integration_and_reconciliation_v1"
)
PREDECESSOR_CAPABILITY_ID_11_4 = (
    "CAPABILITY_11_4_TESTNET_EXECUTION_ADAPTER_AND_LIFECYCLE_CLOSURE_V1"
)
PREDECESSOR_OWNER_11_4 = "ops.capability_11_4_testnet_execution_adapter_and_lifecycle_closure_v1"
PREDECESSOR_CAPABILITY_ID_11_5 = (
    "CAPABILITY_11_5_TESTNET_RESTART_RECOVERY_AND_KILL_SWITCH_CLOSURE_V1"
)
PREDECESSOR_OWNER_11_5 = "ops.capability_11_5_testnet_restart_recovery_and_kill_switch_closure_v1"
PREDECESSOR_CAPABILITY_ID_11_6 = "CAPABILITY_11_6_LONG_RUNNING_AUTONOMOUS_TESTNET_EVIDENCE_V1"
PREDECESSOR_OWNER_11_6 = "ops.capability_11_6_long_running_autonomous_testnet_evidence_v1"
PREDECESSOR_CAPABILITY_ID_11_7 = (
    "CAPABILITY_11_7_LIVE_PRIVATE_READONLY_AND_SHADOW_RECONCILIATION_V1"
)
PREDECESSOR_OWNER_11_7 = "ops.capability_11_7_live_private_readonly_and_shadow_reconciliation_v1"
PREDECESSOR_CAPABILITY_ID_11_8 = "CAPABILITY_11_8_LIVE_DRY_RUN_ORDER_PLAN_PARITY_V1"
PREDECESSOR_OWNER_11_8 = "ops.capability_11_8_live_dry_run_order_plan_parity_v1"
PREDECESSOR_CAPABILITY_ID_11_9 = "CAPABILITY_11_9_LIVE_CANARY_ORDER_EXECUTION_V1"
PREDECESSOR_OWNER_11_9 = "ops.capability_11_9_live_canary_order_execution_v1"
PREDECESSOR_CAPABILITY_ID_11_10 = "CAPABILITY_11_10_LIVE_BOUNDED_SINGLE_FUTURE_CONTINUITY_V1"
PREDECESSOR_OWNER_11_10 = "ops.capability_11_10_live_bounded_single_future_continuity_v1"

# Hard safety bindings (contracts/scaffolding only; non-authorizing).
CORE_LOGIC_CHANGE = False
CORE_LOGIC_CHANGE_ALLOWED = False
ACTIVATION_STATE = "not_activated"
ACTIVATION_CHANGED = False
RUNTIME_ACTIVATED = False
LIVE_TRADING_ALLOWED = False
TESTNET_ALLOWED = False
PAPER_EXCHANGE_ORDERS_ALLOWED = False
EXCHANGE_CREDENTIAL_USE_ALLOWED = False
REAL_CAPITAL_MOVEMENT_ALLOWED = False
NETWORK_SESSION_ALLOWED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
RULESET_MUTATION_ALLOWED = False
NOTION_MUTATION_ALLOWED = False

TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False
EXCHANGE_CREDENTIAL_USE_AUTHORIZED = False
REAL_CAPITAL_MOVEMENT_AUTHORIZED = False
OWNER_GO_REQUIRED_FOR_EACH_ACTIVATION = True

LIVE_PATH_CHANGED = False
TESTNET_PATH_CHANGED = False
ORDER_PATH_CHANGED = False
EXCHANGE_CREDENTIAL_PATH_CHANGED = False
NETWORK_SESSION_STARTED = False
PRIVATE_NETWORK_SESSION_STARTED = False

VOLATILITY_NUMERIC_MAX_AGE_ENFORCING = False
NUMERIC_MAX_AGE_EFFECT = "DIAGNOSTIC_ONLY"
DASHBOARD_AUTHORITY_EFFECT = "NONE"

# Cap 11.1–11.10 retention (must not be weakened / activated).
CAPABILITY_11_1_FAIL_CLOSED_RETAINED = True
CAPABILITY_11_1_IDEMPOTENCY_RETAINED = True
CAPABILITY_11_1_UNKNOWN_SEMANTICS_RETAINED = True
CAPABILITY_11_1_LIFECYCLE_RETAINED = True
CAPABILITY_11_1_AUDIT_CONTRACTS_RETAINED = True
CAPABILITY_11_1_ANTI_CORRUPTION_RETAINED = True
CAPABILITY_11_1_JOURNALING_RETAINED = True

CAPABILITY_11_2_CREDENTIAL_BOUNDARY_RETAINED = True
CAPABILITY_11_2_AUTHORIZATION_BOUNDARY_RETAINED = True
CAPABILITY_11_2_ACCOUNT_IDENTITY_BOUNDARY_RETAINED = True
CAPABILITY_11_2_NO_CREDENTIAL_LOAD_RETAINED = True
CAPABILITY_11_2_NO_AUTH_CONSUMPTION_RETAINED = True

CAPABILITY_11_3_PRIVATE_READONLY_BOUNDARY_RETAINED = True
CAPABILITY_11_3_RECONCILIATION_HIERARCHY_RETAINED = True
CAPABILITY_11_3_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_3_NO_NETWORK_FETCH_RETAINED = True
CAPABILITY_11_3_NO_CREDENTIAL_LOAD_RETAINED = True

CAPABILITY_11_4_TESTNET_ADAPTER_BOUNDARY_RETAINED = True
CAPABILITY_11_4_LIFECYCLE_CLOSURE_RETAINED = True
CAPABILITY_11_4_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_4_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_4_NO_NETWORK_SESSION_RETAINED = True

CAPABILITY_11_5_RESTART_RECOVERY_KILL_SWITCH_RETAINED = True
CAPABILITY_11_5_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_5_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_5_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_5_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_6_LONG_RUNNING_EVIDENCE_RETAINED = True
CAPABILITY_11_6_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_6_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_6_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_6_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_7_LIVE_PRIVATE_READONLY_RETAINED = True
CAPABILITY_11_7_SHADOW_RECONCILIATION_RETAINED = True
CAPABILITY_11_7_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_7_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_7_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_7_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_8_LIVE_DRY_RUN_ORDER_PLAN_RETAINED = True
CAPABILITY_11_8_ORDER_PLAN_PARITY_RETAINED = True
CAPABILITY_11_8_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_8_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_8_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_8_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_9_LIVE_CANARY_ORDER_EXECUTION_RETAINED = True
CAPABILITY_11_9_MINIMUM_EXPOSURE_RETAINED = True
CAPABILITY_11_9_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_9_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_9_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_9_NO_PROVEN_CLAIMS_RETAINED = True

CAPABILITY_11_10_LIVE_BOUNDED_SINGLE_FUTURE_CONTINUITY_RETAINED = True
CAPABILITY_11_10_NOT_ACTIVATED_RETAINED = True
CAPABILITY_11_10_NO_ORDER_SUBMIT_RETAINED = True
CAPABILITY_11_10_NO_NETWORK_SESSION_RETAINED = True
CAPABILITY_11_10_NO_PROVEN_CLAIMS_RETAINED = True

# Reachability claims for Cap 11.11 (contracts only — no real Live recovery session).
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
EXCHANGE_CREDENTIAL_ACCESS_REACHABLE = False
REAL_CAPITAL_MOVEMENT_REACHABLE = False
PRIVATE_READONLY_NETWORK_REACHABLE = False
PRIVATE_READONLY_VENUE_INTEGRATION_ACTIVATED = False
CREDENTIAL_PLAINTEXT_LOADED = False
CREDENTIAL_LOAD_PERFORMED_IN_CAPABILITY_11_11 = False
TESTNET_EXECUTION_ADAPTER_ACTIVATED = False
TESTNET_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_11 = False
TESTNET_NETWORK_SESSION_STARTED_IN_CAPABILITY_11_11 = False
LIVE_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_11 = False
PAPER_ORDER_SUBMIT_PERFORMED_IN_CAPABILITY_11_11 = False
LIVE_ORDER_EXECUTION_PERFORMED_IN_CAPABILITY_11_11 = False

# Cap 11.11 contract surface claims (bound, not activated, not observed/proven).
LIVE_AUTONOMOUS_DEGRADATION_CONTRACT_BOUND = True
LIVE_AUTONOMOUS_DEGRADATION_CONTRACT_ACTIVATED = False
LIVE_AUTONOMOUS_RECOVERY_CONTRACT_BOUND = True
LIVE_AUTONOMOUS_RECOVERY_CONTRACT_ACTIVATED = False
LIVE_AUTONOMOUS_RECOVERY_EVIDENCE_LADDER_CONTRACT_BOUND = True
LIVE_AUTONOMOUS_RECOVERY_EVIDENCE_LADDER_CONTRACT_ACTIVATED = False
LIVE_AUTONOMOUS_RECOVERY_AND_DEGRADATION_FIXTURE_ONLY = True
CAPABILITY_11_11_STARTED = True
CAPABILITY_11_11_LIVE_AUTONOMOUS_RECOVERY_STARTED = True
LIVE_BOUNDED_MULTI_SESSION_ACTIVATED = False
LIVE_AUTONOMOUS_SINGLE_FUTURE_ACTIVATED = False
LIVE_AUTONOMOUS_DEGRADATION_ACTIVATED = False
LIVE_AUTONOMOUS_RECOVERY_ACTIVATED = False

# Cap 11.11 does NOT claim Live evidence-ladder proven / observed fields (§11.14).
LIVE_EXECUTION_CODE_EXISTS = False
LIVE_EXECUTION_PATH_REACHABLE = False
LIVE_PRIVATE_READ_ONLY_PROVEN = False
LIVE_ORDER_PLAN_OBSERVED = False
LIVE_SUBMIT_ACK_OBSERVED = False
LIVE_FILL_OBSERVED = False
LIVE_FEE_OBSERVED = False
LIVE_POSITION_RECONCILED = False
LIVE_ACCOUNTING_RECONSTRUCTED = False
LIVE_RESTART_RECONSTRUCTED = False
LIVE_AUTONOMOUS_RECOVERY_OBSERVED = False
LIVE_END_TO_END_EVIDENCE_PROVEN = False
LIVE_AUTONOMOUS_DEGRADATION_PROVEN = False
LIVE_AUTONOMOUS_RECOVERY_PROVEN = False

# Explicit Cap 11.12+ surfaces remain out of scope / unbound.
CAPABILITY_11_12_STARTED = False
CAPABILITY_11_12_FULLY_AUTONOMOUS_LIVE_READINESS_STARTED = False
FULLY_AUTONOMOUS_LIVE_TRADING_READY = False
FULLY_AUTONOMOUS_LIVE_TRADING_ACTIVE = False

# Live progression: Cap 11.11 owns recovery/degradation evidence stages (§11.13 / §11.19).
LIVE_PROGRESSION_STAGES_IN_SCOPE: tuple[str, ...] = (
    "LIVE_BOUNDED_MULTI_SESSION",
    "LIVE_AUTONOMOUS_SINGLE_FUTURE",
)

LIVE_PROGRESSION_STAGES_FORBIDDEN: tuple[str, ...] = ()

# Continuity / canary-inherited bounds (§11.13).
MINIMUM_RATIFIED_NOTIONAL_ONLY = True
POSITION_COUNT_LIMIT = 1
SINGLE_FUTURE_ONLY = True
NO_AUTOMATIC_STAGE_PROMOTION = True
OWNER_GO_REQUIRED_FOR_STAGE_PROMOTION = True
AUTOMATIC_STAGE_DEMOTION_ALLOWED = True
AUTOMATIC_HALT_ALLOWED = True
BOUNDED_RECOVERY_ROLLBACK_CONTRACT_REQUIRED = True

# Operating / degradation states from §11.8 (Live evidence contract surface).
OPERATING_STATES: tuple[str, ...] = (
    "OFF",
    "PREFLIGHT",
    "RECONCILING",
    "READY",
    "ACTIVE",
    "DEGRADED_NO_NEW_ENTRY",
    "EXIT_ONLY",
    "REDUCE_ONLY",
    "CANCEL_ALL",
    "RECOVERING",
    "HALTED",
    "OWNER_LOCKED",
)

RECOVERY_PERMITTED_GATES: tuple[str, ...] = (
    "ROOT_CAUSE_CLASSIFIED",
    "RECOVERY_POLICY_PRE_RATIFIED",
    "RETRY_BUDGET_AVAILABLE",
    "AUTHORIZATION_STILL_VALID",
    "NO_UNRESOLVED_ECONOMIC_AMBIGUITY",
    "POST_RECOVERY_RECONCILIATION_PASS",
)

RECOVERY_FORBIDDEN_CONDITIONS: tuple[str, ...] = (
    "credential_scope_mismatch",
    "repository_or_config_integrity_mismatch",
    "unknown_account_identity",
    "unexplained_position_divergence",
    "kill_switch_activation",
    "repeated_duplicate_order_evidence",
    "risk_limit_breach_requiring_limit_change",
    "evidence_chain_corruption_affecting_economic_truth",
    "unauthorized_mode_or_venue_transition",
)

# §11.14 Live evidence ladder fields (bound as contracts; not proven/observed).
LIVE_EVIDENCE_LADDER_FIELDS: tuple[str, ...] = (
    "LIVE_EXECUTION_CODE_EXISTS",
    "LIVE_EXECUTION_PATH_REACHABLE",
    "LIVE_PRIVATE_READ_ONLY_PROVEN",
    "LIVE_ORDER_PLAN_OBSERVED",
    "LIVE_SUBMIT_ACK_OBSERVED",
    "LIVE_FILL_OBSERVED",
    "LIVE_FEE_OBSERVED",
    "LIVE_POSITION_RECONCILED",
    "LIVE_ACCOUNTING_RECONSTRUCTED",
    "LIVE_RESTART_RECONSTRUCTED",
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED",
    "LIVE_END_TO_END_EVIDENCE_PROVEN",
)

# Cap 11.11 in-scope ladder focus (contract-bound only; observed=false).
LIVE_AUTONOMOUS_RECOVERY_LADDER_FOCUS_FIELDS: tuple[str, ...] = (
    "LIVE_RESTART_RECONSTRUCTED",
    "LIVE_AUTONOMOUS_RECOVERY_OBSERVED",
)

# Cap 11.12+ ladder fields remain forbidden to claim from Cap 11.11.
LIVE_AUTONOMOUS_RECOVERY_LADDER_FORBIDDEN_CLAIM_FIELDS: tuple[str, ...] = (
    "LIVE_END_TO_END_EVIDENCE_PROVEN",
)

LIVE_AUTONOMOUS_DEGRADATION_OWNER = OWNER
LIVE_AUTONOMOUS_RECOVERY_OWNER = OWNER
LIVE_AUTONOMOUS_RECOVERY_EVIDENCE_LADDER_OWNER = OWNER

EVIDENCE_DIRNAME = "capability_11_11_live_autonomous_recovery_and_degradation_evidence_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
