"""Standing constants for the P08 CASE_A nonzero adjudication persist/close.

Reuses classify_target_position_state_v1, classify_position_observation_v1,
and qty_numeric_status_v1. Does not GET, POST, flatten, mutate live gates,
or invent original wire bytes. Binds the already-executed authorized GET.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    ENDPOINT_ACCOUNT_POSITIONS,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_p08_position_observation_v1.constants_v1 import (
    CASE_A_TARGET_NONZERO,
    NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC,
    P08_CANONICAL_DEFINITION,
    RESULT_CLASS_200_OKX_0,
)

CAPABILITY_ID = "P08_NONZERO_POSITION_ADJUDICATION_PERSIST_CLOSE_V1"
PACKAGE_MARKER = "P08_NONZERO_POSITION_ADJUDICATION_PERSIST_CLOSE_V1=true"
OWNER = "ops.section_11_13_5_p08_nonzero_position_adjudication_persist_close_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "p08_nonzero_position_adjudication_persist_close.v1"
OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_P08_NONZERO_POSITION_ADJUDICATE_PERSIST_CLOSE_AND_PR_MAX_LEVERAGE_V1"
)
PRIOR_CAPTURE_OWNER_GO = "PEAK_TRADE_OWNER_GO_P08_UNFILTERED_ACCOUNT_POSITIONS_OBSERVATION_AFTER_QTY1_ORDER_ACCEPTANCE_V1"
WORKPACKAGE_ID = "OKX_EEA_P08_NONZERO_POSITION_ADJUDICATION_PERSIST_CLOSE_V1"
THIS_SLICE = "11.13.5.P08"
PREDECESSOR_SLICE = "11.13.5.P08_POST_READ_ONLY_EXHAUSTION_AUTHORITY_BOUNDARY"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_P08"
EXPECTED_ORIGIN_MAIN_SHA = "d59e5d3dcdc2b6c9e1ffec375c7a58508e21e71e"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_ENDPOINT = "GET /api/v5/account/positions"
ENDPOINT = ENDPOINT_ACCOUNT_POSITIONS
AUTHORIZED_OPERATION = (
    "OFFLINE_ADJUDICATION_AND_PERSIST_OF_ALREADY_CAPTURED_UNFILTERED_ACCOUNT_POSITIONS_GET"
)
AUTHORIZED_SCOPE = "A_P08_NONZERO_POSITION_ADJUDICATION_PERSIST_CLOSE_OFFLINE"

REQUEST_TIMESTAMP = "2026-09-03T22:37:25.851429Z"
RESPONSE_TIMESTAMP = "2026-09-03T22:37:26.102299Z"
CANONICAL_EVIDENCE_RUN_ID = "20260903T223726Z"
HTTP_STATUS = 200
OKX_CODE = "0"
OKX_MSG = ""
QUERY = {}
RAW_DATA_COUNT = 1
TARGET_INSTRUMENT_MATCH_COUNT = 1
AUTHORIZED_GET_COUNT = 1
ACTUAL_GET_COUNT = 1
THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0

AUTHORIZED_CLASSIFIER_ID = "classify_target_position_state_v1"
AUTHORIZED_CLASSIFIER_STATE = "TARGET_POSITION_NONZERO_PROVEN"
AUTHORIZED_SIGNED_POS = "1"
AUTHORIZED_CLASSIFIER_REASON = "TARGET_POSITION_NONZERO_PROVEN"
AUTHORIZED_QUERY_COMPLETENESS_PROVEN = False
AUTHORIZED_EMPTY_DATA_IS_ZERO = False

RESULT_CLASS = RESULT_CLASS_200_OKX_0
POSITION_OBSERVATION_CLASS = CASE_A_TARGET_NONZERO
P08_VERDICT = "P08_CLOSED_UNIQUE_TARGET_NONZERO_ROW_THIS_WINDOW"
NEXT_AUTHORITY_BOUNDARY = NEXT_AUTHORITY_BOUNDARY_CASE_A_QTY_NUMERIC
EARLIEST_UNRESOLVED_DEPENDENCY = "EXECUTION_PREREQUISITE_10_TARGET_POSITION_QTY_UNIT"
P08_CANONICAL_CLOSE_DEFINITION = P08_CANONICAL_DEFINITION

EMPTY_DATA_IS_ZERO = False
ABSENT_TARGET_ROW_IS_ZERO = False
TARGET_INSTRUMENT_NOT_OBSERVED = False
TARGET_POSITION_ZERO_PROVEN = False
TARGET_POSITION_ZERO_ROW_OBSERVED = False
TARGET_POSITION_NONZERO_PROVEN = True
P08_CLOSED = True
G_POSMODE_SUBMIT_BODY_PROVEN = False
ORIGINAL_WIRE_BODY_BYTES_AVAILABLE = False
RAW_FIELD_NORMALIZATION_PERFORMED = False
PLAUSIBILITY_RECONSTRUCTION_PERFORMED = False
FORENSIC_INPUT_MUTATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
POST_ALLOWED = False
GET_ALLOWED = False
SECOND_GET_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
P09_WORK_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
P08_CLOSE_DOES_NOT_GRANT_EXECUTION_READINESS = True
QUERY_COMPLETENESS_PROVEN_FALSE_DOES_NOT_INVALIDATE_OBSERVED_NONZERO_TARGET_ROW = True

EVIDENCE_DIRNAME = "section_11_13_5_p08_nonzero_position_adjudication_persist_close_v1"
CLASSIFIER_ID = AUTHORIZED_CLASSIFIER_ID
OBSERVATION_CLASSIFIER_ID = "classify_position_observation_v1"
QTY_NUMERIC_OWNER = "qty_numeric_status_v1"
REUSED_REST_HOST = AUTHORIZED_HOST
SECRETREF_URI = "secretref://vault/peak-trade/live-canary-minimum-exposure/okx"
