"""Standing constants for productive flatten POST and reconciliation."""

from __future__ import annotations

from src.ops.section_11_13_5_authenticated_private_runtime_read_and_runtime_permit_issuance_v1.constants_v1 import (
    AUTHORIZED_ACCOUNT_UID as REUSED_ACCOUNT_UID,
)
from src.ops.section_11_13_5_authenticated_private_runtime_read_and_runtime_permit_issuance_v1.runtime_permit_v1 import (
    PRICE_BINDING_ROLE,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.bounded_activation_permit_v1 import (
    BOUNDED_ACTIVATION_OWNER_GO_CANONICAL,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    DEFAULT_TD_MODE,
    ENDPOINT_ACCOUNT_POSITIONS,
    ENDPOINT_ORDER_GET,
    ENDPOINT_ORDERS_PENDING,
    ENDPOINT_SUBMIT,
    ENDPOINT_TRADE_FILLS,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.flatten_execute_authority_v1 import (
    FLATTEN_EXECUTE_CONFIRM_TOKEN_CANONICAL,
    FLATTEN_EXECUTE_OWNER_GO_CANONICAL,
    FLATTEN_EXECUTE_PURPOSE_CANONICAL,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.flatten_limit_price_contract_v1 import (
    FRESHNESS_THRESHOLD_MS,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.position_observation_freshness_contract_v1 import (
    POSITION_OBSERVATION_FRESHNESS_MAX_AGE_MS,
)
from src.ops.section_11_13_5_p13_execution_prerequisite_12_exact_flatten_payload_v1.constants_v1 import (
    OFFLINE_CONTRACT_PROOF_TICK_SZ,
)
from src.ops.section_11_13_5_productive_flatten_post_and_reconciliation_v1.contract_v1 import (
    EMPTY_DATA_IS_ZERO,
    FLATTEN_EXECUTE_INVOCATION_AUTHORIZED,
    MERGE_AUTHORIZED_BY_THIS_PERSIST,
    NETWORK_SESSION_INSTANCE_AUTHORIZED,
    PRODUCTIVE_FLATTEN_POST_AUTHORIZED,
    PRODUCTIVE_RECONCILIATION_AUTHORIZED,
    RETRY_ALLOWED,
    THIS_GO_DOES_NOT_SET_CANARY_AUTHORIZED,
    THIS_GO_DOES_NOT_SET_LIVE_AUTHORIZED,
)

CAPABILITY_ID = "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_V1"
PACKAGE_MARKER = "PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_V1=true"
OWNER = "ops.section_11_13_5_productive_flatten_post_and_reconciliation_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "productive_flatten_post_and_reconciliation.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_MAXIMUM_SAFE_LEVERAGE_V1"
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE_V1"
)
WORKPACKAGE_ID = "OKX_EEA_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION_V1"
THIS_SLICE = "11.13.5.PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION"
PREDECESSOR_SLICE = "11.13.5.AUTHENTICATED_PRIVATE_RUNTIME_READ_AND_RUNTIME_PERMIT_ISSUANCE"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION"
EXPECTED_ORIGIN_MAIN_SHA = "a23cb998d4d9121a7f06816cc54c0c6ce19a5992"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_ACCOUNT_UID
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
CANONICAL_TD_MODE = DEFAULT_TD_MODE
CANONICAL_TICK_SZ = OFFLINE_CONTRACT_PROOF_TICK_SZ
CANONICAL_POS_SIDE = "net"
CANONICAL_MARGIN_MODE = "cross"
CANONICAL_LEVERAGE = "3"
CANONICAL_OWNER_GO_TOKEN_FOUND = True
CANONICAL_FLATTEN_EXECUTE_TOKEN = FLATTEN_EXECUTE_CONFIRM_TOKEN_CANONICAL
CANONICAL_FLATTEN_EXECUTE_OWNER_GO = FLATTEN_EXECUTE_OWNER_GO_CANONICAL
CANONICAL_FLATTEN_EXECUTE_PURPOSE = FLATTEN_EXECUTE_PURPOSE_CANONICAL
CANONICAL_BOUNDED_ACTIVATION_OWNER_GO = BOUNDED_ACTIVATION_OWNER_GO_CANONICAL
AUTHORIZED_SCOPE = "H_THEN_J_PRODUCTIVE_FLATTEN_POST_AND_RECONCILIATION"
AUTHORIZED_OPERATION = (
    "FRESH_PRIVATE_READS_THEN_EXACTLY_ONE_REDUCE_ONLY_LIMIT_FLATTEN_POST_"
    "THEN_READ_ONLY_RECONCILIATION"
)
MAX_GET_COUNT = 8
MAX_POST_COUNT = 1
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
FRESHNESS_POLICY_MAX_AGE_MS = POSITION_OBSERVATION_FRESHNESS_MAX_AGE_MS
QUOTE_FRESHNESS_THRESHOLD_MS = FRESHNESS_THRESHOLD_MS
PRICE_BINDING_ROLE_VALUE = PRICE_BINDING_ROLE
ENDPOINT_TICKER = "/api/v5/market/ticker"
ENDPOINT_POSITIONS = ENDPOINT_ACCOUNT_POSITIONS
ENDPOINT_PENDING = ENDPOINT_ORDERS_PENDING
ENDPOINT_ORDER = ENDPOINT_ORDER_GET
ENDPOINT_FILLS = ENDPOINT_TRADE_FILLS
ENDPOINT_FLATTEN_POST = ENDPOINT_SUBMIT

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_GET_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_POST_TRANSPORT = "AuthenticatedGatedProductiveFlattenTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY

NAMED_REMAINING_HIGHER_AUTHORITY: tuple[str, ...] = (
    "OWNER_MERGE_GO",
    "SECTION_11_14_LIVE_EVIDENCE_LADDER",
)
EARLIEST_UNRESOLVED_DEPENDENCY = "OWNER_MERGE_GO_THEN_SECTION_11_14_IF_FLATTEN_PROVEN"
NEXT_AUTHORITY_BOUNDARY = "OWNER_MERGE_GO"
NEXT_WORKPACKAGE = "OWNER_MERGE_GO"
NEXT_OWNER_GO_REQUIRED = "OWNER_MERGE_GO"
MINIMUM_ADDITIONAL_OWNER_GO_COUNT = 1
WORKPACKAGE_COUNT = 1
CENSUS_RUNTIME_RESIDUAL = "MERGE_AND_SECTION_11_14_REMAIN_SEPARATE_OWNER_GO"
CENSUS_TEXT_REWRITTEN = False

PRODUCTIVE_FLATTEN_POST_AUTHORIZED_VALUE = PRODUCTIVE_FLATTEN_POST_AUTHORIZED
PRODUCTIVE_RECONCILIATION_AUTHORIZED_VALUE = PRODUCTIVE_RECONCILIATION_AUTHORIZED
FLATTEN_EXECUTE_INVOCATION_AUTHORIZED_VALUE = FLATTEN_EXECUTE_INVOCATION_AUTHORIZED
NETWORK_SESSION_INSTANCE_AUTHORIZED_VALUE = NETWORK_SESSION_INSTANCE_AUTHORIZED
RETRY_ALLOWED_VALUE = RETRY_ALLOWED
EMPTY_DATA_IS_ZERO_VALUE = EMPTY_DATA_IS_ZERO
THIS_GO_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = THIS_GO_DOES_NOT_SET_LIVE_AUTHORIZED
THIS_GO_DOES_NOT_SET_CANARY_AUTHORIZED_VALUE = THIS_GO_DOES_NOT_SET_CANARY_AUTHORIZED
MERGE_AUTHORIZED_BY_THIS_PERSIST_VALUE = MERGE_AUTHORIZED_BY_THIS_PERSIST

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P25_CLOSED = True
STP_CLOSED = True
APT_CLOSED = True
STPR_CLOSED = True
CENSUS_CLOSED = True
APRPI_CLOSED = True

CASE_A_TARGET_NONZERO = "CASE_A_TARGET_NONZERO"
CASE_B_TARGET_ZERO = "CASE_B_TARGET_ZERO"
CASE_C_EMPTY_DATA_NOT_ZERO = "CASE_C_EMPTY_DATA_NOT_ZERO"
CASE_D_TARGET_NOT_OBSERVED = "CASE_D_TARGET_NOT_OBSERVED"
CASE_E_HTTP_OR_OKX_ERROR = "CASE_E_HTTP_OR_OKX_ERROR"
CASE_F_AMBIGUOUS = "CASE_F_AMBIGUOUS"

STATUS_POST_SENT = "POST_SENT"
STATUS_POST_ACCEPTED = "POST_ACCEPTED"
STATUS_ORDER_EXISTS = "ORDER_EXISTS"
STATUS_ORDER_FILLED = "ORDER_FILLED"
STATUS_POSITION_REOBSERVED = "POSITION_REOBSERVED"
STATUS_TARGET_POSITION_ZERO_PROVEN = "TARGET_POSITION_ZERO_PROVEN"
STATUS_LIVE_FLATTEN_PROVABILITY_PROVEN = "LIVE_FLATTEN_PROVABILITY_PROVEN"

RESULT_CLASS_200_OKX_0 = "HTTP_200_OKX_0"
RESULT_CLASS_401_50110 = "HTTP_401_OKX_50110"
RESULT_CLASS_OTHER = "OTHER_FAIL_CLOSED"
RESULT_CLASS_TRANSPORT = "TRANSPORT_OR_CLIENT_FAIL"

DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_EVIDENCE_RUN_ID = "20260904T061816Z"
CANONICAL_RECOVERY_EVIDENCE_RUN_ID = "20260904T061816Z_recovery_read_only"
EVIDENCE_DIRNAME = "section_11_13_5_productive_flatten_post_and_reconciliation_v1"
PR_CHANGED_PATHS_FREEZE_DIRNAME = "pr_changed_paths_freeze_v1"
PR_CHANGED_PATHS_FREEZE_CONTRACT_VERSION = "pr_changed_paths_freeze.v1"
PR_CHANGED_PATHS_FREEZE_BASE_SHA = EXPECTED_ORIGIN_MAIN_SHA
PR_CHANGED_PATHS_FREEZE_HEAD_SHA = "1486b0989ccd8a8efbee6d488baf56c3c0f4bb1b"
PR_CHANGED_PATHS_FREEZE_COUNT = 35
PR_CHANGED_PATHS_FREEZE_SET_HASH = (
    "9d08d90b93583fced8a01fdcb419f4ec24f476656caa90ba1430c91e37a85c12"
)
PR_CHANGED_PATHS_FREEZE_GIT_SEMANTICS = "THREE_DOT_NAME_ONLY_LC_ALL_C_SORT"
PR_CHANGED_PATHS_FREEZE_GENERATOR_COMMAND = (
    "git diff --name-only "
    f"{PR_CHANGED_PATHS_FREEZE_BASE_SHA}...{PR_CHANGED_PATHS_FREEZE_HEAD_SHA}"
    " | LC_ALL=C sort"
)
PR_CHANGED_PATHS_TEMP_HISTORICAL = "/tmp/pfpr_changed_files_v1.txt"
