"""Fail-closed reason codes for Cap 2.2 append-only 15m PIT persistence."""

from __future__ import annotations

from enum import Enum


class Cap22AppendOnlyPitPersistenceFailureCodeV1(str, Enum):
    INVALID_ANCHOR = "INVALID_15M_ANCHOR"
    EVENT_TIME_MISSING = "EVENT_TIME_MISSING"
    EVENT_TIME_MISMATCH = "EVENT_TIME_MISMATCH"
    DIGEST_OR_SCHEMA_ERROR = "DIGEST_OR_SCHEMA_ERROR"
    INCOMPLETE_ECONOMIC_MD_SNAPSHOT = "INCOMPLETE_ECONOMIC_MD_SNAPSHOT"
    MISSING_CAP21_BINDING = "MISSING_CAP21_BINDING"
    CAP21_BINDING_MISMATCH = "CAP21_BINDING_MISMATCH"
    CONFLICTING_DUPLICATE = "CONFLICTING_DUPLICATE_AT_T"
    OVERWRITE_FORBIDDEN = "SILENT_OVERWRITE_FORBIDDEN"
    CORRUPT_PERSISTED_SNAPSHOT = "CORRUPT_PERSISTED_SNAPSHOT"
    SNAPSHOT_MISSING = "SNAPSHOT_MISSING"
