"""Standing constants for the post-whitelist one-shot private auth GET.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1, and
build_okx_live_canary_auth_headers_v1. Does not mint a second HTTP client,
signer, SecretRef owner, live/testnet/canary authority, or mutation path.
Does not authorize P08 observation or closure.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    ENDPOINT_ACCOUNT_CONFIG,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)

CAPABILITY_ID = "POST_Z2DS_POST_WHITELIST_PRIVATE_AUTH_ATTESTATION_SINGLE_GET_V1"
PACKAGE_MARKER = "POST_Z2DS_POST_WHITELIST_PRIVATE_AUTH_ATTESTATION_SINGLE_GET_V1=true"
OWNER = "ops.section_11_13_5_post_z2ds_post_whitelist_private_auth_attestation_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "post_z2ds_post_whitelist_private_auth_attestation.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_POST_WHITELIST_PRIVATE_AUTH_ATTESTATION_SINGLE_GET_V1"
WORKPACKAGE_ID = "OKX_EEA_POST_WHITELIST_PRIVATE_AUTH_ATTESTATION_SINGLE_GET_V1"
THIS_SLICE = "11.13.5.POST_Z2DS_POST_WHITELIST_PRIVATE_AUTH_ATTESTATION"
PREDECESSOR_SLICE = "11.13.5.POST_Z2DS_50110_WHITELIST_ADD_FROM_CAPTURE"
CURRENT_CANONICAL_SECTION = THIS_SLICE
EXPECTED_ORIGIN_MAIN_SHA = "f796e2f7497282862a1762f1bcc7a63ce4b99d9c"
AUTHORIZED_HOST = "eea.okx.com"

AUTHORIZED_OPERATION = "EXACTLY_ONE_AUTHENTICATED_NON_MUTATING_PRIVATE_GET_ACCOUNT_CONFIG"
AUTHORIZED_ENDPOINT = "GET /api/v5/account/config"
MAX_NETWORK_REQUEST_COUNT = 1
MAX_HTTP_EXCHANGE_COUNT = 1
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
RETRY_AUTHORIZED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
SECOND_GET_ALLOWED = False
SECOND_GET_AUTHORIZED = False
ALTERNATE_ENDPOINT_ALLOWED = False
PUBLIC_GET_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False
P08_OBSERVATION_ALLOWED = False
P08_CLOSE_ALLOWED = False
FUNDING_ALLOWED = False
POSITIONS_GET_ALLOWED = False
BALANCE_GET_ALLOWED = False
MAX_SIZE_GET_ALLOWED = False
KEY_ROTATION_ALLOWED = False
PERMISSION_CHANGE_ALLOWED = False
ORDER_SUBMIT_ALLOWED = False
POSITION_CREATION_ALLOWED = False
POSITION_MODIFICATION_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
G_POSMODE_REOPEN_ALLOWED = False
G_POSMODE_CLOSE_ALLOWED = False
HISTORICAL_IP_FALLBACK_ALLOWED = False

ENDPOINT = ENDPOINT_ACCOUNT_CONFIG
ENDPOINT_METHOD = "GET"
FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/positions",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET = False

EVIDENCE_DIRNAME = "section_11_13_5_post_z2ds_post_whitelist_private_auth_attestation_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "EXECUTION_PREREQUISITE_08_TARGET_POSITION_NONZERO_PROVEN"
)
NEXT_AUTHORITY_BOUNDARY_CASE_A = "SEPARATE_OWNER_GO_FOR_P08_POSITION_OBSERVATION"
NEXT_AUTHORITY_BOUNDARY_CASE_B = "NEW_PRIVATE_AUTH_WHITELIST_ADJUDICATION_REQUIRED"
NEXT_AUTHORITY_BOUNDARY_CASE_C = "FAIL_CLOSED_FRESH_ADJUDICATION_REQUIRED"
RESULT_CLASS_200_OKX_0 = "HTTP_200_OKX_0"
RESULT_CLASS_401_50110 = "HTTP_401_OKX_50110"
RESULT_CLASS_OTHER = "OTHER_FAIL_CLOSED"
AUTH_SUCCESS_PROVEN = "PROVEN_FOR_THIS_ENDPOINT_AND_OBSERVATION_TIME"
AUTH_SUCCESS_FALSE = False
AUTH_SUCCESS_NOT_PROVEN = "NOT_PROVEN"
CLEARANCE_PROVEN = "PROVEN_FOR_THIS_ENDPOINT_AND_OBSERVATION_TIME"
CLEARANCE_FALSE = False
CLEARANCE_NOT_PROVEN = "NOT_PROVEN"
BLOCKER_CLEARED = "CLEARED_AT_OBSERVATION_TIME"
BLOCKER_OPEN = "OPEN"
BLOCKER_NOT_PROVEN = "NOT_PROVEN"
PRIVATE_AUTH_RESULT_OTHER = "OTHER_FAIL_CLOSED"
