"""Authority and effect markers for the offline DDO contract foundation v0.

This module is the package-local authority declaration. It does not confer
runtime, promotion, trading, risk, safety, or execution authority.
"""

from __future__ import annotations

from typing import Final

PACKAGE_ID: Final[str] = "peak_trade.learning.deterministic_decision_outcome_v0"
WORKPACKAGE_ID: Final[str] = (
    "WP_FA_06_OFFLINE_LEARNING_REGISTRY_VALIDATION_PACKS_AND_SHADOW_CHALLENGER_V1"
)
AUTHORITY_CLASS: Final[str] = "OFFLINE_OBSERVATION_ADAPTER_WITH_PRODUCTIVE_HOST_HOOK"
EVALUATION_ENGINE_AUTHORITY_CLASS: Final[str] = (
    "OFFLINE_DETERMINISTIC_NON_AUTHORIZING_EVALUATION_ENGINE"
)
AUTHORITY_OWNER: Final[str] = "NONE"
RUNTIME_EFFECT: Final[str] = "NONE"
CAPTURE_RUNTIME_EFFECT: Final[str] = "OBSERVATION_ONLY"
EVALUATION_RUNTIME_EFFECT: Final[str] = "NONE"
LIVE_EFFECT: Final[str] = "NONE"
TESTNET_EFFECT: Final[str] = "NONE"
CANARY_EFFECT: Final[str] = "NONE"
EXECUTION_EFFECT: Final[str] = "NONE"
TRADING_CORE_EFFECT: Final[str] = "NONE"
SELECTION_EFFECT: Final[str] = "NONE"
RISK_EFFECT: Final[str] = "NONE"
SAFETY_EFFECT: Final[str] = "NONE"
PROMOTION_AUTHORITY_EFFECT: Final[str] = "NONE"
PROMOTION_AUTHORITY_ACTIVATION: Final[bool] = False
PROMOTION_CONTROLLER_CODE_PRESENT: Final[bool] = True
PROMOTION_ELIGIBILITY_COMPUTATION_ALLOWED: Final[bool] = True
LEARNING_PRODUCTIVE_AUTHORITY: Final[str] = "NONE"
NETWORK_EFFECT: Final[str] = "NONE"
SECTION_11_13_5_DEPENDENCY: Final[str] = "NONE"
CAPTURE_ADAPTER_PRESENT: Final[bool] = True
AUTO_CAPTURE_ENABLED: Final[bool] = True
OUTCOME_ENGINE_PRESENT: Final[bool] = True
ATTRIBUTION_ENGINE_PRESENT: Final[bool] = True
COUNTERFACTUAL_ENGINE_PRESENT: Final[bool] = True
REPLAY_ENGINE_PRESENT: Final[bool] = True
LEARNING_REGISTRY_ENGINE_PRESENT: Final[bool] = True
VALIDATION_PACK_ENGINE_PRESENT: Final[bool] = True
SHADOW_CHALLENGER_ENGINE_PRESENT: Final[bool] = True
VALIDATOR_PRODUCTIVE_AUTHORITY: Final[str] = "NONE"
SHADOW_PRODUCTIVE_AUTHORITY: Final[str] = "NONE"
EVALUATION_RUNTIME_WIRING: Final[bool] = False
PRODUCTIVE_CAPTURE_ADAPTERS: Final[bool] = True
PRODUCTIVE_RUNTIME_WIRING: Final[bool] = True
AUTONOMY_SUPERVISOR_CODE_PRESENT: Final[bool] = True
AUTONOMY_SUPERVISOR_RUNTIME_REACHABILITY: Final[bool] = False
AUTONOMY_SUPERVISOR_EXECUTION_AUTHORITY: Final[bool] = False
PRODUCTIVE_DEPLOYMENT_ALLOWED: Final[bool] = False
PRODUCTIVE_ROLLBACK_ALLOWED: Final[bool] = False
PROMOTION_OWNER_FORKED: Final[bool] = False
SECOND_TRADING_AUTHORITY_CREATED: Final[bool] = False
SECOND_SELECTION_AUTHORITY_CREATED: Final[bool] = False
SECOND_PROMOTION_AUTHORITY_CREATED: Final[bool] = False
SECOND_RISK_SAFETY_AUTHORITY_CREATED: Final[bool] = False
SECOND_EXECUTION_AUTHORITY_CREATED: Final[bool] = False
BLUEPRINT_AUTHORITY: Final[str] = "NONE"
BLUEPRINT_ROLE: Final[str] = "FUTURE_DESIGN_TARGET_NOT_CURRENT_STATE"
MASTER_RUNBOOK_MUTATED: Final[bool] = False
