"""Standing constants for §11.13.5.Z2DL one-shot private Auth GET.

Reuses LiveCanaryHttpClientV1, UrllibLiveCanaryTransportV1, and
build_okx_live_canary_auth_headers_v1. Does not mint a second HTTP client,
signer, SecretRef owner, live/testnet/canary authority, or mutation path.
Does not reuse consumed Z2DH/Z2DK Owner-GOs.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    ENDPOINT_ACCOUNT_CONFIG,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REQUIRED_CREDENTIAL_CLASS,
    REQUIRED_SECRETREF_URI,
    REUSED_BINDING_REST_HOST,
    REUSED_BINDING_VENUE,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
    USER_AGENT_CANARY,
)

CAPABILITY_ID = "Z2DL_POST_REMEDIATION_SINGLE_PRIVATE_AUTH_GET_V1"
PACKAGE_MARKER = "Z2DL_POST_REMEDIATION_SINGLE_PRIVATE_AUTH_GET_V1=true"
OWNER = "ops.section_11_13_5_z2dl_post_remediation_single_private_auth_get_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "z2dl_post_remediation_single_private_auth_get.v1"
OWNER_GO = "PEAK_TRADE_OWNER_GO_Z2DL_POST_REMEDIATION_SINGLE_PRIVATE_AUTH_GET_V1"
WORKPACKAGE_ID = "POST_REMEDIATION_SINGLE_PRIVATE_AUTH_GET_V1"
THIS_SLICE = "11.13.5.Z2DL"
PREDECESSOR_SLICE = "11.13.5.Z2DK"
CURRENT_CANONICAL_SECTION = "11.13.5.Z2DL"
EXPECTED_ORIGIN_MAIN_SHA = "a074995099ad8473a79cf281adc8052de0b874bd"
LAST_MERGED_PR = "6223"
AUTHORIZED_HOST = "eea.okx.com"

AUTHORIZED_OPERATION = "EXACTLY_ONE_ACTUAL_AUTHENTICATED_READ_ONLY_GET"
AUTHORIZED_ENDPOINT = "GET /api/v5/account/config"
MAX_NETWORK_REQUEST_COUNT = 1
MAX_HTTP_EXCHANGE_COUNT = 1
DEFAULT_MAX_RETRIES = 0
DEFAULT_TIMEOUT_SECONDS = 10.0
RETRY_ALLOWED = False
REDIRECT_FOLLOW_ALLOWED = False
FALLBACK_REQUEST_ALLOWED = False
SECOND_GET_ALLOWED = False
ALTERNATE_ENDPOINT_ALLOWED = False
WHITELIST_MUTATION_ALLOWED = False
CREDENTIAL_MUTATION_ALLOWED = False
SECRETREF_CHANGE_ALLOWED = False

ENDPOINT = ENDPOINT_ACCOUNT_CONFIG
ENDPOINT_METHOD = "GET"
FORBIDDEN_ENDPOINTS: tuple[str, ...] = (
    "/api/v5/asset/balances",
    "/api/v5/account/balance",
    "/api/v5/account/positions",
    "/api/v5/account/max-size",
    "/api/v5/account/leverage-info",
    "/api/v5/asset/transfer",
    "/api/v5/asset/withdrawal",
    "/api/v5/trade/order",
)

REUSED_REST_HOST = REUSED_BINDING_REST_HOST
REUSED_VENUE = REUSED_BINDING_VENUE
REUSED_REST_BASE = f"https://{REUSED_BINDING_REST_HOST}"
REUSED_HTTP_CLIENT = "LiveCanaryHttpClientV1"
REUSED_TRANSPORT = "UrllibLiveCanaryTransportV1"
REUSED_SIGNER = "build_okx_live_canary_auth_headers_v1"
REUSED_SECRETREF_URI = REQUIRED_SECRETREF_URI
REUSED_CREDENTIAL_CLASS = REQUIRED_CREDENTIAL_CLASS
REUSED_USER_AGENT = USER_AGENT_CANARY
SECOND_HTTP_CLIENT_CREATED = False
SECOND_SIGNER_CREATED = False
SECOND_SECRETREF_OWNER_CREATED = False
GENERIC_ALLOWLIST_BYPASS_CREATED = False
NEW_TRANSPORT_CLASS_CREATED = False
NEW_AUTH_SIGNING_IMPLEMENTATION = False
CAPITAL_MOVEMENT_PRODUCER_CREATED = False

STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_ORDERS_ALLOWED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED
TRANSFER_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
CAPITAL_MOVEMENT_ALLOWED = False
AUTHORITY_EXPANSION_BEYOND_THIS_GET = False

EVIDENCE_DIRNAME = "section_11_13_5_z2dl_post_remediation_single_private_auth_get_v1"
DEFAULT_VAULT_RELATIVE = "section_11_13_5_live_canary_minimum_exposure/secrets/secretref_vault.json"
CANONICAL_LIVE_EARLIEST_UNRESOLVED_DEPENDENCY = (
    "NO_AUTHORIZED_REACHABLE_PRODUCER_OF_NONZERO_VENUE_POSITION_REQUIRED_BY_PREREQUISITE_08"
)
SANITIZED_EGRESS_EVIDENCE = "NOT_OBSERVED_THIS_REQUEST_NO_SECOND_LOOKUP"
