"""Standing constants for bounded K1 macOS Keychain provisioning authority.

No standing Keychain write. No credential load. No network. No secret persist.
"""

from __future__ import annotations

from src.ops.full_core_live_path_composition_root_v1.checkout_independent_credential_concrete_backend_item_identity_v1 import (
    KEYCHAIN_ACCOUNT_ID,
    KEYCHAIN_SERVICE_ID,
    PROVIDER_REF_IDENTIFIER,
    SOURCE_REF_URI,
)
from src.ops.pl_tf_002_productive_read_only_session_executor_v1.constants_v1 import (
    K1_KEYCHAIN_UTF8_JSON_FIELD_API_KEY,
    K1_KEYCHAIN_UTF8_JSON_FIELD_PASSPHRASE,
    K1_KEYCHAIN_UTF8_JSON_FIELD_SECRET_KEY,
    K1_KEYCHAIN_UTF8_JSON_REQUIRED_FIELDS,
)

CAPABILITY_ID = "K1_PRODUCTIVE_MACOS_KEYCHAIN_PROVISIONING_AUTHORITY_V1"
PACKAGE_MARKER = "K1_PRODUCTIVE_MACOS_KEYCHAIN_PROVISIONING_AUTHORITY_V1=true"
OWNER = "ops.k1_productive_macos_credential_store_provisioning_authority_v1"
SCHEMA_VERSION = "k1_productive_macos_keychain_provisioning_authority.v1"
CONTRACT_VERSION = "v1"
WP_ID = "K1_PRODUCTIVE_KEYCHAIN_PROVISIONING_AUTHORITY_V1"

OWNER_GO = "OWNER_GO_K1_PRODUCTIVE_MACOS_KEYCHAIN_PROVISIONING_V1"

PROVISIONING_AUTHORITY_OWNER = OWNER
PROVISIONING_TARGET = f"service={KEYCHAIN_SERVICE_ID};account={KEYCHAIN_ACCOUNT_ID};provider_ref={PROVIDER_REF_IDENTIFIER}"

ALLOWED_OPERATION = "BOUNDED_UPSERT_OPAQUE_UTF8_JSON_AT_DZ_TUPLE_ONLY"
FORBIDDEN_OPERATIONS = (
    "OTHER_KEYCHAIN_ITEMS",
    "DELETE_ALL",
    "WILDCARD_QUERY",
    "CREDENTIAL_DISCOVERY",
    "ALTERNATE_BACKEND",
    "K2_LEGACY",
    "REPO_PERSIST",
    "SECRET_LOGGING",
    "VENUE_WIRE",
    "AUTO_ROTATION",
    "AUTO_KEY_GENERATION",
)

INPUT_BOUNDARY = "EPHEMERAL_CALLER_SUPPLIED_FIELDS_ONLY"
SECRET_LIFETIME = "ZERO_REPO_RETENTION;WIPE_AFTER_ENCODE"
VERIFICATION_CONTRACT = "POST_WRITE_SHAPE_FINGERPRINT_ONLY_NO_SECRET_EMIT"

WRITE_AUTHORIZATION_DEFAULT = False
REAL_KEYCHAIN_WRITE_AUTHORIZED = False
REAL_KEYCHAIN_WRITE_IMPLEMENTED = True
EXTERNAL_EFFECT_AUTHORIZED = False
NETWORK_EXECUTION_AUTHORIZED = False
K2_REINTRODUCED = False
ALTERNATIVE_CREDENTIAL_AUTHORITY_CREATED = False

EPHEMERAL_PROVISIONING_CONSUMER = CAPABILITY_ID

MIN_OKX_MATERIAL_FIELD_LEN = 8
MINIMAL_TRIPLE_STUB_OPAQUE_LEN = 47
