"""Ratified productive reconciliation single-check + Master-V2 entry contract.

Governance-only markers; runtime enforcement lives in admission validation and
``run_current_productive_master_v2_runtime_cycle_v1``. Does not activate live,
testnet, orders, or external effects.

RUNTIME_AUTHORIZATION_EFFECT=NONE
"""

from __future__ import annotations

from src.ops.productive_reconciliation_runtime_binding_v1.constants_v1 import (
    AUTHORITY_OWNER,
    OWNER,
)

CONTRACT_ID = "PRODUCTIVE_RECONCILIATION_SINGLE_CHECK_MASTER_V2_ENTRY_V1"
SCHEMA_VERSION = "productive_reconciliation_single_check_master_v2_entry.v1"

PRODUCTIVE_PORTFOLIO_RECONCILIATION_SINGLE_CHECK = True
PRODUCTIVE_MASTER_V2_ENTRY_REQUIRES_UPSTREAM_SUCCESSFUL_RECONCILIATION = True
MASTER_V2_RECHECK_REQUIRED = False
DOUBLE_PLAY_RECHECK_REQUIRED = False
DOWNSTREAM_RECONCILIATION_STATE_MAY_BE_PROPAGATED = True
RECONCILIATION_AUTHORITY_TRANSFER = False

RECONCILIATION_OWNER = OWNER
RECONCILIATION_AUTHORITY_OWNER = AUTHORITY_OWNER

PRE_EXTERNAL_TERMINAL = True
POST_ALLOWED = False
EXTERNAL_EFFECT_AUTHORIZED = False
TESTNET_AUTHORIZED = False
LIVE_AUTHORIZED = False

assert PRODUCTIVE_PORTFOLIO_RECONCILIATION_SINGLE_CHECK is True
assert PRODUCTIVE_MASTER_V2_ENTRY_REQUIRES_UPSTREAM_SUCCESSFUL_RECONCILIATION is True
assert MASTER_V2_RECHECK_REQUIRED is False
assert DOUBLE_PLAY_RECHECK_REQUIRED is False
assert DOWNSTREAM_RECONCILIATION_STATE_MAY_BE_PROPAGATED is True
assert RECONCILIATION_AUTHORITY_TRANSFER is False
assert RECONCILIATION_OWNER == "ops.productive_reconciliation_runtime_binding_v1"

__all__ = [
    "CONTRACT_ID",
    "DOUBLE_PLAY_RECHECK_REQUIRED",
    "DOWNSTREAM_RECONCILIATION_STATE_MAY_BE_PROPAGATED",
    "EXTERNAL_EFFECT_AUTHORIZED",
    "LIVE_AUTHORIZED",
    "MASTER_V2_RECHECK_REQUIRED",
    "POST_ALLOWED",
    "PRE_EXTERNAL_TERMINAL",
    "PRODUCTIVE_MASTER_V2_ENTRY_REQUIRES_UPSTREAM_SUCCESSFUL_RECONCILIATION",
    "PRODUCTIVE_PORTFOLIO_RECONCILIATION_SINGLE_CHECK",
    "RECONCILIATION_AUTHORITY_OWNER",
    "RECONCILIATION_AUTHORITY_TRANSFER",
    "RECONCILIATION_OWNER",
    "SCHEMA_VERSION",
    "TESTNET_AUTHORIZED",
]
