"""PEAK_TRADE_PUBLIC_MARKET_DATA_RUNTIME_V1 — observation-only public data plane."""

from __future__ import annotations

CAPABILITY_ID = "PEAK_TRADE_PUBLIC_MARKET_DATA_RUNTIME_V1"
PACKAGE_MARKER = "PEAK_TRADE_PUBLIC_MARKET_DATA_RUNTIME_V1=true"
SCHEMA_VERSION = "peak_trade_public_market_data_runtime.v1"
OWNER = "ops.peak_trade_public_market_data_runtime_v1"

POLICY_CONFIG_RELATIVE = "config/governance/peak_trade_public_market_data_runtime_v1_policy_v1.json"

PUBLIC_V1_MARK_PRICE_MAX_AGE_SECONDS = 5
PUBLIC_V1_BEST_BID_ASK_MAX_AGE_SECONDS = 5
PUBLIC_V1_TRADE_FRESHNESS_POLICY = "CONSUMER_SPECIFIC"
PUBLIC_V1_TRADE_GLOBAL_MAX_AGE_SECONDS = None
PUBLIC_V1_RETENTION_POLICY = "TIERED_SEMANTIC"

EEA_REST_HOST = "eea.okx.com"
EEA_PUBLIC_WS_BASE = "wss://wseea.okx.com:8443/ws/v5/public"
FORBIDDEN_WS_AUTHORITY_HOSTS = frozenset({"wseeapap.okx.com"})

RANKING_FINALIZED_PT1M_MARK_COUNT = 61
PT1M_STEP_MS = 60_000
O4_AUTHORITATIVE_INTERVAL = "PT1H"

SELECTION_AUTHORITY = "NONE"
STRATEGY_AUTHORITY = "NONE"
PROMOTION_AUTHORITY = "NONE"
EXECUTION_AUTHORITY = "NONE"
WIRE_AUTHORITY = "NONE"

MULTI_FUTURE_RUNTIME_AUTHORIZED = False
MAX_POSITIONS_EFFECTIVE = 1

MARK_PRICE_REST_PATH = "/api/v5/public/mark-price"
TICKER_REST_PATH = "/api/v5/market/ticker"
TRADES_REST_PATH = "/api/v5/market/trades"
MARK_HISTORY_CANDLES_PATH = "/api/v5/market/history-mark-price-candles"

DEFAULT_MAX_RECONNECT_ATTEMPTS = 10
DEFAULT_HEARTBEAT_SECONDS = 5.0
DEFAULT_BACKOFF_INITIAL_SECONDS = 1.0
DEFAULT_BACKOFF_MAX_SECONDS = 30.0

FACT_STORE_SCHEMA = "peak_trade_public_market_fact_record.v1"
