"""Read-only safety and authority boundary attestation for WP-A."""

from __future__ import annotations

from typing import Any

from src.ops.full_core_live_path_composition_root_v1.constants_v1 import (
    EXTERNAL_EFFECT_AUTHORIZED,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    POST_ALLOWED,
    PRODUCTIVE_WIRE_SEND_REACHABLE,
    REAL_EXTERNAL_EFFECT_AUTHORIZED,
    REAL_VENUE_POST_ALLOWED,
    SUBMISSION_AUTHORIZED,
    WIRE_SEND_PERMITTED,
)
from src.ops.peak_trade_public_market_data_runtime_v1.constants_v1 import (
    EXECUTION_AUTHORITY,
    MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED,
    PROMOTION_AUTHORITY,
    SELECTION_AUTHORITY,
    WIRE_AUTHORITY,
)


def public_runtime_safety_attestation_v1() -> dict[str, Any]:
    return {
        "LIVE_ENABLED": LIVE_ENABLED is True,
        "LIVE_ARMED": LIVE_ARMED is True,
        "WIRE_SEND_PERMITTED": WIRE_SEND_PERMITTED is True,
        "SUBMISSION_AUTHORIZED": SUBMISSION_AUTHORIZED is True,
        "LIVE_AUTHORIZED": LIVE_AUTHORIZED is True,
        "PRODUCTIVE_WIRE_SEND_REACHABLE": PRODUCTIVE_WIRE_SEND_REACHABLE is True,
        "EXTERNAL_EFFECT_AUTHORIZED": EXTERNAL_EFFECT_AUTHORIZED,
        "REAL_EXTERNAL_EFFECT_AUTHORIZED": REAL_EXTERNAL_EFFECT_AUTHORIZED,
        "REAL_VENUE_POST_ALLOWED": REAL_VENUE_POST_ALLOWED,
        "POST_ALLOWED": POST_ALLOWED,
        "MULTI_FUTURE_RUNTIME_AUTHORIZED": MULTI_FUTURE_RUNTIME_AUTHORIZED,
        "MAX_POSITIONS_EFFECTIVE": MAX_POSITIONS_EFFECTIVE,
        "SELECTION_AUTHORITY": SELECTION_AUTHORITY,
        "EXECUTION_AUTHORITY": EXECUTION_AUTHORITY,
        "PROMOTION_AUTHORITY": PROMOTION_AUTHORITY,
        "WIRE_AUTHORITY": WIRE_AUTHORITY,
        "public_runtime_may_post": False,
    }
