"""Fail-closed reason codes for B05 feature production."""

from __future__ import annotations

from enum import Enum


class RankingFeatureProductionReasonCodeV1(str, Enum):
    MISSING_MARK_PRICE = "MISSING_MARK_PRICE"
    NONPOSITIVE_MARK_PRICE = "NONPOSITIVE_MARK_PRICE"
    NON_FINALIZED_MARK = "NON_FINALIZED_MARK"
    NON_CONTIGUOUS_PT1M = "NON_CONTIGUOUS_PT1M"
    INSUFFICIENT_PT1M_MARK_WARMUP = "INSUFFICIENT_PT1M_MARK_WARMUP"
    AMPLITUDE_MID_NONPOSITIVE = "AMPLITUDE_MID_NONPOSITIVE"
    AMPLITUDE_PMIN_NONPOSITIVE = "AMPLITUDE_PMIN_NONPOSITIVE"
    COMPUTE_ERROR = "COMPUTE_ERROR"
