"""Constants for §11.12.8 productive Testnet campaign RUN (implementation only).

Layers (must not be conflated):
  FIXTURE_PROOF = Cap 11 §11.12.8 fixture-only residual
  PRODUCTIVE_TESTNET_PATH = Cap 11 §11.12.8 path package (gates; no run)
  PRODUCTIVE_TESTNET_EXECUTION = Cap 11 §11.12.8 execution package (executor; no run)
  PRODUCTIVE_TESTNET_RUN = this package (run surface present; no campaign start)
  PRODUCTIVE_TESTNET_RUN_ACTIVATION = later separate Owner-GO (out of scope)
"""

from __future__ import annotations

from src.ops.capability_11_section_11_12_8_productive_testnet_campaign_execution_v1.constants_v1 import (
    CANONICAL_ALLOWED_ORDER_TYPES as EXEC_ALLOWED_ORDER_TYPES,
    CANONICAL_EMERGENCY_COMMANDS as EXEC_EMERGENCY_COMMANDS,
    CANONICAL_INSTRUMENT_SCOPE as EXEC_INSTRUMENT_SCOPE,
    CANONICAL_POSITION_COUNT_LIMIT as EXEC_POSITION_COUNT_LIMIT,
    CANONICAL_RUNTIME_MODE as EXEC_RUNTIME_MODE,
    CANONICAL_VENUE as EXEC_VENUE,
    CAPABILITY_ID as EXEC_CAPABILITY_ID,
    FORBIDDEN_CONFIRM_TOKEN_ARGV_FLAGS as EXEC_FORBIDDEN_CONFIRM_ARGV,
    FORBIDDEN_CONFIRM_TOKEN_ENV_KEYS as EXEC_FORBIDDEN_CONFIRM_ENV,
    OWNER as EXEC_OWNER,
)

CAPABILITY_ID = "CAPABILITY_11_SECTION_11_12_8_PRODUCTIVE_TESTNET_CAMPAIGN_RUN_V1"
PACKAGE_MARKER = "CAPABILITY_11_SECTION_11_12_8_PRODUCTIVE_TESTNET_CAMPAIGN_RUN_V1=true"
OWNER = "ops.capability_11_section_11_12_8_productive_testnet_campaign_run_v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID = EXEC_CAPABILITY_ID
PREDECESSOR_OWNER = EXEC_OWNER
NEXT_CONSUMER_CAPABILITY_ID = (
    "SEPARATE_OWNER_GO_REQUIRED_FOR_PRODUCTIVE_TESTNET_CAMPAIGN_RUN_ACTIVATION"
)

CORE_LOGIC_CHANGE = False
ACTIVATION_STATE = "not_activated"
RUNTIME_ACTIVATED = False
REFERENCE_ONLY = False

# Layer claims.
EXECUTION_PREDECESSOR_PRESERVED = True
PRODUCTIVE_TESTNET_CAMPAIGN_RUN_IMPLEMENTED = True
PRODUCTIVE_TESTNET_CAMPAIGN_RUN_SURFACE_PRESENT = True
PRODUCTIVE_TESTNET_CAMPAIGN_RUN_SURFACE_ABSENT = False

# Permanent fail-closed — this OWNER_GO is IMPLEMENTATION_ONLY / RUN_AUTHORIZED=false.
RUN_AUTHORIZED = False
PRODUCTIVE_TESTNET_CAMPAIGN_STARTED = False
PRODUCTIVE_TESTNET_CAMPAIGN_COMPLETED = False
PRODUCTIVE_TESTNET_CAMPAIGN_ACTIVATED = False
NETWORK_SESSION_STARTED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
AUTHORIZATION_CONSUMED = False
CONFIRM_TOKEN_ISSUANCE_ALLOWED = False
CONFIRM_TOKEN_CONSUMPTION_ALLOWED = False
FUTURE_RUN_GO_CONSUMPTION_ALLOWED = False
FUTURE_RUN_GO_CONSUMED = False
ORDER_SEND_DISABLED = True
ORDERS_AUTHORIZED = False
ORDER_PATH_STARTED = False
ORDER_SUBMIT_PERFORMED = False
MUTATING_EXCHANGE_CALLS = False
NETWORK_WRITES_AUTHORIZED = False
NETWORK_WRITE_PERFORMED = False
NETWORK_EFFECT = "NONE"
ORDER_EFFECT = "NONE"
LIVE_ORDER_EFFECT = "NONE"
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
TESTNET_ORDER_SUBMIT_PERFORMED = False
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
LIVE_AUTHORIZED = False
TESTNET_AUTHORIZED = False
CAPABILITY_11_13_STARTED = False
SECTION_11_13_STARTED = False
KILL_SWITCH_CONTRACT_ACTIVATED = False
CAMPAIGN_SIDE_EFFECTS_AUTHORIZED = False

MODE_PROVE_RUN_ONLY = "PROVE_RUN_ONLY"
MODE_GOVERNED_RUN_GATE = "GOVERNED_CAMPAIGN_RUN_GATE"
PATH_CLASS = "PRODUCTIVE_TESTNET_CAMPAIGN_RUN"

CANONICAL_RUNTIME_MODE = EXEC_RUNTIME_MODE
CANONICAL_VENUE = EXEC_VENUE
CANONICAL_INSTRUMENT_SCOPE: tuple[str, ...] = EXEC_INSTRUMENT_SCOPE
CANONICAL_ALLOWED_ORDER_TYPES: tuple[str, ...] = EXEC_ALLOWED_ORDER_TYPES
CANONICAL_POSITION_COUNT_LIMIT = EXEC_POSITION_COUNT_LIMIT
CANONICAL_EMERGENCY_COMMANDS: tuple[str, ...] = EXEC_EMERGENCY_COMMANDS
FORBIDDEN_CONFIRM_TOKEN_ARGV_FLAGS = EXEC_FORBIDDEN_CONFIRM_ARGV
FORBIDDEN_CONFIRM_TOKEN_ENV_KEYS = EXEC_FORBIDDEN_CONFIRM_ENV

REQUIRED_PRECONDITIONS: tuple[str, ...] = (
    "execution_predecessor_bound",
    "execution_gate_admissible",
    "testnet_only_scope",
    "live_path_blocked",
    "credential_scope_testnet",
    "owner_authorization_bound",
    "confirm_token_digest_bound",
    "campaign_enabled",
    "campaign_armed",
    "kill_switch_operational",
    "emergency_control_operational",
    "risk_scope_within_authority",
    "run_authorized_ephemeral",
    "side_effects_unauthorized_permanent",
    "campaign_not_started",
    "future_run_go_not_consumed",
    "cap_11_13_not_started",
    "network_effect_none",
    "order_effect_none",
)

EVIDENCE_DIRNAME = "capability_11_section_11_12_8_productive_testnet_campaign_run_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
