"""R6 S2 structural portfolio-risk contract dimensions (read-only).

Statuses are contract/boundary classifications. Name collision with
research helpers is not productive VaR authority. Numerics remain
DEFERRED_UNRATIFIED and are not required to close S2.
"""

from __future__ import annotations

from src.ops.canonical_r6_s2_portfolio_risk_contracts_v1.models_v1 import (
    ContractDimensionRowV1,
    ContractItemStatus,
    R6S2PortfolioRiskError,
)

_CP = ContractItemStatus.CLOSED_PROVEN
_CB = ContractItemStatus.CLOSED_BOUNDARY
_NRS = ContractItemStatus.NOT_REQUIRED_AT_S2

REQUIRED_ITEM_IDS = (
    "component_per_instrument_exposure",
    "component_per_instrument_loss_risk_budget",
    "component_per_instrument_var_semantics",
    "component_missing_data_behavior",
    "component_stale_data_behavior",
    "portfolio_aggregate_exposure",
    "portfolio_gross_exposure",
    "portfolio_net_exposure",
    "portfolio_var",
    "portfolio_component_marginal_var",
    "portfolio_cvar_expected_shortfall",
    "portfolio_concentration_limits",
    "portfolio_loss_budget",
    "correlation_estimation_semantics",
    "correlation_insufficient_history",
    "correlation_unstable_nan",
    "correlation_fallback_behavior",
    "correlation_zero_corr_prohibition",
    "capital_envelope_ownership",
    "risk_budget_ownership",
    "portfolio_weights_vs_trading_authority",
    "active_set_input_boundary",
    "no_allocation_order_bypass",
    "safety_global_kill_interaction",
    "safety_per_instrument_kill_interaction",
    "safety_auto_liquidation_i12",
    "safety_max_position_invariant",
    "safety_fail_closed_inconsistent_aggregate",
    "accounting_one_global_writer",
    "accounting_per_instrument_state_isolation",
    "accounting_portfolio_aggregation_derived",
    "accounting_restart_reconstruction",
    "accounting_duplicate_missing_position",
    "evidence_required_inputs",
    "evidence_deterministic_output",
    "evidence_identity_lineage",
    "evidence_verifier_expectations",
    "evidence_needed_before_s3_s4_s5",
)


def _row(
    item_id: str,
    *,
    family: str,
    status: ContractItemStatus,
    current_binding: str,
    owner: str,
    reuse_candidate: str,
    later_requirement: str,
) -> ContractDimensionRowV1:
    return ContractDimensionRowV1(
        item_id=item_id,
        family=family,
        status=status,
        current_binding=current_binding,
        owner=owner,
        reuse_candidate=reuse_candidate,
        later_requirement=later_requirement,
    )


S2_DIMENSIONS: tuple[ContractDimensionRowV1, ...] = (
    _row(
        "component_per_instrument_exposure",
        family="A_COMPONENT_RISK",
        status=_CB,
        current_binding="N=1; Cap1.1 PHASE1_MAX_OPEN_POSITIONS=1; capital_risk_sizing exposure caps",
        owner="src.governance.capital_risk_sizing_v1",
        reuse_candidate="src.risk.portfolio.compute_position_notional",
        later_requirement="per_instrument_exposure_matrix_at_S3_behind_flags",
    ),
    _row(
        "component_per_instrument_loss_risk_budget",
        family="A_COMPONENT_RISK",
        status=_CB,
        current_binding="single-instrument daily/trade risk envelopes in capital_risk_sizing_v1; MF budgets unratified",
        owner="src.governance.capital_risk_sizing_v1",
        reuse_candidate="src.governance.capital_risk_sizing_v1",
        later_requirement="NUMERIC_POLICY_STATUS=DEFERRED_UNRATIFIED_until_S5",
    ),
    _row(
        "component_per_instrument_var_semantics",
        family="A_COMPONENT_RISK",
        status=_CB,
        current_binding="I37 methods exist as supporting library; not current risk authority; I85 is contract identity",
        owner="canonical_risk_chain + I85_identity",
        reuse_candidate="src.risk.var; src.risk.component_var",
        later_requirement="S3 may consume I37 methods behind flags; no second VaR owner",
    ),
    _row(
        "component_missing_data_behavior",
        family="A_COMPONENT_RISK",
        status=_CP,
        current_binding="authority path must fail-closed; CovarianceEstimator raises on insufficient/non-finite data",
        owner="S2_contract + src.risk.covariance",
        reuse_candidate="src.risk.covariance.CovarianceEstimator",
        later_requirement="S3 must not promote dropna-silent helper paths",
    ),
    _row(
        "component_stale_data_behavior",
        family="A_COMPONENT_RISK",
        status=_CB,
        current_binding="RiskGate STALE_DATA + Cap2.3 stale/unknown fail-closed for the single selected future",
        owner="src.ops.gates.risk_gate + ops.single_selected_future_policy_v1",
        reuse_candidate="src.ops.gates.risk_gate.RiskDenyReason.STALE_DATA",
        later_requirement="MF stale matrix is S3",
    ),
    _row(
        "portfolio_aggregate_exposure",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="N=1 implies aggregate==component; helpers compute gross/net as non-authority analytics",
        owner="canonical_risk_chain",
        reuse_candidate="src.risk.portfolio.compute_gross_exposure",
        later_requirement="derived aggregator at S3; not a second writer",
    ),
    _row(
        "portfolio_gross_exposure",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="helper exists; not productive authority; MF gross limit unratified",
        owner="canonical_risk_chain",
        reuse_candidate="src.risk.portfolio.compute_gross_exposure",
        later_requirement="NUMERIC_POLICY_STATUS=DEFERRED_UNRATIFIED",
    ),
    _row(
        "portfolio_net_exposure",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="helper exists; relevant for later MF; currently N=1; limit unratified",
        owner="canonical_risk_chain",
        reuse_candidate="src.risk.portfolio.compute_net_exposure",
        later_requirement="NUMERIC_POLICY_STATUS=DEFERRED_UNRATIFIED",
    ),
    _row(
        "portfolio_var",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="src/risk/portfolio_var.py and var.py are research/supporting; I85 identity G13-gated; not live authority",
        owner="I85_contract_identity_not_engine",
        reuse_candidate="src.risk.portfolio_var; src.risk.var",
        later_requirement="S3 consume behind flags; S4 evidence; S5 numeric+GO",
    ),
    _row(
        "portfolio_component_marginal_var",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="src/risk/component_var.py Euler allocation helper; not authority; CompVaR != CVaR",
        owner="I85_contract_identity_not_engine",
        reuse_candidate="src.risk.component_var.ComponentVaRCalculator",
        later_requirement="S3 may reuse; must not create parallel owner",
    ),
    _row(
        "portfolio_cvar_expected_shortfall",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="historical/parametric CVaR helpers in src/risk/var.py; I37 library; not authority",
        owner="I37_method_library",
        reuse_candidate="src.risk.var.historical_cvar; parametric_cvar",
        later_requirement="S3 consume; numerics deferred",
    ),
    _row(
        "portfolio_concentration_limits",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="N=1 implies 100% concentration; MF concentration % unratified",
        owner="PHASE1_MAX_OPEN_POSITIONS=1",
        reuse_candidate="src.risk.enforcement.RiskLimitsV2.max_position_weight",
        later_requirement="NUMERIC_POLICY_STATUS=DEFERRED_UNRATIFIED",
    ),
    _row(
        "portfolio_loss_budget",
        family="B_PORTFOLIO_RISK",
        status=_CB,
        current_binding="single-future daily/trade loss envelopes in capital_risk_sizing_v1; MF portfolio budget unratified",
        owner="src.governance.capital_risk_sizing_v1",
        reuse_candidate="src.governance.capital_risk_sizing_v1",
        later_requirement="NUMERIC_POLICY_STATUS=DEFERRED_UNRATIFIED",
    ),
    _row(
        "correlation_estimation_semantics",
        family="C_DEPENDENCE",
        status=_CB,
        current_binding="Pearson helper + CovarianceEstimator exist; not current authority because N=1 has no concurrent set",
        owner="S2_contract",
        reuse_candidate="src.risk.covariance; src.risk.portfolio.correlation_matrix",
        later_requirement="S3 must bind fail-closed estimator, not RiskEnforcer NaN-skip",
    ),
    _row(
        "correlation_insufficient_history",
        family="C_DEPENDENCE",
        status=_CP,
        current_binding="authority contract=fail-closed; CovarianceEstimator raises when rows < min_history",
        owner="S2_contract + src.risk.covariance",
        reuse_candidate="src.risk.covariance.CovarianceEstimator",
        later_requirement="must remain fail-closed at S3",
    ),
    _row(
        "correlation_unstable_nan",
        family="C_DEPENDENCE",
        status=_CP,
        current_binding="authority contract=fail-closed on NaN/unstable corr; RiskEnforcer NaN-skip is helper-not-authority",
        owner="S2_contract",
        reuse_candidate="src.risk.covariance validate path, not enforcement skip",
        later_requirement="do not promote RiskEnforcer._check_correlations NaN continue",
    ),
    _row(
        "correlation_fallback_behavior",
        family="C_DEPENDENCE",
        status=_CP,
        current_binding="no optimistic fallback authorized; equal-weight mean fallback in RiskEnforcer is forbidden as authority",
        owner="S2_contract",
        reuse_candidate="none_as_authority",
        later_requirement="S3 fail-closed; no silent equal-weight or identity-corr",
    ),
    _row(
        "correlation_zero_corr_prohibition",
        family="C_DEPENDENCE",
        status=_CP,
        current_binding="optimistic zero-correlation fallback forbidden unless separately proven; not proven",
        owner="S2_contract",
        reuse_candidate="none",
        later_requirement="remains forbidden through S5 unless explicit Owner proof",
    ),
    _row(
        "capital_envelope_ownership",
        family="D_CAPITAL_ALLOCATION",
        status=_CP,
        current_binding="ScopeCapitalEnvelope lives in capital_risk_sizing_v1; src/portfolio weights are not envelope owner",
        owner="src.governance.capital_risk_sizing_v1",
        reuse_candidate="src.governance.capital_risk_sizing_v1",
        later_requirement="MF envelopes remain same owner; no second capital writer",
    ),
    _row(
        "risk_budget_ownership",
        family="D_CAPITAL_ALLOCATION",
        status=_CP,
        current_binding="pre/post sizing risk assessment in capital_risk_sizing_v1; I37/I74/I85 are not budget owners",
        owner="src.governance.capital_risk_sizing_v1",
        reuse_candidate="src.governance.capital_risk_sizing_v1",
        later_requirement="I85 may feed metrics; must not own budget",
    ),
    _row(
        "portfolio_weights_vs_trading_authority",
        family="D_CAPITAL_ALLOCATION",
        status=_CB,
        current_binding="src/portfolio equal_weight/vol_target/fixed_weights are backtest/research; no trading grant",
        owner="S2_contract",
        reuse_candidate="src.portfolio as RESEARCH_ONLY",
        later_requirement="must not become MF allocation authority at S3",
    ),
    _row(
        "active_set_input_boundary",
        family="D_CAPITAL_ALLOCATION",
        status=_CP,
        current_binding="Cap2.3 N=1; TOP_N_ACTIVE_SET_AUTHORITY=false; ranking is candidate context only",
        owner="ops.single_selected_future_policy_v1",
        reuse_candidate="ops.productive_futures_ranking_producer_v1",
        later_requirement="S3 consumes S1 policy; N>1 unratified",
    ),
    _row(
        "no_allocation_order_bypass",
        family="D_CAPITAL_ALLOCATION",
        status=_CP,
        current_binding="allocation helpers cannot submit; intent remains after risk/safety; orders unauthorized",
        owner="Master §1 chain + Cap7.2",
        reuse_candidate="none",
        later_requirement="preserve at S3",
    ),
    _row(
        "safety_global_kill_interaction",
        family="E_SAFETY",
        status=_CB,
        current_binding="I29 canonical kill; RiskGate KILL_SWITCH; global kill applies to the single instrument; MF extra interactions later",
        owner="I29 + src.ops.gates.risk_gate",
        reuse_candidate="src.ops.gates.risk_gate; src.risk_layer.kill_switch",
        later_requirement="R7 live kill proof; MF kill matrix S5",
    ),
    _row(
        "safety_per_instrument_kill_interaction",
        family="E_SAFETY",
        status=_NRS,
        current_binding="N=1 makes per-instrument kill identical to global kill; no concurrent second instrument",
        owner="I29",
        reuse_candidate="src.ops.gates.risk_gate",
        later_requirement="per_instrument_kill is S3/S5 contract detail",
    ),
    _row(
        "safety_auto_liquidation_i12",
        family="E_SAFETY",
        status=_CB,
        current_binding="I12 not implemented; must not create a second execution writer; auto-liq is R7 after R6",
        owner="I12_CANONICAL_NOT_IMPLEMENTED",
        reuse_candidate="none_as_authority",
        later_requirement="R7; LIVE_WRITE_FOR_AUTO_LIQ_KILL; blocked by live proof",
    ),
    _row(
        "safety_max_position_invariant",
        family="E_SAFETY",
        status=_CP,
        current_binding="MAX_POSITIONS_EFFECTIVE=1 across Cap2.2/2.3/2.4/1.1/7.2; G13 barrier",
        owner="Cap2.3/2.4/1.1/7.2",
        reuse_candidate="existing constants",
        later_requirement="must remain 1 until S5 GO",
    ),
    _row(
        "safety_fail_closed_inconsistent_aggregate",
        family="E_SAFETY",
        status=_CP,
        current_binding="N=1 has no inconsistent multi-instrument aggregate; authority contract=fail-closed if aggregate diverges",
        owner="S2_contract",
        reuse_candidate="Cap1.1 recon",
        later_requirement="S3 derived aggregator must fail-closed on mismatch",
    ),
    _row(
        "accounting_one_global_writer",
        family="F_ACCOUNTING_RECON",
        status=_CP,
        current_binding="productive_futures_accounting_portfolio_writer_v1 is the accounting writer",
        owner="ops.productive_futures_accounting_runtime_binding_v1",
        reuse_candidate="Cap3.1",
        later_requirement="must preserve single writer at S3",
    ),
    _row(
        "accounting_per_instrument_state_isolation",
        family="F_ACCOUNTING_RECON",
        status=_CB,
        current_binding="single selected future runtime context; no second instrument state writer",
        owner="ops.single_selected_future_runtime_binding_v1",
        reuse_candidate="Cap2.4",
        later_requirement="per-instrument context graph is S3",
    ),
    _row(
        "accounting_portfolio_aggregation_derived",
        family="F_ACCOUNTING_RECON",
        status=_CP,
        current_binding="portfolio aggregation is derived unless explicitly authoritative; currently derived; not a writer",
        owner="S2_contract",
        reuse_candidate="src.risk.portfolio analytics only",
        later_requirement="S3 derived aggregator; no second accounting writer",
    ),
    _row(
        "accounting_restart_reconstruction",
        family="F_ACCOUNTING_RECON",
        status=_CB,
        current_binding="Cap6.4/Cap1.1/Cap2.3 restart-safe for single-future no-order scope",
        owner="Cap6.4 + Cap1.1",
        reuse_candidate="ops.full_decision_path_atomic_restart_closure_v1",
        later_requirement="MF restart matrix is S3",
    ),
    _row(
        "accounting_duplicate_missing_position",
        family="F_ACCOUNTING_RECON",
        status=_CB,
        current_binding="Cap1.1 productive recon; max open=1; duplicate/missing fail-closed in single-future scope",
        owner="ops.productive_reconciliation_runtime_binding_v1",
        reuse_candidate="Cap1.1",
        later_requirement="MF recon is S3/S4",
    ),
    _row(
        "evidence_required_inputs",
        family="G_EVIDENCE",
        status=_CP,
        current_binding="this overlay + Cap2.2/2.3/2.4/3.1/1.1/7.2 + capital_risk_sizing_v1 + I37/I74/I85 surfaces",
        owner="ops.canonical_r6_s2_portfolio_risk_contracts_v1",
        reuse_candidate="existing owners",
        later_requirement="S3/S4/S5 consume this contract identity",
    ),
    _row(
        "evidence_deterministic_output",
        family="G_EVIDENCE",
        status=_CP,
        current_binding="canonical JSON config digest + machine-checkable dimension/intent rows",
        owner="ops.canonical_r6_s2_portfolio_risk_contracts_v1",
        reuse_candidate="lineage_v1.digest_mapping",
        later_requirement="S4 MF sim/shadow evidence pack later",
    ),
    _row(
        "evidence_identity_lineage",
        family="G_EVIDENCE",
        status=_CP,
        current_binding="Package-N join remains CLOSED_PROVEN; no MF identity plane; this overlay is contract identity only",
        owner="EG-I82-JOIN + this overlay",
        reuse_candidate="S1 evidence identity binding",
        later_requirement="MF session identity is S4/S5",
    ),
    _row(
        "evidence_verifier_expectations",
        family="G_EVIDENCE",
        status=_CP,
        current_binding="fail-closed verifier rejects AUTHORIZED/IMPLEMENTED/LIVE_PROOF/N!=1/numeric ratification/canary",
        owner="ops.canonical_r6_s2_portfolio_risk_contracts_v1.verifier_v1",
        reuse_candidate="S1 verifier pattern",
        later_requirement="S3 must not treat this overlay as runtime grant",
    ),
    _row(
        "evidence_needed_before_s3_s4_s5",
        family="G_EVIDENCE",
        status=_CP,
        current_binding="S3 needs this contract + separate Owner-GO; S4 needs MF sim/shadow pack; S5 needs live proof + GO",
        owner="UQ5 staged path",
        reuse_candidate="none",
        later_requirement="do not auto-progress",
    ),
)


def require_item(item_id: str) -> ContractDimensionRowV1:
    for row in S2_DIMENSIONS:
        if row.item_id == item_id:
            return row
    raise R6S2PortfolioRiskError(f"unknown_s2_item:{item_id}")
