"""Bound constants for the derived-only adjudication contract.

Infrastructure only. Does not bind occurrences, adjudicate parentage,
currentness, supersession, or winners. Does not close residuals.
Does not authorize PROVEN_OCCURRENCE_IDENTITY under the current OWNER_GO.
"""

from __future__ import annotations

from scripts.ops.forensic_structure_schema_v1.alignment_constants import (
    ALIGNMENT_LAYER_ID,
    BOUND_SIDECAR_SHA256,
    BOUND_SOURCE_SHA256,
    EXPECTED_ENDPOINT_RECORD_COUNT,
    NON_IDENTITY_STATEMENTS,
    OPEN_CLUSTER_RESIDUAL_IDS,
    REPO_ALIGNMENT_RELPATH,
)
from scripts.ops.forensic_structure_schema_v1.constants import OVERLAY_CLASS_ORDER
from scripts.ops.forensic_structure_schema_v1.disposition_constants import (
    MUST_REMAIN_OPEN_RESIDUAL_IDS,
    SECTION_22_SIDECAR_ENDPOINT,
    SIDECAR_DEPENDENCY_SUBJECT,
)

ADJUDICATION_LAYER_ID = "FORENSIC_STRUCTURE_SCHEMA_V1_ADJUDICATION_CONTRACT_V1"
ADJUDICATION_CONTRACT_VERSION = "1.0.0"
ADJUDICATION_TRANSFORMATION_VERSION = "1.0.0"
ADJUDICATION_GENERATOR_ID = "FORENSIC_STRUCTURE_SCHEMA_V1_ADJUDICATION_CONTRACT_GENERATOR_1.0.0"
ADJUDICATION_OUTPUT_ROLE = "DERIVED_NAVIGATION_OR_ANALYSIS_ONLY"
ADJUDICATION_AUTHORITY = "NONE"
REPO_ADJUDICATION_RELPATH = (
    "forensics/derived/FORENSIC_STRUCTURE_SCHEMA_V1_ADJUDICATION_CONTRACT_V1"
)

OPERATOR_AUTHORIZATION_SCOPE = (
    "FORENSIC_STRUCTURE_SCHEMA_V1_ADJUDICATION_CONTRACT_V1_DERIVED_ONLY"
    "_IMPLEMENT_VALIDATE_PERSIST_AND_PR_MAXIMUM_LEVERAGE"
)

EXPECTED_CANDIDATE_SHARD_SHA256 = "9eaded3909af1c5e89148b93650b08448a5b51eda359d2c51b8ea86f798c075e"
EXPECTED_T4_SHARD_SHA256 = "53773007b39c3997ce55eae312e54e3fece80dbe9cb594316a7dbab3e3134ec1"
ALIGNMENT_INPUT_LAYER_ID = ALIGNMENT_LAYER_ID
ALIGNMENT_INPUT_RELPATH = REPO_ALIGNMENT_RELPATH

EXPECTED_CANDIDATE_COUNT = EXPECTED_ENDPOINT_RECORD_COUNT
EXPECTED_CANDIDATE_FAMILY_COUNT = 11
EXPECTED_COMPETING_SET_COUNT = 8
EXPECTED_COMPETING_MEMBER_COUNT = 18
EXPECTED_ORIGINAL_AMBIGUOUS_BINDING_COUNT = 6
EXPECTED_REFERENCED_OVERLAY_CLASS_FAMILY_COUNT = len(OVERLAY_CLASS_ORDER)
EXPECTED_PROVEN_OCCURRENCE_IDENTITY_COUNT = 0
EXPECTED_PROVEN_PARENTAGE_COUNT = 0
EXPECTED_WINNER_SELECTED_COUNT = 0

CANDIDATE_FAMILIES = (
    "T3_SRC_ALIAS",
    "T4_REL_ALIAS",
    "OVERLAY_WRAPPER_PAIR",
    "OVERLAY_APPEND_EPOCH_REUSED",
    "OVERLAY_APPEND_EPOCH_UNIQUE",
    "LAYER1_OCCURRENCE",
    "DOC_Z2AR",
    "DOC_Z2AP",
    "DOC_SECTION_22",
    "DOC_Z2AR_SUI_POSITION_VALUE_ALGEBRA_RECORD",
    "DOC_EXPLICIT_DEPENDENCY_COUNTERPARTY",
)

DOC_DEPENDENCY_COUNTERPARTY_STRINGS = frozenset(
    {
        "Z2AR_SUI_PUBLIC_EVIDENCE_PACK_PERSISTED",
        "SUI_INSTID_EXISTS",
        "LINEAR_FORMULA_SHAPE_Z2S_Z2T",
        "Z2AS_P3_UNRANKED_CLASS_POLICY",
    }
)

KNOWN_COMPETING_ENDPOINT_STRINGS = (
    SIDECAR_DEPENDENCY_SUBJECT,
    "Z2AP",
    "Z2AR",
    SECTION_22_SIDECAR_ENDPOINT,
    "append_epoch-405fcb00e65a771b8292f17a1310499e",
    "append_epoch-960ae2792d8eb755942e63e16a78ada1",
    "append_epoch-cf0b6e987ba84af5d14b810882453867",
    "append_epoch-f887599833b745d07ba58727a58aa929",
)

COMPETING_SET_KIND = {
    SIDECAR_DEPENDENCY_SUBJECT: "SIDECAR_CONSTRUCTED_STRING_REUSE",
    "Z2AP": "CONFLICT_TRIANGLE_DOCUMENTARY",
    "Z2AR": "CONFLICT_TRIANGLE_DOCUMENTARY",
    SECTION_22_SIDECAR_ENDPOINT: "CONFLICT_TRIANGLE_SIDECAR_CONSTRUCTED",
    "append_epoch-405fcb00e65a771b8292f17a1310499e": "OVERLAY_STRING_REUSE",
    "append_epoch-960ae2792d8eb755942e63e16a78ada1": "OVERLAY_STRING_REUSE",
    "append_epoch-cf0b6e987ba84af5d14b810882453867": "OVERLAY_STRING_REUSE",
    "append_epoch-f887599833b745d07ba58727a58aa929": "OVERLAY_STRING_REUSE",
}

ADJUDICATION_DIMENSIONS = (
    "OCCURRENCE_IDENTITY",
    "EXACT_TEXTUAL_IDENTITY",
    "PROVENANCE_IDENTITY",
    "SOURCE_TO_DERIVED_PROJECTION",
    "SEMANTIC_EQUIVALENCE",
    "PARENTAGE",
    "DEPENDENCY",
    "CHRONOLOGY",
    "CURRENTNESS",
    "SUPERSESSION",
    "CONTRADICTION",
    "DUPLICATION",
    "NAVIGATION_LINKAGE",
    "WINNER_SELECTION",
    "AUTHORITY",
)

EXECUTED_CLASSIFY_DISQUALIFY_DIMENSIONS = ("OCCURRENCE_IDENTITY",)
UNEXECUTED_DIMENSIONS = tuple(
    dim for dim in ADJUDICATION_DIMENSIONS if dim not in EXECUTED_CLASSIFY_DISQUALIFY_DIMENSIONS
)

ADJUDICATION_OUTCOMES = (
    "UNADJUDICATED",
    "INSUFFICIENT_EVIDENCE",
    "NOT_BINDABLE_AS_OCCURRENCE",
    "AMBIGUOUS_COMPETING",
    "CONFLICTED",
    "DUPLICATE_CANDIDATE_RECORD",
    "NAVIGATION_LINK_ONLY",
    "DISQUALIFIED_BY_NON_IDENTITY",
    "PROVEN_OCCURRENCE_IDENTITY",
)

FORBIDDEN_NAKED_OUTCOMES = ("PROVEN", "OPEN", "CLOSED")

REASON_CODES = (
    "NI_APPLIES",
    "LOCUS_ABSENT",
    "LOCUS_INCOMPLETE",
    "SIDECAR_CONSTRUCTED",
    "NAVIGATION_ONLY",
    "CLASS_CROSSING",
    "COMPETING_SET",
    "AMBIGUOUS_BINDING",
    "DISPOSITION_DO_NOT_BIND",
    "INSUFFICIENT_POSITIVE_EVIDENCE",
    "MARKER_REFERENCE_ONLY",
    "CORPUS_SHA_NOT_OCCURRENCE_PROOF",
    "ALIAS_NOT_OCCURRENCE",
    "OVERLAY_NOT_OCCURRENCE",
    "MECHANICAL_ORDER_NOT_DEPENDENCY",
    "EPOCH_NOT_CURRENTNESS",
    "EPOCH_NOT_SUPERSESSION",
    "LATER_NOT_WINNER",
    "PARENT_HINT_NOT_PARENTAGE",
    "RESIDUAL_STATUS_NOT_ADJUDICATION_OUTCOME",
    "DIMENSION_NOT_AUTHORIZED",
    "STRING_REUSE_NOT_DUPLICATE_RECORD",
    "STRING_REUSE_NOT_OCCURRENCE_IDENTITY",
)

POLARITY_POSITIVE = "POSITIVE"
POLARITY_NEGATIVE = "NEGATIVE"
LOCUS_PRESENT = "PRESENT"
LOCUS_ABSENT = "ABSENT"

EVIDENCE_EPISTEMIC_CLASSES = (
    "FACT_FROM_SOURCE",
    "STRUCTURAL_DERIVATION",
    "PRIOR_ADJUDICATION_REFERENCE",
    "NAVIGATION_ONLY",
    "UNKNOWN",
)

NON_IDENTITY_IDS = tuple(row[0] for row in NON_IDENTITY_STATEMENTS)
NON_IDENTITY_BY_ID = {row[0]: row for row in NON_IDENTITY_STATEMENTS}

DISPOSITION_DISQUALIFIERS = (
    "DR-002",
    "DR-003",
    "INVENTED_OR_SIDECAR_CONSTRUCTED_STRING",
    "LAYER1_MARKER_REFERENCE_ONLY",
    "AMBIGUOUS_BINDING",
    "NAVIGATION_ONLY",
    "DO_NOT_BIND",
)

EXECUTION_BOUNDARIES = (
    "A_CANDIDATE_ADJUDICATION",
    "B_PROVEN_OCCURRENCE_PERSISTENCE",
    "C_PARENTAGE",
    "D_CURRENTNESS",
    "E_SUPERSESSION",
    "F_WINNER_SELECTION",
    "G_RESIDUAL_CLOSURE",
    "H_CANONICALIZATION",
)

ADJUDICATION_SHARD_ORDER = (
    "dimension_model.json",
    "evidence_index.json",
    "competing_set_graph.json",
    "candidate_adjudication_results.json",
    "adjudication_decision_records.json",
    "non_inference_audit.json",
    "execution_boundaries.json",
)

GIT_TRACKED_SHARDS = ADJUDICATION_SHARD_ORDER

ADJUDICATION_MUST_REMAIN_OPEN = MUST_REMAIN_OPEN_RESIDUAL_IDS
ADJUDICATION_OPEN_CLUSTER = OPEN_CLUSTER_RESIDUAL_IDS

ADJUDICATION_GUARD_NAMES = (
    "forbid_proven_occurrence_identity",
    "forbid_parentage_adjudication",
    "forbid_currentness_adjudication",
    "forbid_supersession_adjudication",
    "forbid_winner_selection",
    "forbid_residual_close",
    "forbid_authority_promotion",
    "forbid_canonical_output",
    "forbid_bind_from_alias_only",
    "forbid_bind_from_sha_only",
    "forbid_bind_from_string_equality_only",
    "forbid_bind_from_adjacency",
    "forbid_dependency_from_mechanical_order",
    "forbid_currentness_from_epoch",
    "forbid_supersession_from_epoch",
    "forbid_winner_from_later_record",
    "forbid_parentage_from_view_hint",
    "forbid_authority_from_structure",
    "forbid_residual_close_from_adjudication",
    "forbid_source_mutation",
    "forbid_sidecar_mutation",
    "forbid_silent_ambiguous_normalization",
)
