"""Additive SW-R-002/004/009 binding-disposition vocabulary.

Derived / non-authoritative only. Does not close residuals or bind occurrences.
"""

from __future__ import annotations

from scripts.ops.forensic_structure_schema_v1.constants import (
    EXPECTED_SIDECAR_SHA256,
    EXPECTED_SOURCE_SHA256,
)

DISPOSITION_LAYER_ID = "FORENSIC_STRUCTURE_SCHEMA_V1_BINDING_DISPOSITION_V1"
DISPOSITION_TRANSFORMATION_VERSION = "1.0.0"
DISPOSITION_GENERATOR_ID = "FORENSIC_STRUCTURE_SCHEMA_V1_BINDING_DISPOSITION_GENERATOR_1.0.0"
DISPOSITION_OUTPUT_ROLE = "DERIVED_NAVIGATION_OR_ANALYSIS_ONLY"
DISPOSITION_AUTHORITY = "NONE"
REPO_DISPOSITION_RELPATH = "forensics/derived/FORENSIC_STRUCTURE_SCHEMA_V1_BINDING_DISPOSITION_V1"

EXPECTED_ORIENTATION = {
    "LAYER3_RELATION_COUNT": 122,
    "STRUCTURAL_ORDERED_BEFORE_COUNT": 87,
    "WRAPPER_CONTAINS_COUNT": 23,
    "PREFIX_EPOCH_SUCCEEDS_COUNT": 5,
    "EXPLICIT_DEPENDENCY_COUNT": 4,
    "EXPLICIT_CONFLICT_COUNT": 3,
    "T4_LINE_COUNT": 7175,
    "VIEW_COUNT": 12,
    "VIEW_PARENT_PRESENT_COUNT": 1,
    "VIEW_PARENT_ABSENT_COUNT": 11,
    "WINNER_SELECTED_COUNT": 0,
}

RELATION_DISPOSITION_RECORD_COUNT = 122
ENDPOINT_DISPOSITION_RECORD_COUNT = 244
VIEW_PARENT_DISPOSITION_RECORD_COUNT = 12

RELATION_DISPOSITION_CATEGORIES = (
    "MECHANICAL_STRUCTURAL_RELATION_ONLY",
    "DOCUMENTARY_RELATION_ONLY",
    "EXPLICIT_TEXT_RECORD",
    "NOT_A_SEMANTIC_GRAPH_EDGE",
    "SEMANTIC_STATUS_UNKNOWN",
)

ENDPOINT_DISPOSITION_CATEGORIES = (
    "DO_NOT_BIND",
    "NAVIGATION_ALIAS_ONLY",
    "OVERLAY_REFERENCE_ONLY",
    "LAYER1_MARKER_REFERENCE_ONLY",
    "DOCUMENTARY_STRING_ONLY",
    "AMBIGUOUS_BINDING",
    "UNBOUND_NO_SUPPORTED_BINDING",
    "UNAMBIGUOUS_BINDING_CANDIDATE_NOT_AUTHORIZED",
    "INVENTED_OR_SIDECAR_CONSTRUCTED_STRING",
    "OCCURRENCE_BINDING_PROVEN",
)

VIEW_PARENT_DISPOSITION_CATEGORIES = (
    "DOCUMENTARY_PARENT_HINT",
    "NOT_ADJUDICATED_PARENTAGE",
    "ABSENT_UNINTERPRETED",
    "PROVEN_PARENTAGE",
)

ADJUDICATION_STATUSES = (
    "UNADJUDICATED",
    "BLOCKED_BY_RESIDUAL",
    "OPEN",
)

T4_DECLARED_TO_LAYER3_DERIVED_MAP = {
    "ORDERED_BEFORE": "STRUCTURAL_ORDERED_BEFORE",
}

# Derived TSV column indices observed on bound Source T4-A rows (field_count=17).
# These are derived representations, not a source-vocabulary claim.
DERIVED_T4_TSV_INDEX = {
    "relation_alias": 0,
    "t4_pass": 1,
    "subject_src": 2,
    "directionality": 5,
    "target_ref": 15,
    "notes": 16,
}

SECTION_22_PAIR_TOKEN = "SECTION_22"
SECTION_22_SIDECAR_ENDPOINT = "§22"
SIDECAR_DEPENDENCY_SUBJECT = "Z2AR_SUI_POSITION_VALUE_ALGEBRA_RECORD"

VIEW_UNRESOLVED_BOUNDARIES_ID = "view_unresolved_boundaries"
DOCUMENTARY_PARENT_HINT_PAIRS = (
    ("U16612", "SRC-000048"),
    ("U25510", "SRC-000082"),
    ("U29481", "SRC-000087"),
)

ABSENT_PARENT_FORBIDDEN_KEYS = (
    "parent_count",
    "has_parent",
    "root",
    "no_parent",
    "childless",
    "NO_PARENT",
    "ROOT",
    "CHILDLESS",
)

FORBIDDEN_EPOCH_PROMOTION_TOKENS = (
    "CURRENT",
    "SUPERSEDED",
    "WINNER",
    "CANONICAL_SUCCESSOR",
)

CROSS_RESIDUAL_PREREQUISITES = {
    "SW-R-002": ("SW-R-004", "DR-002"),
    "SW-R-004": ("SW-R-008", "DR-003", "SW-R-002"),
    "SW-R-009": ("SW-R-005", "SW-R-015", "DR-003", "DR-006"),
}

CLUSTER_RESIDUAL_IDS = ("SW-R-002", "SW-R-004", "SW-R-009")
MUST_REMAIN_OPEN_RESIDUAL_IDS = (
    "SW-R-002",
    "SW-R-004",
    "SW-R-005",
    "SW-R-008",
    "SW-R-009",
    "SW-R-015",
    "DR-002",
    "DR-003",
    "DR-006",
)

BOUND_SOURCE_SHA256 = EXPECTED_SOURCE_SHA256
BOUND_SIDECAR_SHA256 = EXPECTED_SIDECAR_SHA256

DEAD_UNWIRED_GUARD_BASELINE = (
    "forbid_epoch_succession_currentness",
    "forbid_alias_occurrence_bind",
    "forbid_documentary_string_auto_resolution",
    "forbid_view_parents_parentage",
)

GUARD_GAP_IDS = ("G1", "G2", "G3", "G4", "G5", "G6")
