"""Constants for §11.12.8 productive Testnet campaign EXECUTION (implementation only).

Layers (must not be conflated):
  FIXTURE_PROOF = Cap 11 §11.12.8 fixture-only residual
  PRODUCTIVE_TESTNET_PATH = Cap 11 §11.12.8 path package (gates; no run)
  PRODUCTIVE_TESTNET_EXECUTION = this package (executor present; no run)
  PRODUCTIVE_TESTNET_RUN = later separate Owner-GO campaign run (out of scope)
"""

from __future__ import annotations

from src.ops.capability_11_section_11_12_8_productive_testnet_campaign_path_v1.constants_v1 import (
    CANONICAL_ALLOWED_ORDER_TYPES as PATH_ALLOWED_ORDER_TYPES,
    CANONICAL_EMERGENCY_COMMANDS as PATH_EMERGENCY_COMMANDS,
    CANONICAL_INSTRUMENT_SCOPE as PATH_INSTRUMENT_SCOPE,
    CANONICAL_POSITION_COUNT_LIMIT as PATH_POSITION_COUNT_LIMIT,
    CANONICAL_RUNTIME_MODE as PATH_RUNTIME_MODE,
    CANONICAL_VENUE as PATH_VENUE,
    CAPABILITY_ID as PATH_CAPABILITY_ID,
    FORBIDDEN_CONFIRM_TOKEN_ARGV_FLAGS as PATH_FORBIDDEN_CONFIRM_ARGV,
    FORBIDDEN_CONFIRM_TOKEN_ENV_KEYS as PATH_FORBIDDEN_CONFIRM_ENV,
    OWNER as PATH_OWNER,
)

CAPABILITY_ID = "CAPABILITY_11_SECTION_11_12_8_PRODUCTIVE_TESTNET_CAMPAIGN_EXECUTION_V1"
PACKAGE_MARKER = "CAPABILITY_11_SECTION_11_12_8_PRODUCTIVE_TESTNET_CAMPAIGN_EXECUTION_V1=true"
OWNER = "ops.capability_11_section_11_12_8_productive_testnet_campaign_execution_v1"
CONTRACT_VERSION = "v1"

PREDECESSOR_CAPABILITY_ID = PATH_CAPABILITY_ID
PREDECESSOR_OWNER = PATH_OWNER
NEXT_CONSUMER_CAPABILITY_ID = "SEPARATE_OWNER_GO_REQUIRED_FOR_PRODUCTIVE_TESTNET_CAMPAIGN_RUN"

CORE_LOGIC_CHANGE = False
ACTIVATION_STATE = "not_activated"
RUNTIME_ACTIVATED = False
REFERENCE_ONLY = False

# Layer claims.
PATH_PREDECESSOR_PRESERVED = True
PRODUCTIVE_TESTNET_CAMPAIGN_EXECUTION_IMPLEMENTED = True
PRODUCTIVE_TESTNET_CAMPAIGN_EXECUTION_PATH_PRESENT = True
PRODUCTIVE_TESTNET_CAMPAIGN_EXECUTION_PATH_ABSENT = False

# Permanent fail-closed — this OWNER_GO is IMPLEMENTATION_ONLY / RUN_AUTHORIZED=false.
RUN_AUTHORIZED = False
PRODUCTIVE_TESTNET_CAMPAIGN_STARTED = False
PRODUCTIVE_TESTNET_CAMPAIGN_COMPLETED = False
PRODUCTIVE_TESTNET_CAMPAIGN_ACTIVATED = False
NETWORK_SESSION_STARTED = False
AUTHORIZATION_CONSUMPTION_ALLOWED = False
AUTHORIZATION_CONSUMED = False
CONFIRM_TOKEN_ISSUANCE_ALLOWED = False
CONFIRM_TOKEN_CONSUMPTION_ALLOWED = False
ORDER_SEND_DISABLED = True
ORDERS_AUTHORIZED = False
ORDER_PATH_STARTED = False
ORDER_SUBMIT_PERFORMED = False
MUTATING_EXCHANGE_CALLS = False
NETWORK_WRITES_AUTHORIZED = False
NETWORK_WRITE_PERFORMED = False
NETWORK_EFFECT = "NONE"
ORDER_EFFECT = "NONE"
LIVE_ORDER_EFFECT = "NONE"
EXCHANGE_ORDER_SUBMIT_REACHABLE = False
TESTNET_ORDER_SUBMIT_PERFORMED = False
TESTNET_EXECUTION_REACHABLE = False
LIVE_EXECUTION_REACHABLE = False
REAL_EXECUTION_ADAPTER_CONSTRUCTED = False
LIVE_AUTHORIZED = False
TESTNET_AUTHORIZED = False
CAPABILITY_11_13_STARTED = False
SECTION_11_13_STARTED = False
KILL_SWITCH_CONTRACT_ACTIVATED = False
CAMPAIGN_SIDE_EFFECTS_AUTHORIZED = False

MODE_PROVE_EXECUTION_ONLY = "PROVE_EXECUTION_ONLY"
MODE_GOVERNED_EXECUTION_GATE = "GOVERNED_CAMPAIGN_EXECUTION_GATE"
PATH_CLASS = "PRODUCTIVE_TESTNET_CAMPAIGN_EXECUTION"

CANONICAL_RUNTIME_MODE = PATH_RUNTIME_MODE
CANONICAL_VENUE = PATH_VENUE
CANONICAL_INSTRUMENT_SCOPE: tuple[str, ...] = PATH_INSTRUMENT_SCOPE
CANONICAL_ALLOWED_ORDER_TYPES: tuple[str, ...] = PATH_ALLOWED_ORDER_TYPES
CANONICAL_POSITION_COUNT_LIMIT = PATH_POSITION_COUNT_LIMIT
CANONICAL_EMERGENCY_COMMANDS: tuple[str, ...] = PATH_EMERGENCY_COMMANDS
FORBIDDEN_CONFIRM_TOKEN_ARGV_FLAGS = PATH_FORBIDDEN_CONFIRM_ARGV
FORBIDDEN_CONFIRM_TOKEN_ENV_KEYS = PATH_FORBIDDEN_CONFIRM_ENV

REQUIRED_PRECONDITIONS: tuple[str, ...] = (
    "path_predecessor_bound",
    "path_start_gate_admissible",
    "testnet_only_scope",
    "live_path_blocked",
    "credential_scope_testnet",
    "owner_authorization_bound",
    "confirm_token_digest_bound",
    "campaign_enabled",
    "campaign_armed",
    "kill_switch_operational",
    "emergency_control_operational",
    "risk_scope_within_authority",
    "run_authorized_ephemeral",
    "side_effects_unauthorized_permanent",
    "campaign_not_started",
    "cap_11_13_not_started",
    "network_effect_none",
    "order_effect_none",
)

EVIDENCE_DIRNAME = "capability_11_section_11_12_8_productive_testnet_campaign_execution_v1"
MANIFEST_FILENAME = "MANIFEST.sha256"
SUMMARY_FILENAME = "SUMMARY.json"
CLAIMS_FILENAME = "claims.json"
