"""Constants for Stage-2 Pure-Stack numeric policy shadow campaign runner v1.

SHADOW_ONLY=true
PRODUCTIVE_ACTIVATION=false
INPUT_AUTHORITY=false
RUNTIME_IMPLEMENTED=false
DASHBOARD_AUTHORITY_EFFECT=NONE
ORDERS=false
TESTNET=false
LIVE=false
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_PRODUCTIVE_PURE_STACK_NUMERIC_POLICY_SHADOW_CAMPAIGN_V1"
PACKAGE_MARKER = "PRODUCTIVE_PURE_STACK_NUMERIC_POLICY_SHADOW_CAMPAIGN_V1=true"
OWNER = "ops.productive_pure_stack_numeric_policy_shadow_campaign_v1"
SCHEMA_VERSION = "productive_pure_stack_numeric_policy_evidence_pack/v1"
PRODUCER_VERSION = "productive_pure_stack_numeric_policy_shadow_campaign/v1"

SOLE_TRADING_AUTHORITY = "run_integrated_offline_trading_logic_replay_v1"
DASHBOARD_ROLE = "READ_ONLY_CONSUMER"
DASHBOARD_AUTHORITY_EFFECT = "NONE"

PRODUCTIVE_ACTIVATION = False
INPUT_AUTHORITY = False
RUNTIME_IMPLEMENTED = False
OWNER_RATIFIED = False
PRODUCTIVE_NUMERIC_VALUES_SET = 0

RELATIVE_OUTPUT_ROOT = "evidence/ops/productive_pure_stack_numeric_policy_shadow_campaign_v1"
EVIDENCE_PACK_FILENAME = "evidence_pack.v1.json"
CAMPAIGN_RESULT_FILENAME = "campaign_result.v1.json"
REPRODUCIBILITY_FILENAME = "reproducibility.v1.json"
MANIFEST_FILENAME = "MANIFEST.sha256"

STAGE1_MANIFEST_REL = "docs/ops/PRODUCTIVE_PURE_STACK_OWNER_VALUES_STRUCTURAL_MANIFEST_V1.json"
CALIBRATION_PROTOCOL_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_NUMERIC_POLICY_CALIBRATION_PROTOCOL_V1.md"
)
EVIDENCE_REQUIREMENTS_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_NUMERIC_POLICY_EVIDENCE_REQUIREMENTS_V1.md"
)
CAMPAIGN_SCAFFOLD_REL = (
    "docs/ops/PRODUCTIVE_PURE_STACK_NUMERIC_POLICY_CALIBRATION_CAMPAIGN_MANIFEST_V1.json"
)

# Internal runner states (mapped to schema campaign_status on emit).
CAMPAIGN_STATE_DECLARED = "DECLARED"
CAMPAIGN_STATE_IN_PROGRESS = "IN_PROGRESS"
CAMPAIGN_STATE_COMPLETE = "COMPLETE"
CAMPAIGN_STATE_REJECTED = "REJECTED"

# Schema-compatible pack statuses.
PACK_STATUS_IN_PROGRESS = "IN_PROGRESS"
PACK_STATUS_EVIDENCE_COMPLETE_PENDING_OWNER = "EVIDENCE_COMPLETE_PENDING_OWNER"
PACK_STATUS_REJECTED_FAIL_CLOSED = "REJECTED_FAIL_CLOSED"

FORBIDDEN_OUTPUT_PATH_MARKERS: tuple[str, ...] = (
    "market_dashboard",
    "dashboard_archive",
    "workflow_archive",
    "runtime_archive",
    "durable_closeout",
    "webui/archives",
    "paper_shadow_archive",
    "active_archive",
)

FORBIDDEN_AUTHORITY_SOURCES: tuple[str, ...] = (
    "fixture",
    "scenario",
    "webui",
    "dashboard",
    "cmc.volatility_estimate",
    "cmc_volatility_estimate",
    "SurvivalResultV1",
    "SuitabilityResultV1",
    "archive_authority",
)

STAGE2_TOKENS: tuple[str, ...] = (
    "OWNER_VALUE_FUTURES_INPUT_FRESHNESS_MAX_AGE_SECONDS",
    "OWNER_VALUE_SURVIVAL_LIMIT_MIN_PATH_SURVIVAL_RATIO",
    "OWNER_VALUE_SURVIVAL_LIMIT_MAX_EARLY_LOSS_TOXICITY",
    "OWNER_VALUE_SURVIVAL_LIMIT_MIN_MARGIN_BUFFER_AT_RISK_99",
    "OWNER_VALUE_SURVIVAL_LIMIT_MAX_SEQUENCE_FRAGILITY_INDEX",
    "OWNER_VALUE_SURVIVAL_LIMIT_MAX_LIQUIDATION_NEAR_MISS_RATE",
    "OWNER_VALUE_SURVIVAL_LIMIT_MAX_GOVERNANCE_BREACH_FREQUENCY",
    "OWNER_VALUE_SURVIVAL_LIMIT_MIN_CHOP_SWITCH_SURVIVAL_SCORE",
    "OWNER_VALUE_SURVIVAL_LIMIT_MAX_EFFECTIVE_LEVERAGE",
    "OWNER_VALUE_SURVIVAL_LIMIT_MIN_LIQUIDATION_BUFFER",
    "OWNER_VALUE_SURVIVAL_LIMIT_MAX_ADVERSE_FILL_LOSS",
    "OWNER_VALUE_CAPITAL_SLOT_PROFIT_STEP_PCT",
    "OWNER_VALUE_CAPITAL_SLOT_CASHFLOW_LOCK_FRACTION",
    "OWNER_VALUE_CAPITAL_SLOT_MIN_REALIZED_VOLATILITY",
    "OWNER_VALUE_CAPITAL_SLOT_MIN_ATR_OR_RANGE",
    "OWNER_VALUE_CAPITAL_SLOT_MAX_TIME_WITHOUT_CASHFLOW_STEP",
    "OWNER_VALUE_CAPITAL_SLOT_MIN_OPPORTUNITY_SCORE",
    "OWNER_VALUE_CAPITAL_SLOT_INITIAL_SLOT_BASE",
)

MECHANICAL_COUPLING_TOKEN = "OWNER_VALUE_CAPITAL_SLOT_REINVEST_FRACTION"
MECHANICAL_COUPLING_RULE = "1 - OWNER_VALUE_CAPITAL_SLOT_CASHFLOW_LOCK_FRACTION"

OBSERVATION_IDENTITY: dict[str, object] = {
    "observation_family": "PUBLIC_MARKET_FINALIZED_BARS",
    "bar_interval": "PT1M",
    "point_in_time_only": True,
    "no_lookahead": True,
    "no_implicit_fill": True,
    "provenance_required": True,
    "sole_consumer_authority": SOLE_TRADING_AUTHORITY,
}

ALLOWED_PRODUCER_CLASSES: tuple[str, ...] = ("sole_trading_authority_shadow_calibration_producer",)

FORBIDDEN_PRODUCER_CLASSES: tuple[str, ...] = (
    "fixture_scenario_scalar",
    "webui_hardcoded_limit",
    "dashboard_presentation_projection",
    "cmc_volatility_estimate",
    "SurvivalResultV1",
    "SuitabilityResultV1",
    "archive_authority_mutation",
    "parallel_arithmetic_volatility_opportunity_kernel",
)

SHADOW_DATA_COLLECTION_GROUPS: dict[str, tuple[str, ...]] = {
    "SHADOW_GROUP_SEQUENCE_METRICS": (
        "OWNER_VALUE_SURVIVAL_LIMIT_MIN_PATH_SURVIVAL_RATIO",
        "OWNER_VALUE_SURVIVAL_LIMIT_MAX_EARLY_LOSS_TOXICITY",
        "OWNER_VALUE_SURVIVAL_LIMIT_MIN_MARGIN_BUFFER_AT_RISK_99",
        "OWNER_VALUE_SURVIVAL_LIMIT_MAX_SEQUENCE_FRAGILITY_INDEX",
        "OWNER_VALUE_SURVIVAL_LIMIT_MAX_LIQUIDATION_NEAR_MISS_RATE",
        "OWNER_VALUE_SURVIVAL_LIMIT_MAX_GOVERNANCE_BREACH_FREQUENCY",
        "OWNER_VALUE_SURVIVAL_LIMIT_MIN_CHOP_SWITCH_SURVIVAL_SCORE",
    ),
    "SHADOW_GROUP_LAYER_ARITHMETIC": (
        "OWNER_VALUE_SURVIVAL_LIMIT_MAX_EFFECTIVE_LEVERAGE",
        "OWNER_VALUE_SURVIVAL_LIMIT_MIN_LIQUIDATION_BUFFER",
        "OWNER_VALUE_SURVIVAL_LIMIT_MAX_ADVERSE_FILL_LOSS",
    ),
    "SHADOW_GROUP_CAPITAL_RELEASE_FEATURES": (
        "OWNER_VALUE_CAPITAL_SLOT_MIN_REALIZED_VOLATILITY",
        "OWNER_VALUE_CAPITAL_SLOT_MIN_ATR_OR_RANGE",
        "OWNER_VALUE_CAPITAL_SLOT_MIN_OPPORTUNITY_SCORE",
    ),
    "SHADOW_GROUP_CAPITAL_CASHFLOW_POLICY": (
        "OWNER_VALUE_CAPITAL_SLOT_PROFIT_STEP_PCT",
        "OWNER_VALUE_CAPITAL_SLOT_CASHFLOW_LOCK_FRACTION",
    ),
}

GROUP_AUTO_RATIFICATION_AUTHORIZED = False
LIVE_ORDERS = False
TESTNET_ORDERS = False
PAPER_EXCHANGE_ORDERS = False
EXCHANGE_CREDENTIAL_USE = False
REAL_CAPITAL_MOVEMENT = False
