"""P5.8B RegimeSideStateProjectionPhase authority (lifecycle persisted state; no CZ-4 wire)."""

from __future__ import annotations

PACKAGE_MARKER = "P5_8B_REGIME_SIDESTATE_PROJECTION_PHASE_AUTHORITY_CONTRACT_V1=true"
OWNER = "ops.p5_8b_regime_sidestate_projection_phase_authority_v1"
CONTRACT_VERSION = "regime_sidestate_projection_phase_authority.v1"
PHASE_AUTHORITY_VARIANT = "PERSISTED_STATE_REQUIRED"

LIFECYCLE_SCHEMA_NAME = "regime_sidestate_projection_lifecycle.v1"
LIFECYCLE_SCHEMA_VERSION = "v1"

PHASE_AUTHORITY_CONTRACT_V1_DEFINED = True

from src.ops.p5_2_productive_cycle_seam_invoke_and_authority_bind_v1.constants_v1 import (  # noqa: E402
    AUTHORITY_CUTOVER_OCCURRED,
    P5_AUTHORITY_CUTOVER_AUTHORIZED,
    PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED,
    REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED,
)

assert PHASE_AUTHORITY_CONTRACT_V1_DEFINED is True
assert PHASE_AUTHORITY_VARIANT == "PERSISTED_STATE_REQUIRED"
assert REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED is True
assert PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED is True
assert P5_AUTHORITY_CUTOVER_AUTHORIZED is False
assert AUTHORITY_CUTOVER_OCCURRED is False

__all__ = [
    "AUTHORITY_CUTOVER_OCCURRED",
    "CONTRACT_VERSION",
    "LIFECYCLE_SCHEMA_NAME",
    "LIFECYCLE_SCHEMA_VERSION",
    "OWNER",
    "P5_AUTHORITY_CUTOVER_AUTHORIZED",
    "PACKAGE_MARKER",
    "PHASE_AUTHORITY_CONTRACT_V1_DEFINED",
    "PHASE_AUTHORITY_VARIANT",
    "PRODUCTIVE_CYCLE_LAYERED_CORE_BIND_ENABLED",
    "REGIME_SIDESTATE_MAPPING_CONTRACT_AUTHORIZED",
]
