"""Constants for CAPABILITY_REGIME_BULL_BEAR_SWITCH_EVIDENCE_READMODEL_V1.

EVIDENCE_ONLY / NON_RESTART_AUTHORITY carrier.
Does not lift Cap 6.x Master-V2 / Double-Play restart persistence bans.
Canonical SideState restart owner remains MEMBER_DYNAMIC_SCOPE.
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_REGIME_BULL_BEAR_SWITCH_EVIDENCE_READMODEL_V1"
SCHEMA_NAME = "regime_bull_bear_switch_evidence_readmodel.v1"
SCHEMA_VERSION = 1
FAMILY_ID = "regime_bull_bear_switch"
PACKAGE_MARKER = "REGIME_BULL_BEAR_SWITCH_EVIDENCE_READMODEL_V1=true"
OWNER = "trading.master_v2.regime_bull_bear_switch_evidence_readmodel_v1"

EVIDENCE_CLASSIFICATION = "EVIDENCE_ONLY"
RESTART_AUTHORITY = False
TRADING_INPUT = False
DECISION_AUTHORITY = False
PRESENTATION_AUTHORITY = False
PARALLEL_PERSISTENCE_DOMAIN = False
CAPTURE_MODE = "IMMUTABLE_CAPTURE_OF_AUTHORIZED_RUNTIME_OUTPUT"

AUTHORITY_EFFECT = "NONE"
RUNTIME_EFFECT = "NONE"
ORDER_EFFECT = "NONE"

ARTIFACT_FILENAME = "regime_bull_bear_switch_evidence_readmodel.v1.json"

RUNTIME_CAPTURE_POINT = (
    "trading.master_v2.integrated_offline_trading_logic_replay_v1."
    "run_integrated_offline_trading_logic_replay_v1@post_transition_state"
)

CANONICAL_SIDESTATE_RESTART_OWNER = "MEMBER_DYNAMIC_SCOPE"
CANONICAL_SIDESTATE_RESTART_FIELD = "CanonicalDynamicScopeStateV1.side_state"

ERROR_MISSING_FIELD = "REGIME_BBS_EVIDENCE_MISSING_FIELD"
ERROR_INVALID_ENUM = "REGIME_BBS_EVIDENCE_INVALID_ENUM"
ERROR_SIDE_NEXT_MISMATCH = "REGIME_BBS_EVIDENCE_SIDE_NEXT_MISMATCH"
ERROR_INVALID_PAYLOAD = "REGIME_BBS_EVIDENCE_INVALID_PAYLOAD"
ERROR_SCHEMA_MISMATCH = "REGIME_BBS_EVIDENCE_SCHEMA_MISMATCH"
ERROR_CLASSIFICATION_MISMATCH = "REGIME_BBS_EVIDENCE_CLASSIFICATION_MISMATCH"
ERROR_WRITE_FAILED = "REGIME_BBS_EVIDENCE_WRITE_FAILED"
ERROR_LOAD_FAILED = "REGIME_BBS_EVIDENCE_LOAD_FAILED"
ERROR_PATH_REQUIRED = "REGIME_BBS_EVIDENCE_PATH_REQUIRED"
