"""CURRENT MF N=5 Full-Autonomy runtime completion.

Invokes canonical ensure_host_activation_binding_v1 on occupied-lane
readiness projections and rolls productive cardinality to 5 isolated
N=1 lanes. No trading-decision authority. No external effect.
"""

from src.ops.current_mf_n5_full_autonomy_runtime_n5_completion_v1.completion_join_v1 import (
    FullAutonomyRuntimeN5CompletionError,
    OccupiedLaneN5JoinedHostV1,
    OccupiedLaneRuntimeN5CompletionResultV1,
    cardinality_joined_token_v1,
    join_occupied_lane_host_activation_v1,
    lane_host_activation_root_v1,
    occupied_lane_runtime_n5_completion_census_v1,
    run_occupied_lane_runtime_n5_completion_v1,
)
from src.ops.current_mf_n5_full_autonomy_runtime_n5_completion_v1.constants_v1 import (
    ATLAS_AUTHORITY,
    AUTHORITY_EFFECT,
    AUTHORITY_WORK_REMAINING,
    CANONICAL_HOST_JOIN_OWNER,
    CANONICAL_HOST_JOIN_SYMBOL,
    CANONICAL_RUNTIME_OWNER,
    CONTRACT_ID,
    EXECUTION_CONCURRENCY_AUTHORIZED,
    EXTERNAL_EFFECT_AUTHORIZED,
    FIRST_UNAUTHORIZED_REMAINING_BOUNDARY,
    FIVE_LANE_RUNTIME_CREATED,
    HOST_JOIN,
    HOST_JOIN_INVOKED,
    JOIN_IMPLEMENTED,
    JOIN_SYMBOL,
    MAX_POSITIONS_EFFECTIVE,
    MAY_INVOKE_HOST_JOIN,
    MF_PRODUCTIVE_JOIN,
    MULTI_FUTURE_RUNTIME_AUTHORIZED,
    N5_MODEL,
    OWNER,
    OWNER_GO_THIS_SLICE,
    PRODUCTIVE_RUNTIME_CARDINALITY,
    RUNTIME_AUTHORIZATION_EFFECT,
    RUNTIME_N5_ARCHITECTURE_COMPLETE,
    SLICE_ID,
    TECHNICAL_WORK_REMAINING,
)

__all__ = [
    "ATLAS_AUTHORITY",
    "AUTHORITY_EFFECT",
    "AUTHORITY_WORK_REMAINING",
    "CANONICAL_HOST_JOIN_OWNER",
    "CANONICAL_HOST_JOIN_SYMBOL",
    "CANONICAL_RUNTIME_OWNER",
    "CONTRACT_ID",
    "EXECUTION_CONCURRENCY_AUTHORIZED",
    "EXTERNAL_EFFECT_AUTHORIZED",
    "FIRST_UNAUTHORIZED_REMAINING_BOUNDARY",
    "FIVE_LANE_RUNTIME_CREATED",
    "HOST_JOIN",
    "HOST_JOIN_INVOKED",
    "JOIN_IMPLEMENTED",
    "JOIN_SYMBOL",
    "MAX_POSITIONS_EFFECTIVE",
    "MAY_INVOKE_HOST_JOIN",
    "MF_PRODUCTIVE_JOIN",
    "MULTI_FUTURE_RUNTIME_AUTHORIZED",
    "N5_MODEL",
    "OWNER",
    "OWNER_GO_THIS_SLICE",
    "PRODUCTIVE_RUNTIME_CARDINALITY",
    "RUNTIME_AUTHORIZATION_EFFECT",
    "RUNTIME_N5_ARCHITECTURE_COMPLETE",
    "SLICE_ID",
    "TECHNICAL_WORK_REMAINING",
    "FullAutonomyRuntimeN5CompletionError",
    "OccupiedLaneN5JoinedHostV1",
    "OccupiedLaneRuntimeN5CompletionResultV1",
    "cardinality_joined_token_v1",
    "join_occupied_lane_host_activation_v1",
    "lane_host_activation_root_v1",
    "occupied_lane_runtime_n5_completion_census_v1",
    "run_occupied_lane_runtime_n5_completion_v1",
]
