"""Constants for CURRENT MF N=5 Full-Autonomy runtime completion.

Consumes N1 host-join readiness, invokes canonical
ensure_host_activation_binding_v1 per occupied lane, and rolls productive
cardinality 1_JOINED→5_JOINED. Cap23/Cap24 remain N=1 per lane.
External effect stays fail-closed.
"""

from __future__ import annotations

from src.ops.current_mf_n5_full_autonomy_occupied_lane_n1_host_join_readiness_v1.constants_v1 import (
    ADDRESS_SYMBOL as READINESS_ADDRESS_SYMBOL,
    CANONICAL_HOST_JOIN_MODULE as READINESS_HOST_JOIN_MODULE,
    CANONICAL_HOST_JOIN_OWNER as READINESS_HOST_JOIN_OWNER,
    CANONICAL_HOST_JOIN_PACKAGE as READINESS_HOST_JOIN_PACKAGE,
    CANONICAL_HOST_JOIN_SYMBOL as READINESS_HOST_JOIN_SYMBOL,
    CANONICAL_PRODUCTIVE_HOST as READINESS_PRODUCTIVE_HOST,
    CANONICAL_PRODUCTIVE_HOST_ENTRY as READINESS_PRODUCTIVE_HOST_ENTRY,
    COMPOSE_SYMBOL as READINESS_COMPOSE_SYMBOL,
    CURSOR_OWNER as READINESS_CURSOR_OWNER,
    FORBIDDEN_CALL_GRAPH_TARGETS as READINESS_FORBIDDEN_CALL_GRAPH_TARGETS,
    FULL_AUTONOMY_HOST_OWNER as READINESS_FULL_AUTONOMY_HOST_OWNER,
    HOST_JOIN as READINESS_HOST_JOIN,
    HOST_JOIN_INVOKED as READINESS_HOST_JOIN_INVOKED,
    LOCKING_MODEL as READINESS_LOCKING_MODEL,
    MAX_POSITIONS_EFFECTIVE as READINESS_MAX_POSITIONS_EFFECTIVE,
    MF_PRODUCTIVE_JOIN as READINESS_MF_PRODUCTIVE_JOIN,
    N1_CONSUMER_JOIN_READY as READINESS_N1_CONSUMER_JOIN_READY,
    N1_GLOBAL_CURSOR_STORE_RELPATH as READINESS_N1_GLOBAL_CURSOR_STORE_RELPATH,
    NATIVE_ID_SOURCE as READINESS_NATIVE_ID_SOURCE,
    OWNER as READINESS_OWNER,
    PREPARED_BOUND_CARDINALITY as READINESS_PREPARED_BOUND_CARDINALITY,
    PRODUCTIVE_RUNTIME_CARDINALITY as READINESS_PRODUCTIVE_RUNTIME_CARDINALITY,
)
from src.ops.current_mf_n5_isolated_lane_instance_topology_v1.constants_v1 import (
    CROSS_UNIVERSE_CANDIDATE_BORROWING as TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING,
    CROSS_UNIVERSE_FALLBACK as TOPOLOGY_CROSS_UNIVERSE_FALLBACK,
    CROSS_UNIVERSE_PIN as TOPOLOGY_CROSS_UNIVERSE_PIN,
    CROSS_UNIVERSE_REPLACEMENT as TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT,
    CROSS_UNIVERSE_RERANKING as TOPOLOGY_CROSS_UNIVERSE_RERANKING,
    CROSS_UNIVERSE_SELECTION as TOPOLOGY_CROSS_UNIVERSE_SELECTION,
    INSTRUMENT_ID_ALONE_SUFFICIENT as TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT,
    LANE_MAPPING_OWNER as TOPOLOGY_LANE_MAPPING_OWNER,
    MAX_LANE_COUNT as TOPOLOGY_MAX_LANE_COUNT,
    MULTI_UNIVERSE_MERGE as TOPOLOGY_MULTI_UNIVERSE_MERGE,
)
from src.ops.current_mf_n5_occupied_lane_pin_consumer_join_v1.constants_v1 import (
    FIVE_LANE_CONTINUOUS_HOST_JOIN as PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN,
)
from src.ops.full_core_live_path_composition_root_v1.constants_v1 import (
    EXTERNAL_EFFECT_AUTHORIZED as FULL_CORE_EXTERNAL_EFFECT_AUTHORIZED,
    HOST_JOIN_OWNER as FULL_CORE_HOST_JOIN_OWNER,
    POST_ALLOWED as FULL_CORE_POST_ALLOWED,
    REAL_VENUE_POST_ALLOWED as FULL_CORE_REAL_VENUE_POST_ALLOWED,
)
from src.ops.single_selected_future_policy_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP23_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP23_OWNER_VALUE,
)
from src.ops.single_selected_future_runtime_binding_v1.constants_v1 import (
    MAX_POSITIONS_EFFECTIVE as CAP24_MAX_POSITIONS_EFFECTIVE,
    MULTI_FUTURE_RUNTIME_AUTHORIZED as CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED,
    OWNER as CAP24_OWNER_VALUE,
    RUNTIME_ACTIVATION_ALLOWED as CAP24_RUNTIME_ACTIVATION_ALLOWED,
)

OWNER = "ops.current_mf_n5_full_autonomy_runtime_n5_completion_v1"
CONTRACT_ID = "CURRENT_MF_N5_FULL_AUTONOMY_RUNTIME_N5_COMPLETION_CONTRACT_V1"
SCHEMA_VERSION = "current_mf_n5_full_autonomy_runtime_n5_completion.v1"
SLICE_ID = "RUNTIME_N5_HOST_JOIN_AND_CARDINALITY_COMPLETION"
OWNER_GO_THIS_SLICE = "OWNER_GO_BIG_RUNTIME_N5_COMPLETION_V1"

LANE_MAPPING_OWNER = TOPOLOGY_LANE_MAPPING_OWNER
CAP23_SELECTION_OWNER = CAP23_OWNER_VALUE
CAP24_BINDING_OWNER = CAP24_OWNER_VALUE
READINESS_OWNER_VALUE = READINESS_OWNER
CONSUMER_OWNER = OWNER
CURSOR_OWNER = READINESS_CURSOR_OWNER
FULL_AUTONOMY_HOST_OWNER = READINESS_FULL_AUTONOMY_HOST_OWNER
CANONICAL_HOST_JOIN_OWNER = FULL_CORE_HOST_JOIN_OWNER
CANONICAL_HOST_JOIN_PACKAGE = READINESS_HOST_JOIN_PACKAGE
CANONICAL_HOST_JOIN_SYMBOL = READINESS_HOST_JOIN_SYMBOL
CANONICAL_HOST_JOIN_MODULE = READINESS_HOST_JOIN_MODULE
CANONICAL_PRODUCTIVE_HOST = READINESS_PRODUCTIVE_HOST
CANONICAL_PRODUCTIVE_HOST_ENTRY = READINESS_PRODUCTIVE_HOST_ENTRY
CANONICAL_RUNTIME_OWNER = CANONICAL_HOST_JOIN_PACKAGE
LOCKING_OWNER = "ops.canonical_durable_authorization_lifecycle_and_revocation_v1.lifecycle_lock_v1"
LOCKING_MODEL = READINESS_LOCKING_MODEL
EXECUTION_SCHEDULE = "SEQUENTIAL_LANE_ID_ORDER_NOT_CONCURRENT"

READINESS_COMPOSE_SYMBOL_VALUE = READINESS_COMPOSE_SYMBOL
READINESS_ADDRESS_SYMBOL_VALUE = READINESS_ADDRESS_SYMBOL
JOIN_SYMBOL = "run_occupied_lane_runtime_n5_completion_v1"
HOST_JOIN_SYMBOL = "join_occupied_lane_host_activation_v1"
COMPOSE_SYMBOL = JOIN_SYMBOL
JOIN_IMPLEMENTED = True
JOIN_INTENDED_EGRESS = "OccupiedLaneRuntimeN5CompletionResultV1"
CONSUMPTION_SEAM = READINESS_COMPOSE_SYMBOL_VALUE
HOST_JOIN_SEAM = CANONICAL_HOST_JOIN_SYMBOL
N1_CONSUMER_JOIN_READY = READINESS_N1_CONSUMER_JOIN_READY
HOST_JOIN_ADDRESSED = True
HOST_JOIN_INVOKED = True
MAY_INVOKE_HOST_JOIN = True
MAY_ENABLE_HOST = True
MAY_JOIN_CAP72_LIVE_EXECUTION_PORT = False
MAY_INVOKE_PRODUCTIVE_HOST_ENTRY = False
MAY_BIND_CAP61_STATE_ROOT = False
MAY_CAP61_PERSIST = False
MAY_MINT_PERMIT = False
MAY_POST = False
MAY_EXECUTE_NETWORK = False
MAY_PERFORM_GET = False
NATIVE_ID_SOURCE = READINESS_NATIVE_ID_SOURCE
N1_GLOBAL_CURSOR_STORE_RELPATH = READINESS_N1_GLOBAL_CURSOR_STORE_RELPATH
N1_GLOBAL_CURSOR_LANE_SAFE = False
CURSOR_BUNDLE_TYPE = "CurrentProductiveSideStateConfirmationCursorV1"
CURSOR_FILENAME = "current_productive_sidestate_confirmation_cursor_v1.json"
CURSOR_HAS_LANE_ID_FIELD = False
CURSOR_SCHEMA_CHANGED = False
NEW_CURSOR_LANE_ID_FIELD = False
NEW_CURSOR_WRITER = False
CURSOR_SINGLE_WRITER = True
ATOMICITY_SEMANTICS = "NON_ATOMIC_DIRECT_WRITE_TEXT"
ATOMICITY_CLAIMED_SATISFIED = False
PERSIST_SURFACE_OWNER = CURSOR_OWNER
CAP61_CYCLE_STATE_ROOT_BOUND = False
INVOCATION_CONTEXT = "BOUNDED_TEST_HARNESS_LANE_ISOLATED"
OCCUPIED_LANES_ONLY = True
UNIQUE_MUTABLE_ROOTS_ENFORCED = True
GLOBAL_N1_CURSOR_REJECTED = True
LANE_STATE_ROOT_ROLE = "LANE_LOCAL_MUTABLE_ROOT"
HOST_STATE_ROOT_ROLE = "LANE_LOCAL_CAP72_ACTIVATION_SUBROOT"
HOST_ACTIVATION_DIRNAME = "cap72_host_activation"
MAX_PRODUCTIVE_OCCUPIED_LANES = int(TOPOLOGY_MAX_LANE_COUNT)

SAME_TRADING_CONFIGURATION_ACROSS_LANES = True
SHARED_MUTABLE_STATE_ACROSS_LANES = False
NEW_STATE_OWNER_CREATED = False
NEW_COLLECTION_DTO_CREATED = False
NEW_TOP5_HANDOFF_DTO_CREATED = False
NEW_MULTI_BOUND_AUTHORITY_DTO_CREATED = False
NEW_MV2_DP_INGRESS_DTO_CREATED = False
NEW_CURSOR_SCHEMA_CREATED = False
NEW_HOST_OWNER_CREATED = False

AUTHORITY_EFFECT = "NONE"
RUNTIME_AUTHORIZATION_EFFECT = "HOST_JOIN_AND_N5_CARDINALITY_ORCHESTRATION_NO_EXTERNAL_EFFECT"
JOIN_SELECTION_AUTHORITY = False
JOIN_CAP23_SELECTION_AUTHORITY = False
JOIN_CAP24_BINDING_AUTHORITY = False
JOIN_TRADING_AUTHORITY = False
JOIN_RUNTIME_ACTIVATION_AUTHORITY = False
JOIN_EXECUTION_AUTHORITY = False
JOIN_RANKING_AUTHORITY = False
JOIN_MEMBERSHIP_AUTHORITY = False
JOIN_MAPPING_AUTHORITY = False
JOIN_PERSISTENCE_AUTHORITY = False
JOIN_FULL_AUTONOMY_HOST_AUTHORITY = False
FULL_AUTONOMY_TRADING_DECISION_AUTHORITY = False
PARALLEL_AUTHORITY_CREATED = False
THIS_SLICE_MAY_REINVOKE_CAP23 = False
THIS_SLICE_MAY_REINVOKE_CAP24 = False
MF_PRODUCTIVE_JOIN = True
FIVE_LANE_RUNTIME_CREATED = True
FIVE_LANE_CONTINUOUS_HOST_JOIN = PIN_CONSUMER_FIVE_LANE_CONTINUOUS_HOST_JOIN
EXECUTION_CONCURRENCY_AUTHORIZED = False
HOST_JOIN = True
MF_SINGLE_EGRESS_REWIRED = False
MAX_POSITIONS_EFFECTIVE = int(READINESS_MAX_POSITIONS_EFFECTIVE)
MULTI_FUTURE_RUNTIME_AUTHORIZED = bool(CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED)
PREPARED_BOUND_CARDINALITY = READINESS_PREPARED_BOUND_CARDINALITY
PRODUCTIVE_RUNTIME_CARDINALITY = "5_JOINED"
N5_MODEL = "FIVE_ISOLATED_N1_LANES"
EXTERNAL_EFFECT_AUTHORIZED = FULL_CORE_EXTERNAL_EFFECT_AUTHORIZED
POST_ALLOWED = FULL_CORE_POST_ALLOWED
REAL_VENUE_POST_ALLOWED = FULL_CORE_REAL_VENUE_POST_ALLOWED
RUNTIME_N5_ARCHITECTURE_COMPLETE = True
TECHNICAL_WORK_REMAINING = "NONE"
AUTHORITY_WORK_REMAINING = "EXTERNAL_EFFECT_LIVE_TRADING_OWNER_GO"
FIRST_UNAUTHORIZED_REMAINING_BOUNDARY = "EXTERNAL_EFFECT_LIVE_TRADING_OWNER_GO"

CROSS_UNIVERSE_SELECTION = TOPOLOGY_CROSS_UNIVERSE_SELECTION
CROSS_UNIVERSE_PIN = TOPOLOGY_CROSS_UNIVERSE_PIN
CROSS_UNIVERSE_REPLACEMENT = TOPOLOGY_CROSS_UNIVERSE_REPLACEMENT
CROSS_UNIVERSE_FALLBACK = TOPOLOGY_CROSS_UNIVERSE_FALLBACK
CROSS_UNIVERSE_CANDIDATE_BORROWING = TOPOLOGY_CROSS_UNIVERSE_CANDIDATE_BORROWING
CROSS_UNIVERSE_RERANKING = TOPOLOGY_CROSS_UNIVERSE_RERANKING
MULTI_UNIVERSE_MERGE = TOPOLOGY_MULTI_UNIVERSE_MERGE
INSTRUMENT_ID_ALONE_SUFFICIENT = TOPOLOGY_INSTRUMENT_ID_ALONE_SUFFICIENT
UNIVERSE_ISOLATION = "HARD"
UNIVERSE_ISOLATION_ENFORCED = True

CAP23_CHANGE_REQUIRED = False
CAP24_CHANGE_REQUIRED = False
MASTER_V2_CHANGE_REQUIRED = False
DOUBLE_PLAY_CHANGE_REQUIRED = False
FULL_AUTONOMY_HOST_CHANGE_REQUIRED = False
CURSOR_OWNER_CHANGE_REQUIRED = False
READINESS_CHANGE_REQUIRED = False
N1_CONSUMER_CHANGE_REQUIRED = False

ATLAS_AUTHORITY = "NONE"

assert READINESS_HOST_JOIN is False
assert READINESS_HOST_JOIN_INVOKED is False
assert READINESS_MF_PRODUCTIVE_JOIN is False
assert READINESS_PRODUCTIVE_RUNTIME_CARDINALITY == "1_UNJOINED"
assert READINESS_N1_CONSUMER_JOIN_READY is True
assert HOST_JOIN is True
assert HOST_JOIN_INVOKED is True
assert MAY_INVOKE_HOST_JOIN is True
assert MAY_ENABLE_HOST is True
assert MAY_JOIN_CAP72_LIVE_EXECUTION_PORT is False
assert MAY_INVOKE_PRODUCTIVE_HOST_ENTRY is False
assert MAY_BIND_CAP61_STATE_ROOT is False
assert MAY_MINT_PERMIT is False
assert MAY_POST is False
assert NATIVE_ID_SOURCE == "BoundInstrumentV1.venue_native_id"
assert ATOMICITY_SEMANTICS == "NON_ATOMIC_DIRECT_WRITE_TEXT"
assert ATOMICITY_CLAIMED_SATISFIED is False
assert NEW_STATE_OWNER_CREATED is False
assert NEW_HOST_OWNER_CREATED is False
assert NEW_CURSOR_WRITER is False
assert CURSOR_SINGLE_WRITER is True
assert MAX_POSITIONS_EFFECTIVE == int(CAP23_MAX_POSITIONS_EFFECTIVE)
assert MAX_POSITIONS_EFFECTIVE == int(CAP24_MAX_POSITIONS_EFFECTIVE) == 1
assert MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP23_MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_MULTI_FUTURE_RUNTIME_AUTHORIZED is False
assert CAP24_RUNTIME_ACTIVATION_ALLOWED is False
assert MF_PRODUCTIVE_JOIN is True
assert FIVE_LANE_RUNTIME_CREATED is True
assert FIVE_LANE_CONTINUOUS_HOST_JOIN is False
assert PARALLEL_AUTHORITY_CREATED is False
assert JOIN_SELECTION_AUTHORITY is False
assert JOIN_CAP23_SELECTION_AUTHORITY is False
assert JOIN_CAP24_BINDING_AUTHORITY is False
assert JOIN_TRADING_AUTHORITY is False
assert JOIN_RUNTIME_ACTIVATION_AUTHORITY is False
assert JOIN_RANKING_AUTHORITY is False
assert JOIN_PERSISTENCE_AUTHORITY is False
assert JOIN_FULL_AUTONOMY_HOST_AUTHORITY is False
assert JOIN_EXECUTION_AUTHORITY is False
assert FULL_AUTONOMY_TRADING_DECISION_AUTHORITY is False
assert PREPARED_BOUND_CARDINALITY == "0..5"
assert PRODUCTIVE_RUNTIME_CARDINALITY == "5_JOINED"
assert MAX_PRODUCTIVE_OCCUPIED_LANES == 5
assert EXECUTION_CONCURRENCY_AUTHORIZED is False
assert N1_CONSUMER_JOIN_READY is True
assert HOST_JOIN_ADDRESSED is True
assert EXTERNAL_EFFECT_AUTHORIZED is False
assert POST_ALLOWED is False
assert REAL_VENUE_POST_ALLOWED is False
assert RUNTIME_N5_ARCHITECTURE_COMPLETE is True
assert TECHNICAL_WORK_REMAINING == "NONE"
assert AUTHORITY_WORK_REMAINING == "EXTERNAL_EFFECT_LIVE_TRADING_OWNER_GO"
assert CANONICAL_HOST_JOIN_OWNER == "stateful_no_order_host_join_v1"
assert CANONICAL_HOST_JOIN_OWNER == FULL_CORE_HOST_JOIN_OWNER
assert CANONICAL_HOST_JOIN_SYMBOL == "ensure_host_activation_binding_v1"
assert JOIN_SYMBOL == "run_occupied_lane_runtime_n5_completion_v1"
assert HOST_JOIN_SYMBOL == "join_occupied_lane_host_activation_v1"
assert HOST_ACTIVATION_DIRNAME == "cap72_host_activation"
assert N5_MODEL == "FIVE_ISOLATED_N1_LANES"
assert ATLAS_AUTHORITY == "NONE"
assert EXECUTION_SCHEDULE == "SEQUENTIAL_LANE_ID_ORDER_NOT_CONCURRENT"

FAILURE_AUTHORITY = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_AUTHORITY_CLAIM_FORBIDDEN"
FAILURE_UNKNOWN_LANE_ID = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_UNKNOWN_LANE_ID"
FAILURE_PAIR_TYPE = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_PAIR_TYPE_MISMATCH"
FAILURE_OCCUPANCY = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_OCCUPANCY_MISMATCH"
FAILURE_IDENTITY_MISMATCH = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_IDENTITY_MISMATCH"
FAILURE_NATIVE_ID_MISSING = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_NATIVE_ID_MISSING"
FAILURE_RESULT_MISSING = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_READINESS_MISSING"
FAILURE_LANE_STATE_ROOT = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_LANE_STATE_ROOT_MISMATCH"
FAILURE_ORIGIN_MAIN_SHA = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_ORIGIN_MAIN_SHA_MISSING"
FAILURE_FORBIDDEN_KWARG = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_FORBIDDEN_KWARG"
FAILURE_EXTERNAL_EFFECT = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_EXTERNAL_EFFECT"
FAILURE_HOST_JOIN = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_HOST_JOIN_FAILED"
FAILURE_CARDINALITY = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_CARDINALITY_MISMATCH"
FAILURE_LIVE_PORT = "FULL_AUTONOMY_RUNTIME_N5_COMPLETION_LIVE_PORT_FORBIDDEN"

FORBIDDEN_CALL_GRAPH_TARGETS = frozenset(READINESS_FORBIDDEN_CALL_GRAPH_TARGETS) - frozenset(
    {
        "ensure_host_activation_binding_v1",
        "HostActivationBindingV1",
    }
) | frozenset(
    {
        "join_cap72_host_to_live_execution_port_v1",
        "run_bridge_cycle_v1",
        "construct_live_execution_port_v1",
        "run_activation_gate_v1",
        "produce_occupied_lane_cap23_n1_selections_v1",
        "run_single_selected_future_policy_v1",
        "produce_single_selected_future_v1",
        "ensure_single_selected_future_runtime_binding_v1",
        "run_current_productive_governed_continuous_cycle_run_v1",
        "_pick_top_eligible",
        "top_n_active_set",
        "LiveExecutionPort",
    }
)

FORBIDDEN_COMPOSE_KWARGS = frozenset(
    {
        "enable_host",
        "host_enabled",
        "host_join",
        "host_joined",
        "persist_activation",
        "live_port",
        "attempt_submit",
        "attempt_wire_send",
        "execute_network",
        "perform_get",
        "mf_productive_join",
        "permit_mint",
        "skip_preconditions",
        "execution_concurrency",
    }
)
