"""Fail-closed reason codes for Cap 6.4 atomic decision-path restart."""

from __future__ import annotations

from enum import Enum


class DecisionPathAtomicFailureCodeV1(str, Enum):
    CONFLICTING_WRITER = "CONFLICTING_WRITER"
    WRITER_LOCK_NOT_HELD = "WRITER_LOCK_NOT_HELD"
    JOURNAL_MISSING = "JOURNAL_MISSING"
    JOURNAL_CORRUPT = "JOURNAL_CORRUPT"
    COMMIT_MARKER_MISSING = "COMMIT_MARKER_MISSING"
    COMMIT_MARKER_CORRUPT = "COMMIT_MARKER_CORRUPT"
    MIXED_STATE_ROOT_COMMIT = "MIXED_STATE_ROOT_COMMIT"
    MEMBER_DIGEST_MISMATCH = "MEMBER_DIGEST_MISMATCH"
    CONFIG_DIGEST_MISMATCH = "CONFIG_DIGEST_MISMATCH"
    REPOSITORY_SHA_MISMATCH = "REPOSITORY_SHA_MISMATCH"
    STATE_VERSION_MISMATCH = "STATE_VERSION_MISMATCH"
    CHECKPOINT_CORRUPT = "CHECKPOINT_CORRUPT"
    PERSISTENCE_INTERRUPTION = "PERSISTENCE_INTERRUPTION"
    MANIFEST_VERIFY_FAILED = "MANIFEST_VERIFY_FAILED"
    IDEMPOTENCY_KEY_REPLAY = "IDEMPOTENCY_KEY_REPLAY"
    PENDING_EVIDENCE_RECOVERY_FAILED = "PENDING_EVIDENCE_RECOVERY_FAILED"
    ALPHA_BLOCKED_ATOMIC_STATE_UNRECOVERABLE = "ALPHA_BLOCKED_ATOMIC_STATE_UNRECOVERABLE"
    CORE_LOGIC_DRIFT = "CORE_LOGIC_DRIFT"
    PARITY_FAILURE = "PARITY_FAILURE"
