"""Constants for V5 process-lifecycle checkpoint contracts."""

from __future__ import annotations

SCHEMA_VERSION = "bollinger_mr_midband_exit_efficiency_process_lifecycle_checkpoint.v5"
SURFACE_ID = "BOLLINGER_MR_MIDBAND_EXIT_EFFICIENCY_PROCESS_LIFECYCLE_CHECKPOINT_V5"
CHECKPOINT_FILENAME = "process_lifecycle_checkpoint_v5.json"
RECOVERY_DIAGNOSTICS_FILENAME = "process_lifecycle_recovery_diagnostics_v5.json"

RESULT_CLASS_INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"
ECONOMIC_VERDICT_NOT_EVALUATED = "NOT_EVALUATED"

LIFECYCLE_STATE_NOT_STARTED = "NOT_STARTED"
LIFECYCLE_STATE_PREFLIGHT_RUNNING = "PREFLIGHT_RUNNING"
LIFECYCLE_STATE_PREFLIGHT_PASSED = "PREFLIGHT_PASSED"
LIFECYCLE_STATE_RUN_SLOT_CLAIMED = "RUN_SLOT_CLAIMED"
LIFECYCLE_STATE_RUNNER_STARTED = "RUNNER_STARTED"
LIFECYCLE_STATE_MEMBER_STARTED = "MEMBER_STARTED"
LIFECYCLE_STATE_MEMBER_COMPLETED = "MEMBER_COMPLETED"
LIFECYCLE_STATE_CHECKPOINT_COMMITTED = "CHECKPOINT_COMMITTED"
LIFECYCLE_STATE_PANEL_COMPLETED = "PANEL_COMPLETED"
LIFECYCLE_STATE_SUMMARY_COMMITTED = "SUMMARY_COMMITTED"
LIFECYCLE_STATE_TERMINAL_COMMITTED = "TERMINAL_COMMITTED"

MONOTONIC_LIFECYCLE_STATES: tuple[str, ...] = (
    LIFECYCLE_STATE_NOT_STARTED,
    LIFECYCLE_STATE_PREFLIGHT_RUNNING,
    LIFECYCLE_STATE_PREFLIGHT_PASSED,
    LIFECYCLE_STATE_RUN_SLOT_CLAIMED,
    LIFECYCLE_STATE_RUNNER_STARTED,
    LIFECYCLE_STATE_MEMBER_STARTED,
    LIFECYCLE_STATE_MEMBER_COMPLETED,
    LIFECYCLE_STATE_CHECKPOINT_COMMITTED,
    LIFECYCLE_STATE_PANEL_COMPLETED,
    LIFECYCLE_STATE_SUMMARY_COMMITTED,
    LIFECYCLE_STATE_TERMINAL_COMMITTED,
)

REQUIRED_PROGRESS_METADATA_FIELDS: tuple[str, ...] = (
    "run_id",
    "process_id",
    "started_at",
    "last_heartbeat_at",
    "current_member_index",
    "completed_member_count",
    "total_member_count",
    "last_completed_member_id",
    "lifecycle_state",
    "checkpoint_sequence",
)

# Member loops may revisit MEMBER_STARTED -> MEMBER_COMPLETED -> CHECKPOINT_COMMITTED.
MEMBER_LOOP_STATES: frozenset[str] = frozenset(
    {
        LIFECYCLE_STATE_MEMBER_STARTED,
        LIFECYCLE_STATE_MEMBER_COMPLETED,
        LIFECYCLE_STATE_CHECKPOINT_COMMITTED,
    }
)

AUTO_RERUN_ALLOWED = False
AUTO_RESUME_ALLOWED = False
CHECKPOINT_AUTHORIZES_RERUN = False
CHECKPOINT_CAN_RECLAIM_RUN_SLOT = False
PARTIAL_METRICS_AUTHORITATIVE = False
RECOVERY_INSPECTION_MUTATES_STATE = False
