"""Assemble the SEND_TIME_PASS_18_19_21_24 persist pack."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.ops.section_11_13_5_send_time_pass_18_19_21_24_v1.adjudicate_v1 import (
    adjudicate_send_time_pass_18_19_21_24_v1,
)
from src.ops.section_11_13_5_send_time_pass_18_19_21_24_v1.constants_v1 import (
    AUTHORIZED_ACCOUNT_UID,
    AUTHORIZED_HOST,
    AUTHORIZED_OPERATION,
    AUTHORIZED_SCOPE,
    CANONICAL_EVIDENCE_RUN_ID,
    CASE_VALUE,
    CONFLICT_COUNT,
    EARLIEST_UNRESOLVED_DEPENDENCY,
    EXPECTED_ORIGIN_MAIN_SHA,
    FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE_VALUE,
    LAST_CANONICALLY_CLOSED_STEP,
    NAMED_REMAINING_HIGHER_AUTHORITY,
    NEXT_AUTHORITY_BOUNDARY,
    OWNER_GO,
    P08_CLOSED,
    P10_CLOSED,
    P11_CLOSED,
    P12_CLOSED,
    P13_CLOSED,
    P16_CLOSED,
    P16_TEXT_REWRITTEN_VALUE,
    P20_CLOSED,
    P20_TEXT_REWRITTEN_VALUE,
    P25_CLOSED,
    P25_TEXT_REWRITTEN_VALUE,
    PREDECESSOR_SLICE,
    PRIOR_OWNER_GO,
    PREREQUISITE_18_PROVEN_AT_SEND_VALUE,
    PREREQUISITE_19_PROVEN_AT_SEND_VALUE,
    PREREQUISITE_21_PROVEN_AT_SEND_VALUE,
    PREREQUISITE_24_PROVEN_AT_SEND_VALUE,
    PRIVATE_AUTH_USED,
    PUBLIC_SPEC_RETRIEVAL_PERFORMED,
    RUNTIME_GET_PERFORMED,
    RUNTIME_GET_REQUIRED,
    SEND_TIME_PASS_18_19_21_24,
    STP_DOES_NOT_AUTHORIZE_AUTHENTICATED_PRODUCTIVE_TRANSPORT_VALUE,
    STP_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
    STP_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
    STP_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
    STP_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
    STP_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
    STP_FLATTEN_EXECUTE_AUTHORIZED_VALUE,
    STP_MECHANISM_IMPLEMENTED,
    STP_NAMED_CONTRACT_CLOSED,
    STP_NETWORK_SESSION_AUTHORIZED_VALUE,
    STP_RUNTIME_RESIDUAL,
    STP_SEND_TIME_REOBSERVATION_PROVEN_VALUE,
    TARGET_INSTRUMENT_ID,
    THIS_GO_GET_COUNT,
    THIS_GO_POST_COUNT,
    THIS_SLICE,
    WORKPACKAGE_ID,
)
from src.ops.section_11_13_5_send_time_pass_18_19_21_24_v1.persist_v1 import (
    persist_send_time_pass_18_19_21_24_evidence_v1,
)


class SendTimePass182124AssembleError(RuntimeError):
    """Fail-closed assemble violation."""


def assemble_send_time_pass_18_19_21_24_v1(
    *,
    origin_main_sha: str,
    evidence_root: Path | None = None,
    run_id: str = CANONICAL_EVIDENCE_RUN_ID,
) -> dict[str, Any]:
    """Build and optionally persist send-time pass 18/19/21/24. No GET. No POST."""
    if str(origin_main_sha or "").strip() != EXPECTED_ORIGIN_MAIN_SHA:
        raise SendTimePass182124AssembleError("ORIGIN_MAIN_SHA_MISMATCH")
    verdict = adjudicate_send_time_pass_18_19_21_24_v1(origin_main_sha=origin_main_sha)
    if verdict["SEND_TIME_PASS_18_19_21_24"] != "PASS_OFFLINE_CONTRACT":
        raise SendTimePass182124AssembleError("SEND_TIME_PASS_MUST_BE_PASS_OFFLINE_CONTRACT")
    if verdict["PREREQUISITE_18_PROVEN_AT_SEND"] is True:
        raise SendTimePass182124AssembleError("PROVEN_AT_SEND_MUST_REMAIN_FALSE")
    if verdict["STP_FLATTEN_EXECUTE_AUTHORIZED"] is True:
        raise SendTimePass182124AssembleError("FLATTEN_EXECUTE_MUST_REMAIN_UNAUTHORIZED")
    census = {
        "DOCUMENT_CLASS": "SEND_TIME_PASS_18_19_21_24_CENSUS_V1",
        "DOCUMENT_ROLE": "FORENSIC_CENSUS_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "SEAM_COUNT": verdict["CENSUS"]["SEAM_COUNT"],
        "EPISTEMIC_CLASS_COUNTS": verdict["CENSUS"]["EPISTEMIC_CLASS_COUNTS"],
        "PROVEN_SEAMS": verdict["CENSUS"]["PROVEN_SEAMS"],
        "NOT_PROMOTED_SEAMS": verdict["CENSUS"]["NOT_PROMOTED_SEAMS"],
        "NAMED_REMAINING_HIGHER_AUTHORITY": list(NAMED_REMAINING_HIGHER_AUTHORITY),
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
        "GET_PERFORMED_THIS_PERSIST": False,
        "PRIVATE_AUTH_USED": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
    }
    lineage = {
        "DOCUMENT_CLASS": "SEND_TIME_PASS_18_19_21_24_LINEAGE_V1",
        "DOCUMENT_ROLE": "FORENSIC_LINEAGE_AUTHORITY_NONE",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "LINEAGE_FIELD_NAMES": verdict["CENSUS"]["LINEAGE_FIELD_NAMES"],
        "SEAMS": verdict["LINEAGE"],
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "POST_PERFORMED": False,
    }
    adjudication = {
        "DOCUMENT_CLASS": "SEND_TIME_PASS_18_19_21_24_ADJUDICATION_V1",
        "DOCUMENT_ROLE": "INTERPRETATION_NOT_RAW_WIRE_NOT_SSOT",
        "AUTHORITY": "NONE",
        "OWNER_GO": OWNER_GO,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "PREDECESSOR_SLICE": PREDECESSOR_SLICE,
        "BOUND_ORIGIN_MAIN_SHA": origin_main_sha,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "SEND_TIME_PASS_18_19_21_24": SEND_TIME_PASS_18_19_21_24,
        "STP_NAMED_SEND_TIME_EVALUATION_CONTRACT_CLOSED": STP_NAMED_CONTRACT_CLOSED,
        "STP_SEND_TIME_EVALUATION_GATE_IMPLEMENTED": STP_MECHANISM_IMPLEMENTED,
        "PREREQUISITE_18_PROVEN_AT_SEND": PREREQUISITE_18_PROVEN_AT_SEND_VALUE,
        "PREREQUISITE_19_PROVEN_AT_SEND": PREREQUISITE_19_PROVEN_AT_SEND_VALUE,
        "PREREQUISITE_21_PROVEN_AT_SEND": PREREQUISITE_21_PROVEN_AT_SEND_VALUE,
        "PREREQUISITE_24_PROVEN_AT_SEND": PREREQUISITE_24_PROVEN_AT_SEND_VALUE,
        "STP_SEND_TIME_REOBSERVATION_PROVEN": STP_SEND_TIME_REOBSERVATION_PROVEN_VALUE,
        "STP_NETWORK_SESSION_AUTHORIZED": STP_NETWORK_SESSION_AUTHORIZED_VALUE,
        "STP_FLATTEN_EXECUTE_AUTHORIZED": STP_FLATTEN_EXECUTE_AUTHORIZED_VALUE,
        "NAMED_REMAINING_HIGHER_AUTHORITY": list(NAMED_REMAINING_HIGHER_AUTHORITY),
        "OFFLINE_CONTRACT_PROOF_CLASS": verdict["OFFLINE_CONTRACT_PROOF_CLASS"],
        "STRUCTURAL_ALLOW_IS_NOT_RUNTIME_MUTATION": True,
        "STRUCTURAL_ALLOW_IS_NOT_WIRE_SEND": True,
        "FAIL_CLOSED_STATUS": verdict["FAIL_CLOSED_STATUS"],
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P08_CLOSED": P08_CLOSED,
        "P10_CLOSED": P10_CLOSED,
        "P11_CLOSED": P11_CLOSED,
        "P12_CLOSED": P12_CLOSED,
        "P13_CLOSED": P13_CLOSED,
        "P16_CLOSED": P16_CLOSED,
        "P20_CLOSED": P20_CLOSED,
        "P25_CLOSED": P25_CLOSED,
        "P16_TEXT_REWRITTEN": P16_TEXT_REWRITTEN_VALUE,
        "P20_TEXT_REWRITTEN": P20_TEXT_REWRITTEN_VALUE,
        "P25_TEXT_REWRITTEN": P25_TEXT_REWRITTEN_VALUE,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "STP_RUNTIME_RESIDUAL": STP_RUNTIME_RESIDUAL,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_POST_COUNT": THIS_GO_POST_COUNT,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
        "RUNTIME_GET_REQUIRED": RUNTIME_GET_REQUIRED,
        "RUNTIME_GET_PERFORMED": RUNTIME_GET_PERFORMED,
        "PRIVATE_AUTH_USED": PRIVATE_AUTH_USED,
        "PUBLIC_SPEC_RETRIEVAL_PERFORMED": PUBLIC_SPEC_RETRIEVAL_PERFORMED,
        "STP_DOES_NOT_GRANT_EXECUTION_READINESS": STP_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE,
        "STP_DOES_NOT_AUTHORIZE_FLATTEN": STP_DOES_NOT_AUTHORIZE_FLATTEN_VALUE,
        "STP_DOES_NOT_SET_LIVE_AUTHORIZED": STP_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE,
        "STP_DOES_NOT_ISSUE_RUNTIME_PERMIT": STP_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE,
        "STP_DOES_NOT_AUTHORIZE_NETWORK_SESSION": STP_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE,
        "STP_DOES_NOT_AUTHORIZE_AUTHENTICATED_PRODUCTIVE_TRANSPORT": (
            STP_DOES_NOT_AUTHORIZE_AUTHENTICATED_PRODUCTIVE_TRANSPORT_VALUE
        ),
        "FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE": (
            FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE_VALUE
        ),
        "LIVE_EXECUTION": False,
        "CANARY_EXECUTION": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "NETWORK_SESSION_AUTHORIZED_DEFAULT": False,
        "IMPLEMENTATION_GO_FORBIDDEN_AS_FLATTEN_EXECUTE": True,
        "CENSUS": verdict["CENSUS"],
        "LINEAGE": verdict["LINEAGE"],
        "WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY": verdict["WINDOW_EARLIEST_UNRESOLVED_DEPENDENCY"],
    }
    summary = {
        "DOCUMENT_CLASS": "SEND_TIME_PASS_18_19_21_24_PACKAGE_V1",
        "DOCUMENT_ROLE": "DERIVED_NON_SSOT",
        "OWNER_GO": OWNER_GO,
        "OWNER_GO_CONSUMED": True,
        "PRIOR_OWNER_GO": PRIOR_OWNER_GO,
        "THIS_SLICE": THIS_SLICE,
        "WORKPACKAGE_ID": WORKPACKAGE_ID,
        "AUTHORIZED_SCOPE": AUTHORIZED_SCOPE,
        "AUTHORIZED_OPERATION": AUTHORIZED_OPERATION,
        "HOST": AUTHORIZED_HOST,
        "AUTHORIZED_ACCOUNT_UID": AUTHORIZED_ACCOUNT_UID,
        "TARGET_INSTRUMENT_ID": TARGET_INSTRUMENT_ID,
        "CASE": CASE_VALUE,
        "SEND_TIME_PASS_18_19_21_24": SEND_TIME_PASS_18_19_21_24,
        "STP_NAMED_SEND_TIME_EVALUATION_CONTRACT_CLOSED": STP_NAMED_CONTRACT_CLOSED,
        "PREREQUISITE_18_PROVEN_AT_SEND": False,
        "STP_FLATTEN_EXECUTE_AUTHORIZED": False,
        "CONFLICT_COUNT": CONFLICT_COUNT,
        "P25_CLOSED": True,
        "P25_TEXT_REWRITTEN": False,
        "P20_CLOSED": True,
        "P20_TEXT_REWRITTEN": False,
        "P16_CLOSED": True,
        "P16_TEXT_REWRITTEN": False,
        "LAST_CANONICALLY_CLOSED_STEP": LAST_CANONICALLY_CLOSED_STEP,
        "EARLIEST_UNRESOLVED_DEPENDENCY": EARLIEST_UNRESOLVED_DEPENDENCY,
        "NEXT_AUTHORITY_BOUNDARY": NEXT_AUTHORITY_BOUNDARY,
        "STP_RUNTIME_RESIDUAL": STP_RUNTIME_RESIDUAL,
        "GET_REQUEST_COUNT": THIS_GO_GET_COUNT,
        "THIS_GO_GET_COUNT": THIS_GO_GET_COUNT,
        "HTTP_EXCHANGE_COUNT": 0,
        "POST_COUNT": THIS_GO_POST_COUNT,
        "WRITE_REQUEST_COUNT": 0,
        "GET_PERFORMED_THIS_PERSIST": False,
        "POST_PERFORMED": False,
        "PRIVATE_AUTH_USED": False,
        "LIVE_AUTHORIZED": False,
        "CANARY_AUTHORIZED": False,
        "SUBMIT_UNLOCKED": False,
        "LIVE_ENABLED": False,
        "LIVE_ARMED": False,
        "MERGE_AUTHORIZED_BY_THIS_PERSIST": False,
        "BOUNDED_RUNTIME_PERMIT_ISSUANCE": False,
        "STP_DOES_NOT_GRANT_EXECUTION_READINESS": True,
        "EXECUTION_READY": False,
        "ATLAS_AUTHORITY": "NONE",
        "LANDSCAPE_AUTHORITY": "NONE",
    }
    result: dict[str, Any] = {
        "verdict": verdict,
        "census": census,
        "lineage": lineage,
        "adjudication": adjudication,
        "summary": summary,
    }
    if evidence_root is not None:
        pack = Path(evidence_root) / run_id
        verified = persist_send_time_pass_18_19_21_24_evidence_v1(
            pack=pack,
            origin_main_sha=origin_main_sha,
            census=census,
            lineage=lineage,
            adjudication=adjudication,
            summary=summary,
        )
        result["EVIDENCE_PACK"] = str(pack)
        result["MANIFEST_VERIFY_RC"] = int(verified.get("MANIFEST_VERIFY_RC", 1))
    return result
