"""Standing constants for SEND_TIME_PASS_18_19_21_24 offline evaluation.

Offline CASE_B contract persist. No GET. No POST. No flatten execute. No
Live/Canary unlock. Does not issue a runtime permit. Does not rewrite P25 text.
"""

from __future__ import annotations

from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.constants_v1 import (
    DEFAULT_INSTRUMENT_ID,
    LIVE_ARMED,
    LIVE_AUTHORIZED,
    LIVE_ENABLED,
    REUSED_BINDING_ACCOUNT_SCOPE,
    REUSED_BINDING_REST_HOST,
    SUBMIT_UNLOCKED,
    TESTNET_AUTHORIZED,
)
from src.ops.section_11_13_5_live_canary_minimum_exposure_v1.send_time_pass_18_19_21_24_v1 import (
    NAMED_REMAINING_AFTER_SEND_TIME_PASS,
    STP_IMPLEMENTATION_OWNER_GO,
)
from src.ops.section_11_13_5_send_time_pass_18_19_21_24_v1.contract_v1 import (
    CASE,
    FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE,
    P16_TEXT_REWRITTEN,
    P20_TEXT_REWRITTEN,
    P25_TEXT_REWRITTEN,
    PREREQUISITE_18_PROVEN_AT_SEND,
    PREREQUISITE_19_PROVEN_AT_SEND,
    PREREQUISITE_21_PROVEN_AT_SEND,
    PREREQUISITE_24_PROVEN_AT_SEND,
    SEND_TIME_PASS_18_19_21_24_STATUS,
    STP_DOES_NOT_AUTHORIZE_AUTHENTICATED_PRODUCTIVE_TRANSPORT,
    STP_DOES_NOT_AUTHORIZE_FLATTEN,
    STP_DOES_NOT_AUTHORIZE_NETWORK_SESSION,
    STP_DOES_NOT_GRANT_EXECUTION_READINESS,
    STP_DOES_NOT_ISSUE_RUNTIME_PERMIT,
    STP_DOES_NOT_SET_LIVE_AUTHORIZED,
    STP_FLATTEN_EXECUTE_AUTHORIZED,
    STP_NAMED_SEND_TIME_EVALUATION_CONTRACT_CLOSED,
    STP_NETWORK_SESSION_AUTHORIZED,
    STP_SEND_TIME_EVALUATION_GATE_IMPLEMENTED,
    STP_SEND_TIME_REOBSERVATION_PROVEN,
)

CAPABILITY_ID = "SEND_TIME_PASS_18_19_21_24_V1"
PACKAGE_MARKER = "SEND_TIME_PASS_18_19_21_24_V1=true"
OWNER = "ops.section_11_13_5_send_time_pass_18_19_21_24_v1"
CONTRACT_VERSION = "v1"
SCHEMA_VERSION = "send_time_pass_18_19_21_24.v1"
OWNER_GO = STP_IMPLEMENTATION_OWNER_GO
PRIOR_OWNER_GO = (
    "PEAK_TRADE_OWNER_GO_EXECUTION_PREREQUISITE_25_NO_ADDITIONAL_OWNER_DECISION"
    "_REQUIRED_MAXIMUM_SAFE_LEVERAGE_V1"
)
WORKPACKAGE_ID = "OKX_EEA_SEND_TIME_PASS_18_19_21_24_V1"
THIS_SLICE = "11.13.5.SEND_TIME_PASS"
PREDECESSOR_SLICE = "11.13.5.P25"
CURRENT_CANONICAL_SECTION = THIS_SLICE
LAST_CANONICALLY_CLOSED_STEP = "SECTION_11_13_5_SEND_TIME_PASS_18_19_21_24"
EXPECTED_ORIGIN_MAIN_SHA = "37a6c1ddcdc4a08821942627197e350e7c084c4e"
AUTHORIZED_HOST = REUSED_BINDING_REST_HOST
AUTHORIZED_ACCOUNT_UID = REUSED_BINDING_ACCOUNT_SCOPE
TARGET_INSTRUMENT_ID = DEFAULT_INSTRUMENT_ID
AUTHORIZED_OPERATION = "OFFLINE_SEND_TIME_PASS_18_19_21_24"
AUTHORIZED_SCOPE = "A_SEND_TIME_PASS_18_19_21_24"
CANONICAL_EVIDENCE_RUN_ID = "20260904T025000Z"

CASE_VALUE = CASE
SEND_TIME_PASS_18_19_21_24 = SEND_TIME_PASS_18_19_21_24_STATUS
STP_NAMED_CONTRACT_CLOSED = STP_NAMED_SEND_TIME_EVALUATION_CONTRACT_CLOSED
STP_MECHANISM_IMPLEMENTED = STP_SEND_TIME_EVALUATION_GATE_IMPLEMENTED
NAMED_REMAINING_HIGHER_AUTHORITY = NAMED_REMAINING_AFTER_SEND_TIME_PASS
CONFLICT_COUNT = 0
P08_CLOSED = True
P10_CLOSED = True
P11_CLOSED = True
P12_CLOSED = True
P13_CLOSED = True
P16_CLOSED = True
P20_CLOSED = True
P25_CLOSED = True
P16_TEXT_REWRITTEN_VALUE = P16_TEXT_REWRITTEN
P20_TEXT_REWRITTEN_VALUE = P20_TEXT_REWRITTEN
P25_TEXT_REWRITTEN_VALUE = P25_TEXT_REWRITTEN
STP_DOES_NOT_GRANT_EXECUTION_READINESS_VALUE = STP_DOES_NOT_GRANT_EXECUTION_READINESS
STP_DOES_NOT_AUTHORIZE_FLATTEN_VALUE = STP_DOES_NOT_AUTHORIZE_FLATTEN
STP_DOES_NOT_SET_LIVE_AUTHORIZED_VALUE = STP_DOES_NOT_SET_LIVE_AUTHORIZED
STP_DOES_NOT_ISSUE_RUNTIME_PERMIT_VALUE = STP_DOES_NOT_ISSUE_RUNTIME_PERMIT
STP_DOES_NOT_AUTHORIZE_NETWORK_SESSION_VALUE = STP_DOES_NOT_AUTHORIZE_NETWORK_SESSION
STP_DOES_NOT_AUTHORIZE_AUTHENTICATED_PRODUCTIVE_TRANSPORT_VALUE = (
    STP_DOES_NOT_AUTHORIZE_AUTHENTICATED_PRODUCTIVE_TRANSPORT
)
PREREQUISITE_18_PROVEN_AT_SEND_VALUE = PREREQUISITE_18_PROVEN_AT_SEND
PREREQUISITE_19_PROVEN_AT_SEND_VALUE = PREREQUISITE_19_PROVEN_AT_SEND
PREREQUISITE_21_PROVEN_AT_SEND_VALUE = PREREQUISITE_21_PROVEN_AT_SEND
PREREQUISITE_24_PROVEN_AT_SEND_VALUE = PREREQUISITE_24_PROVEN_AT_SEND
STP_SEND_TIME_REOBSERVATION_PROVEN_VALUE = STP_SEND_TIME_REOBSERVATION_PROVEN
STP_NETWORK_SESSION_AUTHORIZED_VALUE = STP_NETWORK_SESSION_AUTHORIZED
STP_FLATTEN_EXECUTE_AUTHORIZED_VALUE = STP_FLATTEN_EXECUTE_AUTHORIZED
FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE_VALUE = (
    FAIL_CLOSED_IF_MARKED_PROVEN_AT_SEND_FROM_OFFLINE_CODE_ALONE
)
EARLIEST_UNRESOLVED_DEPENDENCY = "AUTHENTICATED_PRODUCTIVE_TRANSPORT"
NEXT_AUTHORITY_BOUNDARY = "SEPARATE_OWNER_GO_FOR_AUTHENTICATED_PRODUCTIVE_TRANSPORT"
STP_RUNTIME_RESIDUAL = (
    "AUTHENTICATED_PRODUCTIVE_TRANSPORT_AND_SEND_TIME_POSITION_REOBSERVATION_AND_"
    "FLATTEN_EXECUTE_AND_BOUNDED_RUNTIME_PERMIT_ISSUANCE_REMAIN_SEPARATE_OWNER_GO"
)
RUNTIME_GET_REQUIRED = False
RUNTIME_GET_PERFORMED = False
PRIVATE_AUTH_USED = False
PUBLIC_SPEC_RETRIEVAL_PERFORMED = False
CENSUS_COMPLETE = True
LINEAGE_COMPLETE = True

THIS_GO_GET_COUNT = 0
THIS_GO_POST_COUNT = 0
AUTHORIZED_GET_COUNT = 0
ACTUAL_GET_COUNT = 0
GET_ALLOWED = False
PRIVATE_GET_ALLOWED = False
SECOND_GET_ALLOWED = False
POST_ALLOWED = False
ORDER_ALLOWED = False
FLATTEN_ALLOWED = False
LIVE_EXECUTION_ALLOWED = False
CANARY_EXECUTION_ALLOWED = False
CORE_CHANGE_ALLOWED = False
SUBMIT_BODY_PROBE_ALLOWED = False
MERGE_AUTHORIZED_BY_THIS_PERSIST = False
STANDING_LIVE_AUTHORIZED = LIVE_AUTHORIZED
STANDING_TESTNET_AUTHORIZED = TESTNET_AUTHORIZED
STANDING_CANARY_AUTHORIZED = False
STANDING_LIVE_ENABLED = LIVE_ENABLED
STANDING_LIVE_ARMED = LIVE_ARMED
STANDING_SUBMIT_UNLOCKED = SUBMIT_UNLOCKED

EVIDENCE_DIRNAME = "section_11_13_5_send_time_pass_18_19_21_24_v1"
