"""Constants for CAPABILITY_REGIME_BULL_BEAR_SWITCH_ARCHIVE_SIBLING_EXPORTER_V1.

AUTHORITY_EFFECT=NONE
TRADING_SEMANTIC_CHANGE=false
REGIME_RECOMPUTE=false
EVIDENCE_READMODEL_RELABEL=false
AUTOMATIC_CALLER_ADDED=false
PRESENTATION_CHANGED=false
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_REGIME_BULL_BEAR_SWITCH_ARCHIVE_SIBLING_EXPORTER_V1"
PACKAGE_MARKER = "REGIME_BULL_BEAR_SWITCH_ARCHIVE_SIBLING_EXPORTER_V1=true"
OWNER = "ops.regime_bull_bear_switch_archive_sibling_exporter_v1"
AUTHORITY_EFFECT = "NONE"
REGIME_AUTHORITY_EFFECT = "NONE"

TARGET_FILENAME = "regime_bull_bear_switch.v1.json"
TARGET_RELATIVE_PATH = f"readmodels/{TARGET_FILENAME}"
READMODELS_DIRNAME = "readmodels"

CONTRACT_NAME = "regime_bull_bear_switch.v1"
FAMILY_ID = "regime_bull_bear_switch"

ERROR_SOURCE_MISSING = "REGIME_BBS_ARCHIVE_SIBLING_SOURCE_MISSING"
ERROR_SOURCE_INVALID = "REGIME_BBS_ARCHIVE_SIBLING_SOURCE_INVALID"
ERROR_SOURCE_LOAD_FAILED = "REGIME_BBS_ARCHIVE_SIBLING_SOURCE_LOAD_FAILED"
ERROR_IDENTICAL_PATHS = "REGIME_BBS_ARCHIVE_SIBLING_IDENTICAL_SOURCE_TARGET"
ERROR_WRITE_FAILED = "REGIME_BBS_ARCHIVE_SIBLING_WRITE_FAILED"
ERROR_DIGEST_MISMATCH = "REGIME_BBS_ARCHIVE_SIBLING_DIGEST_MISMATCH"
ERROR_PATH_REQUIRED = "REGIME_BBS_ARCHIVE_SIBLING_PATH_REQUIRED"
ERROR_TARGET_CONFLICT = "REGIME_BBS_ARCHIVE_SIBLING_TARGET_CONFLICT"
ERROR_REPLAY_COMMIT_INCOMPLETE = "REGIME_BBS_ARCHIVE_SIBLING_REPLAY_COMMIT_INCOMPLETE"
ERROR_TRANSITION_IDENTITY_MISMATCH = "REGIME_BBS_ARCHIVE_SIBLING_TRANSITION_IDENTITY_MISMATCH"
ERROR_EVIDENCE_READMODEL_SHORTCUT_FORBIDDEN = (
    "REGIME_BBS_ARCHIVE_SIBLING_EVIDENCE_READMODEL_SHORTCUT_FORBIDDEN"
)
