"""Authority-bounded constants for B06 Cap 2.2 Peak_Trade economic ranking runtime."""

from __future__ import annotations

from src.ops.peak_trade_ranking_matrix_policy_v1 import (
    AMPLITUDE_POLICY_ID,
    AMPLITUDE_WEIGHT,
    ECONOMIC_RANK_STATE_N0,
    INPUT2_MAX_AGE_SECONDS,
    INPUT2_MAX_AGE_SECONDS_RATIFIED,
    ORDER_PRIMARY,
    ORDER_SECONDARY,
    ORDER_TERTIARY,
    POLICY_ID,
    POLICY_VERSION,
    PRODUCTIVE_ECONOMIC_RANK_ACTIVATION,
    SCORE_CONSTRUCTION,
    SINGLETON_AMPLITUDE_PERCENTILE,
    SINGLETON_BALANCED_MOVEMENT_SCORE,
    SINGLETON_CROSS_SECTION_STATE,
    SINGLETON_VOLATILITY_PERCENTILE,
    VOLATILITY_POLICY_ID,
    VOLATILITY_WEIGHT,
)

CAPABILITY_ID = "CAP22_PEAK_TRADE_RANKING_RUNTIME_V1"
RUNTIME_VERSION = "peak_trade_economic_ranking_runtime.v1"
OWNER_GO_THIS_SLICE = "PEAK_TRADE_B06_CAP22_PEAK_TRADE_RANKING_RUNTIME_V1"
BOUND_ORIGIN_MAIN_SHA = "6cf96b61361ad67ee5bbe434b9b47d27d75a990e"

B06_IMPLEMENTED = True
CAP22_PRODUCTIVE_ECONOMIC_RUNTIME_WIRED = True
ECONOMIC_RANK_ACTIVATED = True
# Distinct from ECONOMIC_RANK_ACTIVATED: Owner pin remains false until
# INPUT2_MAX_AGE_SECONDS is ratified (B03 §10).
PRODUCTIVE_ECONOMIC_RANK_ACTIVATION_PIN = PRODUCTIVE_ECONOMIC_RANK_ACTIVATION
RUNTIME_AUTHORIZATION_EFFECT = "NONE"
SELECTION_AUTHORITY_CREATED = False
BINDING_EFFECT = False
CAP23_SOLE_SELECTION_OWNER = True
CROSS_UNIVERSE_AUTHORITY = "NONE"
MULTI_FUTURE_RUNTIME_AUTHORIZED = False
MAX_POSITIONS_EFFECTIVE = 1
LIVE_EXTERNAL_EFFECT_AUTHORIZED = False

RANKING_POLICY_ID = POLICY_ID
RANKING_POLICY_VERSION = POLICY_VERSION
SCORE_CONSTRUCTION_ID = SCORE_CONSTRUCTION

ECONOMIC_RANK_STATE_S_STAR_N0 = ECONOMIC_RANK_STATE_N0
ECONOMIC_RANK_STATE_S_STAR_N1 = "S_STAR_N1"
ECONOMIC_RANK_STATE_S_STAR_N_GE_2 = "S_STAR_N_GE_2"

REASON_MISSING_FEATURE_SNAPSHOT = "ECONOMIC_FEATURE_PRODUCTION_SNAPSHOT_MISSING"
REASON_CORRUPT_FEATURE_SNAPSHOT = "ECONOMIC_FEATURE_PRODUCTION_SNAPSHOT_CORRUPT"
REASON_INCOMPLETE_FEATURE_CANDIDATE = "INCOMPLETE_FEATURE_CANDIDATE"
REASON_INVALID_FEATURE_CANDIDATE = "INVALID_FEATURE_CANDIDATE"
REASON_STRUCTURAL_NOT_ELIGIBLE = "STRUCTURAL_NOT_ELIGIBLE"
REASON_NO_COMPLETE_ECONOMIC_CANDIDATES = "NO_COMPLETE_ECONOMIC_CANDIDATES"

__all__ = [
    "AMPLITUDE_POLICY_ID",
    "AMPLITUDE_WEIGHT",
    "B06_IMPLEMENTED",
    "BOUND_ORIGIN_MAIN_SHA",
    "CAP22_PRODUCTIVE_ECONOMIC_RUNTIME_WIRED",
    "CAP23_SOLE_SELECTION_OWNER",
    "CAPABILITY_ID",
    "CROSS_UNIVERSE_AUTHORITY",
    "ECONOMIC_RANK_ACTIVATED",
    "ECONOMIC_RANK_STATE_S_STAR_N0",
    "ECONOMIC_RANK_STATE_S_STAR_N1",
    "ECONOMIC_RANK_STATE_S_STAR_N_GE_2",
    "INPUT2_MAX_AGE_SECONDS",
    "INPUT2_MAX_AGE_SECONDS_RATIFIED",
    "LIVE_EXTERNAL_EFFECT_AUTHORIZED",
    "MAX_POSITIONS_EFFECTIVE",
    "MULTI_FUTURE_RUNTIME_AUTHORIZED",
    "ORDER_PRIMARY",
    "ORDER_SECONDARY",
    "ORDER_TERTIARY",
    "OWNER_GO_THIS_SLICE",
    "PRODUCTIVE_ECONOMIC_RANK_ACTIVATION_PIN",
    "RANKING_POLICY_ID",
    "RANKING_POLICY_VERSION",
    "REASON_CORRUPT_FEATURE_SNAPSHOT",
    "REASON_INCOMPLETE_FEATURE_CANDIDATE",
    "REASON_INVALID_FEATURE_CANDIDATE",
    "REASON_MISSING_FEATURE_SNAPSHOT",
    "REASON_NO_COMPLETE_ECONOMIC_CANDIDATES",
    "REASON_STRUCTURAL_NOT_ELIGIBLE",
    "RUNTIME_AUTHORIZATION_EFFECT",
    "RUNTIME_VERSION",
    "SCORE_CONSTRUCTION_ID",
    "SELECTION_AUTHORITY_CREATED",
    "BINDING_EFFECT",
    "SINGLETON_AMPLITUDE_PERCENTILE",
    "SINGLETON_BALANCED_MOVEMENT_SCORE",
    "SINGLETON_CROSS_SECTION_STATE",
    "SINGLETON_VOLATILITY_PERCENTILE",
    "VOLATILITY_POLICY_ID",
    "VOLATILITY_WEIGHT",
]
