"""Constants for CAPABILITY_SAFETY_AUTHORITY_ARCHIVE_SIBLING_EXPORTER_V1.

AUTHORITY_EFFECT=NONE
TRADING_SEMANTIC_CHANGE=false
SAFETY_RECOMPUTE=false
KILLSWITCH_EVALUATION=false
AUTOMATIC_CALLER_ADDED=false
PRESENTATION_CHANGED=false
"""

from __future__ import annotations

CAPABILITY_ID = "CAPABILITY_SAFETY_AUTHORITY_ARCHIVE_SIBLING_EXPORTER_V1"
PACKAGE_MARKER = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_EXPORTER_V1=true"
OWNER = "ops.safety_authority_archive_sibling_exporter_v1"
AUTHORITY_EFFECT = "NONE"
SAFETY_AUTHORITY_EFFECT = "NONE"

TARGET_FILENAME = "safety_authority_fields.v1.json"
TARGET_RELATIVE_PATH = f"readmodels/{TARGET_FILENAME}"
READMODELS_DIRNAME = "readmodels"
CONTRACT_NAME = "safety_authority_fields_v1"

ERROR_SOURCE_MISSING = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_SOURCE_MISSING"
ERROR_SOURCE_CORRUPT = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_SOURCE_CORRUPT"
ERROR_SOURCE_INVALID = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_SOURCE_INVALID"
ERROR_SOURCE_LOAD_FAILED = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_SOURCE_LOAD_FAILED"
ERROR_IDENTICAL_PATHS = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_IDENTICAL_SOURCE_TARGET"
ERROR_WRITE_FAILED = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_WRITE_FAILED"
ERROR_DIGEST_MISMATCH = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_DIGEST_MISMATCH"
ERROR_PATH_REQUIRED = "SAFETY_AUTHORITY_ARCHIVE_SIBLING_PATH_REQUIRED"
ERROR_REPLAY_COMMIT_INCOMPLETE = "SAFETY_AUTHORITY_REPLAY_COMMIT_INCOMPLETE"
ERROR_DECISION_EVIDENCE_ABSENT = "SAFETY_AUTHORITY_DECISION_EVIDENCE_ABSENT"
ERROR_TYPED_REPLAY_SAFETY_ABSENT = "SAFETY_AUTHORITY_TYPED_REPLAY_SAFETY_ABSENT"
ERROR_KILLSWITCH_BOUNDARY_NOT_BOUND = "SAFETY_AUTHORITY_KILLSWITCH_BOUNDARY_NOT_BOUND"
